### ISSUE TITLE
Node 10.* on RHEL 7 is built with openssl 1.1

### ISSUE THREAD

**Issue by gcampax** [nodesource/distributions#1006]
RHEL 7 ships with openssl 1.0.* in the repos, but the node binary is linked to openssl 1.1.* (as per upstream recommendation). Furthermore, openssl symbols are not hidden from the node binary.
Unfortunately, this means that loading any system library that also uses openssl (and links to the system version of openssl) causes a crash. An example of this is [sqlcipher](https://github.com/sqlcipher/sqlcipher), through the popular [node-sqlite3](https://github.com/mapbox/node-sqlite3) addon.
Example backtrace:
```
#0  0x0000000001490386 in EVP_MD_CTX_clear_flags ()
#1  0x000000000147cc4e in EVP_DigestInit_ex ()
#2  0x000000000149b37a in HMAC_Init_ex ()
#3  0x00007f0a2c1eb989 in sqlcipher_openssl_hmac ()
```
Note the very low addresses for the openssl functions, as they come from the statically linked node binary, rather than the true openssl library libsqlcipher was compiled against.

A solution for this bug is to build node against the system version of openssl for RHEL 7. Note that RedHat is still supporting openssl 1.0.* on RHEL for a while, so this is not inherently insecure.
Alternatively, hiding all openssl symbols from the node binary with a linker script would help.

This is in fact the same issue as #768. It is a build issue though, not an upstream issue, so it needs to be fixed here.

**Comment by JesusPaz** [comment]
Thank you for contacting us. At this time at NodeSource, we do not have sufficient resources to handle this type of request. I will add a tag and close the issue for future review. Sorry for the inconvenience.
