### ISSUE TITLE
Please build Node 10 for Ubuntu 20.04 (Focal Fossa)

### ISSUE THREAD

**Issue by jbglaw** [nodesource/distributions#1007]
Hi!

A new Ubuntu release is emerging and it would be nice to have DEBs for it.

Thanks,
  Jan-Benedict

**Comment by jbglaw** [comment]
HI!

Just a notice: Up to now, I was using the Eoan DEBs for Focal, which broke some two weeks ago due to a dependency on python-minimal, which was separated in Focal into python2-minimal and python3-minimal. I guess it shouldn't be much of an issue to build the Focal DEBs.

Thanks a lot,
  Jan-Benedict

**Comment by igsu** [comment]
Hi @jbglaw 

Support for Ubuntu 20.04 Focal Fossa will begin when it has been officially released. This will be on April 23, 2020 if everything goes according to plans. 

Thank you for your patience!

N.B. the `python-minimal`/`python2-minimal` handling has been taken into account in our plans.

**Comment by SGmuwa** [comment]
You can try this: https://github.com/nodesource/distributions#snap

**Comment by jbglaw** [comment]
> You can try this: https://github.com/nodesource/distributions#snap

That's a good hint and quite useable for manual usage, but doesn't integrate too well into my Gitlab-based CI/CD setup for testing my stuff. So I'll just wait for it to happen until #1007 and #1013 are fully done.

(Actually I've never looked into Snap and I'm just considering to get me started with it to be able to play around with it. Good hint, thanks!)

**Comment by nhuisman** [comment]
Used this technique to install nodejs on my 20.04 docker 

##  Dockerfile
```
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN /usr/bin/apt-get update
RUN /usr/bin/apt-get upgrade -y
RUN /usr/bin/apt-get install -y wget curl pulseaudio xvfb firefox ffmpeg xdotool curl unzip nodejs

# INSTALL NODE HACK
COPY nodesource.sh /
RUN /nodesource.sh 
```
##  nodesource.sh
```
#!/bin/bash

set -xeo pipefail

wget https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/nodejs_12.16.1-1nodesource1_amd64.deb
dpkg-deb -R nodejs_12.16.1-1nodesource1_amd64.deb tmp
cd tmp
cat DEBIAN/control| sed -e 's/python-minimal/python2-minimal/g'|sed -e 's/nodesource1/nodesource2/g' > DEBIAN/control.tmp ; cat DEBIAN/control.tmp > DEBIAN/control ; rm DEBIAN/control.tmp
cd ..
dpkg-deb -b tmp nodejs_12.16.1-1nodesource2_amd64_new.deb 
apt install ./nodejs_12.16.1-1nodesource2_amd64_new.deb -y
```

**Comment by igsu** [comment]
Due to the high demand that `Ubuntu 20.04 Focal Fossa` has generated, it has been enabled for manual installation before its official release. [These steps](https://github.com/nodesource/distributions#manual-installation) should be enough.

If you attempt to install the packages with the scripts on pre-release distributions, you could face this issue:

```
## Your distribution, identified as "${DISTRO}", is a pre-release version of Ubuntu. 
NodeSource does not maintain official support for Ubuntu versions until they are 
formally released. You can try using the manual installation instructions available at 
https://github.com/nodesource/distributions and use the latest supported Ubuntu 
version name as the distribution identifier, although this is not guaranteed to work.
```

**Comment by darkdragon-001** [comment]
@igsu You should keep that practice for further releases as well! It is a win-win situation.

Think about it: People upgrading their operating system early are experienced software testers. Releasing early, you get valuable feedback without annoyed users (early adopters expect bugs) while still having time to fix these issues before the crowd will upgrade on/after the official release date!

**Comment by jbglaw** [comment]
> Due to the high demand that `Ubuntu 20.04 Focal Fossa` has generated, it has been enabled for manual installation before its official release. [These steps](https://github.com/nodesource/distributions#manual-installation) should be enough.

Seems it still depends on "python-minimal", which has been given up in favor of python{2,3}-minimal.

**Comment by igsu** [comment]
> > Due to the high demand that `Ubuntu 20.04 Focal Fossa` has generated, it has been enabled for manual installation before its official release. [These steps](https://github.com/nodesource/distributions#manual-installation) should be enough.
> 
> Seems it still depends on "python-minimal", which has been given up in favor of python{2,3}-minimal.

Please note that it depends on: 
libc6 (>= 2.17), libgcc1 (>= 1:3.4), libstdc++6 (>= 4.8), python2-minimal, ca-certificates

Just tested and got:
```
xxxxxxxxxx:/# add-apt-repository -y -r ppa:chris-lea/node.js
xxxxxxxxxx:/# rm -f /etc/apt/sources.list.d/chris-lea-node_js-*.list
xxxxxxxxxx:/# rm -f /etc/apt/sources.list.d/chris-lea-node_js-*.list.save
xxxxxxxxxx:/# curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK
xxxxxxxxxx:/# VERSION=node_13.x
xxxxxxxxxx:/# DISTRO="$(lsb_release -s -c)"
xxxxxxxxxx:/# echo "deb https://deb.nodesource.com/$VERSION $DISTRO main" | tee /etc/apt/sources.list.d/nodesource.list
deb https://deb.nodesource.com/node_13.x focal main
xxxxxxxxxx:/# echo "deb-src https://deb.nodesource.com/$VERSION $DISTRO main" | tee -a /etc/apt/sources.list.d/nodesource.list
deb-src https://deb.nodesource.com/node_13.x focal main
xxxxxxxxxx:/# apt-get update
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:2 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:3 https://deb.nodesource.com/node_13.x focal InRelease [4583 B]
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Get:5 https://deb.nodesource.com/node_13.x focal/main amd64 Packages [770 B]
Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:7 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [34.7 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:9 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1294 kB]
Fetched 12.9 MB in 4s (3397 kB/s)
Reading package lists... Done
xxxxxxxxxx:/# apt-get install nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 30 not upgraded.
Need to get 24.2 MB of archives.
After this operation, 117 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_13.x focal/main amd64 nodejs amd64 13.13.0-focal-1nodesource1 [24.2 MB]
Fetched 24.2 MB in 3s (8614 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package nodejs.
(Reading database ... 11634 files and directories currently installed.)
Preparing to unpack .../nodejs_13.13.0-focal-1nodesource1_amd64.deb ...
Unpacking nodejs (13.13.0-focal-1nodesource1) ...
Setting up nodejs (13.13.0-focal-1nodesource1) ...
xxxxxxxxxx:/# node -v
v13.13.0
```

**Comment by 616b2f** [comment]
I tried with 'https://deb.nodesource.com/setup_13.x' (in Ubuntu Focal 20.04) it didn't work for me.
What did work was using 'https://deb.nodesource.com/node_13.x'. In the README.md it's still 'setup_13.x' should we update it or did I miss hier something?

Also it would be nice to see hat Focal is supported in the README file.

Thank you for adding it before the official release!

**Comment by LuisAlejandro** [comment]
Hi, this change has been made correctly for Ubuntu Focal but not for Debian Sid, which has the same problem for being its parent distribution. Please make the change there too.
