### ISSUE TITLE
NodeJS 13.8.0 not available for download

### ISSUE THREAD

**Issue by pedrofurtado** [nodesource/distributions#1009]
NodeJS 13.8.0 was released ( https://github.com/nodejs/node/releases/tag/v13.8.0 ), but is not available yet in URL:

https://rpm.nodesource.com/pub_13.x/el/7/x86_64/nodejs-13.8.0-1nodesource.x86_64.rpm

👍 🤝

**Comment by igsu** [comment]
It is available now!
Please confirm.

**Comment by pedrofurtado** [comment]
@igsu it works 🎸
