### ISSUE TITLE
not able to install node and npm in Linux 7

### ISSUE THREAD

**Issue by paramacharya** [nodesource/distributions#1010]
I am under corporate proxy and I am not able to install node and npm in Linux 7
My OS-release:
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
 please suggest me.
gajulapavans@gmail.com

**Comment by igsu** [comment]
Similar issues with installations on subsystems and behind proxies: #1002 #947 #904 and many more.

It's not a problem related to distributions or compatibility, but to the network setup.

**Comment by mhedden** [comment]
Hi @paramacharya ,

Please see [my response to a similar thread](https://github.com/nodesource/distributions/issues/904#issuecomment-594181237) about how I was able to get node to install correctly behind corporate proxy.
