### ISSUE TITLE
Your distribution, identified as "juniper", is not currently supported

### ISSUE THREAD

**Issue by fcddk** [nodesource/distributions#1011]
Linux master1 4.4.58-20180615.kylin.server.YUN+-generic #kylin SMP Tue Jul 10 14:55:31 CST 2018 aarch64 aarch64 aarch64 GNU/Linux

**Comment by igsu** [comment]
Hey @fcddk,

We, unfortunately, do not have the resources necessary to support and test the plethora of Linux releases in the wild, so we rely on community members such as yourself to get support on your favorite distributions.

I've added Kylin to the list of requested releases in our [README.md](https://github.com/nodesource/distributions#requested-distributions).

**Comment by youngquan** [comment]
Hi, @igsu, is there a toturial or description or something else for me to add this distribution "juniper" ?
