### ISSUE TITLE
Your distribution, identified as "LinDoz", is not currently supported

### ISSUE THREAD

**Issue by LouieTian0209** [nodesource/distributions#1012]
Running latest MakuluLinux testing build based on Ubuntu (http://makululinux.online/downloads/MakuluLinux-LinDoz-x64-Stable-2020-02-10.iso). Please add "LinDoz" to supported distro list, thanks a lot.

**Comment by igsu** [comment]
Hey @LouieTian0209,

We, unfortunately, do not have the resources necessary to support and test the plethora of Linux releases in the wild, so we rely on community members such as yourself to get support on your favorite distributions.

I've added MakuluLinux to the list of requested releases in our [README.md](https://github.com/nodesource/distributions#requested-distributions).
