### ISSUE TITLE
Remove hard Python 2 dependency

### ISSUE THREAD

**Issue by nazar-pc** [nodesource/distributions#1013]
All modern and not so modern distros should have Python 3 installed and gyp should support that since a while ago.
Can you, please, stop depending on Python 2 exclusively?

I'm on Ubuntu 20.04 and nodejs is one of just 2 packages that depend on legacy python-minimal. At least making either python-minimal or python3-minimal as a requirement would be useful and allow legacy package to be removed from my system.

**Comment by igsu** [comment]
For future distributions such as Ubuntu 20.04 Focal Fossa we are taking into account the management of this dependency. In fact, we are already doing it for CentOS 8 and Fedora 31.

Please note that Ubuntu 20.04 has not been officially released, only when that happens the support will begin.

[See comment.](https://github.com/nodesource/distributions/issues/1007#issuecomment-589652057)

**Comment by yomguy** [comment]
Hi @igsu, please do it also for the Debian package.

**Comment by nazar-pc** [comment]
Less than 2 weeks to Ubuntu 20.04 release, nothing significant is going to change by then.

**Comment by igsu** [comment]
[Please check](https://github.com/nodesource/distributions/issues/1007#issuecomment-612959889).

**Comment by Congee** [comment]
> 
> 
> [Please check](https://github.com/nodesource/distributions/issues/1007#issuecomment-612959889).

but, that thread does not provide a solution of removing python2 dependency 😕

**Comment by mattboston** [comment]
I'm having the same issue on CentOS 8 with NodeJS 10.x.  CentOS 8 already has Python 3, we should not be installing Python 2.x for anything.  When will there be a fix?

```
[root@test ~]# yum install nodejs
Last metadata expiration check: 0:02:23 ago on Tue 16 Jun 2020 10:58:46 AM EDT.
Dependencies resolved.
==========================================================================================================================================================
 Package                              Architecture       Version                                              Repository                             Size
==========================================================================================================================================================
Installing:
 nodejs                               x86_64             2:10.21.0-1nodesource                                nodesource                             20 M
Installing dependencies:
 python2                              x86_64             2.7.17-1.module_el8.2.0+381+9a5b3c3b                 centos8-appstream             108 k
 python2-libs                         x86_64             2.7.17-1.module_el8.2.0+381+9a5b3c3b                 centos8-appstream             6.0 M
 python2-pip-wheel                    noarch             9.0.3-16.module_el8.2.0+381+9a5b3c3b                 centos8-appstream             1.2 M
 python2-setuptools-wheel             noarch             39.0.1-11.module_el8.2.0+381+9a5b3c3b                centos8-appstream             289 k

Transaction Summary
==========================================================================================================================================================
Install  5 Packages

Total download size: 28 M
Installed size: 87 M
Is this ok [y/N]: n
Operation aborted.
`
