### ISSUE TITLE
Switch to APT on debian based systems 

### ISSUE THREAD

**Issue by lucsoft** [nodesource/distributions#1014]
use the new version of apt-get. apt!

**Comment by SuperSandro2000** [comment]
https://itsfoss.com/apt-vs-apt-get-difference/

Does not matter, apt-get is not deprecated and should be preferred in scripts.

**Comment by lucsoft** [comment]
of course it won't get deprecated quickly, but we should use apt more

its more simpler and friendlier for the user

**Comment by SuperSandro2000** [comment]
> of course it won't get deprecated quickly
It will not get deprecated anytime in the near future.
> but we should use apt more
if you are an end user you can use it. It has some more convenience features for you.
> its more simpler and friendlier for the user
for the end user. for headless environment apt-get is preferred. Also apt is missing a lot of the low level stuff a developer might need to use.

**Comment by igsu** [comment]
@lucsoft there is no reason in the short or long term to prefer `apt` over `apt-get` in scripting. Also, there are no plans to deprecate `apt-get`. If this becomes required, the migration will be done. 

Thanks for the recommendation! It will be an issue that we will consider in the future.
