### ISSUE TITLE
Your distribution, identified as "n/a",

### ISSUE THREAD

**Issue by leonardevans** [nodesource/distributions#1018]
Your distribution, identified as "n/a", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by SuperSandro2000** [comment]
Which distribution are you using?

**Comment by Sephi-Chan** [comment]
Same problem here. Don't know why I don't have a codename… :( 

root@sd-118782:~/# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.12 (n/a)
Release:	9.12
Codename:	n/a

**Comment by muhammadb-786** [comment]
apt-get install lsb-release, Even i have installed release with apt-get install lsb-release but still getting the error but i am checking release with command 
root@------:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.2
Codename:	n/a

Any help to resolve the issue will be apprecaied.
