### ISSUE TITLE
Drop older Fedora versions

### ISSUE THREAD

**Issue by afranke** [nodesource/distributions#1019]
The only currently supported versions of Fedora are 30 and 31 (and soon 32). Nobody should keep using 29, 28 and certainly not 27. They should be dropped.

**Comment by afranke** [comment]
Once that’s done, #812 can be closed as obsolete.

**Comment by igsu** [comment]
As of #1022, we updated the documentation. We also updated our build process to avoid continuing to ship these EOL distros. 

Thank you very much for pointing this out, really appreciate it @afranke.
