### ISSUE TITLE
iojs armhf debian packages still vulnerable

### ISSUE THREAD

**Issue by mvduin** [nodesource/distributions#102]
While updated packages are available for i386 and amd64, the latest iojs armhf debian packages in the repositories are currently still 1.8.1 and 2.3.1 (regardless of distro). These are still [vulnerable to the V8 UTF-8 bug](https://medium.com/node-js-javascript/important-security-upgrades-for-node-js-and-io-js-8ac14ece5852). Needless to say, updated packages for armhf are urgently desirable.

**Comment by rvagg** [comment]
@chrislea these are built and deployed now aren't they?

**Comment by chrislea** [comment]
iojs 1.8.4 is in the repos. iojs 2.3.4 is still currently compiling as I type this, and I'll push them in once the builds are done. That should be late tonight my time (Pacific) or first thing in the morning.

**Comment by chrislea** [comment]
And as of now, everything for arm is updated to current.
