### ISSUE TITLE
Stop recommending yum for Fedora

### ISSUE THREAD

**Issue by afranke** [nodesource/distributions#1020]
dnf has been present on Fedora since version 18 and the default (replacing yum) since 22 (released **5 years ago**). RHEL still uses yum though.

Please stop recommending `yum` and switch to `dnf` for Fedora.

**Comment by igsu** [comment]
Hi @afranke, thanks for your recommendation. Despite the fact that `dnf` is the default tool, our packaging system will continue to rely on `yum`, which is valid and has no plans to be deprecated. Closing this now.
