### ISSUE TITLE
our distribution, identified as "redhat-release-server-7.7-10.0.1.el7.x86_64", is not currently supported,

### ISSUE THREAD

**Issue by bijendrab** [nodesource/distributions#1025]
Trying to install nodejs
Set the proxy 

curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -

================================================================================
================================================================================

                              DEPRECATION WARNING

  Node.js 8.x LTS Carbon is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_10.x — Node.js v10 LTS "Dubnium" (recommended)
   * https://deb.nodesource.com/setup_12.x — Node.js v12 LTS "Erbium"

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.

  The NodeSource Node.js distributions repository contains
  information both about supported versions of Node.js and supported Linux
  distributions. To learn more about usage, see the repository:
    https://github.com/nodesource/distributions

================================================================================
================================================================================

Continuing in 20 seconds ...

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

**Comment by igsu** [comment]
Similar issues with installations on subsystems and behind proxies: #1002 #947 #904 and many more.

It's not a problem related to distributions or compatibility, but to the proxy setup.

Check @mhedden [comment](https://github.com/nodesource/distributions/issues/904#issuecomment-594181237) for more guidance on this issue.

**Comment by be4ndr** [comment]
I was able to add a repository with following command
`curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -`
