### ISSUE TITLE
No man page for npm on Debian 10

### ISSUE THREAD

**Issue by MikHulk** [nodesource/distributions#1029]
Hi,

I have installed node from nodesource on Debian 10. 

I have man page for node. But I don't have man page for NPM. How can I install them ?

Thx

**Comment by igsu** [comment]
Hi @MikHulk, this is probably not the best place for that issue, as only packaging and distribution are performed here. [This may be](https://github.com/npm/npm/issues) a better place to answer your question.

Closing this now.

**Comment by MikHulk** [comment]
Hi thank you. Actually the man pages are installed after a npm update:
```
pm install -g npm
```
