### ISSUE TITLE
IPv6 not available (deb.nodesource.com)

### ISSUE THREAD

**Issue by Saiv46** [nodesource/distributions#1030]
deb.nodesource.com has no AAAA records

**Comment by igsu** [comment]
I just validated our IPv6 accessibility and it looks good, can you check at your end and confirm that this is still an issue?

<img width="579" alt="Screen Shot 2020-03-30 at 8 41 05 AM" src="https://user-images.githubusercontent.com/25617909/77919026-4b112e00-7262-11ea-9342-732ddbef02c9.png">
<img width="597" alt="Screen Shot 2020-03-30 at 8 41 24 AM" src="https://user-images.githubusercontent.com/25617909/77919030-4cdaf180-7262-11ea-9eeb-399649b4fefd.png">

**Comment by Saiv46** [comment]
Yeah, everything works now
