### ISSUE TITLE
focal fossa nodejs packages

### ISSUE THREAD

**Issue by dg14** [nodesource/distributions#1031]
it's impossible to install nodejs into focal fossa using packages from eoan. it reports an error saying that python-minimal is not installable.

(probably it's better to use python2-minimal as dependency).

**Comment by SGmuwa** [comment]
https://github.com/nodesource/distributions/issues/1007
https://github.com/nodesource/distributions/issues/1013

**Comment by igsu** [comment]
Hi @dg14, find more information in the issues mentioned by @SGmuwa.

> #1007
> #1013

**Comment by dg14** [comment]
>Support for Ubuntu 20.04 Focal Fossa will begin when it has been officially released. This will be >on April 23, 2020 if everything goes according to plans.
>Thank you for your patience!
>N.B. the python-minimal/python2-minimal handling has been taken into account in our plans.
>Support for Ubuntu 20.04 Focal Fossa will begin when it has been officially released. This will be 
>on April 23, 2020 if everything goes according to plans.
> Thank you for your patience!
> N.B. the python-minimal/python2-minimal handling has been taken into account in our plans.

hi @igsu, the creation of fossa packages from  is very simple, you have to change python-minimal in python2-minimal, in DEBIAN/control.

if someone want to try: 

```
#!/bin/bash
dpkg-deb -R nodejs_12.16.1-1nodesource1_amd64.deb tmp
cd tmp
cat DEBIAN/control| sed -e 's/python-minimal/python2-minimal/g'|sed -e 's/nodesource1/nodesource2/g' > DEBIAN/control.tmp ; cat DEBIAN/control.tmp > DEBIAN/control ; rm DEBIAN/control.tmp
cd ..
dpkg-deb -b tmp nodejs_12.16.1-1nodesource2_amd64.deb 
```

**Comment by nhuisman** [comment]
> > Support for Ubuntu 20.04 Focal Fossa will begin when it has been officially released. This will be >on April 23, 2020 if everything goes according to plans.
> > Thank you for your patience!
> > N.B. the python-minimal/python2-minimal handling has been taken into account in our plans.
> > Support for Ubuntu 20.04 Focal Fossa will begin when it has been officially released. This will be
> > on April 23, 2020 if everything goes according to plans.
> > Thank you for your patience!
> > N.B. the python-minimal/python2-minimal handling has been taken into account in our plans.
> 
> hi @igsu, the creation of fossa packages from is very simple, you have to change python-minimal in python2-minimal, in DEBIAN/control.
> 
> if someone want to try:
> 
> ```
> #!/bin/bash
> dpkg-deb -R nodejs_12.16.1-1nodesource1_amd64.deb tmp
> cd tmp
> cat DEBIAN/control| sed -e 's/python-minimal/python2-minimal/g'|sed -e 's/nodesource1/nodesource2/g' > DEBIAN/control.tmp ; cat DEBIAN/control.tmp > DEBIAN/control ; rm DEBIAN/control.tmp
> cd ..
> dpkg-deb -b tmp nodejs_12.16.1-1nodesource2_amd64.deb 
> ```

Used this technique to install nodejs on my 20.04 docker 

---  Dockerfile
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN /usr/bin/apt-get update
RUN /usr/bin/apt-get upgrade -y
RUN /usr/bin/apt-get install -y wget curl pulseaudio xvfb firefox ffmpeg xdotool curl unzip nodejs

# INSTALL NODE HACK
COPY nodesource.sh /
RUN /nodesource.sh 

---  nodesource.sh
#!/bin/bash

set -xeo pipefail

wget https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/nodejs_12.16.1-1nodesource1_amd64.deb
dpkg-deb -R nodejs_12.16.1-1nodesource1_amd64.deb tmp
cd tmp
cat DEBIAN/control| sed -e 's/python-minimal/python2-minimal/g'|sed -e 's/nodesource1/nodesource2/g' > DEBIAN/control.tmp ; cat DEBIAN/control.tmp > DEBIAN/control ; rm DEBIAN/control.tmp
cd ..
dpkg-deb -b tmp nodejs_12.16.1-1nodesource2_amd64_new.deb 
apt install ./nodejs_12.16.1-1nodesource2_amd64_new.deb -y

**Comment by dg14** [comment]
Why dont they release also source packages? Doing a sha256sum of binaries,
they are the same as nodejs.org ones.

Il dom 12 apr 2020, 14:54 Nathan Huisman <notifications@github.com> ha
scritto:

**Comment by igsu** [comment]
[Please check](https://github.com/nodesource/distributions/issues/1007#issuecomment-612959889).
