### ISSUE TITLE
Your distribution, identified as "Ubuntu Focal Fossa (development branch)", is a pre-release version of Ubuntu.

### ISSUE THREAD

**Issue by ankuragarwal18** [nodesource/distributions#1036]
## Your distribution, identified as "Ubuntu Focal Fossa (development branch)", is a pre-release version of Ubuntu. NodeSource does not maintain official support for Ubuntu versions until they are formally released. You can try using the manual installation instructions available at https://github.com/nodesource/distributions and use the latest supported Ubuntu version name as the distribution identifier, although this is not guaranteed to work.

When can we expect nodejs official support on Focal Fossa (ubuntu 20.04)?

**Comment by igsu** [comment]
Duplicated #1007. 
[Please check](https://github.com/nodesource/distributions/issues/1007#issuecomment-612959889).
