### ISSUE TITLE
Create a continuously upgrade LTS installation

### ISSUE THREAD

**Issue by brunoalmeida-fairtiq** [nodesource/distributions#1037]
I ask, for all distributions you support, to provide a deb with the latest LTS available.
Currently, the LTS version is 12 but that will change later on to version 14 when it comes out.
The idea is that repository will always have the latest LTS version available.
How feasible is that?

**Comment by igsu** [comment]
As mentioned in the [comment](https://github.com/nodesource/distributions/issues/1064#issuecomment-652392899), we will work on this in the near future.

**Comment by brunoalmeida-fairtiq** [comment]
@igsu I closed because it's being addressed.

**Comment by igsu** [comment]
Reopened to keep track of the progress.

**Comment by igsu** [comment]
As of #1083 we provide two new scripts for the installation of the `LTS` and `Current` versions. They have been documented in the installation instructions.
