### ISSUE TITLE
 Your distribution, identified as "focal", is not currently supported

### ISSUE THREAD

**Issue by ceciliazcx** [nodesource/distributions#1044]
I got ` Your distribution, identified as "focal", is not currently supported` in my dockerfile when deploy to Azure.
The detail error is as following, could I know how to fix it?

```## Populating apt-get cache...
+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists...
## Installing packages required for setup: lsb-release gnupg...
+ apt-get install -y lsb-release gnupg > /dev/null 2>&1
## Confirming "focal" is supported...
+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_11.x/dists/focal/Release'
## Your distribution, identified as "focal", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support```

**Comment by siquick** [comment]
@ceciliazcx 

I had `FROM ubuntu:latest` in my Dockerfile which was causing the above error.

Changing it to `FROM ubuntu:16.04` fixed it so I presume its an incompatibility issue with Ubuntu 20

**Comment by igsu** [comment]
Scripts are set to support Ubuntu 20.04, @ceciliazcx please confirm this is still an issue.

**Comment by paulmillr** [comment]
@igsu still happens

**Comment by mateuszbrycki** [comment]
I see a similar issue with `https://deb.nodesource.com/setup_12.x`:

> ## Your distribution, identified as "Ubuntu Focal Fossa (development branch)", is a pre-release version of Ubuntu. NodeSource does not maintain official support for Ubuntu versions until they are formally released. You can try using the manual installation instructions available at https://github.com/nodesource/distributions and use the latest supported Ubuntu version name as the distribution identifier, although this is not guaranteed to work.

**Comment by bryanlatten** [comment]
@mateuszbrycki @paulmillr check that you aren't (somehow) using a development version of Ubuntu. The script is looking specifically for the words "development" in the name of the OS release. You can check this yourself with the `lsb_release` tool (`apt install lsb-release` if its missing).

Successful (working) example:

```
root@4a452b8c2aba:/# lsb_release -d -s
Ubuntu 20.04 LTS
```

**Comment by paulmillr** [comment]
@bryanlatten yeah it's not development, it's lts

**Comment by igsu** [comment]
@ceciliazcx please note that the Node version that you are trying to install is deprecated:
```
curl -sLf -o /dev/null 'https://deb.nodesource.com/node_11.x/dists/focal/Release'
```
Please try again with the currently supported versions: 10, 12, 13 and 14.

**Comment by paulmillr** [comment]
@igsu i'm trying v14 btw

**Comment by igsu** [comment]
@paulmillr I am getting a similar result with v14:
```
...
Setting up nodejs (14.2.0-deb-1nodesource1) ...
...
xxxxx:/# node -v
v14.2.0
xxxxx:/# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```
Please provide more information about your environment or any custom network setup (some users experience this issue when they are behind a proxy #904 - [see comment](https://github.com/nodesource/distributions/issues/904#issuecomment-547278260))

**Comment by paulmillr** [comment]
yup, using socks proxy. apt-get still works though.

**Comment by igsu** [comment]
@paulmillr check [this comment](https://github.com/nodesource/distributions/issues/810#issuecomment-483041398).

**Comment by paulmillr** [comment]
@igsu the issue is not "using proxies". It's useless error. If proxies aren't supported, nodesource should communicate this.

**Comment by betancour** [comment]
Errors while trying to register the repo for 12.x

```bash
## Installing the NodeSource Node.js 12.x repo...
## Populating apt-get cache...
+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [107 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease [98.3 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [119 kB]
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [56.1 kB]
Fetched 487 kB in 16s (30.2 kB/s)
Reading package lists... Done
## Confirming "focal" is supported...
+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_12.x/dists/focal/Release'
## Adding the NodeSource signing key to your keyring...
+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
gpg: can't connect to the agent: IPC connect call failed
Error executing command, exiting
```

**Comment by igsu** [comment]
@paulmillr you can check our FAQ, that is the first question there:

https://github.com/nodesource/distributions#faq

**Comment by jb892** [comment]
I removed `-E` flag and it works now.
eg:
```
sudo curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
```

**Comment by thamaraiselvam** [comment]
Facing same issue for installing nodejs 9.x on ubuntu 20.04

```
## Confirming "focal" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_9.x/dists/focal/Release'

## Your distribution, identified as "focal", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by raguri** [comment]
> Scripts are set to support Ubuntu 20.04, @ceciliazcx please confirm this is still an issue.

@igsu, I got Your distribution, identified as "focal", is not currently supported in my dockerfile.
 Have tried all the suggested approaches here to fix the focal issue like changed Ubuntu version to 16.04, 20.04 and node versions changed to 12, 14. Before running the script,  have installed lsb-release pkgs. still couldn't helped me to fix the issue.
Can you please suggest, if there is any workaround.

**Comment by igsu** [comment]
@raguri you can always use the manual installation steps: https://github.com/nodesource/distributions#manual-installation

**Comment by williamstein** [comment]
I was able to cleanly reproduce this today using Docker by doing:
```sh
sudo docker run -it ubuntu:20.04 bash
```
then pasting the following (note http instead of https):
```sh
apt-get update \
  && apt-get install -qy --no-install-recommends curl \
  && curl -sL http://deb.nodesource.com/setup_14.x | bash - \
  && apt-get install -y nodejs
```

The problem is that node's script does this:
```sh
## Installing packages required for setup: lsb-release gnupg...

+ apt-get install -y lsb-release gnupg > /dev/null 2>&1
```
and those two packages are **not** sufficient currently to install node.

The right solution in my case was to install the ` ca-certificates ` Ubuntu package.  Then `http://deb.nodesource.com/setup_14.x` worked, and the "Your distribution, identified as "focal", is not currently supported" error was no longer triggered.

I'm not sure this issue should be re-opened, but perhaps the above comment will be useful to somebody.

**Comment by nguyenhuy07** [comment]
> I was able to cleanly reproduce this today using Docker by doing:
> 
> ```shell
> sudo docker run -it ubuntu:20.04 bash
> ```
> 
> then pasting the following (note http instead of https):
> 
> ```shell
> apt-get update \
>   && apt-get install -qy --no-install-recommends curl \
>   && curl -sL http://deb.nodesource.com/setup_14.x | bash - \
>   && apt-get install -y nodejs
> ```
> 
> The problem is that node's script does this:
> 
> ```shell
> ## Installing packages required for setup: lsb-release gnupg...
> 
> + apt-get install -y lsb-release gnupg > /dev/null 2>&1
> ```
> 
> and those two packages are **not** sufficient currently to install node.
> 
> The right solution in my case was to install the `ca-certificates` Ubuntu package. Then `http://deb.nodesource.com/setup_14.x` worked, and the "Your distribution, identified as "focal", is not currently supported" error was no longer triggered.
> 
> I'm not sure this issue should be re-opened, but perhaps the above comment will be useful to somebody.

cool! it worked for me!

**Comment by raguri** [comment]
> I was able to cleanly reproduce this today using Docker by doing:
> 
> ```shell
> sudo docker run -it ubuntu:20.04 bash
> ```
> 
> then pasting the following (note http instead of https):
> 
> ```shell
> apt-get update \
>   && apt-get install -qy --no-install-recommends curl \
>   && curl -sL http://deb.nodesource.com/setup_14.x | bash - \
>   && apt-get install -y nodejs
> ```
> 
> The problem is that node's script does this:
> 
> ```shell
> ## Installing packages required for setup: lsb-release gnupg...
> 
> + apt-get install -y lsb-release gnupg > /dev/null 2>&1
> ```
> 
> and those two packages are **not** sufficient currently to install node.
> 
> The right solution in my case was to install the `ca-certificates` Ubuntu package. Then `http://deb.nodesource.com/setup_14.x` worked, and the "Your distribution, identified as "focal", is not currently supported" error was no longer triggered.
> 
> I'm not sure this issue should be re-opened, but perhaps the above comment will be useful to somebody.

I have followed the same approach. It worked for me too.
But I too felt still an issue with node scripts that need to support Ubuntu 20.04.

**Comment by shaangontia** [comment]
I am using 

```
$ lsb_release -d -s
Ubuntu 20.04.3 LTS
```

and when I try running the command 

```
curl -fksSL https://deb.nodesource.com/setup_lts.x | sudo bash -
```

I am getting the error

## Confirming "focal" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/focal/Release'

## Your distribution, identified as "focal", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

I think the issue with focal still exists. Any knows a permanent solution to this?

**Comment by Dusayanta** [comment]
It is actually a certificate issue. I made it working by ignoring the certificate checks. I know its not a good thing to do.
This is how I ignored the cert checks - 
`
RUN echo insecure > ~/.curlrc && \
echo 'Acquire::https::deb.nodesource.com::Verify-Peer "false";' > /etc/apt/apt.conf.d/80ssl-exceptions && \
echo 'Acquire::https::deb.nodesource.com::Verify-Host "false";' >> /etc/apt/apt.conf.d/80ssl-exceptions

RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - && \
apt install -y nodejs
`
