### ISSUE TITLE
Remove hard Python 2 dependency

### ISSUE THREAD

**Issue by pratikborsadiya** [nodesource/distributions#1045]
There is still a dependency on `python2-minimal` package for node 12.x on Ubuntu 20.04. [Link](https://deb.nodesource.com/node_12.x/dists/focal/main/binary-amd64/Packages)

#1013 was closed that's why this new issue is created.

**Comment by makoven** [comment]
I feel your pain, bro. Sad situation. The original package in deb distros of a very old version (10.x). And one and only third-party maintainer with the proud inscription  "**modern digital era**" on its the main page is too lazy to separate packages by node and npm and get rid of python2.

In fact, the node is not dependent on npm. For production npm it's just too much crap (not to mention python2)

Fortunately, you can still set up a node 14.x without python2:

1. Download deb package from https://deb.nodesource.com/node_14.x/pool/main/n/nodejs/
2. sudo dpkg --force-all -i path_to_deb_file

**Comment by makoven** [comment]
@pratikborsadiya and if you need only node, without npm, you can unpack the deb file, pull out single file (data.tar.xz/usr/bin/node) and distribute it with your project. This file contains all node API inside
