### ISSUE TITLE
Warning: apt-key output should not be parsed (stdout is not a terminal)

### ISSUE THREAD

**Issue by LinqLover** [nodesource/distributions#1047]
When installing node in my Dockerfile using:

```bash
curl -sL https://deb.nodesource.com/setup_12.x | bash -
```

Then I receive the following warning multiple times:

> Warning: apt-key output should not be parsed (stdout is not a terminal)

See the following places in the `setup` script:

- https://github.com/nodesource/distributions/blob/ce7f535a7bd9f0a684a388e358a61068888754c0/deb/setup#L304-L308
- https://github.com/nodesource/distributions/blob/ce7f535a7bd9f0a684a388e358a61068888754c0/deb/setup#L323

I did some research on the warning and it appears as if it is raised because the gpg keys could deprecate. However, all cited code fragments fetch these keys dynamically, so I think it would be okay to ignore the warnings.

Can we set `APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1` during each single `apt-get add` operation? It would be nice get rid of these warnings in so many Dockerfiles.

**Comment by nmccready** [comment]
Having the same problem and would love an answer to this.

**Comment by henz90** [comment]
Would love to know how to fix this, I too have the same issue

**Comment by OlafStyle** [comment]
Same...

**Comment by AkashicSeer** [comment]
So I am guessing the only fix to  this is to use a functioning OS other than Ubuntu... GOT IT THANKS.
![flippin sweet](https://user-images.githubusercontent.com/45157506/104126603-8c735580-532b-11eb-9aa5-f85a46029fd1.jpeg)

**Comment by JesusPaz** [comment]
This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).
