### ISSUE TITLE
cannot execute binary file

### ISSUE THREAD

**Issue by VTsuprov** [nodesource/distributions#1048]
Raspberry pi 3b. Debian Buster as root
curl -sL https://deb.nodesource.com/setup_14.x | bash -
apt-get install -y nodejs
/usr/bin/apt-get: /usr/bin/apt-get: cannot execute binary file

**Comment by igsu** [comment]
The issue is not related to the packages distributed here @VTsuprov. Find more info about the issue [here](http://forums.debian.net/viewtopic.php?f=30&t=137639).

**Comment by VTsuprov** [comment]
thanks a lot. The problem was smthg went wrong with the Sources List. I found the solution here https://debgen.simplylinux.ch/index.php?generate
