### ISSUE TITLE
[snap] Snap node doesn't define any default track

### ISSUE THREAD

**Issue by fcole90** [nodesource/distributions#1052]
Node snap has no default track defined, so when attempting `sudo snap install node --classic` it fails with the following error message:

```
$ sudo snap install node
error: snap "node" is not available on stable but is available to install on
       the following channels:

       edge snap install --edge node

       Please be mindful pre-release channels may include features not
       completely tested or implemented. Get more information with 'snap info
       node'.
```

One could then use `snap info node` (as suggested) but I think that's a bad experience not having a default

Related issues:
Node snap: https://snapcraft.io/node
Related issue on store: https://github.com/canonical-web-and-design/snapcraft.io/issues/2764
Related issue on backend: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1879374

**Comment by igsu** [comment]
We are not responsible for maintaining the Snap packages, to solve any issue or more information:

https://github.com/nodejs/snap
