### ISSUE TITLE
Snap node cannot read output of another node process

### ISSUE THREAD

**Issue by angryziber** [nodesource/distributions#1053]
When node is installed via snap (14/stable channel).

`execSync('node something').toString()` always returns an empty string with no errors.
This is a problem as many transforming packages use this trick to deasync processing.

`execSync('node something', {stdio: 'inherit'}).toString()`
would correctly display the output in parent process's stdout, but there is no way of capturring it.

If node is installed via deb package, there is no such problem.

Makes jest/etc unusable in many cases.

**Comment by igsu** [comment]
We are not responsible for maintaining the Snap packages, to solve any issue or more information:

https://github.com/nodejs/snap
