### ISSUE TITLE
Unable to install Yarn

### ISSUE THREAD

**Issue by aryancs07** [nodesource/distributions#1056]
sudo apt update && sudo apt install yarn
Hit:1 https://dl.yarnpkg.com/debian stable InRelease                           
Hit:2 http://dl.google.com/linux/chrome/deb stable InRelease                   
Ign:3 http://ppa.launchpad.net/chris-lea/node.js/ubuntu bionic InRelease       
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]    
Hit:5 https://packages.microsoft.com/ubuntu/19.04/prod disco InRelease         
Err:6 http://ppa.launchpad.net/chris-lea/node.js/ubuntu bionic Release         
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
Hit:7 http://us.archive.ubuntu.com/ubuntu bionic InRelease                     
Get:8 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Reading package lists... Done                                                  
E: The repository 'http://ppa.launchpad.net/chris-lea/node.js/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by igsu** [comment]
This issue is not related to packages distributed in this repository. [Check this](https://github.com/yarnpkg/yarn/issues).
