### ISSUE TITLE
Where is the debian source folder package ?

### ISSUE THREAD

**Issue by GMLudo** [nodesource/distributions#1059]
Hi,

I'm looking for the debian source folder to regenerate the NodeJS package, because I have a dependency problem with the actual package provided by NodeSource, not present in the actual deb package provided by Ubuntu.

I don't find a folder like this in this repository: https://salsa.debian.org/js-team/nodejs/-/tree/master/debian

Could you point me where it is ?

Thanks

**Comment by igsu** [comment]
Hi @GMLudo,

It is not publicly available but you can always get the source folder by yourself:

```
ar p $deb control.tar.gz | tar -xz
# Manipulate control source
tar czf control.tar.gz control
ar r $deb control.tar.gz
```
