### ISSUE TITLE
Vzlinux / OpenVZ

### ISSUE THREAD

**Issue by Xaekai** [nodesource/distributions#1060]
Any chances you guys could add support for this?

It wouldn't be any extra packaging work, just a matter of correct detection. For all intents and purposes, the userland of OVZ7 is CentOS 7. And OVZ8 will be CentOS 8.

**Comment by JesusPaz** [comment]
Unfortunately, we do not plan to support VzLinux at this time, but it has been added to our list of requested distributions #1327.

When your distribution is not supported you can install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).

You can also help us to support this distribution, here are some examples of pull request #1231 #1195. If you have any problems let us know.
