### ISSUE TITLE
Cannot install on XCP-ng Server (Centos8 base)

### ISSUE THREAD

**Issue by lambepa** [nodesource/distributions#1061]
Hello,
I am trying to deploy XenOrchestra manually and I cannot install NodeJS12 as it is needed;
Server:  XCP-ng release 8.1.0 (xenenterprise)
Using the script I get an error:
[19:59 synnefoxcpng XenOrchestraInstallerUpdater]# curl -sL https://rpm.nodesource.com/setup_12.x | bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

**Comment by GogoAkira** [comment]
OK I know this is late, but I assumed the same thing that XOA should be compiled on host or dom0 machine while instead you should fire up a new VM it can be Debian or CentOS and then install the script or manually install nvm node yarn and compile XOA :)

**Comment by JesusPaz** [comment]
Unfortunately, we do not plan to support XCP-ng at this time, but it has been added to our list of requested distributions #1327.

When your distribution is not supported you can install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).

You can also help us to support this distribution, here are some examples of pull request #1231 #1195. If you have any problems let us know.
