### ISSUE TITLE
Tests use deprecated buffertools module

### ISSUE THREAD

**Issue by rogererens** [nodesource/distributions#1062]
In
distributions/test/test
distributions/test/test.yarn
distributions/test/test/package/server.js
and
distributions/test/test/package/package.json

the module 'buffertools' is required.
On the author's repo the readme states that the module is deprecated, see
https://github.com/bnoordhuis/node-buffertools
and cannot be used with newer versions of Node.js

**Comment by igsu** [comment]
Hi @rogererens,

As of #1065 this is fixed. Thanks for pointing this out.
