### ISSUE TITLE
A URL for the latest version of the DEB and RPM "setup" scripts ...

### ISSUE THREAD

**Issue by nmvega** [nodesource/distributions#1064]
Hello Friends:

I hope all is well.

I'm building a `Docker` container (using a `Dockerfile`), and want to install the latest version of the `node` `setup` script. I'm performing this as **lights out** `infrastructure as code`.

However, I don't think there's a `URL` for `latest` versions.

[This URL (DEB)](https://deb.nodesource.com/setup) and [this URL (RPM)](https://rpm.nodesource.com/setup) point to (the older) `v0.10` version. Would it be possible to have those URLs always point to their latest version?

Thank you in advance! =:)

**Comment by igsu** [comment]
Hi @nmvega,

When you use the setup scripts, they automatically provide the latest version of the Node.js package with its respective version of npm, so this would be fulfilling the action you ask for in your Dockerfile.

**Comment by nmvega** [comment]
Hi @igsu Thank you. So, although this script `https://deb.nodesource.com/setup` (for example) 
specifies `NODENAME="Node.js 0.10"` and `NODEREPO="node_0.10"`, it upgrades them to the latest versions later on? Or are you referring to another script? Thanks again.

**Comment by igsu** [comment]
Your request is clear now and it is completely valid, we will be working to provide such scripts (`latest`and `latest_lts`), thanks for pointing this out.
