### ISSUE TITLE
installation on centos version centos-release-7-8.2003.0.el7.centos.x86_64 fails

### ISSUE THREAD

**Issue by shyam-infraon** [nodesource/distributions#1066]
Command executed: sudo yum install -y nodejs
Get the following error:

Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
nodejs-10.21.0-1nodesource.x86 FAILED
https://rpm.nodesource.com/pub_12.x/el/7/x86_64/nodejs-10.21.0-1nodesource.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not FoundTA
Trying other mirror.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

Error downloading packages:
  2:nodejs-10.21.0-1nodesource.x86_64: [Errno 256] No more mirrors to try.

**Comment by igsu** [comment]
Hi @shyam-infraon,

Note that you are trying to install v10.21.0 from the v12 repository. Please run:

```
sudo yum clean all
curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
sudo yum install -y nodejs
```
