### ISSUE TITLE
Installation of libv8-dev/libnode-dev on ubuntu 20.04

### ISSUE THREAD

**Issue by nbbn** [nodesource/distributions#1069]
Hi,
I try to install [V8 R package](https://cran.r-project.org/web/packages/V8/index.html).
According to docs of this package, I need: `On Debian / Ubuntu install either libv8-dev or libnode-dev`.
Unfortunately those packages are not available at your repo and to install them I have to remove nodejs package

I tried to install manually to point to v8.h:
`R CMD INSTALL --no-multiarch --configure-vars="INCLUDE_DIR=/usr/include/node" "V8-3.1.0"`
and it was fine, but I stopped on next missing file:
`/usr/bin/ld: cannot find -lv8_libplatform`

Any idea how I can fix it?
Maybe you can add those packages to your repo or I can install this files another way? Installing node from source is not an option for me :(

**Comment by stla** [comment]
Hi, maybe this can help: https://github.com/jeroen/V8/issues/100

**Comment by FoamScience** [comment]
I need libv8 version 9.1 for a vscode extension, which is not provided by `libnode-dev` package on Ubuntu 20.04
Any options to get it (other that building from source?)

**Comment by JesusPaz** [comment]
Unfortunately, we only generate the package for the versions with active Node.js support.
