### ISSUE TITLE
Error on Linux Mint 19.2

### ISSUE THREAD

**Issue by joeinslw** [nodesource/distributions#1070]
"The repository 'cdrom://Linux Mint 19.2 _Tina_ - Release amd64 20190729 bionic Release' does not have a Release file."  

It could be the repository is either missing, or corrupted, has anyone had this error message when upgrading to 19.3 ?   I also need to add that I do not have an AMD processor in this computer, it's Intel processor inside, could that be the problem?  
If that's the problem, what's the solution, because 19.3 won't install correctly.

Please let me know, Thanks !

**Comment by igsu** [comment]
@joeinslw this issue is not related to the packages distributed by this repository.
Try [here](https://github.com/linuxmint).
