### ISSUE TITLE
Snap channel: should have a "lts" and a "stable" channel

### ISSUE THREAD

**Issue by jehon** [nodesource/distributions#1074]
It would be great if the snap distribution of node had a **stable** channel, for node normal releases (14 as of today), and a **LST** channel (version 12 as of today).

That would help people have the latest version without thinking.

It already exists for the edge channel, matching the latest dev version (15 as of today)

So, this should be great:

name   | current target | status                | alternative (1)
--------|-----------------|------------------|------
stable  | 14.*                  |                          | beta
lts        | 12.*                  |                          | stable
edge    | 15.*                 | already exists    | edge

(1) these alternatives better match [snapcraft documentation](https://snapcraft.io/docs/channels), but are less intuitive in this case.

Have a nice day

**Comment by igsu** [comment]
We are not responsible for maintaining the Snap packages, to solve any issue or more information:

https://github.com/nodejs/snap
