### ISSUE TITLE
PPA for Linux Mint 20 Ulyana

### ISSUE THREAD

**Issue by KikelDmitry** [nodesource/distributions#1075]
Hi! Have issue with adding repository in recently released Linux Mint 20 "Ulyana". When i'm trying to add new repository get message:

> Your distribution, identified as "ulyana", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Thanks in advance!

**Comment by alvaroico** [comment]
@KikelDmitry  ola 
Eu abri o comando 

`curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -  `


baixei o arquivo e adicionei uma linha de comparação.

`check_alt "Linux Mint"    "ulyana"   "Ubuntu" "focal"`

Rodei no Vscode Live serve e apliquei o comando 

`curl -sL http://127.0.0.1:5500/setup_14.x.sh | sudo -E bash -`

`sudo apt-get install -y nodejs`

----------------------------------------
Google Translate

@KikelDmitry hello
I opened the command

`curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -  `

I downloaded the file and added a comparison line.

`check_alt "Linux Mint"    "ulyana"   "Ubuntu" "focal"`

I ran Vscode Live and applied the command

`curl -sL http://127.0.0.1:5500/setup_14.x.sh | sudo -E bash -`

`sudo apt-get install -y nodejs`

**Comment by KikelDmitry** [comment]
@alvaroico hm, it's worked, thanks! i was install 12.18.1. Just one correction - you start received *.sh immediately, but you need add string into it **before**: 

1. `curl -sL https://deb.nodesource.com/setup_12.x -o nodelist.sh`
2. add string `check_alt "Linux Mint" "ulyana" "Ubuntu" "focal"` to `nodelist.sh`
3. `sudo bash nodelist.sh`
4. `sudo apt install nodejs`

**Comment by igsu** [comment]
As of #1071, Linux Mint 20 is fully supported.
