### ISSUE TITLE
Linux Mint 20 "Ulyana" is not supported

### ISSUE THREAD

**Issue by chroventer** [nodesource/distributions#1077]
Command:
```bash
$ curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
```

Error:
```
Your distribution, identified as "ulyana", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by muizer** [comment]
prus one from me. A 'ln -s focal ulyana' might already do the trick.

**Comment by jchalare** [comment]
same problem here

> Command:
> 
> ```shell
> $ curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
> ```
> 
> Error:
> 
> ```
> Your distribution, identified as "ulyana", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
> ```

**Comment by igsu** [comment]
As of #1071 Linux Mint 20 "Ulyana" is supported:

```
Unpacking nodejs (12.18.2-deb-1nodesource1) ...
...
Setting up nodejs (12.18.2-deb-1nodesource1) ...
Processing triggers for man-db (2.9.1-1) ...
xxxxxxx:/# node -v
v12.18.2
xxxxxxx:/# lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20
Release:	20
Codename:	ulyana
```
