### ISSUE TITLE
NodeJS 8.x support on Ubuntu 20.04

### ISSUE THREAD

**Issue by andreymoskvenkov** [nodesource/distributions#1079]
Please, add a support of NodeJS 8 on Ubuntu 20.04. We have a project, which cannot be upgraded for the new version of NodeJS at least in the nearest future. And many of our developers have installed newest ubuntu 20.04 on their developer's computers. Is it possible to add support for "focal" Ubuntu?

**Comment by igsu** [comment]
@andreymoskvenkov Node.js v8.x has reached EOL (2019-12-31). We do not support EOL versions in new distributions. Please move to the recommended LTS version or one of the currently supported ones.
