### ISSUE TITLE
Node Install on RHEL 7.8.2 - unsupported 

### ISSUE THREAD

**Issue by SANKASU** [nodesource/distributions#1084]
Trying to install node from the below source, throws un supported message as show below
curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release |                                                                                                                                                             | rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_14.x/el/7/x86_64/nodeso                                                                                                                                                             urce-release-el7-1.noarch.rpm'

**## Your distribution, identified as "redhat-release-server-7.8-2.el7.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support**

Any help on this is appreciated.

**Comment by derekslenk** [comment]
I am running into this as well (but with CentOS)


+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Your distribution, identified as "centos-release-7-8.2003.0.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by marciogadelha** [comment]
Solution:
`yum groupinstall 'Development Tools'`

**Comment by Enlingus** [comment]
I'm Having this issue as well with "redhat-release-server-7.8-2.el7.x86_64".

**Comment by Buutafly** [comment]
As I'am signed in as root, `curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -` did not work. I get the follwing message:

```
## Your distribution, identified as "centos-release-7-7.1908.0.el7.centos.x86_64", is not currently 
supported, please contact NodeSource at https://github.com/nodesource/distributions/issues 
if you think this is incorrect or could like your distribution to be considered for support 
```

But removing sudo did the job:
`[root@server01 ~]# curl -sL https://rpm.nodesource.com/setup_14.x | bash -`

**Comment by kunalborker** [comment]
Facing the same issue on Redhat Linux 7.8

## Your distribution, identified as "redhat-release-server-7.8-2.el7.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

yum groupinstall 'Development Tools' & removing sudo also did not work.

**Comment by riosje** [comment]
Hello guys, with the new installation process the repo is agnostic to the distro.
Unfortunately as of today Node14 has not support, this new solution was adapted to Node16,18 and 20

Take a look to the new README
https://github.com/nodesource/distributions#installation-instructions-1
