### ISSUE TITLE
Node Install on CentOS 7 - unsupported

### ISSUE THREAD

**Issue by Afdenis** [nodesource/distributions#1086]
[root@freepbx ~]# curl -sL https://rpm.nodesource.com/setup_current.x | bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

**Comment by xfix** [comment]
This looks like FreePBX rather than CentOS 7.

**Comment by igsu** [comment]
As mentioned above, duplicated #257.
