### ISSUE TITLE
Your distribution, identified as "n/a", is not currently supported

### ISSUE THREAD

**Issue by eng-hillary** [nodesource/distributions#1093]
i have been trying to install nodejs and npm on my parrot security (debian) system but i always been getting the following errors ""Your distribution, identified as "n/a", is not currently supportedplease contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
"".
thanks

**Comment by xfix** [comment]
I think this distribution is based on Debian Bullseye which is not currently supported (but likely will be soon). That being said, distribution reporting its codename as `n/a` (using `lsb_release -c -s`) will likely be an issue for supporting this distribution.

**Comment by imic07** [comment]
modify  line209       DISTRO=$(lsb_release -c -s)   to         DISTRO=stable

**Comment by JesusPaz** [comment]
Hi @eng-hillary 

Unfortunately, at this time we are unable to provide support for Parrot Security OS.

If your distribution is not supported you can install the packages manually. You can take a look at our README.

**Comment by immo-huneke-zuhlke** [comment]
Hi @JesusPaz I am hitting the identical problem in a bog-standard Debian bullseye 3.1 distribution.

My Dockerfile says
`FROM ruby:3.1-bullseye AS ruby`
...
`RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -`
