### ISSUE TITLE
updating supported version list

### ISSUE THREAD

**Issue by LeonardoFuba** [nodesource/distributions#1094]
Hi guys,

I've been using node 12.18 on my **openSUSE Leap 15.3** and noticed that the documentation only describes support for [Leap 42.x](https://nodejs.org/en/download/package-manager/#opensuse-and-sle)
The doc needs to update the [list](https://github.com/nodesource/distributions/blob/master/README.md) for this supported version and instructions:

---

**Node.js v8.x**:

```sh
# Using zypper
sudo zypper in nodejs8 nodejs8-devel
```

**Node.js v10.x**:

```sh
# Using zypper
sudo zypper in nodejs10 nodejs10-devel
```

**Node.js v12.x**:

```sh
# Using zypper
sudo zypper in nodejs12 nodejs12-devel
```

**Comment by xfix** [comment]
NodeSource doesn't maintain Nodejs.org website, try reporting the issue on https://github.com/nodejs/nodejs.org/issues.
