### ISSUE TITLE
Warning in deb/setup_14.x

### ISSUE THREAD

**Issue by Ricardicus** [nodesource/distributions#1097]
I get this warning when I build nodejs:

> Warning: apt-key output should not be parsed (stdout is not a terminal)

I am building a Docker image using your node distribution, as follows:

```
# Pull base image, using Ubuntu latest
FROM ubuntu:latest

# Install Node.js
RUN apt-get update && apt-get install --yes curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
```

The build is in the end **successful** however, I get this warning:

```
 ## Adding the NodeSource signing key to your keyring...
 
 + curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
 Warning: apt-key output should not be parsed (stdout is not a terminal)
 OK

```

**Comment by igsu** [comment]
This is happening in installations via Dockerfile due to changes in the operation of `apt-key add` command, to avoid this warning please check [**this topic**](https://stackoverflow.com/questions/48162574/how-to-circumvent-apt-key-output-should-not-be-parsed). Add to the Dockerfile:

```
# Pull base image, using Ubuntu latest
FROM ubuntu:latest

# Install Node.js
RUN apt-get update && apt-get install --yes curl
ARG APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
```

**Comment by Ricardicus** [comment]
I see, thanks for the clarification!
