### ISSUE TITLE
nodejs 0.12 on Fedora 21

### ISSUE THREAD

**Issue by rswrz** [nodesource/distributions#110]
When running `sh ~/nodejs-install/distributions/rpm/setup_0.12`, https://rpm.nodesource.com/pub_0.12/fc/21/x86_64/nodesource-release-fc21-1.noarch.rpm will be installed, thats fine. But the .repo file in this rpm contains `baseurl=https://rpm.nodesource.com/pub/fc/21/$basearch` not `baseurl=https://rpm.nodesource.com/pub_0.12/fc/21/$basearch`. So nodejs-0.10 would be installed through `yum install nodejs`. Changing the baseurl in .repo file and everything work as assumed.

**Comment by afranke** [comment]
Fedora 21 reached EOL 4 years ago, this should be closed as obsolete.
