### ISSUE TITLE
unable to install on debian sid

### ISSUE THREAD

**Issue by mathieuruellan** [nodesource/distributions#1100]
The dependency python2-minimal (= 2.7.17-2) can't be resolved.
```

apt install -y  nodejs

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-minimal : Depends: python2-minimal (= 2.7.17-2) but 2.7.18-2 is to be installed
                  Recommends: python but it is not going to be installed

```

**Comment by hakuamesan** [comment]
I have the same error on Debian Sid when trying to install Node 14.x.

**Comment by sabelapaulo** [comment]
I'm also getting the same unmet dependencies too. Exact same output as well.

I'm actually new to using Sid and never experienced this kind of thing with stable. Can anyone explain what this means?

Is there any solution as of yet?

**Comment by flemeur** [comment]
Hi. I'm also experiencing this problem. I managed to get nodejs installed by creating a dummy package for python-minimal with equivs. See: https://wiki.debian.org/Packaging/HackingDependencies

First install the `python2-minimal` package, if you haven't already.

Next create a file called `dummy-python-minimal.equivs` with the following content:

```
Package: python-minimal
Version: 99:99
Maintainer: Your Name <you@example.com>
Architecture: all
Description: dummy python-minimal package
 A dummy package providing python-minimal for nodesource nodejs repository.
```

Then run

```
equivs-build dummy-python-minimal.equivs
```

Then install the generated dummy package

```
sudo dpkg -i python-minimal_99_all.deb
```

Now you should be able to install the nodejs package without problems.

**Comment by lovell** [comment]
@igsu It looks like the Node.js 14.x sid `Packages` files e.g. https://deb.nodesource.com/node_14.x/dists/sid/main/binary-arm64/Packages files have now been updated so their `Depends` contains `python3-minimal`, thank you.

> Depends: libc6 (>= 2.17), libgcc1 (>= 1:3.4), libstdc++6 (>= 4.8), python3-minimal, ca-certificates

Please can you also update the `node_10.x` and `node_12.x` versions of these `Packages` files? (I would open a PR for this but it doesn't look like these are open source, or at least I can't find them.)

**Comment by igsu** [comment]
@lovell This has only been distributed with the new version of Node.js 14.x, with the new versions of Node.js 10.x and 12.x that will be released today so will the dependency update for these versions.

**Comment by igsu** [comment]
Packages have already been updated:
https://deb.nodesource.com/node_10.x/dists/sid/main/binary-arm64/Packages
https://deb.nodesource.com/node_12.x/dists/sid/main/binary-arm64/Packages
https://deb.nodesource.com/node_14.x/dists/sid/main/binary-arm64/Packages

**Comment by memoryhole** [comment]
I think the Ubuntu distros also need updating: https://deb.nodesource.com/node_10.x/dists/cosmic/main/binary-amd64/Packages

**Comment by dandv** [comment]
I've just run into the same problem with `node_15.x` and `bionic`.

**Comment by LuisAlejandro** [comment]
@igsu Hi! could you update the `node_11.x` and `node_13.x` packages too? This problem is still present in those versions.

https://deb.nodesource.com/node_11.x/dists/sid/main/binary-arm64/Packages
https://deb.nodesource.com/node_13.x/dists/sid/main/binary-arm64/Packages
