### ISSUE TITLE
Q: Why npm version is 6.9.0 on 12.x and 14.x??

### ISSUE THREAD

**Issue by FrnandMG** [nodesource/distributions#1101]
I installed nodejs via **nodesource.com/setup_12.x** and **nodesource.com/setup_14.x** 

always install the correct version of node but **npm is outdated** and generates a compatibility error -> **(cb.apply is not a function)**

I had to install **node version 10** for it to work.

How can I have the latest version of node and npm? Thanks for the help

**Comment by igsu** [comment]
@FrnandMG we take care of packaging the binaries and distributing them, with the `npm` version available at the time they were released. If you need to upgrade `npm` just run:

```
xxxxxxxx@xxxxxxxx:/# npm -v
6.14.6
xxxxxxxx@xxxxxxxx:/# npm i -g npm@latest
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
+ npm@6.14.8
added 17 packages from 3 contributors, removed 18 packages and updated 20 packages in 4.609s
xxxxxxxx@xxxxxxxx:/# npm -v
6.14.8

```

**Comment by FrnandMG** [comment]
thanks for reply but I can not upgrade npm (npm i -g npm@latest) with node v12 or v14. Its generate a compatibility error -> (cb.apply is not a function). I think I will have to use node v10
