### ISSUE TITLE
Potential issue with a nodesource mirror

### ISSUE THREAD

**Issue by smrutimandal** [nodesource/distributions#1104]
I am trying to install Nodejs 10 in Ubuntu Xenial.

Whenever deb.nodesource.com points to `2.16.177.51` the installation works fine.

But when it points to `2.16.177.26`, it fails with either of the below messages:

```E: Failed to fetch https://deb.nodesource.com/node_10.x/pool/main/n/nodejs/nodejs_10.22.0-1nodesource1_amd64.deb  GnuTLS recv error (-24): Decryption has failed.```

OR

```
## Confirming "xenial" is supported...
+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_10.x/dists/xenial/Release'
## Your distribution, identified as "xenial", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

The behaviour is consistent across multiple attempts.

**Comment by nlfiedler** [comment]
Is there a work-around for this?

**Comment by smrutimandal** [comment]
This is what I did

```
wget -v --tries=5 --wait=3 --retry-connrefused --continue --no-dns-cache https://deb.nodesource.com/node_10.x/pool/main/n/nodejs/nodejs_10.22.0-1nodesource1_amd64.deb
dpkg -i nodejs_10.22.0-1nodesource1_amd64.deb
apt-get install -f -yqq
rm nodejs_10.22.0-1nodesource1_amd64.deb
```

**Comment by zmilonas** [comment]
I'm also having this problem with Node 12.x. On retry it works

**Comment by JesusPaz** [comment]
This seems to be a problem with our cache service, it should be fixed already.
