### ISSUE TITLE
Why are we still writing installation instructions that require piping to bash?

### ISSUE THREAD

**Issue by SamJC-FG** [nodesource/distributions#1109]
Hi,

This is a pretty straight-forward issue: using "curl | bash" is not considered good practice, and can be dangerous or detrimental if something goes wrong. To the inexperienced user, this can be a headache for them and can potentially blame the authors for creating a shoddy installation process.

For reference:
https://sysdig.com/blog/friends-dont-let-friends-curl-bash/
https://www.seancassidy.me/dont-pipe-to-your-shell.html
https://blog.dijit.sh//don-t-pipe-curl-to-bash
https://stackoverflow.com/questions/46070068/why-should-piping-be-avoided-in-bash-scripts

**What could go wrong?**

If a curl request is prematurely interrupted, the half-complete results are sent to bash. Meaning if there was an instruction such as "sudo rm -rf /name-of-directory" and bash only receives "rm -rf /" - your root filesystem is gone. Another example can be if your package manager repo configurations are malformed because an entry wasn't sufficiently filled out.

The fix is incredibly simple to implement: Instead, the user intending to install the software should be using the url provided in the curl request to download the shell script's text as a file and run the script themselves. For example:
```
curl -sL https://deb.nodesource.com/setup_14.x --output nodesjssetup_14.x.sh
/bin/bash nodesjssetup_14.x.sh
rm -f nodesjssetup_14.x.sh
sudo apt-get install -y nodejs
```

Thanks for your attention!

**Comment by oliv3r** [comment]
to add to your example, in the docker-world, one can do
```
ADD "https://deb.nodesource.com/setup_12.x" "/nodejs/setup_12.x"
RUN bash "/nodejs/setup_12.x"
```
to obtain the same result

**Comment by bsolomon1124** [comment]
Though it does not alleviate the issue entirely, I added some `curl` flags in https://github.com/nodesource/distributions/pull/1162 that should at least tell the user something's up if the request goes awry, rather than failing silently.

**Comment by igsu** [comment]
@SamJC-FG @bsolomon1124 

We do have manual instructions.

https://github.com/nodesource/distributions/#debmanual

Though piping our script into bash isn't a security issue in our case.
