### ISSUE TITLE
Downgrade to node8.x not supported in ubuntu20.04

### ISSUE THREAD

**Issue by mahesh-rajput** [nodesource/distributions#1111]
I am trying to install node via ` curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh` and got below output :

```
================================================================================
================================================================================

                              DEPRECATION WARNING                            

  Node.js 8.x LTS Carbon is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_10.x — Node.js 10 LTS "Dubnium"
   * https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium" (recommended)
   * https://deb.nodesource.com/setup_14.x — Node.js 14 LTS "Fermium"

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.

  The NodeSource Node.js distributions repository contains
  information both about supported versions of Node.js and supported Linux
  distributions. To learn more about usage, see the repository:
    https://github.com/nodesource/distributions

================================================================================
================================================================================

Continuing in 20 seconds ...


## Installing the NodeSource Node.js 8.x LTS Carbon repo...


## Populating apt-get cache...

+ apt-get update
Get:1 https://download.docker.com/linux/ubuntu focal InRelease [36.2 kB]                                                                                                                                  
Hit:2 http://in.archive.ubuntu.com/ubuntu focal InRelease                                                                                                                                                 
Get:3 http://in.archive.ubuntu.com/ubuntu focal-updates InRelease [111 kB]                                                              
Hit:4 http://packages.microsoft.com/repos/vscode stable InRelease                                                                 
Hit:5 https://deb.nodesource.com/node_10.x focal InRelease                                           
Get:6 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]      
Get:7 http://in.archive.ubuntu.com/ubuntu focal-backports InRelease [98.3 kB]
Get:8 http://in.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [374 kB]
Get:9 http://in.archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [217 kB]
Get:10 http://in.archive.ubuntu.com/ubuntu focal-updates/main amd64 DEP-11 Metadata [209 kB]
Get:11 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [24.3 kB]
Get:12 http://in.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [170 kB]        
Get:13 http://in.archive.ubuntu.com/ubuntu focal-updates/universe i386 Packages [93.7 kB]
Get:14 http://security.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [54.6 kB]
Get:15 http://in.archive.ubuntu.com/ubuntu focal-updates/universe amd64 DEP-11 Metadata [195 kB]
Get:16 http://in.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [2,468 B]          
Get:17 http://in.archive.ubuntu.com/ubuntu focal-backports/universe amd64 DEP-11 Metadata [1,768 B]
Fetched 1,694 kB in 4s (460 kB/s)                                              
Reading package lists... Done

## Confirming "focal" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/focal/Release'

## Your distribution, identified as "focal", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

OS : Ubuntu 20.04
node : 10.22.1

**Comment by denisgolius** [comment]
> I am trying to install node via ` curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh` and got below output :
> 
> ```
> ================================================================================
> ================================================================================
> 
>                               DEPRECATION WARNING                            
> 
>   Node.js 8.x LTS Carbon is no longer actively supported!
> 
>   You will not receive security or critical stability updates for this version.
> 
>   You should migrate to a supported version of Node.js as soon as possible.
>   Use the installation script that corresponds to the version of Node.js you
>   wish to install. e.g.
> 
>    * https://deb.nodesource.com/setup_10.x — Node.js 10 LTS "Dubnium"
>    * https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium" (recommended)
>    * https://deb.nodesource.com/setup_14.x — Node.js 14 LTS "Fermium"
> 
>   Please see https://github.com/nodejs/Release for details about which
>   version may be appropriate for you.
> 
>   The NodeSource Node.js distributions repository contains
>   information both about supported versions of Node.js and supported Linux
>   distributions. To learn more about usage, see the repository:
>     https://github.com/nodesource/distributions
> 
> ================================================================================
> ================================================================================
> 
> Continuing in 20 seconds ...
> 
> 
> ## Installing the NodeSource Node.js 8.x LTS Carbon repo...
> 
> 
> ## Populating apt-get cache...
> 
> + apt-get update
> Get:1 https://download.docker.com/linux/ubuntu focal InRelease [36.2 kB]                                                                                                                                  
> Hit:2 http://in.archive.ubuntu.com/ubuntu focal InRelease                                                                                                                                                 
> Get:3 http://in.archive.ubuntu.com/ubuntu focal-updates InRelease [111 kB]                                                              
> Hit:4 http://packages.microsoft.com/repos/vscode stable InRelease                                                                 
> Hit:5 https://deb.nodesource.com/node_10.x focal InRelease                                           
> Get:6 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]      
> Get:7 http://in.archive.ubuntu.com/ubuntu focal-backports InRelease [98.3 kB]
> Get:8 http://in.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [374 kB]
> Get:9 http://in.archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [217 kB]
> Get:10 http://in.archive.ubuntu.com/ubuntu focal-updates/main amd64 DEP-11 Metadata [209 kB]
> Get:11 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [24.3 kB]
> Get:12 http://in.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [170 kB]        
> Get:13 http://in.archive.ubuntu.com/ubuntu focal-updates/universe i386 Packages [93.7 kB]
> Get:14 http://security.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [54.6 kB]
> Get:15 http://in.archive.ubuntu.com/ubuntu focal-updates/universe amd64 DEP-11 Metadata [195 kB]
> Get:16 http://in.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [2,468 B]          
> Get:17 http://in.archive.ubuntu.com/ubuntu focal-backports/universe amd64 DEP-11 Metadata [1,768 B]
> Fetched 1,694 kB in 4s (460 kB/s)                                              
> Reading package lists... Done
> 
> ## Confirming "focal" is supported...
> 
> + curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/focal/Release'
> 
> ## Your distribution, identified as "focal", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
> ```
> 
> OS : Ubuntu 20.04
> node : 10.22.1

New installation is not working too... 🤘

**Comment by igsu** [comment]
@mahesh-rajput Ubuntu 20.04 LTS was released on April 23, 2020 and Node.js 8.x reached its End Of Life on December 31, 2019. Deprecated versions are not supported in new distributions.

**Comment by Airstriker** [comment]
You can alway use nvm in such cases:
https://github.com/nvm-sh/nvm
