### ISSUE TITLE
Node.js v14.x does not support Debiam 11.x "Bullseye"

### ISSUE THREAD

**Issue by ManchoBlanko** [nodesource/distributions#1112]
Please update Node.js to support Debian 11.x Bullseye. I have just started using Bullseye to have the latest software so being forced to use Node.js v. 12.x is rather frustrating, especially as I have been using 14.x on Buster for some time now. Thank you.

**Comment by igsu** [comment]
Hi @ManchoBlanko, I have added Debian 11.x Bullseye as one of the supported distributions.

**Comment by ManchoBlanko** [comment]
Great news, thank you very much.
