### ISSUE TITLE
Where are located the SRPMS files?

### ISSUE THREAD

**Issue by atoomic** [nodesource/distributions#1113]
I can find the SRPMS for the v7 release, for example here: http://rpm.nodesource.com/pub_7.x/el/7/SRPMS/
but I cannot find the SRPMS for the v12 https://rpm.nodesource.com/pub_12.x/el/7?

Are they published somewhere? Is it possible to have access to the src.rpm files?

Related to #998

**Comment by locobastos** [comment]
Hello atoomic, 

Here is the answer ==> #576

Have a good day !

**Comment by atoomic** [comment]
Thanks for the hint.
We can browse them from: https://nodejs.org/dist/
