### ISSUE TITLE
Support for Ubuntu 20.10 (groovy)

### ISSUE THREAD

**Issue by SirMishaa** [nodesource/distributions#1116]
Hello, 

Unfortunately it is impossible to install NodeJS on Ubuntu 20.10, but version 20.10 of Ubuntu will be released in a couple of weeks.

Is it possible to add support for this version? 

Best regards

**Comment by igsu** [comment]
**Ubuntu Groovy Gorilla 20.10** is a pre-release version of Ubuntu. NodeSource does not maintain official support for Ubuntu versions until they are formally released. You can try using the manual installation instructions available at https://github.com/nodesource/distributions and use the latest supported Ubuntu version name as the distribution identifier, although this is not guaranteed to work.
