### ISSUE TITLE
Support  distribution package "alinux-release-2.1903-4.al7.x86_64"

### ISSUE THREAD

**Issue by CN000** [nodesource/distributions#1122]
#curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

**Comment by MunchingRabbit** [comment]
Hi, I had same problem but I managed to run through the script and came up with a workaround;
My system has the following version: alinux-release-2.1903-8.al7.x86_64

The workaround shell script command:
mkdir '/tmp/node' && curl -sL -o '/tmp/node' 'https://rpm.nodesource.com/pub_14.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm' && rpm -i --nosignature --force '/tmp/node'

After running this command, you can run 'yum install nodejs' normally. 
I am unsure if your aliyun-linux version specified is using yum package manager but ill leave this here for whomever who is using ali linux as reference.

**Comment by JesusPaz** [comment]
Unfortunately, we do not plan to support aLinux at this time.

When your distribution is not supported you can install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).

You can also help us to support this distribution, here are some examples of pull request #1231 #1195. If you have any problems let us know.
