### ISSUE TITLE
Installation of current Node.js  LTS (v14.x) using ubuntu installs v12.x instead

### ISSUE THREAD

**Issue by edersonrmachado** [nodesource/distributions#1127]
Hi. I've  tried to install node.js current LTS version (v14_x) in ubuntu 18.03, by following the readme steps: 

### Node.js LTS (v14.x):

 \# Using Ubuntu

```bash
curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
sudo apt-get install -y nodejs
```

but it installs v12x instead. It seems that installation uses  12_x repo.

**Comment by YOU54F** [comment]
Yep seeing the same here, we have the following script in an ec2 deployer

```
#! /usr/bin/env bash
set -euf -o pipefail

yum install -y jq

curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E sh -
yum install -y nodejs --enablerepo=nodesource
```

And we get an error in our logs

```
/ec2/deployments/xyz /ec2/deployments/xyz/i-08a51cda3ecb52564 https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodejs-12.19.0-1nodesource.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found
/ec2/deployments/xyz /ec2/deployments/xyz/i-08a51cda3ecb52564 Trying other mirror.
/ec2/deployments/xyz /ec2/deployments/xyz/i-08a51cda3ecb52564 Error downloading packages:
  2:nodejs-12.19.0-1nodesource.x86_64: [Errno 256] No more mirrors to try.
```

Failing to download

https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodejs-12.19.0-1nodesource.x86_64.rpm

If you look at the above link, it is checking in `pub_10.x` but trying to downloading a nodejs 12 package.

Changing the link to 

https://rpm.nodesource.com/pub_12.x/el/7/x86_64/nodejs-12.19.0-1nodesource.x86_64.rpm works

**Comment by YOU54F** [comment]
@igsu 

Hi Ivan, is this possibly related to changes done in the last day?

https://github.com/nodesource/distributions/commit/f8c2099d76763d5b221b5e8f7b963b939fd56562

Apologies, if this is a red-herring
