### ISSUE TITLE
python-minimal Package Requirement

### ISSUE THREAD

**Issue by JacobSweeten** [nodesource/distributions#1133]
Hello.

I am trying to install via your instructions, but I get the following error:

`The following packages have unmet dependencies:
 nodejs : Depends: python-minimal but it is not installable
E: Unable to correct problems, you have held broken packages.`

When I try to install python-minimal, I get the following result:

`Package python-minimal is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python2-minimal`

So I installed python2-minimal, but apt will not recognize it as a replacement for python-minimal.

Node version: 15.1.0
Distro: Kali Linux 2020.4

**Comment by JacobSweeten** [comment]
Update: I was able to come up with _a_ solution, but I had to roll back python2 and libpython2-stdlib to 2.7.16-1 then install python-minimal from the Debian Buster repo. (All packages manually downloaded from packages.debian.org/buster/amd64/)

**Comment by ZoeS17** [comment]
I have written a workaround that works for me on Kali so long as I have `ar` and `apt` installed and am able to pull the package via `apt`. It only works with python3-minimal but you could modify the 3 to a 2 on line 13 of my [gist](https://gist.github.com/ZoeS17/3e1f46006d990f990438decd00ff2a76).
