### ISSUE TITLE
node setup_10.x does not install

### ISSUE THREAD

**Issue by mike20007** [nodesource/distributions#1135]
Hello,

I ran the below to install nodejs 10.x and I got the below error.

wget -qO- https://rpm.nodesource.com/setup_10.x | bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_10.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "redhat-release-server-6Server-6.7.0.3.0.1.el6.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Could you please help to fix this?

Thanks!

**Comment by mckaygerhard** [comment]
taking in consideration that failed for wheeze on olders 8.x and 10.X packages.. well i do not used rpm shit but seems @mike20007 that allthe older releases distros packages where erased .. without archiving! 

any archived files of those packages?

**Comment by igsu** [comment]
@mike20007 RHEL6 is currently supported for Node.js 10.x and
```
curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_10.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'
```
should properly fetch the nodesource-release file.

If you are behind a proxy please read #9.
