### ISSUE TITLE
Is Amazon Linux -  arm instance supported?

### ISSUE THREAD

**Issue by alexcleu** [nodesource/distributions#1137]
Hi team! so as i run this on arm based instance for Amazon linux Instance, i get this error : 
```
# As root
curl -sL https://rpm.nodesource.com/setup_15.x | bash -
```

    amazon-ebs: ## You don't appear to be running a supported machine architecture: aarch64. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support.

Curious to know if this supported.

**Comment by igsu** [comment]
Hey @alexcleu, is not currently supported. We will be actively working on this. Thanks for highlighting it.

**Comment by igsu** [comment]
@alexcleu as of #1139 `arm64` - `aarch64` architecture is supported for Enterprise Linux based distributions, which includes Amazon Linux.

**Comment by mrleu** [comment]
awesome! thank you!
