### ISSUE TITLE
Not Supported on LInux distro Focal

### ISSUE THREAD

**Issue by ritiksoni00** [nodesource/distributions#1138]
I'm unable to install it 

```
v=8   # set to 4, 5, 6, ... as needed
curl -sL https://deb.nodesource.com/setup_$v.x | sudo -E bash -
```
![Screenshot from 2020-11-18 09-22-33](https://user-images.githubusercontent.com/47344024/99481221-a887f580-297f-11eb-9da2-82e148d548c3.png)

**Comment by ritiksoni00** [comment]
i'm installing 10 but it is installing 8 i doint why

**Comment by igsu** [comment]
Node.js v8.x is not supported on Ubuntu Focal Fossa 20.04, support starts at v10.x. To fix the issue of the v10.x script trying to install v8.x please clean your `apt` cache.

**Comment by ritiksoni00** [comment]
I got This Issue!
