### ISSUE TITLE
Node v14 not up to date for Centos7 ?

### ISSUE THREAD

**Issue by christalk** [nodesource/distributions#1140]
What I did :

% curl -RLO https://rpm.nodesource.com/setup_**14**.x
% chmod 755 setup_**14**.x

$ sudo ./setup_**14**.x -x

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_14.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Downloading release setup RPM...

+ mktemp
+ curl -sL -o '/tmp/tmp.8cOPpsy4UJ' 'https://rpm.nodesource.com/pub_14.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Installing release setup RPM...

+ rpm -i --nosignature --force '/tmp/tmp.8cOPpsy4UJ'

## Cleaning up...

+ rm -f '/tmp/tmp.8cOPpsy4UJ'

## Checking for existing installations...

+ rpm -qa 'node|npm' | grep -v nodesource

## You may also need development tools to build native addons:
     sudo yum install gcc-c++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
     sudo yum install yarn
************************
$ **sudo yum install -y nodejs**
Modules complementaires charges  : fastestmirror
Reposito
ry base is listed more than once in the configuration
Repository updates is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository centosplus is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: centos.mirror.ate.info
 * extras: centos.crazyfrogs.org
 * updates: centos.crazyfrogs.org
Le paquet 2:   nodejs-**12.20**.0-1nodesource.x86_64 **is already installed** in its latest version
Nothing to do
$

Why 12.20  instead of 14.15 ?

PS same as https://github.com/nodesource/distributions/issues/922

**Comment by igsu** [comment]
Looks like you have `nodejs` already installed. Please uninstall it and retry the 14.x script:
```
sudo yum remove nodejs -y
sudo yum clean all
curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
sudo yum install nodejs -y
```

**Comment by christalk** [comment]
Thank you Iván. 

It works after launching the commands you specify.

I thought I didn't need to delete an older version because I thought the update was doing it, or rewriting on top of it, but it doesn't.

**Comment by igsu** [comment]
It only update
