### ISSUE TITLE
Remove "i386" from apt repo (after 10.x)

### ISSUE THREAD

**Issue by selimrecep** [nodesource/distributions#1142]
Hi,
I am using Debian 10 Buster, I had trouble while trying to install nodejs. I did everything, tried 12.x, 14.x but it still tried to install 10.x, I had remove main deb repos to check it, and apt couldn't find it. So after hours later I realised that 32 bit OS was installed. I didn't think it was about that, because there was "https://deb.nodesource.com/node_14.x/dists/buster/main/binary-i386" folder in repo, and when I checked "https://deb.nodesource.com/node_14.x/dists/buster/main/binary-i386/Packages" (Packages page) I saw it was empty, after a little search (after hours) I realised that only 64-bit OS supported after 10.x . It is a problem about my server provider, I know. But wouldn't it be better to show a message to user that arch wasn't supported? I am not sure if you can remove "i386", but if it is possible, it is a better option, to prevent mistakes like this.

**Comment by igsu** [comment]
@selimrecep as of #1147 this has been removed. Sorry for the inconvenience.

**Comment by selimrecep** [comment]
Thanks for fix, I don't have much knowledge about repos but, #1147  has name "... CentOS8". So will this only affect CentOS? I was using Debian 10, just want to clarify, I meant to prevent adding repo using "curl -sL https://deb.nodesource.com/setup_XXXXXXX.x | sudo -E bash -" command, because even there isn't "i386" build, the bash file adds the repo, and when installing nodejs, it falls back to main debian repo with version of 10.x . But I might be wrong because I am only speaking because of title of the PR. Just wanted to inform. Thank you :)
