### ISSUE TITLE
Installation fails with "distribution version" error on CentOS 8

### ISSUE THREAD

**Issue by AJCStriker** [nodesource/distributions#1146]
Attempting to install NodeJS 12 with NodeSource Node.js 12.x results in the following error:

```
## Could not determine your distribution version, you may not be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect. Include your 'distribution package' name: centos-linux-release-8.3-1.2011.el8.noarch.
```

I'd appreciate any guidance you could offer with regards to this 🙏🏽

**Comment by SingerWang** [comment]
The RPM file that the setup.bash script changed in name with the latest CentOS 8 release, it was
`centos-release-8.2-2.2004.0.2.el8.x86_64` but is now 'centos-linux-release-8.3-1.2011.el8.n'

The place to change it is in line 233 of the setup.bash, here:
`
  DIST_VERSION=$(echo $DISTRO_PKG | sed -r 's/^[[:alpha:]]+(-stream)?-release(-server|-workstation|-client|-common)?-([0-9]+).*$/\3/')
`

If you want to get it working, one simple hack is to just replace it with this line:
`
  DIST_VERSION=$(echo $DISTRO_PKG | sed -r 's/^[[:alpha:]]+(-linux)?-release(-server|-workstation|-client|-common)?-([0-9]+).*$/\3/')
``

The true solution depends on what CentOS 8 renamed the `centos-stream-release` to: 1) centos-linux-stream-release or 2) centos-stream-linux-release

**Comment by zrhoffman** [comment]
Might as well just install the repo directly.

```shell
dnf -y module disable nodejs
<<'REPO' tee /etc/yum.repos.d/nodesource-nodejs.repo
[nodesource-nodejs]
name=Node.js Packages for Linux RPM based distros - $basearch
baseurl=https://rpm.nodesource.com/pub_22.x/nodistro/nodejs/$basearch
priority=9
enabled=1
gpgcheck=1
gpgkey=https://rpm.nodesource.com/gpgkey/ns-operations-public.key
module_hotfixes=1
REPO
```

**Comment by igsu** [comment]
As of #1147 this has been fixed.
@SingerWang the new regex looks like this:
```
DIST_VERSION=$(echo $DISTRO_PKG | sed -r 's/^[[:alpha:]]+(-stream|-linux)?-release(-server|-workstation|-client|-common)?-([0-9]+).*$/\3/')
```

**Comment by AJCStriker** [comment]
Thanks all for the help and the quick resolution!

**Comment by SingerWang** [comment]
I guess the package for centos-stream didn't change their name (or yet).
