### ISSUE TITLE
How do I undo the "setup" script?

### ISSUE THREAD

**Issue by mcclure** [nodesource/distributions#1148]
So.

I `wget https://deb.nodesource.com/setup_14.x` , to install Node 14. I `sudo bash` that script.

…then I realize I pasted the wrong URL.

I meant to get 14 LTS `https://deb.nodesource.com/setup_lts.x `, but instead I installed normal 14.

How do I reverse the setup_14.x script? I haven't installed any packages yet. I just want to undo the PPAs and such.

I see a `/etc/apt/sources.list.d/nodesource.list` but I don't know if removing this is enough.

My "expected behavior" is there should be uninstall / un-PPA instructions in your README, the way you have manual install options.

**Comment by igsu** [comment]
Hey @mcclure, if you haven't installed anything yet then run `sudo apt-get clean`, then run the correct script and installations steps. Let us know if you have any other issue.
