### ISSUE TITLE
https://deb.nodesource.com/node_15.x/dists/eoan/Release returns 404

### ISSUE THREAD

**Issue by inoyakaigor** [nodesource/distributions#1151]
I got an error while trying to install latest version
![image](https://user-images.githubusercontent.com/1235286/101991184-1512bd80-3cbc-11eb-8ebd-db9dd35cf635.png)

**Comment by igsu** [comment]
Hey @inoyakaigor. Unfortunately, by the time Node.js 15.x was released, Ubuntu Eoan Ermine was already deprecated, so there will be no support for this version for that distribution.

I recommend using the [manual instructions](https://github.com/nodesource/distributions#manual-installation) using Ubuntu Focal Fossa as the version.
