### ISSUE TITLE
xenial and node v15x - can we continue it please?

### ISSUE THREAD

**Issue by traceypooh** [nodesource/distributions#1153]
[might have had a caching issue...]
today our CI/CD pipelines started to fail since our main/production is still pegged at ubuntu xenial LTS
(don't get me started).

this used to work [0..60] days ago.
any chance you could still support node v15+ on xenial?
it's working _just fine_ in our production.

the CI/CD fails said to search / new issue here - so here ya go! :) 

archive.org lead, tracey, thx!

**Comment by igsu** [comment]
Hey @traceypooh, Ubuntu `xenial` is currently supported for version 15.x: https://deb.nodesource.com/node_15.x/dists/xenial/

Can you give us more details of what is happening or logs that refer to the mentioned issue?

**Comment by traceypooh** [comment]
Oh, ok, phew, thanks & YAAAY!

here's what happened last night in our (gitlab) CI/CD pipelines (2x, on reruns, too):

#16 1189. ## Installing the NodeSource Node.js 15.x repo...
#16 1189. 
#16 1189. 
#16 1189. ## Populating apt-get cache...
#16 1189. 
#16 1189. + apt-get update
#16 1189. Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
#16 1189. Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
#16 1189. Hit:3 http://ppa.launchpad.net/git-core/ppa/ubuntu xenial InRelease
#16 1189. Get:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
#16 1190. Hit:5 https://packagecloud.io/github/git-lfs/ubuntu xenial InRelease
#16 1190. Get:6 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
#16 1190. Fetched 325 kB in 1s (234 kB/s)
#16 1190. Reading package lists...
#16 1192. 
#16 1192. ## Confirming "xenial" is supported...
#16 1192. 
#16 1192. + curl -sLf -o /dev/null 'https://deb.nodesource.com/node_15.x/dists/xenial/Release'
#16 1213. 
#16 1213. ## Your distribution, identified as "xenial", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support


but it totally worked today.  So maybe it was just a random network glitch or something, phew!
