### ISSUE TITLE
Supporting error for Ubuntu "bionic"

### ISSUE THREAD

**Issue by abdul152** [nodesource/distributions#1154]
Hi, 
I am receiving below error. 

## Confirming "bionic" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_4.x/dists/bionic/Release'

## Your distribution, identified as "bionic", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Can someone please tell me which version is compaitable with it. 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

Thanks in advance.

Regards,
Abdul Samad

**Comment by igsu** [comment]
Hey @abdul152, Node.js v4.x is a deprecated version and it's not supported in Ubuntu Bionic.
My advice is that you use a newer version. Let me know!
