### ISSUE TITLE
You don't appear to be running an Enterprise Linux based system, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support.

### ISSUE THREAD

**Issue by SoulflyTR** [nodesource/distributions#1155]
Can someone help I try to run this code curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash - in my win 10 system with ubuntu terminal and I get this error You don't appear to be running an Enterprise Linux based system,
please contact NodeSource at https://github.com/nodesource/distributions/issues
if you think this is incorrect or would like your distribution to be considered
for support.

**Comment by keannyooi** [comment]
i also have this issue (my laptop runs windows 10)

**Comment by igsu** [comment]
Binaries distributed here are compatible ONLY with Ubuntu, Debian and Enterprise Linux based systems. Running these scripts on Windows machines will not result in a successful installation. Please use one of these options for Windows systems:

- Official Windows installer: https://nodejs.org/en/download/
- Chocolatey package manager: https://chocolatey.org/packages/nodejs
