### ISSUE TITLE
iojs 3.x Packages file in deb repos is empty whilst x86 are filled

### ISSUE THREAD

**Issue by shouze** [nodesource/distributions#116]
https://deb.nodesource.com/iojs_3.x/dists/vivid/main/binary-armhf/

![capture d ecran 2015-08-05 a 12 16 29](https://cloud.githubusercontent.com/assets/54712/9083599/d82bde26-3b6b-11e5-9ab2-d9f3cb2c7837.png)

**Comment by chrislea** [comment]
The arm builds should be there now. They take vastly longer to build as it happens in an emulator, so I generally build the x86 packages first and get them into the repo ASAP since they are obviously in much higher demand. Then I let the arm builds go overnight and they typically land the day after the x86 builds do. Just for future reference.

**Comment by shouze** [comment]
ok :+1: @chrislea do you think it could be a good thing if @scaleway can provide you some bare metal machines for free to build `arm` flavours? I can ask us, they probably will be interested in as they are the main `arm` hosting platform nowadays.

**Comment by chrislea** [comment]
That's an excellent question, and I'm not sure who the proper person to ask is (it's not me). Punting over to @rvagg ?

**Comment by shouze** [comment]
@chrislea ok someone from @scaleway told me you already have some hosted machines, I don't know if you already use them for amr builds, @rvagg?

**Comment by chrislea** [comment]
We have machines that are graciously being donated by Digital Ocean. However they aren't ARM native machines. So to do the ARM builds we use an emulator which is why they take much much longer than the x86 builds.

**Comment by shouze** [comment]
ok fine, so @scaleway would probably donate you some ARM machines too. This way, won't be necessary to emulate ARM on x86 machines and this could maybe drive to faster builds?
