### ISSUE TITLE
NSolid 4.4.1 doesn't run on CentOS 7

### ISSUE THREAD

**Issue by realphi** [nodesource/distributions#1160]
Hi,
I am using nodesource supplied commands to install NSolid on CentOS 7.

```
curl -sL https://nsolid-rpm.nodesource.com/nsolid_setup_4.x | sudo bash -

sudo yum -y install nsolid-erbium nsolid-console
```

The installation goes successfully but when I try to run nsolid command I get the following error:
```
nsolid: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by nsolid)
nsolid: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by nsolid)
nsolid: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by nsolid)
nsolid: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by nsolid)
```

The latest Glibc version on CentOS 7 is 2.17, so can I even run nsolid?

**Comment by igsu** [comment]
@realphi as stated in the release notes here: https://downloads.nodesource.com/

```
Ubuntu 16.04 and RHEL7 / CentOS 7 installations require GLIBC_2.25 or higher
```

So if you want to use it in that distribution, you have to update the packages manually.
