### ISSUE TITLE
"403 Forbidden" trying access rpm.nodesource.com

### ISSUE THREAD

**Issue by 9maf4you** [nodesource/distributions#1164]
Hello! We use JFROG Artifactory as proxy to access different repos at rpm.nodesource.com 
At Friday Mon.  22.02 we’ve been alerted that repo https://rpm.nodesource.com/pub_13.x/ was unavailable.   
Actually we have no access to all repos you serve. 
Probably we have been banned because of limit or something.  
Address from where we come from is 81.19.83.229  

> \> GET /pub_13.x/ HTTP/1.1 
> \> User-Agent: curl/7.29.0 
> \> Host: rpm.nodesource.com 
> \> Accept: */* > 
> < HTTP/1.1 403 Forbidden 
> < Server: AkamaiGHost 
> < Mime-Version: 1.0
> < Content-Type: text/html
> < Content-Length: 288 
> < Expires: Mon, 25 Jan 2021 11:14:25 GMT
> < Date: Mon, 25 Jan 2021 11:14:25 GMT 
> < Connection: keep-alive 

I’d like to know was it ban or something else happened and also i’d be appreciated to know what we should fix to gain access again.  

I've sent an email to info@nodesource.com but didn't get response. So that's why I've posted here.

Thank you. Best regards.  Maxim.

**Comment by 9maf4you** [comment]
Hello, @igsu . Any news ?

**Comment by igsu** [comment]
Hi, @9maf4you. We have already responded to this issue via email, let me know if you got it.

**Comment by 9maf4you** [comment]
@igsu Hello, Ivan! No, didn't get it. On which email have you responded ?

**Comment by igsu** [comment]
@9maf4you m.timokhin

**Comment by 9maf4you** [comment]
@igsu Hm, double check - None. Would you be kind to post your reply here or send to another my email ncx2-yandex.ru

**Comment by 9maf4you** [comment]
@igsu Hello :)

**Comment by igsu** [comment]
We wrote back to ncx2@yandex.ru.
