### ISSUE TITLE
Add support for Alma Linux

### ISSUE THREAD

**Issue by gittela** [nodesource/distributions#1166]
'distribution package' name: almalinux-release-8.3-2.el8.x86_64

**Comment by igsu** [comment]
Hi @gittela

We, unfortunately, do not have the resources necessary to support and test the plethora of Linux releases in the wild, so we rely on community members such as yourself to get support on your favorite distributions.

I've added Alma Linux to the list of requested releases in our README.md.

**Comment by igsu** [comment]
As of https://github.com/nodesource/distributions/pull/1195 AlmaLinux OS is supported.
