### ISSUE TITLE
Red hat server?

### ISSUE THREAD

**Issue by RobertBaron** [nodesource/distributions#117]
Hi, 

It is any other way of install this on a redhat server 6.4? It is going to be supported? Any Hack? 

Your distribution, identified as "redhat-release-server-6Server-6.4.0.4.el6.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by No9** [comment]
Yeah we have just walked into this as well
Slightly later version of RHEL `redhat-release-server-6Server-6.7.0.3.el6.x86_64`
So we downloaded the ones available here 
https://rpm.nodesource.com/pub_0.12/el/6/x86_64/ 
```
nodejs-0.12.7-1nodesource.el6.x86_64.rpm
nodejs-debuginfo-0.12.7-1nodesource.el6.x86_64.rpm
nodejs-devel-0.12.7-1nodesource.el6.x86_64.rpm
nodejs-docs-0.12.7-1nodesource.el6.noarch.rpm  
```

And everything installed fine.

**Comment by jwdavistx** [comment]
As someone new to using Linux, would you be able to describe how you went about installing those specific versions?

**Comment by No9** [comment]
@jwdavistx Our stuff is a little complicated but basically we wget the files then use rpm 
something like 
```
wget https://rpm.nodesource.com/pub_0.12/el/6/x86_64/nodejs-0.12.7-1nodesource.el6.x86_64.rpm
rpm -i --nosignature --force nodejs-0.12.7-1nodesource.el6.x86_64.rpm
```

As you can see it's for v0.12.7 but you can update it to do what you want.

**Comment by jwdavistx** [comment]
Ah, hey, thanks!  I ended up deleting my original comment but thanks for the clarification.

**Comment by retrohacker** [comment]
RPMs for el6 are now being built. Closing this issue as stale.

If you continue to have issues using the setup script on el6, feel free to reopen this issue and we can help debug!
