### ISSUE TITLE
Not able to install nodejs 14.x on redhat 6.10

### ISSUE THREAD

**Issue by Umang2801** [nodesource/distributions#1170]
Hello team, 

I am not able to install nodejs on redhat 6.10, it is promting below error.

Can you tell me which version of nodejs is supported for redhat 6.10

Screenshot as below.

Your distribution, identified as "redhat-release-server-6Server-6.10.0.13.el6_10.9.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by igsu** [comment]
@Umang2801 as stated in the [README](https://github.com/nodesource/distributions#enterprise-linux-based-distributions), RHEL 6 is not currently supported.
