### ISSUE TITLE
ubuntu: `nodejs` conflicts with package `nodejs-doc`

### ISSUE THREAD

**Issue by soredake** [nodesource/distributions#1172]
```
Preparing to unpack .../nodejs-doc_12.18.2~dfsg-1ubuntu2_all.deb ...
Unpacking nodejs-doc (12.18.2~dfsg-1ubuntu2) ...
dpkg: error processing archive /var/cache/apt/archives/nodejs-doc_12.18.2~dfsg-1ubuntu2_all.deb (--unpack):
 trying to overwrite '/usr/share/doc/nodejs/api/addons.html', which is also in package nodejs 15.9.0-deb-1nodesource1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs-doc_12.18.2~dfsg-1ubuntu2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

Can someone add `Conflicts: nodejs-doc` to control file?
https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/

**Comment by soredake** [comment]
@chrislea @rvagg @igsu

**Comment by soredake** [comment]
@chrislea @rvagg @igsu @JesusPaz

**Comment by JesusPaz** [comment]
Hi @soredake,

It looks like someone has already found a solution to your issue #1278. Let us know if you have more problems.

**Comment by soredake** [comment]
@JesusPaz the "solution" is to add `Conflicts: nodejs-doc` to control file, is it so hard? The problem is still exists, both nodejs-doc and nodejs have files in one directory.

![изображение](https://user-images.githubusercontent.com/5204968/147112847-280c63dd-ff36-4eae-b149-695ae713472b.png)

**Comment by soredake** [comment]
@JesusPaz please reopen.

**Comment by JesusPaz** [comment]
Hi @soredake, we have already added the changes to our repository. You will see them in the next version of Node.js that we generate.
