### ISSUE TITLE
W: GPG error: https://packagecloud.io/shiftkey/desktop/any any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7E65990E879472F

### ISSUE THREAD

**Issue by viren-vii** [nodesource/distributions#1174]
The public key which they are showing is invalid so cannot be downloaded from keyserver. Please guide.
![sse](https://user-images.githubusercontent.com/56278281/109386715-a809de00-7922-11eb-9e08-683e2fd55415.png)

**Comment by igsu** [comment]
The error is not related to the packages distributed in this repository. The error is associated with an external key and it is not under our control.
