### ISSUE TITLE
Unable to install nodejs:12

### ISSUE THREAD

**Issue by rogerywoo** [nodesource/distributions#1175]
I'm not able to install nodej.  I get a 404 for https://rpm.nodesource.com/pub_12.x/el/7/x86_64/nodejs-10.24.0-1nodesource.x86_64.rpm.  Here are the steps taken.

$ curl -fsSL https://rpm.nodesource.com/setup_12.x | bash -
$ yum install -y nodejs
...
Dependencies Resolved

===================================================================================================================
 Package               Arch                  Version                               Repository                 Size
===================================================================================================================
Installing:
 nodejs                x86_64                2:10.24.0-1nodesource                 nodesource                 20 M

Transaction Summary
===================================================================================================================
Install  1 Package

Total download size: 20 M
Installed size: 60 M
Downloading packages:
No Presto metadata available for nodesource
nodejs-10.24.0-1nodesource.x86 FAILED                                          
https://rpm.nodesource.com/pub_12.x/el/7/x86_64/nodejs-10.24.0-1nodesource.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
...............

**Comment by igsu** [comment]
`yum` is trying to find a package of version `10.x` in the repository of `12.x`, I recommend you to clean the cache since this package does exist in the `10.x` repo, try running:

`yum clean all`
