### ISSUE TITLE
setup_14.x fails to work on Ubuntu 20.04

### ISSUE THREAD

**Issue by HouzuoGuo** [nodesource/distributions#1176]
Hello!

I started with launching a container of Ubuntu 20.04:

    docker run -it --rm ubuntu:20.04

And then install a bunch of system packages:

<pre>
apt update && apt upgrade -q -y -f -m -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-overwrite && \
>     apt install -q -y -f -m -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-overwrite ansible apache2-utils \
>     apt-file aptitude aspell aspell-en autoconf automake bash bat binutils bison build-essential \
>     ca-certificates ccls cgroup-tools clang clang-format clang-tidy clang-tools clangd cloc cmake cpanminus cppcheck cscope curl \
>     dateutils debhelper devscripts dh-systemd dialog diffutils direnv dnsutils docker-compose dos2unix dpkg-cross dpkg-dev dpkg-sig \
>     emacs fd-find findutils finger fish flex fzf g++ gcc gdb git global glslang-tools gnutls-bin golang hostname htop hub hwinfo \
>     iamerican ibritish iftop iotop ipcalc iputils-ping iputils-tracepath irony-server jq jsonlint \
>     language-pack-en lftp libtool libtool-bin libvterm-dev libxml2-utils lldb llvm locales lrzsz lsof \
>     man-db manpages manpages-dev manpages-posix manpages-posix-dev mailutils make miscfiles moreutils \
>     ncurses-term net-tools netcat nfs-common nicstat nmap nmon \
>     p7zip patchutils pciutils postgresql-client-12 postgresql-client-common procps psmisc python-dev-is-python3 python-is-python3 python3 python3-clang python3-dev python3-pip python3-pygments python3-setuptools python3-venv \
>     radare2 ripgrep rpmlint rsync rtags ruby ruby-dev rubygems screen shellcheck snmp socat software-properties-common sqlite strace sudo sysstat \
>     tcpdump tcptraceroute telnet tmux traceroute tree tshark ubuntu-standard unar uniutils universal-ctags unzip urlview usbutils util-linux util-linux-locales \
>     vim wamerican wbritish wget whois wiggle wordnet yamllint zip zsh zshdb zstd
</pre>

Afterwards, run `setup_14.x` and observe the following error:

<pre>
curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
...
...
raceback (most recent call last):
  File "/usr/lib/cnf-update-db", line 26, in <module>
    col.create(db)
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 94, in create
    self._fill_commands(con)
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 138, in _fill_commands
    self._parse_single_commands_file(con, fp)
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 176, in _parse_single_commands_file
    suite=tagf.section["suite"]
KeyError: 'suite'
Reading package lists... Done
E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
E: Sub-process returned an error code
</pre>

Here are more console output for the context:
<details>
<pre>
howard@cs-977014017816-default-boost-cssfp ~/hg (master) [1]> s docker run -it --rm ubuntu:20.04
root@7d4fb09a1345:/# apt update && apt upgrade -q -y -f -m -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-overwrite && \
>     apt install -q -y -f -m -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-overwrite ansible apache2-utils \
>     apt-file aptitude aspell aspell-en autoconf automake bash bat binutils bison build-essential \
>     ca-certificates ccls cgroup-tools clang clang-format clang-tidy clang-tools clangd cloc cmake cpanminus cppcheck cscope curl \
>     dateutils debhelper devscripts dh-systemd dialog diffutils direnv dnsutils docker-compose dos2unix dpkg-cross dpkg-dev dpkg-sig \
>     emacs fd-find findutils finger fish flex fzf g++ gcc gdb git global glslang-tools gnutls-bin golang hostname htop hub hwinfo \
>     iamerican ibritish iftop iotop ipcalc iputils-ping iputils-tracepath irony-server jq jsonlint \
>     language-pack-en lftp libtool libtool-bin libvterm-dev libxml2-utils lldb llvm locales lrzsz lsof \
>     man-db manpages manpages-dev manpages-posix manpages-posix-dev mailutils make miscfiles moreutils \
>     ncurses-term net-tools netcat nfs-common nicstat nmap nmon \
>     p7zip patchutils pciutils postgresql-client-12 postgresql-client-common procps psmisc python-dev-is-python3 python-is-python3 python3 python3-clang python3-dev python3-pip python3-pygments python3-setuptools python3-venv \
>     radare2 ripgrep rpmlint rsync rtags ruby ruby-dev rubygems screen shellcheck snmp socat software-properties-common sqlite strace sudo sysstat \
>     tcpdump tcptraceroute telnet tmux traceroute tree tshark ubuntu-standard unar uniutils universal-ctags unzip urlview usbutils util-linux util-linux-locales \
>     vim wamerican wbritish wget whois wiggle wordnet yamllint zip zsh zshdb zstd
Get:1 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:7 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [934 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1062 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [209 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [29.6 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [4301 B]
Get:14 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [21.6 kB]
Get:15 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [177 kB]
Get:16 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [671 kB]
Get:17 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [651 kB]
Fetched 17.2 MB in 2s (10.7 MB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
6 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages will be upgraded:
  apt base-files gpgv libapt-pkg6.0 libc-bin libc6
6 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 5735 kB of archives.
After this operation, 2048 B of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libc6 amd64 2.31-0ubuntu9.2 [2715 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 base-files amd64 11ubuntu5.3 [60.6 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libc-bin amd64 2.31-0ubuntu9.2 [639 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libapt-pkg6.0 amd64 2.0.4 [833 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 gpgv amd64 2.2.19-3ubuntu2.1 [199 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 apt amd64 2.0.4 [1289 kB]
Fetched 5735 kB in 0s (27.5 MB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 4121 files and directories currently installed.)
Preparing to unpack .../libc6_2.31-0ubuntu9.2_amd64.deb ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Unpacking libc6:amd64 (2.31-0ubuntu9.2) over (2.31-0ubuntu9.1) ...
Setting up libc6:amd64 (2.31-0ubuntu9.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
(Reading database ... 4121 files and directories currently installed.)
Preparing to unpack .../base-files_11ubuntu5.3_amd64.deb ...
Unpacking base-files (11ubuntu5.3) over (11ubuntu5.2) ...
Setting up base-files (11ubuntu5.3) ...
Installing new version of config file /etc/issue ...
Installing new version of config file /etc/issue.net ...
Installing new version of config file /etc/lsb-release ...
(Reading database ... 4121 files and directories currently installed.)
Preparing to unpack .../libc-bin_2.31-0ubuntu9.2_amd64.deb ...
Unpacking libc-bin (2.31-0ubuntu9.2) over (2.31-0ubuntu9.1) ...
Setting up libc-bin (2.31-0ubuntu9.2) ...
(Reading database ... 4121 files and directories currently installed.)
Preparing to unpack .../libapt-pkg6.0_2.0.4_amd64.deb ...
Unpacking libapt-pkg6.0:amd64 (2.0.4) over (2.0.2ubuntu0.2) ...
Setting up libapt-pkg6.0:amd64 (2.0.4) ...
(Reading database ... 4121 files and directories currently installed.)
Preparing to unpack .../gpgv_2.2.19-3ubuntu2.1_amd64.deb ...
Unpacking gpgv (2.2.19-3ubuntu2.1) over (2.2.19-3ubuntu2) ...
Setting up gpgv (2.2.19-3ubuntu2.1) ...
(Reading database ... 4121 files and directories currently installed.)
Preparing to unpack .../archives/apt_2.0.4_amd64.deb ...
Unpacking apt (2.0.4) over (2.0.2ubuntu0.2) ...
Setting up apt (2.0.4) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Reading package lists...
Building dependency tree...
Reading state information...
diffutils is already the newest version (1:3.7-3).
findutils is already the newest version (4.7.0-1ubuntu1).
hostname is already the newest version (3.23).
procps is already the newest version (2:3.3.16-1ubuntu2).
bash is already the newest version (5.0-6ubuntu1.1).
util-linux is already the newest version (2.34-0.1ubuntu9.1).
The following additional packages will be installed:
  accountsservice adwaita-icon-theme alsa-topology-conf alsa-ucm-conf apparmor appstream-util aptitude-common ascii2binary at at-spi2-core autopoint autotools-dev
  bash-completion bc bind9-dnsutils bind9-host bind9-libs binfmt-support binutils-common binutils-x86-64-linux-gnu bridge-utils bsdmainutils busybox-static cgroupfs-mount
  clang-10 clang-format-10 clang-tidy-10 clang-tools-10 clangd-10 cmake-data command-not-found containerd cpio cpp cpp-9 cron cross-config dbus dbus-user-session
  dconf-gsettings-backend dconf-service dctrl-tools debugedit desktop-file-utils dh-autoreconf dh-elpa-helper dh-strip-nondeterminism dictionaries-common diffstat dirmngr
...
...
...
...

aspell-autobuildhash: processing: en [en_GB-ize-wo_accents-only].
aspell-autobuildhash: processing: en [en_GB-variant_0].
aspell-autobuildhash: processing: en [en_GB-variant_1].
aspell-autobuildhash: processing: en [en_US-w_accents-only].
aspell-autobuildhash: processing: en [en_US-wo_accents-only].
Processing triggers for ca-certificates (20210119~20.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Processing triggers for dbus (1.12.16-2ubuntu2.1) ...
Processing triggers for php7.4-cli (7.4.3-4ubuntu2.4) ...
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.40.0+dfsg-3ubuntu0.2) ...
root@7d4fb09a1345:/# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
root@7d4fb09a1345:/# curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

## Populating apt-get cache...

+ apt-get update
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal amd64 Contents (deb) [40.9 MB]
Get:6 http://security.ubuntu.com/ubuntu focal-security amd64 Contents (deb) [26.8 MB]
Get:7 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [7072 B]
Get:8 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 c-n-f Metadata [392 B]
Get:9 http://security.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [10.4 kB]
Get:10 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 c-n-f Metadata [340 B]
Get:11 http://archive.ubuntu.com/ubuntu focal/main amd64 c-n-f Metadata [29.5 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal/restricted amd64 c-n-f Metadata [392 B]
Get:13 http://archive.ubuntu.com/ubuntu focal/universe amd64 c-n-f Metadata [265 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 c-n-f Metadata [9136 B]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates amd64 Contents (deb) [32.9 MB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [12.8 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 c-n-f Metadata [436 B]
Get:18 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [16.2 kB]
Get:19 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 c-n-f Metadata [596 B]
Get:20 http://archive.ubuntu.com/ubuntu focal-backports amd64 Contents (deb) [8038 B]
Get:21 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 c-n-f Metadata [112 B]
Get:22 http://archive.ubuntu.com/ubuntu focal-backports/restricted amd64 c-n-f Metadata [116 B]
Get:23 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 c-n-f Metadata [224 B]
Get:24 http://archive.ubuntu.com/ubuntu focal-backports/multiverse amd64 c-n-f Metadata [116 B]
Fetched 101 MB in 19s (5421 kB/s)
Traceback (most recent call last):
  File "/usr/lib/cnf-update-db", line 26, in <module>
    col.create(db)
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 94, in create
    self._fill_commands(con)
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 138, in _fill_commands
    self._parse_single_commands_file(con, fp)
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 176, in _parse_single_commands_file
    suite=tagf.section["suite"]
KeyError: 'suite'
Reading package lists... Done
E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
E: Sub-process returned an error code
Error executing command, exiting
root@7d4fb09a1345:/#
root@7d4fb09a1345:/#
</pre>
</details>

**Comment by JesusPaz** [comment]
The error seems to be related to an `apt-get update` running at the start of the script. Can you give us more information?
