### ISSUE TITLE
Trying to install Node.js 12, getting 10 instead, no npm.

### ISSUE THREAD

**Issue by kshetline** [nodesource/distributions#1178]
I'm trying create a bash installation script to install Node.js version 12 on Debian Linux 10.8 using:

```
curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
sudo apt-get install -y nodejs
```
When the installation is done, however, I check the version with `node --version`, and I've got v10.24.0 instead.

What would cause this, and how do I stop it from happening?

I'm also finding that `npm` isn't installed unless I instead do:

```
sudo apt-get install -y nodejs npm
```

...and make the installation of `npm` explicit.

Am I perhaps missing some prerequisite for version 12, and being automatically downgraded to version 10?

I'm trying to emulate a Raspberry Pi 3B+ with only 1GB RAM. Could that be the issue? I'm actually trying to deliberately install 12 instead of 14 in this installation script I'm creating if the memory is so small, because I think 14 might take too much RAM. Maybe 1GB is too small for 12 too?

If I try to install again, I get:

```
pi@raspberry:~ $ sudo apt-get install -y nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (10.24.0~dfsg-1~deb10u1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
```

**Comment by kshetline** [comment]
I think I understand part of the problem now. As I remember, `sudo apt-get install nodejs` didn't work before on Raspbian, not without running a script like yours first to set up a repo. Now, however, there is an officially-available Node installation, but it's Node 10.

So I guess the question now is: How do I make the Node 12 from nodesource supersede Node 10?

**Comment by lukeescude** [comment]
This is happening to me on CentOS 7 as well - It always installs 10.13.0

I have been upgrading NPM, then using the "n" package manager to then upgrade Node to the version I want. Steps below:

npm install -g npm
npm install -g n
n stable
PATH="$PATH"

That will update npm, then install n (the node version manager basically), then install the latest stable version of node, then export the path to update the current session.

**Comment by kshetline** [comment]
Just to clarify my previous post, disregard the Raspberry Pi stuff. Debian is the real issue. I was using a VM with Debian 10.8 and the RPi desktop environment, but it’s an AMD64 processor, not ARM like a real RPi. And now I see I get the same error in a straight Debian 10.8 environment without the Raspberry Pi stuff.

A real non-simulated Pi can install Node 12 just fine.

**Comment by t1m0thyj** [comment]
I'm seeing the same issue in Debian (running in `jenkins/agent` Docker container). The command:
```dockerfile
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get install -y nodejs
```
ends up with Node.js 10 installed and the `npm` binary is missing.

The expected behavior would be Node.js 14 installed and the `npm` binary is added to PATH.

**Comment by lukeescude** [comment]
I believe a possible fix is to clean your cache prior to installing - Specifically `yum clean all` on centOS - Not sure what the equivalent expression is for aptitude.

Recently it hasn't been happening to me anymore.

**Comment by t1m0thyj** [comment]
In my case I was starting fresh with a clean Docker image, so caching wasn't an issue. It turned out to be a network-related issue caused by VPN configuration - cURL was failing to verify the SSL certificate.

**Comment by reverse28** [comment]
This solved my problem

1. Delete the installed version

`sudo apt purge nodejs`

2. Download the archive, ignoring the SSL certificate, unpack it, then copy it to /usr/local/ (use uname -a to get the exact version of ARMv*):

```
wget --no-check-certificate https://nodejs.org/dist/v12.9.1/node-v12.9.1-linux-armv7l.tar.xz 
unxz node-v12.9.1-linux-armv7l.tar.xz
tar xvf node-v12.9.1-linux-armv7l.tar
cd node-v12.9.1-linux-armv7l/
sudo cp -R * /usr/local/
```

3. Restart your device and check node.js and npm version
