### ISSUE TITLE
please consider advertising nodejs from debian

### ISSUE THREAD

**Issue by kapouer** [nodesource/distributions#1179]
Hi,

i'm debian nodejs maintainer, this is actual situation;
https://tracker.debian.org/pkg/nodejs

To sum it up debian is x-2 behind upstream releases:
- 10 in stable
- 12 in testing (which is soon the next stable)
- 14 in experimental (soon the next unstable)

I think this is fair, because debian has to cope with all the nodejs modules
that come along. Even in real npmjs.org life it's difficult to keep up...

It would be nice to let users know debian is spending lots of resources
to make nodejs work there ! On many archs, and with many tests.

Also all dependencies (like openssl) benefit from other maintainers work,
and get security updates *before* the ones made by nodejs upstream.

**Comment by igsu** [comment]
Thanks for contacting us, good luck on this project. In case we consider it, we will let you know.
