### ISSUE TITLE
Fedora 22 not supported

### ISSUE THREAD

**Issue by cortopy** [nodesource/distributions#118]
Would it be possible to support Fedora 22 in the repositories?

WHen trying to install I get this message

```Your distribution, identified as "fedora-release-22-1.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support```

**Comment by chrislea** [comment]
Hi. We're working on this, please ref #87. Thanks.
