### ISSUE TITLE
HTTP request sent, awaiting response... 403 Forbidden

### ISSUE THREAD

**Issue by UpworksTeam** [nodesource/distributions#1184]
Hi All
The server (IP address) of one of my clients seems to be blacklisted... This is a new server... So we didn't do anything criminal

curl https://deb.nodesource.com/node_14.x/dists/buster/Release
"
Access Denied
You don't have permission to access "http&#58;&#47;&#47;deb&#46;nodesource&#46;com&#47;node&#95;14&#46;x&#47;dists&#47;buster&#47;Release" on this server.<P>
Reference&#32;&#35;18&#46;75ee2017&#46;1616679390&#46;3a99e8c
</BODY>
</HTML>
"

At the same time, git works well:

git clone https://github.com/nodesource/distributions.git
But I still can't install Node. 
Since curl -sLf -o /dev/null 'https://deb.nodesource.com/node_14.x/dists/buster/Release' returns error 404
How can I solve this problem?

**Comment by thanosk** [comment]
Hello, I also have the same problem and sent an e-mail to info@nodesource.com with the details of my IPs, in a similar manner as for issues #1177 and #1164, but still after 2 weeks I've got no reply. Can you please fix these issues permanently with your akamai servers ? Thank you in advance.

**Comment by igsu** [comment]
@UpworksTeam @thanosk can you provide information on the IP ranges from which you are trying to connect?

**Comment by thanosk** [comment]
My originating IPs are in the 188.42.44.xx range.

**Comment by UpworksTeam** [comment]
My IP in the 135.181.7.xxx

**Comment by igsu** [comment]
@UpworksTeam @thanosk these IP ranges had been generating large amounts of requests. For now they will be unblocked, however, we will be monitoring their behavior and giving you feedback if necessary.

**Comment by thanosk** [comment]
@igsu Thank you, but be aware that of course you are getting large amounts of requests from these IP ranges, as they are major ISPs for data centers in central Europe (VPS, dedicated servers, etc). Perhaps it would be a nice idea to allow having some (community or non-community) (linux repo) mirrors around the globe as well ? That usually solves such issues. I would gladly communicate with the ISP and suggest they host such a large mirror for their infrastructure, as they are already hosting mirrors for the official deb repos, which I guess saves them tons on bandwidth traffic.

**Comment by igsu** [comment]
@thanosk That would be really appreciated, as we are private and unofficial we don't have many mirrors to ease the load.
