### ISSUE TITLE
How do I update node js version?

### ISSUE THREAD

**Issue by ahmedmalick** [nodesource/distributions#1186]
I can't update node js version. Will you please let me know about it.

**Comment by igsu** [comment]
Hi @ahmedmalick, if there is a new version available you can run:
```
sudo apt update
sudo apt install --only-upgrade -y nodejs
```

In case you want to install a new major version, uninstall the current version, clear the cache and use the steps in the readme to set that new version.

**Comment by ahmedmalick** [comment]
hey is this applicable for LTS versions?
