### ISSUE TITLE
No Fedora 34 repo

### ISSUE THREAD

**Issue by heyakyra** [nodesource/distributions#1188]
Fedora 34 is branched, so a version 34 repo should be created: https://rpm.nodesource.com/pub_14.x/fc/

**Comment by igsu** [comment]
Hi @heyakyra,

More than an hour ago we left everything ready for the incoming release:

https://rpm.nodesource.com/pub_10.x/fc/34/x86_64/
https://rpm.nodesource.com/pub_10.x/fc/34/aarch64/

https://rpm.nodesource.com/pub_12.x/fc/34/x86_64/
https://rpm.nodesource.com/pub_12.x/fc/34/aarch64/

https://rpm.nodesource.com/pub_14.x/fc/34/x86_64/
https://rpm.nodesource.com/pub_14.x/fc/34/aarch64/

https://rpm.nodesource.com/pub_15.x/fc/34/x86_64/
https://rpm.nodesource.com/pub_15.x/fc/34/aarch64/

Unfortunately, we do not support distributions on development/test/launch phase, it will be officially supported on Wed 2021-04-21 when its maintenance phase starts.

**Comment by Evoke-PHP** [comment]
It looks like fedora 34 isn't matching.  On a fresh install of Fedora f34,  with the command:
`
curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -`

I get:

```
## Installing the NodeSource Node.js 14.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## You don't appear to be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support. Include your 'distribution package' name: no package provides redhat-release
no package provides centos-release
no package provides cloudlinux-release
no package provides sl-release. 
```

Could this be related to: [https://src.fedoraproject.org/rpms/fedora-release/pull-request/183](https://src.fedoraproject.org/rpms/fedora-release/pull-request/183)

```
rpm -q --whatprovides redhat-release
no package provides redhat-release
```

**Comment by igsu** [comment]
Yes @Evoke-PHP, it is related.
We are actively working to find a solution.

**Comment by igsu** [comment]
Support for the Fedora distribution in version 34 is already in place, please give it a try and let us know.
