### ISSUE TITLE
Alma linux is not supported

### ISSUE THREAD

**Issue by Mythbusters123** [nodesource/distributions#1189]
With the end of CentOS near, Alma Linux has stepped in to take its place. As it is completly compatable with any RHEL 8 distro, I think it should be suported. The distri
bution package is `almalinux-release-8.3-3.el8.x86-64`

**Comment by Mythbusters123** [comment]
This is being fixed

**Comment by Mythbusters123** [comment]
This was done by adding |almalinux in the distro check. It works perfectly fine as it is a fork of RHEL.

**Comment by igsu** [comment]
As of #1195 AlmaLinux OS is supported.
