### ISSUE TITLE
Your distribution, identified as "centos-release-7-9.2009.1.el7.centos.x86_64", is not currently supported

### ISSUE THREAD

**Issue by mertvecnsk** [nodesource/distributions#1191]
Your distribution, identified as "centos-release-7-9.2009.1.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

But i need to install NodeSource Node.js 8.x LTS Carbon repo

**Comment by mertvecnsk** [comment]
After remove this
`if [[ $RC != 0 ]]; then
    print_status "\
Your distribution, identified as \"${DISTRO_PKG}\", \
is not currently supported, please contact NodeSource at \
https://github.com/nodesource/distributions/issues \
if you think this is incorrect or would like your distribution to be considered for support"
    exit 1
fi`

all installed ;)

**Comment by locvfx** [comment]
It does not work anymore when removing the check

hit error: :)

rpm -i --nosignature --force  https://rpm.nodesource.com/pub_20.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://rpm.nodesource.com/pub_20.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm - transfer failed
