### ISSUE TITLE
CVE updates v14.16.1 not yet available

### ISSUE THREAD

**Issue by avimar** [nodesource/distributions#1192]
https://github.com/nodejs/node/releases/tag/v14.16.1 lists multiple CVE fixes released 12 hours ago
... but the latest available seems to be v14.16.0: `Setting up nodejs (14.16.0-1nodesource1)`

I see a recent post that says updates are available within a few hours. Is there some issue?

Thanks!

**Comment by igsu** [comment]
@avimar sorry for the inconvenience. The packages were deployed on `06-Apr-2021 21:11`, please check here:

https://deb.nodesource.com/node_14.x/pool/main/n/nodejs/ 

In case it is a cache problem, I just invalidated it.

Let me know!

**Comment by avimar** [comment]
This is bizarre.

1) On another machine Description:    Debian GNU/Linux 9.11 (stretch)

2) Worked on Description:    Debian GNU/Linux 9.13 (stretch)

3) worked on Description:    Debian GNU/Linux 9.9 (stretch)

4) But on this machine it's still stuck at 14.16.0
Description:    Debian GNU/Linux 8.11 (jessie)

Digging in a bit, it looks like it didn't update the jessie release:
https://deb.nodesource.com/node_14.x/dists/stretch/main/binary-arm64/Packages <-- shows `14.16.1`
https://deb.nodesource.com/node_14.x/dists/jessie/main/binary-arm64/Packages <-- shows `14.16.0`

**Comment by igsu** [comment]
@avimar unfortunately, `Debian Jessie` and `Ubuntu Trusty Tahr` just got discontinued as they are currently EOL, that is the reason.

**Comment by avimar** [comment]
Ah - just in time for multiple CVE fixes. Oh well. Thanks!

**Comment by igsu** [comment]
@avimar The decision to deprecate it was before the announcement of the security release, just bad timing.

In any case we understand how critical it can be and that is why we have generated the release files manually for `Debian Jessie`, they should already be available.

However, keep in mind that it will not receive any more updates.

**Comment by avimar** [comment]
Oh cool, thanks!

I'll find the appropriate time to upgrade that production machine to a supported distro.
