### ISSUE TITLE
Your distribution, identified as "centos-release-7-3.1611.el7.centos.x86_64", is not currently supported

### ISSUE THREAD

**Issue by ichiopro** [nodesource/distributions#1196]
i want to install nodejs on centos server, but i have a problem :

i'm running :
curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -

error :
## Your distribution, identified as "centos-release-7-3.1611.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

anyone can help me, please?

**Comment by Kudratov** [comment]
Similar problem

```
## Installing the NodeSource Node.js 12.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_12.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Your distribution, identified as "centos-release-7-8.2003.0.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by bkdejesus** [comment]
Similar problem, version I have is "centos-release-7-7.1810.2.e17.centos.x86_64"

**Comment by igsu** [comment]
@ichiopro @Kudratov @bkdejesus please check this topic: https://github.com/nodesource/distributions/issues/9.
