### ISSUE TITLE
Error in Installing - setup_12.x On Ubuntu

### ISSUE THREAD

**Issue by AbhiBirla** [nodesource/distributions#1198]
while Installing the setup

Getting Error

https://dl.bintray.com/sbt/debian  InRelease
--
38 | 403  Forbidden [IP: 52.42.217.145 443]

Kindly Provide Solution

![image](https://user-images.githubusercontent.com/69300714/114440252-88372c80-9be7-11eb-9dec-4c39138da05e.png)

**Comment by igsu** [comment]
@AbhiBirla the `403 Forbidden` error you are getting is not related to the packages distributed in this repository, but to https://dl.bintray.com/sbt/debian.

**Comment by AbhiBirla** [comment]
Thanks for the reply
