### ISSUE TITLE
Using setup script behind company proxy

### ISSUE THREAD

**Issue by KoenVingerhoets** [nodesource/distributions#120]
Hi,
I modified the `curl -sL https://deb.nodesource.com/setup | sudo bash -` line to `curl -k https://deb.nodesource.com/setup | sudo bash -` to pass our company proxy.

I also received the "trusty" is not supported message, so I changed to `curl -k https://deb.nodesource.com/setup | sudo -E bash -`. However, my issue is not the -E but the fact that the setup script doesn't copy my -k parameter. 

Wouldn't it be better if the the curl line in setup used to check the eligibility would copy all parameters from the initial curl? (no clue if it's possible... but atm I'm stuck :)

**Comment by KoenVingerhoets** [comment]
Worked around it by `sudo vim /etc/apt/apt.conf`and adding `Acquire::https::deb.nodesource.com::Verify-Peer "false";`

**Comment by wblankenship** [comment]
Hey @KoenVingerhoets,

Instead of piping directly into shell try this:

        curl -k https://deb.nodesource.com/setup > setup.sh
        vim setup.sh
        # edit setup.sh as needed
        chmod +x setup.sh
        ./setup.sh

I don't think it is possible for bash scripts to see the flags passed to other commands that pipe to it.

**Comment by retrohacker** [comment]
We are adding a FAQ to the README.md that covers using proxies.

It will land in https://github.com/nodesource/distributions/pull/308
