### ISSUE TITLE
Your distribution, identified as "n/a", is not currently supported

### ISSUE THREAD

**Issue by jakbin** [nodesource/distributions#1205]
while installing nodejs in parrot os its showing error. "Your distribution, identified as "n/a", is not currently supported"

i am using parrot os 4.10 please fix it.

**Comment by Siyamchunu** [comment]
Getting a similar error on CentOS:7 docker image.
`RUN curl -k --silent --location https://rpm.nodesource.com/setup_15.x | bash - 
	&& yum -y install nodejs \
	&& node -v \
	&& npm -v `
Your distribution, identified as "centos-release-7-9.2009.0.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by JesusPaz** [comment]
@Siyamchunu CentOS 7 is currently supported and any issue during its installation is related to the environment and the network in which the installation is being carried out.

Similar issues with installations on subsystems and behind proxies: #1002 #947 #904 #9 and many more.

It's not a problem related to distributions or compatibility, but to the proxy setup. Also, this comment is not related to the original issue.

**Comment by JesusPaz** [comment]
@jakbin Unfortunately we do not plan to support Parrot OS at this time, but it has been added to our list of requested distributions #1327. 

When your distribution is not supported you can install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).
