### ISSUE TITLE
apt-transport-https has unmet dependencies when installing Node 10 on Debian 9 stretch

### ISSUE THREAD

**Issue by mc-ct** [nodesource/distributions#1206]
I have a Docker image which is built from a Dockerfile as part of a CI/CD job. It was last successfully built 10 days ago, but as of today the build has started failing when trying to run the Node install script. The Dockerfile starts with `drupal:8.6.1-apache` which is based on Debian 9 stretch and it attempts to install Node 10. 

When it runs:
```
curl -fsSL https://deb.nodesource.com/setup_10.x | bash
```
the script fails on the line:
```
apt-get install -y apt-transport-https lsb-release > /dev/null 2>&1
```

I'm able to reproduce the issue and see the error by running a container:
```
docker run -it drupal:8.6.1-apache bash
root@83944fb40f53:/var/www/html# curl -fsSL https://deb.nodesource.com/setup_10.x | bash -
Error executing command, exiting
```
Then while still in the container if I try to install `apt-transport-https` directly so I can see the error:
```
root@83944fb40f53:/var/www/html# apt-get update && apt-get install -y apt-transport-https
...
The following packages have unmet dependencies:
 apt-transport-https : Depends: apt (>= 1.5~alpha4) but 1.4.8 is to be installed
E: Unable to correct problems, you have held broken packages.
```
I've also tried adding an instruction in the Dockerfile to install the latest version of `apt` before the script runs, but that has a significant number of unmet dependencies and dependencies-of-dependencies. 
```
root@83944fb40f53:/var/www/html# apt-get install -y apt=1.5~alpha4
...
E: Version '1.5~alpha4' for 'apt' was not found
root@83944fb40f53:/var/www/html# apt list -a apt
...
apt/stable-updates 1.8.2.3 amd64 [upgradable from: 1.4.8]
apt/stable,stable 1.8.2.2 amd64
apt/oldstable 1.4.11 amd64
apt/oldstable 1.4.10 amd64
apt/now 1.4.8 amd64 [installed,upgradable to: 1.8.2.3]
root@83944fb40f53:/var/www/html# apt-get install -y apt=1.8.2.3
...
The following packages have unmet dependencies:
 apt : Depends: libapt-pkg5.0 (>= 1.7.0~alpha3~) but 1.4.8 is to be installed
       Depends: libgnutls30 (>= 3.6.6) but 3.5.8-5+deb9u5 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by mc-ct** [comment]
I've also tried running some older versions of the script:
```
curl -fsSL https://raw.githubusercontent.com/nodesource/distributions/f2eda2a271e00b52e992c10800b72439aeed1113/deb/setup_10.x | bash -
curl -fsSL https://raw.githubusercontent.com/nodesource/distributions/1e1ee93cffc254f9fa71ca10465585496a7d148d/deb/setup_10.x | bash -
```
...but the same issue still occurred.

**Comment by antoniassiph** [comment]
I could reproduce it using docker image `php:7.3.5-apache-stretch` and scripts for node 10, 12, 16 and LTS. All builds failed.

**Comment by mc-ct** [comment]
A temporary workaround has been discovered for my use case. If I run this before running the `setup_10.x` script:
```
sed -i '2,2s/buster/buster*/' /etc/apt/preferences.d/argon2-buster
```
... it updates the `apt` preferences file in the container to be:
```
Package: *
Pin: release n=buster*
Pin-Priority: -10

Package: libargon2*
Pin: release n=buster
Pin-Priority: 990
```
Adding the asterisk on line 2 allows `apt` to pull from `buster-updates`, which, in turn, allows the installation of `apt-transport-https` to succeed during the `setup_10.x` script.

**Comment by santiago-ley** [comment]
In my case, I am working with a docker image based on `php:7.2.15-apache-stretch`.
At the end, I figured out that the script was trying to install `apt-transport-https`  version=`1.4.11`.

However when running `apt apt-transport-https -v` inside a container built before this problem appeared, I got that the version was `1.4.10`. So I changed it and it was solved.

Just added the install before the node curl.

    FROM php:7.2.15-apache-stretch
    ...
    RUN apt-get update
    ...
    RUN apt-get install -y apt-transport-https=1.4.10
    RUN curl -sL https://deb.nodesource.com/setup_15.x | bash -

**Comment by santiago-ley** [comment]
Also, when I run `apt install -y apt-transport-https` inside the old container, I get that it's at the newest version (1.4.10). Then if I run `apt update && apt install -y apt-transport-https` I get the same error when it tries to install version 1.4.11:

`apt-transport-https : Depends: apt (>= 1.5~alpha4) but 1.4.8 is to be installed`

**Comment by JesusPaz** [comment]
At this time we no longer support Node.js version 10. We recommend installing one of the currently supported versions.
