### ISSUE TITLE
Incorrect MIME type (text/html) used for all(?) Packages.gz

### ISSUE THREAD

**Issue by rhencke** [nodesource/distributions#1208]
The current distribution URLs (at least) are broken:

https://deb.nodesource.com/node_14.x/dists/focal/main/binary-amd64/Packages.gz
https://deb.nodesource.com/node_15.x/dists/focal/main/binary-amd64/Packages.gz
https://deb.nodesource.com/node_16.x/dists/focal/main/binary-amd64/Packages.gz

They are being served up as `content-type: text/html` instead of the correct content type which you can verify by clicking one.

(Incorrect MIME type is also on GPG signatures it seems as `text/html`)

**Comment by riosje** [comment]
Fixed mime-types for `.gz` and `gpg` files
