### ISSUE TITLE
404  Not Found [IP: 91.189.88.151 80]

### ISSUE THREAD

**Issue by dehimer** [nodesource/distributions#121]
odroid@odroid:~$ wget -qO- https://deb.nodesource.com/setup_0.12 | sudo -E bash -

## Populating apt-get cache...

+ apt-get update
Ign http://ports.ubuntu.com saucy InRelease<br>
Ign http://ports.ubuntu.com saucy-updates InRelease<br>
Ign http://ports.ubuntu.com saucy-security InRelease<br>
Ign http://ports.ubuntu.com saucy Release.gpg<br>
Ign http://ports.ubuntu.com saucy-updates Release.gpg<br>
Ign http://ports.ubuntu.com saucy-security Release.gpg<br>
Ign http://ports.ubuntu.com saucy Release<br>
Ign http://ports.ubuntu.com saucy-updates Release<br>
Ign http://ports.ubuntu.com saucy-security Release<br>
Ign http://ports.ubuntu.com saucy/main Sources/DiffIndex<br>
Ign http://ports.ubuntu.com saucy/restricted Sources/DiffIndex<br>
Ign http://ports.ubuntu.com saucy/universe Sources/DiffIndex<br>
Ign http://ports.ubuntu.com saucy/multiverse Sources/DiffIndex<br>
Ign http://ports.ubuntu.com saucy/main armhf Packages/DiffIndex<br>
Ign http://ports.ubuntu.com saucy/restricted armhf Packages/DiffIndex<br>
Ign http://ports.ubuntu.com saucy/universe armhf Packages/DiffIndex<br>
Ign http://ports.ubuntu.com saucy/multiverse armhf Packages/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-updates/main Sources/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-updates/restricted Sources/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-updates/universe Sources/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-updates/multiverse Sources/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-updates/main armhf Packages/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-updates/restricted armhf Packages/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-updates/universe armhf Packages/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-updates/multiverse armhf Packages/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-security/main Sources/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-security/restricted Sources/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-security/universe Sources/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-security/multiverse Sources/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-security/main armhf Packages/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-security/restricted armhf Packages/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-security/universe armhf Packages/DiffIndex<br>
Ign http://ports.ubuntu.com saucy-security/multiverse armhf Packages/DiffIndex<br>
Ign http://ports.ubuntu.com saucy/main Translation-en_US<br>
Ign http://ports.ubuntu.com saucy/main Translation-en<br>
Ign http://ports.ubuntu.com saucy/multiverse Translation-en_US<br>
Ign http://ports.ubuntu.com saucy/multiverse Translation-en<br>
Ign http://ports.ubuntu.com saucy/restricted Translation-en_US<br>
Ign http://ports.ubuntu.com saucy/restricted Translation-en<br>
Ign http://ports.ubuntu.com saucy/universe Translation-en_US<br>
Ign http://ports.ubuntu.com saucy/universe Translation-en<br>
Ign http://ports.ubuntu.com saucy-updates/main Translation-en_US<br>
Ign http://ports.ubuntu.com saucy-updates/main Translation-en<br>
Ign http://ports.ubuntu.com saucy-updates/multiverse Translation-en_US<br>
Ign http://ports.ubuntu.com saucy-updates/multiverse Translation-en<br>
Ign http://ports.ubuntu.com saucy-updates/restricted Translation-en_US<br>
Ign http://ports.ubuntu.com saucy-updates/restricted Translation-en<br>
Ign http://ports.ubuntu.com saucy-updates/universe Translation-en_US<br>
Ign http://ports.ubuntu.com saucy-updates/universe Translation-en<br>
Ign http://ports.ubuntu.com saucy-security/main Translation-en_US<br>
Ign http://ports.ubuntu.com saucy-security/main Translation-en<br>
Ign http://ports.ubuntu.com saucy-security/multiverse Translation-en_US<br>
Ign http://ports.ubuntu.com saucy-security/multiverse Translation-en<br>
Ign http://ports.ubuntu.com saucy-security/restricted Translation-en_US<br>
Ign http://ports.ubuntu.com saucy-security/restricted Translation-en<br>
Ign http://ports.ubuntu.com saucy-security/universe Translation-en_US<br>
Ign http://ports.ubuntu.com saucy-security/universe Translation-en<br>
Err http://ports.ubuntu.com saucy/main Sources<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy/restricted Sources<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy/universe Sources<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy/multiverse Sources<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy/main armhf Packages<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy/restricted armhf Packages<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy/universe armhf Packages<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy/multiverse armhf Packages<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-updates/main Sources<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-updates/restricted Sources<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-updates/universe Sources<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-updates/multiverse Sources<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-updates/main armhf Packages<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-updates/restricted armhf Packages<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-updates/universe armhf Packages<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-updates/multiverse armhf Packages<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-security/main Sources<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-security/restricted Sources<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-security/universe Sources<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-security/multiverse Sources<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-security/main armhf Packages<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-security/restricted armhf Packages<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-security/universe armhf Packages<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
Err http://ports.ubuntu.com saucy-security/multiverse armhf Packages<br>
  404  Not Found [IP: 91.189.88.151 80]<br>
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy/main/source/Sources  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy/restricted/source/Sources  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy/universe/source/Sources  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy/multiverse/source/Sources  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy/main/binary-armhf/Packages  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy/restricted/binary-armhf/Packages  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy/universe/binary-armhf/Packages  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy/multiverse/binary-armhf/Packages  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-updates/main/source/Sources  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-updates/restricted/source/Sources  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-updates/universe/source/Sources  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-updates/multiverse/source/Sources  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-updates/main/binary-armhf/Packages  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-updates/restricted/binary-armhf/Packages  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-updates/universe/binary-armhf/Packages  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-updates/multiverse/binary-armhf/Packages  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-security/main/source/Sources  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-security/restricted/source/Sources  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-security/universe/source/Sources  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-security/multiverse/source/Sources  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-security/main/binary-armhf/Packages  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-security/restricted/binary-armhf/Packages  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-security/universe/binary-armhf/Packages  404  Not Found [IP: 91.189.88.151 80]<br>

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/saucy-security/multiverse/binary-armhf/Packages  404  Not Found [IP: 91.189.88.151 80]<br>

E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting<br>

**Comment by dehimer** [comment]
odroid@odroid:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 13.10
Release:	13.10
Codename:	saucy

**Comment by dehimer** [comment]
setup_0.10 lead to same result

**Comment by dehimer** [comment]
Sorry. My problem.

**Comment by ak131217** [comment]
same problem...
I have installed Ubuntu 13.10 on my android smartphone through linuxonandroid app
but when I type "sudo apt-get update" it display same error as above...

u0_a89@msm8610:/ $
u0_a89@msm8610:/ $ su
root@msm8610:/ # /data/data/com.zpwebsites.linuxonandonandroid/files/busybox chroot                        /data/local/mnt /root/init.sh
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
Config file loaded
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
A VNC server is already running as :0

If you see the message 'New 'X' Desktop is localhost:0' then you are ready to VNC into your ubuntu OS..

If connection from a different machine on the same network as the android device use the address below:
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
wlan0: error fetching interface information: Device not found

If using androidVNC, change the 'Color Format' setting to 24-bit colour, and once you've VNC'd in, change the 'input mode' to touchpad (in settings)
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
 * Starting OpenBSD Secure Shell server sshd       ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
                                              [ OK ]

To shut down the Linux environment, just enter 'exit' at this terminal - and WAIT for all shutdown routines to finish!

ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
bash: no job control in this shell
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
root@localhost:/# root@localhost:/# ERROR: ld.so: object '/vendor/lib/libNimsWrap.so' from LD_PRELOAD cannot be preloaded: ignored.
Ign http://ports.ubuntu.com saucy InRelease
Ign http://ports.ubuntu.com saucy Release.gpg
Ign http://ports.ubuntu.com saucy Release
Ign http://ports.ubuntu.com saucy/main Sources/DiffIndex
Ign http://ppa.launchpad.net saucy InRelease
Ign http://ports.ubuntu.com saucy/restricted Sources/DiffIndex
Ign http://ports.ubuntu.com saucy/universe Sources/DiffIndex
Ign http://ports.ubuntu.com saucy/main armhf Packages/DiffIndex
Ign http://ports.ubuntu.com saucy/restricted armhf Packages/DiffIndex
Ign http://ports.ubuntu.com saucy/universe armhf Packages/DiffIndex
Hit http://ppa.launchpad.net saucy Release.gpg
Hit http://ppa.launchpad.net saucy Release
Hit http://ppa.launchpad.net saucy/main armhf Packages
Ign http://ppa.launchpad.net saucy/main Translation-en
Ign http://ports.ubuntu.com saucy/main Translation-enIgn http://ports.ubuntu.com saucy/restricted Translation-en
Ign http://ports.ubuntu.com saucy/universe Translation-en
Err http://ports.ubuntu.com saucy/main Sources
  404  Not Found [IP: 91.189.88.151 80]
Err http://ports.ubuntu.com saucy/restricted Sources
  404  Not Found [IP: 91.189.88.151 80]
Err http://ports.ubuntu.com saucy/universe Sources
  404  Not Found [IP: 91.189.88.151 80]
Err http://ports.ubuntu.com saucy/main armhf Packages  404  Not Found [IP: 91.189.88.151 80]
Err http://ports.ubuntu.com saucy/restricted armhf Packages
  404  Not Found [IP: 91.189.88.151 80]
Err http://ports.ubuntu.com saucy/universe armhf Packages
  404  Not Found [IP: 91.189.88.151 80]
W: Failed to fetch http://ports.ubuntu.com/dists/saucy/main/source/Sources  404  Not Found [IP: 91.189.88.151 80]

W: Failed to fetch http://ports.ubuntu.com/dists/saucy/restricted/source/Sources  404  Not Found [IP: 91.189.88.151 80]

W: Failed to fetch http://ports.ubuntu.com/dists/saucy/universe/source/Sources  404  Not Found [IP: 91.189.88.151 80]

W: Failed to fetch http://ports.ubuntu.com/dists/saucy/main/binary-armhf/Packages  404  Not Found [IP: 91.189.88.151 80]

W: Failed to fetch http://ports.ubuntu.com/dists/saucy/restricted/binary-armhf/Packages  404  Not Found [IP: 91.189.88.151 80]

W: Failed to fetch http://ports.ubuntu.com/dists/saucy/universe/binary-armhf/Packages  404  Not Found [IP: 91.189.88.151 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
root@localhost:/#

pls solve it... thanku...

**Comment by chrislea** [comment]
Ubuntu saucy is no longer supported by Canonical, so we do not support it either. Please look [here](https://github.com/nodesource/distributions/) for a list of supported distributions.
