### ISSUE TITLE
14.x (Ubuntu Bionic) still comes with npm 6

### ISSUE THREAD

**Issue by scy** [nodesource/distributions#1218]
Hi there!

I've installed Node 14.17.0 on Ubuntu Bionic, and it comes with npm 6.14.13. Now I've seen in #1101 that you're packaging the npm versions “available at the time”, but Node 14.17.0 was released in May and npm 7 became stable in February. Am I misunderstanding something here?

Thanks in advance for any clarification!

**Comment by igsu** [comment]
Hi @scy 

Yes, the misunderstanding is that we package and distribute the version of `npm` that is provided in the [Node.js binaries](https://nodejs.org/en/download/). Although `7.x.x` is available, the latest binaries, for example, distributed in the bundles, have version `6.14.14`.
