### ISSUE TITLE
Unable to install Node.js 14.x on RHEL 6 and CentOS

### ISSUE THREAD

**Issue by mileacolaco** [nodesource/distributions#1219]
Hi,

Our team is facing issue in upgrading node version from Node 10.x to 14.x on a RHEL6 server.

**Platform**: redhat-release-server-6Server-6.10.0.13.el6_10.9.x86_64

We have tried installing the node 14 version via rpm and also with nvm and n. But we are getting errors with all the options.

```
1.	Node 14 installation by sudo curl -sL https://rpm.nodesource.com/setup_14.x | bash -

## Installing the NodeSource Node.js 14.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_14.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "redhat-release-server-6Server-6.10.0.13.el6_10.9.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
            

2.	Installing node via n and nvm.

It installs node server but for node -v it throws following error:

node: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by node)
node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by node)
node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by node)
node: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by node)
node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by node)
```

Can someone help in letting us know if node14 can be installed and used successfully on a rhel 6 server.

Also if possible is there any link that can provide me with the list of supported platforms for a given node version. 

Do note that we have also tried upgrading to Node 12 and same issues are seen as mentioned above for node 14.

Regards,
Milea Colaco

**Comment by deltoura** [comment]
Hi,
RHEL6 is end-of-life (https://endoflife.software/operating-systems/linux/red-hat-enterprise-linux-rhel). Not only Node.js can't be upgraded on this OS, but probably other packages as well.
You should consider upgrading to a more recent OS.
