### ISSUE TITLE
Can't install on Fedora 34 anymore

### ISSUE THREAD

**Issue by ricardoalonso** [nodesource/distributions#1222]
The application is asking for specific packages from EL:

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release

But fedora is among those and the the package that provides the /etc/redhat-release file is the fedora-release.rpm

**Comment by bpowers** [comment]
its not just the install script -- the actual `nodesource-release` rpm package depends on redhat-release as well:

```
+ curl -sL -o '/tmp/tmp.7wrUC6dZP0' 'https://rpm.nodesource.com/pub_16.x/fc/34/x86_64/nodesource-release-fc34-1.noarch.rpm'

## Installing release setup RPM...

+ rpm -i --nosignature --force '/tmp/tmp.7wrUC6dZP0'
error: Failed dependencies:
	redhat-release >= fc34 is needed by nodesource-release-fc34-1.noarch
Error executing command, exiting

```

**Comment by bpowers** [comment]
(I was able to manually unpack the nodesource-release RPM with `rpm2cpio /tmp/tmp.7wrUC6dZP0 | cpio -idmv` and copy the repo defintiion and GPG key to the right place to install `nodejs`, so it looks like jut a packaging problem

**Comment by sonnyp** [comment]
A bit off topic - sorry but FYI Node.js 16 is available on Fedora 34

```sh
sud dnf module reset nodejs
sudo dnf module install nodejs:16/default
```

https://fedoraproject.org/wiki/Changes/Nodejs16

**Comment by jdavidavendano** [comment]
Hi, we have detected this issue and we are currently working to solve it.

**Comment by igsu** [comment]
Support for the Fedora distribution in version 34 is already in place, please give it a try and let us know.

**Comment by binarykitchen** [comment]
Curious when this will be upgraded again to latest Node LTS v16.13?
