### ISSUE TITLE
Hard-coded Fedora version prevents upgrade

### ISSUE THREAD

**Issue by deltoura** [nodesource/distributions#1224]
The Fedora version is hard-coded in the repository configuration, e.g. in `/etc/yum.repos.d/nodesource-fc33.repo`:
```
baseurl=https://rpm.nodesource.com/pub_14.x/fc/33/$basearch
```

This prevents upgrade from F33 to F34.
Should use `$releasever` variable instead (and rename file to `nodesource-fedora.repo`):
```
baseurl=https://rpm.nodesource.com/pub_14.x/fc/$releasever/$basearch
```

I would be glad to help and propose a PR (for other Feodra-releated issues as well https://github.com/nodesource/distributions/issues/1188 and https://github.com/nodesource/distributions/issues/1222) but I could not find the sources for the nodesource-release package?

**Comment by JesusPaz** [comment]
This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).
