### ISSUE TITLE
Can't install nodeJs 12.x / 14.x on Ubuntu 20.04

### ISSUE THREAD

**Issue by Shahpnico** [nodesource/distributions#1226]
When following installation procedure, the nodeJs installed is 10.19.0 :
![image](https://user-images.githubusercontent.com/50636714/122417790-0a4a2580-cf8a-11eb-9a9f-92601c142b93.png)

The command `sudo apt install nodejs` indicates that this version is the latest :
![image](https://user-images.githubusercontent.com/50636714/122418058-41b8d200-cf8a-11eb-8521-44d7ffdabd6d.png)

The command curl supposed to download the setup script indicates that these versions of nodeJs aren't supported on Ubuntu 20.04, which is surprising considering that it is the latest Ubuntu distrib :
![image](https://user-images.githubusercontent.com/50636714/122417885-1cc45f00-cf8a-11eb-87de-10f064296c6f.png)

Therefore, I am looking forward to reading your thought on this problem, and would like to know if anybody has encountered/solved the issue

**Comment by tambasco** [comment]
:~$ curl -fsSL https://rpm.nodesource.com/setup_lts.x | sudo bash -

## Installing the NodeSource Node.js 14.x repo...


## Inspecting system...


## You don't appear to be running an Enterprise Linux based system,
please contact NodeSource at https://github.com/nodesource/distributions/issues
if you think this is incorrect or would like your distribution to be considered
for support.

________________________________________________________________________________________

I got that Ubuntu 20.04 is not a Enterprise Linux based system. No update, stagnated on v10.19.0

**Comment by Shahpnico** [comment]
Thank you tambasco for replying!

I see... So is it really impossible for ubuntu users to update their OS, and keep using nodeJs, angular and others frameworks using node ?? 
Seems really odd, isn't it?

**Comment by tambasco** [comment]
It's really weird! But researching I found an alternative that worked. 
You install nvm - Node Version Manager
using curl or wget

$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
$ wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

List the versions you have installed on your pc:
$ nvm ls

List the versions available for download:
$ nvm ls-remote

Install the desired version: 
$ nvm install vX.X.X


Unistall a not desired version:
$ nvm uninstall vX.X.X

Alternate to the version you want to run:
$ nvm use vX.X.X

Uses the latest version:
$ nvm use node

Hope it works for you too Shahpnico!

**Comment by Shahpnico** [comment]
Great! I am currently in remote work and can't access this PC, but will get it a try by tomorrow. Then I'll tell you whether or not it has worked...

Really hope it will, fingers crossed!
