### ISSUE TITLE
Unable to install  Node 14.x in Ubuntu 18.04

### ISSUE THREAD

**Issue by subhasisbanik** [nodesource/distributions#1227]
Commands used:
# Using Ubuntu
curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs

Issues faced:

## Populating apt-get cache...

+ apt-get update
Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:4 https://deb.nodesource.com/node_14.x bionic InRelease [4584 B]
Hit:5 https://download.docker.com/linux/ubuntu bionic InRelease
Get:6 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2099 kB]
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:8 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1736 kB]
Err:4 https://deb.nodesource.com/node_14.x bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1655A0AB68576280
Reading package lists... Done
W: GPG error: https://deb.nodesource.com/node_14.x bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1655A0AB68576280
E: The repository 'https://deb.nodesource.com/node_14.x bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting

**Comment by subhasisbanik** [comment]
I had to run the below commands to remove the PPAs and download Node and NPM from https://nodejs.org/dist/v14.17.1/node-v14.17.1-linux-x64.tar.xz and manually place them in /usr/bin 

sudo rm -rf /var/lib/apt/lists/*
sudo rm -rf /etc/apt/sources.list.d/*
sudo apt-get update

**Comment by sandyarmstrong** [comment]
Similar output here, on Ubuntu 18.04.5 (as provided from Azure's VM image). Ran this as root:

```
curl -fsSL https://deb.nodesource.com/setup_14.x | bash

## Installing the NodeSource Node.js 14.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:4 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:6 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2099 kB]
Get:7 https://apt.kitware.com/ubuntu bionic InRelease [6801 B]
Err:7 https://apt.kitware.com/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DE19EB17684BA42D
Reading package lists... Done
W: http://azure.archive.ubuntu.com/ubuntu/dists/bionic/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/kitware.gpg are ignored as the file has an unsupported filetype.
W: http://azure.archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/kitware.gpg are ignored as the file has an unsupported filetype.
W: http://azure.archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/kitware.gpg are ignored as the file has an unsupported filetype.
W: https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/kitware.gpg are ignored as the file has an unsupported filetype.
W: http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/kitware.gpg are ignored as the file has an unsupported filetype.
W: https://apt.kitware.com/ubuntu/dists/bionic/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/kitware.gpg are ignored as the file has an unsupported filetype.
W: GPG error: https://apt.kitware.com/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DE19EB17684BA42D
E: The repository 'https://apt.kitware.com/ubuntu bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting
```

**Comment by m-terlinde** [comment]
Hey guys,

I had the same issue today.
The permissions for the key were not set correctly by the script. I don't know why, but I think GPG complained about too strict permissions.

A `sudo chmod +644 /usr/share/keyrings/nodesource.gpg` did the trick and the apt-update went through.
Maybe this could be added to the installation script?

Hope this helps,
Matthias

**Comment by sglajchEG** [comment]
> I had to run the below commands to remove the PPAs and download Node and NPM from https://nodejs.org/dist/v14.17.1/node-v14.17.1-linux-x64.tar.xz and manually place them in /usr/bin
> 
> sudo rm -rf /var/lib/apt/lists/*
> sudo rm -rf /etc/apt/sources.list.d/*
> sudo apt-get update

Do NOT run these instructions, reader on the internet.  This will remove ALL of your PPAs.  Please at least limit your command to node PPAs if you're going to post something so destructive.
Luckily I caught it in time and didn't run it myself.

m-terlinde's commant above worked for me.  The file was 400 and changing to 644 worked.

**Comment by m-terlinde** [comment]
Happy to hear, @sglajchEG!
Maybe I should do a FAQ entry for this issue.
Or the maintainer could add this little chmod to the installation script.

**Comment by armanism24** [comment]
> Hey guys,
> 
> I had the same issue today. The permissions for the key were not set correctly by the script. I don't know why, but I think GPG complained about too strict permissions.
> 
> A `sudo chmod +644 /usr/share/keyrings/nodesource.gpg` did the trick and the apt-update went through. Maybe this could be added to the installation script?
> 
> Hope this helps, Matthias

this works well
