### ISSUE TITLE
Add support for Rocky Linux

### ISSUE THREAD

**Issue by thejjw** [nodesource/distributions#1229]
Hello,

I saw request for Alma Linux on #1166 has been resolved and implemented via #1195 .
[Rocky Linux](https://rockylinux.org/) should behave the same since they both derive from rhel 8(8.4).
Could you consider adding 'rocky' string to enterprise linux check?

Thanks.

```
'distribution package' name: rocky-release-8.4-26.el8.noarch.
```

**Comment by igsu** [comment]
Duplicated of #1228
