### ISSUE TITLE
Unable to install node 8.x in macBig Sur

### ISSUE THREAD

**Issue by aiswariaDam** [nodesource/distributions#1233]
Getting below error in terminal 
## You don't appear to be running an Enterprise Linux based system,
please contact NodeSource at https://github.com/nodesource/distributions/issues
if you think this is incorrect or would like your distribution to be considered
for support.

**Comment by igsu** [comment]
The binaries have been packaged for Linux distributions compatibility.
Check more MacOS installing options [here](https://nodejs.org/en/download/).
