### ISSUE TITLE
Node v14.17.3 not available from nodesource Ubuntu Focal

### ISSUE THREAD

**Issue by Stromos** [nodesource/distributions#1235]
Trying to update to v14.17.3 in Ubuntu

Updating Node.js from v14.17.2 to v14.17.3...
Updating from NodeSource...
nodejs is already the newest version (14.17.2-deb-1nodesource1).

Not sure if this is a bug or if the build is just not available yet.

**Comment by bogdan-13** [comment]
> 2021-07-05, Version 14.17.3 'Fermium' (LTS), @richardlau
Notable Changes

Node.js 14.17.2 introduced a regression in the Windows installer on non-English locales that is being fixed in this release. There is no need to download this release if you are not using the Windows installer.

**Comment by Stromos** [comment]
Thanks!
