### ISSUE TITLE
Error installing on buster

### ISSUE THREAD

**Issue by thpglobal** [nodesource/distributions#1236]
I am unable to get this to work on Debian 10 now. It 
## Populating apt-get cache...

+ apt-get update
Hit:1 http://packages.microsoft.com/repos/code stable InRelease
Ign:2 https://storage.googleapis.com/cros-packages/91 buster InRelease                                             
Hit:3 https://deb.debian.org/debian buster InRelease                                                               
Hit:4 https://deb.debian.org/debian-security buster/updates InRelease           
Hit:5 https://packages.cloud.google.com/apt cloud-sdk InRelease                 
Hit:6 https://storage.googleapis.com/cros-packages/91 buster Release            
Get:7 https://packages.sury.org/php buster InRelease [6,837 B]
Reading package lists... Done        
E: Repository 'https://packages.sury.org/php buster InRelease' changed its 'Suite' value from '' to 'buster'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Error executing command, exiting

I have no idea what to do about this....

**Comment by Ratfiend** [comment]
I also encountered an error during the installation:

`curl -fsSL https://deb.nodesource.com/setup_12.x | bash -`

## Installing the NodeSource Node.js 12.x repo...

## Populating apt-get cache...

+ apt-get update
OK:1 https://download.docker.com/linux/debian buster InRelease
Holen:2 https://archive.raspberrypi.org/debian buster InRelease [32,6 kB]
Holen:3 http://raspbian.raspberrypi.org/raspbian buster InRelease [15,0 kB]
Holen:4 https://archive.raspberrypi.org/debian buster/main armhf Packages [376 kB]
Holen:5 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13,0 MB]
**Fehl:6 https://ookla.bintray.com/debian buster InRelease
  403  Forbidden [IP: 35.164.5.2 443]**
Paketlisten werden gelesen... Fertig
E: Fehlschlag beim Holen von https://ookla.bintray.com/debian/dists/buster/InRelease 403  Forbidden [IP: 35.164.5.2 443]
E: Das Depot »https://ookla.bintray.com/debian buster InRelease« ist nicht mehr signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
Error executing command, exiting

**Comment by JesusPaz** [comment]
Our script executes in the first lines `apt-get update`. Therefore, this error is related to your environment configuration. Thank you for contacting us.
