### ISSUE TITLE
Node 0.12 is not supported on redhat-release-server-7.1-1.el7.x86_64?

### ISSUE THREAD

**Issue by Pikdo** [nodesource/distributions#124]
I tried to install nodejs 0.12 lastest version in RHEL redhat-release-server-7.1-1.el7.x86_64, I put:  "curl -sL https://rpm.nodesource.com/setup_0.12 | bash -" but I got this message:

Installing the NodeSource Node.js 0.12 repo...
Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release
+ uname -m

Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_0.12/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

Your distribution, identified as "redhat-release-server-7.1-1.el7.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Thank you any help!!!

**Comment by shaiksphere** [comment]
I hit the same issue. Please support to the same.

Your distribution, identified as "redhat-release-workstation-7.1-1.el7.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by shaiksphere** [comment]
Dug more into the setup steps.

Apparently the missing piece is **nodesource-release-el7-1.noarch.rpm**

It exists in https://rpm.nodesource.com/**pub**/el/7/x86_64/ but does **not** exist in https://rpm.nodesource.com/**pub_0.12**/el/7/x86_64/

**Comment by tdietrich513** [comment]
Also getting this issue. Please add support.

**Comment by marpada** [comment]
+1, the packages are there but the release package is missing

**Comment by shaiksphere** [comment]
For the time being, this is the workaround I am using

    #
    # Login as 'root' before performing this operation
    #
    
    $ yum -y groupinstall 'Development Tools'
    
    $ wget https://nodejs.org/dist/latest/node-v5.0.0-linux-x64.tar.gz
    $ tar zxvf node-v5.0.0-linux-x64.tar.gz -C /usr/local --strip-components 1
    $ rm -f node-v5.0.0-linux-x64.tar.gz

**Comment by marpada** [comment]
I ended up adding the repo url and importing the key manually:

https://gist.github.com/marpada/f067a3d50defb122066d

**Comment by Pikdo** [comment]
Thank you for your help

Can I install node 0.12 with that last steps?

Attt: Ale

**Comment by marpada** [comment]
Yes

```
# yum info nodejs
Loaded plugins: amazon-id, rhui-lb
Installed Packages
Name        : nodejs
Arch        : x86_64
Version     : 0.12.7
Release     : 1nodesource.el7.centos
Size        : 20 M
Repo        : installed
From repo   : nodesource
Summary     : JavaScript runtime
URL         : http://nodejs.org
License     : MIT and ASL 2.0 and ISC and BSD
Description : Node.js is a platform built on Chrome\'s JavaScript runtime
            : for easily building fast, scalable network applications.
            : Node.js uses an event-driven, non-blocking I/O model that
            : makes it lightweight and efficient, perfect for data-intensive
            : real-time applications that run across distributed devices.
```

**Comment by retrohacker** [comment]
RPMs for el7 are now being built and live in https://rpm.nodesource.com/pub_0.12/el/7/x86_64/

Closing this issue as stale

If you continue to have issues with the setup script for Node.js 0.12 on EL7, please reopen this issue and we can help debug!
