### ISSUE TITLE
Buster not supported ?

### ISSUE THREAD

**Issue by NebzHB** [nodesource/distributions#1244]
## Populating apt-get cache...

+ apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 https://deb.nodesource.com/node_14.x buster InRelease
Hit:3 http://deb.debian.org/debian buster InRelease
Hit:4 http://deb.debian.org/debian-security buster/updates InRelease
Hit:5 http://deb.debian.org/debian buster-updates InRelease
Reading package lists...

## Confirming "buster" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_14.x/dists/buster/Release'

**Comment by yannoff** [comment]
Same here 👍 

**Command**
```
curl -skS http://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
curl -skL http://deb.nodesource.com/setup_12.x | bash - 
```

**Output**
```
OK
deb http://dl.yarnpkg.com/debian/ stable main

## Installing the NodeSource Node.js 12.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://security.debian.org/debian-security buster/updates InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Get:4 http://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Get:5 http://dl.yarnpkg.com/debian stable/main amd64 Packages [10.1 kB]
Get:6 http://dl.yarnpkg.com/debian stable/main all Packages [10.1 kB]
Fetched 37.2 kB in 0s (89.5 kB/s)
Reading package lists...

## Installing packages required for setup: lsb-release...

+ apt-get install -y lsb-release > /dev/null 2>&1

## Confirming "buster" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_12.x/dists/buster/Release'

## Your distribution, identified as "buster", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

````

**Comment by jrj2211** [comment]
I'm getting this too, is this really not supported? Debian stretch is oldold stable and buster is now oldstable.

**Comment by igsu** [comment]
Debian `buster` is fully supported, there must be something else in your setup that is preventing the installation from being successful, please share more information about your setup if this is still an issue.
