### ISSUE TITLE
Nodesource 14 and 16 install on Debian buster still require python2

### ISSUE THREAD

**Issue by BretFisher** [nodesource/distributions#1249]
I saw other tickets somewhat related to this but thought I'd start one for the specific issue of, sorry if it's a dupe.

I saw some upstream dependencies that had to wait for moving off python2 but that all seems done, and it seems CentOS installer works with python3, so:

**Is there any update on a plan to replace python2 with python3 in apt-based installs?**

## how to reproduce

`docker run -it debian:buster bash`

```shell
apt update && apt install -y curl gnupg2
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - 
echo 'deb https://deb.nodesource.com/node_16.x buster main' > /etc/apt/sources.list.d/nodesource.list
echo 'deb-src https://deb.nodesource.com/node_16.x buster main' >> /etc/apt/sources.list.d/nodesource.list
apt update && apt install nodejs
```

Result text shows:

```
The following additional packages will be installed:
  bzip2 file libexpat1 libmagic-mgc libmagic1 libpython-stdlib libpython2-stdlib libpython2.7-minimal
  libpython2.7-stdlib mime-support python python-minimal python2 python2-minimal python2.7 python2.7-minimal xz-utils
```

Same issue on `node_14.x`

**Comment by igsu** [comment]
Hi @BretFisher, thanks for reporting this. We are already working on fixing this behavior.

**Comment by igsu** [comment]
The dependencies issue has been fixed.
