### ISSUE TITLE
buster InRelease changed its 'Suite' value from 'stable' to 'oldstable'

### ISSUE THREAD

**Issue by evenSosaAkido** [nodesource/distributions#1251]
Hi I'm getting an issue when running 
`curl -sL https://deb.nodesource.com/setup_12.x | bash -` from a dockerfile

```
Step 13/34 : RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
 ---> Running in 57cecb99a0c6

## Installing the NodeSource Node.js 12.x repo...


## Populating apt-get cache...

+ apt-get update
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Get:5 https://dl.yarnpkg.com/debian stable/main amd64 Packages [10.1 kB]
Get:6 https://dl.yarnpkg.com/debian stable/main all Packages [10.1 kB]
Reading package lists...
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'
Error executing command, exiting
```

I read you need to just accept the changes but the way the script is set I think we cannot answer any questions. Do you know any workarounds for this?

**Comment by feline-fanatic** [comment]
I'm running into the same issue. I think `--allow-releaseinfo-change` needs to be added to the `apt-get update` command.

**Comment by flgraveline** [comment]
```
curl -sL https://deb.nodesource.com/setup_12.x | sed "s/exec_cmd 'apt-get update'/exec_cmd 'apt-get --allow-releaseinfo-change update'/" | bash -
```

I may try something like that temporarily to see if it fixes my issue, basically appending the flag after the `apt-get` in the script :thinking:

**Comment by evenSosaAkido** [comment]
> Running into the same issue in my DockerFile using `nodesource/setup_8.x`.
> 
> I'm using a temporary dirty fix to see if it solves the issue, basically appending the flag after the `apt-get` in the script 🤔
> 
> ```
> curl -sL https://deb.nodesource.com/setup_8.x | sed "s/exec_cmd 'apt-get update'/exec_cmd 'apt-get --allow-releaseinfo-change update'/" | bash -
> ```

@flgraveline did that work for you? I wasn't able to make sed work that way

**Comment by flgraveline** [comment]
> > Running into the same issue in my DockerFile using `nodesource/setup_8.x`.
> > I'm using a temporary dirty fix to see if it solves the issue, basically appending the flag after the `apt-get` in the script thinking
> > ```
> > curl -sL https://deb.nodesource.com/setup_8.x | sed "s/exec_cmd 'apt-get update'/exec_cmd 'apt-get --allow-releaseinfo-change update'/" | bash -
> > ```
> 
> @flgraveline did that work for you? I wasn't able to make sed work that way

Seems to have done the trick for me, replaces every `exec_cmd 'apt-get update'` with `exec_cmd 'apt-get --allow-releaseinfo-change update'`.

**Comment by evenSosaAkido** [comment]
@flgraveline tried to play around with my own script using your logic but didn't do the replacement for some reason. But I just gave it a shot with the actual setup_12.x and it worked perfectly, thanks a lot!

**Comment by JesusPaz** [comment]
This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).

**Comment by alibajelan** [comment]
just change dns to 8.8.8.8 , 4.4.4.4
