### ISSUE TITLE
Any request to the urls *.nodesource.com blocked code 403

### ISSUE THREAD

**Issue by salamp** [nodesource/distributions#1252]
Hi,
Recently we discovered that updates from repository *.nodesource.com not works. As well as new installations.
We discovered that any requests from this network segment denied:

```
inetnum: 23.109.52.0 - 23.109.55.255
netname: SERVERS-COM-AMS2
country: NL
admin-c: SC16774-RIPE
tech-c: SC16774-RIPE
status: ASSIGNED PA
mnt-by: SERVERS-MNT
created: 2020-07-08T00:49:52Z
last-modified: 2020-07-08T00:49:52Z
source: RIPE
```

We do checks with curl and as standart apt:
`# curl https://deb.nodesource.com/node_15.x
<TITLE>Access Denied</TITLE>
Access Denied

You don't have permission to access "http://deb.nodesource.com/node_15.x" on this server.

link to a similar issue https://github.com/nodesource/distributions/issues/1199 
Reference #18.cc781102.1618409601.8736fa
`

apt:
Err:8 http://deb.nodesource.com/node_15.x buster InRelease 403 Forbidden [IP: 2.22.147.74 80]
Thanks! Will wait your reply.

**Comment by igsu** [comment]
Duplicated. Same IP range. Please let us know what the purpose of using the repository is.
#1261
