### ISSUE TITLE
Nodesource deb packages not installable on Debian Bullseye

### ISSUE THREAD

**Issue by amrishparmar** [nodesource/distributions#1254]
When attempting to install the nodesource distribution of Node 12 on Debian 11 (Bullseye) it fails as the dependency `python-minimal` is no longer present in the distro repository.

The following is a minimal example to demonstrate the problem:
```Dockerfile
FROM debian:11.0

RUN apt-get -qq update && apt-get install -qq -y curl
RUN NODE_FILENAME="nodejs_12.22.5-1nodesource1_amd64.deb" \
    && curl --fail --silent --show-error https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/${NODE_FILENAME} --output ${NODE_FILENAME} \
    && apt-get -o Debug::pkgProblemResolver=true -qq install -y ./${NODE_FILENAME} \
    && rm ${NODE_FILENAME}
```

Attemping to build this image gives the following error:
```
Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) nodejs:amd64 < none -> 12.22.5-1nodesource1 @un puN Ib >
Broken nodejs:amd64 Depends on python-minimal:amd64 < none @un H >
Done
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c NODE_FILENAME="nodejs_12.22.5-1nodesource1_amd64.deb"     && curl --fail --silent --show-error https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/${NODE_FILENAME} --output ${NODE_FILENAME}     && apt-get -o Debug::pkgProblemResolver=true --no-install-recommends --no-upgrade -qq install -y ./${NODE_FILENAME}     && rm ${NODE_FILENAME}' returned a non-zero code: 100
```

In Bullseye the `python-minimal` package is now [python2-minimal](https://packages.debian.org/bullseye/python2-minimal) (or more explictly [python2.7-minimal](https://packages.debian.org/bullseye/python2.7-minimal))

**Comment by amrishparmar** [comment]
I've now tested this with both 14.17.5 and 16.7.0 and get the same error message, so the problem isn't specific to v12.

**Comment by igsu** [comment]
@amrishparmar our packages are running smoothly on `Debian Bullseye`.
We have packages with dependency on `python-minimal` and others with dependency on `python3-minimal`, you are using the wrong one.

Replace:
```
RUN NODE_FILENAME="nodejs_12.22.5-1nodesource1_amd64.deb"
```

With:
```
RUN NODE_FILENAME="nodejs_12.22.5-deb-1nodesource1_amd64.deb"
```
And the issue should be fixed.

**Comment by LevelXStudiosorg** [comment]
I am well aware that it is not a real bug. However, it may be a problem that could arise if you follow the installation routine from the documentation. 

Even if the issue has been closed, I would like to add that a new package has already been released for NodeJS which could be installed without problems. The package is now called: nodejs_12.22.6-deb-1nodesource1_amd64.deb and can be installed under Bullseye without problems. With this, the "problem" has more or less been solved. I just wanted to add it for the sake of completeness and would like to ask you to close here again.

**Comment by Kiemes** [comment]
@igsu thank you. You saved my day. Do you know what exactly the difference is between the two files? I couldn't find any documentation on this.
