### ISSUE TITLE
AWS: No package nodejs available

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [nodesource/distributions#1255]
I've previous run this code successfully, but now I'm getting an error message that "No package nodejs available".

> commands:
>   01-installNode:
>     cwd: /tmp
>     test: '[ ! -f /usr/bin/node ] && echo "Node not installed"'
>     command: curl -fsSL https://rpm.nodesource.com/setup_16.x | bash - | yum -y install nodejs
>   02-installNpm:
>     cwd: /tmp
>     test: '[ ! -f /usr/bin/npm ] && echo "npm not installed"'
>     command: sudo rm -rf /usr/bin/npm | curl -L http://npmjs.org/install.sh | sh

If I remove silent I get:

> Activity execution failed, because: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>   Dload  Upload   Total   Spent    Left  Speed
>   
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>   Loaded plugins: priorities, update-motd, upgrade-helper
>   No package nodejs available.
>   Error: Nothing to do

I'm using Elastic Beanstalk PHP 7.2 running on 64bit Amazon Linux (v2.9.21).

Why would this message be appearing now? Thanks.

**Comment by igsu** [comment]
This problem is not related to packages distributed by NodeSource.

Probably if you try a simpler execution, in which the installation command waits for the execution of the installation of the repositories:

> curl -fsSL https://rpm.nodesource.com/setup_16.x | bash - && yum -y install nodejs

**Comment by JohnnyWalkerDesign** [comment]
Thank you!
