### ISSUE TITLE
No `Snap packages` section in README.md

### ISSUE THREAD

**Issue by ATOMICMAN007** [nodesource/distributions#1256]
Currently, the [README.md](https://github.com/nodesource/distributions/blob/b8510857fb4ce4b023161be8490b00119884974c/README.md)'s *Table Of Contents* has specified the `Snap Packages` section and subsections to it, but not actually documented anywhere in the same file. Is there a planned commit which is in progress which will document it?

In any case, I strongly suggest please remove the previously specified section from the documents until and unless it has been fully documented. It is very likely to cause inconvenience to visitors like me who would prefer using snap over other methods.

Proposed label(s):
- enhancement

> **NOTE:**
> I'm sorry if I am oblivious to some facts that may be obvious to everyone and this issue becomes of no significance because of those facts, but I thought it would be better to speak up rather than passing.

**Comment by igsu** [comment]
Hi @ATOMICMAN007, contents have been updated. Thanks for the report.
