### ISSUE TITLE
nodejs installation doesnt work on ubuntu 

### ISSUE THREAD

**Issue by 7--** [nodesource/distributions#1257]
The commands you listed in the readme don't work. The only way I found to install node is with nvm.

**Comment by BitumFelix** [comment]
It did not work for me either on ubuntu 20.04. It only installed the default version  or 10.x yet I wanted version 16.x( Gallium).
After trying over and over. I had to use nvm.

**Comment by JesusPaz** [comment]
@7-- Please give us more information so we can help identify what your error may be.

**Comment by P1xelC0da** [comment]
How are you going to ask for more information then close the issue as completed? Like it makes no sense.
