### ISSUE TITLE
Support New Debian Testing (bookworm)

### ISSUE THREAD

**Issue by tychedelia** [nodesource/distributions#1258]
Since Bullseye has been upgraded to stable, it is no longer possible to install Node via nodesource on Debian testing (bookworm).

```
## Confirming "bookworm" is supported... 02:01
+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/bookworm/Release' 02:02
## Your distribution, identified as "bookworm", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by openkasnet** [comment]
Hello, I also can't install, Linux debian 11 (bullseye)

## Confirming "bullseye" is supported...
+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_14.x/dists/bullseye/Release'
## Your distribution, identified as "bullseye", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by JesusPaz** [comment]
@tychedelia Changes are already in place to support bookworm. To install node you can now run:
```sh
# Using Debian, as root
curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
apt-get install -y nodejs
```
