### ISSUE TITLE
Can not update the version of iojs on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by junguchina** [nodesource/distributions#126]
Pre-conditions:My base version number is 2.5.0 on ubuntu 14.04 LTS
Steps:
1. Use blew command to update the iojs:
 curl -sL https://deb.nodesource.com/setup_iojs_3.x | sudo -E bash -
2. Then terminal shows:
>Installing the NodeSource io.js 3.x repo...
Populating apt-get cache...
+ apt-get update
Ign http://cn.archive.ubuntu.com trusty InRelease
Ign http://cn.archive.ubuntu.com trusty-updates InRelease                      
Ign http://cn.archive.ubuntu.com trusty-backports InRelease                    
Hit http://cn.archive.ubuntu.com trusty Release.gpg                            
Ign http://archive.ubuntukylin.com:10006 trusty InRelease                      
Hit http://cn.archive.ubuntu.com trusty-updates Release.gpg                    
Hit http://cn.archive.ubuntu.com trusty-backports Release.gpg                  
Hit http://cn.archive.ubuntu.com trusty Release                                
Hit http://archive.ubuntukylin.com:10006 trusty Release.gpg                    
Hit http://cn.archive.ubuntu.com trusty-updates Release                        
Hit http://cn.archive.ubuntu.com trusty-backports Release                      
Ign http://dl.google.com stable InRelease                                      
Hit http://cn.archive.ubuntu.com trusty/main Sources                           
Hit http://archive.ubuntukylin.com:10006 trusty Release                        
Hit http://cn.archive.ubuntu.com trusty/restricted Sources                     
Hit http://cn.archive.ubuntu.com trusty/universe Sources                       
Hit http://cn.archive.ubuntu.com trusty/multiverse Sources                     
Hit http://archive.ubuntukylin.com:10006 trusty/main amd64 Packages            
Hit http://cn.archive.ubuntu.com trusty/main amd64 Packages                    
Hit http://cn.archive.ubuntu.com trusty/restricted amd64 Packages              
Hit http://cn.archive.ubuntu.com trusty/universe amd64 Packages                
Hit http://archive.ubuntukylin.com:10006 trusty/main i386 Packages             
Hit http://cn.archive.ubuntu.com trusty/multiverse amd64 Packages              
Hit http://cn.archive.ubuntu.com trusty/main i386 Packages                     
Hit http://cn.archive.ubuntu.com trusty/restricted i386 Packages               
Hit http://dl.google.com stable Release.gpg                                    
Hit http://cn.archive.ubuntu.com trusty/universe i386 Packages                 
Hit http://cn.archive.ubuntu.com trusty/multiverse i386 Packages               
Ign http://archive.ubuntukylin.com:10006 trusty/main Translation-en            
Hit http://cn.archive.ubuntu.com trusty/main Translation-en                    
Hit http://cn.archive.ubuntu.com trusty/multiverse Translation-en              
Hit http://cn.archive.ubuntu.com trusty/restricted Translation-en              
Hit http://dl.google.com stable Release                                        
Hit http://cn.archive.ubuntu.com trusty/universe Translation-en                
Hit http://cn.archive.ubuntu.com trusty-updates/main Sources                   
Hit http://cn.archive.ubuntu.com trusty-updates/restricted Sources             
Hit http://cn.archive.ubuntu.com trusty-updates/universe Sources               
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse Sources             
Hit http://cn.archive.ubuntu.com trusty-updates/main amd64 Packages            
Hit http://cn.archive.ubuntu.com trusty-updates/restricted amd64 Packages      
Hit http://cn.archive.ubuntu.com trusty-updates/universe amd64 Packages        
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse amd64 Packages      
Hit http://dl.google.com stable/main amd64 Packages                            
Hit http://cn.archive.ubuntu.com trusty-updates/main i386 Packages             
Hit http://cn.archive.ubuntu.com trusty-updates/restricted i386 Packages       
Hit http://cn.archive.ubuntu.com trusty-updates/universe i386 Packages         
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse i386 Packages       
Hit http://cn.archive.ubuntu.com trusty-updates/main Translation-en            
Hit http://dl.google.com stable/main i386 Packages                             
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse Translation-en      
Hit http://cn.archive.ubuntu.com trusty-updates/restricted Translation-en      
Hit http://cn.archive.ubuntu.com trusty-updates/universe Translation-en        
Hit http://cn.archive.ubuntu.com trusty-backports/main Sources                 
Hit http://cn.archive.ubuntu.com trusty-backports/restricted Sources           
Hit http://cn.archive.ubuntu.com trusty-backports/universe Sources             
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse Sources           
Hit http://cn.archive.ubuntu.com trusty-backports/main amd64 Packages          
Hit http://cn.archive.ubuntu.com trusty-backports/restricted amd64 Packages    
Hit http://cn.archive.ubuntu.com trusty-backports/universe amd64 Packages      
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse amd64 Packages    
Hit http://cn.archive.ubuntu.com trusty-backports/main i386 Packages           
Hit http://cn.archive.ubuntu.com trusty-backports/restricted i386 Packages     
Hit http://cn.archive.ubuntu.com trusty-backports/universe i386 Packages       
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse i386 Packages     
Hit http://cn.archive.ubuntu.com trusty-backports/main Translation-en          
Ign http://ppa.launchpad.net trusty InRelease                                  
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse Translation-en    
Hit http://cn.archive.ubuntu.com trusty-backports/restricted Translation-en    
Hit http://cn.archive.ubuntu.com trusty-backports/universe Translation-en      
Ign http://extras.ubuntu.com trusty InRelease                                  
Ign http://security.ubuntu.com trusty-security InRelease                       
Hit http://download.virtualbox.org trusty InRelease                            
Ign http://cn.archive.ubuntu.com trusty/main Translation-en_US                 
Ign http://cn.archive.ubuntu.com trusty/multiverse Translation-en_US           
Ign http://cn.archive.ubuntu.com trusty/restricted Translation-en_US           
Ign http://cn.archive.ubuntu.com trusty/universe Translation-en_US             
Ign http://ppa.launchpad.net trusty InRelease                                  
Hit http://extras.ubuntu.com trusty Release.gpg                                
Get:1 http://security.ubuntu.com trusty-security Release.gpg [933 B]           
Ign http://ppa.launchpad.net trusty Release.gpg                                
Hit https://deb.nodesource.com trusty InRelease                                
Ign http://dl.google.com stable/main Translation-en_US                         
Hit http://extras.ubuntu.com trusty Release                                    
Hit http://download.virtualbox.org trusty/contrib amd64 Packages               
Ign http://dl.google.com stable/main Translation-en                            
Get:2 http://security.ubuntu.com trusty-security Release [63.5 kB]             
Hit https://deb.nodesource.com trusty/main Sources                             
Hit http://ppa.launchpad.net trusty Release.gpg                                
Hit http://extras.ubuntu.com trusty/main Sources                               
Hit https://deb.nodesource.com trusty/main amd64 Packages                      
Ign http://ppa.launchpad.net trusty Release                                    
Hit https://deb.nodesource.com trusty/main i386 Packages                       
Hit http://extras.ubuntu.com trusty/main amd64 Packages                        
Hit http://download.virtualbox.org trusty/non-free amd64 Packages              
Get:3 https://deb.nodesource.com trusty/main Translation-en_US                 
Get:4 http://security.ubuntu.com trusty-security/main Sources [94.1 kB]        
Hit http://ppa.launchpad.net trusty Release                                    
Hit http://extras.ubuntu.com trusty/main i386 Packages                         
Hit http://download.virtualbox.org trusty/contrib i386 Packages                
Get:5 http://security.ubuntu.com trusty-security/restricted Sources [2,061 B]  
Get:6 http://security.ubuntu.com trusty-security/universe Sources [30.5 kB]    
Hit http://download.virtualbox.org trusty/non-free i386 Packages               
Get:7 http://security.ubuntu.com trusty-security/multiverse Sources [2,330 B]  
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Ign https://deb.nodesource.com trusty/main Translation-en_US                   
Get:8 http://security.ubuntu.com trusty-security/main amd64 Packages [341 kB]  
Ign https://deb.nodesource.com trusty/main Translation-en                      
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Get:9 http://security.ubuntu.com trusty-security/restricted amd64 Packages [8,875 B]
Ign http://extras.ubuntu.com trusty/main Translation-en_US                     
Get:10 http://security.ubuntu.com trusty-security/universe amd64 Packages [116 kB]
Ign http://extras.ubuntu.com trusty/main Translation-en                        
Get:11 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [3,686 B]
Get:12 http://security.ubuntu.com trusty-security/main i386 Packages [326 kB]  
Get:13 http://security.ubuntu.com trusty-security/restricted i386 Packages [8,846 B]
Get:14 http://security.ubuntu.com trusty-security/universe i386 Packages [116 kB]
Get:15 http://security.ubuntu.com trusty-security/multiverse i386 Packages [3,830 B]
Hit http://security.ubuntu.com trusty-security/main Translation-en             
Err http://ppa.launchpad.net trusty/main amd64 Packages                        
  404  Not Found
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en       
Err http://ppa.launchpad.net trusty/main i386 Packages                         
  404  Not Found
Hit http://security.ubuntu.com trusty-security/restricted Translation-en       
Ign http://ppa.launchpad.net trusty/main Translation-en_US                     
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Ign http://ppa.launchpad.net trusty/main Translation-en                        
Ign http://download.virtualbox.org trusty/contrib Translation-en_US            
Ign http://download.virtualbox.org trusty/contrib Translation-en
Ign http://download.virtualbox.org trusty/non-free Translation-en_US
Ign http://download.virtualbox.org trusty/non-free Translation-en
Fetched 1,117 kB in 26s (42.7 kB/s)
W: Failed to fetch http://ppa.launchpad.net/alexeftimie/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
W: Failed to fetch http://ppa.launchpad.net/alexeftimie/ppa/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting

3.It will exit at last,I can not update the version of iojs.

**Comment by retrohacker** [comment]
Hi @junguchina,

It appears that you have a broken repo in your sources file. Try commenting out or removing the line for `http://ppa.launchpad.net/alexeftimie/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages` and see if that helps.

Closing this as it doesn't appear to be related to the NodeSource repos. Happy to reopen and help debug if that proves to be wrong!
