### ISSUE TITLE
Failing for Redhat 6.10

### ISSUE THREAD

**Issue by arun-chib** [nodesource/distributions#1263]
LOGS:

curl -fsSL https://rpm.nodesource.com/setup_14.x | sudo bash -
[sudo] password for chib:
\
## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release || rpm -q --whatprovides fedora-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_14.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'
[chib@apgbs18vm3 ~]$ curl -fsSL https://rpm.nodesource.com/setup_14.x | sudo bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release || rpm -q --whatprovides fedora-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_14.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

**Comment by igsu** [comment]
EL 6.x is already EOL.
That is why Node.js 14.x and newer versions are not supported.
