### ISSUE TITLE
Red Hat Enterprise Linux 9.7 (Maipo) Not supported...

### ISSUE THREAD

**Issue by jullrey** [nodesource/distributions#1264]
Sorry for the typo in the title, should say 7.9.
getting this output from the setup_16.x script:

Your distribution, identified as "redhat-release-server-7.9-6.el7_9.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to e considered for support

Does the setup script just need to be updated?

Thanks.

**Comment by igsu** [comment]
RHEL 7.x is currently supported and any issue during its installation is related to the environment and the network in which the installation is being carried out.

Similar issues with installations on subsystems and behind proxies: #1002 #947 #904 #9 and many more.

It's not a problem related to distributions or compatibility, but to the proxy setup.
