### ISSUE TITLE
Debian wheezy

### ISSUE THREAD

**Issue by financedemo** [nodesource/distributions#127]
Your distribution, identified as "wheezy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
There aren't Wheezy packages because the compiler is too old. Ref:

https://github.com/nodesource/distributions/issues/125#issuecomment-138982755

We're working on it though. Hopefully we can get around the problem.

**Comment by seeden** [comment]
What is the final state of this issue?
Is it supported or no?

**Comment by chrislea** [comment]
The current state is that I'm still working on getting a toolchain into the build environment that will compile the current V8. I'm **hoping** that the final state will result in having wheezy builds.
