### ISSUE TITLE
The repository 'https://deb.nodesource.com/node_14.x focal Release' no longer has a Release file

### ISSUE THREAD

**Issue by SaeedSalem** [nodesource/distributions#1271]
I get this message (The repository 'https://deb.nodesource.com/node_14.x focal Release' no longer has a Release file) and if I open the url I get this page:

<img width="807" alt="Screen Shot 1443-02-24 at 6 30 08 PM" src="https://user-images.githubusercontent.com/8950085/135647096-8a6de9cc-bdb5-4e3f-ad3c-243e1a42897c.png">

**Comment by LuckierDodge** [comment]
Also seeing this with Debian Buster: `The repository 'https://deb.nodesource.com/node_14.x buster Release' does not have a Release file.`
