### ISSUE TITLE
Your distribution, identified as "xenial", is not currently

### ISSUE THREAD

**Issue by reheman31** [nodesource/distributions#1273]
When trying to run below command 

curl -kfsSL https://deb.nodesource.com/setup_16.x | sudo -E bash

Getting below error message

## Confirming "xenial" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/xenial/Release'

## Your distribution, identified as "xenial", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by reheman31** [comment]
![image](https://user-images.githubusercontent.com/92074461/136323751-fd3c32fb-cd67-4d21-ab4e-04911e402ca0.png)

**Comment by igsu** [comment]
Ubuntu `xenial` is fully supported, there must be something else in your setup that is preventing the installation from being successful, please share more information about your setup if this is still an issue.
