### ISSUE TITLE
Can you provide the packages for Ubuntu 21.10?

### ISSUE THREAD

**Issue by seyoon20087** [nodesource/distributions#1280]
Now that [Ubuntu 21.10 has been released](https://discourse.ubuntu.com/t/impish-indri-release-notes/21951), it may be a good time to provide the packages for Ubuntu 21.10.

**Comment by Harshballin5** [comment]
Yes please provide the packages for Ubuntu 21.10, i have updated to 21.10 and i have a big project with discord.js v13 which needs node v16+. Please provide it asap.

**Comment by holta** [comment]
> We have already generated the changes to support Ubuntu 21.10. We will keep an eye out in case of any inconvenience.

Thanks @JesusPaz.

We'll keep our fingers crossed that the "impish" directory will appear in https://deb.nodesource.com/node_16.x/dists/ soon!

**Comment by seyoon20087** [comment]
Thanks for providing the packages for Ubuntu 21.10. I'll close the issue right now.
