### ISSUE TITLE
it don't install npm, just nodejs

### ISSUE THREAD

**Issue by yessith93** [nodesource/distributions#1284]
i followed your instruction, and I could install nodejs but I can't execute npm

**Comment by changke** [comment]
Can confirm. Only node gets upgraded (v14 -> v16), npm stays the old version (v6) not the bundled one (v8).

**Comment by DevDengChao** [comment]
+1

**Comment by wizard-28** [comment]
+1

**Comment by 123Mr-king** [comment]
+1

**Comment by TimDaub** [comment]
can confirm and then additionally when I use the command to install n v18, I end up with v12 on Ubuntu 22
