### ISSUE TITLE
"Too many levels of symbolic links"

### ISSUE THREAD

**Issue by roddy** [nodesource/distributions#1288]
Installed v16 via Ubuntu instructions on Ubuntu 20.04.3 LTS and both node and npm can't be run -- both fail with "Too many levels of symbolic links".

Commands run:

```
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt-get install -y nodejs
```

Both complete successfully.

After, `node --version` reports a version as expected, `npm` and `npx` fail:

```
roddy@box:~$ node --version
v16.13.0
roddy@box:~$ npm --version
/usr/bin/env: ‘node’: Too many levels of symbolic links
roddy@box:~$ npx --version
/usr/bin/env: ‘node’: Too many levels of symbolic links
```

Tried to install Angular CLI via npm, and this time `node` call failed with "too many levels of symbolic links":

```
roddy@box:~$ npm install -g @angular/cli
/usr/bin/env: ‘node’: Too many levels of symbolic links
```

**Comment by Muhammad45992** [comment]
All payment app and

**Comment by JesusPaz** [comment]
Hi @roddy,

It seems to be a specific configuration error in your environment. Try to remove node, npm and npx completely. Then install node again with our script.

If the problem persists let us know.
