### ISSUE TITLE
[NFR] Ubuntu 15.10 Wily

### ISSUE THREAD

**Issue by ovr** [nodesource/distributions#129]
It's not supported yet

**Comment by chrislea** [comment]
We don't support distros in alpha or beta state. When Wily is actually released we will support it at that time. Thanks.

**Comment by mxrguspxrt** [comment]
On https://github.com/nodesource/distributions you claim that 15.10 is supported. Also it is public relase from today. But:

## Confirming "wily" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_0.12/dists/wily/Release'

## Your distribution, identified as "wily", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
That's because you're trying to install the 0.12 branch which isn't being updated anymore. If you use the setup script for 4.x (the current release line) it should work correctly:

https://deb.nodesource.com/setup_4.x
