### ISSUE TITLE
nodejs-14.18.1-1nodesource.x86_64.rpm: Downloading successful, but checksum doesn't match

### ISSUE THREAD

**Issue by bhanson322** [nodesource/distributions#1291]
[MIRROR] nodejs-14.18.1-1nodesource.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 169c65275299723d25d069e4b66a0bb07bbd6f9a(sha1)  Expected: 3d3655ab9862340b3aa9371d15290aa323c8f9c9(sha1) 
[MIRROR] nodejs-14.18.1-1nodesource.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 169c65275299723d25d069e4b66a0bb07bbd6f9a(sha1)  Expected: 3d3655ab9862340b3aa9371d15290aa323c8f9c9(sha1) 
[MIRROR] nodejs-14.18.1-1nodesource.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 169c65275299723d25d069e4b66a0bb07bbd6f9a(sha1)  Expected: 3d3655ab9862340b3aa9371d15290aa323c8f9c9(sha1) 
[MIRROR] nodejs-14.18.1-1nodesource.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 169c65275299723d25d069e4b66a0bb07bbd6f9a(sha1)  Expected: 3d3655ab9862340b3aa9371d15290aa323c8f9c9(sha1) 
[FAILED] nodejs-14.18.1-1nodesource.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

dnf clean packages
yum clean all

Always getting the error.  

Is the checksum correct on the downloads site?

**Comment by jimlindeman** [comment]
Same broken for nodejs-12.26.7...
```
MIRROR] nodejs-12.22.7-1nodesource.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 97450e8d786f1b501f30fbba55b5c2ab52ffedd9(sha1)  Expected: a48c6ab7b1596d6a44ff10a7cffe2fe2cb22dbe7(sha1) 

[MIRROR] nodejs-12.22.7-1nodesource.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 97450e8d786f1b501f30fbba55b5c2ab52ffedd9(sha1)  Expected: a48c6ab7b1596d6a44ff10a7cffe2fe2cb22dbe7(sha1) 

[FAILED] nodejs-12.22.7-1nodesource.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
```

**Comment by bswan0002** [comment]
I'm getting the same error for node 14 on a build process that was working a week ago and has not been modified.

**Comment by jimlindeman** [comment]
Side note, it would be really useful if these scripts supported an optional environment variable to force the download of a specific version so users like us could manually backlevel to a working version.  Example would be that instead of just this Dockerfile sniplet: 
```
RUN curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -
```
we could set some env-var like:
```
RUN FETCHNODEVERSION=12.22.6 curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -
```

**Comment by gianricod** [comment]
same issue here with 14.18.1

container cannot be built because of that

https://rpm.nodesource.com/pub_14.x/el/7/x86_64/nodejs-14.18.1-1nodesource.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=nodesource clean metadata

**Comment by snobb** [comment]
Same here.

```
https://rpm.nodesource.com/pub_14.x/el/7/x86_64/nodejs-14.18.1-1nodesource.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=nodesource clean metadata
Trying other mirror.

Error downloading packages:
  2:nodejs-14.18.1-1nodesource.x86_64: [Errno 256] No more mirrors to try.```

**Comment by snobb** [comment]
Just tried with v16 and it's also broken:
```
https://rpm.nodesource.com/pub_16.x/el/7/x86_64/nodejs-16.13.0-1nodesource.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=nodesource clean metadata
Trying other mirror.


Error downloading packages:
  2:nodejs-16.13.0-1nodesource.x86_64: [Errno 256] No more mirrors to try.

**Comment by gentig** [comment]
I am having the same problem for 14.x. Is there a fix for this yet?

**Comment by patkoscsaba** [comment]
Same issue here as well. Node 12.22.7.

**Comment by alfresanc** [comment]
Hey friends, maybe not the best solution, but I solved it changing the node version my process is working with:
**from:** curl -sL https://rpm.nodesource.com/setup_14.x | bash -
**to:** curl -sL https://rpm.nodesource.com/setup_13.x | bash -

**Comment by snobb** [comment]
There is another issue for this problem: https://github.com/nodesource/distributions/issues/1290

The workarounds that worked for me:
1. Run clean all before installing:
```
RUN yum clean all
RUN yum install nodejs -y
```
2.Hardcoding version in the yum command:
```
RUN yum install nodejs-14.18.1 -y
```
I hope it helps.

**Comment by kulor** [comment]
@snobb's suggested pinning didn't work for me but the LTS (14.18.0) did:

```
RUN curl -sL https://rpm.nodesource.com/setup_14.x | bash -
RUN yum install nodejs-14.18.0 -y
```

**Comment by snobb** [comment]
@kulor Yes, I also noticed that the workarounds do not work everytime. Eg. it works when I build a container locally, but consistently fails at the build servers. Stilll trying to figure out why.

**Comment by kulor** [comment]
> @kulor Yes, I also noticed that the workarounds do not work everytime. Eg. it works when I build a container locally, but consistently fails at the build servers. Stilll trying to figure out why.

Cool. Using 14.18.0 feels fairly deterministic so far (ran in an isolated container a few times). Just realised my previous comment sounded a bit aggressive, not intended 🤗 .

**Comment by igsu** [comment]
Duplicated #1290
