### ISSUE TITLE
nodejs-16.13.0-1nodesource.x86_64.rpm: Downloading successful, but checksum doesn't match

### ISSUE THREAD

**Issue by lenfree** [nodesource/distributions#1292]
The package that was released yesterday does not match the checksum in the metadata files as shown below:

![image](https://user-images.githubusercontent.com/5163675/140423618-daa0c6df-beec-47c2-961a-70a9b63791e6.png). 

This also happened last time with v16.10.0 if I recall correctly. Anyway, do you need to republish the artifact to fix this?

**Comment by igsu** [comment]
Duplicated #1290
