### ISSUE TITLE
[Feature] GuixSD Support

### ISSUE THREAD

**Issue by ncorder** [nodesource/distributions#1297]
Hey, I was curious if it would be possible to add GuixSD to supported distrobutions.

and to start a discussion thread documenting any attempts to get NodeJS on GuixSD.

**Comment by JesusPaz** [comment]
Unfortunately, we do not plan to support GuixSD at this time, but it has been added to our list of requested distributions #1327.

When your distribution is not supported you can install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).

You can also help us to support this distribution, here are some examples of pull request #1231 #1195. If you have any problems let us know.
