### ISSUE TITLE
Support for Ubuntu Utopic (14.10)

### ISSUE THREAD

**Issue by rvagg** [nodesource/distributions#13]
We won't be officially supporting Utopic until it's released by Canonical, towards the end of October. In the meantime, the Trusty binaries should work fine, simply run this as **root** to try it out:

```text
apt-get update && apt-get install curl apt-transport-https -y
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
echo 'deb https://deb.nodesource.com/node trusty main' > /etc/apt/sources.list.d/nodesource.list
echo 'deb-src https://deb.nodesource.com/node trusty main' >> /etc/apt/sources.list.d/nodesource.list
apt-get update && apt-get install nodejs -y
node -v && npm -v
```

Additionally, to support building native add-ons:

```text
apt-get install build-essential python -y
```

To confirm a full, working installation:

```text
curl -sL https://deb.nodesource.com/test | bash -
```

**Comment by Moter8** [comment]
@rvagg 
>We won't be officially supporting Utopic until it's released by Canonical, towards the end of October.

Well, it is released for some time now, when will it be oficially supported (or the docs get updated)?

**Comment by chrislea** [comment]
Apologies, I'll check if we need to update the docs, but builds for Utopic have been in the repo ever since it was released. You should be able to install it just as you would for Trusty or any other supported distro.

**Comment by Moter8** [comment]
@chrislea Sorry for not being specific, see https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions and scroll down. It links to this issue; it's probably not nodesource's fault but you could have closed this issue nevertheless :)

**Comment by dandv** [comment]
https://github.com/nodesource/distributions still doesn't mention 14.10. Is it supported now? When I follow the installation steps at https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions, I end up with v10.0.25 because . I'm not behind a proxy.

```
W: Failed to fetch https://deb.nodesource.com/node_5.x/dists/utopic/main/source/Sources  HttpError404

W: Failed to fetch https://deb.nodesource.com/node_5.x/dists/utopic/main/binary-amd64/Packages  HttpError404

W: Failed to fetch https://deb.nodesource.com/node_5.x/dists/utopic/main/binary-i386/Packages  HttpError404
```

**Comment by chrislea** [comment]
@dandv Ubuntu Utopic hit the end of it's supported release schedule in July of 2015 (see [here](https://wiki.ubuntu.com/Releases)). Once a distro stops being supported by Canonical, we can't support it either. Sorry!
