### ISSUE TITLE
if bullseye is the new stable for debian why is it not supported, please fix this

### ISSUE THREAD

**Issue by Void4DevYT** [nodesource/distributions#1302]
When doing:
`curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
`
is returns with 
` *some other random install stuff*

Your distribution, identified as "bullseye", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support `

please, a lot of people use bullseye as it's the new stable version, please support it.

**Comment by igsu** [comment]
Debian `bullseye` is currently supported.
Please note that Node.js 6.x was deprecated back in 01 MAY 2019.
