### ISSUE TITLE
Cannot install an older version of 16.x on Debian buster

### ISSUE THREAD

**Issue by phr3nzii** [nodesource/distributions#1303]
Hi,

We're trying to install version 16.1.0 of nodejs on Debian buster. When we try to install it we get this error:
```
apt-get install nodejs=16.1.0-*
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '16.1.0-*' for 'nodejs' was not found
```

I see that version 16.13.0 is available, which we are planning to upgrade to in the near future, but for now we need to stay at version 16.1.0. How can we do this? I see the all 16.x versions are available at https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/, can they be made available to be installed using apt?

**Comment by igsu** [comment]
This behavior is not supported in our repository. https://github.com/nodesource/distributions/issues/33#issuecomment-169345680

I could you suggest:

```
export NODEJS_DEB="nodejs_16.1.0-deb-1nodesource1_arm64.deb"
curl -o $NODEJS_DEB https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/$NODEJS_DEB && apt install ./$NODEJS_DEB && rm $FILE
```

Note that this version is for `arm64`.
