### ISSUE TITLE
config.gypi for node 16/gallium refers to the 14/fermium mirror, breaking node-gyp

### ISSUE THREAD

**Issue by FauxFaux** [nodesource/distributions#1306]
### What

nsolid 16 can't build working native modules with `node-gyp`, you get an error like:

```
Error: The module '/srv/app/node_modules/@snyk/node-dump-stacks/build/Release/dump-stacks.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1197:18)
```

abi 83: node 14.
abi 93: node 16.

### Why

`/usr/include/node/config.gypi` contains a `node_release_urlbase`, which `node-gyp` uses to locate headers for compiling native node modules. `node-gyp` expects these headers to match the `node_module_version` specified in the same `config.gypi` file.

In [nodesource's 16/gallium `deb` release, as of 4.6.2](https://s3-us-west-2.amazonaws.com/nodesource-public-downloads/4.6.2/artifacts/linux/nsolid-gallium_4.6.2-nodesource-systemd1_amd64.deb), `/usr/include/node/config.gypi` contains:

```
...
'node_module_version': 93,
...
'node_release_urlbase': 'https://s3-us-west-2.amazonaws.com/nodesource-public-downloads/4.6.2/artifacts/headers/fermium/',
...
```

That is, the node 16 release (module version 93), refers to the `fermium` headers, which is node 14, module/abi version 83.

This causes `node-gyp` to build incorrect binaries, and them to fail at runtime.

### Fix

Changing the `config.gypi` doesn't seem to be sufficient, as it is also hardcoded into `/usr/bin/nsolid` too. Perhaps it just needs to be changed at build time?

### Steps to reproduce

```
docker run -it ubuntu:20.04
apt update
apt install -y build-essential python3 wget
wget https://s3-us-west-2.amazonaws.com/nodesource-public-downloads/4.6.2/artifacts/linux/nsolid-gallium_4.6.2-nodesource-systemd1_amd64.deb
apt install -y ./nsolid*
cd /tmp
npm install @snyk/node-dump-stacks
node -e 'require("@snyk/node-dump-stacks")'
```

...gives the error at the top of the bug report, despite there being no node14 involved anywhere.

I notice the alpine docker images do not have this issue.

**Comment by igsu** [comment]
We are aware of this issue and are actively working to fix it.
Thanks for reporting this @FauxFaux.
