### ISSUE TITLE
I CANNOT UPDATE NODEJS IN LINUX MINT

### ISSUE THREAD

**Issue by JhonLSN** [nodesource/distributions#1309]
I cannot install node on Linux Mint.
I'm always having this problem. It turns out that I've tried to install it all the ways and it still didn't work. I'm very layman because I'm on linux for about 7 months and I need the current version.

Problems I have:

- Whenever I go to install this error that are in the images happens.
- In the Linux Mint store there is node, but it is not up to date and I can only install it because it is this outdated version 10.x

can you help me? I do not know what else to do!!!!

![Captura de tela de 2021-12-08 22-49-05](https://user-images.githubusercontent.com/80855598/145319687-be9b71cb-dda8-4a8d-9e64-496c5690b845.png)
![Captura de tela de 2021-12-08 22-49-46](https://user-images.githubusercontent.com/80855598/145319691-06630db6-6c35-480c-b0af-6ba560d8e104.png)
![Captura de tela de 2021-12-08 22-50-04](https://user-images.githubusercontent.com/80855598/145319693-e5b03b9e-bd8f-4553-837d-897946b9e456.png)

**Comment by igsu** [comment]
From your logs the repository failing is Spotify, it is not under our control.

Please fix that problem and try interacting with our script again.
