### ISSUE TITLE
Remove Debian 7 Wheezy as supported in main README

### ISSUE THREAD

**Issue by logoff** [nodesource/distributions#131]
Debian 7 Wheezy is not supported but the main README says it is. Moreover some issues reflect this fact (#125 seems to be the reference).

**Comment by opt9** [comment]
> pi at erlang in ~/Work
> $ curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
> ... (snip) ...
> \#\# Confirming "wheezy" is supported... 
> \+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_4.x/dists/wheezy/Release'
> ... (snip) ...
> \#\# Your distribution, identified as "wheezy", is not currently supported
> ... (snip) ...

**Comment by jhewt** [comment]
+1

**Comment by ftribrunn** [comment]
+1

**Comment by chrislea** [comment]
Please ref: https://github.com/nodesource/distributions/issues/125#issuecomment-143911468 ... we're getting there.

**Comment by chrislea** [comment]
Wheezy builds are available now.
