### ISSUE TITLE
Installation instructions leading to 404 using curl on Ubuntu

### ISSUE THREAD

**Issue by webthethird** [nodesource/distributions#1310]
```
$ sudo curl -fsSL https://deb.nodesource.com/setup_16.13.1 | sudo -E bash -
curl: (22) The requested URL returned error: 404 
```

I get the same 404 error when I try `setup_16.13` or any other number below the latest LTS version.

**Comment by igsu** [comment]
Hey @webthethird, that's not how this script is suppose to be used. To install specific versions try: https://github.com/nodesource/distributions/issues/33#issuecomment-169345680
