### ISSUE TITLE
Invalid configuration value: failovermethod=priority

### ISSUE THREAD

**Issue by navjotjsingh** [nodesource/distributions#1311]
I am trying to install Node v16 in Rocky Linux 8 and this is the warning error I get when I try to run the install command. Doesn't matter if I use dnf or yum to install.

```
Invalid configuration value: failovermethod=priority in /etc/yum.repos.d/nodesource-el8.repo; Configuration: OptionBinding with id "failovermethod" does not exist
Invalid configuration value: failovermethod=priority in /etc/yum.repos.d/nodesource-el8.repo; Configuration: OptionBinding with id "failovermethod" does not exist
```

**Comment by thebitguru** [comment]
[`failovermethod` was deprecated](https://github.com/rpm-software-management/libdnf/pull/1276) in `dnf`.  Take a look at https://communicode.io/how-to-fix-failovermethod-error-fedora/ for possible mitigation options.

**Comment by themowski** [comment]
Confirming that we see this in AlmaLinux 8.5 as well, which uses `dnf`.

**Comment by JesusPaz** [comment]
This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).
