### ISSUE TITLE
Elementary OS 6.1 Jolnir

### ISSUE THREAD

**Issue by candiedoperation** [nodesource/distributions#1312]
Elementary OS 6 was branded Odin and now, 6.1 is Jolnir. The setup says Jolnir is unsupported but, it works fine and Jolnir is based on Ubuntu 20.04 only...

Requesting the contributors to please add 6.1 to the list soon...

**Comment by webdevhrithik** [comment]
Please Add support for Elementary OS 6.1 Jolnir

**Comment by webdevhrithik** [comment]
i need to install Node Js for my work, on Elementary OS 6.1 Jolnir it is not supported, i request to contributors to add it to the list
