### ISSUE TITLE
Can't install on Windows11 wsl2 Ubuntu20.04

### ISSUE THREAD

**Issue by alancodvo** [nodesource/distributions#1318]
I tried "curl -fsSL https://rpm.nodesource.com/setup_17.x | bash -".
My condition is Windows11 wsl2 Ubuntu20.04.
Probably, Windows11 isn't supported yet, right?

**Comment by igsu** [comment]
@alancodvo right, Windows WSL is not supported.

**Comment by alancodvo** [comment]
My another computer could install successfully.
It's almost same condition but Windows OS is 10.
Why could this installed successfully using wsl?
