### ISSUE TITLE
setup_0.12

### ISSUE THREAD

**Issue by mehtadev17** [nodesource/distributions#132]
Setup file not working for centos 6.5? 
Using vagrant box: "CentOS-6.5-x86_64-v20140311"
from: http://sourceforge.net/projects/nrel-vagrant-boxes/files/CentOS-6.5-x86_64-v20140311.box/download

**Comment by alrunner4** [comment]
This is also producing a strange error for me on CentOS 6.7:
```
curl -sL https://rpm.nodesource.com/setup_0.12 | bash -

## Installing the NodeSource Node.js 0.12 repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_0.12/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "centos-release-6-7.el6.centos.12.3.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by retrohacker** [comment]
Centos should now be supported.

https://github.com/nodesource/distributions/blob/master/rpm/setup_0.12#L78

Closing this issue as stale. If you continue to have problems using the 0.12 setup script on Centos 6.7, feel free to reopen this issue and we can help debug!
