### ISSUE TITLE
Unable to install nodejs version on Centos 7

### ISSUE THREAD

**Issue by sansaraf** [nodesource/distributions#1325]
Hi,
I ran below command and tried to install on my Centos-release-7-9.2009.1.e17.centos.x86_64 however I got message that my Centos is not currently supported. I tried version 10.x, 12.x and 14.x

-       curl –sL https://rpm.nodesource.com/setup_14.x | sudo bash -
-       sudo yum install –y nodejs

I desparetly need your advice on this.

Thanks,
Sanjay

**Comment by JesusPaz** [comment]
CentOS 7 is currently supported and any issue during its installation is related to the environment and the network in which the installation is being carried out.

Similar issues with installations on subsystems and behind proxies: #1002 #947 #904 #9 and many more.

It's not a problem related to distributions or compatibility, but to the proxy setup.

**Comment by iantra123** [comment]
Error: Package: 2:nodejs-19.2.0-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(GLIBCXX_3.4.21)(64bit)
Error: Package: 2:nodejs-19.2.0-1nodesource.x86_64 (nodesource)
           Requires: libm.so.6(GLIBC_2.27)(64bit)
Error: Package: 2:nodejs-19.2.0-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(GLIBCXX_3.4.20)(64bit)
Error: Package: 2:nodejs-19.2.0-1nodesource.x86_64 (nodesource)
           Requires: libc.so.6(GLIBC_2.28)(64bit)
Error: Package: 2:nodejs-19.2.0-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(CXXABI_1.3.9)(64bit)
