### ISSUE TITLE
nodejs 4.1.0

### ISSUE THREAD

**Issue by deployable** [nodesource/distributions#133]
More a question than anything, how long does it normally take for node releases to become available on nodesource? I see there are a few open issues with the initial 4.0.0 builds so I guess this might be a bad time to ask, just looking for a bug fix from the 4.1.0 release - https://github.com/nodejs/node/releases/tag/v4.1.0

**Comment by chrislea** [comment]
We try hard to get them out asap. In this particular case, we haven't
pushed builds of 4.1.0 out yet because there's a minor issue with it, and
we expect to see a 4.1.1 out tomorrow. The packages for 4.1.1 should also
land tomorrow assuming nothing else turns up.

**Comment by deployable** [comment]
Excellent, thanks Chris. btw it looks like 4.1.1 was pushed back after the weekend.

**Comment by chrislea** [comment]
That's correct it was pushed (issue wasn't as big a deal as originally thought). As a result I went ahead and pushed 4.1.0 into the repos, so it's there for you now. Sorry for the confusion!
