### ISSUE TITLE
Default version is past end-of-life

### ISSUE THREAD

**Issue by wbt** [nodesource/distributions#1330]
[This comment](https://github.com/nodejs/node/issues/27293#issuecomment-1001691769) reports that the default version of Node `apt` installs is unsupported. 
That should probably be updated by having a person or script publish the latest LTS version (or at least some current version!) to relevant repositories.

**Comment by pyhoff** [comment]
We have an issue with dependency gpg key being expired.

W: GPG error: http://www.inetsim.org/debian binary/ InRelease: The following signatures were invalid: EXPKEYSIG 6881B9A7E9F601C8 INetSim Archive Signing Key (2016-2021) <inetsim@inetsim.org>
E: The repository 'http://www.inetsim.org/debian binary/ InRelease' is not signed.

**Comment by RobQuistNL** [comment]
Thanks for reporting this @wbt  👍

**Comment by JesusPaz** [comment]
At the moment we only publish the new packages in this repo. Thanks for reporting it.
