### ISSUE TITLE
miss https://deb.nodesource.com/node_11.x/dists/bullseye

### ISSUE THREAD

**Issue by caoshitong369** [nodesource/distributions#1331]
11.x version download is unsuccessful, setup_11.x is wrong

**Comment by caoshitong369** [comment]
## Confirming "bullseye" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_11.x/dists/bullseye/Release'

## Your distribution, identified as "bullseye", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

The command '/bin/sh -c curl -sL https://deb.nodesource.com/setup_11.x | bash -' returned a non-zero code: 1

**Comment by caoshitong369** [comment]
![image](https://user-images.githubusercontent.com/44139321/147825513-920e26a0-bfd8-4ffa-9663-350c6431cba8.png)

**Comment by igsu** [comment]
@caoshitong369 Node.js 11.x was deprecated back in April 2019. It will not be available for newer distributions (like bullseye).
