### ISSUE TITLE
Could not resolve 'in.old-releases.ubuntu.com' || Error executing command, exiting || See apt-secure(8) manpage for repository creation and user configuration details.

### ISSUE THREAD

**Issue by imbharat420** [nodesource/distributions#1333]
## Populating apt-get cache...

+ apt-get update
Err:1 http://in.old-releases.ubuntu.com/ubuntu eoan InRelease
  Could not resolve 'in.old-releases.ubuntu.com'
Err:2 http://in.old-releases.ubuntu.com/ubuntu eoan-updates InRelease       
  Could not resolve 'in.old-releases.ubuntu.com'
Err:3 http://in.old-releases.ubuntu.com/ubuntu eoan-backports InRelease     
  Could not resolve 'in.old-releases.ubuntu.com'
Ign:4 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu eoan InRelease         
Ign:5 http://old-releases.ubuntu.com/ubuntu bionic InRelease                
Ign:6 http://ppa.launchpad.net/linuxjedi/ppa/ubuntu eoan InRelease
Ign:7 http://old-releases.ubuntu.com/ubuntu bionic-security InRelease
Err:8 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu eoan Release              
  404  Not Found [IP: 91.189.95.85 80]
Ign:9 http://old-releases.ubuntu.com/ubuntu bionic-updates InRelease           
Hit:10 http://deb.playonlinux.com trusty InRelease                             
Hit:11 http://old-releases.ubuntu.com/ubuntu eoan InRelease                    
Err:12 http://ppa.launchpad.net/linuxjedi/ppa/ubuntu eoan Release              
  404  Not Found [IP: 91.189.95.85 80]
Ign:13 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_16.04  InRelease
Hit:14 http://old-releases.ubuntu.com/ubuntu eoan-security InRelease
Err:15 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_16.04  Release
  404  Not Found [IP: 195.135.221.134 80]
Err:16 http://old-releases.ubuntu.com/ubuntu bionic Release
  404  Not Found [IP: 91.189.91.124 80]
Err:17 http://old-releases.ubuntu.com/ubuntu bionic-security Release
  404  Not Found [IP: 91.189.91.124 80]
Err:18 http://old-releases.ubuntu.com/ubuntu bionic-updates Release
  404  Not Found [IP: 91.189.91.124 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/deadsnakes/ppa/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/linuxjedi/ppa/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://download.opensuse.org/repositories/home:/strycore/xUbuntu_16.04  Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://old-releases.ubuntu.com/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://old-releases.ubuntu.com/ubuntu bionic-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://old-releases.ubuntu.com/ubuntu bionic-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting

**Comment by guiverc** [comment]
http://in.old-releases.ubuntu.com/ubuntu  is invalid; and is not a bug, but a user error (ie. _the person who added it to your system was in error & should have checked the URL_)

http://ppa.launchpad.net/deadsnakes/ppa/ubuntu does not provide support for _eoan_ or 19.10; so again a user error (_the person who added it didn't do their checks & thus should never have added it_)

`http://old-releases.ubuntu.com/ubuntu bionic` likewise is invalid; it's a _supported_ release thus isn't found in old-releases..

I didn't read further, this is just three user-errors.

Your issue is the operator who was given `sudo` rights isn't doing their homework before adding/changing sources, and should be seeking support; not raising bug tickets (_unless it's with their teachers of IT/technology who didn't instruct well enough_)

**Comment by imbharat420** [comment]
Thanks ❤, the issue is resolved now 
i change whole OS by iso into 20.04 😅
maybe the links I am updating  in **sources.lists** are not the latest one because I was trying stackoverflow questions Links not from the official ubuntu archives links

**Comment by JesusPaz** [comment]
@guiverc thank you for helping us to solve this issue.

**Comment by knshkp** [comment]
could anyone help me out
how can i resolve this:
sudo apt update
Ign:1 http://old-releases.ubuntu.com/ubuntu/dists/artful-updates main InRelease     
Err:2 http://old-releases.ubuntu.com/ubuntu/dists/artful-updates main Release       
  404  Not Found [IP: 2620:2d:4000:1::17 80]
Ign:3 https://old-releases.ubuntu.com/ubuntu/dists/artful main InRelease
Ign:4 https://old-releases.ubuntu.com/ubuntu/dists/artful-security main InRelease
Err:5 https://old-releases.ubuntu.com/ubuntu/dists/artful main Release
  404  Not Found [IP: 2620:2d:4000:1::17 443]
Err:6 https://old-releases.ubuntu.com/ubuntu/dists/artful-security main Release
  404  Not Found [IP: 2620:2d:4000:1::17 443]
Reading package lists... Done
E: The repository 'http://old-releases.ubuntu.com/ubuntu/dists/artful-updates main Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://old-releases.ubuntu.com/ubuntu/dists/artful main Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://old-releases.ubuntu.com/ubuntu/dists/artful-security main Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
