### ISSUE TITLE
"bullseye", is not currently supported

### ISSUE THREAD

**Issue by sumitok22** [nodesource/distributions#1334]
I get this error code when I try to build an docker image in cloud66. Any thoughts?

Error code:
Your distribution, identified as "bullseye", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by JesusPaz** [comment]
Debian Bullseye is currently supported and any issue during its installation is related to the environment and the network in which the installation is being carried out.

Similar issues with installations on subsystems and behind proxies: #1002 #947 #904 #9 and many more.

It's not a problem related to distributions or compatibility, but to the proxy setup.
