### ISSUE TITLE
Not able to install node js -v13.12.0 in Centos-release-7.9.2009.1.el7.centosx86_64

### ISSUE THREAD

**Issue by rishabkoul** [nodesource/distributions#1335]
While Installing node.js -v13.12.0 in Centos-release-7.9.2009.1.el7.centosx86_64 i.e. my organization's server I am facing the following error
![image](https://user-images.githubusercontent.com/42373934/148209633-98e75205-8142-426e-960a-c4393d5bfc7a.png)
Please tell me how to do this installation correctly

**Comment by JesusPaz** [comment]
CentOS 7 is currently supported and any issue during its installation is related to the environment and the network in which the installation is being carried out.

Similar issues with installations on subsystems and behind proxies: #1002 #947 #904 #9 and many more.

It's not a problem related to distributions or compatibility, but to the proxy setup.
