### ISSUE TITLE
Request for Pacstall Support

### ISSUE THREAD

**Issue by saenai255** [nodesource/distributions#1336]
[Pacstall](https://pacstall.dev/) is a community-driven AUR-like package manager for Ubuntu. We have an ongoing [pull request](https://github.com/pacstall/pacstall-programs/pull/628) to add Nodejs LTS to our repository.

We have a few questions for you:

- Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can create and maintain it for you if you decide not to.
- Could you include a section in your documentation showing Pacstall as a valid method of installation for Nodejs LTS for Debian/Ubuntu users? We could make a pull request for that if you want.

Example usage:
```bash
$ pacstall -I nodejs-lts-deb
```

**Comment by wizard-28** [comment]
1 week has passed. So we would have to merge this pull request You can still request to maintain the script later on.
