### ISSUE TITLE
Add repository aliases for Debian

### ISSUE THREAD

**Issue by jawnsy** [nodesource/distributions#1338]
Thanks for publishing and maintaining these distributions!

## Overview

NodeSource provides `bookworm`, which is the current Debian testing release. Debian has a fixed `testing` suite, which is an alias for `bookworm` (currently), and then rolls things forward when new stable releases are published. The current behavior of requiring `bookworm` to be specified explicitly means that users would need to update their repository source list when a new `stable` release is published.

## Current behavior

Users of Debian `testing` need to add the following, and keep it updated when new releases are cut:

```
deb https://deb.nodesource.com/node_16.x bookworm main
```

and later, when `bookworm` becomes the `stable` release:

```
deb https://deb.nodesource.com/node_16.x trixie main
```

## Proposed behavior

Add `testing` and `unstable` suites, so that users can use the following to track the rest of the system packages:

```
deb https://deb.nodesource.com/node_16.x testing main
```

**Comment by JesusPaz** [comment]
Thank you for contacting us. At this time at NodeSource, we do not have sufficient resources to handle this type of request. I will add a tag and close the issue for future review. Sorry for the inconvenience.
