### ISSUE TITLE
jessie distribution - not currently supported

### ISSUE THREAD

**Issue by hkkumargithub** [nodesource/distributions#1339]
Hello Dears,

I am currently using below lines in the Dockerfile to install node16 version.

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install nodejs

curl command was working fine until November, but now it's throwing below error. Please assist.

ERROR:
Step 2/8 : RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
// Installing the NodeSource Node.js 16.x repo...
// Populating apt-get cache...
+ apt-get update
Ign http://deb.debian.org jessie InRelease
Get:1 http://deb.debian.org jessie-updates InRelease [16.3 kB]
Get:2 http://security.debian.org jessie/updates InRelease [44.9 kB]
Get:3 http://deb.debian.org jessie Release.gpg [1652 B]
Get:4 http://deb.debian.org jessie Release [77.3 kB]
Get:5 http://deb.debian.org jessie-updates/main amd64 Packages [20 B]
Get:6 http://security.debian.org jessie/updates/main amd64 Packages [992 kB]
Get:7 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Fetched 10.2 MB in 10s (1021 kB/s)
Reading package lists...
// Installing packages required for setup: apt-transport-https lsb-release...
+ apt-get install -y apt-transport-https lsb-release > /dev/null 2>&1
// You seem to be using Devuan version jessie.
// This maps to Debian "jessie"... Adjusting for you...
// Confirming "jessie" is supported...
+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/jessie/Release'
// Your distribution, identified as "jessie", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
The command '/bin/sh -c curl -fsSL https://deb.nodesource.com/setup_16.x | bash -' returned a non-zero code: 1

**Comment by mehov** [comment]
I'm also on Jessie and this guide for manual install helps: https://github.com/nodesource/distributions/blob/master/README.md#manual-installation

Note: [16.x](https://deb.nodesource.com/node_16.x/dists/) won't work, but [14.x](https://deb.nodesource.com/node_14.x/dists/) will and shouldn't get EOL until [well into 2023](https://nodejs.org/en/about/releases/)

**Comment by JesusPaz** [comment]
Jessie is not supported at this time. Thank you @mehov for helping us to solve this issue.
