### ISSUE TITLE
BROKEN PIPE

### ISSUE THREAD

**Issue by shawnpaffhausen** [nodesource/distributions#1340]
trying to install mm2 on raspberry pi 3 with newest distro of OS
when trying to install node js i get this
never had an issue before

Unpacking nodejs (17.3.0-deb-1nodesource1) over (12.22.5~dfsg-2~11u1) ...
dpkg: error processing archive /var/cache/apt/archives/nodejs_17.3.0-deb-1nodesource1_armhf.deb (--unpack):
 trying to overwrite '/usr/share/doc/nodejs/api/fs.html', which is also in package nodejs-doc 12.22.5~dfsg-2~11u1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_17.3.0-deb-1nodesource1_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by riosje** [comment]
@shawnpaffhausen are you still facing this issue?
Can you check if you already have installed node 12, if you have it installed, please remove it and try to run the installation again.
