### ISSUE TITLE
Repository change?

### ISSUE THREAD

**Issue by slipttees** [nodesource/distributions#1341]
https://deb.nodesource.com/setup_16.x focal main - error 404
https://deb.nodesource.com/setup_lts.x focal main - error 404
https://deb.nodesource.com/setup_current.x focal main - error 404

https://deb.nodesource.com/node_16.x focal main - works!!

**Comment by JesusPaz** [comment]
Hi @slipttees,
The following URLs are installation scripts:
- https://deb.nodesource.com/setup_16.x 
- https://deb.nodesource.com/setup_lts.x
- https://deb.nodesource.com/setup_current.x

[Here](https://github.com/nodesource/distributions#installation-instructions) you can find instructions for a successful installation.
