### ISSUE TITLE
Nodesource APT repositories provide only the latest version, even though more versions are stored in the server

### ISSUE THREAD

**Issue by ecazamir** [nodesource/distributions#1345]
On Debian/Ubuntu systems, the manual nodejs installation procedure ( described here https://github.com/nodesource/distributions/blob/master/README.md#debmanual ) adds a repository to the system, which can be used by apt to fetch the NodeJS packages. APT-based systems rely on a file named "Packages", which contains the inventory of the packages available in the repository. When looking at https://deb.nodesource.com/node_14.x/dists/focal/main/binary-amd64/Packages , I see that only the latest version is listed (Check the 2nd line on the Packages file), as of now it is `Version: 14.18.3-deb-1nodesource1` .

If you check this path https://deb.nodesource.com/node_14.x/pool/main/n/nodejs/, you can notice that much more versions are available in the repo. 

The problem that I'm unable to install any arbitrary version using `apt install nodejs=nodejs_14.11.0-1nodesource1`, I must manually download the package from the pool and install it with dpkg. I'd like to be able to rely on apt alone for this, and for this to work, the `Packages` file should contain all available versions. 

When this behavior is implemented, it will be possible to reproduce an older NodeJS runtime artefact with automated systems, defining the desired NodeJS major.minor.patch version number as a variable. 

This behaviour is successfully implemented by other projects, such as kubernetes.io and terraform.

**Comment by JesusPaz** [comment]
Thank you for contacting us. At this time at NodeSource, we do not have sufficient resources to handle this type of request. I will add a tag and close the issue for future review. Sorry for the inconvenience.
