### ISSUE TITLE
Your distribution, identified as "focal", is not currently supported - Still an issue

### ISSUE THREAD

**Issue by shaangontia** [nodesource/distributions#1350]
The issue mentioned below:
https://github.com/nodesource/distributions/issues/1044
still exists.

I am using

$ lsb_release -d -s
Ubuntu 20.04.3 LTS
and when I try running the command

curl -fksSL https://deb.nodesource.com/setup_lts.x | sudo bash -
I am getting the error

Confirming "focal" is supported...
curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/focal/Release'
Your distribution, identified as "focal", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
I think the issue with focal still exists. 

 Does that mean we have to upgrade to a newer Ubuntu version? Please help.

**Comment by JesusPaz** [comment]
Ubuntu Focal is currently supported and any issue during its installation is related to the environment and the network in which the installation is being carried out.

Similar issues with installations on subsystems and behind proxies: #1002 #947 #904 #9 and many more.

It's not a problem related to distributions or compatibility, but to the proxy setup.
