### ISSUE TITLE
CDN problem with deb.nodesource.com

### ISSUE THREAD

**Issue by ghost** [nodesource/distributions#1352]
Hello,

I am having a connection problem while fetching packages from deb.nodesource.com.

I could not use HTTPS connection nor fetch anything from deb.nodesource.com.

Is this normal?

![Capture](https://user-images.githubusercontent.com/91770832/156422350-edf20a18-e266-4015-9c31-afbf3924d18e.PNG)

![Capture (2)](https://user-images.githubusercontent.com/91770832/156422355-02e1919c-1c2a-4362-8da3-b6030af61475.PNG)

![Capture (3)](https://user-images.githubusercontent.com/91770832/156422731-8dfee793-700e-453d-9368-08cf86ed118a.PNG)

cc @JesusPaz @edsadr

**Comment by riosje** [comment]
as of today our distributions CDN is working properly.
If you're still experiencing some kind of connectivity issues, bring more details on a new issue.
