### ISSUE TITLE
NodeSource Node.js 17.x repo

### ISSUE THREAD

**Issue by Jonahc0014** [nodesource/distributions#1353]
My installation on Linux threw a odd error; You don't appear to be running an Enterprise Linux based system,
please contact NodeSource at https://github.com/nodesource/distributions/issues
if you think this is incorrect or would like your distribution to be considered
for support.

I'm not sure what to do with this

**Comment by JesusPaz** [comment]
I need more details to be able to help you with your problem. It looks like you are using a script for a different distribution.

In order to make it work you must use the correct script, in the case of Enterprise Linux based distributions use:
```
# As root
curl -fsSL https://rpm.nodesource.com/setup_17.x | bash -

# No root privileges
curl -fsSL https://rpm.nodesource.com/setup_17.x | sudo bash -
```
For Debian and Ubuntu based distributions
```
# Using Ubuntu
curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
sudo apt-get install -y nodejs

# Using Debian, as root
curl -fsSL https://deb.nodesource.com/setup_17.x | bash -
apt-get install -y nodejs
```

**Comment by Jonahc0014** [comment]
Thanks :)
