### ISSUE TITLE
The repository  does not have a Release file.

### ISSUE THREAD

**Issue by wajika** [nodesource/distributions#1354]
ubuntu: 20.04

```
sudo apt update
------------------------------
Reading package lists... Done
E: The repository 'https://deb.nodesource.com/node_17.x focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
```
https://deb.nodesource.com/node_17.x/dists/focal/
```
I see that the focal branch exists, why does apt prompt that it cannot be found? Has anyone encountered a similar situation?

**Comment by kczx3** [comment]
Same thing here for 16_x on bionic.

**Comment by himanshurathore29** [comment]
I also faced the same issue for install nodejs specific version:
you can go through Documentation

- **Install Node.js Locally with Node Version Manager (nvm)**

https://heynode.com/tutorial/install-nodejs-locally-nvm/

or a **youtube tutorial video** would be helpful too
https://youtu.be/OT7QOFvs9Lk

I hope my contribution will solve this problem.

**Comment by wajika** [comment]
> @JesusPaz I also faced the same issue for install nodejs specific version: you can simply go through Documentation
> 
> * **Install Node.js Locally with Node Version Manager (nvm)**
> 
> https://heynode.com/tutorial/install-nodejs-locally-nvm/
> 
> or a **youtube tutorial video** would be helpful too https://youtu.be/OT7QOFvs9Lk
> 
> I hope my contribution will solve this problem.

If you use a method other than apt to install, I think the problem should be solved, but I want to know why this problem occurs? If the cause can be found, it can reduce such problems

**Comment by JesusPaz** [comment]
This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).
