### ISSUE TITLE
Your distribution, identified as "ara", is not currently supported

### ISSUE THREAD

**Issue by gsairam08** [nodesource/distributions#1358]
Hello,
       I am trying to install nodejs current version using package manager it was not working.
       
       I am getting error as.
       
       **## Your distribution, identified as "ara", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support**

Currently i am running Parrot OS 5.0

**Comment by JesusPaz** [comment]
Unfortunately, we do not plan to support Parrot OS at this time, but it has been added to our list of requested distributions #1205.

When your distribution is not supported you can install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).

You can also help us to support this distribution, here are some examples of pull requests #1231 #1195. If you have any problems let us know.

**Comment by 0xAgun** [comment]
why not support parrot os is this for hackers only thats why are u afraid... that malicious package can be injected.. dude. I'm pissed.. trying to practice react but due to v12 can't event create app fkk.
