### ISSUE TITLE
LMDE 5 (elsie): Linux Mint Debian Edition (based on debian 11)

### ISSUE THREAD

**Issue by Kiminator** [nodesource/distributions#1360]
$ curl -sL https://deb.nodesource.com/setup_lts.x | sudo bash -

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/elsie/Release'

## Your distribution, identified as "elsie", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Thanks in advance for adding support for LMDE 5.

**Comment by Victormgomeza** [comment]
Please could you help us to support  the new version of LMDE in nodejs installers?
