### ISSUE TITLE
Your distribution, identified as "1.7_x86-64", is not currently supported

### ISSUE THREAD

**Issue by dposhivalnikov** [nodesource/distributions#1366]
Good afternoon! Please add support for Astra Linux 1.7. An error occurs when installing on this system:
Your distribution, identified as "1.7_x86-64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by JesusPaz** [comment]
Unfortunately, we do not plan to support Astra Linux at this time.

When your distribution is not supported you can install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).

You can also help us to support this distribution, here are some examples of pull request #1231 #1195. If you have any problems let us know.
