### ISSUE TITLE
distribution package Amazon Linux 2022 not supported

### ISSUE THREAD

**Issue by hodnett** [nodesource/distributions#1367]
Please add support for Amazon Linux 2022.

Since there is support for Amazon Linux 2, I am hopeful we just need to add this new distribution to the same auto-detection "block" as earlier generations of Amazon Linux.

Github's [page on AL2022](https://github.com/amazonlinux/amazon-linux-2022) has additional info including a Docker image for testing. 2022 is a tag that's guaranteed to point to the latest image of this generation so I'm not certain the output of my `uname -a` will be the same as yours, but in case you need it, mine is:

`Linux <DOCKER CONTAINER ID> 5.10.104-linuxkit #1 SMP Thu Mar 17 17:08:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by JesusPaz** [comment]
Hi @hodnett,

Can you show more information about the error you are having? I just created a vm on AWS and was able to install Gallium with no problems.

This is the output for `uname -a`:

`Linux <ID> 5.10.109-104.500.amzn2.x86_64 #1 SMP Wed Apr 13 20:31:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by timd73** [comment]
@JesusPaz 
That's not Amazon Linux 2022 - that's Amazon Linux 2.
This is what I get when I try on Amazon Linux 2022:

```$ uname -a
Linux <ID> 5.10.75-82.359.amzn2022.x86_64 #1 SMP Mon Nov 15 18:04:59 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ bash setup_16.x.sh

## Installing the NodeSource Node.js 16.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release || rpm -q --whatprovides fedora-release
+ uname -m

## You don't appear to be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support. Include your 'distribution package' name: no package provides redhat-release
no package provides centos-release
no package provides cloudlinux-release
no package provides sl-release
no package provides fedora-release.
```

I spun up an EC2 instance from one of the `al2022-ami` AMIs.

**Comment by hodnett** [comment]
@JesusPaz - will you please reopen this issue?

As @timd73 mentioned, Amazon 2 is not the same thing as Amazon 2022. Amazon recently decided to switch to a year based versioning system and technically, Amazon 2022 is Amazon Linux major version 3.

**Comment by okynos** [comment]
Hello all,

I'm facing this issue too, there is some workaround? Thanks.

**Comment by atsalolikhin-spokeo** [comment]
I ran into this as well.

```
[root@ip-172-20-92-18 ~]# wget -O /tmp/nodejs https://rpm.nodesource.com/setup_14.x
...
2022-05-25 17:29:08 (572 MB/s) - ‘/tmp/nodejs’ saved [13214/13214]

[root@ip-172-20-92-18 ~]# /tmp/nodejs

## Installing the NodeSource Node.js 14.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release || rpm -q --whatprovides fedora-release
+ uname -m

## You don't appear to be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support. Include your 'distribution package' name: no package provides redhat-release
no package provides centos-release
no package provides cloudlinux-release
no package provides sl-release
no package provides fedora-release.

[root@ip-172-20-92-18 ~]#
```

The release version package on Amazon Linux 2022 is called `system-release`:

```
[root@ip-172-20-92-18 ~]# rpm -qi system-release
Name        : system-release
Version     : 2022.0.20220504
Release     : 0.amzn2022
Architecture: noarch
Install Date: Mon 09 May 2022 05:29:43 PM UTC
Group       : Unspecified
Size        : 15591
License     : MIT
Signature   : RSA/SHA512, Thu 01 Jan 1970 12:00:00 AM UTC, Key ID f59904d8afaa0026
Source RPM  : system-release-2022.0.20220504-0.amzn2022.src.rpm
Build Date  : Tue 03 May 2022 10:34:14 PM UTC
Build Host  : ip-10-0-42-29.us-west-2.compute.internal
Packager    : Amazon Linux
Vendor      : Amazon Linux
URL         : https://amazonlinux.com/
Summary     : Amazon Linux release files
Description :
Amazon Linux release files
[root@ip-172-20-92-18 ~]#
```

I was able to install the "nodesource" repo RPM by patching the installation script:

```
[root@ip-172-20-92-18 ~]# diff /tmp/nodejs.orig /tmp/nodejs
183,184c183,185
< echo "+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release || rpm -q --whatprovides fedora-release"
< DISTRO_PKG=$(rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release || rpm -q --whatprovides fedora-release)
---
> echo "+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release || rpm -q --whatprovides fedora-release || rpm -q --whatprovides system-release"
> DISTRO_PKG=$(rpm -qa | egrep '(centos|cloudlinux|sl|fedora|system)-release')
> echo DISTRO_PKG=${DISTRO_PKG}
231a233,237
>   # Amazon Linux 2022
>   if uname -r | grep -F .amzn2022.; then
>     DIST_VERSION=8
>   fi
>
348c354
< exec_cmd "rpm -i --nosignature --force '${RPM_TMP}'"
---
> exec_cmd "rpm -i --nodeps --nosignature --force '${RPM_TMP}'"
[root@ip-172-20-92-18 ~]#
```

Ta-da!

```
[root@ip-172-20-92-18 ~]# dnf repolist
repo id                                              repo name
amazonlinux                                          Amazon Linux 2022 repository
nodesource                                           Node.js Packages for Enterprise Linux 8 - x86_64
[root@ip-172-20-92-18 ~]#
```

I don't know what this comment refers to, so I'm not sure if my change is completely proper, I didn't change it the same way in the echo statement as I did in the for loop:

```
## Annotated section for auto extraction in test.sh
```

**Comment by atsalolikhin-spokeo** [comment]
I am not sure which file(s) I would patch if I wanted to open a pull request:

```
[~/git/nodesource/distributions] [py-3.9.7] master ± git grep -l system-release
rpm/setup
rpm/setup_0.10
rpm/setup_0.12
rpm/setup_10.x
rpm/setup_11.x
rpm/setup_12.x
rpm/setup_13.x
rpm/setup_14.x
rpm/setup_15.x
rpm/setup_16.x
rpm/setup_17.x
rpm/setup_18.x
rpm/setup_4.x
rpm/setup_5.x
rpm/setup_6.x
rpm/setup_7.x
rpm/setup_8.x
rpm/setup_9.x
rpm/setup_current.x
rpm/setup_iojs_1.x
rpm/setup_iojs_2.x
rpm/setup_iojs_3.x
rpm/setup_lts.x
rpm/src/_setup.sh
[~/git/nodesource/distributions] [py-3.9.7] master ±
```

And what about adding `system-release` to the RPM build process? I don't see the RPM spec file:

```
[~/git/nodesource/distributions] [py-3.9.7] master ± find . | grep spec
[~/git/nodesource/distributions] [py-3.9.7] master ±
```

**Comment by riosje** [comment]
Hello @atsalolikhin-spokeo it looks like you already have a patch for the installation script.

do you mind help us to support this distribution?
here are some examples of pull request https://github.com/nodesource/distributions/pull/1231 - https://github.com/nodesource/distributions/pull/1195. If you have any problems let us know.

**Comment by atsalolikhin-spokeo** [comment]
I don't feel it's clean to force `rpm --nodeps`.  Where do you all build the RPM?  The spec file needs to be updated for Amazon Linux 2022.

**Comment by riosje** [comment]
Hello guys, Amazon Linux 2022 is still in preview, we will be able to support this version after the GA release.

https://aws.amazon.com/linux/amazon-linux-2022/faqs/
https://docs.aws.amazon.com/linux/al2022/ug/release-cadence.html 
<img width="648" alt="image" src="https://user-images.githubusercontent.com/55195249/177211705-1960c6b5-801c-476b-bacc-04a99de07c10.png">

**Comment by atsalolikhin-spokeo** [comment]
Thanks @riosje that totally makes sense.

**Comment by lifeofguenter** [comment]
@riosje I do not think this ticket should be closed when its not fixed.

**Comment by jlarmstrongiv** [comment]
@atsalolikhin-spokeo thank you so much!  Lifesaver

I created a github gist of the changes for setup_16.x:
- gist `https://gist.github.com/jlarmstrongiv/d6c4dbeeccc43a592e5f5a580e51359f`
- install `curl --silent --location https://gist.githubusercontent.com/jlarmstrongiv/d6c4dbeeccc43a592e5f5a580e51359f/raw/ce59c2247752f5dbb0e8f42c5fd980e9690c6f66/nodejs | bash -`

Feel free to git diff to see the changes, as they are similar to the original.

To install the latest nodejs16.x version, use `yum install -y nodejs-2:16.*`

---

@riosje while amazonlinux2022 is still in preview, I think it’s beneficial to support so that users and library authors can prepare for the transition.

**Comment by timd73** [comment]
Hi - between issue #1381 and this issue, it appears that I am in a catch-22, and unable to start testing the move to node18 on amazon linux:

1. I cannot upgrade to node18 on "amazon linux 2" because of #1381  - it appears that "glibc 2.28 or later" will not be available on amazon linux 2.
2. I'd like to upgrade to "amazon linux 2022" (yes, even though it's still at RC and not GA) but then I can't install any node due to this ticket (#1367)

So.... I need either this or #1381 (or both?) fixed.

Anyone else in this quandary and have a way out?

**Comment by atsalolikhin-spokeo** [comment]
@timd73 See https://github.com/nodesource/distributions/issues/1367#issuecomment-1137642816 for a workaround

**Comment by santialbo** [comment]
> Hello guys, Amazon Linux 2022 is still in preview, we will be able to support this version after the GA release.
> 
> https://aws.amazon.com/linux/amazon-linux-2022/faqs/ https://docs.aws.amazon.com/linux/al2022/ug/release-cadence.html <img alt="image" width="648" src="https://user-images.githubusercontent.com/55195249/177211705-1960c6b5-801c-476b-bacc-04a99de07c10.png">

Amazon Linux 2023 is now GA. Can we reopen this ticket?

**Comment by lifeofguenter** [comment]
What is not working with AL2023 @santialbo ?

**Comment by santialbo** [comment]
> What is not working with AL2023 @santialbo ?

```
$ curl -sL https://rpm.nodesource.com/setup_18.x | sudo bash -

## Installing the NodeSource Node.js 18.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release || rpm -q --whatprovides fedora-release
+ uname -m

## You don't appear to be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support. Include your 'distribution package' name: no package provides redhat-release
no package provides centos-release
no package provides cloudlinux-release
no package provides sl-release
no package provides fedora-release.
```

**Comment by lifeofguenter** [comment]
How is that related to Ansible @santialbo ?

**Comment by tivanov-qb** [comment]
@riosje can you review this ? it's reproducible with amazonlinux:latest

**Comment by riosje** [comment]
> @riosje can you review this ? it's reproducible with amazonlinux:latest

The next nodejs releases will be available for AL2023.

**Comment by matiasmasca** [comment]
For us, it is still a problem with the AWS AL2 on Workers

Your distribution, identified as **"system-release-2-16.amzn2.x86_64",** is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
