### ISSUE TITLE
Your distribution, identified as "apricot", is not currently supported

### ISSUE THREAD

**Issue by dmorfav** [nodesource/distributions#1368]
Hi i install deepin 20.5 and the script detect the distribution name as ```"apricot"``` and mark as not supported. Please can you add the distribution.

**Comment by JesusPaz** [comment]
Unfortunately, we do not plan to support Deepin at this time, but it has been added to our list of requested distributions #638.

When your distribution is not supported you can install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).

You can also help us to support this distribution, here are some examples of pull request #1231 #1195. If you have any problems let us know.
