### ISSUE TITLE
Support for Squeeze ? 

### ISSUE THREAD

**Issue by JnMik** [nodesource/distributions#137]
Hello guys

Just wondering if you are planning any Support For Squeeze ?

Tried to install latest nodejs on it and got this error
Your distribution, identified as "squeeze", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

thx !

**Comment by rvagg** [comment]
see also #23 and #29, sorry, it's out of scope and far too difficult
