### ISSUE TITLE
Debian 11 only installs v12.22.5

### ISSUE THREAD

**Issue by dobrosavljevic** [nodesource/distributions#1370]
After adding the nodesource repo according to the instructions provided [here](https://github.com/nodesource/distributions#debinstall) for Debian 11 the version that is still installed is v12.22.5, which is the default version that gets installed without the nodesource repo.

Am I missing something or we just not able to install latest versions with apt at the moment for whatever reason?

**Comment by Grothesk242** [comment]
No issue here. 

```apt policy nodejs```
tells you?

**Comment by redward** [comment]
nodejs:
  Installed: 12.22.5~dfsg-2~11u1
  Candidate: 12.22.5~dfsg-2~11u1
  Version table:
 *** 12.22.5~dfsg-2~11u1 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        500 http://security.debian.org/debian-security bullseye-security/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by dobrosavljevic** [comment]
I needed a newer version of node and wanted to make sure that it's updated through apt so I setup what I needed on Ubuntu instead and thought I'd report what I was finding on Debian. I would be happy to try again but I suspect I'd see similar to what redward posted above.

**Comment by XiaoPanPanKevinPan** [comment]
I just met and solved the problem on my Debian 11. It turned out that the script exited after running `apt-get update`, and the reason was some of my repo problems (such as unsigned repo). 

After solving the problem, it just worked well. Hope this info helps.

**Comment by JesusPaz** [comment]
Debian 11 is currently supported and any issue during its installation is related to the environment and the network in which the installation is being carried out.

Similar issues with installations on subsystems and behind proxies: #1002 #947 #904 #9 and many more.

It's not a problem related to distributions or compatibility, but to the proxy setup.
