### ISSUE TITLE
Error while installing node 16 in ubuntu docker image

### ISSUE THREAD

**Issue by mayuri2307** [nodesource/distributions#1371]
Installing packages required for setup: lsb-release gnupg...
apt-get install -y lsb-release gnupg > /dev/null 2>&1
Confirming "focal" is supported...
curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/focal/Release'
Your distribution, identified as "focal", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by JesusPaz** [comment]
Ubuntu Focal is currently supported and any issue during its installation is related to the environment and the network in which the installation is being carried out.

Similar issues with installations on subsystems and behind proxies: #1002 #947 #904 #9 and many more.

It's not a problem related to distributions or compatibility, but to the proxy setup.
