### ISSUE TITLE
Not supported on (UBUNTU 22.04 JAMMY JELLYFISH)

### ISSUE THREAD

**Issue by Iamkrishnaa** [nodesource/distributions#1379]
During installing nodejs from source on ubuntu 22.04 it is throwing error saying 
Your distribution, identified as "jammy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by Keetta** [comment]
I think the problem is that the page https://deb.nodesource.com/node_16.x/dists/jammy/Release is in 404 error

**Comment by joshxyzhimself** [comment]
#1359

**Comment by seojustin** [comment]
I'm running into this issue too, please take a look!!

`## Your distribution, identified as "jammy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support`

**Comment by mertgundoganx** [comment]
still...

**Comment by leonardobbh** [comment]
## Your distribution, identified as "jammy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by dhengGhuring** [comment]
Yes i have same problem, node V12+ not supported on Ubuntu 22.04 Jammy, please fix this

**Comment by tunasayin** [comment]
Same problem here...

**Comment by Keetta** [comment]
Use debian

**Comment by JukKie-ai** [comment]
same problem here, too.

**Comment by oscar6echo** [comment]
idem

**Comment by adi6499** [comment]
https://tecadmin.net/how-to-install-node-js-on-ubuntu-22-04/
try this

**Comment by oscar6echo** [comment]
@adi6499 in the link you give method 2 does not work.  

error msg: 
```
## Confirming "jammy" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/jammy/Release'

## Your distribution, identified as "jammy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by jie10** [comment]
Good day guys i found a solution!,
1st: install nvm.
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

2nd: copy and paste this line of code to use nvm.
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

3rd: install node version you like.
nvm install 18.0.0

4th: close the terminal and open new terminal then type "node -v" and "npm -v"
and it's working fine

**Comment by EntenKoeniq** [comment]
You can install them yourself for now (tested on Ubuntu 22.04):

`sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz`
`sudo tar -xvf node-v18.0.0-linux-x64.tar.xz`
`sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/`
`node --version` => `v18.0.0`

**Comment by oscar6echo** [comment]
tested @EntenKoeniq script.  
Works for me too.  
Thx

**Comment by dhengGhuring** [comment]
> Good day guys i found a solution!, (Ubuntu)
> 
> 1st: install nvm. curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
> 
> 2nd: copy and paste this line of code to use nvm. export NVM_DIR="$HOME/.nvm" [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
> 
> 3rd: check available version of node nvm list-remote
> 
> 4th: install node version you like. nvm install 18.0.0
> 
> 5th: close the terminal and open new terminal then type "node -v" and "npm -v" and it's working fine

I get error message can't install node js because permission denied
![image](https://user-images.githubusercontent.com/91442296/164955489-879af309-8909-42fa-98c3-bebf52d536e1.png)

**Comment by dhengGhuring** [comment]
> You can install them yourself for now (tested on Ubuntu 22.04):
> 
> `sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz` `sudo tar -xvf node-v18.0.0-linux-x64.tar.xz` `sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/` `node --version` => `v18.0.0`

Thankyou this work on me

**Comment by dhengGhuring** [comment]
> > Good day guys i found a solution!, (Ubuntu)
> > 1st: install nvm. curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
> > 2nd: copy and paste this line of code to use nvm. export NVM_DIR="$HOME/.nvm" [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
> > 3rd: check available version of node nvm list-remote
> > 4th: install node version you like. nvm install 18.0.0
> > 5th: close the terminal and open new terminal then type "node -v" and "npm -v" and it's working fine
> 
> I get error message can't install node js because permission denied ![image](https://user-images.githubusercontent.com/91442296/164955489-879af309-8909-42fa-98c3-bebf52d536e1.png)

To fix this i try unistall curl snap and install curl apt, and this work!

**Comment by InklingGirl** [comment]
Bump, please fix this, would rather not use workarounds.

**Comment by Rubanrubi** [comment]
> 18.0.

this is absolutely working fine

**Comment by Rubanrubi** [comment]
> You can install them yourself for now (tested on Ubuntu 22.04):
> 
> `sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz` `sudo tar -xvf node-v18.0.0-linux-x64.tar.xz` `sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/` `node --version` => `v18.0.0`

this is working fine kindly use this

**Comment by Iamkrishnaa** [comment]
> You can install them yourself for now (tested on Ubuntu 22.04):
> 
> `sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz` `sudo tar -xvf node-v18.0.0-linux-x64.tar.xz` `sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/` `node --version` => `v18.0.0`

This works if you want to perform it manually. If you want previous steps/processes wait until the new version is released.

**Comment by mertgundoganx** [comment]
> You can install them yourself for now (tested on Ubuntu 22.04):
> 
> `sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz` `sudo tar -xvf node-v18.0.0-linux-x64.tar.xz` `sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/` `node --version` => `v18.0.0`

thanks. that's work!

**Comment by timeloveboy** [comment]
here is my solution
run ok in  dockerfile

`ENV NODE_VERSION=16.14.2
RUN curl -LO https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz &&\
    tar -xvf node-v${NODE_VERSION}-linux-x64.tar.xz
ENV PATH=${PATH}:/node-v${NODE_VERSION}-linux-x64/bin
RUN npm i -g corepack && corepack enable
`

**Comment by Filipe-lima082** [comment]
> 
Here it worked perfectly!

**Comment by Filipe-lima082** [comment]
Here it worked perfectly!

**Comment by muchemiphilip** [comment]
@EntenKoeniq Thanks your solution works perfectly.

**Comment by joevaughan** [comment]
> You can install them yourself for now (tested on Ubuntu 22.04):
> 
> `sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz` `sudo tar -xvf node-v18.0.0-linux-x64.tar.xz` `sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/` `node --version` => `v18.0.0`

Thanks for this. Works perfectly. 

Note: You don't need 'sudo' for the curl or tar commands, only the cp command.

**Comment by danielbarbosadelima1998** [comment]
sudo rm -rf /etc/apt/sources.list.d/nodesource.list
sudo rm -rf  /usr/share/keyrings/nodesource.gpg
curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
node --version

**Comment by InklingGirl** [comment]
`curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -` seems to work now, finally.

**Comment by mahernoz-d** [comment]
https://deb.nodesource.com/setup_6.x and https://deb.nodesource.com/setup_8.x (6 and 8) links are not working properly. please check or let me know if there is any other method to do it.

**Comment by ThyagoLucas** [comment]
> You can install them yourself for now (tested on Ubuntu 22.04):
> 
> `sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz` `sudo tar -xvf node-v18.0.0-linux-x64.tar.xz` `sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/` `node --version` => `v18.0.0`

Works forme too! Tnks <3

**Comment by InklingGirl** [comment]
No need to do it that way anymore.

**Comment by kgb-financial-com** [comment]
Workarounds may still be needed for old, unmaintained versions, like version 12. For current versions 16 and 18, the issue is fixed, as reported by @InklingGirl :

> `curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -` seems to work now, finally.

**Comment by zakumoon** [comment]
for me in linux mint
$ sudo autoremove  
$ curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash - 
$ sudo apt-get install -y nodejs
