### ISSUE TITLE
Error: Cannot find module 'are-we-there-yet'

### ISSUE THREAD

**Issue by zodthepossum** [nodesource/distributions#138]
hoping someone can help, i installed node.js on ubuntu 14.04 virtual server with apache 2.4 on a MAC
after grappling with various instructions with the following
curl -sL https://deb.nodesource.com/setup_0.12 | sudo -E bash -
success and then apache instructed run "npm install npm -g" in root
after that i get the following error message see attached JPG
![npm_error](https://cloud.githubusercontent.com/assets/7981980/10152083/c3600020-6691-11e5-8e4a-edca89fc35ab.jpg)

be great if someone could point me in the right direction, i've been trying to install this for over a day with no luck
thanx

**Comment by rvagg** [comment]
Have a look here: https://github.com/npm/npm/search?q=are-we-there-yet&type=Issues&utf8=%E2%9C%93

A known issue with npm, using a very old version to upgrade to the newest. I believe the most reliable workaround is to `npm install npm@2 -g` to be on v2 first and then if you want to go to v3 with `npm install npm@latest -g` (which is what your command is trying to do).

**Comment by zodthepossum** [comment]
sorry but i get exactly the same error message with the command npm install npm@2 -g

**Comment by rvagg** [comment]
@zodthepossum try `npm install npm@1 -g` then, you may need to hop through major-versions perhaps

**Comment by zodthepossum** [comment]
i've worked through a lot of issues on that page and have tried subsequent versions
npm@1.4.28 & npm@2.14.4 as per  'Installing npm from older npm missing dependencies: Error: Cannot find module 'are-we-there-yet' #9644' 

error from npm-debug.log is;
116699 verbose etag debug from cache
116700 http 200 https://registry.npmjs.org/optionator/-/optionator-0.5.0.tgz
116701 error Error: ENOENT, chmod '/home/susana/tmp/npm-6631-wCcVvRS4/1442961446098-0.3583860835060477/package/LICENSE'
116702 error If you need help, you may report this log at:
116702 error     <http://github.com/isaacs/npm/issues>
116702 error or email it to:
116702 error     <npm-@googlegroups.com>
116703 error System Linux 3.13.0-32-generic
116704 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
116705 error cwd /home/susana/public_html/zod
116706 error node -v v0.10.25
116707 error npm -v 1.3.10
116708 error path /home/susana/tmp/npm-6631-wCcVvRS4/1442961446098-0.3583860835060477/package/LICENSE
116709 error fstream_path /home/susana/tmp/npm-6631-wCcVvRS4/1442961446098-0.3583860835060477/package/LICENSE
116710 error fstream_type File
116711 error fstream_class FileWriter
116712 error fstream_finish_call chmod
116713 error code ENOENT
116714 error errno 34
116715 error fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:305:19
116715 error fstream_stack Object.oncomplete (fs.js:107:15)
116716 verbose exit [ 34, true ]

however i cannot get it to load

any other suggestions? apache suggested do the install from root - but is this the right way to go? i am trying to install globally.

**Comment by rvagg** [comment]
Can you check if `dpkg -l | grep npm` doesn't show you have anything installed? you _shouldn't_ have an `npm` package installed but it's possible it's come from somewhere. If you do, uninstall it first, it shouldn't be there.

Then, reinstall the `nodejs` package again with: `sudo apt-get purge nodejs -y && sudo apt-get install nodejs` and you'll get a new npm. Then, don't do a full `npm install npm -g` because it'll upgrade you to version 3 which is a little bit buggy at the moment. Instead, run `npm install npm@2 -g` to get the latest of the v2 stream which is very stable.

Then `npm cache clean` to deal with your latest error. Alternatively, `rm -rf ~/tmp/ ~/.npm/` will do a full clean of the temporary npm files. Then try again.

**Comment by zodthepossum** [comment]
tried ...
Can you check if dpkg -l | grep npm doesn't show you have anything installed? you shouldn't have an npm package installed but it's possible it's come from somewhere. If you do, uninstall it first, it shouldn't be there.

Then, reinstall the nodejs package again with: sudo apt-get purge nodejs -y && sudo apt-get install nodejs and you'll get a new npm. Then, don't do a full npm install npm -g because it'll upgrade you to version 3 which is a little bit buggy at the moment. Instead, run npm install npm@2 -g to get the latest of the v2 stream which is very stable.

Then npm cache clean to deal with your latest error. Alternatively, rm -rf ~/tmp/ ~/.npm/ will do a full clean of the temporary npm files. Then try again.

still no luck, when i run
npm -v
throws Error: Cannot find module 'are-we-there-yet' ...
should i be taking this up at http://github.com/isaacs/npm/issues ?

**Comment by rvagg** [comment]
@zodthepossum yes, unfortunately this is an issue for npm and they are familiar with this problem because it's quite common at the moment. Sorry.

**Comment by zodthepossum** [comment]
@rvagg thanks for your help

**Comment by frank0718** [comment]
i installed yarn ; then run npm, i got this error ; i can't find any reason, so i will use yarn instead of it

**Comment by jdrydn** [comment]
FYI I got this module by (stupidly) running `npm install -g npm@3` in the [`node:7.9.0`](https://hub.docker.com/_/node/) container, when it already has npm 4.2.x installed 🤦‍♂️

**Comment by pajacobjean** [comment]
Error: Cannot find module 'are-we-there-yet

**Comment by pajacobjean** [comment]
Error: Cannot find module 'are-we-there-yet'
Require stack:
- C:\Users\jacob\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\log.js
- C:\Users\jacob\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\Users\jacob\AppData\Roaming\npm\node_modules\←[4mnpm←[24m\node_modules\←[4mnpmlog←[24m\log.js:2:16)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\jacob\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\npmlog\\log.js'←[39m,
    ←[32m'C:\\Users\\jacob\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js'←[39m
  ]
}

**Comment by MuhammadFahadbinSajjad** [comment]
i got same

**Comment by f1rstpers0n** [comment]
same
