### ISSUE TITLE
Not supported on popos 

### ISSUE THREAD

**Issue by ThatGuyJamal** [nodesource/distributions#1380]
I'm on `Pop!_OS 22.04 LTS x86_64` and I'm having problems installing `nodejs v17`. I keep getting errors saying: **Your distribution, identified as "jammy", is not currently supported**. 

How would I fix this?

**Comment by GlassedSilver** [comment]
Pop_OS is basically Ubuntu underneath the surface. Search this repo‘s issue tracker for „22.04“ and you‘ll get plenty of feedback already reported and answered.

tl;dr: wait a bit or use the alternative methods described there.

**Comment by JesusPaz** [comment]
Unfortunately, we do not plan to support Pop!_OS at this time, but it has been added to our list of requested distributions #924.

When your distribution is not supported you can install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).

You can also help us to support this distribution, here are some examples of pull requests #1231 #1195. If you have any problems let us know.
