### ISSUE TITLE
Can not install node 18 on amazonlinux2

### ISSUE THREAD

**Issue by VirgileZol** [nodesource/distributions#1381]
```
# curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
...
curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_18.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'
...
# yum install -y nodejs
Loaded plugins: ovl, priorities
amzn2-core                                                                                              | 3.7 kB  00:00:00     
236 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 2:18.0.0-1nodesource will be installed
--> Processing Dependency: libc.so.6(GLIBC_2.28)(64bit) for package: 2:nodejs-18.0.0-1nodesource.x86_64
--> Processing Dependency: libm.so.6(GLIBC_2.27)(64bit) for package: 2:nodejs-18.0.0-1nodesource.x86_64
--> Finished Dependency Resolution
Error: Package: 2:nodejs-18.0.0-1nodesource.x86_64 (nodesource)
           Requires: libc.so.6(GLIBC_2.28)(64bit)
Error: Package: 2:nodejs-18.0.0-1nodesource.x86_64 (nodesource)
           Requires: libm.so.6(GLIBC_2.27)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by JesusPaz** [comment]
Node.js 18 is compatible with Linux distributions based on glibc 2.28 or later, for example, Debian 10, RHEL 8, and Ubuntu 20.04.

You can find more information in the [release notes](https://github.com/nodejs/node/releases/tag/v18.0.0).

**Comment by RichardBradley** [comment]
Hi @JesusPaz , please could you expand your comment a little?

What is the resolution for users who want to use both node 18 and amazonlinux2?

Is there a workaround or are you saying this is not possible?

**Comment by RichardBradley** [comment]
See also 

https://repost.aws/questions/QUNO13SFKYS2eiCt3f0lwP4Q/how-to-install-node-js-18-in-amazon-linux-2-ami
>  such a beast exists, and is provided by amazon themselves: the nodejs 18 aws lambda runtime -- which exactly includes nodejs 18 in an amazonlinux2 image. That obviously means that there must be a way to run both of them together. Maybe AWS could share their knowledge about how to build that ...

and https://serverfault.com/questions/1132783/how-can-i-get-node18-on-amazonlinux2

**Comment by riosje** [comment]
Guys the thing is that AWS build their own version of Nodejs to run with glibc 2.27.
We do not build Nodejs we distribute the Nodejs binaries as it comes from https://nodejs.org we only create the deb and rpm packages.
There are several discussions on the node official repo about this.
We can do nothing about this.

**Comment by RichardBradley** [comment]
Thanks

> There are several discussions on the node official repo about this.

Are you able to link to any, please?

**Comment by yokrysty** [comment]
AWS nodejs 18 used in beanstalk environments:
https://elasticbeanstalk-platform-assets-eu-central-1.s3.eu-central-1.amazonaws.com/stalks/eb_nodejs18_amazon_linux_2_1.0.2234.0_20230627221929/lib/node-v18.16.1-linux-x64.tar.gz

**Comment by sapzs** [comment]
If you do not want to use the Docker image public.ecr.aws/lambda/nodejs:18 directly, you can copy node from that image to your own image via multi-stage build:

```Dockerfile
FROM public.ecr.aws/lambda/nodejs:18 as nodesource

FROM amazonlinux:2
ENV PATH="$PATH:/var/lang/bin"
COPY --from=nodesource /var/lang /var/lang

RUN npm i whatever
```

**Comment by udondan** [comment]
If you're using Docker, you can copy node 18 from the Amazon's own NodeJs18 Lambda image: https://serverfault.com/a/1141673/267588

**Comment by DragosPlaton90** [comment]
There is also the possibility to install node 18 from source `nvm install -s 18.x.x`

**Comment by j1mmie** [comment]
> Can be found by creating a sample NodeJS Beanstalk environment and looking at the Cloud Init logs/User Data of the instance that is created.

It would be amazing if there were an easier / reliable way to obtain the latest. Or if Amazon could document their build process somewhere. Have they announced that this is officially supported by them?

**Comment by rabbitfufu** [comment]
Does anyone have some links to arm binaries, by chance?

**Comment by riosje** [comment]
Hi @rabbitfufu  does the repo for arm is not working?

**Comment by duckworth** [comment]
> https://elasticbeanstalk-platform-assets-us-east-1.s3.amazonaws.com/stalks/eb_nodejs18_amazon_linux_2_1.0.2600.0_20231211220514/lib/node-v18.19.0-linux-x64.tar.gz

I just tried arm64 in the url and it seems to link to the arm build
https://elasticbeanstalk-platform-assets-us-east-1.s3.amazonaws.com/stalks/eb_nodejs18_amazon_linux_2_1.0.2600.0_20231211220514/lib/node-v18.19.0-linux-arm64.tar.gz

**Comment by riosje** [comment]
⚠️ I would not download binaries provided by external sources nor suggested by non-maintainers users.

**Comment by rabbitfufu** [comment]
Thanks -- I should have thought to try the url like that. 
Appreciate the help.
