### ISSUE TITLE
NodeJS 18 not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by cobalt2727** [nodesource/distributions#1392]
Looks like NodeJS 18 wasn't built properly for Ubuntu Bionic - it only has glibc 2.27...

(not my screenshot, but I can contact the uploader for any tests needed)

![image](https://user-images.githubusercontent.com/60624944/166636360-13b301ba-14bb-498c-9d6d-a1535efaa80b.png)

**Comment by JesusPaz** [comment]
Node.js 18 is compatible with Linux distributions based on glibc 2.28 or later, for example, Debian 10, RHEL 8, and Ubuntu 20.04.

You can find more information in the [release notes](https://github.com/nodejs/node/releases/tag/v18.0.0).

**Comment by cobalt2727** [comment]
Yes, I've read the release update. But the problem is NodeJS 18 **has a release file** [over here](https://deb.nodesource.com/node_18.x/dists/bionic/Release) for an OS you're telling me it doesn't support.

A fix for this problem would be to build NodeJS 18 on Debian Stretch, RHEL 7, Ubuntu 16.04 (which is still under ESM), or 18.04 (which is still receiving maintenance updates, as detailed [here](https://ubuntu.com/about/release-cycle)). If that's not possible for some reason, then the documentation needs updating. Is glibc 2.28 a hard requirement for NodeJS 18, or is that simply a side effect of the build environment used?

**Comment by theofficialgman** [comment]
agreed @JesusPaz , you should at MINIMUM remove the dists from your repo that nodejs18 doesn't support
you currently host packages for:
```
Index of /node_18.x/dists/
[../](https://deb.nodesource.com/node_18.x/)
[bionic/](https://deb.nodesource.com/node_18.x/dists/bionic/)                                            03-May-2022 15:55       -
[bookworm/](https://deb.nodesource.com/node_18.x/dists/bookworm/)                                          03-May-2022 15:55       -
[bullseye/](https://deb.nodesource.com/node_18.x/dists/bullseye/)                                          03-May-2022 15:55       -
[buster/](https://deb.nodesource.com/node_18.x/dists/buster/)                                            03-May-2022 15:55       -
[focal/](https://deb.nodesource.com/node_18.x/dists/focal/)                                             03-May-2022 15:55       -
[groovy/](https://deb.nodesource.com/node_18.x/dists/groovy/)                                            03-May-2022 15:55       -
[hirsute/](https://deb.nodesource.com/node_18.x/dists/hirsute/)                                           03-May-2022 15:55       -
[impish/](https://deb.nodesource.com/node_18.x/dists/impish/)                                            03-May-2022 15:55       -
[jammy/](https://deb.nodesource.com/node_18.x/dists/jammy/)                                             03-May-2022 15:55       -
[sid/](https://deb.nodesource.com/node_18.x/dists/sid/)                                               03-May-2022 15:55       -
[stretch/](https://deb.nodesource.com/node_18.x/dists/stretch/)                                           03-May-2022 15:55       -
[xenial/](https://deb.nodesource.com/node_18.x/dists/xenial/)                                            03-May-2022 15:55       -Index of /node_18.x/dists/
[../](https://deb.nodesource.com/node_18.x/)
[bionic/](https://deb.nodesource.com/node_18.x/dists/bionic/)                                            03-May-2022 15:55       -
[bookworm/](https://deb.nodesource.com/node_18.x/dists/bookworm/)                                          03-May-2022 15:55       -
[bullseye/](https://deb.nodesource.com/node_18.x/dists/bullseye/)                                          03-May-2022 15:55       -
[buster/](https://deb.nodesource.com/node_18.x/dists/buster/)                                            03-May-2022 15:55       -
[focal/](https://deb.nodesource.com/node_18.x/dists/focal/)                                             03-May-2022 15:55       -
[groovy/](https://deb.nodesource.com/node_18.x/dists/groovy/)                                            03-May-2022 15:55       -
[hirsute/](https://deb.nodesource.com/node_18.x/dists/hirsute/)                                           03-May-2022 15:55       -
[impish/](https://deb.nodesource.com/node_18.x/dists/impish/)                                            03-May-2022 15:55       -
[jammy/](https://deb.nodesource.com/node_18.x/dists/jammy/)                                             03-May-2022 15:55       -
[sid/](https://deb.nodesource.com/node_18.x/dists/sid/)                                               03-May-2022 15:55       -
[stretch/](https://deb.nodesource.com/node_18.x/dists/stretch/)                                           03-May-2022 15:55       -
[xenial/](https://deb.nodesource.com/node_18.x/dists/xenial/)                                            03-May-2022 15:55       -
```

this is disingenuous

**Comment by cobalt2727** [comment]
@JesusPaz it's been about a week - when can we receive an update or an ETA on this?

**Comment by Botspot** [comment]
If Node.js 18 doesn't work at all on older systems, then [information stating otherwise](https://deb.nodesource.com/node_18.x/dists/bionic/Release) should be removed or at least clarified.

Right now, anyone who tries to install the Node.js package on an older OS will find that it's completely broken.

**Comment by cobalt2727** [comment]
@chrislea Hi there - sorry if I'm pinging the wrong person, but would you be able to give us an update on what the plans are here?

**Comment by cobalt2727** [comment]
> Node.js 18 is compatible with Linux distributions based on glibc 2.28 or later, for example, Debian 10, RHEL 8, and Ubuntu 20.04.
> 
> You can find more information in the [release notes](https://github.com/nodejs/node/releases/tag/v18.0.0).

@JesusPaz Good morning/afternoon/evening.

![image](https://user-images.githubusercontent.com/60624944/169728107-62cf6468-43ea-4aa9-876d-1f17057ae9d1.png)

This issue needs to be reopened. No PPAs, external repos, or source builds (besides the building of NodeJS itself) were used in the process of bringing you the screenshot above. NodeJS 18 itself **does not require** glibc 2.28 or later to function. Saying so directly conflicts with [NodeJS's official documentation](https://github.com/nodejs/node/blob/v18.x/BUILDING.md#unix-and-macos), which lists off required dependencies that are **all** available just from Ubuntu 18.04's apt repository.

The decision to build NodeJS 18's binaries on newer environments needs to be fixed. As @Botspot and @theofficialgman pointed out above, it's resulting in critical installation failures with [packages being built that are impossible to install on the intended system, as shown here](https://deb.nodesource.com/node_18.x/dists/bionic/Release).

There are two solutions to this.
1. NodeJS 18+ packages from Nodesource get built on a build environment old enough to correctly support them - I'm willing to bet whatever you guys were building NodeJS 17 on probably still works, and if not, set up an extra build environment to handle all older systems still in use. I get it if you're not checking to make sure, say, Debian Jessie is being supported or anything, but 18.04 really still needs to be at *least* until it hits End of Life in [April 2023, or maybe even April 2028 if that's possible](https://wiki.ubuntu.com/Releases).
2. Nodesource stops listing distributions without glibc 2.28 as being compatible and leaves users on older systems on their own to just build things themselves.

One way or another, [this part of the README](https://github.com/nodesource/distributions#debian-and-ubuntu-based-distributions) is currently inaccurate and must be fixed.
![image](https://user-images.githubusercontent.com/60624944/169732165-2c077a48-7340-463d-851f-87dada7fcc4b.png)

**Comment by dominic-p** [comment]
Thanks for sharing that! I considered trying to build it myself, but I figured it was going to be a massive pain, and there's no way I was going to figure out the exceptions above on my own. For now, Node v16 is sufficient for my needs until I can get around to upgrading the host OS.

I'm just kind of surprised that Nodesource is leaving this closed. This issue is definitely not resolved.

**Comment by cobalt2727** [comment]
Hi @JesusPaz, any updates?

**Comment by TranNgocKhoa** [comment]
So current NodeJS LTS version will break on Ubuntu LTS 18.04. Is there any work around?

**Comment by lehni** [comment]
I just managed to get Node 20 to work on an Ubuntu 18 instance, by compiling my own version of glibc 2.28, installing it to `/opt/glibc-2.28` and using `patchelf` to patch `/usr/local/bin/node` to use it. It works like a charm, and building `glibc` takes much less time than building `node`. Instructions (on a Jetson Nano, so the arch-related details will vary):

```js
sudo -i

# Start by installing Node 20:

curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
bash n 20

# Node 20 is now at /usr/local/bin/node, but glibc 2.28 is missing

# Build and install glibc 2.28:
apt install -y gawk
cd ~
wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.28.tar.gz
tar -zxf glibc-2.28.tar.gz
cd glibc-2.28
../configure --prefix=/opt/glibc-2.28
make -j 4
make install
cd ..
rm -fr glibc-2.28 glibc-2.28.tar.gz
 
# Patch the installed Node 20 to work with /opt/glibc-2.28 instead: 
apt install -y patchelf
patchelf --set-interpreter /opt/glibc-2.28/lib/ld-linux-aarch64.so.1 --set-rpath /opt/glibc-2.28/lib/:/lib/aarch64-linux-gnu/:/usr/lib/aarch64-linux-gnu/ /usr/local/bin/node

# Et voilà:
node --version
v20.8.0
```

**Comment by riosje** [comment]
Hi @lehni shout outs to you for this instructions it looks pretty easy.
Not sure what would be the drawbacks of this.
Would you like to help us to create a `Non official Installation guide` on our wiki for node18 and node20 on unsupported distros.

**Comment by lehni** [comment]
@riosje I can't see any downside so far, but will keep an eye out and report back if I see issues with this approach. I don't really have time to write the wiki article, but feel free to use the above and add it there.

**Comment by ShotSkydiver** [comment]
@lehni this works perfectly! Just as a note for others, on x64 Ubuntu, you'll have to replace `aarch64-linux-gnu` with `x86_64-linux-gnu` and `ld-linux-aarch64.so.1` with `ld-linux-x86-64.so.2`.

**Comment by microdou** [comment]
@lehni Thanks a million! Finally resolved my issue in installing NodeJS 20 on Ubuntu 18 ❤️

**Comment by RomanovaCute** [comment]
@4KDA when i do "make install", an error appears. Maybe, you know how to fix it? i can't find

`make[2]: *** No rule to make target '/root/glibc-2.28/glibc-build/mathvec/libmvec.so.1', needed by '/opt/glibc-2.28/lib/libm.so'.  Stop.
make[2]: Leaving directory '/root/glibc-2.28/math'
Makefile:258: recipe for target 'math/subdir_install' failed
make[1]: *** [math/subdir_install] Error 2
make[1]: Leaving directory '/root/glibc-2.28'
Makefile:12: recipe for target 'install' failed
make: *** [install] Error 2
`

**Comment by adcb101** [comment]
i find another way. this link https://blog.csdn.net/Youning_Yim/article/details/129343107

1.deb http://security.debian.org/debian-security buster/updates main 
2. sudo apt update  # 更新软件源
3.sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 112695A0E562B32A 54404762BBB6E853
4.sudo apt list --upgradable   
5.sudo apt install libc6-dev  /sudo apt install libc6
6.strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC_

after finish all steps ,you can install hign version node.

**Comment by adcb101** [comment]
> @lehni @4KDA compile error when run 'make -j 4',the error output is as follows:
> 
> /tmp/glibc-2.28/nss/nss_files/files-key.c:101: undefined reference to `xdecrypt' collect2: error: ld returned 1 exit status ../Makerules:606: recipe for target '/tmp/glibc-2.28/glibc-build/nss/libnss_files.so' failed make[2]: *** [/tmp/glibc-2.28/glibc-build/nss/libnss_files.so] Error 1 make[2]: *** Waiting for unfinished jobs.... make[2]: Leaving directory '/tmp/glibc-2.28/nss' Makefile:258: recipe for target 'nss/others' failed make[1]: *** [nss/others] Error 2 make[1]: Leaving directory '/tmp/glibc-2.28' Makefile:9: recipe for target 'all' failed make: *** [all] Error 2
> 
> how to fix it? My building env is ubuntu 18.04.

Hi,i find another way ,you can try it,come from this article https://blog.csdn.net/Youning_Yim/article/details/129343107
1. deb http://security.debian.org/debian-security buster/updates main 
2. sudo apt update  # 更新软件源
3. sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 112695A0E562B32A 54404762BBB6E853
4. sudo apt list --upgradable   
5. sudo apt install libc6-dev  /sudo apt install libc6
6. strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC_

after finish all steps ,you can install high version node on ubuntu 18.04

**Comment by TCarmine** [comment]
executing 

   patchelf --set-interpreter /opt/glibc-2.28/lib/ld-linux-x86-64.so.2 

I got missing filename

**Comment by TCarmine** [comment]
actually at root running:

patchelf --set-interpreter /opt/glibc-2.28/lib/ld-linux-x86-64.so.2 --set-rpath /opt/glibc-2.28/lib/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/ /usr/local/bin/node

I got

stat: No such file or directory

**Comment by TCarmine** [comment]
seems now in glibc-2.28 lib folder is been renamed or changed

**Comment by TCarmine** [comment]
@4KDA I got an error at very last command in patch the new build for the library:

patchelf --set-interpreter /opt/glibc-2.28/lib/ld-linux-x86-64.so.2 --set-rpath /opt/glibc-2.28/lib/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/ /usr/local/bin/node

got 

stat: No such file or directory

I guess it refer to /usr/local/bin/node

P.S I am at my root Ubuntu(I see root@Legion~#)

**Comment by prantlf** [comment]
If you need to build a newer glibc, you may need to use a newer gcc, than the version available in the distro. For example, glibc 2.34 requires gcc 6, while Ubuntu 16 contains gcc 4. And upgrading the distro may not be easy for an exotic SBC hardware.

[As chrislea wrote](https://github.com/nodesource/distributions/issues/1392#issuecomment-1131930135), it's not easy to upgrade the interconnected gcc, libstc++ and glibc. Luckily, the team "PPA for Ubuntu Toolchain Uploads" prepares packages with newer gcc versions.

[4KDA's instructions](https://github.com/nodesource/distributions/issues/1392#issuecomment-1815887430) work great for newer glibcs too, once you install a newer gcc.

1. Install a newer gcc:

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-9 g++-9
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 \
  --slave /usr/bin/g++ g++ /usr/bin/g++-9

sudo apt-get install gcc-9 g++-9
```

2. Replace the instructions for glibc build configuration:

```
CC=/usr/bin/gcc-9 CXX=/usr/bin/g++-9 ../configure --prefix=/opt/glibc-2.34
```

3. Update the library path when patching binaries:

```
patchelf --set-interpreter /opt/glibc-2.34/lib/ld-linux-x86-64.so.2 \
  --set-rpath /opt/glibc-2.34/lib/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/ \
  <binary>
```

The rest of the instructions will work as-is.

**Comment by fraviofii** [comment]
> ```shell
> /opt/glibc-2.28/lib/ld-linux-x86-64.so.2
> ```

To have it working on a Jetson Nano machine, I replaced the last `patchelf` command for the following:

```
patchelf --set-interpreter /opt/glibc-2.28/lib/ld-linux-aarch64.so.1 --set-rpath /opt/glibc-2.28/lib/:/lib/aarch64-linux-gnu/:/usr/lib/aarch64-linux-gnu/ /usr/local/bin/node
```
