### ISSUE TITLE
Ubuntu jammy reports not supported

### ISSUE THREAD

**Issue by dimanz00** [nodesource/distributions#1395]
am installing nodejs 12 using nodesource but it says jammy is unsupported although release file is present on the repo.

**Comment by alexishida** [comment]
Ubuntu jammy dont't have any nodejs versions

**Comment by riosje** [comment]
@dimanz00 Nodejs 12 is not being supported anymore, you may want to try a manual installation
https://github.com/nodesource/distributions#manual-installation

@alexishida the issue with node17.X is gonna be tracked on this issue #1409
