### ISSUE TITLE
debian linux distro "apricot" not supported

### ISSUE THREAD

**Issue by Dorfeuheinz** [nodesource/distributions#1396]
$ curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -

## You don't appear to be running an Enterprise Linux based system,
please contact NodeSource at https://github.com/nodesource/distributions/issues
if you think this is incorrect or would like your distribution to be considered
for support.

**Comment by cobalt2727** [comment]
You're trying to run the RHEL/Fedora installation for some reason instead of the Debian/Ubuntu installation.
https://github.com/nodesource/distributions#installation-instructions

```bash
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by Dorfeuheinz** [comment]
Still shows the same error. I installed the correct thing. But it gives the same error.

## Confirming "apricot" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/apricot/Release'

## Your distribution, identified as "apricot", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by cobalt2727** [comment]
Interesting - what version of Debian is it based on?

**Comment by riosje** [comment]
Hello @Dorfeuheinz 
Unfortunately, we do not plan to support apricot at this time, but it has been added to our list of requested distributions.

When your distribution is not supported you can install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).

You can also help us to support this distribution, here are some examples of pull request #1231 -  #1195. If you have any problems let us know.
