### ISSUE TITLE
Installation failed when installing nodejs on Lubuntu

### ISSUE THREAD

**Issue by killerdroid99** [nodesource/distributions#1398]
I was facing the issue as same as [https://github.com/nodesource/distributions/issues/1157](url) and followed all the given steps there but there was this error
`/var/cache/apt/archives/nodejs_16.15.0-deb-1nodesource1_amd64.deb
trying to overwrite '/usr/share/systemtap/tapset/node.stp', which is also in package libnode72:amd64 12.22.9~dfsg-1ubuntu3`
i also forcefully removed the `node.stp` using `sudo rm -rf /usr/share/systemtap/tapset/node.stp` but it had no effect. I had also tried to install node js via the muon package manager built into Lubuntu but it still gives this error.

**Comment by riosje** [comment]
Hello @killerdroid99 it looks like the solution for your issue is already documented on this issue https://github.com/nodesource/distributions/issues/1157#issuecomment-1131212089 as @user4me already mentioned it

> Hi,
> 
> It seems another post with the same topic should help you : [#1157 (comment)](https://github.com/nodesource/distributions/issues/1157#issuecomment-1131212089)
> 
> I was facing the same issue and it works for me, hope it will for you !

Thank you @user4me

**Comment by maxflorex** [comment]
> Hi,
> 
> It seems another post with the same topic should help you : [#1157 (comment)](https://github.com/nodesource/distributions/issues/1157#issuecomment-1131212089)
> 
> I was facing the same issue and it works for me, hope it will for you !

This worked flawlessly for me! Cheers :)

**Comment by killerdroid99** [comment]
yes it worked

**Comment by danger89** [comment]
Actually in my case I first removed `apt purge nodejs` (the old version). Then `apt autoremove`. Finally install again `apt install nodejs`. Which is basically removing those conflicting deps for you.

**Comment by AbdullahJr69** [comment]
> apt purge nodejs
> apt autoremove
> apt install nodejs

worked for me, thanks <3

**Comment by tigranParemuzian** [comment]
`sudo apt remove libnode72 && sudo apt install -y nodejs`

Worked for me

**Comment by kushan-gunasekera** [comment]
this is for `libnode-dev` package

[https://stackoverflow.com/a/75943902/6194097](https://stackoverflow.com/a/75943902/6194097)
