### ISSUE TITLE
Errors during downloading

### ISSUE THREAD

**Issue by ivan-kramarenko** [nodesource/distributions#1401]
**Version**
16

**Platform**
Fedora Linux 36 - x86_64

**What steps will reproduce the bug?**
During installation, an error occurs, as a result of which it is not possible to install NodeJS.

![изображение](https://user-images.githubusercontent.com/81351460/170633093-21ec39b5-bd3a-47cf-94fb-c072124e369e.png)

**Comment by riosje** [comment]
Hello @ivan-kramarenko I'm so sorry for you your inconvenience.
this is a network issue from our CDN side, this issue is already being discussed here -> https://github.com/nodesource/distributions/issues/1362

**Comment by undefinedaspect** [comment]
> Hello @ivan-kramarenko I'm so sorry for you your inconvenience. this is a network issue from our CDN side, this issue is already being discussed here -> #1362

The post you mentioned ended up being a whole political mess, can we get this fixed ASAP?
