### ISSUE TITLE
Package nodejs-18.3.0-1nodesource.x86_64.rpm is not signed

### ISSUE THREAD

**Issue by heitkergm** [nodesource/distributions#1405]
This started today (6/2/2022).  running Fedora 36, and updating an existing install of nodejs 18...

**Comment by jknaus** [comment]
I can confirm this also for Fedora 35 + nodejs18

**Comment by GeorgeDakhil** [comment]
I have this fix > **Package nodejs-18.3.0-1nodesource.x86_64.rpm is not signed.**

Does anyone know how to solve?

**Comment by riosje** [comment]
Hello guys, we're looking into this issue to fix it.
We expect this to be solved on the next release.

**Comment by ripsivis** [comment]
use `--nogpgcheck` flag with dnf to skip gpg check temporarily

**Comment by SiqueiraX** [comment]
same issue :(

**Comment by Zabrah** [comment]
> use `--nogpgcheck` flag with dnf to skip gpg check temporarily

@ripsivis Is this secure to do? Did you made this and is everything working correctly?

**Comment by geosuna** [comment]
> use `--nogpgcheck` flag with dnf to skip gpg check temporarily

it worked for me, thanks!

**Comment by jknaus** [comment]
Seems to be fixed in 18.4.0

**Comment by riosje** [comment]
Hello guys on the latests versions this issue has been fixed.
