### ISSUE TITLE
Error: Cannot find Module binaries/uws_linux_arm64_108.node

### ISSUE THREAD

**Issue by mrghubba** [nodesource/distributions#1407]
When I tried to run 'NPM Start' for Trufffle Suite, I got this error: **https://paste.pics/H6C18_**

My system is Ubuntu 20.04 ARM64. I can't seem to find a Node JS version with binaries that works for this system.

**Comment by riosje** [comment]
Hello @mrghubba it looks like you have missing dependencies in your project.

This repo is intended only to bring support for the package distribution and installation.
I expect you can can find a solution for your issue on [StackOverflow ](https://stackoverflow.com/questions/tagged/node.js)or any other [NodeJs community Channel](https://nodejs.org/en/get-involved/)
