### ISSUE TITLE
LTS set up

### ISSUE THREAD

**Issue by andreighh** [nodesource/distributions#1408]
Does setting-up the LTS repository mean that node will update when a new major version becomes LTS?

I've set-up the LTS repository and it seems to point to the `16.x` one. When node 18 becomes LTS (around october I think), will the repository automatically point to `18.x` or will I have to uninstall everything and set-up the script again for LTS?

**Comment by riosje** [comment]
Hello @andreighh you will need to uninstall the old version and execute the setup again for the new one.

**Comment by andreighh** [comment]
Thanks for the answer, @riosje!
