### ISSUE TITLE
Node 0.12.x for el6 vanished from repo

### ISSUE THREAD

**Issue by azilber** [nodesource/distributions#141]
Received this error:
"https://rpm.nodesource.com/pub/el/6/x86_64/nodejs-0.12.7-1nodesource.el6.x86_64.rpm: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found""

Checked the repo, and all the 0.12.x packages are gone, even though I still have old repo data from when it existed.

**Comment by chrislea** [comment]
It looks like you're looking in the wrong directory. Here's where you want to be:

<https://rpm.nodesource.com/pub_0.12/el/6/x86_64/>

**Comment by azilber** [comment]
If that is the case, then the repo data is incorrect because  0.10.40-1nodesource.el6 is shown as the latest nodejs.

# yum clean all
Loaded plugins: fastestmirror, priorities, security
Cleaning repos: base elrepo epel extras mariadb nodesource updates
Cleaning up Everything
Cleaning up list of fastest mirrors
[root@sfdbtestslave1 yum.repos.d]# yum install nodejs
Loaded plugins: fastestmirror, priorities, security
Setting up Install Process
Determining fastest mirrors
epel/metalink                                                                                                        |  12 kB     00:00
 * elrepo: dfw.mirror.rackspace.com
 * epel: fedora-epel.mirror.lstn.net
base                                                                                                                 | 3.7 kB     00:00
base/primary_db                                                                                                      | 4.6 MB     00:00
elrepo                                                                                                               | 2.9 kB     00:00
elrepo/primary_db                                                                                                    | 730 kB     00:00
epel                                                                                                                 | 4.3 kB     00:00
epel/primary_db                                                                                                      | 5.7 MB     00:00
extras                                                                                                               | 3.4 kB     00:00
extras/primary_db                                                                                                    |  32 kB     00:00
mariadb                                                                                                              | 2.9 kB     00:00
mariadb/primary_db                                                                                                   |  20 kB     00:00
nodesource                                                                                                           | 2.5 kB     00:00
nodesource/primary_db                                                                                                |  17 kB     00:00
updates                                                                                                              | 3.4 kB     00:00
updates/primary_db                                                                                                   | 1.9 MB     00:00
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 0:0.10.40-1nodesource.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================================================================
 Package                     Arch                        Version                                      Repository                       Size
============================================================================================================================================
Installing:
 nodejs                      x86_64                      0.10.40-1nodesource.el6                      nodesource                      4.6 M

Transaction Summary
============================================================================================================================================
Install       1 Package(s)

Total download size: 4.6 M
Installed size: 16 M
Is this ok [y/N]: y
Downloading Packages:
nodejs-0.10.40-1nodesource.el6.x86_64.rpm                                                                            | 4.6 MB     00:00
warning: rpmts_HdrFromFdno: Header V3 RSA/SHA1 Signature, key ID 34fa74dd: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
Importing GPG key 0x34FA74DD:
 Userid : NodeSource <gpg-rpm@nodesource.com>
 Package: nodesource-release-el6-1.noarch (installed)
 From   : /etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
Is this ok [y/N]: y
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : nodejs-0.10.40-1nodesource.el6.x86_64                                                                                    1/1
  Verifying  : nodejs-0.10.40-1nodesource.el6.x86_64                                                                                    1/1

Installed:
  nodejs.x86_64 0:0.10.40-1nodesource.el6

Complete!
This is what's in nodesource-el.repo:

# cat /etc/yum.repos.d/nodesource-el.repo 
```
[nodesource]
name=Node.js Packages for Enterprise Linux 6 - $basearch
baseurl=https://rpm.nodesource.com/pub/el/6/$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL

[nodesource-source]
name=Node.js for Enterprise Linux 6 - $basearch - Source
baseurl=https://rpm.nodesource.com/pub/el/6/SRPMS
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
gpgcheck=1
```


That repo data is generated via curl -sL https://rpm.nodesource.com/setup | bash -

**Comment by azilber** [comment]
Attempting to use: curl -sL https://rpm.nodesource.com/setup_0.12 | bash -

we get:

# yum --disablerepo=epel install nodejs
Loaded plugins: fastestmirror, priorities, security
Setting up Install Process
Loading mirror speeds from cached hostfile
 * elrepo: repos.dfw.lax-noc.com
No package nodejs available.
