### ISSUE TITLE
Ip Blocked

### ISSUE THREAD

**Issue by lopezrodrigo** [nodesource/distributions#1410]
Hello, we have a problem installing Nodejs on the organization Debian servers from the nodesource repositories
It seems that our ips are blocked, when we try to download the installation script we get : 
 curl -sL https://deb.nodesource.com/setup_18.x
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;deb&#46;nodesource&#46;com&#47;setup&#95;18&#46;x" on this server.<P>
Reference&#32;&#35;18&#46;a4bc1002&#46;1655953307&#46;1c6397ff
</BODY>
</HTML>

Can anyone help in check if the ips are blacklisted an how to delist them ?

**Comment by riosje** [comment]
Hi @lopezrodrigo do you still have this issue?
can you add some verbosity to the curl command with `-vv` and attach here the output.
Additionally can you provide some additional info, are you behind some VPN or proxy service?

**Comment by riosje** [comment]
You're getting this error `Connection state changed (MAX_CONCURRENT_STREAMS == 100)!` does your proxy support `HTTP/2`?
can you try to to force the curl with `http1.1` something like this:
`curl -fsSL https://deb.nodesource.com/setup_18.x --http1.1 --proxy http://10.50.114.101:3128/`

Additional try with http, jut to discar ssl issues from the proxy side.

**Comment by riosje** [comment]
@lopezrodrigo still having the same issue?

**Comment by lopezrodrigo** [comment]
Hello, yes, we are having the same issue, we still get  "The requested URL returned error: 403 Forbidden" even from the proxy itself (that ip address is NATed ).
I checked my public ip addresses in akamai and the reputation is good.
Don´t know what else to check, any idea?

**Comment by riosje** [comment]
Hi @lopezrodrigo we've raised a ticket with akamai to se whats going on.
We will be in touch with you as soon as they give us an answer.

**Comment by lopezrodrigo** [comment]
Hello, i paste the error as requested: 
:/home/rodrigo# curl -v -fsSL http://deb.nodesource.com/setup_18.x --http1.1
* Hostname was NOT found in DNS cache
*   Trying 2.16.188.168...
* Connected to deb.nodesource.com (2.16.188.168) port 80 (#0)
> GET /setup_18.x HTTP/1.1
> User-Agent: curl/7.38.0
> Host: deb.nodesource.com
> Accept: */*
>
* The requested URL returned error: 403 Forbidden
* Closing connection 0
curl: (22) The requested URL returned error: 403 Forbidden


The public IP from where i´m triying to access is 190.3.92.170.

Thanks.

**Comment by lopezrodrigo** [comment]
Sorry, here it is: 
 curl -sL https://deb.nodesource.com/setup_18.x
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;deb&#46;nodesource&#46;com&#47;setup&#95;18&#46;x" on this server.<P>
Reference&#32;&#35;18&#46;24951602&#46;1659381537&#46;7206bcf
</BODY>
</HTML>

**Comment by riosje** [comment]
@lopezrodrigo it looks like we blocked in the past that Ip address because of an unexplainable huge amount of requests during a long period time.
I just removed your Ip address of the blacklist, you should be able to access the repo now.

**Comment by lopezrodrigo** [comment]
Thank you very much, its working now. The problem with the amount of requests was long time ago, it was derivated from a missconfigured monitoring system that checks for updates and by default was checking every minute, now it´s checking once per day.
Can you check this other ip:  190.12.101.219 ?  Probably is the same issue, because we use both, changing from one to the other  when one link fails.

**Comment by riosje** [comment]
@lopezrodrigo I remove that one too.
If you want to monitor new NodeJS releases, I highly suggest you to subscribe directly to the repo notifications, We usually deploy the DEB and RPM packages within the first 24hours after the official release.

https://github.com/nodejs/node 

![image](https://user-images.githubusercontent.com/55195249/182713625-b2694f19-9fd3-412d-a535-fea35a25d348.png)
