### ISSUE TITLE
LDME multiboot iso (feature request and solution)

### ISSUE THREAD

**Issue by trupf** [nodesource/distributions#1411]
Currently you write "The LMDE ISOs and the live installer use a different structure than the ones used by other distributions. Do not use Yumi or multiboot technologies with LMDE as it won't install properly." But actually, you ar very clos to a working .iso.

As far as I see you would only neet to add the fooling boot parameters to the grub command line in your loopback .cfg:
"live-media=removable findiso=$iso_path "

The compete menu etry would change from:
menuentry "Start Linux Mint Cinnamon 64-bit (5)" {
    set gfxpayload=keep
    linux   /live/vmlinuz boot=live live-config live-media-path=/live quiet splash --
    initrd  /live/initrd.lz

to something like this:
menuentry "Start Linux Mint Cinnamon 64-bit (5)" {
    set gfxpayload=keep
    linux   /live/vmlinuz boot=live live-config live-media=removable findiso=$iso_path quiet splash --
    initrd  /live/initrd.lz

You could even leave out the "live-media-path=/live" part, but at least it doesn't hurt if it remains. Of coure you need to do the same modification to all menuentries. With this simple modification it should start with tools like YUMI....

**Comment by trupf** [comment]
Or just di it the way Debian does:

if [ ${iso_path} ] ; then
set loopback="findiso=${iso_path}"
export loopback
fi
menuentry "Start Linux Mint Cinnamon 64-bit (5)" {
  set gfxpayload=keep
  linux /live/vmlinuz boot=live live-config live-media-path=/live splash quiet  "${loopback}"
  initrd /live/initrd.lz
}

This way you can even put everythin to grub.cfg and make a loopback.cfg just to source the grub.cfg with 1 line:
"source /boot/grub/grub.cfg"

**Comment by riosje** [comment]
@trupf is this issue related directly to the NodeJS dpkg or rpm packages?

**Comment by trupf** [comment]
No. it has nothing to do with node.js, it is an issue with the live iso distribution of the LDME projekt. Looks like I have posted the issue at the wrong place...
