### ISSUE TITLE
Please add support for "jammy"

### ISSUE THREAD

**Issue by samjeezy** [nodesource/distributions#1416]
Was doing a terminal install of node.js and ran into this issue:

## Confirming "jammy" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_17.x/dists/jammy/Release'

**Comment by riosje** [comment]
Hello @samjeezy.
Nodejs 17 is not being supported anymore, Please check below the current maintained versions
![image](https://user-images.githubusercontent.com/55195249/178087910-f94ccf14-e2f0-44d5-b6ae-8fb55dd21597.png)
Image source: https://nodejs.org/en/about/releases

Also you can try to install ir manually by following the documentation
https://github.com/nodesource/distributions#debmanual

Or search your desired package and manually try to install it
https://deb.nodesource.com/node_17.x/pool/main/n/nodejs/
