### ISSUE TITLE
Fedora 22 support

### ISSUE THREAD

**Issue by voor** [nodesource/distributions#142]
Hi, looks like the current script has some issues with Fedora 22:
```
➜  ~  curl --silent --location https://rpm.nodesource.com/setup | bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release
+ uname -m

## Confirming "fc22-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub/fc/22/x86_64/nodesource-release-fc22-1.noarch.rpm'

## Your distribution, identified as "fedora-release-22-1.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

```

However, you definitely have some RPMs for f22 at https://rpm.nodesource.com/pub/fc/22/x86_64/

**Comment by maklemenz** [comment]
+1

**Comment by rvagg** [comment]
please feel free to download the f22 rpms from the link above, they'll work just fine, it's just that they have been in a "testing" state for a while so not hooked up to the release script (plus we only have them for fedora and el7 so it's not as complete as we hoped to get at this point)

we'll update the setup scripts as soon as we're confident with the state of things

**Comment by voor** [comment]
Is this the place where we ask about the progress with 0.12.x or 4.0.x on Fedora systems?

**Comment by rvagg** [comment]
Oh, sorry, "link above" was wrong in my comment, I misread what @voor posted, see this link for those rpms: https://rpm.nodesource.com/pub_4.x/ i.e. put a `_4.x` after `pub` and you'll get what we have already for v4.x. They are usable now as per my comment above.

**Comment by voor** [comment]
Thanks, I'm pulling everything down now and installing!

**Comment by mMerlin** [comment]
to reduce some manual entry, as root:
```sh
wget https://rpm.nodesource.com/setup
vi setup
:s/pub/pub_4.x/
:wq
chmod +x setup
./setup
rm setup
```
