### ISSUE TITLE
Node js 12.x is no longer actively supported while adding the PPA to the Ubuntu system.

### ISSUE THREAD

**Issue by waqarGIT** [nodesource/distributions#1423]
Your distribution, identified as "jammy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Anyone have idea what is the problem?

**Comment by riosje** [comment]
Hello @waqarGIT as the warning says we no longer maintain and/or support Node12 anymore.

take a look to the current supported versions:
https://nodejs.org/en/about/releases/

If you really need to install this unsupported version you can try to do it manually, just follow the instructions.
https://github.com/nodesource/distributions#debmanual
