### ISSUE TITLE
Linux Mint 21(vanessa) error on install nodejs LTS

### ISSUE THREAD

**Issue by arthurgomespassos** [nodesource/distributions#1424]
Installing the NodeSource Node.js 16.x repo...

Populating apt-get cache...

apt-get update
Hit:1 http://ubuntu.c3sl.ufpr.br/ubuntu jammy InRelease
Hit:2 http://ubuntu.c3sl.ufpr.br/ubuntu jammy-updates InRelease                
Get:3 http://ubuntu.c3sl.ufpr.br/ubuntu jammy-backports InRelease [99,8 kB]    
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]      
Ign:5 https://mirror.ufscar.br/mint-archive vanessa InRelease                  
Hit:6 https://mirror.ufscar.br/mint-archive vanessa Release                    
Hit:8 https://packages.microsoft.com/repos/code stable InRelease               
Fetched 210 kB in 1s (254 kB/s)                                                
Reading package lists... Done

Confirming "vanessa" is supported...

curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/vanessa/Release'

Your distribution, identified as "vanessa", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by dhanyn10** [comment]
Im waiting

**Comment by arielsaucedo** [comment]
Any solution? Thank!

**Comment by KaKi87** [comment]
Two workarounds :
1. Use the solution described by the PR author [here](https://github.com/nodesource/distributions/pull/1422#issuecomment-1202203051)
2. Use [`nvm`](https://github.com/nvm-sh/nvm)

**Comment by SZemanek** [comment]
would it be possible to have unrecognized Linux Mint versions (and other Ubuntu variants) check /etc/upstream-release/lsb-release instead of relying on manually updating this script every time Linux Mint releases a new version every couple of months?
