### ISSUE TITLE
Request on issue(Your distribution, identified as "ara", is not currently supported)

### ISSUE THREAD

**Issue by Nandakishore-cmd** [nodesource/distributions#1425]
Your distribution, identified as "ara", is not currently supported

**Comment by JesusPaz** [comment]
Unfortunately, we do not plan to support ara at this time.

When your distribution is not supported you can install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).

You can also help us to support this distribution, here are some examples of pull request #1231 #1195. If you have any problems let us know.
