### ISSUE TITLE
i want 16.13.2

### ISSUE THREAD

**Issue by SakuraLxm** [nodesource/distributions#1427]
i want nodejs 16.13.2 ,but i get 16.16 ...
![image](https://user-images.githubusercontent.com/22929594/183251026-fa4646a3-e345-4887-bf3c-885546a53ca5.png)
![image](https://user-images.githubusercontent.com/22929594/183251036-1c8ceebc-fe06-48ee-aa49-dcea0e302cfc.png)
help me please

**Comment by wolfiediscord** [comment]
Nodesource only provides the latest version of Node.JS in their repositories. You will most likely have to install Node.JS 16.13.2 using [NVM](https://github.com/nvm-sh/nvm).

**Comment by JesusPaz** [comment]
Duplicate of #33
