### ISSUE TITLE
Linux Mint 21 Vanessa request for support 

### ISSUE THREAD

**Issue by KPiedra23** [nodesource/distributions#1430]
I would like Linux Mint Vanessa be considered for support. Thanks in advance

**Comment by Captainpast** [comment]
According to _README.md_ **Linux Mint 21 "Vanessa"** is supported, but I always get the following message
```
## Confirming "vanessa" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/vanessa/Release'

## Your distribution, identified as "vanessa", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```
I wonder about the URL [https://deb.nodesource.com/node_16.x/dists/**vanessa**/Release](https://deb.nodesource.com/node_16.x/dists/vanessa/Release), because vanessa is supported via _Ubuntu 22.04 "Jammy"_ and the mapping seems to be wrong.
The URL should be [https://deb.nodesource.com/node_16.x/dists/**jammy**/Release](https://deb.nodesource.com/node_16.x/dists/jammy/Release)

**Comment by commanddotcom** [comment]
```
## Your distribution, identified as "vanessa", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

```

**Comment by edueocara27** [comment]
Same problem here. Linux Mint 21 does not appear to be supported.

**Comment by Proberts** [comment]
work-around (change _18.x to whichever version you want):

1. `cd /tmp; curl -fsSL https://deb.nodesource.com/setup_18.x > node_setup_18.x`
2. edit node_setup_18.x line ~240 add: `check_alt "Linux Mint"    "vanessa"      "Ubuntu" "jammy"`
3. save
4. `sudo -E bash node_setup_18.x`
5. `sudo apt-get install -y nodejs`

**Comment by malisoft** [comment]
> work-around (change _18.x to whichever version you want):
> 
> 1. `cd /tmp; curl -fsSL https://deb.nodesource.com/setup_18.x > node_setup_18.x`
> 2. edit node_setup_18.x line ~240 add: `check_alt "Linux Mint"    "vanessa"      "Ubuntu" "jammy"`
> 3. save
> 4. `sudo -E bash node_setup_18.x`
> 5. `sudo apt-get install -y nodejs`

works, thank you

**Comment by ailtonbsj** [comment]
Run sequentially on terminal:

```bash
KEYRING=/usr/share/keyrings/nodesource.gpg

curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | sudo tee "$KEYRING" >/dev/null

echo "deb [signed-by=$KEYRING] https://deb.nodesource.com/node_18.x jammy main" | sudo tee /etc/apt/sources.list.d/nodesource.list

sudo apt-get update

sudo apt-get install nodejs
```

**Comment by JesusPaz** [comment]
Changes to support Linux Mint are already in our repo. They will be updated in our CDN soon.
