### ISSUE TITLE
 Your distribution, identified as "jammy", is not currently supported

### ISSUE THREAD

**Issue by kenkomu** [nodesource/distributions#1434]
I am trying to install the latest version of node.js

**Comment by gaurav-ingalkar** [comment]
getting the same error while installing node 14

**Comment by AZ7562** [comment]
getting the exact same error when trying to install Node 18

**Comment by AlexanderDmitriyev** [comment]
I get the same error for any version

**Comment by fantianmi** [comment]
Please check your network,  jammy is a node verseion we need to install

**Comment by riosje** [comment]
@gaurav-ingalkar Node14 is not being maintained any more.

**Comment by tinyoverflow** [comment]
@riosje While this is true, there are possibilities that old node versions are still required for legacy projects where an upgrade is not possible or too expensive due to various reasons. A project I'm participating in requires Node 13, for example.

**Comment by JesusPaz** [comment]
When your distribution is not supported you can install the packages manually by following our [README](https://github.com/nodesource/distributions#manual-installation).

**Comment by mehaase** [comment]
I tried multiple Ubuntu LTS and both node 16 and 18 and all were reporting this "not supported" error. Scratching my head until I realize that it uses curl and a certificate error will produce this "distribution not supported" message, which is misleading.
