### ISSUE TITLE
not able to install node js lts 

### ISSUE THREAD

**Issue by kunjbosamia** [nodesource/distributions#1436]
$ sudo curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -

##Installing the NodeSource Node.js 16.x repo...

##Populating apt-get cache...

+apt-get update
Ign:1 cdrom://Ubuntu 22.04 LTS _Jammy Jellyfish_ - Release amd64 (20220419) jammy InRelease
Err:2 cdrom://Ubuntu 22.04 LTS _Jammy Jellyfish_ - Release amd64 (20220419) jammy Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Hit:3 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:4 http://in.archive.ubuntu.com/ubuntu jammy InRelease                                                                                            
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]                                   
Hit:6 http://in.archive.ubuntu.com/ubuntu jammy-updates InRelease                                                      
Get:7 http://in.archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]         
Hit:8 https://ppa.launchpadcontent.net/git-core/ppa/ubuntu jammy InRelease                       
Reading package lists... Done
E: The repository 'cdrom://Ubuntu 22.04 LTS _Jammy Jellyfish_ - Release amd64 (20220419) jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting

**Comment by riosje** [comment]
It looks like you have issues with your Linux installation.
are you able to run successfully `apt get update` ?? 

the script what is trying to do is update before install the package.
```
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
