### ISSUE TITLE
4.x not installed on wheezy

### ISSUE THREAD

**Issue by andig** [nodesource/distributions#144]
I'm following https://github.com/nodesource/distributions to install on raspbian/wheezy. 

  - Running the 4.x installer and then `apt-get install -y nodejs` I'm getting nodejs 0.6.19. 
  - Running the 0.12 installer I'm getting 0.12.7 as expected.

**Comment by hennr** [comment]
Wheezy seems unsupported see  #127

**Comment by andig** [comment]
Understood, thank you!
