### ISSUE TITLE
dpkg error while installing node 

### ISSUE THREAD

**Issue by tayyabzino19** [nodesource/distributions#1442]
Getting this error :
```
dpkg: error processing archive /var/cache/apt/archives/nodejs_16.17.0-deb-1nodesource1_amd64.deb (--unpack):
 trying to overwrite '/usr/share/systemtap/tapset/node.stp', which is also in package libnode72:amd64 12.22.9~dfsg-1ubuntu3
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_16.17.0-deb-1nodesource1_amd64.deb
```
 
 Also follow this below doc but still getting error 
 https://github.com/nodesource/distributions/issues/1157

**Comment by devephy** [comment]
which operating system are you using?  kali/ubuntu/mint/.....

**Comment by Grothesk242** [comment]
Just deinstall nodejs 12.22.9~dfsg-1ubuntu3

**Comment by riosje** [comment]
@tayyabzino19 please follow the instructions mentioned here.
as tunna-7 suggests.

https://github.com/nodesource/distributions/issues/1157#issuecomment-1166783466
