### ISSUE TITLE
when curl isn't installed the command just downloads nodejs from apt-get

### ISSUE THREAD

**Issue by TimDaub** [nodesource/distributions#1446]
can confirm and then additionally when I use the command to install n v18, I end up with v12 on Ubuntu 22

_Originally posted by @TimDaub in https://github.com/nodesource/distributions/issues/1284#issuecomment-1260794191_

I have a new ubuntu desktop system and in the installer I had run the install with a "minimal installation". Then I used the command outlined in the readme 

```
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt-get install -y nodejs
Command 'curl' not found, but can be installed with:
sudo snap install curl  # version 7.84.0, or
sudo apt  install curl  # version 7.81.0-1ubuntu1.4
See 'snap info curl' for additional versions.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
```

I hadn't seen the messages that curl isn't installed and so I was very confused when node v12 was installed and no npm. So I was googling around and everything until after reinstalling a couple of times I noticed that curl wasn't yet installed, which I had naturally expected.

Potentially it could help people if the command failed hard if curl isn't installed instead of then downloading a default source

**Comment by riosje** [comment]
Hi @TimDaub thanks to report this.
This little confusion could be avoided as simple as running the script as this:

```SH
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - \ &&
sudo apt-get install -y nodejs
```

We will fix/improve our documentation
