### ISSUE TITLE
[DISTRIBUTION] Support for distribution focal

### ISSUE THREAD

**Issue by pankajjpatil** [nodesource/distributions#1447]
**Describe the distribution information:**
 - OS: [Ubuntu 20.04.5 LTS]
 - Distribution Type: RPM/DEB
 - Version [e.g. 20.04]
 - Other info if needed

user@localhost:~$ sudo curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -

## Populating apt-get cache...

+ apt-get update
Hit:1 http://mirrors.linode.com/ubuntu focal InRelease
Hit:2 http://mirrors.linode.com/ubuntu focal-updates InRelease                                                                                             
Hit:3 http://mirrors.linode.com/ubuntu focal-backports InRelease                                                                                           
Hit:4 https://deb.nodesource.com/node_14.x focal InRelease                                                                                                
Hit:5 https://dl.yarnpkg.com/debian stable InRelease                                                                                                      
Get:6 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                  
Fetched 114 kB in 1s (94.0 kB/s)                           
Reading package lists... Done
main: /usr/bin/lsb_release: /usr/bin/python3.10: bad interpreter: No such file or directory
main: /usr/bin/lsb_release: /usr/bin/python3.10: bad interpreter: No such file or directory

## Confirming "" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists//Release'

**Comment by MartinHotmann** [comment]
Same here. One server of me runns on Debian/Sid. I get:

```
## Confirming "n/a" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_18.x/dists/n/a/Release'

## Your distribution, identified as "n/a", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

Something must have changed very recently. This did not happen some days ago.

**Comment by riosje** [comment]
Hello guys this is not an issuee anymore.
We've updated our repositories, Now are distro agnostico.

Please take a look to the installation instruction on the new README
https://github.com/nodesource/distributions#installation-instructions
