### ISSUE TITLE
Nodejs error when installing on RHEL 8 in DISA STING Profile

### ISSUE THREAD

**Issue by nandakumarcs** [nodesource/distributions#1449]
**Describe the distribution information:**
 - OS: RHEL 8
 - Distribution Type: RPM
 - Version : 8.4
 - Other info if needed : This system is enabled with the default DISA STING Profile which has FIPS enabled.

**Additional context**

dnf install nodejs
Updating Subscription Management repositories.
Dependencies resolved.

 Package                                       Architecture                      Version                                                           Repository                                                   Size

Installing:
 nodejs                                        x86_64                            2:16.17.1-1nodesource                                             nodesource                                                   32 M
Installing dependencies:
 python3-pip                                   noarch                            9.0.3-22.el8                                                      rhel-8-for-x86_64-appstream-rpms                             20 k
 python3-setuptools                            noarch                            39.2.0-6.el8                                                      rhel-8-for-x86_64-baseos-rpms                               163 k
 python36                                      x86_64                            3.6.8-38.module+el8.5.0+12207+5c5719bc                            rhel-8-for-x86_64-appstream-rpms                             19 k
Enabling module streams:
 python36                                                                        3.6

Transaction Summary

Install  4 Packages

Total download size: 32 M
Installed size: 90 M
Is this ok [y/N]: y
Downloading Packages:
(1/4): python36-3.6.8-38.module+el8.5.0+12207+5c5719bc.x86_64.rpm                                                                                                                     64 kB/s |  19 kB     00:00
(2/4): python3-setuptools-39.2.0-6.el8.noarch.rpm                                                                                                                                    427 kB/s | 163 kB     00:00
(3/4): python3-pip-9.0.3-22.el8.noarch.rpm                                                                                                                                           105 kB/s |  20 kB     00:00
(4/4): nodejs-16.17.1-1nodesource.x86_64.rpm                                                                                                                                          32 MB/s |  32 MB     00:00

Total                                                                                                                                                                                 33 MB/s |  32 MB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  package nodejs-2:16.17.1-1nodesource.x86_64 does not verify: no digest

cat /etc/yum.repos.d/nodesource-el8.repo
[nodesource]
name=Node.js Packages for Enterprise Linux 8 - $basearch
baseurl=https://rpm.nodesource.com/pub_16.x/el/8/$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL

[nodesource-source]
name=Node.js for Enterprise Linux 8 - $basearch - Source
baseurl=https://rpm.nodesource.com/pub_16.x/el/8/SRPMS
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
gpgcheck=1

 cat /etc/*-release
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
Red Hat Enterprise Linux release 8.6 (Ootpa)
Red Hat Enterprise Linux release 8.6 (Ootpa)

**Comment by nandakumarcs** [comment]
@riosje Thoughts?

**Comment by nandakumarcs** [comment]
@riosje 

Upon further investigation, i figured out SHA256 digest is missing from the rpm build setup.

 rpm --checksig --verbose nodejs-16.17.1-1nodesource.x86_64.rpm
nodejs-16.17.1-1nodesource.x86_64.rpm:
    Header V4 RSA/SHA512 Signature, key ID 34fa74dd: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: NOTFOUND
    V4 RSA/SHA512 Signature, key ID 34fa74dd: OK
    MD5 digest: NOTFOUND

**Comment by nandakumarcs** [comment]
More information found here: https://www.starlab.io/blog/adding-sha256-digests-to-rpms

**Comment by nandakumarcs** [comment]
@riosje, any updates on the reported issue?

**Comment by riosje** [comment]
Sorry guys we we're a little bit busy working on the new LTS release.
I gona check this soon.

**Comment by nandakumarcs** [comment]
looking for an update in this matter

**Comment by vladislavkalina** [comment]
A year passed and the rpms from https://rpm.nodesource.com  are still signed with SHA1 only while Red Hat has been insisting on SHA256 for quite a long time. Sure I can change the system crypto policy to "legacy" but my employer is not happy about that. May I ask if there is any plan for signing nodejs packages with SHA256?

**Comment by smaceno** [comment]
I'm in a similar boat, slightly newer OS.  We're using Rocky Linux 9 in FIPS mode, which doesn't allow the SHA1 signature method any longer as well.  FIPS mode is required for us, and I'm unable to move forward with an environment setup until/unless these packages are signed with SHA256.

**Comment by jcox10** [comment]
Another issue here with the same problem https://github.com/nodesource/distributions/issues/1653

**Comment by riosje** [comment]
Guys we've fixed this for Node18 to Node21
It took some time but is ok now.
