### ISSUE TITLE
"Illegal instruction" output on any command

### ISSUE THREAD

**Issue by DrCord** [nodesource/distributions#145]
I have installed node 4.12 via the very simple and easy instructions for Debian (I am using Raspbian Jessie) on the site, thanks for making that so easy, it used to be a real PITA! I am using a Raspberry Pi B+.

I get an "Illegal instruction" error on any command to node, including --version.

I think it is related to these older version problems with the arm processor reporting the wrong version to v8 but I don't know where to make the needed changes to fix the problem:

http://raspberrypi.stackexchange.com/a/30068/9703

also this issue is at https://github.com/nodejs/node-v0.x-archive/issues/7222

**Comment by rvagg** [comment]
@DrCord unfortunately we only supply "armhf" style binaries to work with that arch distribution from Debian and this means that only ARMv7 (and above) will work with the binaries provided. Raspberry Pi B+ is still an ARMv6 processor, it's only in the Raspberry Pi 2 that they jumped to ARMv7 so the binaries we provide here aren't going to work (and why Raspbian exists and they can't just reuse armhf Debian).

The good news is that you can actually download AMRv6 binaries straight from nodejs.org now for each new release. For 4.1.2 go to https://nodejs.org/download/release/v4.1.2/ and you'll see linux-armv6 binaries that you can unpack. Use something like this to do it from the commandline: `curl -sL https://nodejs.org/download/release/v4.1.2/node-v4.1.2-linux-armv6l.tar.xz | tar -Jxv -C /usr/local/`
