### ISSUE TITLE
[ERROR] curl: (23) Failure writing output to destination Ubuntu 22.04

### ISSUE THREAD

**Issue by patsevanton** [nodesource/distributions#1450]
**Describe your bug**
curl: (23) Failure writing output to destination

**Distribution Information:**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 22.04]

**Node Version:**
 - Node: [e.g. Node.js v16.x:]

**To Reproduce**
```
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - \ &&
sudo apt-get install -y nodejs
bash:  : No such file or directory
curl: (23) Failure writing output to destination
```

**Expected behavior**
add repo and install nodejs

**Screenshots**
![image](https://user-images.githubusercontent.com/10828883/194319334-f961de20-1106-4bad-873a-40d26d5548de.png)

**Comment by Chandram-Dutta** [comment]
Same error on Pop OS 22.04

**Comment by codeforkjeff** [comment]
I also experienced this on Ubuntu 22.04.

Removing the backslash made it work for me:

```sh
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - &&
sudo apt-get install -y nodejs
```

**Comment by Icey67** [comment]
Same error on Pop OS 22.04
Removing the backslash didn't work for me:
`curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&
sudo apt-get install -y nodejs`
it threw me a different error though:
`Error executing command, exiting`
Am I missing a dependency?

**Comment by g0sk** [comment]
Just got it working on Pop OS 22.04 with the instructions before commit #1448.

`curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - sudo apt-get install -y nodejs`

Just change the setup_version with yours.

**Comment by shushiro** [comment]
(this might help) I am experiencing the same issue yet with another error output:

```
Unpacking nodejs (16.18.1-deb-1nodesource1) over (12.22.9~dfsg-1ubuntu3) ...
dpkg: error processing archive /var/cache/apt/archives/nodejs_16.18.1-deb-1nodesource1_amd64.deb (--unpack):
 trying to overwrite '/usr/include/node/common.gypi', which is also in package libnode-dev 12.22.9~dfsg-1ubuntu3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_16.18.1-deb-1nodesource1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by riosje** [comment]
The original issue was because the line continuation `\` is causing troubles in some distros/shells.
We will replace the doc to use 1 linea command instead of line continuation.

**Comment by hassamulhaq** [comment]
@patsevanton 

In the screenshot, I noticed you were logged-in as `user@acer` that's why you got error like `curl: (23) Failure writing output to destination`

**How to Fix**:
run command `sudo su` to login as root
this will change the current user to root user and terminals will look like `root@vps-1a7c9c` or `root@acser`.

After changing user to `root@` user, your command will work without any curl error. I faced the same error and by changing user to `root@your-server-ip` by running command `sudo su` my curl errors were gone.


Some says: just add `sudo` before the command, but it is not worked. Simply change the user to root user and hit your commands.
Even no need to uninstall curl and reinstall curl. Simple is change the user to root user by `sudo su`

**Comment by vitalije** [comment]
I had the same problem with `curl` being unable to write to a folder. The problem was that my `curl` from snap. The solution was to remove snap curl and install curl using apt.
```bash
sudo snap remove curl
sudo apt install curl
```
After, that the error was gone.

**Comment by elpardal** [comment]
> I had the same problem with `curl` being unable to write to a folder. The problem was that my `curl` from snap. The solution was to remove snap curl and install curl using apt.
> 
> ```shell
> sudo snap remove curl
> sudo apt install curl
> ```
> 
> After, that the error was gone.

Thanks, it solved my problem here in ubutnu 22.04

**Comment by vijaysmetgud** [comment]
sudo apt install docker.io -----------------resolved this issue

**Comment by moh0009** [comment]
in my case i use `sudo curl`
