### ISSUE TITLE
[DISTRIBUTION] Missing Node 16.18.0 DEB

### ISSUE THREAD

**Issue by cp1992** [nodesource/distributions#1457]
**Describe the distribution information:**
 - OS: Ubuntu
 - Distribution Type: DEB
 - Version: 20.04
 - Other info if needed

**Additional context**

Node 16.18.0 appears to be missing from https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/ . We manually pull down node from here in order to pin versions as part of docker images we build.

[Node 16.18.0 was released back on 10-12-2022](https://nodejs.org/en/blog/release/v16.18.0/), so not sure if it was missed or if something else has changed with how specific versions are being distributed. Any help on this matter would be greatly appreciated!

**Comment by Grothesk242** [comment]
Check your favourite package manager. 

16.18.0 should be available now.

**Comment by cp1992** [comment]
Issue is fixed, thank you!
