### ISSUE TITLE
[DISTRIBUTION] Support for distribution Ubuntu 22.10 (kinetic)

### ISSUE THREAD

**Issue by jnoordsij** [nodesource/distributions#1458]
**Describe the distribution information:**
 - OS: Ubuntu
 - Distribution Type: DEB
 - Version 22.10 (kinetic kudu)

**Additional context**
Official released planned for 20/10/2022. See also https://wiki.ubuntu.com/Releases.

**Comment by JesusPaz** [comment]
changes have already been made for Node.js 19 https://deb.nodesource.com/node_19.x/dists/kinetic/
