### ISSUE TITLE
[ERROR] Node.js 18 on Ubuntu 22.04 Installation fail: Hash Sum mismatch

### ISSUE THREAD

**Issue by candrews** [nodesource/distributions#1465]
**Describe your bug**
[APT repository metadata format is inherently racy](https://bugs.launchpad.net/ubuntu/+source/apt/+bug/972077).

Can you please enable `Acquire-by-hash` in Release/InRelease (such as in https://deb.nodesource.com/node_18.x/dists/jammy/main/binary-amd64/Release) to fix this race condition making installation/updates reliable?

Please see https://blog.packagecloud.io/fixing-apt-hash-sum-mismatch-consistent-apt-repositories/

Output when this race condition occurs:
```
Reading package lists...
E: Failed to fetch https://deb.nodesource.com/node_18.x/dists/jammy/main/binary-amd64/Packages.gz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:775 [weak]
    - SHA256:619a85164b13b613f19873ef3c3e59a25a97ab8364aab9f38706a9eee29a6af9
    - SHA1:9d4a936a194c70ab37f3d8364e8532877a18534b [weak]
    - MD5Sum:82be59485849fcec624ffc2fc2f11045 [weak]
   Hashes of received file:
    - SHA256:5d52e1394ba3f81f36883e153f1e0d41f28d7c8faae2609ea9f69ae243d82e2d
    - SHA1:5cb5aa1790e272d3b7c4a8ccd6d3ab48b85cd201 [weak]
    - MD5Sum:e918fa42247376d977aa70797eb24848 [weak]
    - Filesize:775 [weak]
   Last modification reported: Tue, 25 Oct 2022 23:03:29 +0000
   Release file created at: Fri, 14 Oct 2022 19:29:19 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Distribution Information:**
 - OS: Ubuntu
 - Version: 22.04
- Using docker image

**Node Version:**
 - Node: Node.js v18

**To Reproduce**
1. `docker run -it ubuntu:22.04`
2. `apt-get update && apt-get install -y curl sudo`
3. `curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && sudo apt-get install -y nodejs`

**Expected behavior**
Installation completes successfully.

**Screenshots**
n/a

**Additional context**
Add any other context about the problem here, specify if already has another NodeJS version or if trying to re-install the current version.

**Comment by JesusPaz** [comment]
This may be an error related to our CDN cache, I just ran the same commands and could not reproduce the issue. Notify us if you still have this problem.

**Comment by candrews** [comment]
@JesusPaz can you please take a look at the issue description and the links provided?

This is a race condition. It's inherently not consistently reproducible, but just because you tried and didn't reproduce immediately does not mean that the issue doesn't exist.

The fix (which Debian, Ubuntu, and packagecloud.io amongst other apt package repositories have implemented) is to enable `Acquire-by-hash`. Can you please do that for this repository?
