### ISSUE TITLE
Update LTS script

### ISSUE THREAD

**Issue by believer** [nodesource/distributions#1468]
The LTS script was updated to support the latest LTS in #1464, but the link in the README still lists the version as Node 16. Is it waiting to be deployed?

**Expected result**
https://deb.nodesource.com/setup_lts.x is version 18

**Actual result**
https://deb.nodesource.com/setup_lts.x is version 16

**Comment by cfouche3005** [comment]
Same problem for the rpm version 
**Expected result**
 https://rpm.nodesource.com/setup_lts.x is version 18

**Actual result**
 https://rpm.nodesource.com/setup_lts.x is version 16

**Comment by JesusPaz** [comment]
The changes have already been applied on the server, it is necessary to wait for our CDN to replicate the changes.

**Comment by zhanghaotongxue** [comment]
> The changes have already been applied on the server, it is necessary to wait for our CDN to replicate the changes.

Thank you, 

> The changes have already been applied on the server, it is necessary to wait for our CDN to replicate the changes.

@JesusPaz  How long will it take long?  It hasn't been in effect since yesterday.

**Comment by zhanghaotongxue** [comment]
> The changes have already been applied on the server, it is necessary to wait for our CDN to replicate the changes.

It is okay, thank you.
