### ISSUE TITLE
[DISTRIBUTION] Support for distribution Debian-derived Linux (HaykOS)

### ISSUE THREAD

**Issue by HaykMarkosyan** [nodesource/distributions#1469]
Support NodeJS for HaykOS

 - OS: HaykOS
 - Distribution Type: DEB
 - Version: 1

HaykOS is an operating system developed by myself and does not support nodejs (node) above version 12.
The OS is currently not ready to be published and I plan to release it soon, however I want nodeJS to be supported before publishing as I am a NodeJS developer and I love NodeJS 😆

**Comment by riosje** [comment]
Since this new OS has not been published and it has not an Stable release we cannot support it yet.

but it is not a problem, you can always install NodeJS Manually
https://github.com/nodesource/distributions#debmanual
