### ISSUE TITLE
Security release

### ISSUE THREAD

**Issue by yavorski** [nodesource/distributions#1472]
Hi can we get the new security releases, and specifically `18.12.1` LTS ?
More information is available here [New security releases now available for Node.js 14, 16, 18, 19 release lines](https://nodejs.org/en/blog/vulnerability/november-2022-security-releases/).
Thank you!

**Comment by nicholi** [comment]
I see they made the necessary build patches for their paying customers on Friday.
https://twitter.com/NodeSource/status/1588724294640885760

**Comment by nicholi** [comment]
Looks to have possibly just gone live at least for Ubuntu 22.04

https://deb.nodesource.com/node_18.x/dists/jammy/main/binary-amd64/Packages

**Comment by yavorski** [comment]
Yes, looks like ubuntu & fedora are updated now

**Comment by riosje** [comment]
Hi guys @yavorski @nicholi the sec release was published on friday, there was missing Node18 becase some technical issues and it was published yesterday successfully.
https://deb.nodesource.com/node_18.x/pool/main/n/nodejs/
https://rpm.nodesource.com/pub_18.x/el/9/x86_64/
