### ISSUE TITLE
[ERROR] Nodejs 19 on Fedora36 Installation does not create repo entry into /etc/yum.repos.d/

### ISSUE THREAD

**Issue by luciatrans** [nodesource/distributions#1475]
**Describe your bug**
/etc/yum.repos.d/nodesource*.repo was missing

**Distribution Information:**
 - OS: Fedora Linux
 - Version 36

**Node Version:**
 - Node: Nodejs v9.x (check for any other ver)

**To Reproduce**
as root
1. curl -fsSL https://rpm.nodesource.com/setup_19.x | bash -
2. ls -lA /etc/yum.repos.d/ <--- nodesource*.repo entry missing
3. dnf install nodejs <-- shows only updates-modular repository nodejs package
**Expected behavior**
/etc/yum.repos.d/nodesource*.repo entry exists.
dnf install nodejs displaying this
 Package                                              Architecture                                         Version                                                             Repository                                                Size
==============================================================================================================================================================================================================================================
Installing:
 nodejs                                               x86_64                                               2:19.1.0-1nodesource                                                nodesource                                                34 M

Riepilogo della transazione
==============================================================================================================================================================================================================================================

**Screenshots**

**Additional context**
I have had to manually add this text file as /etc/yum.repos.d entry:  nodesource-release-fc36-1.repo
content:

[nodesource]
name=rpm.nodesource.com
baseurl=https://rpm.nodesource.com/pub_19.x/fc/36/x86_64/
enabled=1
gpgcheck=0
repo_gpgcheck=0
metadata_expire=1h

With this entry in yum.repos.d folder the installation had successfully finished

**Comment by riosje** [comment]
Hi @luciatrans I was not able to reproduce your error. make sure you have curl installed and the environment updated, also run the commands with sudo or as root.

Tried to reproduce this way and everything works.
```SHELL
docker run -it --rm fedora:36 bash
curl -fsSL https://rpm.nodesource.com/setup_19.x | bash -
dnf install -y nodejs
```
![image](https://user-images.githubusercontent.com/55195249/207404922-c367fbc1-02be-41f3-8ae2-659f325b7d94.png)
