### ISSUE TITLE
Problem instaling nodejs E: Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by shameemwarsi707** [nodesource/distributions#1478]
$ sudo apt-get install -y nodejs
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 0 B/25.7 MB of archives.
After this operation, 125 MB of additional disk space will be used.
(Reading database ... 202595 files and directories currently installed.)
Preparing to unpack .../nodejs_14.21.1-deb-1nodesource1_amd64.deb ...
Unpacking nodejs (14.21.1-deb-1nodesource1) ...
dpkg: error processing archive /var/cache/apt/archives/nodejs_14.21.1-deb-1nodesource1_amd64.deb (--unpack):
 trying to overwrite '/usr/share/systemtap/tapset/node.stp', which is also in package libnode72:amd64 12.22.9~dfsg-1ubuntu3
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_14.21.1-deb-1nodesource1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ThatGuyCalledJesse** [comment]
I have this error too

**Comment by riosje** [comment]
@shameemwarsi707 do you already have another NodeJS version installed?

**Comment by ivar** [comment]
@riosje  - I have this error except for version 18.12.1 
```
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 21 not upgraded.
Need to get 0 B/28.5 MB of archives.
After this operation, 180 MB of additional disk space will be used.
(Reading database ... 467683 files and directories currently installed.)
Preparing to unpack .../nodejs_18.12.1-deb-1nodesource1_amd64.deb ...
Unpacking nodejs (18.12.1-deb-1nodesource1) ...
dpkg: error processing archive /var/cache/apt/archives/nodejs_18.12.1-deb-1nodesource1_amd64.deb (--unpack):
 trying to overwrite '/usr/include/node/common.gypi', which is also in package libnode-dev 12.22.9~dfsg-1ubuntu3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_18.12.1-deb-1nodesource1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Let me know if this helps or if there's anything else I can provide.

**Comment by riosje** [comment]
@ivar can you provide the step by step you're following to try to replicate the same behavior, also I need to know the version of your SO

**Comment by muaiyadh** [comment]
Just in case this helps someone, turns out I used `sudo apt install npm` instead of following the instructions here. Purging it and nodejs then reinstalling using the proper instructions from this repo fixed the issue. (using Pop os 22.04)

**Comment by riosje** [comment]
It looks like this error is not happening anymore.
