### ISSUE TITLE
Your distribution, identified as "redhat-release-server-6Server-6.10.0.13.el6_10.9.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

### ISSUE THREAD

**Issue by vilalali** [nodesource/distributions#1479]
# curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release || rpm -q --whatprovides fedora-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_18.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "redhat-release-server-6Server-6.10.0.13.el6_10.9.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

[root@localhost electron]# curl -fsSL https://rpm.nodesource.com/setup_14.x | bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release || rpm -q --whatprovides fedora-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_14.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

**Comment by riosje** [comment]
Hi @vilalali NodeJS 18 (Hydrogen) is not supported on RHEL6 and 7 and this is because Node18 requires `glibc >= 2.28` you will need at least RHEL8, take a look to the [NodeJS docs](https://github.com/nodejs/node/blob/main/BUILDING.md)

if you think you can install the required version of `glibc` on your distribution you can download and install the package manually
