### ISSUE TITLE
Can't install in 15.04 Docker Ubuntu container

### ISSUE THREAD

**Issue by atrauzzi** [nodesource/distributions#148]
```
## Installing packages required for setup: apt-transport-https lsb-release...

+ apt-get install -y apt-transport-https lsb-release > /dev/null 2>&1

## Confirming "vivid" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_0.12/dists/vivid/Release'
curl: symbol lookup error: /usr/lib/x86_64-linux-gnu/libasn1.so.8: undefined symbol: _et_list

## Your distribution, identified as "vivid", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by retrohacker** [comment]
Vivid is supported by the 0.12 install script, which simply checks for the existance of this folder: https://deb.nodesource.com/node_0.12/dists/vivid/

The following line is concerning

```
curl: symbol lookup error: /usr/lib/x86_64-linux-gnu/libasn1.so.8: undefined symbol: _et_list
```

This seems to be a problem with curl and not with the setup scripts.

We maintain official Docker Images for Ubuntu Vivid that you may want to use as a base for your image: https://hub.docker.com/r/nodesource/vivid/

It will save you the trouble of getting Node.js setup and installed in your Docker Image.

Hope this helps!
