### ISSUE TITLE
[DISTRIBUTION] Support for distribution XX

### ISSUE THREAD

**Issue by useantay** [nodesource/distributions#1488]
**Describe the distribution information:**
 - OS: [Linux Mint 21.1]
 - Distribution Type: DEB
 - Version [e.g. 18.*, 19.*]
 - Other info if needed

**Additional context**
![Screenshot from 2022-12-23 16-00-35 (1)](https://user-images.githubusercontent.com/108556759/209405864-219b1b51-aa63-429a-83c9-8551a4b9cc83.png)

**Comment by mayurdhwaj** [comment]
Waiting for it :((

**Comment by skander-sc1908360** [comment]
is there a workaround? maybe installing a version meant for the previous mint release?

**Comment by MrTuNNe** [comment]
For me what I did was to replace "vera" with "jammy" in nodesource.list
Follow the instructions from the Manual installation (https://github.com/nodesource/distributions#debmanual)
`echo "deb [signed-by=$KEYRING] https://deb.nodesource.com/$VERSION jammy main" | sudo tee /etc/apt/sources.list.d/nodesource.list
echo "deb-src [signed-by=$KEYRING] https://deb.nodesource.com/$VERSION jammy main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list`

**Comment by riosje** [comment]
Already merge this PR with the changes to support this dist.
https://github.com/nodesource/distributions/pull/1487

**Comment by Matheus-Felipe-C** [comment]
Hello there @riosje! I just tried to install it through the comments in the distributions/README.md, but it still says that my distribution is not supported yet. I have the same version as @useantay

**Comment by gabriel-russo** [comment]
@Matheus-Felipe-C I think it's not on distribution server yet. Let's wait some time and check again later in `https://deb.nodesource.com/setup_lts.x` script
