### ISSUE TITLE
[DISTRIBUTION] Support for distribution Linux Mint 21.2 "Vera"

### ISSUE THREAD

**Issue by rich1n** [nodesource/distributions#1489]
**Describe the distribution information:**
 - OS: Linux Mint 21.1 "Vera"
 - Distribution Type: DEB
 - Version Linux Mint 21.1 "Vera" (via Ubuntu 22.04 LTS)

**Additional context**
## Your distribution, identified as "vera", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by vxrnxk** [comment]
I have the same problem "Your distribution, identified as "vera", is not currently supported...",
I tried to install Node version 18(LTS) and version 19 but without success.

I'm using Linux Mint 21.1

**Comment by prices** [comment]
I downloaded the script setup_16.x and modified it to add Mint Linux "vera".  Since it is based on Ubuntu "Jammy" this should work.

It has installed fine and seems to run fine.

**Comment by michaelschalckse** [comment]
> I have the same problem "Your distribution, identified as "vera", is not currently supported...", I tried to install Node version 18(LTS) and version 19 but without success.
> 
> I'm using Linux Mint 21.1

Same issue for me..

**Comment by BrunoSSantana** [comment]
> **Describe the distribution information:**
> 
>     * OS: Linux Mint 21.1 "Vera"
> 
>     * Distribution Type: DEB
> 
>     * Version Linux Mint 21.1 "Vera" (via Ubuntu 22.04 LTS)
> 
> 
> **Additional context**
> ## Your distribution, identified as "vera", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Me too

**Comment by DonBolli** [comment]
> Describe the distribution information:

OS: Linux Mint 21.1 "Vera"
Distribution Type: DEB
Version Linux Mint 21.1 "Vera" (via Ubuntu 22.04 LTS)

Same here

**Comment by gavinr** [comment]
Title of issue should be changed to `Linux Mint 21.21"Vera"`

It looks like support was added here: https://github.com/nodesource/distributions/pull/1487

**Comment by JazzyArmando1234** [comment]
I have same issue...

**Comment by BrunoSSantana** [comment]
hello everyone, I managed to solve the problem here, I don't know if it was the best way to proceed, but for now, it solved it.

1. I followed what the friend suggested in this [post](https://unix.stackexchange.com/questions/729614/cannot-install-nodejs-on-linux-mint-vera), where he talks about downloading the script and right in the script rename the verification there from "vanessa" to "vera", since they are all based on "Ubuntu Jammy", so 'theoretically would not have problems

2. Even so, I received an error in the terminal informed there that it would not be possible to install, then, in the file `/etc/apt/sources.list.d/nodesource.list` I commented what existed and changed yesterday there was "vera" to " jammy" getting the file like this:
```
# deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_19.x vera main
# deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_19.x vera main

deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_19.x jammy main
deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_19.x jammy main
```

**Comment by gavinr** [comment]
I got Node v19 installed by following the [suggestion in that thread](https://unix.stackexchange.com/a/729864/211979):

```
curl -sL https://deb.nodesource.com/setup_19.x | sed -e 's/vanessa/vera/' | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by riosje** [comment]
Hi guys, we've purged our CDN cache, it should be ok now.

**Comment by aaditya-cpu** [comment]
curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash - &&\
sudo apt-get install -y nodejs

## Installing the NodeSource Node.js 19.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://mirrors.piconets.webwerks.in/ubuntu-mirror/ubuntu jammy InRelease
Hit:2 https://deb.nodesource.com/node_19.x jammy InRelease
Hit:3 http://mirrors.piconets.webwerks.in/ubuntu-mirror/ubuntu jammy-updates InRelease
Hit:4 http://mirrors.piconets.webwerks.in/ubuntu-mirror/ubuntu jammy-backports InRelease
Ign:5 https://mirrors.piconets.webwerks.in/linuxmint-mirror/packages vera InRelease
Hit:6 https://mirrors.piconets.webwerks.in/linuxmint-mirror/packages vera Release
Hit:8 http://security.ubuntu.com/ubuntu jammy-security InRelease               
Reading package lists... Done

## Confirming "vera" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_19.x/dists/vera/Release'

## Your distribution, identified as "vera", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by eclecticdave** [comment]
> I got Node v19 installed by following the [suggestion in that thread](https://unix.stackexchange.com/a/729864/211979):
> 
> ```
> curl -sL https://deb.nodesource.com/setup_19.x | sed -e 's/vanessa/vera/' | sudo -E bash -
> sudo apt-get install -y nodejs
> ```

I found that for Linux Mint 'victoria' and Node 20.x, reversing the 'sed' parameters works (it modifies one of the 'check_alt' lines in the script):

`curl -fsSL https://deb.nodesource.com/setup_20.x | sed -e 's/vera/victoria/' | sudo -E bash -`
`sudo apt-get install -y nodejs`
