### ISSUE TITLE
There is no PPA package for Node.js for Ubuntu 15.04 vivid.

### ISSUE THREAD

**Issue by AiOO** [nodesource/distributions#149]
So I've being faced following error:

```
$ curl -sL https://deb.nodesource.com/setup_0.12 | sudo -E bash -

## Installing the NodeSource Node.js 0.12 repo...


## Populating apt-get cache...

+ apt-get update
... ellipsis ...
Err http://ppa.launchpad.net vivid/main amd64 Packages
  404  Not Found
... ellipsis ...
Fetched 2,252 B in 4s (554 B/s)               
W: Failed to fetch http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/vivid/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting
```

FYI: There is actually no any files or directories for vivid on [this path](http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/).

**Comment by rvagg** [comment]
> `W: Failed to fetch http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/vivid/main/binary-amd64/Packages  404  Not Found`

It looks like you have the launchpad PPA installed in a way that it can't be removed by the script (which runs `add-apt-repository -y -r ppa:chris-lea/node.js`). Can you look in /etc/apt/sources.list and /etc/apt/sources.list and remove anything with `ppa.launchpad.net/chris-lea/node.js` in it, then run `apt-get update && apt-get install nodejs` again.

**Comment by siddhant389** [comment]
facing the same issue can anyone please update with a solution to this??

**Comment by chrislea** [comment]
You'll also need to look in

```
/etc/apt/sources.list.d
```

and make sure there are no `chris-lea-*` files in there. Our installer script should remove them, but if something's going wrong those need to be removed.

**Comment by front-end1981** [comment]
Same issue for me. I`m trying to install 5.x version using this:

curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install -y nodejs

and this:
add-apt-repository -y -r ppa:chris-lea/node.js
rm -f /etc/apt/sources.list.d/chris-lea-*node_js-*.list

2. Add the NodeSource signing key
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -

3. Add the repositories to your sources.list
echo 'deb https://deb.nodesource.com/setup_5.x vivid main' > /etc/apt/sources.list.d/nodesource.list
echo 'deb-src https://deb.nodesource.com/setup_5.x vivid main' >> /etc/apt/sources.list.d/nodesource.list

instructions.

Err https://deb.nodesource.com vivid/main Sources
  HttpError404
Get:27 https://deb.nodesource.com vivid/main amd64 Packages [162 B]
Err https://deb.nodesource.com vivid/main amd64 Packages
  HttpError404
Get:28 https://deb.nodesource.com vivid/main i386 Packages [162 B]
Err https://deb.nodesource.com vivid/main i386 Packages
  HttpError404
Get:29 https://deb.nodesource.com vivid/main Translation-en_US [162 B]
Ign https://deb.nodesource.com vivid/main Translation-en_US
Get:30 https://deb.nodesource.com vivid/main Translation-en [162 B]
Ign https://deb.nodesource.com vivid/main Translation-en
W: Failed to fetch https://deb.nodesource.com/setup_5.x/dists/vivid/main/source/Sources  HttpError404        
W: Failed to fetch https://deb.nodesource.com/setup_5.x/dists/vivid/main/binary-amd64/Packages  HttpError404
W: Failed to fetch https://deb.nodesource.com/setup_5.x/dists/vivid/main/binary-i386/Packages  HttpError404
E: Some index files failed to download. They have been ignored, or old ones used instead.

so it`s seems to me that there is no repository

**Comment by chrislea** [comment]
You're seeing this because you used `setup_5.x` in the path and not `node_5.x`. Specifically, you did this:

```
echo 'deb https://deb.nodesource.com/setup_5.x vivid main' > /etc/apt/sources.list.d/nodesource.list
echo 'deb-src https://deb.nodesource.com/setup_5.x vivid main' >> /etc/apt/sources.list.d/nodesource.list
```

and those lines should have been:

```
echo 'deb https://deb.nodesource.com/node_5.x vivid main' > /etc/apt/sources.list.d/nodesource.list
echo 'deb-src https://deb.nodesource.com/node_5.x vivid main' >> /etc/apt/sources.list.d/nodesource.list
```

If you fix that it should work.
