### ISSUE TITLE
[Request] Make debian/rpm buildscripts open source

### ISSUE THREAD

**Issue by theofficialgman** [nodesource/distributions#1491]
Since this issue remains unfixed and is a hot toppic of discussion (https://github.com/nodejs/node/issues/43246) there needs to be transparency and open instructions for the creation of debian and rpm packages as distributed through this repo.

repository setup is not needed but the scripts utilized to check for nodejs updates as well as create the deb/rpm packages should be made open source so that other packagers who wish to create alternative repositories for this distributions repository which matches the packaging here exactly can be made.

**Comment by theofficialgman** [comment]
cc: @igsu since you are the listed maintainer for the debian packages. the nodesource repos do not have source files for the debs so they can not be reproduced

**Comment by riosje** [comment]
CC @edsadr

**Comment by riosje** [comment]
@theofficialgman
I understand this requirement is because of the need to have Node18 bin and installers for ubuntu 18 and/or amazon linux 2.
we're going to make some tests building Node18 with glibc 2.26, with this we can bring support to ubuntu and amazon linux 2.
let you know any news on this.

**Comment by theofficialgman** [comment]
> @theofficialgman I understand this requirement is because of the need to have Node18 bin and installers for ubuntu 18 and/or amazon linux 2. we're going to make some tests building Node18 with glibc 2.26, with this we can bring support to ubuntu and amazon linux 2. let you know any news on this.

this is a reason for my personal desire for having the scripts open source, yes, but its not the only reason for doing so. right now the debs/rpms are unreproduceable by 3rd parties (like myself). like I have already shown here https://github.com/nodesource/distributions/issues/1492 the buildscripts need modification to prevent installation on unsupported configurations (incorrect control file and to this day still being posted in the bionic apt repo). I would fix it myself but since they are closed source I cannot do so.

**Comment by eugene1g** [comment]
@theofficialgman We still need NodeSource buildscripts to be open sourced, but FWIW I checked ~20 RPM packages of Node 18 for for EL7-EL9, FC34-FC37, and in every case the `bin/node` binary was exactly the same as downloadable directly from Node.js. In other words, you can `wget` official tarballs and get the same executable.

**Comment by theofficialgman** [comment]
I don't care that the executables are the same.
having the tarfiles is not the same as a generated deb or rpm.
how is the debian `control` file made? how are the tarfiles converted into formatting for debs and rpms? what about changelogs, how are those generated and placed?

I could go on, all of these things are being done by the buildscripts that are closed source which prevent the creation of compatible debs/rpms. In order to properly create these packages so as to not conflict and properly setup we need the buildscripts.

**Comment by theofficialgman** [comment]
on top of that. since the buildscripts are fundamentally broken and nobody here seems to care to fix them (coming up on a 1 year anniversary of broken scripts, YAY) they definitly need to be made open source. I would gladly submit a PR to fix: https://github.com/nodesource/distributions/issues/1492 https://github.com/nodesource/distributions/pull/1400 but I can't do that if the buildscripts are closed source

**Comment by eugene1g** [comment]
@theofficialgman I agree. I evaluated what was the value-add from using NodeSource distributions, and found out that it was negligible versus how many pain points we're experiencing. So we moved our infra to use "plain" tarballs from Node, as that path gives us most flexibility about what/when we deploy, while (and this was the surprising part) keeping the same level of assurance that the release would work for our OS. 

I'm not saying you should use tarballs too. I'm saying I was surprised to discover that the binaries were exactly the same, and that was all I needed to retire NodeSource from our pipeline.

**Comment by cobalt2727** [comment]
> @theofficialgman We still need NodeSource buildscripts to be open sourced, but FWIW I checked ~20 RPM packages of Node 18 for for EL7-EL9, FC34-FC37, and in every case the `bin/node` binary was exactly the same as downloadable directly from Node.js. In other words, you can `wget` official tarballs and get the same executable.

**This is exactly the problem**, though. Having the executable be the same everywhere breaks older operating systems. That's what gman wants fixed here by open-sourcing the build scripts.

**Comment by theofficialgman** [comment]
> while (and this was the surprising part) keeping the same level of assurance that the release would work for our OS.

no, that is just blatently wrong. that is what packaging as a proper rpm and deb solves. downloading the tarbar directly and using it provides NO level of assurance at all. debs and rpms have listed dependencies and versions associated with those dependencies that prevent installation on OSs where the binaries will not work (eg: `Depends: libc6 (>= 2.17), libgcc1 (>= 1:4.2), libstdc++6 (>= 5.2), python3-minimal, ca-certificates
`) . again, that is broken currently and has been for over a year https://github.com/nodesource/distributions/issues/1492 but if it was implemented properly (like if the buildscripts were open source and fixed) then you could simply tell from the package what EXACT systems the binaries would work on.

**Comment by eugene1g** [comment]
> no, that is just blatently wrong. that is what packaging as a proper rpm and deb solves. downloading the tarbar directly and using it provides NO level of assurance at all

I think the key difference here is that you are describing what you want to be happening, and I'm describing what is actually happening. Currently, NodeSource "packages" are just thin wrappers around binaries distributed directly by Node.js. They are _not_ rebuilt for each platform and are _not_ harmonized with other dependencies typical on that distro (e.g, EL7). You are saying "they should be", I am saying "yes, but they are not". I am not saying "they shouldn't be". My statement "....keeping the same level of assurance that the release would work for our OS" is correct: today, NodeSource packages offer _zero_ additional assurance that the binary will work on your OS versus getting the same binary from Node.

**Comment by theofficialgman** [comment]
> I think the key difference here is that you are describing what you want to be happening, and I'm describing what is actually happening. Currently, NodeSource "packages" are just thin wrappers around binaries distributed directly by Node.js. They are _not_ rebuilt for each platform and are _not_ harmonized with other dependencies typical on that distro (e.g, EL7). You are saying "they should be", I am saying "yes, but they are not". I am not saying "they shouldn't be". My statement "....keeping the same level of assurance that the release would work for our OS" is correct: today, NodeSource packages offer _zero_ additional assurance that the binary will work on your OS versus getting the same binary from Node.

again, no. they packages DO provide additional assurance that the binary will work on your OS. that is what the debian control file is for `Depends: libc6 (>= 2.17), libgcc1 (>= 1:4.2), libstdc++6 (>= 5.2), python3-minimal, ca-certificates`. you clearly don't understand what this means. the `Depends:` information from the `control` file inside the `.deb` tells dpkg to not allow the package to install if the system's available libc6 package is less than version 2.17, less than libgcc1 1:4.2, etc. 

please read up on how package management works before continuing to deny basic facts.

**Comment by cobalt2727** [comment]
> They are not rebuilt for each platform and are not harmonized with other dependencies typical on that distro (e.g, EL7). You are saying "they should be", I am saying "yes, but they are not".

We're not saying "they should be," we're saying **the packages themselves incorrectly claim this by the very nature of them being installable from the repo** (for reasons gman just did a better job explaining above than I ever could) and it's misleading users. As other people have pointed out in some of the issues we linked, this is deeply unprofessional at *best*. I didn't even expect [this PR](https://github.com/nodesource/distributions/pull/1400) to get merged because of how ridiculous the situation is!

**Comment by eugene1g** [comment]
We are talking about two distinct problems -

1. You are concerned with the trustworthiness of _control data_ in the published deb/rpm package. "The package claims it depends on `xxxx-v1`, but it actually needs `xxx-v2`". You are asking that the process to build the metadata is open-sourced, presumably so you can update the `Depends` list.

2. I am concerned with the trustworthiness of the _binary_ included in that package. If the the dependency metadata is correct, but the binary itself is a zip bomb, that will not do. I discovered that the binaries published by NodeSource are _not_ built for the target systems, but are the same generic binaries as in Node.js tarballs. I would expect that a NodeSource package for e.g., `EL7` would be created by building and validating the binary on ~EL7. This is not the case - all binaries are the same, and generic.
 
What was surprising to me is that even if we completely ignore wrong control files in these NodeSource packages, the _binaries_ they distribute have no extra assurance that they work will work the OS (because they are just generics from Node tarballs). I don't care if the package metadata is correct nearly as much as I care if the binary is designed for my OS. This does not mean that having wrong control files is OK, but the real solution is to actually build a Node binary specifically for OS you are targeting, and that's not happening.

**Comment by riosje** [comment]
Hi guys.
I want to ask you guys to keep calm and try to not make disrespectful comments to each other or against nodesource itself, I notice some comments may are getting out of tone here.

**I'm going to try to fix this mess with the control files before the next security release (02/14/23).**
We're can't opensource the build scripts for now since those scripts are highly coupled to some internal(repos) process. We may do that later.

**Comment by riosje** [comment]
Hi every body we've fixed the control file some weeks ago.
I think is working as expected not it show glibc.1.28 as dependency.

**Comment by theofficialgman** [comment]
@riosje I would appreciate this staying open as the original issue topic has not been fixed

**Comment by riosje** [comment]
Hi @theofficialgman, I'm so sorry we can't open source those scripts at this moment becase those are highly coupled to our internal tools and other process.
If there is anything else we can fix, just let me know I would be happy to help with that.
Just in case you want to build your own packages I can give some hints about where you can start.

**Comment by theofficialgman** [comment]
I am once again asking that you please post the scripts
I am not asking for fully functional versions. I do not care if they work or require specific setup. Just post a tarfile of them (with any keys or secrets redacted). Right now the way that the control file, rules, changelog, etc are generated are a complete mistery and since nodejs does not intend to support older LTS distros is is time that the community take control. building compatible packages with the official packages is desirable for any tooling that expects the format, version scheme, etc to be the same.
