### ISSUE TITLE
[ERROR] Your distribution, identified as "vera", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

### ISSUE THREAD

**Issue by Arpon-svg** [nodesource/distributions#1493]
**Describe your bug**

**Distribution Information:**
 - OS: [Linux Mint]
 - Version [Vera(21.1)]

**Node Version:**
 - Node: [Nodejs 18 LTS]

**Comment by riosje** [comment]
Hi @Arpon-svg we've purged our CDN cache, it should be ok now.
