### ISSUE TITLE
[ERROR] Node.js 14.21.2 packages are missing for CentOS 7

### ISSUE THREAD

**Issue by noone1337** [nodesource/distributions#1495]
**Describe your bug**
Packages for Node.js 14.21.2 are not on the repo. Latest version is still 14.21.1

**Distribution Information:**
 - OS: CentOS
 - Version 7

**Node Version:**
 - Node: 14.21.2
 - 
**To Reproduce**
1. Check https://rpm.nodesource.com/pub_14.x/el/7/x86_64/ for latest version which is 14.21.1

**Expected behavior**
Node.js 14.21.2 should be rpm should be available

**Comment by okuryu** [comment]
It seems that there is no package for RHEL 8.
https://rpm.nodesource.com/pub_14.x/el/8/x86_64/

**Comment by Grothesk242** [comment]
The build is missing for any platform it seems: 

```
apt policy nodejs
nodejs:

     14.21.1-deb-1nodesource1 500
        500 https://deb.nodesource.com/node_14.x bullseye/main armhf Packages
```

**Comment by JesusPaz** [comment]
we had a problem in our pipelines, the version is now available.
