### ISSUE TITLE
[ERROR] Node.js 18.13.0 on Ubuntu 22.04 Installation missing

### ISSUE THREAD

**Issue by foolioo** [nodesource/distributions#1497]
**Describe your bug**
[Latest LTS Version 18.13.0](https://github.com/nodejs/node/releases/tag/v18.13.0) installation [is missing](https://deb.nodesource.com/node_18.x/dists/jammy/main/binary-amd64/Packages).

**Distribution Information:**
 - OS: Ubuntu
 - Version: 22.04.1

**Node Version:**
 - Node: 18.13.0

**To Reproduce**

```shell
$ curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
$ apt-get install nodejs=18.13.0
...
E: Version '18.13.0' for 'nodejs' was not found
```

**Expected behavior**
NodeJS version 18.13.0 should be available for installation

**Comment by Grothesk242** [comment]
Seems that any recent builds are missing atm. 
```
apt policy nodejs
nodejs:
  Installed: 19.3.0-deb-1nodesource1
  Candidate: 19.3.0-deb-1nodesource1
  Version table:
 *** 19.3.0-deb-1nodesource1 500
        500 https://deb.nodesource.com/node_19.x bullseye/main arm64 Packages
        100 /var/lib/dpkg/status
     18.12.1-deb-1nodesource1 501
        500 https://deb.nodesource.com/node_18.x bullseye/main arm64 Packages
```

**Comment by JesusPaz** [comment]
we had a problem in our pipelines, the version is now available.

**Comment by 3XC1T3D** [comment]
Hi,

we still cant install 18.13.0 under Ubuntu Focal or Ubuntu Jammy. We are still getting the Error:

`E: Version '18.13.0' for 'nodejs' was not found`

Some got a hint?

Best regards
