### ISSUE TITLE
[ERROR] Node.js 19.0.4 on Ubuntu 20.04 (focal) missing

### ISSUE THREAD

**Issue by dsine-de** [nodesource/distributions#1498]
**Describe your bug**
Update from Node.js 19.0.3 to 19.0.4 is missing. Is there something I need to change on my end?
I know it could take some time until new versions are available but it's been 7 days since the release.

**Distribution Information:**
 - OS: Ubuntu
 - Version focal (20.04)

**Node Version:**
 - Node: Node.js v19.0.4

**To Reproduce**
`sudo apt-get update`
`sudo apt-get dist-upgrade`
with installed NodeSource repository https://deb.nodesource.com/node_19.x focal InRelease

or

Open https://deb.nodesource.com/node_19.x/dists/focal/main/binary-amd64/Packages in a browser

**Comment by JesusPaz** [comment]
we had a problem in our pipelines, the version is now available.
