### ISSUE TITLE
[FEATURE] evergreen stable link

### ISSUE THREAD

**Issue by mangelozzi** [nodesource/distributions#1499]
Say one has a script like this:
```
curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash - 
```
The problem is the version is hardcoded and over the years it gets stale. It would be nice if there was a fixed url for the latest stable vesion, e.g.:
```
curl -sL https://deb.nodesource.com/setup_stable.x | sudo -E bash - 
```
That would never go out of date, and script can run happily in the background.

**Comment by mangelozzi** [comment]
PS the bug label is not appropriate, but was auto added.

**Comment by JesusPaz** [comment]
Hello @mangelozzi, we have another script that you can use. Is always the latest LTS version of node.
https://deb.nodesource.com/setup_lts.x
