### ISSUE TITLE
NodeJS 4.2.0 LTS

### ISSUE THREAD

**Issue by AlexSwensen** [nodesource/distributions#150]
Node 4.2.0 was released today under LTS. Distributions need to be updated for the current LTS release.

https://nodejs.org/en/blog/release/v4.2.0/

**Comment by dikiaap** [comment]
Yeah, I'll wait to. :smiley:

**Comment by chrislea** [comment]
4.2.0 is already building guys, please be patient. Compiling takes time. :)

**Comment by AlexSwensen** [comment]
No worries, just wanted to put it up on the radar. :+1:

**Comment by chrislea** [comment]
They're in there.

https://twitter.com/chrislea/status/653741716613296128
