### ISSUE TITLE
[DISTRIBUTION] Support for distribution Ubuntu 22.04 (jammy) Node.js.x

### ISSUE THREAD

**Issue by YohanesGetinet1** [nodesource/distributions#1504]
**Describe the distribution information:**
 - OS: Ubuntu 22.04.1 LTS
 - Distribution Type: DEB
 - Version [20.04.1 LTS]
 - Distributor ID:	Ubuntu
 - Release:	22.04
 - Codename:	jammy

**Additional context**
- ## Confirming "jammy" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_12.x/dists/jammy/Release'

**Comment by LonYui** [comment]
hav same issue

**Comment by riosje** [comment]
Hi guys, currently we don't support 12 on Jammy.
only those are supported
![image](https://user-images.githubusercontent.com/55195249/216621481-32f90e83-cba7-4809-a64f-98091beab538.png)

But you can try to perform a manual installation
https://github.com/nodesource/distributions#manual-installation

I highly suggest you to move forward and use the LTS version which is NODE18
https://nodejs.dev/en/about/releases/
