### ISSUE TITLE
[ERROR] Node.js 14 on Ubuntu22.04 Installation fail: certificate has expired

### ISSUE THREAD

**Issue by Krenodeno** [nodesource/distributions#1508]
**Describe your bug**
Trying to update with `apt update` result in an error indicating the certificate has expired for `deb.nodesource.com`

**Distribution Information:**
 - OS: Ubuntu 
 - Version: Jammy 22.04

**Node Version:**
 - Node: v14.x

**To Reproduce**
1. Execute Ubuntu Docker Image 22.04
2. Execute Installation instructions for Node.js v14.x:
3. Get the following error
```
Err:7 https://deb.nodesource.com/node_14.x jammy InRelease
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 104.109.143.4 443]
```

**Expected behavior**
`apt update` should end without any error

**Additional context**
Worked about one hour ago, tried with a vagrant image (ubuntu/jammy64) to be sure, ended with the same error.

**Comment by beheh** [comment]
Duplicate of #1507.

**Comment by Krenodeno** [comment]
Close as it is duplicate.
