### ISSUE TITLE
bullseye not supported

### ISSUE THREAD

**Issue by dchandekstark** [nodesource/distributions#1509]
Error message:

```
## Your distribution, identified as "bullseye", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

This happens with both 16.x and 18.x

See https://github.com/nodesource/distributions/issues/1453

**Comment by dchandekstark** [comment]
Could be caused by #1507 ?

**Comment by PvanHengel** [comment]
I agree, obv as a quick hack we prob all did curl -k, but then we get this.. I suspect its not the correct error
