### ISSUE TITLE
debian squeeze install

### ISSUE THREAD

**Issue by lukiies** [nodesource/distributions#151]
hello,
i'm in trouble..  can't install new nodejs in debian squeeze environment with this tutorial:
https://github.com/nodesource/distributions#debinstall
(which seemed to been good idea)

but i got : 

Your distribution, identified as "squeeze", is not currently supported, please contact NodeSource at

what can I do to get this working?

**Comment by chrislea** [comment]
Debian squeeze is not in our list of [supported distributions](https://github.com/nodesource/distributions/) so `deb` packages you can install with `apt-get` are not available for it. You can try using the binary tarballs available [here](https://nodejs.org/dist/v4.2.0/).
