### ISSUE TITLE
[DISTRIBUTION] Support for distribution elementary OS 7

### ISSUE THREAD

**Issue by lecroix74** [nodesource/distributions#1513]
**Describe the distribution information:**
 - OS: [e.g. elementary OS 7 'Horus']
 - Distribution Type: DEB
 - Version 7 (based on Ubuntu 22.04.1
 - Other info if needed

**Additional context**

![Screenshot from 2023-02-06 17 50 23](https://user-images.githubusercontent.com/28774320/217033510-b6b66066-192f-47bc-a6f5-ea50df131c52.png)

**Comment by Thalhammer** [comment]
As a quick fix until the script gets updated, you can download the script to a file, open it in your editor and add the following line right after the other check_alt lines.
```
check_alt "elementaryOS"   "horus"           "Ubuntu"        "jammy"
```
Its not a support issue, its just that the script hasn't been updated to correctly detect elementaryOS horus as Ubuntu jammy, which is supported just fine.

**Comment by lecroix74** [comment]
it sounds plausible, but being not as technically savvy as you might think of me, I do not quite understand that.
if you could give step-by-step instructions I would really appreciate it.
thnx

**Comment by SoleeL** [comment]
In the repository on node.js distributions there are the download links of the files.

https://github.com/nodesource/distributions/blob/master/README.md#debinstall

Example, with version lts 14 the link would be this:

https://deb.nodesource.com/setup_14.x

Save the file as "setup_14.x" (without extension).

You open it and add the line:

`check_alt "elementaryOS" "horus" "Ubuntu" "jammy"`

You save it and from a terminal you do the following in the directory where the file is located.

1.- `$ sudo -E bash setup_14.x`
2.- `$ sudo apt install -y nodejs`

I hope it helps you.

**Comment by lecroix74** [comment]
it took a while to figure out how to install latest LTS version, but I managed. 
thnx a million

**Comment by rshpeley** [comment]
Thanks @Thalhammer and @SoleeL.

I downloaded the current script with wget, opened nano, added the horus check_alt line at the end of the block, saved it, ran the script (as SoleeL said) and installed node v19.7.0, then tested.

```bash
wget https://deb.nodesource.com/setup_current.x
nano setup_current.x
sudo -E bash setup_current.x
sudo apt install nodejs
node -v
```

**Comment by Dreamyplayer** [comment]
I tried those steps as commented by @rshpeley  but getting an error:
Error:
```bash
E: Could not get lock /var/lib/apt/lists/lock. It is held by process 1869 (packagekitd)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to lock directory /var/lib/apt/lists/
Error executing command, exiting
```
- Got error while running below command:
```bash
sudo -E bash setup_current.x
```
- If i try to install anyway it installing old node version - `12v`.

**Comment by riosje** [comment]
This distribution is now supported
