### ISSUE TITLE
[ERROR] Node.js 19.x on ParrotOS (Debian 11) Installation fail

### ISSUE THREAD

**Issue by kbaniszack** [nodesource/distributions#1514]
**Bad version installed on ParrotOS**
When execute `curl -fsSL https://deb.nodesource.com/setup_19.x | bash - &&\
apt-get install -y nodejs`
The result of `nodejs --version` is v12.22.12

**Distribution Information:**
 - OS: ParrotOS
 - Version [5.1.2]

**Node Version:**
 - Node: [Node.js v19.x:]

**To Reproduce**
1. execute `curl -fsSL https://deb.nodesource.com/setup_19.x | bash - &&\
apt-get install -y nodejs`
2. `nodejs --version` print : v12.22.12

**Expected behavior**
Version 19.x installed

**Additional context**
see above the result of the execution :

```
┌─[root@parrot]─[~]
└──╼ #curl -fsSL https://deb.nodesource.com/setup_19.x | bash - &&\
apt-get install -y nodejs

## Installing the NodeSource Node.js 19.x repo...


## Populating apt-get cache...

+ apt-get update
Atteint :1 https://deb.parrot.sh/parrot lts InRelease
Atteint :2 https://deb.parrot.sh/parrot parrot InRelease
Atteint :3 https://deb.parrot.sh/direct/parrot parrot-security InRelease
Atteint :4 https://deb.parrot.sh/parrot parrot-backports InRelease
Lecture des listes de paquets... Fait

## You seem to be using Parrot version ara.
## This maps to Debian "bullseye"... Adjusting for you...

## Confirming "bullseye" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_19.x/dists/bullseye/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg >/dev/null

## Creating apt sources list file for the NodeSource Node.js 19.x repo...

+ echo 'deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_19.x bullseye main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_19.x bullseye main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Réception de :1 https://deb.nodesource.com/node_19.x bullseye InRelease [4 586 B]
Réception de :2 https://deb.nodesource.com/node_19.x bullseye/main amd64 Packages [772 B]
Atteint :3 https://deb.parrot.sh/parrot lts InRelease 
Atteint :4 https://deb.parrot.sh/parrot parrot InRelease
Atteint :5 https://deb.parrot.sh/direct/parrot parrot-security InRelease
Atteint :6 https://deb.parrot.sh/parrot parrot-backports InRelease
5 358 o réceptionnés en 1s (5 437 o/s)
Lecture des listes de paquets... Fait

## Run `sudo apt-get install -y nodejs` to install Node.js 19.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
     echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn


Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Les paquets supplémentaires suivants seront installés : 
  libjs-highlight.js libnode72 nodejs-doc
Paquets suggérés :
  npm
Les NOUVEAUX paquets suivants seront installés :
  libjs-highlight.js libnode72 nodejs nodejs-doc
0 mis à jour, 4 nouvellement installés, 0 à enlever et 1 non mis à jour.
Il est nécessaire de prendre 0 o/11,4 Mo dans les archives.
Après cette opération, 50,4 Mo d'espace disque supplémentaires seront utilisés.
Sélection du paquet libjs-highlight.js précédemment désélectionné.
(Lecture de la base de données... 478725 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../libjs-highlight.js_9.18.5+dfsg1-1_all.deb ...
Dépaquetage de libjs-highlight.js (9.18.5+dfsg1-1) ...
Sélection du paquet libnode72:amd64 précédemment désélectionné.
Préparation du dépaquetage de .../libnode72_12.22.12~dfsg-1~deb11u3_amd64.deb ...
Dépaquetage de libnode72:amd64 (12.22.12~dfsg-1~deb11u3) ...
Sélection du paquet nodejs précédemment désélectionné.
Préparation du dépaquetage de .../nodejs_12.22.12~dfsg-1~deb11u3_amd64.deb ...
Dépaquetage de nodejs (12.22.12~dfsg-1~deb11u3) ...
Sélection du paquet nodejs-doc précédemment désélectionné.
Préparation du dépaquetage de .../nodejs-doc_12.22.12~dfsg-1~deb11u3_all.deb ...
Dépaquetage de nodejs-doc (12.22.12~dfsg-1~deb11u3) ...
Paramétrage de libnode72:amd64 (12.22.12~dfsg-1~deb11u3) ...
Paramétrage de libjs-highlight.js (9.18.5+dfsg1-1) ...
Paramétrage de nodejs (12.22.12~dfsg-1~deb11u3) ...
update-alternatives: utilisation de « /usr/bin/nodejs » pour fournir « /usr/bin/js » (js) en mode automatique
Paramétrage de nodejs-doc (12.22.12~dfsg-1~deb11u3) ...
Traitement des actions différées (« triggers ») pour libc-bin (2.31-13+deb11u5) ...
Traitement des actions différées (« triggers ») pour man-db (2.10.1-1~bpo11+1) ...
Traitement des actions différées (« triggers ») pour doc-base (0.11.1) ...
Traitement de 1 fichier de documentation ajouté…
Scanning application launchers
Removing duplicate launchers or broken launchers
Launchers are updated
┌─[root@parrot]─[~]
└──╼ #nodejs --version
v12.22.12

```

**Comment by riosje** [comment]
@kbaniszack it looks like you already have NodeJS 12 installed, could you try to remove it before install nodejs19.
thank you.

**Comment by ceszgdav** [comment]
Hi, I'm trying to install nodejs in my ParrotOS and I get the same error as kbaniszack, I almost uninstall node and npm with `$ sudo apt purge --autoremove nodejs npm` and then run as root ```
curl -fsSL https://deb.nodesource.com/setup_16.x | bash - &&\
apt-get install -y nodejs
```
but when it finish i get 
```

## Installing the NodeSource Node.js 16.x repo...


## Populating apt-get cache...

+ apt-get update
Obj:1 http://packages.microsoft.com/repos/code stable InRelease
Obj:2 https://deb.nodesource.com/node_16.x bullseye InRelease                  
Obj:3 https://deb.parrot.sh/parrot lts InRelease      
Obj:4 https://deb.parrot.sh/parrot parrot InRelease
Obj:5 https://deb.parrot.sh/direct/parrot parrot-security InRelease
Obj:6 https://deb.parrot.sh/parrot parrot-backports InRelease
Leyendo lista de paquetes... Hecho

## You seem to be using Parrot version ara.
## This maps to Debian "bullseye"... Adjusting for you...

## Confirming "bullseye" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/bullseye/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg >/dev/null

## Creating apt sources list file for the NodeSource Node.js 16.x repo...

+ echo 'deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x bullseye main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x bullseye main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Obj:1 https://deb.nodesource.com/node_16.x bullseye InRelease
Obj:2 http://packages.microsoft.com/repos/code stable InRelease                
Obj:3 https://deb.parrot.sh/parrot lts InRelease                               
Obj:4 https://deb.parrot.sh/parrot parrot InRelease                     
Obj:5 https://deb.parrot.sh/direct/parrot parrot-security InRelease
Obj:6 https://deb.parrot.sh/parrot parrot-backports InRelease
Leyendo lista de paquetes... Hecho

## Run `sudo apt-get install -y nodejs` to install Node.js 16.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
     echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn


Leyendo lista de paquetes... Hecho
Creando árbol de dependencias... Hecho
Leyendo la información de estado... Hecho
Se instalarán los siguientes paquetes adicionales:
  libc-ares2 libjs-highlight.js libnode72 nodejs-doc
Paquetes sugeridos:
  npm
Se instalarán los siguientes paquetes NUEVOS:
  libc-ares2 libjs-highlight.js libnode72 nodejs nodejs-doc
0 actualizados, 5 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
Se necesita descargar 0 B/11.5 MB de archivos.
Se utilizarán 50.5 MB de espacio de disco adicional después de esta operación.
Seleccionando el paquete libc-ares2:amd64 previamente no seleccionado.
(Leyendo la base de datos ... 319871 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar .../libc-ares2_1.17.1-1+deb11u2_amd64.deb ...
Desempaquetando libc-ares2:amd64 (1.17.1-1+deb11u2) ...
Seleccionando el paquete libjs-highlight.js previamente no seleccionado.
Preparando para desempaquetar .../libjs-highlight.js_9.18.5+dfsg1-1_all.deb ...
Desempaquetando libjs-highlight.js (9.18.5+dfsg1-1) ...
Seleccionando el paquete libnode72:amd64 previamente no seleccionado.
Preparando para desempaquetar .../libnode72_12.22.12~dfsg-1~deb11u3_amd64.deb ...
Desempaquetando libnode72:amd64 (12.22.12~dfsg-1~deb11u3) ...
Seleccionando el paquete nodejs previamente no seleccionado.
Preparando para desempaquetar .../nodejs_12.22.12~dfsg-1~deb11u3_amd64.deb ...
Desempaquetando nodejs (12.22.12~dfsg-1~deb11u3) ...
Seleccionando el paquete nodejs-doc previamente no seleccionado.
Preparando para desempaquetar .../nodejs-doc_12.22.12~dfsg-1~deb11u3_all.deb ...
Desempaquetando nodejs-doc (12.22.12~dfsg-1~deb11u3) ...
Configurando libc-ares2:amd64 (1.17.1-1+deb11u2) ...
Configurando libnode72:amd64 (12.22.12~dfsg-1~deb11u3) ...
Configurando libjs-highlight.js (9.18.5+dfsg1-1) ...
Configurando nodejs (12.22.12~dfsg-1~deb11u3) ...
update-alternatives: utilizando /usr/bin/nodejs para proveer /usr/bin/js (js) en modo automático
Configurando nodejs-doc (12.22.12~dfsg-1~deb11u3) ...
Procesando disparadores para man-db (2.10.1-1~bpo11+1) ...
Procesando disparadores para libc-bin (2.31-13+deb11u6) ...
Scanning application launchers
Removing duplicate launchers or broken launchers
 [-] Missing executable file nautilus at launcher /usr/share/applications/brasero-nautilus.desktop
Launchers are updated

```
any idea how can i fix this?
