### ISSUE TITLE
[Permission denied] Node.js v19.x on Debian, as root Installation fail

### ISSUE THREAD

**Issue by IanoNjuguna** [nodesource/distributions#1516]
**Describe your bug**
During the installation, one gets a permission denied error.

**Distribution Information:**
 - OS: Zorin OS
 - Version [16.2]
 - Other info if applicable [Linux 5.15.0-60-generic]

**Node Version:**
 - Node: [e.g. Node.js v19.x:]

**To Reproduce**
1. Execute Installation instructions for Node.js v19.x using Debian, as root:

**Expected behavior**
The installation doesn't continue because of a permission denied error

**Additional context**
This is simply fixed by running ```apt-get install -y nodejs``` with admin powers (sudo)

**Comment by IanoNjuguna** [comment]
@JesusPaz  I'd love to fix this bug.

**Comment by riosje** [comment]
Hi @IanoNjuguna 
In [the documentation ](https://github.com/nodesource/distributions#installation-instructions) is specified that you should run with root or without root should use sudo.
It's not a bug.
```shell
curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - &&\
sudo apt-get install -y nodejs
```
