### ISSUE TITLE
[ERROR] Node.js 18.x Installation fail libc6

### ISSUE THREAD

**Issue by rafaelmaframg** [nodesource/distributions#1517]
getting an error with the **lib6c** on aws codebuild runs the command "-apt-get install -y nodejs"

 - AWS Codebuild
 - Node: Node.js v18.x
 - Linux - aws/codebuild/standard:4.0

Execute Installation instructions for Node.js v18.x:

`
[Container] 2023/02/22 16:58:47 Running command apt-get install -y nodejs`
`Reading package lists...`
`Building dependency tree...`
`Reading state information...`
`Some packages could not be installed. This may mean that you have`
`requested an impossible situation or if you are using the unstable`
`distribution that some required packages have not yet been created`
`or been moved out of Incoming.`
`The following information may help to resolve the situation:`
`The following packages have unmet dependencies:`
`nodejs : Depends: libc6 (>= 2.28) but 2.27-3ubuntu1.6 is to be installed`
`E: Unable to correct problems, you have held broken packages.`

**error**
 nodejs : Depends: libc6 (>= 2.28) but 2.27-3ubuntu1.6 is to be installed 
 E: Unable to correct problems, you have held broken packages.

**Additional context**
the deployment was done before using the same configuration and it was working until today, nothing was changed

**Comment by riosje** [comment]
Hi @rafaelmaframg the newer versions of NodeJS requires `GLIBC2.28` or higher to run.
You may use a newer version like `aws/codebuild/standard:5.0` or `aws/codebuild/standard:6.0`
