### ISSUE TITLE
[DISTRIBUTION] Support for distribution Ubuntu 22.10

### ISSUE THREAD

**Issue by AndresCidInst** [nodesource/distributions#1519]
**Describe the distribution information:**
 - OS: UBUNTU
 - Distribution Type: DEB
 - Version 22.10
 - codename: kinetic

**Additional context**
![image](https://user-images.githubusercontent.com/121510315/222454052-175ab04f-dba0-40be-b654-2e3f6c979fe4.png)

I tried to install a version of node on ubuntu, but the process broke down because my distro was not supported :/

**Comment by JesusPaz** [comment]
This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).
