### ISSUE TITLE
[ERROR] Node.js 14.x/16.x on Ubuntu20.04 Installation fails via published install packages

### ISSUE THREAD

**Issue by avosper-intellaegis** [nodesource/distributions#1520]
**Describe your bug**
node distribution package for Ubuntu 20.04 appears to be linked incorrectly as of 03.02.23 -

**Distribution Information:**
Ubuntu20.04 based container image

**Node Version:**
 - Node fermium or gallium

**To Reproduce**
- apt update -y
- curl -sL https://nsolid-deb.nodesource.com/nsolid_setup_4.x | bash -
- apt -y install nsolid-gallium 
- (or) apt -y install nsolid-fermium

**Expected behavior**
The linked package installs as expected and was experienced prior to 03.02.23. 

**Screenshots**
N/A

**Additional context**
 200 - (from browsing at http://nsolid-deb.nodesource.com/nsolid_4.x)
	http://nsolid-deb.nodesource.com/nsolid_4.x/pool/main/n/nsolid-gallium/nsolid-gallium_4.9.2-nodesource-systemd1_amd64.deb
404 - (from build steps above)
	http://nsolid-deb.nodesource.com/nsolid_4.x/pool/main/n/nsolid-gallium/nsolid-gallium_4.9.2-deb-nodesource-systemd1_amd64.deb

**Comment by riosje** [comment]
Hi @avosper-intellaegis we have some issues with the release of 'nsolid-4.9.2' as workaround you might install it manually with`dpk` using this package. [nsolid-gallium_4.9.2-nodesource-systemd1_amd64.deb](https://nsolid-deb.nodesource.com/nsolid_4.x/pool/main/n/nsolid-gallium/nsolid-gallium_4.9.2-nodesource-systemd1_amd64.deb)
We're working to solve this issue ASAP.
