### ISSUE TITLE
Your distribution, identified as "vera", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

### ISSUE THREAD

**Issue by aaditya-cpu** [nodesource/distributions#1522]
lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.1
Release:	21.1
Codename:	vera

 curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash - &&\
sudo apt-get install -y nodejs

## Populating apt-get cache...

+ apt-get update
Hit:1 http://mirrors.piconets.webwerks.in/ubuntu-mirror/ubuntu jammy InRelease
Hit:2 https://deb.nodesource.com/node_19.x jammy InRelease
Hit:3 http://mirrors.piconets.webwerks.in/ubuntu-mirror/ubuntu jammy-updates InRelease
Hit:4 http://mirrors.piconets.webwerks.in/ubuntu-mirror/ubuntu jammy-backports InRelease
Ign:5 https://mirrors.piconets.webwerks.in/linuxmint-mirror/packages vera InRelease
Hit:6 https://mirrors.piconets.webwerks.in/linuxmint-mirror/packages vera Release
Hit:8 http://security.ubuntu.com/ubuntu jammy-security InRelease               
Reading package lists... Done

## Confirming "vera" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_19.x/dists/vera/Release'

**Comment by JesusPaz** [comment]
Your distribution is already supported
