### ISSUE TITLE
Unable to install on Kali

### ISSUE THREAD

**Issue by farhatnawaz** [nodesource/distributions#153]
Hi, I have tried my ass off to install Nodejs on my Kali linux but it just won't. Could anybody be of some help? Any input would be appreciated.

**Comment by wblankenship** [comment]
Hi @farhatnawaz,

It looks like @mattbrun has done the work to get our scripts running on Kali linux through https://github.com/nodesource/distributions/blob/master/deb/setup#L81. Simply using the default installation script should work.

Could you provide a bit more context on the problems your having?

**Comment by mattbrun** [comment]
Hi @farhatnawaz, as @wblankenship sad I'm run bot nodejs 0.12 and 4.x on Kali Linux 2.0 
Which is your configuration? Which errors are you getting?

**Comment by farhatnawaz** [comment]
Hi, @wblankenship  @mattbrun - thanks for your time and suggestions guys - I was using kali 1.1 previously but I updated it to 2.0 yestaerday and I was able to install nodejs. But now I'm trying to generate the files using yo but i get some error shown in the screenshot. Any idea?
![screenshot from 2015-10-19 16 08 26](https://cloud.githubusercontent.com/assets/8686962/10576381/4c038876-767c-11e5-88f4-6cb2e27151bc.png)

**Comment by retrohacker** [comment]
Installing on Khali appears to have been solved.

The permissions issue you are experiencing is a file system permission issue on your computer, and is outside the scope of this repo.

As the currently logged in user, try to `cd` down into that directory and see what happens. You may need to create that folder or take ownership of it.

Hope this helps!
