### ISSUE TITLE
[DISTRIBUTION] Support for distribution centos-release-7-9.2009.0.el7.centos.aarch64

### ISSUE THREAD

**Issue by zaunist** [nodesource/distributions#1530]
**Describe the distribution information:**
 - OS: centos-release-7-9.2009.0.el7.centos.aarch64
 - Distribution Type: RPM
 - Version 7.9
 - Other info if needed

**Additional context**

![image](https://user-images.githubusercontent.com/38528079/226277594-be25cc9f-63e4-4e3f-b9a0-eb20d62ed13b.png)

**Comment by zaunist** [comment]
Can someone help me out here? Can you assist in adding support, or provide me with some guidance to add support for CentOS 7.9?

**Comment by cobalt2727** [comment]
They won't help you - this has been a problem for over a year. You'll either need to use NodeJS 16 or upgrade to CentOS 8.

Relevant links:
https://github.com/nodesource/distributions/issues/1392
https://github.com/nodejs/node/issues/43246
https://github.com/nodesource/distributions/pull/1400 (I didn't expect this to actually get merged...)

There's been some attempts to get alternative sources for NodeJS 18 working for older distros, but so far the response time has been inexplicably slow...
https://github.com/nodesource/distributions/issues/1491
https://github.com/nodesource/distributions/issues/1492

**Comment by zaunist** [comment]
> 

thx

**Comment by Nic128** [comment]
https://github.com/nodejs/node/issues/43246#issuecomment-1528903208

**Comment by riosje** [comment]
@zaunist as far as I can see, your case is not the same as @cobalt2727 mentions.
I can see you're trying to install Node14 on Centos7 with aarch64.
Node14 and Node16 can run on Centos7 without problem, but Node18 can't

I was able to Install Node14 without problems on Centos7, can you paste here the script you're using?
![image](https://github.com/nodesource/distributions/assets/55195249/52e9d939-fbe4-4cf9-ab33-aef5e48f41f7)

@cobalt2727 just stop blaming on us about something we can do NOTHING, You know this repo is only intended to distribute de Nodejs packages as it comes from [NODE](https://github.com/nodejs/node)
you have enough alternatives from Node team to get the LTS version running on OLD distros

https://github.com/nodejs/unofficial-builds [node/node#43246](https://github.com/nodejs/node/issues/43246)
https://github.com/bnoordhuis/cracknode [node/node#42351](https://github.com/nodejs/node/issues/42351)

**Comment by cobalt2727** [comment]
My mistake. Didn't realize this was _14_. Disregard my comments in regards to this particular Issue.

**Comment by zaunist** [comment]
@riosje Sorry, I think this issue has already been resolved. Initially, the problem occurred when executing this [command,](https://github.com/zaunist/apisix-build-tools/blob/663b716c92448b77dbc93ef185d5f3dcb9fd6ffa/utils/install-common.sh#L137) but it seems that it was not encountered later on. After that, I had no issues installing Node.js 14 on aarch64 architecture machines.

**Comment by zaunist** [comment]
Thank @cobalt2727  and @riosje  for the guidance. Now I no longer have any issues, so I will close this issue.
