### ISSUE TITLE
[DISTRIBUTION] Support for distribution system-release-2-14.amzn2.x86_64

### ISSUE THREAD

**Issue by sandhyak19** [nodesource/distributions#1531]
When I am trying to install Node js on Amazon EC2, I am getting this error:

curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_16.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

Your distribution, identified as "system-release-2-14.amzn2.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by riosje** [comment]
Hi @sandhyak19 
I was able to install node16 on amazon linux 2 following kind of similar steps running a docker image

Run the docker

```SHELL
docker run -it --rm amazonlinux:2 bash
```

Install Node
```SHELL
curl –sL https://rpm.nodesource.com/setup_16.x | bash -
yum install -y nodejs
```

Validate the version
```SHELL
node -v
bash-4.2# node -v
v16.20.0
```
