### ISSUE TITLE
[DISTRIBUTION] Support for distribution Amazon Linux 3

### ISSUE THREAD

**Issue by niharkarra** [nodesource/distributions#1532]
**Describe the distribution information:**
 - OS: Amazon Linux
 - Distribution Type: RPM
 - Version 3

---

**Additional context**

**_Issue :_**
The [newly released](https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-linux-2023/) **Amazon Linux 3** distribution is not yet available causing the line `FROM amazonlinux:latest` to fail. Please add this new distribution. 

---

**_Error:_**
`
#5 5.060 ## You don't appear to be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support. Include your 'distribution package' name: no package provides redhat-release`

---

**_Temporary Workaround:_**
Modifying the line `FROM amazonlinux:latest` to `FROM amazonlinux:2`is working as a temporary solution.

---

**_Reproduction steps:_**

<img width="483" alt="image" src="https://user-images.githubusercontent.com/22804384/227117533-35ac499d-0ebf-469f-8ac7-f183e6fc1cef.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22804384/227117687-ab4435ee-b898-49b7-939e-768da73fea95.png">

**Comment by skyzyx** [comment]
@niharkarra meant "Amazon Linux 2023". They will all follow this naming pattern moving forward.

@JesusPaz: Is there a branch where you're working on this? I'd like to take a look and see if I can help.

**Comment by riosje** [comment]
hi guys there is already support for amazon linux 2023.
