### ISSUE TITLE
[DISTRIBUTION] Support for distribution XX

### ISSUE THREAD

**Issue by hechendorf** [nodesource/distributions#1536]
**Describe the distribution information:**
Distro: Linux Mint 21.1 Vera

**Additional context**
needed for github Copilot

**Comment by hechendorf** [comment]
Is there anybody there ? Does anybody care for this kind of requests ?

**Comment by JesusPaz** [comment]
Your distribution is already supported

**Comment by hechendorf** [comment]
I try to user Copilt with neovim.
":Copilot setup" results in
"Copilot: 'Node.js version 16.x or newer required but found 12.22.9'"
Linux Mint 21.1 Vera doesn't have Node.js version 16.x or newer.
