### ISSUE TITLE
Support for long term support releases

### ISSUE THREAD

**Issue by Siilwyn** [nodesource/distributions#154]
It would be really nice to have a distribution for LTS releases such as [Node v4.2.1](https://nodejs.org/en/blog/release/v4.2.1/).

**Comment by chrislea** [comment]
That's just going to track with the 4.x releases now that 5.x hash been pushed out. If you want to stay on the LTS release, you just keep using the packages from 4.x and you should be good to go.

**Comment by Siilwyn** [comment]
Roger that, thanks for your reply!
