### ISSUE TITLE
[ERROR] Node.js 16.20.0 installation fail

### ISSUE THREAD

**Issue by okuryu** [nodesource/distributions#1546]
**Describe your bug**
The recently released 16.20.0 rpm package seems to be missing.
https://nodejs.org/en/blog/release/v16.20.0

**Distribution Information:**
 - OS: Rocky Linux
 - Version 8

**Node Version:**
 - Node: v16.20.0

**To Reproduce**
1. open https://rpm.nodesource.com/pub_16.x/el/8/x86_64/

**Additional context**
Packages for Ubuntu are probably in a similar state.

**Comment by JesusPaz** [comment]
Thank you for reporting this issue. In a few hours, you will have this package available.
