### ISSUE TITLE
[DISTRIBUTION] Support for distribution Linux Mint 21.1 Vera

### ISSUE THREAD

**Issue by hechendorf** [nodesource/distributions#1548]
Distro: Linux Mint 21.1 Vera
IDE: Neovim

Foolowup Issue #1543

The Setup command
":Copilot setup"
results in
"Copilot: 'Node.js version 16.x or newer required but found 12.22.9'"
Linux Mint 21.1 Vera doesn't have Node.js version 16.x or newer.

So Copilot requests Node.js version 16.x or newer.
Linux Mint 21.1 Vera has Node.js version 12.22.9.
All my applications are up to date.
There is no Node.js version 16 in the Mint repository.

$ apt list Nodejs
Auflistung… Fertig
nodejs/jammy,now 12.22.9~dfsg-1ubuntu3 amd64  [installiert]

So what can be wrong with my System ?

Are there any Linux Mint 21.1 Vera Systems in the world providing Node.js version 16.x ?

**Comment by JesusPaz** [comment]
This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).
