### ISSUE TITLE
[DISTRIBUTION] Support for distribution XX

### ISSUE THREAD

**Issue by GeovaRS** [nodesource/distributions#1549]
**Describe the distribution information:**
 - OS: Linux Fedora 6.2.11-300
 - Distribution Type: RPM
 - Version fc38.x86_64
 - Other info if needed

**Additional context**

![Captura de tela de 2023-04-20 19-04-11](https://user-images.githubusercontent.com/5035658/233497765-ac5d6d2d-7dc3-477d-8822-cc01b7f2b4a9.png)

**Comment by GeovaRS** [comment]
After update from Fedora 37 to Fedora 38, the described Error is generated by the run command: sudo dnf update

**Comment by riosje** [comment]
Node18 is already available for Fedora38, I was able to install it by following the below steps

Run Docker
```SHELL
docker run -it --rm fedora:38 bash
```

install nodejs
```SHELL
curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
yum install nodejs
```

Validate version
```SHELL
 node -v
```
