### ISSUE TITLE
Support nodejs in Ubuntu 15.10

### ISSUE THREAD

**Issue by AcaDemIQ** [nodesource/distributions#155]
I can't install packet, because:
```
## Confirming "wily" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_0.12/dists/wily/Release'

## Your distribution, identified as "wily", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by aensley** [comment]
Same issue here.

**Comment by chrislea** [comment]
Hi guys. You're seeing this because you're trying to install 0.12 which is no longer the currently maintained version. Please ref: https://github.com/nodesource/distributions/issues/129#issuecomment-150382619

**Comment by chrislea** [comment]
Also, if it's helpful, NodeSource has published [this upgrade guide](https://nodesource.com/services/upgrade-self-service) which you may find useful.

**Comment by aensley** [comment]
Whoops. Thanks for the pointer.

**Comment by greenx** [comment]
The trouble is that not all modules are running on latest version.
