### ISSUE TITLE
README should mention that the npm CLI is included

### ISSUE THREAD

**Issue by mikebolt** [nodesource/distributions#1550]
The README does not mention that npm is included. There is this comment in the output of the setup script:

```
## Run `sudo apt-get install -y nodejs` to install Node.js 18.x and npm
```

I think it would be good to include this in the README. It only mentions something about npm native addons.

**Distribution Information:**
 - OS: N/A
 - Version N/A

**Node Version:**
 - Node: N/A

**Comment by riosje** [comment]
Hi @mikebolt npm is already included with the NodeJS binaries.
All what we do is package into deb and rpm the software as it comes from de Node.

https://github.com/nodejs/node/tree/main/deps
https://nodejs.org/dist
