### ISSUE TITLE
[DISTRIBUTION] Support for distribution Ubuntu 23.04 (Lunar Lobster)

### ISSUE THREAD

**Issue by heyrmi** [nodesource/distributions#1552]
**Describe the distribution information:**
 - OS: Ubuntu 23.04 (Lunar Lobster)
 - Distribution Type: DEB
 - Version 23.04
  - Other info if needed

**Additional context**
Currently nor supported: 

![LunarNotSupported](https://user-images.githubusercontent.com/42892759/234684118-0016858c-208c-4c93-85ce-4102ee28b504.png)

**Comment by eljejer** [comment]
Same with me. Distribution: Regolith Linux

**Comment by filmverse** [comment]
Same with me

**Comment by mr-abdellah** [comment]
**hey folks** @heyrmi @eljejer @filmverse I had same issue when I was trying to install node 18, I tried to install node 20 and it works well on my end 
![image](https://user-images.githubusercontent.com/98021746/235924245-526756f9-0dd1-4ef3-90ca-3e37916db3d5.png)

**Comment by riosje** [comment]
Hi guys we've installed the nodejs packages for this dist.
You should be able to install now nodejs on Ubuntu Lunar.
