### ISSUE TITLE
Upgrade Instructions

### ISSUE THREAD

**Issue by 720720** [nodesource/distributions#1554]
Last year I installed Node.js LTS on a debian server via

```bash
curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - &&\
apt-get install -y nodejs
```

The LTS version changed from 16 to 18 and I want to upgrade Node.js.
The README has great Install and Uninstall but no Upgrade Instructions.
Should I just run the install script again or uninstall Node.js 16 before installing Node.js 18.

**Comment by riosje** [comment]
Hello guys, with the new installation process the repo is agnostic to the distro.
We will not use installation scripts anymore.
To change the node version all what you need is remove the old repo a repeat the installation instructions on the README

Take a look to the new README
https://github.com/nodesource/distributions#installation-instructions-1
