### ISSUE TITLE
[ERROR] Node.js 18 on Linux2023 Installation fail

### ISSUE THREAD

**Issue by mind-mind** [nodesource/distributions#1555]
Can't install using this command

`curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -`

![image](https://user-images.githubusercontent.com/68138683/235945148-a09f581e-a82b-4dda-a887-2b0e99942671.png)

**Comment by Laiarenas** [comment]
yes, it always say this error...

**Comment by mind-mind** [comment]
I contact AWS support and they already provide the step to install nodejs18 on Linux2023

```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
 . ~/.nvm/nvm.sh
nvm install --lts
node -e "console.log('Running Node.js ' + process.version)"
```
