### ISSUE TITLE
Ubuntu 18.04 LTS support

### ISSUE THREAD

**Issue by borodadada** [nodesource/distributions#1556]
Hi! i use ubuntu 18 LTS. Can not install node js 18 or 20 wtf? On windows all work fine!
(Bionic Beaver) WARNING: BUILD SYSTEM CURRENTLY BROKEN FOR NODEJS 18+
Will it fix in future? or not?

**Comment by riosje** [comment]
Hi @borodadada hope you're doing well today.
Please have in mind the following.
**First**: That windows comparison just doesn't make sense.
**Second**: Ubuntu 18 has not the minimum requirements to run Node 18 or 20. You need a OS which support GLIBC2.28 or higher read a bit more about the requirements [here](https://github.com/nodejs/node/blob/v18.x/BUILDING.md#platform-list).
**Third**: the build system is ok, there is nothing to fix on the build side.
