### ISSUE TITLE
[DISTRIBUTION] Support for distribution Nobara (Fedora fork)

### ISSUE THREAD

**Issue by tomByrer** [nodesource/distributions#1557]
**Describe the distribution information:**
 - OS: Nobara Linux (Fedora fork)
 - Distribution Type: RPM
 - Version 37 (Thirty Seven)
 
**Additional context**
https://nobaraproject.org/
Your CLI said `nobara-release-workstation-37-2.noarch.`

**Comment by riosje** [comment]
Hi guys, recently we've deployed new changes on our distribution solution.
Now the installation is agnostic to the Linux distro.
Follow the instruction on the new README
https://github.com/nodesource/distributions#installation-instructions-1
