### ISSUE TITLE
No support for sl-release-6.6-1.x86_64?

### ISSUE THREAD

**Issue by acampove** [nodesource/distributions#156]
Hi,
I am trying to install in sl-release-6.6-1.x86_64 but when i do:

curl --silent --location https://rpm.nodesource.com/setup | bash -

i get:

## You don't appear to be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support. Include your 'distribution package' name: sl-release-6.6-1.x86_64. 

is there a way to install this package in my OS?

Thanks.

**Comment by JoshuaPK** [comment]
This might help:  https://github.com/nodesource/distributions/issues/117
