### ISSUE TITLE
[DISTRIBUTION] Support for distribution Amazon Linux 2023

### ISSUE THREAD

**Issue by Joe-Zer0** [nodesource/distributions#1564]
Distribution Information
cat /etc/os-release
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
SUPPORT_END="2028-03-01"

Please update Node.js 18.x to support installation on Amazon Linux 2023.  Thanks!

**Comment by riosje** [comment]
Hi @Joe-Zer0 the scripts has been updated and the cache has been cleaned.
you should be able to install Nodejs now on Amazon Linux 2023
