### ISSUE TITLE
Debian "Release" file does not contain the "Suite" keyword

### ISSUE THREAD

**Issue by 4wk-** [nodesource/distributions#1578]
**Describe your bug**
When adding the apt repository `nodesource` for the LTS version of node, the package `nodejs `is listed as **unknown** in apt.
Maybe it's because the "Release" [file for Debian](https://deb.nodesource.com/node_18.x/dists/bullseye/InRelease) is lacking the "Suite" key? 

https://askubuntu.com/a/921955/310574
https://wiki.debian.org/DebianRepository/Format#A.22Release.22_files

Before (nodejs default version packed in Debian):
```
apt search --names-only nodejs
nodejs/oldstable-security 12.22.12~dfsg-1~deb11u4 amd64
  evented I/O for V8 javascript - runtime executable
```

After:
```
apt search --names-only nodejs
nodejs/unknown 18.16.0-deb-1nodesource1 amd64
  Node.js event-based server-side javascript engine
```

**Distribution Information:**
 - OS: Debian 11.7 on a docker container, ran inside wsl2, in Windows 10

**Node Version:**
 - Node: v18.16.0

**To Reproduce**
- Download gpg key https://deb.nodesource.com/gpgkey/nodesource.gpg.key
- `gpg --batch --yes -o /usr/share/keyrings/nodesource.gpg --dearmor /usr/share/keyrings/nodesource.gpg.key`
- update sources.list.d with 
`deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x  bullseye main`
- apt update

**Expected behavior**
I was expecting something else than **unknow** (probably `LTS something`)

**Comment by JesusPaz** [comment]
This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).
