### ISSUE TITLE
[ERROR] Setup_16.x on Debian 12 Bookworm installs `v18.13.0`

### ISSUE THREAD

**Issue by o1y** [nodesource/distributions#1579]
**Describe your bug**
When installing node 16.x, the setup script installs node `v18.13.0` without any npm package.

**Distribution Information:**
 - OS: Debian
 - Version 12 Bookworm
 - Docker Base Image: php:8.2-apache

**Node Version:**
 - Node: v16.x

**To Reproduce**

Use this Dockerfile:

```Dockerfile
FROM php:8.2-apache

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
&& apt-get install -y nodejs
```

**Expected behavior**
Installation of node v16.x and npm package.

**Comment by gaurangblaze** [comment]
Same issue with python docker image. Switched to `python:3.11-slim-bullseye` to solve this issue (previous image was `python:3.11-slim`).

**Comment by amirredouane** [comment]
You can add 'npm' after nodejs "&& apt-get install -y nodejs npm" in order to solve the problem

**Comment by alexk2000** [comment]
No problem to install npm but I expect to install nodejs version 14 but get 18.

**Comment by amirredouane** [comment]
I mean the other half of your problem "the setup script installs node v18.13.0 **without any npm package**"

**Comment by riosje** [comment]
Hi guys this is an issue with the repositories configuration on your OS, I was not even able to re-produce this behavior.
this resource may help you
https://unix.stackexchange.com/questions/448135/specify-specific-source-apt-repository-for-package

**Comment by o1y** [comment]
Sorry @riosje, you are right. The script is working correctly. 

The challenge is that Debian Bookworm provides a newer Node.js package `18.13.0` from the ﻿`deb.debian.org` repository. On previous Buster, the available version was ﻿10.24.0. The curl script can be a bit misleading, as it suggests that you can install Node.js 16.x and npm by just installing the ﻿nodejs package:
```
## Run `sudo apt-get install -y nodejs` to install Node.js 16.x and npm
```

But as you already mentioned the solution is to pin the `deb.nodesource.com` repo first, before installing the nodejs package. Thanks! :)

**Comment by gaurangblaze** [comment]
Thanks for the clarification. How can we pin `deb.nodesource.com` repo in the Dockerfile? Based on the linked StackExchange answer, does this suffice:

```bash
RUN echo "Package: *
Pin: origin deb.nodesource.com
Pin-Priority: 1001" >> /etc/apt/preferences.d/preferences
```

**Comment by o1y** [comment]
@gaurangblaze You could use the following Dockerfile as an example:

```Dockerfile
FROM php:8.2-apache-bookworm

RUN echo 'Package: nodejs\nPin: origin deb.nodesource.com\nPin-Priority: 600' > /etc/apt/preferences.d/nodesource \
    && curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs

```

**Comment by liang611zh** [comment]
> @gaurangblaze You could use the following Dockerfile as an example:
> 
> ```dockerfile
> FROM php:8.2-apache-bookworm
> 
> RUN echo 'Package: nodejs\nPin: origin deb.nodesource.com\nPin-Priority: 600' > /etc/apt/preferences.d/nodesource \
>     && curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
>     && apt-get install -y nodejs
> ```

Hi o1y,
When I use this resource, I got a wrong version v18.x, did u figure out how to get the correct version of it?

**Comment by BatmanAoD** [comment]
Right now, it appears to me that _every_ script with the following conditions is broken:

* It uses a Docker image based on `Bookworm`
* It uses the `nodesource` setup-script
* It uses the command *suggested by the setup script* for installing Node & npm: `apt-get install -y nodejs`
* It requires a version of NodeJS prior to 18, and/or it requires `npm`

This seems like a fairly common situation, which is why there are already multiple comments in this thread even though Bookworm was released under two weeks ago. Note that prior to this, running the `nodesource` setup script and then installing `nodejs` "just worked."

Can the `pin` command be added to the setup script itself? Alternatively, can the suggested installation command printed by the setup script be updated to explicitly use the newly-added source (i.e. using `apt install -t ...`)?

**Comment by beijaflor** [comment]
@liang611zh 
> Hi o1y,
> When I use this resource, I got a wrong version v18.x, did u figure out how to get the correct version of it?

it works for me
```dockerfile
RUN echo "Package: nodejs" >> /etc/apt/preferences.d/preferences && \
    echo "Pin: origin deb.nodesource.com" >> /etc/apt/preferences.d/preferences && \
    echo "Pin-Priority: 1001" >> /etc/apt/preferences.d/preferences

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs
```

**Comment by BatmanAoD** [comment]
@riosje Can the `Pin` be added to the `nodesource` script itself? Without it, the script is effectively broken (as I explained in my comment above).
