### ISSUE TITLE
npm not executable in nodejs_4.2.1-2nodesource1~sid1_amd64.deb

### ISSUE THREAD

**Issue by mvduin** [nodesource/distributions#158]
```
lrwxrwxrwx 1 root root /usr/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
-rw-r--r-- 1 root root /usr/lib/node_modules/npm/bin/npm-cli.js
```

**Comment by chrislea** [comment]
That does look inconsistent. Can you show the output of this please?

```bash
dpkg -L nodejs | grep npm-cli.js | xargs ls -la
```

**Comment by chrislea** [comment]
And also

```bash
dpkg -V nodejs
```

please?

**Comment by mvduin** [comment]
with dpkg -L only the /usr/lib/node_modules/npm/bin/npm-cli.js file shows up. I've changed its permissions manually as a workaround, but if I list the contents of the deb file instead
```
dpkg-deb -c /var/cache/apt/archives/nodejs_4.2.1-2nodesource1~sid1_amd64.deb | grep npm-cli.js
```
the result corresponds to what I saw on my system after installation:
```
-rw-r--r-- root/root      1881 2015-10-19 20:54 ./usr/lib/node_modules/npm/bin/npm-cli.js
lrwxrwxrwx root/root         0 2015-10-19 20:54 ./usr/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
```
If I do the same on the previous version, nodejs_4.2.1-1nodesource1~sid1_amd64.deb, I get:
```
-rwxr-xr-x root/root      1881 2015-10-14 02:51 ./usr/lib/node_modules/npm/bin/npm-cli.js
lrwxrwxrwx root/root         0 2015-10-14 02:51 ./usr/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
```

**Comment by mvduin** [comment]
(dpkg -V completed succesfullly. I had also already tried reinstall and purge and reinstall)

**Comment by chrislea** [comment]
Okay, I a seeing the same thing you are for the sid package. Which is just incredibly weird, as for example in the corresponding wheezy package it's executable as it should be, and they are built from identical sources.

Unfortunately, this means there is probably something "clever" going on in sid that's not happening anywhere else that I'll have to figure out, but I'm looking into it. Thanks for the catch.

**Comment by chrislea** [comment]
Found it / fixed it. It seems that in sid they made some changes to `dh_fixperms` that caused this. An

```bash
apt-get update
apt-get upgrade
```
should get you sorted as of now (but please let us know if not).
