### ISSUE TITLE
[ERROR] setup_14.x on Debian installs v18.13.0

### ISSUE THREAD

**Issue by BasilaryGroup** [nodesource/distributions#1581]
**Describe your bug**
Installing node 14.x, the setup script installs node v18.13.0 without any npm package.

**Distribution Information:**
 - OS: Debian
 - Version 9.13
 - Docker image node:14.16.1

**Node Version:**
 - Node: v14.x

**To Reproduce**
1. Use docker image: node:14.6.1
2. curl -sL https://deb.nodesource.com/setup_14.x | bash -
3. apt-get install -y nodejs
4. $ node --version
v18.13.0
$ npm --version
/usr/bin/bash: line 152: npm: command not found

**Expected behavior**
Installation of node v14.x and npm packages.

**Screenshots**

**Comment by dcrec1** [comment]
This is also happening with the v16.x script.

**Comment by riosje** [comment]
Hi @BasilaryGroup

1. this docker image does not exist `node:14.6.1`
2. Instead I highly suggest you to use the latest version of Node14 (14.21.3) using `node:14`
3. if you are already using the node image you do not need to install node, is already installed.
![image](https://github.com/nodesource/distributions/assets/55195249/38b6566c-6402-42e0-998b-880ea0042fb5)

I was not able to re-produce it using ubuntu

```docker
FROM ubuntu:22.04
RUN apt-get update -y && apt-get install curl -y
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install nodejs
```
![image](https://github.com/nodesource/distributions/assets/55195249/8f1d7e3f-cef2-4090-b6be-620b46cae738)

**Comment by dcrec1** [comment]
In my case I am using `ruby:3.1-slim` as the base image.

**Comment by BasilaryGroup** [comment]
We still think something has changed with image `python:lastest` and trying to install node. Our _broken_ build and deploy pipeline had been working for over 26 months until this issue appeared.

```bash
    curl -sL https://deb.nodesource.com/setup_14.x | bash -
    apt-get install -y nodejs
```

It installed node `18.x`.

Moving forward, we improved our pipeline.

1. The build job used image `node:14.16.1`, yes it exists. 
2. Then saved the distribution and node_modules folder as an archive.
3. The deploy job used image `python:latest`, installed `awsebcli` and used gitlab's `dependencies` to get the build output.

It is a better build and deploy flow.

**Comment by devkornev** [comment]
curl -sL https://deb.nodesource.com/setup_14.x | bash -
apt update
apt-cache madison nodejs
in list "14.21.3-deb-1nodesource1"
apt install nodejs=14.21.3-deb-1nodesource1
