### ISSUE TITLE
[DISTRIBUTION] Support for distribution ubuntu 22.04.20

### ISSUE THREAD

**Issue by namanchandak** [nodesource/distributions#1586]
**Describe the distribution information:**
 - OS: ubuntu 22.04.20

this command is not working
$ curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - &&\
sudo apt-get install -y nodejs

it is showing this error

Ign:37 https://in.mirror.coganng.com/ubuntu-ports jammy/multiverse i386 Packages
Hit:38 http://mirror.cse.iitk.ac.in/ubuntu jammy InRelease
Reading package lists... Done           
E: The repository 'https://deb.nodesource.com/node jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting
jonty@jonty-ASUS-TUF-Gaming-F15-FX506L

**Comment by Zenexer** [comment]
Are you on a 32-bit system?  What's the output of `arch`?  I don't believe jammy supports 32-bit, which may be why you're ending up with the wrong repo.  The correct repo is `https://deb.nodesource.com/node_19.x`, but I'd be surprised if it supports 32-bit builds.

**Comment by Zenexer** [comment]
I don't see how the installation script would do that.  Somehow you're ending up with the wrong repo.  Try checking your various APT source files to see where that's coming from.

**Comment by namanchandak** [comment]
> 

I am on 64-bit 
I have not used it on arch linux

**Comment by namanchandak** [comment]
I have probably found the issue...
I had installed Nalla packet manager which is having a compatibility issue...
after Nalla uninstallation it worked
