### ISSUE TITLE
Node.js 16.20.1 not available

### ISSUE THREAD

**Issue by samuelg** [nodesource/distributions#1589]
**Describe your bug**
Per https://deb.nodesource.com/node_16.x/dists/jammy/main/binary-amd64/ packages was updated on June 21, 2023 but looking at the content of https://deb.nodesource.com/node_16.x/dists/jammy/main/binary-amd64/Packages Node.js 16.20.0 is still the latest version configured. The latest release of the 16.x branch is 16.20.1 and so I would expect this to be the exposed version.

**Distribution Information:**
 - OS: Ubuntu
 - Version: jammy 22.04

**Node Version:**
 - Node: Node.js v16.x

**To Reproduce**
1. apt update
2. apt-cache policy nodejs

**Expected behavior**
I would expect version 16.20.1 to be available but instead 16.20.0 is still the latest version available.

**Comment by samuelg** [comment]
FYI I'm also seeing the same thing against bionic: https://deb.nodesource.com/node_16.x/dists/bionic/main/binary-amd64/Packages. Likely other version of Ubuntu affected as well.

**Comment by JesusPaz** [comment]
After some changes, I tried several times and was able to install version 16.20.1 successfully.
