### ISSUE TITLE
Ubuntu 15.10 (Wily) not available for Node 0.12

### ISSUE THREAD

**Issue by luislobo** [nodesource/distributions#159]
In https://github.com/nodesource/distributions it says Ubuntu 15.10 (Wily) is supported, but the repo is empty on 0.12. It exists for 4.x though.

Check:
https://deb.nodesource.com/node_4.x/dists/wily/
https://deb.nodesource.com/node_0.12/dists/wily

**Comment by chrislea** [comment]
Please ref: https://github.com/nodesource/distributions/issues/129#issuecomment-150382619
