### ISSUE TITLE
Ajuda!! NodeJS não inicia após comando

### ISSUE THREAD

**Issue by JuniorWSP** [nodesource/distributions#1590]
Olá pessoal, estou iniciando um curso no qual foi pedido para instalar o NodeJS no meu PC e apesar de ter tido muita dificuldade acredito que tenha instalado porque quando dou os comandos “node -v e npm -v aparece as versões v18.16.1 e 9.5.1”, porem, quando tento abrir com o comando node da a seguinte mensagem:

Welcome to Node.js v18.16.1.
Type “.help” for more information.

Já tentei resolver e instalar de varias formas e não da certo, estou utilizando o Linux Ubunto. Alguem pode me ajudar???

![Captura de tela de 2023-06-22 20-29-03](https://github.com/nodesource/distributions/assets/128398202/c09a3477-24fd-461d-854a-022d02168d79)

**Comment by JesusPaz** [comment]
Can you translate this issue into English please?
