### ISSUE TITLE
[ERROR] Node.js 16.x on Ubuntu 22.10 Installation fail

### ISSUE THREAD

**Issue by AbhinanduReddy** [nodesource/distributions#1596]
Unable to install nodejs 16.x on ubuntu 22.10, instead of 16.x it is installing 18.x and 18.x also not installing npm 

**Distribution Information:**
 - OS: Ubuntu
 - Version 22.10

**Node Version:**
 - Node: nodejs16.x

**To Reproduce**
1. Execute Ubuntu Docker Image 22.10

FROM ubuntu:22.10
ENV NODE_ENV=production
WORKDIR /opt/app
RUN apt-get purge -y nodejs
RUN apt update
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs
RUN node -v
RUN npm -v

**Comment by beijaflor** [comment]
this may be duplicated of #1579
