### ISSUE TITLE
[ERROR] Node.js 12.x on Ubuntu22.04 Installation fail

### ISSUE THREAD

**Issue by AganzeFelicite** [nodesource/distributions#1599]
**Describe your bug**
Your distribution, identified as "jammy", is not currently supported

**Distribution Information:**
 - OS: [e.g. Ubuntu]
 - Version [e.g. focal (22.04)]

**Node Version:**
 - Node:  Node.js v12.x

**To Reproduce**

1. Execute Installation instructions for Node.js v12.x:

**Error message**

## Confirming "jammy" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_12.x/dists/jammy/Release'

## Your distribution, identified as "jammy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

i will be greatfull for your help thanks

**Comment by AganzeFelicite** [comment]
need some help on this

**Comment by riosje** [comment]
HI @AganzeFelicite Nodejs 12 is deprecated now.
try to use the current LTS which is Node18.
just in case you need Node12 must be installed manually since, we do not bring support anymore on older Nodejs Versions.
https://github.com/nodesource/distributions#debmanual
