### ISSUE TITLE
Difference between packages with same Node.js version

### ISSUE THREAD

**Issue by tjconcept** [nodesource/distributions#160]
```shell
$ apt list --upgradable
Listing... Done
nodejs/unknown 4.2.1-2nodesource1~jessie1 amd64 [upgradable from: 4.2.1-1nodesource1~jessie1]
```

How can I check what has been updated or what mandated a new package?

**Comment by retrohacker** [comment]
Hey @tjconcept,

There are several occurrences of this throughout the NodeSource repositories. When there is a problem with a build, we trigger a rebuild. We have been very religious about keeping build artifacts around. In this spirit, when we rebuild an artifact, we generate a new unique package name like the one you see there (with `2nodesource1` in the name) as opposed to displacing the original. I don't believe we formally document the reason for each rebuild, but in the event there are two packages with the same version number, you should always use the most recent build.

Hope this helps!
