### ISSUE TITLE
[ERROR] Node.js XX on UbuntuXX Installation fail

### ISSUE THREAD

**Issue by HummingMind** [nodesource/distributions#1600]
Hello,
The [repomd.xml](https://rpm.nodesource.com/pub_20.x/fc/38/x86_64/repodata/) file for Fedora 38 x86_64 contains the wrong checksums and therefore wrong location href links. Doesn't match the file names in that folder.

So obviously updating the mirror with DNF/YUM fails.

![Screenshot from 2023-07-08 22-52-37](https://github.com/nodesource/distributions/assets/87399963/aa9930d3-53e2-4c1a-8c64-6f422188aaa8)

![Screenshot from 2023-07-08 22-52-26](https://github.com/nodesource/distributions/assets/87399963/3873e194-bf3c-4340-b46e-88793b041f11)

Please fix.
Thank you!

**Comment by JesusPaz** [comment]
This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).
