### ISSUE TITLE
[ERROR] Node.js Lts installation on Debian testing fails

### ISSUE THREAD

**Issue by nicobross** [nodesource/distributions#1602]
**Describe your bug**
The nodejs installation for Debian testing is outdated. The current version of Debian Testing is Trixie. 
However, the nodejs installation script doesn't recognise the distribution.

**Distribution Information:**
 - OS: Debian
 - Version: Trixie

**Node Version:**
 - Node: Node.js v18.x

**To Reproduce**
1. Copy and execute
`curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - &&\
apt-get install -y nodejs`

**Expected behavior**
Being able to install the LTS nodejs on Debian testing.

**Screenshots**
![image](https://github.com/nodesource/distributions/assets/11701736/281a435b-0032-4983-b175-4132ae565d9e)
![image](https://github.com/nodesource/distributions/assets/11701736/f3e69c0a-9903-4c36-ad5c-1cab28669dd2)

**Additional context**
Please, update the nodejs installation for Debian testing

**Comment by rafalkrupinski** [comment]
bookworm is now stable so the list of Debian versions is outdated.

**Comment by luther84** [comment]
also checking in, bookworm has been released and it would be super handy if the repo was updated to reflect that

**Comment by JesusPaz** [comment]
This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).
