### ISSUE TITLE
[DISTRIBUTION] Support for distribution XX

### ISSUE THREAD

**Issue by richardfp76** [nodesource/distributions#1603]
**Describe the distribution information:**
 - OS: Mint Linux 21.2 'victoria' - Ubuntu base 22.04 'Jammy'
 - Distribution Type: DEB
 - Version: 21.2 
 - Need node.js 18.x to run foundry vtt 

**Additional context**

**Comment by TomasKukumberg** [comment]
Same issue. Mint Victoria came out a few days ago and it seems to not be supported yet.

**Comment by vlad0337187** [comment]
As a workaround for Linux Mint 21.2 Victoria - download file by linkt, apply oneline fix:

<details>

![Screenshot from 2023-07-19 15-11-16](https://github.com/nodesource/distributions/assets/12682937/745691dc-6324-4508-875f-e63c037e73de)

</details>

Then run like: `sudo -E bash ~/Desktop/install-node.sh`

**Comment by JesusPaz** [comment]
Changes are already in the server, soon they will be replicated in our CDN #1608

**Comment by StephenAtty** [comment]
How long does replication across the CDN take as this is still not working
