### ISSUE TITLE
[ERROR] Node.js 20 on RHEL 8 

### ISSUE THREAD

**Issue by bjfi** [nodesource/distributions#1605]
**Describe your bug**
When trying to use the nodesource repo to install nodejs 20.x  I get a 404 on the target file. 

Node.js Packages for Enterprise Linux 8 - x86_64                                                                                    91 kB/s | 143 kB     00:01    
Errors during downloading metadata for repository 'nodesource':
  - Status code: 404 for https://rpm.nodesource.com/pub_20.x/el/8/x86_64/repodata/a99dce4c8da2f13c7ee39f93913578ae15cbceb9-primary.xml.gz (IP: 193.246.48.56)

For me it seems that the file names under
https://rpm.nodesource.com/pub_20.x/el/8/x86_64/repodata/

do not match the descriptions in the repomd.xml file under the same url. 
The setup script rpm.nodesource.com/setup_20.x works fine by the way. The error appears if it tries to use the repo and download the rpm package with a wrong name.

The same works without issues for Node version 16.x (there the informations in repomd.xml and the file names do match)

**Distribution Information:**
 - OS: redhat-release-8.8-0.8.el8.x86_64
 - Version RHEL 8.8

**Node Version:**
 - Node: 20.x

**To Reproduce**
under RHEL 8.8 do the installation instructions:
curl -sL https://rpm.nodesource.com/setup_20.x | sudo bash - && sudo yum -y install nodejs

![setup_with_20 x](https://github.com/nodesource/distributions/assets/139950311/7e1d3329-ae70-42fc-997b-cac94941d762)

For Node 16.x it works fine
curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash - && sudo yum -y install nodejs

**Expected behavior**
I would expect that the rpm package would be found and installed by yum / dnf as it does for 16.x

**Screenshots**

**Additional context**
As I said above I think its a mismatch between repomd.xml and the file names under https://rpm.nodesource.com/pub_20.x/el/8/x86_64/repodata/
Thanks for any hint / workaround 
Kind regards
Bjoern

**Comment by lexterwee** [comment]
I am experiencing the same exact problem as bjfi. Only for a different version, pub_18.x for EL9;
The URLS mentioned in 
https://rpm.nodesource.com/pub_18.x/el/9/x86_64/repodata/repomd.xml
do not match the files in 
https://rpm.nodesource.com/pub_18.x/el/9/x86_64/repodata/

**Comment by funjay** [comment]
same issue here
there repomd content for primary is not found in the repodata directory

`<data type="primary">
<checksum type="sha">a2650f8a6d735e015127aa01b60ae47ee5d5ff89</checksum>
<open-checksum type="sha">7f70c16bd9b74c6560ccaac16737273781a2e349</open-checksum>
<location href="repodata/a2650f8a6d735e015127aa01b60ae47ee5d5ff89-primary.xml.gz"/>
<timestamp>1687448431</timestamp>
<size>3430</size>
<open-size>48307</open-size>
</data>`


there is no file repodata/a2650f8a6d735e015127aa01b60ae47ee5d5ff89-primary.xml.gz but repodata/55b4b3a8c157986c61cfb8d08ba0124348d7d1eb-primary.xml.gz

**Comment by riosje** [comment]
Hi guys we've purged our CDN and the issue should be solver.
in case you have troubles with yum you should be ok running `yum clean all`

**Comment by bjfi** [comment]
works for me (rhel8.8 nodejs 20). Thanks for fixing it
