### ISSUE TITLE
Ubuntu 15.10 Wily Werewolf support

### ISSUE THREAD

**Issue by drzel** [nodesource/distributions#161]
When installing on Lubuntu 15.10 I get the following error:

Your distribution, identified as "wily", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
Most likely this: https://github.com/nodesource/distributions/issues/129#issuecomment-150382619

Just updated the docs accordingly.
