### ISSUE TITLE
[DISTRIBUTION] Support for distribution focal

### ISSUE THREAD

**Issue by post-avantika** [nodesource/distributions#1610]
**Distribution information:**
 - OS: Ubuntu 
 - Distribution Type: RPM/DEB
 - Version:. 20.04
 -

![Screenshot from 2023-07-25 10-02-20](https://github.com/nodesource/distributions/assets/115720357/aebc295c-b738-41c9-ab46-54a8d43eb73b)

**Comment by JesusPaz** [comment]
This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).
