### ISSUE TITLE
[DISTRIBUTION] Support for LINUX MINT 21.2 "VICTORIA"

### ISSUE THREAD

**Issue by arizzen** [nodesource/distributions#1612]
**Describe the distribution information:**
 - OS: LINUX MINT 21.2 "VICTORIA"
 - Distribution Type: DEB
 - 
## Your distribution, identified as "victoria", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

![NODE](https://github.com/nodesource/distributions/assets/65240295/89fc0432-6303-4ca3-8dae-58ff8a456edf)

**Comment by Skinner927** [comment]
Since Mint 21.2 Victoria is based on Ubuntu Jammy, you can, as a workaround, use the Jammy repo without issue.

contents of `/etc/apt/sources.list.d/nodesource.list`. Replace your desired node version as appropriate (yes the trailing `.x` is literal). 

```
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x jammy main
deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x jammy main
```

**Comment by JesusPaz** [comment]
This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).

**Comment by unclehowell** [comment]
> This issue is resolved with our new repository. More information can be found [here](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository).

Wow dude, this links to a blank page
