### ISSUE TITLE
[ERROR] Node.js 16 on Redhat 7 Installation fail

### ISSUE THREAD

**Issue by phoenix741** [nodesource/distributions#1616]
**Describe your bug**
When i made a yum update i have the following error :

Failure talking to yum: failure: repodata/43c58a5f03fc0599eebe27e35839e85ecc56a9f6-primary.sqlite.bz2 from nodesource

When i look in the file https://rpm.nodesource.com/pub_16.x/el/7/x86_64/repodata/repomd.xml, i see this line : 

```xml
<data type="primary_db">
<checksum type="sha">43c58a5f03fc0599eebe27e35839e85ecc56a9f6</checksum>
<open-checksum type="sha">97301804b93c3e18686d724971fde16c48f44d2b</open-checksum>
<location href="repodata/43c58a5f03fc0599eebe27e35839e85ecc56a9f6-primary.sqlite.bz2"/>
<timestamp>1687382440</timestamp>
<database_version>10</database_version>
<size>60804</size>
<open-size>520192</open-size>
</data>
```

But if i look in the directory the file should be : https://rpm.nodesource.com/pub_16.x/el/7/x86_64/repodata/b3b905260193b72a6689066fcda5148dc8b9f2c5-primary.sqlite.bz2 

We don't have the good hash string.

**Distribution Information:**
 - OS: Amazon Linux 2 (Redhat 7)
 - Version: Amazon Linux 2 / Redha 7 
 - AMI ID : ami-0b5c00c0109ecef42

**Node Version:**
 - Node: 16.x

**To Reproduce**
1. Start an amazon linux 2 
2. Install the nodesource repository
3. yum update

**Expected behavior**
The file repodata.xml should contains the good hash (or the missing file shoud be present)

**Comment by riosje** [comment]
it seems to be a cache issue.
We're trying to purge our cache and it should be fine in a while.

**Comment by phoenix741** [comment]
The problem is resolved. That is perfect. Thanks.
