### ISSUE TITLE
[ERROR] Node.js 16 aarch64 not signed error in AL2 (el7-aarch64)

### ISSUE THREAD

**Issue by krk** [nodesource/distributions#1617]
**Describe your bug**

**Distribution Information:**
 - OS: amazonlinux
 - Version 2

**Node Version:**
 - Node: `nodejs-16.20.2-1nodesource.aarch64.rpm`

**To Reproduce**
1. On an aarch64 machine, build the Dockerfile attached below.
2. `yum install` fails with:
  ```
  Package nodejs-16.20.2-1nodesource.aarch64.rpm is not signed
  The command '/bin/sh -c yum install -y nodejs' returned a non-zero code: 1
  ```

**Expected behavior**
`yum install` succeeds.

**Dockerfile**
```
FROM public.ecr.aws/amazonlinux/amazonlinux:2

RUN curl -sL https://rpm.nodesource.com/setup_16.x | bash -

RUN yum install -y nodejs
```

**Comment by squaredx** [comment]
We're experiencing the same issue with installing Node 16 on Amazon Linux 2 (aarch64)

**Comment by riosje** [comment]
Hi guys for some reason the signing step failed for the aarch64 packages.
I already signed those and purged the cache, and everything looks ok now.
![image](https://github.com/nodesource/distributions/assets/55195249/7a8cf600-4ed1-448a-b7c4-b106236ea051)

**Comment by squaredx** [comment]
Thank you! The fix appears to be working for us 😊
