### ISSUE TITLE
[ERROR] Package node-v18.13.0-linux-x64.tar.gz gives HTTP 500

### ISSUE THREAD

**Issue by anderius** [nodesource/distributions#1620]
When I try to download from https://nodejs.org/dist/v18.13.0/node-v18.13.0-linux-x64.tar.gz, I get 500.

This is the only file I have found that gives that error, for example https://nodejs.org/dist/v18.13.0/node-v18.13.0-linux-x64.tar.xz works.

**Comment by anderius** [comment]
Maybe it is a cloudfare caching issue, as https://github.com/nodejs/nodejs.org/issues/5149. The direct link https://direct.nodejs.org/dist/v18.13.0/node-v18.13.0-linux-x64.tar.gz is working (but I should not use that address).

**Comment by riosje** [comment]
Hi @anderius we don't manage the nodejs.org distributions server.
We do for rpm.nodesource.com and deb.nodesource.com
