### ISSUE TITLE
 error: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL: import read failed(2

### ISSUE THREAD

**Issue by haata** [nodesource/distributions#1621]
Occasionally we see 404s trying to grab the signing key from rpm.nodesource.com. Are there alternate mirrors for nodesource that we can retry on? 

```bash
17:17:15 	 [1;31m2023-08-15T17:15:11-07:00: ==> amazon-ebs.vcdr-aws: + sudo rpm --import [https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL[0m](https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL%1B[0m)
17:17:15 	 [1;31m2023-08-15T17:15:42-07:00: ==> amazon-ebs.vcdr-aws: curl: (22) The requested URL returned error: 522[0m
17:17:15 	 [1;31m2023-08-15T17:15:42-07:00: ==> amazon-ebs.vcdr-aws: error: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL: import read failed(2).[0m
```

**Distribution Information:**
 - OS: Amazon Linux 2
 - ami-07d59d159373b8030

**Node Version:**
 - Node: 12.22.7

**Additional context**
This is part of our CI/CD on AWS so we're looking to improve the reliability of generating a full image.

We had a similar issue back in Feb as well.
```bash
2023/02/13 03:09:27 ui error: [1;31m2023-02-13T03:09:27-08:00: ==> amazon-ebs.vcdr-aws: + sudo rpm --import https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL[0m
2023/02/13 03:09:28 ui error: [1;31m2023-02-13T03:09:28-08:00: ==> amazon-ebs.vcdr-aws: curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error[0m
2023/02/13 03:09:28 packer-builder-amazon-ebs plugin: [ERROR] Remote command exited with '1': chmod +x /tmp/script_9773.sh; PACKER_BUILDER_TYPE='amazon-ebs' PACKER_BUILD_NAME='vcdr-aws'  /tmp/script_9773.sh
2023/02/13 03:09:28 packer-builder-amazon-ebs plugin: [INFO] RPC endpoint: Communicator ended with: 1
```

**Comment by riosje** [comment]
Hi @haata, We had a small outage some hours ago due to a CDN vendor migration, right now all the artifacts are available.
We aim to provide a high percentage of availability, but there are external factors that we can't manage like vendor issues, even thus we barely have outages of the service.

Can you confirm if this issue is still happening?
I've just tested it without problem
![image](https://github.com/nodesource/distributions/assets/55195249/6b57c550-f066-4f02-9c8d-c57fa137eccf)

**Comment by haata** [comment]
Yes, right now it's fine.

The whole point of having mirrors is to work around the external factors (datacenter is down).
Are there any notifications when migrations/server work is going to happen?

My problem is I have hundreds of engineers breathing down my neck asking me why a build is broken and why retries don't work in the moment. I can possibly setup a mirror, but I'm not sure what would be involved.

**Comment by riosje** [comment]
yeah, completely understand you.
If you want to have a local mirror you can implement it with `createrepo_c` and `reposync`

At this point everything is ok from our side and we don't expect to have more issues.
let us know if there is something else we can help.
