### ISSUE TITLE
[ERROR] Node.js 16.20.2 on Amazon Linux 2023 Installation fails because of missing signature

### ISSUE THREAD

**Issue by simonhaenisch** [nodesource/distributions#1623]
**Describe your bug**

```
Package nodejs-16.20.2-1nodesource.x86_64.rpm is not signed

Error: GPG check FAILED
```

Works with `16.20.1`: https://rpm.nodesource.com/pub_16.x/al/2023/x86_64/nodejs-16.20.1-1nodesource.x86_64.rpm
Fails with `16.20.2`: https://rpm.nodesource.com/pub_16.x/al/2023/x86_64/nodejs-16.20.2-1nodesource.x86_64.rpm

**Distribution Information:**
 - OS: Amazon Linux
 - Version: 2023

**Node Version:**
 - Node: 16.20.2

**To Reproduce**

I have a `nodejs.repo` file like this:

```ini
[nodejs-16]
name=nodejs-16
baseurl=http://rpm.nodesource.com/pub_16.x/al/2023/$basearch/
failovermethod=priority
enabled=1
repo_gpgcheck=0
gpgkey=http://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
gpgcheck=1
```

And a `Dockerfile` like this:

```dockerfile
FROM amazonlinux:2023.1.20230725.0

COPY nodejs.repo .

RUN dnf install -y dnf-plugins-core \
    && dnf config-manager --add-repo nodejs.repo \
    && dnf config-manager --enable nodejs-16 \
    && dnf install -y nodejs-16.20.2
```

With a `docker build .` I get the above error "is not signed".

**Expected behavior**

The signature is there and can be verified.

**Comment by riosje** [comment]
Hi @simonhaenisch sorry for the inconvenience.
The signature has been fixed.
