### ISSUE TITLE
[ERROR] Node.js 18 on Debian 11 Installation fail

### ISSUE THREAD

**Issue by pietryszak** [nodesource/distributions#1630]
**Describe your bug**
When I try install Node with new instruction I have a error:
```
gpg: can't create '/etc/apt/keyrings/nodesource.gpg': No such file or directory
gpg: no valid OpenPGP data found.
gpg: dearmoring failed: No such file or directory

(23) Failed writing body
```
**Distribution Information:**
 - OS: Debian
 - Version: 11

**Node Version:**
 - Node: Node.js v18

**To Reproduce**
1. Execute `sudo apt-get update
sudo apt-get install -y ca-certificates curl gnupg
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg`
2. The problem shown in the image

**Expected behavior**
Succesfull installation

**Screenshots**
![264168400-2968ced0-dae7-4b6d-b7a8-688f0d113f7c](https://github.com/nodesource/distributions/assets/45850093/c3497858-6159-4c75-a49e-982b17a55bb6)

**Comment by JesusPaz** [comment]
can you validate if the directory exists? `/etc/apt/keyrings/`
If not, run this
`mkdir -p /etc/apt/keyrings/`

**Comment by pietryszak** [comment]
> can you validate if the directory exists? `/etc/apt/keyrings/` If not, run this `mkdir -p /etc/apt/keyrings/`

By default in new installation of Debian 11 folder `/etc/apt/keyrings/` not exsist
![image](https://github.com/nodesource/distributions/assets/45850093/527ef16b-c9de-421c-9e90-55c79eabf27e)

when i use `sudo mkdir -p /etc/apt/keyrings/` then everything works fine.
![image](https://github.com/nodesource/distributions/assets/45850093/8f9b5b29-f125-4a90-90bf-4104fda07ab0)

**Comment by pietryszak** [comment]
@JesusPaz Please update a readme.md with info that folder needs to be created.
Thank you for help :)
