### ISSUE TITLE
[ERROR] Node.js 16.11.1 source for Debian not available

### ISSUE THREAD

**Issue by jcampalo** [nodesource/distributions#1631]
**Describe your bug**
For some reason the node 16.11.1 binary is no longer available in the following URL:

https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.11.1-1nodesource1_arm64.deb

But it works for older and newer versions like:

https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.11.0-1nodesource1_arm64.deb
https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.12.0-1nodesource1_arm64.deb

**Distribution Information:**
 - OS: Debian
 - Version: Any

**Node Version:**
 - Node: 16.11.1

**To Reproduce**
1. Go to https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.11.1-1nodesource1_arm64.deb
2. The link does not work

**Expected behavior**
Being able to download the binary.

**Comment by Rheeseyb** [comment]
We're seeing the exact same issue with `nodejs_16.18.1-deb-1nodesource1_amd64.deb`

**Comment by JesusPaz** [comment]
Must be a migration issue. The packages are not in our repo, I will regenerate them. To access them when using the repo directly, see this documentation on [how to migrate](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository). The new version of the repo allows you to easily install the [version of node.js you need](https://github.com/nodesource/distributions/wiki/How-to-select-the-Node.js-version-to-install).

**Comment by Rheeseyb** [comment]
Thank you for the quick turnaround @JesusPaz! I've migrated, and after a little wait I'm now seeing 16.18.1 in the version list 👍

**Comment by jcampalo** [comment]
Thanks for your fast response @JesusPaz, everything went back to normal with 16.11.1

**Comment by giladshanan** [comment]
@JesusPaz I'm seeing a similar issue with: 
https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb

**Comment by riosje** [comment]
Hi @giladshanan you already migrated to the new repo?
https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository

**Comment by giladshanan** [comment]
@riosje not yet, I will give that a shot

**Comment by eburton** [comment]
Also seeing the same issue with 16.20.2 as mentioned above. Is there any plan to correct this as with 16.11.1 and 16.18.1?

We have a number of builds that are failing as a result, and while we will be migrating to the new repository as soon as possible, this will take some time as we have a number of projects to apply the change to!

**Comment by christoph-kluge** [comment]
> To access them when using the repo directly, see this documentation on [how to migrate](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository). The new version of the repo allows you to easily install the [version of node.js you need](https://github.com/nodesource/distributions/wiki/How-to-select-the-Node.js-version-to-install).

Migration went pretty smooth! 👍

**Comment by alexjacobsCDS** [comment]
Following these instructions im able to install node, but it does not appear to install npm?  (also its showing node v10.x ??)
```
root@4365f171dde8:/# node -v
v10.19.0
root@4365f171dde8:/# npm -v
bash: npm: command not found

```

Anybody else seeing this issue?

**Comment by riosje** [comment]
Hi @alexjacobsCDS I think you've installed the wrong package.
are you trying to install Node10?
I have not the same issue with the current LTS

```
root@d8091eb59347:/# node -v
v18.17.1
root@d8091eb59347:/# npm -v
9.6.7
```

**Comment by alexjacobsCDS** [comment]
Here's an example.  This installs node v10.19.0

```
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND noninteractive

ENV NODE_MAJOR='16'


RUN apt-get update --fix-missing && apt-get install -y curl ca-certificates gnupg
RUN mkdir /etc/apt/keyrings/ && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get install -y git nodejs
```

**Comment by derekmckinnon** [comment]
@alexjacobsCDS you are forgetting the additional `apt-get update` after adding the new source. Your apt cache is stale and only has the default crappy old Node version from some other source.

**Comment by JesusPaz** [comment]
@eburton 16.20.2 is available, you need to migrate to the new repo
https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-1nodesource1_amd64.deb

**Comment by llhhaa** [comment]
@pierre-heap When trying to migrate to the new repository, we get the `Mirror sync in progress?` error as well.

**Comment by JesusPaz** [comment]
Sorry folks, the following node versions were missing from the repo:
- 16.4.2
- 16.13.0
- 16.15.0
- 16.18.0

I added them to the repo and deleted the cache, sorry for the inconvenience.

**Comment by jcollins-gc** [comment]
Hi there.

I'm attempting to change our build from using
https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.15.0-deb-1nodesource1_amd64.deb
to using
https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.15.0-1nodesource1_amd64.deb

The SHA256 checksums on these two packages are different, however.  Is that something I should be expecting, and what would be the reason?
