### ISSUE TITLE
[ERROR] Node.js 16.20.2 on Debian stretch Installation Fails

### ISSUE THREAD

**Issue by Shintaro-s-b** [nodesource/distributions#1637]
**Describe your bug**
build fail with invalid size.

**Distribution Information:**
 - OS: [Debian]
 - Version [stretch]

**Node Version:**
 - Node: [16.20.2]

**To Reproduce**
1. Execute apt-get update && apt-get install -y npm

**Expected behavior**
Download the package correctly.

**Additional context**
```
Err:1 http://deb.nodesource.com/node_16.x stretch/main amd64 nodejs amd64 16.20.2-1nodesource1
  Writing more data than expected (27211240 > 27210210) [IP: 104.22.4.26 80]
  Hashes of expected file:
   - SHA256:80730cbf61c72b9cf55435cdf8bef44a865cd797bdf4b62b7e3a9151568a0a17
   - SHA1:f3ce40f55d97d4582eed117e4d26fdaa09d46a32 [weak]
   - MD5Sum:94cdd9c58e730374a1cf2c818e8ecedb [weak]
   - Filesize:27210210 [weak]
E: Failed to fetch http://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-1nodesource1_amd64.deb  Writing more data than expected (27211240 > 27210210) [IP: 104.22.4.26 80]
   Hashes of expected file:
    - SHA256:80730cbf61c72b9cf55435cdf8bef44a865cd797bdf4b62b7e3a9151568a0a17
    - SHA1:f3ce40f55d97d4582eed117e4d26fdaa09d46a32 [weak]
    - MD5Sum:94cdd9c58e730374a1cf2c818e8ecedb [weak]
    - Filesize:27210210 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 100
```

**Comment by Shintaro-s-b** [comment]
https://github.com/nodesource/distributions/issues/1635

same error occured with stretch

**Comment by mbarrs** [comment]
Had the same issue with Strech which started same time as you :( 
From what I can tell they've changed install instructions so something might have changed behind the scenes [mentioned in the docs](https://github.com/nodesource/distributions#new-update-%EF%B8%8F) 

I followed the updated instructions [here](https://git.lab.smartsheet.com/team-solutions/smartsheet_datamesh/-/pipelines/1540830) and that seemed to fix the issue. 


Note: if you get `The method driver /usr/lib/apt/methods/http could not be found` error you might need to add `apt-transpot-https` package. [Link to issue/resolution](https://askubuntu.com/questions/165676/how-do-i-fix-a-e-the-method-driver-usr-lib-apt-methods-http-could-not-be-foun)

**Comment by Shintaro-s-b** [comment]
Thank you, it solved the problem in my environment!
