### ISSUE TITLE
[ERROR]  Node.js [Manual Installation] on Debian and Ubuntu based Installation fail

### ISSUE THREAD

**Issue by michaelmdrs** [nodesource/distributions#1642]
**Describe your bug**
When clicking on the link: [Manual installation](https://github.com/nodesource/distributions#manual-installation) it does not direct to the manual installation with this the user has difficulties to continue the manual installation.

**Distribution Information:**
 - OS: [e.g. LinuxMint]
 - Version [e.g. Victoria (21.2)]

**Node Version:**
 - Node: [e.g. Node.js v12.22.9:]

**Expected behavior**
sudo apt-get install nodejs npm

**Screenshots**
![image](https://github.com/nodesource/distributions/assets/64491132/c8ad4b4a-c6b3-4935-980b-0c3390d34ae1)

**Additional context**
- sudo pacman -S nodejs npm

- sudo yum install epel-release
- sudo yum install nodejs npm

- sudo dnf install nodejs npm

**Comment by JesusPaz** [comment]
We no longer maintain the scripts. That's why everything is considered a manual installation. Here is the link to the guide https://github.com/nodesource/distributions#installation-instructions
