### ISSUE TITLE
[ERROR] Trying to install node 16 but installs 18

### ISSUE THREAD

**Issue by rinarakaki** [nodesource/distributions#1645]
**Describe your bug**

**Distribution Information:**
 - OS: Debian
 - Version: 12
  - Docker image

**Node Version:**

**To Reproduce**
1. `apt-get update`
2. `apt-get install -y ca-certificates curl gnupg`
3. `mkdir -p /etc/apt/keyrings`
4. `curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg`
5. `NODE_MAJOR=16`
6. `echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list`
7. `apt update`
8. `install nodejs -y`

**Expected behavior**
Installs node 16.

**Screenshots**

**Additional context**
Add any other context about the problem here, specify if already has another NodeJS version or if trying to re-install the current version.

**Comment by JesusPaz** [comment]
Can you send us your logs? We need more information about what's happening

**Comment by hackel** [comment]
I'm experiencing a similar, possibly related issue.  Trying to install Node 16 (in a docker container build script), and it does download the nodejs 16 package, but then I get an npm error indicating that it requires node 18 or 20.

![image](https://github.com/nodesource/distributions/assets/583677/04d1bc38-2e56-4936-944e-446ed1d4df7c)

**Comment by saimon-moore** [comment]
Same here. Trying to install v18 but installs v20

**Comment by andtherand** [comment]
I am having the same issue in a Docker image building process. The required version is 16 but get 18 as others have stated.

<img width="1203" alt="Wrong node version" src="https://github.com/nodesource/distributions/assets/1202405/78a54ece-65f2-4881-95b5-27de88fa1059">

**Comment by andtherand** [comment]
As @o1y mentions in [here](https://github.com/nodesource/distributions/issues/1601#issuecomment-1701384841),
the version difference can be omitted by pinning the preference:

```docker
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg; \
  echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list; \
  echo "Package: nodejs" >> /etc/apt/preferences.d/preferences; \
  echo "Pin: origin deb.nodesource.com" >> /etc/apt/preferences.d/preferences; \
  echo "Pin-Priority: 1001" >> /etc/apt/preferences.d/preferences; \
  apt-get update -qq; \
  apt-get install -yq --no-install-recommends nodejs;
```

**Comment by diegocam** [comment]
This is still a problem

**Comment by brent20** [comment]
Bump. Still an issue.

**Comment by Nardol** [comment]
As @andtherand says, pining is the solution.
I don't know if it is possible to specify pining at the repository level, IIRC it is the case for Debian backports repository.

**Comment by JesusPaz** [comment]
Thanks for your contribution, this issue is resolved by https://github.com/nodesource/distributions/pull/1739

**Comment by riosje** [comment]
This issue was solved with the current implementation.
Using the installation scripts will create the pin-priority by default

**Comment by sparrowt** [comment]
If you are not using the official install scripts, adding this before you call `apt update` should do the trick:
```
# Pin priority so that it doesn't try to get node from another source, potentially getting a different version
echo "Package: nodejs" | tee /etc/apt/preferences.d/nodejs > /dev/null
echo "Pin: origin deb.nodesource.com" | tee -a /etc/apt/preferences.d/nodejs > /dev/null
echo "Pin-Priority: 600" | tee -a /etc/apt/preferences.d/nodejs > /dev/null
```
so that it uses the major version that you specified earlier (in the deb.nodesource.com path) rather than finding a newer version from some other OS repository e.g. debian.
