### ISSUE TITLE
How to install "lts" or "current" on Debian, with the new DEB packages instead of setup_XX.x?

### ISSUE THREAD

**Issue by gremo** [nodesource/distributions#1648]
With the "old" setup_XX.x you can install `lts` (https://deb.nodesource.com/setup_lts.x) and `current` node version (https://deb.nodesource.com/setup_current.x).

With the new DEB packages, it won't work. Supported version are [listed here](https://github.com/nodesource/distributions#debian-versions) and keywords `lts` and `current` aren't listed.

Is there a way to install `lts` and `current` with the new method?

**Comment by JesusPaz** [comment]
The current version is v20 and LTS is v18. You only need to select the version you want to install.
![image](https://github.com/nodesource/distributions/assets/27715376/8a5f148a-abf8-4d69-871a-e998d84c80d6)

for more information: https://nodejs.dev/en/about/releases/

**Comment by gremo** [comment]
@JesusPaz sorry but the question was about installing the correspondig lts/current version, without actually specify the version number directly.

**Comment by JesusPaz** [comment]
At the moment, this is not possible. We will only keep the versions that are published by node.js. It is a bit complicated to create and maintain an additional repository. Also, the current version only changes to LTS once a year, you can have that version in a repository or server and consume that variable in your dockerfile.
