### ISSUE TITLE
RPMs for RHEL

### ISSUE THREAD

**Issue by TinajaLabs** [nodesource/distributions#165]
Trying to find the actual RPMs for nodejs, npm to install offline (via puppet) from our local yum repo.

It looks like the curl setup script requires access to the internet and online epel repo.

How does one install nodejs/npm without access to internet?  I think I just need the RPMs installed into my local yum repo.

Ultimately, want to install node-red which requires nodejs.

Thanks for any advice,
Chris.

**Comment by JoshuaPK** [comment]
Hi Chris-

I examined the script and found that I could download RPM's from here:

https://rpm.nodesource.com/pub_5.x/

They appear to somewhat work on CentOS, except for the fact that npm is not configured correctly.  It is putting all the node_modules under /etc/yum.repos.d...

**Comment by retrohacker** [comment]
Yes, the rpm files live in in those directories. They follow the convention `pub_[VERSION]`, I.E. `pub_0.12` `pub_4.x`
