### ISSUE TITLE
[DISTRIBUTION] Support for distribution AL1

### ISSUE THREAD

**Issue by tumes** [nodesource/distributions#1652]
**Describe the distribution information:**
 - OS: Amazon Linux 1
 - Distribution Type: RPM
 - Version 2018.03
 - Other info if needed

I am in charge of a legacy project that, unfortunately, relies on the setup script. Specifically for node 11, however, I'm pretty sure 16 would be totally fine. This is what the error in the script spits out when I attempt to deploy as my distribution package name: system-release-2018.03-0.2.noarch.

I've attempted the various other install methods from the wiki without luck (they either error out or seemingly hang). Totally understand if I'm SOL, I'll keep at it, but I figured this was worth a shot.

**Comment by riosje** [comment]
Hi @tumes I was able to install Node16 following the current [installation instructions on the README](https://github.com/nodesource/distributions#nodejs-v16x)

I performed the test using Docker

```SHELL
docker run -it --rm amazonlinux:1 bash
yum install https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1
```

So if you can upgrade to 16 you will be fine, also is important to mention that Node16 will lost support soon, but upgrading from 11 to 16 you will get important security fixes.

### If you can't upgrade from Node11 to Node16
Install it manually downloading the RPM.

```shell
curl -LO https://rpm.nodesource.com/pub_11.x/fc/28/x86_64/nodejs-11.15.0-1nodesource.x86_64.rpm
yum install nodejs-11.15.0-1nodesource.x86_64.rpm -y
```
I've tested this and it works
![image](https://github.com/nodesource/distributions/assets/55195249/c2908945-062e-469d-b235-183acfc91b21)


is important to mention we won't give any kind of support to those old scripts.
