### ISSUE TITLE
[ERROR] Node.js 20.x on AlmaLinux9.2 Installation fail

### ISSUE THREAD

**Issue by IsraPerez98** [nodesource/distributions#1653]
**Describe your bug**
Installation on AlmaLinux9.2 fails due to this error:
Signature not supported. Hash algorithm SHA1 not available.

It seems to be related to RHEL 9 deprecating SHA-1 as stated on this post:
https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9

**Distribution Information:**
 - OS: AlmaLinux
 - Version 9.2

**Node Version:**
 - Node: Node.js v20.x

**To Reproduce**
1. Run `sudo dnf install https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y`
3. Run `sudo dnf install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1`
4. Installation will fail with `Signature not supported. Hash algorithm SHA1 not available.`

The error also happens if you try to run `sudo rpm --import https://rpm.nodesource.com/gpgkey/nodesource.gpg.key`

**Expected behavior**
The Node.js package getting installed properly.

**Screenshots**
![image](https://github.com/nodesource/distributions/assets/24889578/ead7bc40-a74a-46e4-a075-08addde71733)
![image](https://github.com/nodesource/distributions/assets/24889578/819b0235-c0ba-4431-a997-e3e7d14661b4)

**Additional context**
As stated earlier, this problem seems to be related to [RHEL 9 deprecating support for SHA-1 signatures](https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9), the problem may be present on all RHEL 9 compatible distros such as Rocky Linux.

**Comment by MilesTFox** [comment]
I too am experiencing this, with NodeJS 18.18.0 LTS.

It is the entire repository that is effected, so all packages from nodesource.

I enabled SHA1, did not have to reboot, then re-disabled after installation.

**Comment by jcicerof** [comment]
I am experienced this error when I tried to update from v16 to v18. I was able to install on a stage server (just for test purpose) but this will not accept by Security team when I try to install on Production environment. 

Is there any plan to switch from SHA-1 to SHA-256?

**Comment by NathanielDayLewis** [comment]
I'm also experiencing this when installing on Rocky Linux 9. Would very much prefer not to disable and then re-enable SHA-1

**Comment by jcox10** [comment]
Same problem installing on a UBI9 container.

**Comment by JesusPaz** [comment]
This issue is now resolved, please run the new scripts:
```
curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
yum install -y nodejs
```
