### ISSUE TITLE
Fedora 23 support

### ISSUE THREAD

**Issue by Assada** [nodesource/distributions#166]
```
assada@localhost ~> sudo curl --silent --location https://rpm.nodesource.com/setup | bash -
[sudo] пароль для assada: 

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release
+ uname -m

## Confirming "fc23-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub/fc/23/x86_64/nodesource-release-fc23-1.noarch.rpm'

## Your distribution, identified as "fedora-release-23-1.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

```

http://fedoramagazine.org/fedora-23-released/

**Comment by cultavix** [comment]
+1

**Comment by gtirloni** [comment]
I'd advise against running scripts from the Internet as root.

You can find the package for FC23 here: https://rpm.nodesource.com/pub_4.x/fc/23

**Comment by askmatey** [comment]
@gtirloni exactly

**Comment by askmatey** [comment]
nodesource.repo

```txt
[nodesource]
name=nodesource
baseurl=https://rpm.nodesource.com/pub_5.x/fc/23/x86_64
enabled=1
gpgcheck=1
```

```sh
[batman@cave ~]# dnf install nodejs
```

**Comment by chrislea** [comment]
FC23 is supported for Node versions > 4.2 ([see here for the correct install scripts to run](https://github.com/nodesource/distributions/)).

We've been through the whole "running scripts as root" thing before and it's always been clear that the convenience of letting users get going quickly and easily is worth it. Please not here that

  1. There's nothing binary in the scripts at all, you're free to just grab them and look to see what we're doing.
  2. If you're installing an `rpm` as root, you're effectively letting us run scripts if we choose to anyway.

That said, it's obviously not in our best interests to intentionally do anything bad to our users, so we don't. :)

**Comment by gtirloni** [comment]
I didn't mean to complain about Nodesource's install script. It was a general piece of unrequested advice and it feels out of place. Sorry. You're totally right about RPM and scripts.

Thanks for providing these packages, they're an welcome improvement over EPEL's packages for us.
