### ISSUE TITLE
[ERROR] Status 403 forbidden when trying to create a mirror of deb.nodesource.com using debmirror

### ISSUE THREAD

**Issue by timur-enet** [nodesource/distributions#1661]
**Describe your bug**
We used to be able to create a local mirror of deb.nodesource.com using the tool "debmirror". For a while now this has stopped working and instead we receive a status 403 whenever trying to use debmirror. This does not seem to be tied to the IP Address we are using as the problem also occurs when trying to replicate it outside the company network.

**Distribution Information:**
 - OS: Ubuntu
 - Version 20.04 and 22.04 LTS

**Node Version:**
 - Node: node_16.x

**To Reproduce**
We are using the following command to create the local mirror:

```
debmirror -a ${arch} \
              --no-source \
              --rsync-extra=none \
              --progress \
              -h ${server} \
              -s ${section} \
              -d ${release} \
              -r ${inPath} \
              --method=${proto} \
              ${outPath}
```  

Using the following parameters: 

```
arch=i386,amd64
section=main
release=focal
server=deb.nodesource.com
inPath=/node_16.x
proto=https
outPath=~/nodesource/srv/repo/deb/node16-focal
```

**Expected behavior**
This should create a local mirror of the repository

**Screenshots**
This is the output we receive:

```
Mirroring to /home/ENET/timur.debbag/nodesource/srv/repo/deb/node16-focal from https://anonymous@deb.nodesource.com/node_18.x/
Arches: i386,amd64
Dists: focal
Sections: main
Pdiff mode: use
Will clean up after mirroring.
Attempting to get lock ...
Getting meta files ...
[  0%] Getting: dists/focal/Release... 	 #** GET https://deb.nodesource.com/node_18.x/dists/focal/Release ==> 403 Forbidden
Download of dists/focal/Release failed: 403 Forbidden
Errors:
 Download of dists/focal/Release failed: 403 Forbidden
Failed to download some Release, Release.gpg or InRelease files!
```

Please advise.

**Comment by riosje** [comment]
Hi @timur-enet I was looking at the `debmirror` docs, it looks like it defaults HTTP basic auth with user "anonymous"
```
-u, --user=remoteusername
Specify the remote user name to use to log into the remote host. Defaults to "anonymous".
```

you should be able to fix this error by disabling the auth our CDN server do not support basic auth, not sure how to disable it with `debmirror`.

If you can't solve it, we have instructions to mirror the repo using `aptly`
https://github.com/nodesource/distributions/wiki/Creating-a-Repository-Mirror:-A-Step%E2%80%90by%E2%80%90Step-Guide#setting-up-a-deb-mirror-

**Comment by GEownt** [comment]
Hi @riosje I was looking at the Code behind debmirror and there is no basic auth with user "anonymous" if we use the "http" method instead of "https".
```  if ($user eq 'anonymous'){
    $url="$download_method://${host}${remoteroot}${file}";
  }
  else {
    $url="$download_method://${user}:${passwd}\@${host}/${remoteroot}${file}";
  }
```
Changing to http still doesn´t solve the problem.
I get the following Output from debmirror where you can see the correct URL´s now

```
Mirroring to /srv/repo/deb/node16-focal from http://deb.nodesource.com/node_16.x/
Arches: i386,amd64
Dists: focal
Sections: main
Pdiff mode: use
Will clean up after mirroring.
Attempting to get lock ...
Getting meta files ...
http://deb.nodesource.com/node_16.x/dists/focal/Release => [  0%] Getting: dists/focal/Release... 	 #** GET http://deb.nodesource.com/node_16.x/dists/focal/Release ==> 403 Forbidden
403 Forbidden
Download of dists/focal/Release failed: 403 Forbidden
Errors:
 Download of dists/focal/Release failed: 403 Forbidden
Failed to download some Release, Release.gpg or InRelease files!
```

Do you have any other idea why we are not able to download from your Repository?
