### ISSUE TITLE
[ERROR] Node.js 16 cannot be installed into amazonlinux on docker 

### ISSUE THREAD

**Issue by rajeshchinnam** [nodesource/distributions#1664]
**Describe your bug**
<html>
<body>

================================================================================
--
742 | ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
743 | ================================================================================
744 |  
745 | SCRIPT DEPRECATION WARNING
746 |  
747 |  
748 | This script, located at https://rpm.nodesource.com/setup_X, used to
749 | install Node.js is deprecated now and will eventually be made inactive.
750 |  
751 | Please visit the NodeSource distributions Github and follow the
752 | instructions to migrate your repo.
753 | https://github.com/nodesource/distributions
754 |  
755 | The NodeSource Node.js Linux distributions GitHub repository contains
756 | information about which versions of Node.js and which Linux distributions
757 | are supported and how to install it.
758 | https://github.com/nodesource/distributions
759 |  
760 |  
761 | SCRIPT DEPRECATION WARNING
762 |  
763 | ================================================================================
764 | ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
765 | ================================================================================
766 |  
767 | TO AVOID THIS WAIT MIGRATE THE SCRIPT
768 | Continuing in 60 seconds (press Ctrl-C to abort) ...
769 |  
770 |  
771 | ## Installing the NodeSource Node.js 16.x repo...
772 |  
773 |  
774 | ## Inspecting system...
775 |  
776 | + uname -m
777 | system-release-2-15.amzn2.x86_64
778 | exec redhat-release
779 | Release package: system-release-2-15.amzn2.x86_64
780 |  
781 | ## Confirming "el2-x86_64" is supported...
782 |  
783 | + curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_16.x/el/2/x86_64/nodesource-release-el2-1.noarch.rpm'
784 |  
785 | ## Your distribution, identified as "system-release-2-15.amzn2.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
786 |  
787 | The command '/bin/sh -c curl -fsSL https://rpm.nodesource.com/setup_16.x \| bash - &&     yum install -y nodejs' returned a non-zero code: 1

</body>
</html>

**Distribution Information:**
 - OS: AWS Linux Ubuntu
 - Version 16
 - Docker image , AWS LINUX

**Node Version:**
 - Node: Node.js v16

**To Reproduce**
1. Execute Ubuntu Docker Image 
2. Execute Installation instructions for Node.js v16

**Expected behavior**
Node.js v16 should be installed 

**Screenshots**

**Additional context**
Add any other context about the problem here, specify if already has another NodeJS version or if trying to re-install the current version.

**Comment by vasu-winzo** [comment]
I replaced the setup curl with the instructions here and it worked:
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-up-node-on-ec2-instance.html

**Comment by bo156** [comment]
You can also try to use this commands from nodesource documentation
https://github.com/nodesource/distributions#amazon-linux-versions

**Comment by mgrozinski** [comment]
Having the same issue.  I'm sure there are other methods to install but we've been using the setup_x method over 15 times/week for quite some time and they all started failing today.

In the above result, as well as my own output, it is returning system version as system-release-2-15.amzn2.x86_64, which i do not believe exists.  as a result, the script is trying to install the rpm from [2-1] (https://rpm.nodesource.com/pub_16.x/el/2/x86_64/nodesource-release-el2-1.noarch.rpm), an endpoint which does not exist.  it is supposed to return system-release-2-14 based on #rpm -q --whatprovides redhat-release , which the script then would point to https://rpm.nodesource.com/pub_16.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm , an endpoint that still works.  It was returning that endpoint yesterday for us, as far as I can tell.

```
PKG_LIST=(
  "redhat-release"
  "centos-release"
  "cloudlinux-release"
  "sl-release"
  "fedora-release"
  "system-release"
  )

for PKG in "${PKG_LIST[@]}"; do
  rpm -q --whatprovides ${PKG}
  if [ $? -eq 0 ]; then
    echo "exec ${PKG}" 
    DISTRO_PKG=$(rpm -q --whatprovides ${PKG})
    echo "Release package: ""${DISTRO_PKG}"
    break
  fi
done
``` 

```
if [[ $DISTRO_PKG =~ ^system-release-2-14 ]]; then

  # Amazon Linux, for 2014.* use el7, older versions are unknown, perhaps el6
  DIST_VERSION=7
``` 


```
RELEASE_URL_VERSION_STRING="${DIST_TYPE}${DIST_VERSION}"
RELEASE_URL="\
https://rpm.nodesource.com/${NODEREPO}/\
${DIST_TYPE}/\
${DIST_VERSION}/\
${DIST_ARCH}/\
nodesource-release-${RELEASE_URL_VERSION_STRING}-1.noarch.rpm"
```

**Comment by sa-snagamine** [comment]
This solution may help
https://github.com/nodesource/distributions/issues/1663#issuecomment-1730755991

**Comment by riosje** [comment]
Hello guys, please do not use any more the installation scripts.
Just follow the instructions on the readme
https://github.com/nodesource/distributions#nodejs-v16x

```
sudo yum install https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
sudo yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1
```

**Comment by GrahamCampbell** [comment]
This fails for node 18.

<img width="1170" alt="image" src="https://github.com/nodesource/distributions/assets/2829600/8f993b91-3f38-4ac3-9810-12ba1d398fcc">

**Comment by riosje** [comment]
@GrahamCampbell you can't install node 18 on amazon linux 2
https://github.com/nodesource/distributions#amazon-linux-versions

Amazon linux 2 has `glibc2.26` and Node 18 requires at least `glibc2.28` you may find an unofficial release which works with amazon linux 2.
https://unofficial-builds.nodejs.org/

**Comment by GrahamCampbell** [comment]
Thanks for confirming. I figured that was the case, so I guess Amazon have made some code changes to node 18 to get it to build on AL2 for their node18 lambda environment.

**Comment by chrislea** [comment]
@GrahamCampbell it has been **many** years since I've had to deal with any of this, but, historically when this came up (too-old versions of `glibc`) the workarounds were changes to the compilers that made things work. As opposed to changes to node itself. Just FYI.
