### ISSUE TITLE
[ERROR] Node.js XX on UbuntuXX Installation fail

### ISSUE THREAD

**Issue by ivose** [nodesource/distributions#1665]
How to avoid curl -sL https://deb.nodesource.com/setup_20.x | bash - deprecation warning and installing now. It displays the warning and lets wait a minute despite of the last release.

**Comment by riosje** [comment]
Hi @ivose we've migrated our repos and those scripts are not maintained anymore.

We invite you to move away from those installation scripts and just follow our new installation instructions
[Debian installation-instructions](https://github.com/nodesource/distributions#installation-instructions)
