### ISSUE TITLE
NodeJS on Ubuntu 15.10 is Not currently Supported

### ISSUE THREAD

**Issue by puguhrismadi** [nodesource/distributions#167]
Please fix it

**Comment by justinabrahms** [comment]
I got this as well. The issue is that 0.12 isn't supported on ubuntu's 15.10.

**Comment by SylvainCorlay** [comment]
Same issue, the latest ubuntu release does not seem to be supported.

**Comment by TomBaxter** [comment]
+1

**Comment by vaughany** [comment]
Same here. :)

**Comment by cyraid** [comment]
I'm also getting this message..

**Comment by chrislea** [comment]
All: what I've been told from some of the core devs is that 0.12 has a lot of issues internally that are never really going to be fixed. It's in maintenance mode, meaning it's only ever going to see an update if there's some super serious security issue.

Basically, move to 4.x or 5.x.

@TomBaxter the dependencies for 0.12.x and 4.x are exactly the same. What are the issues you're seeing?

**Comment by cyraid** [comment]
@chrislea do you have a PPA for 4.x or 5.x?

**Comment by TomBaxter** [comment]
@chrislea I ran into several node modules that won't load. Most notably for me was https://github.com/brianmcd/contextify/issues/180#issuecomment-155032021 .

@cyraid Both PPAs are referenced in the README for this github repository.

**Comment by cyraid** [comment]
Ahhh, I used 'setup_dev' before.. That's why, now I'm using 5.x and giving it a shot. Thanks Chris!

**Comment by chrislea** [comment]
@TomBaxter if you are having module issues and you think it's related to how this is packaged, please open a separate issue for that and include specifics about your setup and steps to reproduce so we can check it out. Thanks.
