### ISSUE TITLE
[ERROR] Node.js 18 on AmazonLinux2023 in Docker Installation fail

### ISSUE THREAD

**Issue by leontp587** [nodesource/distributions#1672]
**Describe your bug**
Following the instructions to install Node.js 18 on AmazonLinux2023 fail

**Distribution Information:**
 - OS: Amazon Linux Docker
 - Version 2023

**Node Version:**
 - Node: v18.x

**To Reproduce**
1. docker run -it amazonlinux:2023
2. Inside the docker container, run "yum install https://rpm.nodesource.com/pub_18.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y"
3. Inside the docker container, run "nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1"

**Expected behavior**
Docker is installed

**Actual Behavior**
Error: "nodejs: command not found"

**Comment by riosje** [comment]
Please follow the installation instructions
This command is wrong -> `nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1`

This should install Nodejs
```
yum install https://rpm.nodesource.com/pub_18.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1
```
![image](https://github.com/nodesource/distributions/assets/55195249/794b22bd-ed42-4de3-bfcc-00f06958e8b7)
