### ISSUE TITLE
[ERROR] sudo: yum: command not found

### ISSUE THREAD

**Issue by sliftist** [nodesource/distributions#1673]
**Describe your bug**

```Command 'yum' not found, did you mean:```

I use these scripts to install NodeJS on Ubuntu 20 digital ocean instances, and the "new" script doesn't work (`yum` isn't present on those machines). Is there any compelling reason for me to update my install script to incorporate the "new" script (besides the deprecation warning)?

**Distribution Information:**
 - OS: Ubuntu
 - Version 20

**Node Version:**
 - Node: 18

**To Reproduce**
1. `sudo yum install https://rpm.nodesource.com/pub_18.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y`

**Comment by benlumia007** [comment]
it seems like you got your OS messed up, Ubuntu does not have yum, Ubuntu uses apt.. CentOS uses yum.

**Comment by JesusPaz** [comment]
The `yum` command is specific to Red Hat-based distributions and is not available on Ubuntu, which uses `apt`. The scripts you're referencing are deprecated. Please refer to the official NodeSource installation guide for the correct installation steps. If you can point us to where you found these instructions, we'll notify the responsible party to update them.

**Comment by sliftist** [comment]
Thanks, that was my mistake, I was a bit confused by the recent instruction changes. I seem to recall installing `yum` on ubuntu before, but it looks like it hasn't been supported since `18.04`. Somewhat unrelated, I made a pull request to change the installation instructions a bit: https://github.com/nodesource/distributions/pull/1699 .
