### ISSUE TITLE
apt update prints warning on Ubuntu 22.04

### ISSUE THREAD

**Issue by owocado** [nodesource/distributions#1676]
**Describe your bug**

Hello and greetings,

when I run `sudo apt-get update`, it prints this warning:
```
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://deb.nodesource.com/node_20.x nodistro InRelease' does not seem to provide it (sources.list entry misspelt?)
```
I have opened this issue to understand what it means and whether it is safe to ignore this warning message. If anyone can guide me through this, i would be grateful. Thank you for reading!

**Distribution Information:**
 - OS: Ubuntu
 - Version 22.04 (aarch64)
 - Other info if applicable: oracle cloud vm

**Node Version:**
 - Node: nodejs v20.8.0

**Comment by pomeo** [comment]
You need to delete the line "deb-src" from /etc/apt/sources.list.d/nodesource.list or where you have this entry located. There is no "deb-src" in the instructions, perhaps you have been updated from old versions where it was.
