### ISSUE TITLE
[MISSING] Node.js 18.18.0 on Debian 11 repository

### ISSUE THREAD

**Issue by touchweb-vincent** [nodesource/distributions#1677]
Hello,

First, thank you for your work.

It's not for a bug or a report, just a "hi" about a potential oversight.

Node JS 18.18.0 has been released since 2 weeks and it is not yet release on your repository for Debian 11 (https://deb.nodesource.com/node_18.x bullseye main)

Since it's quite rare that you do not update  your repositories for Debian within a week after a new version of NodeJS, i guess, it's an oversight else we will wait - there is no hurry at all.

Thanks you

Vincent

**Comment by riosje** [comment]
Hi @touchweb-vincent I think you should migrate your repo to our new version.
[This is a how to guide to migrate](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository)

Also take a look into the [Readme](https://github.com/nodesource/distributions/blob/master/README.md) instructions

Here you can see we do have the version `18.18.0` released properly.
```
root@ed5fbe1f2309:/# apt-cache policy nodejs
nodejs:
  Installed: (none)
  Candidate: 18.18.0-1nodesource1
  Version table:
     18.18.0-1nodesource1 500
        500 https://deb.nodesource.com/node_18.x nodistro/main amd64 Packages
```

**Comment by touchweb-vincent** [comment]
Thanks you ! I didn't notice this move. All is OK.
