### ISSUE TITLE
[ERROR] Node.js 20 on Ubuntu 22

### ISSUE THREAD

**Issue by nixrajput** [nodesource/distributions#1680]
Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://deb.nodesource.com/node_20.x nodistro InRelease' doesn't support architecture 'i386'

**Comment by GrahamCampbell** [comment]
This is not a bug. The architecture was intentionally dropped and is not supported. Supported architectures are listed on https://github.com/nodesource/distributions/blob/master/README.md#debian-and-ubuntu-based-distributions.

**Comment by riosje** [comment]
Hi, Highly suggest you to look directly in the following NodeJs site if there is some unofficial build for your arch
https://unofficial-builds.nodejs.org/
