### ISSUE TITLE
[ERROR] Node.js 20 on debian bookworm armv7 fails to run

### ISSUE THREAD

**Issue by martinetd** [nodesource/distributions#1687]
**Describe your bug**
node doesn't run by default because it depends on libatomic1 but doesn't install it. installing it manually fixes it.

**Distribution Information:**
 - OS: debian
 - Version bookworm

**Node Version:**
 - Node:Node.js v20.x

**To Reproduce**
Steps to reproduce the behavior (this requires qemu-user setup to run arm32 binaries, or running on an arm32 machine. podman can be replaced with docker):
```
$ podman run --rm -ti docker.io/arm32v7/debian:bookworm-20230919-slim
# apt update && apt install -y curl ca-certificates gnupg
# curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
  && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" > /etc/apt/sources.list.d/nodesource.list
# apt update && apt install nodejs
...
Setting up nodejs (20.8.0-1nodesource1) ... [success]
# node --version
node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
# ldd /usr/bin/node
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x3f7f7000)
	libatomic.so.1 => not found
	libstdc++.so.6 => /lib/arm-linux-gnueabihf/libstdc++.so.6 (0x3f680000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x3f63f000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x3f600000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x3f5fd000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x3f4e6000)
	/lib/ld-linux-armhf.so.3 (0x40000000)
# apt install libatomic1
# node --version
v20.8.0
```

**Expected behavior**
node should work without manually installing libatomic1 (should be pulled in automatically)

EDIT: fixed copy-paste error on first `node --version` error...
Also, FWIW it used to work with the old setup script (that installs the 'bookworm' dist instead of 'nodistro')

**Comment by JesusPaz** [comment]
Thank you for highlighting this issue. We've identified the missing dependency on `libatomic1` for arm32 on Debian bookworm. We'll add this to our task list and will update you once we have a resolution. Appreciate your patience and understanding.

**Comment by martinetd** [comment]
Thanks for the follow up!

We've just added the dependency manually so it's not a blocker, but I'll check the fix once you report it's done.

**Comment by rajeshisgood** [comment]
I am on armv7l(termux) & trying to install node v18.15.0 .And this arch dosent support libatomic1 , how can fix this issue?

**Comment by PoisonousWisper** [comment]
I'm trying to get Node.js v20 running on MyPassportWirelessPro (also armv7l).
Since Node.js v12 (said here: https://github.com/nodejs/help/issues/2981) nodejs needs libatomic.
Node.js v11 works nice on MyPassportWirelessPro. But I would like to update to the newest version.
Thanks for reading!

**Comment by riosje** [comment]
Hi guys i was able to replicate this behavior using the docker image `arm32v7/debian:12`
As the nodejs devs mention `libatomic1` it's a system library, we can't add that lib package itself to our repo, we may improve our package to make `libatomic1' required and therefore the `apt-get` command will solve that dependency, but is something that we need to validate internally.


To be honest I do not consider this an issue since the package is available to be installed via apt.

You can install the `build-essential` package in the SO


```
docker run -it arm32v7/debian:12 bash
```

```
apt-get update -y
apt-get install build-essential curl -y
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get install -y nodejs
```

I"m closing this issue, since is not a real issue for our distribution solution.

**Comment by martinetd** [comment]
Thanks for having a look!

I don't understand why it's not an issue for the distribution -- the package is part of the distribution and its dependencies can be fixed, so might as well get all the way to it?

Normally I'd expect dpkg-buildpackage or the tool you're using to build the package to pick up library runtime dependencies automatically, so it might be as simple as making the builder run in the right environment.

**Comment by riosje** [comment]
@martinetd I'll reopen this and check if can do something without breaking anything.
I understand your point.

**Comment by riosje** [comment]
This not an issue anymore with the latest versions published we've updated the package dependencies.

Installation instructions:
```SHELL
docker run -it arm32v7/debian:12 bash
apt-get update -y
apt-get install ca-certificates curl -y
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get install -y nodejs
node --version
```
