### ISSUE TITLE
Use nodesource-jessie-backports name instead of jessie 

### ISSUE THREAD

**Issue by arthurlogilab** [nodesource/distributions#169]
Follow up of #114

It is considered good practice to use a different name than the main distro in third party repositories (like backports). That way users can do the following command : 

```
apt-get install -t nodesource-jessie-backports nodejs 
```

instead of having to give a specific version or changing the pinning in their preferences. 

This is a request for all distro names, not only jessie.

**Comment by retrohacker** [comment]
Hi @arthurlogilab,

We've attempted to set up our debian style repos to behave like repos on Launchpad. This is both for practical and historical reasons.

The precedent of using `jessie` as opposed to something more specific was set by Launchpad. Example: `deb http://ppa.launchpad.net/chris-lea/nginx-devel/ubuntu wily main`

We are in the middle of a long process of revamping the infrastructure for these repos. This revamp will give us a lot more flexibility in the features we can offer to package managers. When that transition is complete, we may revisit this convention.
