### ISSUE TITLE
[ERROR] Node.js 20 on Ubuntu22.04 Installation fail

### ISSUE THREAD

**Issue by kush30** [nodesource/distributions#1691]
Unpacking nodejs (20.8.1-1nodesource1) ...
dpkg: error processing archive /var/cache/apt/archives/nodejs_20.8.1-1nodesource1_amd64.deb (--unpack):
 trying to overwrite '/usr/include/node/common.gypi', which is also in package libnode-dev 12.22.9~dfsg-1ubuntu3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_20.8.1-1nodesource1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

 - OS: [e.g. Ubuntu]
 - Version [e.g. focal (22.04)]

 - Node: [e.g. Node.js v20.x:]

**Comment by JesusPaz** [comment]
It seems there's a conflict between the nodejs package from NodeSource and the libnode-dev package. Please uninstall libnode-dev first and then try installing the nodejs package again. We'll add this to our task list to prevent such issues in the future.

**Comment by jsnider3** [comment]
@JesusPaz this solution worked for me with the same issue on WSL. I couldn't reinstall libnode-dev without getting this error:

```
dpkg: error processing archive /var/cache/apt/archives/libnode-dev_12.22.9~dfsg-1ubuntu3.2_amd64.deb (--unpack):
 trying to overwrite '/usr/include/node/common.gypi', which is also in package nodejs 20.5.1-deb-1nodesource1
```

I'm going to leave libnode-dev uninstalled for now and see when something explodes.

**Comment by riosje** [comment]
The solution was uninstall `libnode-dev`

**Comment by NingAnMe** [comment]
> It seems there's a conflict between the nodejs package from NodeSource and the libnode-dev package. Please uninstall libnode-dev first and then try installing the nodejs package again. We'll add this to our task list to prevent such issues in the future.

use this cmd: `sudo apt purge libnode-dev`
