### ISSUE TITLE
[ERROR] Node.js 21.x on Ubuntu22.04 jammy Installation fail (repo no existant)

### ISSUE THREAD

**Issue by MohamedLamineAllal** [nodesource/distributions#1692]
**Bug description**
21.x repo is no existent. Or missing critical files. I tested `InRelease` and `Release` both no existent.

**Distribution Information:**
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

**Node Version:**
 - Node: 21.x

**To Reproduce**
```
wget -O InRelease https://deb.nodesource.com/node_21.x/dists/jammy/InRelease
```

> HTTP request sent, awaiting response... 404 Not Found

Or 

Official install

```
~$ sudo apt-get update && sudo apt-get install -y ca-certificates curl gnupg
~$ curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
~$ NODE_MAJOR=21
~$ echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
~$ sudo apt-get update && sudo apt-get install nodejs -y
```

> E:The repository 'https://deb.nodesource.com/node_21.x jammy Release' does not have a Release file."

**Expected behavior**

Repo should be existent

Just like `20.x`

Any of the command above in `20.x` works

- If 21.x is not ready yet. I guess, it should be removed from the documentation. So people don't waste time unnecessarily.
- Otherwise, i wonder what the issue is for the repo to not exist.

Thank you cordially.

**Comment by QuentiumYT** [comment]
Hey, actually the distro codenames moved to the "nodistro" name. You might have several list files with multiple sources of node conflicting, please check that :)

Just a small not if a maintainer stumble upon this, why choosing nodistro instead of the standard "stable" name?

**Comment by JesusPaz** [comment]
Thank you @QuentiumYT . We use "nodistro" to simplify across all distributions instead of specifying each one like "jammy". @MohamedLamineAllal, it seems you're using the old repo. I recommend checking out our migration guide. https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository

**Comment by QuentiumYT** [comment]
Yeah make sense, totally a good idea @JesusPaz. But many company or big project use the "stable" name, which make more sense honestly

**Comment by MohamedLamineAllal** [comment]
@JesusPaz @QuentiumYT thank you a lot. Well noted.
