### ISSUE TITLE
[ERROR] wsl installation fails for installFO.sh // installFull.sh

### ISSUE THREAD

**Issue by sgjue** [nodesource/distributions#1700]
**Describe your bug**
I´ve done today the installation in an fresh Ubuntu-22.04 with the commands:
 curl -sSL https://raw.githubusercontent.com/monarc-project/MonarcAppFO/master/wsl/installFO.sh | bash
and additional with 
curl -sSL https://raw.githubusercontent.com/monarc-project/MonarcAppFO/master/wsl/installFull.sh | bash

There were no error message during installation and the installation is finished with:

MONARC FO is ready and available at http://localhost
MONARC BO is ready and available at http://localhost:8080
Stats service is ready and available at http://localhost:5000
user: admin@admin.localhost / password: removed

 
**Distribution Information:**
Ubuntu-22.04 as fresh wsl installation. apt update && apt upgrade also fresh done

**Node Version:**
The version which is included in the wsl setup scripts : installFO.sh // installFull.sh

**To Reproduce**
wsl --install -d Ubuntu-20.04
sudo apt update
sudo apt upgrade
sudo -i 
curl -sSL https://raw.githubusercontent.com/monarc-project/MonarcAppFO/master/wsl/installFO.sh | bash

*(or with another fresh wsl Ubuntu:*
curl -sSL https://raw.githubusercontent.com/monarc-project/MonarcAppFO/master/wsl/installFull.sh | bash

2. Execute Installation instructions for Node.js v1x.x:

**Expected behavior**
Login to monarc should be possible. Instead 

Not Found
HTTP Error 404. The requested resource is not found.

**Screenshots**

**Additional context**
Attached the installation logfile:
[monarc.logfile.txt](https://github.com/nodesource/distributions/files/13167860/monarc.logfile.txt)

**Comment by JesusPaz** [comment]
This problem is not related to this repository.
