### ISSUE TITLE
[ERROR] can’t update node

### ISSUE THREAD

**Issue by ericdhkim** [nodesource/distributions#1702]
Hi there,

first off, I’m not that tech savvy and installed node for homebridge on my Raspberry pi so please excuse me if my issue submission is missing components or not clear. If you point out what I’m missing I’d be happy to add what details I can add. 

Like I said, I have node 18.17.1 installed on my Raspberry pi for my homebridge installation. I was having issues installing a plugin so the creator of the plugin advised that I update node. However when I run the command sudo hb-service update-node I get an error and it seems it’s because it’s not able to create a file or directory? Not sure what I’m supposed to do here to fix this so that I can update node 

![IMG_2402](https://github.com/nodesource/distributions/assets/61293059/d29a2bac-eb5c-4c1f-89b8-22cd88d0a6a5)

**Comment by riosje** [comment]
the error is because the folder `/etc/apt/keyrings` does not exist.
so, just execute `mkdir /etc/apt/keyrings`

**Comment by ericdhkim** [comment]
Thanks for the help! After I create that and tried update again, I got a different error about a pubkey?

![IMG_2404](https://github.com/nodesource/distributions/assets/61293059/f6e7dbc3-1937-4388-b2a4-b683686c6d76)

**Comment by riosje** [comment]
You just skipped some important info while creating the issue.
We have the issue template to make more easy for us to debug and give support, please share to me the steps you're executing to install node.
**To Reproduce**
Steps to reproduce the behavior:
1. Execute Ubuntu Docker Image XX
2. Execute Installation instructions for Node.js v1x.x:
3. ....

**Comment by riosje** [comment]
If you're still facing this issue please create a new one with all the needed information.
