### ISSUE TITLE
[ERROR] Node.js 20 on Ubuntu22.04 Installation fail

### ISSUE THREAD

**Issue by quad** [nodesource/distributions#1709]
**Describe your bug**

```
1.334 Err:1 https://deb.nodesource.com/node_20.x lunar/main arm64 nodejs arm64 20.5.1-deb-1nodesource1
1.334   404  Not Found [IP: 104.22.5.26 443]
…
88.27 E: Failed to fetch https://deb.nodesource.com/node_20.x/pool/main/n/nodejs/nodejs_20.5.1-deb-1nodesource1_arm64.deb  404  Not Found [IP: 104.22.5.26 443]
88.27 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Distribution Information:**
 - OS: Ubuntu
 - Version jammy (22.04)

**Node Version:**
 - Node: Node.js v20.x

**To Reproduce**

1. Download `https://deb.nodesource.com/gpgkey/nodesource.gpg.key` to `nodesource.gpg.key`
2. Build the following `Dockerfile` via: `docker build .`
    ```
    FROM ubuntu:lunar
    COPY nodesource.gpg.key .
    
    ENV DEBIAN_FRONTEND=noninteractive
    RUN apt-get update
    RUN apt-get install --yes \
            gpg \
            software-properties-common
    
    RUN gpg --dearmor --output /etc/apt/trusted.gpg.d/nodesource.gpg nodesource.gpg.key && \
        add-apt-repository --uri https://deb.nodesource.com/node_20.x
    
    RUN apt-get install --yes nodejs
    ```

**Expected behavior**

Node 20.x should be installed.

**Screenshots**

```
> [6/6] RUN apt-get install --yes nodejs:
0.926 Reading state information...
1.042 The following NEW packages will be installed:
1.042   nodejs
1.422 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
1.422 Need to get 29.4 MB of archives.
1.422 After this operation, 193 MB of additional disk space will be used.
1.422 Err:1 https://deb.nodesource.com/node_20.x lunar/main arm64 nodejs arm64 20.5.1-deb-1nodesource1
1.422   404  Not Found [IP: 104.22.5.26 443]
1.437 E: Failed to fetch https://deb.nodesource.com/node_20.x/pool/main/n/nodejs/nodejs_20.5.1-deb-1nodesource1_arm64.deb  404  Not Found [IP: 104.22.5.26 443]
1.437 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
------
Dockerfile.test:13
--------------------
  11 |         add-apt-repository --uri https://deb.nodesource.com/node_20.x
  12 |     
  13 | >>> RUN apt-get install --yes nodejs
  14 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get install --yes nodejs" did not complete successfully: exit code: 100
```

**Additional context**
I needed to use the package repository key as documented in #1682.

**Comment by StachuDotNet** [comment]
FWIW, seeing this as well, in the setup of a Devcontainer on amd64

**Comment by edgan** [comment]
I am seeing this issue too.

**Comment by jasontorres-sf** [comment]
Also seing this problem... Please help fix.

**Comment by edgan** [comment]
Workaround for those affected:
```
curl https://deb.rwx.work/nodejs/node_20.x/pool/main/n/nodejs/nodejs_20.5.1-deb-1nodesource1_amd64.deb -o nodejs_20.5.1-deb-1nodesource1_amd64.deb
dpkg -i nodejs_20.5.1-deb-1nodesource1_amd64.deb
```

**Comment by nnellanspdl** [comment]
Adding my name to the list of users seeing this issue.

**Comment by eugali** [comment]
same here

**Comment by soren121** [comment]
Install the repository using the `nodistro` codename instead of a specific Debian/Ubuntu codename.

I'm not sure if it's intentional or an accident, but all of the package files were renamed. They've only updated the`nodistro` pool as of now, and not the distro-named pools.

**Comment by namhyuck-kim-otsk** [comment]
Getting the same issue for Node 18.

```
#7 111.4 Err:1 https://deb.nodesource.com/node_18.x focal/main amd64 nodejs amd64 18.17.1-deb-1nodesource1
#7 111.4   404  Not Found [IP: 104.22.4.26 443]
#7 111.4 E: Failed to fetch https://deb.nodesource.com/node_18.x/pool/main/n/nodejs/nodejs_18.17.1-deb-1nodesource1_amd64.deb  404  Not Found [IP: 104.22.4.26 443]
#7 111.4 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by dhampik** [comment]
Installing it according to instructions from [deb.nodesource.com](https://deb.nodesource.com/) using the `nodistro` codename instead of a specific Debian/Ubuntu codename indeed helped to solve the issue. Thanks @soren121!

**Comment by tungtranthanh95** [comment]
I have same issue too
```
E: Failed to fetch https://deb.nodesource.com/node_18.x/pool/main/n/nodejs/nodejs_18.17.1-deb-1nodesource1_amd64.deb  404  Not Found [IP: 104.22.4.26 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by chatterbox777** [comment]
we solve it on our project by 
![image](https://github.com/nodesource/distributions/assets/48375860/448eb369-39ef-43ef-988e-420f7264ffd0)

**Comment by alextselegidis** [comment]
![image](https://github.com/nodesource/distributions/assets/4527441/3a4b568f-e289-4cdd-a782-4bb740bae2fe)

That might be related

**Comment by StachuDotNet** [comment]
> FWIW, seeing this as well, in the setup of a Devcontainer on amd64

Thanks to [this](https://github.com/nodesource/distributions/issues/1709#issuecomment-1788473588) comment, along with the notes [here](https://deb.nodesource.com), I think we've resolve the issue in our case.

In case it's helpful to someone else, here's the fixing PR for our usage: https://github.com/darklang/dark/pull/5141/files

**Comment by harsha-chamarthi** [comment]
same here

**Comment by m-rwash** [comment]
seems to be working fine for me now out of no where

**Comment by harsha-chamarthi** [comment]
Worked for me too

**Comment by ignl** [comment]
Still doesn't work for Node 14

**Comment by gabriel-mend** [comment]
The same error was happening to me, it worked for me to install nodejs in the new way that they ask for in the documentation:
https://github.com/nodesource/distributions

But my version in this case is 18.

```
RUN set -uex; \
     apt-get update; \
     apt-get install -y ca-certificates curl gnupg; \
     mkdir -p /etc/apt/keyrings; \
     curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
      | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg; \
     NODE_MAJOR=18; \
     echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" \
      > /etc/apt/sources.list.d/nodesource.list; \
     apt-get -qy update; \
     apt-get -qy install nodejs;
```

**Comment by alextselegidis** [comment]
Hello!

That is correct. There was a short time where the setup scripts used to fail and this will probably happen again. 

Here is the updated dockerfile for you to use: 

https://github.com/alextselegidis/easyappointments/blob/develop/docker/php-fpm/Dockerfile

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by fabianospinelli** [comment]
@gabriel-mend have you resolved? I'm trying to use the version 18 but I obtain error during the installation:

4.765 + curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
4.766 + gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
4.853 + NODE_MAJOR=19
4.853 + echo deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_19.x nodistro main
4.853 + apt-get -qy update
5.012 Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
5.145 Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
5.229 Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
5.248 Ign:4 https://deb.nodesource.com/node_19.x nodistro InRelease
5.313 Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
5.463 Err:6 https://deb.nodesource.com/node_19.x nodistro Release
5.463   404  Not Found [IP: 104.22.4.26 443]
5.489 Reading package lists...
6.622 E: The repository 'https://deb.nodesource.com/node_19.x nodistro Release' does not have a Release file.
------
Dockerfile:14
--------------------
  13 |     
  14 | >>> RUN set -uex; \
  15 | >>>     apt-get update; \
  16 | >>>     apt-get install -y ca-certificates curl gnupg; \
  17 | >>>     mkdir -p /etc/apt/keyrings; \
  18 | >>>     curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
  19 | >>>      | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg; \
  20 | >>>     NODE_MAJOR=19; \
  21 | >>>     echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" \
  22 | >>>      > /etc/apt/sources.list.d/nodesource.list; \
  23 | >>>     apt-get -qy update; \
  24 | >>>     apt-get -qy install nodejs;
  25 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c set -uex;     apt-get update;     apt-get install -y ca-certificates curl gnupg;     mkdir -p /etc/apt/keyrings;     curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key      | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg;     NODE_MAJOR=19;     echo \"deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main\"      > /etc/apt/sources.list.d/nodesource.list;     apt-get -qy update;     apt-get -qy install nodejs;" did not complete successfully: exit code: 100
