### ISSUE TITLE
[ERROR] Missing Node.js 18.18.x packages on Rocky Linux 8

### ISSUE THREAD

**Issue by mattboston** [nodesource/distributions#1713]
**Describe your bug**
v18.18.2 is not available for installation. The latest version available via rpm is v18.17.1

**Distribution Information:**
 - OS: Rocky Linux
 - Version 8

**Node Version:**
 - Node: v18.18.2

**To Reproduce**
1. sudo dnf install https://rpm.nodesource.com/pub_18.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
2. sudo dnf clean all
3. sudo dnf --showduplicates list nodejs

**Expected behavior**
Even though v18.18.2 is out, it doesn't appear to be available.

**Screenshots**
![image](https://github.com/nodesource/distributions/assets/852911/7e7e706d-35db-4a78-ab2b-f2da0fec0777)

**Comment by mattboston** [comment]
I was able to fix this by adding "module_hotfixes=true" to each of the repo config's.  So now my yum file looks like this:

```
[nodesource-nsolid]
name=Nsolid Packages for Linux RPM based distros - $basearch
baseurl=https://rpm.nodesource.com/pub_18.x/nodistro/nsolid/$basearch
priority=8
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-NSOLID-GPG-SIGNING-KEY-EL
module_hotfixes=true

[nodesource-nodejs]
name=Node.js Packages for Linux RPM based distros - $basearch
baseurl=https://rpm.nodesource.com/pub_18.x/nodistro/nodejs/$basearch
priority=9
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-NSOLID-GPG-SIGNING-KEY-EL
module_hotfixes=true
```

**Comment by mattboston** [comment]
Looks like I was mistaken and it's not working.  I've also tried mirroring the repo locally and pointing my server at that repo and it still can't detect it. 

Is there something that's done different when the v18.18.1 and v18.18.2 packages were built?

**Comment by JesusPaz** [comment]
I made some changes in the repo, the packages are now available.
![image](https://github.com/nodesource/distributions/assets/27715376/94da2ab4-4600-446c-b0ba-b3e3892315bc)
