### ISSUE TITLE
[ERROR] Node.js XX on Debian 10 Installation fail

### ISSUE THREAD

**Issue by ndrone-kr** [nodesource/distributions#1714]
**Describe your bug**
Certificate verification failed when running apt-get update

**Distribution Information:**
 - OS: Debian
 - Version: 10
 - Other info if applicable Docker

**Node Version:**
 - Node: 18.x

**To Reproduce**
1. curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor | tee /etc/apt/keyrings/nodesource.gpg > /dev/null
2. chmod go+r /etc/apt/keyrings/nodesource.gpg
3. echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
4. apt-get update

**Expected behavior**
I'd expect apt-get to update its database with the added nodesource repository.

**Screenshots**
```
 > [16/17] RUN apt-get update:
0.598 Ign:1 https://deb.nodesource.com/node_18.x nodistro InRelease
0.720 Hit:2 http://deb.debian.org/debian buster InRelease
0.742 Err:3 https://deb.nodesource.com/node_18.x nodistro Release
0.742   Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 104.22.4.26 443]
0.767 Hit:4 http://deb.debian.org/debian-security buster/updates InRelease
0.825 Hit:5 http://deb.debian.org/debian buster-updates InRelease
0.870 Hit:6 https://packages.microsoft.com/repos/azure-cli buster InRelease
1.019 Reading package lists...
1.344 E: The repository 'https://deb.nodesource.com/node_18.x nodistro Release' does not have a Release file.
```

**Additional context**
Add any other context about the problem here, specify if already has another NodeJS version or if trying to re-install the current version.

**Comment by riosje** [comment]
Hi @ndrone-kr you want to try this installation script
```
curl -SLO https://deb.nodesource.com/nsolid_setup_deb.sh
chmod 500 nsolid_setup_deb.sh
./nsolid_setup_deb.sh 18
apt-get install nodejs -y
```
https://github.com/nodesource/distributions#installation-scripts
