### ISSUE TITLE
[ERROR] Node.js 18 and 20 versions are not updated

### ISSUE THREAD

**Issue by orgads** [nodesource/distributions#1715]
**Describe your bug**
Node versions are not updated for long time. 18.x is stuck on 18.17.1, and 20.x is stuck on 20.5.1.

It's been more than 3 months since the release of 20.5.1, and about 2 months since 20.6.0.

For 18.x, 3 months since 18.17.1 and almost 2 months since 18.18.0.

Is this project still maintained?

**Distribution Information:**
 - OS: Ubuntu lunar (23.04) and Debian bookworm

**Node Version:**
 - Node: 18.x, 20.x

**Comment by pomeo** [comment]
What's in your file `/etc/apt/sources.list.d/nodesource.list`?

**Comment by jgottlander** [comment]
I have a similar problem, that I think is related.
I've added the repository from nodesource, but when I try to install nodejs via apt, it installs the version provided with bookworm, which is 18.13.
when I type `apt show nodejs -al` it lists all available version, also from nodesource. But somehow the Debian package has higher priority when installing.

**Comment by jgottlander** [comment]
> I have a similar problem, that I think is related. I've added the repository from nodesource, but when I try to install nodejs via apt, it installs the version provided with bookworm, which is 18.13. when I type `apt show nodejs -al` it lists all available version, also from nodesource. But somehow the Debian package has higher priority when installing.

I remembered that I had set a custom priority for the stable repo to 900, from when installing firefox from unstable. I uncommented the setting and it installed version 20 as wanted.

**Comment by orgads** [comment]
> What's in your file `/etc/apt/sources.list.d/nodesource.list`?

Ubuntu:
```
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x lunar main
```

Debian:
```
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x bookworm main
```

**Comment by pomeo** [comment]
> > What's in your file `/etc/apt/sources.list.d/nodesource.list`?
> 
> Ubuntu:
> 
> ```
> deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x lunar main
> ```
> 
> Debian:
> 
> ```
> deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x bookworm main
> ```

They no longer use the name of the distribution, you need to change to `nodistro`
`deb [arch=amd64 signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main`

**Comment by orgads** [comment]
Ok, I just found out that the updated distro should be `nodistro`.

I changed it and it looks good now.

Notice that the gpg instructions on https://deb.nodesource.com don't work on Debian testing. The gpg file should be stored in `/etc/apt/trusted.gpg.d/nodesource.gpg`, and there's no need to specify it in `signed-by`.

**Comment by orgads** [comment]
Is it possible to change the old ones to be symbolic links to `nodistro`?

**Comment by angryziber** [comment]
I have just realized that my node wasn't updated for several months. Definitely, symlinks should be there for backwards-compatibility

**Comment by MartinEmrich** [comment]
> I have just realized that my node wasn't updated for several months. Definitely, symlinks should be there for backwards-compatibility

Either that, or please delete the old distro-specific `distribution`s, so running `apt-get update` will present an error to act on. This way, I bet many will be stuck on old (possibly error-prone) versions for a long time, thinking they are running the latest version.
