### ISSUE TITLE
[ERROR] Node.js 16.x on Almalinux 8 Installation fail

### ISSUE THREAD

**Issue by leejaycoke** [nodesource/distributions#1717]
**Describe your bug**
yum tries to install legacy version 10.x not 16.x

**Distribution Information:**
 - OS: Almalinux
 - Version: 8.7
 - Other info if applicable: It's a Docker image from almalinux:8.7-minimal-20221201

**Node Version:**
 - Node: Node.js 16.x

**To Reproduce**
Below commands were run as root.

```
sudo -u root -i
yum remove nodejs &&\
rm -r /etc/yum.repos.d/nodesource*.repo &&\
yum clean all
```

```
NODE_MAJOR=16
sudo yum install https://rpm.nodesource.com/pub_${NODE_MAJOR}.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
```

`cat /etc/yum.repos.d/nodesource-nodistro.repo`

```
[nodesource-nsolid]
name=Nsolid Packages for Linux RPM based distros - $basearch
baseurl=https://rpm.nodesource.com/pub_16.x/nodistro/nsolid/$basearch
priority=8
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-NSOLID-GPG-SIGNING-KEY-EL

[nodesource-nodejs]
name=Node.js Packages for Linux RPM based distros - $basearch
baseurl=https://rpm.nodesource.com/pub_16.x/nodistro/nodejs/$basearch
priority=9
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-NSOLID-GPG-SIGNING-KEY-EL
```

- Then yum tries to install nodejs version 10 `1:10.24.0-1.module_el8.4.0+2224+b07ac28e` repository from appstream

**Expected behavior**
Yum must try install nodejs version 16.x

<img width="1485" alt="스크린샷 2023-11-15 오후 4 39 43" src="https://github.com/nodesource/distributions/assets/4186934/1e861ae7-a051-48d2-9a37-468e07f37d18">

Thanks.

**Comment by JesusPaz** [comment]
Node.js v16 is deprecated, we recommend using a newer version. you can run:
```
curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
yum install -y nodejs
```
