### ISSUE TITLE
Setup scripts are much easier than copy paste many commands

### ISSUE THREAD

**Issue by greenpdx** [nodesource/distributions#1718]
**Describe your bug**
It is much more difficult to install nodejs now, setup scripts were much easier

**Distribution Information:**
 - OS: Ubuntu
 - Version22.04

**Node Version:**
 - Node: Node.js v18.x

**To Reproduce**
1.Install changed

**Expected behavior**
paste setup-18.xxx and it installs

**Additional context**
Install went from single command to copy paste many commands
Come on, make things easier not harder for the user.

**Comment by riosje** [comment]
Hi @greenpdx 
We'e created some installation scripts
https://github.com/nodesource/distributions#installation-scripts

Do you mind to give it a try and then give us some feedback about your experience?
