### ISSUE TITLE
[ERROR] Node.js 16 on Amazon linux2 Installation fail

### ISSUE THREAD

**Issue by nandikatlakishore** [nodesource/distributions#1719]
**Describe your bug**

Node.js 16 on Amazon linux2   Installation fail

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_16.x/el/2/x86_64/nodesource-release-el2-1.noarch.rpm'

## Your distribution, identified as "system-release-2-16.amzn2.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Distribution Information:**
 - OS: [e.g. Amazonlinux2]

**Node Version:**
 - Node: [e.g. Node.js v16.x:]

**To Reproduce**
1. Execute Ubuntu Docker Image XX
2. Execute Installation instructions for Node.js v1x.x:
3. ....

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here, specify if already has another NodeJS version or if trying to re-install the current version.

**Comment by yuileroy** [comment]
Got same error 

> Your distribution, identified as "system-release-2-16.amzn2.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

While Release package: system-release-2-14.amzn2.x86_64 doesn't have such issue.

**Comment by satyam88** [comment]
Any Solution for the same
