### ISSUE TITLE
No support for Ubuntu Gnome 15.10 Willy

### ISSUE THREAD

**Issue by Hammerstad** [nodesource/distributions#172]
Running the following command

    curl -sL https://deb.nodesource.com/setup | sudo bash -

resulted in the following output

    ## Your distribution, identified as "wily", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

I'd love if my distribution was supported, so here I am :smile:

**Comment by chrislea** [comment]
Please see [here](https://github.com/nodesource/distributions/#deb). Wily is only supported on 4.2.x or newer, so you need to use a different setup script. One of:

https://deb.nodesource.com/setup_5.x
https://deb.nodesource.com/setup_4.x

**Comment by Hammerstad** [comment]
Ok, thanks.
