### ISSUE TITLE
[ERROR] Node.js 21 on Cents 9 Installation fail - Signature SHA1 not available

### ISSUE THREAD

**Issue by Raptormagnum** [nodesource/distributions#1721]
**Describe your bug**
GPG import : Signature not supported. Hash algorithm SHA1 not available.
Cause : https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9

Please update your signatures

**Comment by jcox10** [comment]
Duplicate of https://github.com/nodesource/distributions/issues/1653
