### ISSUE TITLE
[ERROR] Node.js 18 Penetration Testing on Ubuntu20 Discovers "Client-Initiated SSL Renegotiation Allowed" Issue

### ISSUE THREAD

**Issue by tangzhiqiangh** [nodesource/distributions#1722]
**Describe your bug**
Node.js 18 Penetration Test on Ubuntu20 Finds "Client-Initiated SSL Renegotiation Allowed"

**Distribution Information:**
 - OS:  Ubuntu
 - Version  20.04
 - AWS EC2

**Node Version:**
 - Node:  Node.js v18.18.2

**Expected behavior**
Disable client-initiated SSL renegotiation on your server if possible,

**Screenshots**

**Additional context**
Which Node.JS version to install on Ubuntu 20.04 to solve the "Client-Initiated SSL Renegotiation Permitted" issue

**Comment by tangzhiqiangh** [comment]
![node_version](https://github.com/nodesource/distributions/assets/70993108/40c256bb-460b-42bb-a3c4-7bb14071bad0)
<img width="587" alt="Pen-Testing" src="https://github.com/nodesource/distributions/assets/70993108/ba093a60-85b0-4ba2-8451-1efd0d5470d9">

**Comment by riosje** [comment]
Hi @tangzhiqiangh please fill an issue directly to https://github.com/nodejs/node/issues
