### ISSUE TITLE
[ERROR] User-Agent Discrimination on Repository Web Server results in "HTTP Error 403: Forbidden"

### ISSUE THREAD

**Issue by oxzi** [nodesource/distributions#1723]
**Describe your bug**
The repository web server performs a User-Agent-based discrimination.
This results, for example, in Ansible's [deb822_repository module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/deb822_repository_module.html) being unable to import the signing key.

```
TASK [Add NodeSource repositories] ***********
fatal: [default]: FAILED! => {"changed": false, "msg": "Could not fetch signed_by key: HTTP Error 403: Forbidden"}
```

```
$ curl -sI https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | grep '^HTTP'
HTTP/2 200

$ curl -sI -A 'Python-urllib/3.11' https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | grep '^HTTP'
HTTP/2 403
```

**Distribution Information:**
_Unrelated_

**Node Version:**
 - Node: _all version, unrelated_

**To Reproduce**
- Either try to import the `deb.nodesource.com` repository through the `deb822_repository` Ansible module or
- reproduce the `curl` command with the Python-User-Agent from above.

**Expected behavior**
I'd expect that a web server does not perform some hard discrimination based on a User-Agent, especially for repository servers.

**Screenshots**
See above.

**Additional context**
The issue is known upstream at Ansible for other CloudFlare-based repositories, <https://github.com/ansible/ansible/issues/80809>. However, it is not always possible to install the freshest Ansible version which allows changing the User-Agent.

As a workaround, it is possible to either download the signing key through Ansible's `get_url` module or paste an armored GPG key to `deb822_repository.signed_by`.

**Comment by JesusPaz** [comment]
@elimork this is open source and free to use. We have made the most of our available resources. By utilizing Cloudflare, we aim to reduce costs and enhance user experience. Please note that hosting and maintaining this service is not without expense and requires considerable effort. If you have a more efficient approach, we encourage you to implement and share it. We are more than willing to assist.

**Comment by riosje** [comment]
@oxzi I just found the way to make Cloudflare to not mark this user agent request as malicious.
You should be ok now with ansible.

**Comment by riosje** [comment]
@elimork this is ridiculous, We definitively don't have enough time to track your PC in your moms basement basement, you're ok.

**Comment by elimork** [comment]
Well, I don't go so very often in my moms basemanet (and when I do, I don't always have plenty of time), so I'll check it as soon as I can, and if it really is fine to install NodeJS over tor, thanks a lot!
(BTW, I just tried and reach https://blog.cloudflare.com/waf-for-everyone/ to learn why CF is so obstinate against Tor, and I keep getting the "Just a momnet" error forever. The real discriminator is Cloudlare and you know it, and still use it, in a place where it nobody AFAIK does, but if I find NodeJS over Tor is fine, thanks just the same.)

**Comment by oxzi** [comment]
@riosje: Thanks for tweaking the configuration. I currently don't have the original Ansible configuration at hand, but I just verified that different User Agents - both the original one, one with an incremented version number, and even one which neither contains Python nor urllib - are resulting in a `200`. Thanks!

@elimork: I totally understand why you are upset because Cloudflare handles Tor users as second class citizen, but, at least for me, this seems to be an own issue, which is only related to this one. Btw, there even seems to be an option to let Cloudflare serve one's webpage as an `.onion` page within Tor, <https://developers.cloudflare.com/network/onion-routing/>. However, as stated earlier, this is out of this issue's scope.
