### ISSUE TITLE
[ERROR] Support for distribution nodejs.16 for Ubuntu 22.04 Jammy windows WSL

### ISSUE THREAD

**Issue by cerroviejo** [nodesource/distributions#1728]
**Describe the distribution information:**

 - OS: [Ubuntu 22.04]
 - Distribution Type: RPM/DEB
 - Version [Ubuntu 22.04.2 LTS]
 - Codename:       jammy

**Additional context**
need to install nodejs 16 specifically for Ubuntu 22.04 jammy WSL on windows 10
the migration script from   https://github.com/nodesource/distributions doesn't work since fail in many steps.

**Comment by riosje** [comment]
@cerroviejo what's the error?
we need more info to provide assistance.

**Comment by JesusPaz** [comment]
we do not support Node.js v16 due to deprecation. I am running node on wsl with no problem using our packages.

**Comment by Glozano26** [comment]
When running the following command "sudo bash nodesource_setup.sh" I get this;
Your distribution, identified as "jammy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
