### ISSUE TITLE
[ERROR] Failed to install Node.js in ubuntu 23.04

### ISSUE THREAD

**Issue by MyDapitt** [nodesource/distributions#1730]
**Describe your bug**
A bug, i'm can't install Node.js.

**Distribution Information:**
 - OS: Ubuntu
 - Version: lunar (23.04)
 - Other info if applicable: VPS

**Node Version:**
 - Node: All of version (maybe)

**To Reproduce**
1. Execute Installation instructions for Node.js v1x.x:

**Expected behavior**
I'm can install Node.js using the step on the repository.

**Screenshots**
![Screenshot_20231210_063715_JuiceSSH](https://github.com/nodesource/distributions/assets/125800740/9e44f8eb-f6df-4755-bf1f-334ee45b7ef1)
![Screenshot_20231210_063723_JuiceSSH](https://github.com/nodesource/distributions/assets/125800740/84935eea-74b6-4040-85fe-2cdf50be7f94)

**Additional context**
-

**Comment by cweijan** [comment]
I encountered the same problem. The reason was that the public key download failed. Just execute the command `mkdir /etc/apt/keyrings` and run guide again.

**Comment by riosje** [comment]
@MyDapitt let's try this

```
curl -SLO https://deb.nodesource.com/nsolid_setup_deb.sh
chmod 500 nsolid_setup_deb.sh
./nsolid_setup_deb.sh 21
apt-get install nodejs -y
```

https://github.com/nodesource/distributions#installation-scripts
