### ISSUE TITLE
[ERROR] Node.js 16 on Ubuntu 20 Installation fail

### ISSUE THREAD

**Issue by cweijan** [nodesource/distributions#1731]
There is a problem with the installation shell provided by Readme. It cannot successfully create /etc/apt/keyrings, resulting in nodesource-repo.gpg.key not being imported by the system.

**Comment by riosje** [comment]
Hi @cweijan you still facing issues after create the folder??

**Comment by cweijan** [comment]
Hi, it works normally after I create the folder. I just want to remind that the guide shell of the readme may cause failure.
