### ISSUE TITLE
[ERROR] Node.js 18 on Ubuntu 22.04 Installation fail

### ISSUE THREAD

**Issue by FelipeSavazii** [nodesource/distributions#1737]
**Describe your bug**

**Distribution Information:**
 - OS: Ubuntu
 - Version: 22.04.03 LTS

**Node Version:**
 - Node: Node.js v18.19

**To Reproduce**
1. Execute Installation instructions for Node.js v18.19 on "https://github.com/nodesource/distributions" to Ubuntu:
2. Run `sudo apt-get install nodejs -y`

**Expected behavior**
An error when unpack nodejs:

```
Preparing to unpack .../nodejs_18.19.0-1nodesource1_amd64.deb ...
Unpacking nodejs (18.19.0-1nodesource1) ...
dpkg: error processing archive /var/cache/apt/archives/nodejs_18.19.0-1nodesource1_amd64.deb (--unpack):
 trying to overwrite '/usr/include/node/common.gypi', which is also in package libnode-dev 12.22.9~dfsg-1ubuntu3.2
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_18.19.0-1nodesource1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Screenshots**
![image](https://github.com/nodesource/distributions/assets/90295858/a2fb93c3-8df6-4417-8132-754a69564bfa)

**Comment by Vasiharan** [comment]
I am also getting this error

**Comment by JesusPaz** [comment]
Try removing all the nodejs packages present in your system:
```
sudo apt-get remove --purge nodejs libnode-dev
sudo apt-get autoremove
sudo apt-get clean
```
then install the version you need:
```
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\
sudo apt-get install -y nodejs
```
