### ISSUE TITLE
[DISTRIBUTION] Support for distribution XX

### ISSUE THREAD

**Issue by KWISKO** [nodesource/distributions#1738]
**kaisen linux:**
 - OS: [Debian12]
 - Distribution Type: RPM/DEB
 - Version [kaisen linux rolling 2.3]

**Additional context**

**Comment by JesusPaz** [comment]
please add more context

**Comment by KWISKO** [comment]
trying to install npm on kaisen linux 2.3 rolling but it says 
## Your distribution, identified as "rolling", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
i feel comfortable using this disturb and i want to start an angular project that's why nodjs and nmp must be installed 
thank you for the reply
