### ISSUE TITLE
Fedora 22 not supported?

### ISSUE THREAD

**Issue by ktriponis** [nodesource/distributions#174]
When I run `curl --silent --location https://rpm.nodesource.com/setup | sudo bash -` I get the following message:
> Your distribution, identified as "fedora-release-22-1.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

It seems kind of strange considering https://rpm.nodesource.com/pub/fc/22/x86_64/ actually exists.

**Comment by chrislea** [comment]
Please look [here](https://github.com/nodesource/distributions/#rpminstall).

You probably want to be using one of:

curl -sL https://rpm.nodesource.com/setup_5.x | bash -
curl -sL https://rpm.nodesource.com/setup_4.x | bash -
