### ISSUE TITLE
[ERROR] Node.js 18 on Amazon Linux 2023 Installation fail

### ISSUE THREAD

**Issue by dmattia** [nodesource/distributions#1740]
**Describe your bug**

**Distribution Information:**
 - OS: amazonlinux
 - Version 2023.2.20231113.0

**Node Version:**
 - Node: Node.js v18.x

**To Reproduce**
1. Run `docker run -it amazonlinux:2023.2.20231113.0 sh`
2. Run `curl -o- https://rpm.nodesource.com/setup_18.x | bash`
3. Run `dnf install nodejs -y`

**Expected behavior**

Node would be installed successfully

**Screenshots**

The full error is:

```text
sh-5.2# dnf install nodejs -y
Last metadata expiration check: 0:00:16 ago on Thu Dec 28 16:35:46 2023.
Dependencies resolved.
==================================================================================================================================================================
 Package                         Architecture                    Version                                         Repository                                  Size
==================================================================================================================================================================
Installing:
 nodejs                          x86_64                          2:18.19.0-1nodesource                           nodesource-nodejs                           34 M

Transaction Summary
==================================================================================================================================================================
Install  1 Package

Total download size: 34 M
Installed size: 100 M
Downloading Packages:
nodejs-18.19.0-1nodesource.x86_64.rpm                                                                                              85 MB/s |  34 MB     00:00    
------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                              84 MB/s |  34 MB     00:00     
Node.js Packages for Linux RPM based distros - x86_64                                                                              58 kB/s | 3.1 kB     00:00    
Importing GPG key 0x3AF28A14:
 Userid     : "Nodesource Operations <operations@nodesource.com>"
 Fingerprint: 242B 8138 31AF 0956 2B6C 46F7 6B88 DA4E 3AF2 8A14
 From       : https://rpm.nodesource.com/gpgkey/ns-operations-public.key
Key imported successfully
Import of key(s) didn't help, wrong key(s)?
Public key for nodejs-18.19.0-1nodesource.x86_64.rpm is not installed. Failing package is: nodejs-2:18.19.0-1nodesource.x86_64
 GPG Keys are configured as: https://rpm.nodesource.com/gpgkey/ns-operations-public.key
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```

<img width="980" alt="Screenshot 2023-12-28 at 10 37 07 AM" src="https://github.com/nodesource/distributions/assets/8922077/d9d42322-54ad-4ca7-94a6-6ebdf4d1b880">

**Additional context**

None

**Comment by dmattia** [comment]
Of note, these commands do work:

```bash
yum install https://rpm.nodesource.com/pub_18.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y \
    && yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1
```

**Comment by AndrVdov** [comment]
same problem

**Comment by calbaLumen** [comment]
Same problem with Redhat's ubi8base image. Unfortunately, [propposed workaround](https://github.com/nodesource/distributions/issues/1740#issuecomment-1871333024) didn't work.

**Comment by anthony-bennett** [comment]
> Same problem with Redhat's ubi8base image. Unfortunately, [propposed workaround](https://github.com/nodesource/distributions/issues/1740#issuecomment-1871333024) didn't work.

The workaround did work for me (Amazon Linux 2023), however on instances where the install had already been attempted, I needed to remove the nodesource.repo file from /etc/yum.repos.d/ first before it would work. I don't know if that is also applicable to RH.

**Comment by pauldanielm** [comment]
Having the same issue here, neither the workaround nor removing the `nodesource.repo` file resolved the issue for me.

**Comment by jc21** [comment]
Experiencing the same issue, with Node 20 package, on any RHEL-like distro. The RPM is signed with a different key than provided by the nodesource repo.

**Comment by dmattia** [comment]
Of note, my workaround no longer appears to work for me, but the original command does?

**Comment by JesusPaz** [comment]
You guys were running the script before any changes were deployed to production. It needs to work now. Please run:
```
curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
dnf install -y nodejs
```

**Comment by JesusPaz** [comment]
![image](https://github.com/nodesource/distributions/assets/27715376/dbbb0ae9-b0b3-4d1d-8152-86d4236bace7)

**Comment by acastruc** [comment]
@JesusPaz Ran command 
`curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
dnf install -y nodejs`

but still see failure

**Comment by yuanzhou** [comment]
Same issue encountered today with nodejs-18.19.0 on Redhat UBI 8.6 for a docker build

**Comment by speller** [comment]
When I use the proposed solution, I can not install `yarn`:

```none
$ yum -y install yarn
No match for argument: yarn
Error: Unable to find a match: yarn
```

How to fix it?
