### ISSUE TITLE
[ERROR] Node.js 20 apt update error

### ISSUE THREAD

**Issue by Hanro50** [nodesource/distributions#1741]
**Describe your bug**
On an amd64 system with i386 packages enabled. You will get the following warning when searching for updates  
```
Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://deb.nodesource.com/node_20.x nodistro InRelease' doesn't support architecture 'i386'
```

**Distribution Information:**
 - OS: LMDE
 - Version 6

**Node Version:**
 - Node: v20.x

**To Reproduce**
1. run `sudo dpkg --add-architecture i386`
2. Follow the instructions for Ubuntu or Debian 
3. run sudo apt update 

**Expected behavior**
I don't expect this error message to be there

**Additional context**
You can fix this bug by changing 
```deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main```
to
```deb [arch=amd64 signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main```

**Edit: Potential fix**
Change this line in the documentation 
```
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
```
to 
```
echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
```

**Comment by JesusPaz** [comment]
Thanks for your contribution, this issue is resolved by #1739
