### ISSUE TITLE
Support for AWS LInux?

### ISSUE THREAD

**Issue by jmcmahon** [nodesource/distributions#175]
I tried to install nodejs version 0.12 on AWS Linux and it failed. Any support for it?

[nodesource_error.txt](https://github.com/nodesource/distributions/files/34804/nodesource_error.txt)

**Comment by retrohacker** [comment]
Support for Amazon Linux should have landed in this commit: https://github.com/nodesource/distributions/commit/dd401435012106b69afea01cb8381d64e99b2a99

Via this line: https://github.com/nodesource/distributions/commit/dd401435012106b69afea01cb8381d64e99b2a99#diff-bce3818f024c3c9391544dc68bb96a4fR80

If you continue to have issues with Amazon Linux and the setup scripts, please reopen this issue and we can help debug!
