### ISSUE TITLE
[ERROR] Node.js 20 on Ubuntu20 Installation fail

### ISSUE THREAD

**Issue by bjoerne2** [nodesource/distributions#1750]
**Describe your bug**
Error when executing https://deb.nodesource.com/setup_20.x:
````
/home/ubuntu/install/nodejs/setup_20.x: 7: local: 13:41:14: bad variable name
````
The error occurs in the line
````

local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
````

**Distribution Information:**

- OS: Ubuntu
- Version focal (20.04)

**Node Version:**

- Node: Node.js v20.x

**To Reproduce**

1. Download script to /home/ubuntu/install/nodejs/setup_20.x (chmod 755)
2. sudo /home/ubuntu/install/nodejs/setup_20.x

**Expected behavior**
Error-free installation of Node.js 20

**Comment by maunzCache** [comment]
Duplicate to #1737

**Comment by JesusPaz** [comment]
can you try using:
```
curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
yum install -y nodejs
```

**Comment by bjoerne2** [comment]
I executed the script via bash instead of sh and that works. Thank you!!
