### ISSUE TITLE
[ERROR] nodejs 18.19.0 missing in nodesource Debian 12 repository

### ISSUE THREAD

**Issue by nudgegoonies** [nodesource/distributions#1751]
**Describe your bug**
nodejs 18.19.0 missing in nodesource Debian 12 repository. Highest version is still 18.17.1.

**Distribution Information:**

- OS: Debian
- Version 12
- Output of apt-cache policy nodejs
```
nodejs:
  Installed: 18.17.1-deb-1nodesource1
  Candidate: 18.17.1-deb-1nodesource1
  Version table:
     18.19.0+dfsg-6~deb12u1 500
        500 http://ftp.de.debian.org/debian-security bookworm-security/main amd64 Packages
 *** 18.17.1-deb-1nodesource1 600
        600 http://deb.nodesource.com/node_18.x bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
...
```
- As you can see the Debian 12 internal nodejs package is already updated to 18.19.0 but we pinned the nodesource repo higher because we need to install different nodejs versions in different debian versions and don't want to stick to the one version debian ships.  

**Node Version:**

- Node: 18.19.0

**Expected behavior**
Provide a nodejs 18.19.0 package within deb.nodesource.com/node_18.x bookworm main.

**Comment by jogoossens** [comment]
It's also conflicting install atm since the debian one get's preferred if you specify version, not sure if some workaround would exist for now

**Comment by nudgegoonies** [comment]
We pinned the nodesource repo higher than the debian repo because debian ships a lower version of npm and await the new nodesource version.

**Comment by riosje** [comment]
Hello everyone, is this happening using our installation scripts?
In the installation script we're pinning the repo, so this should not be happening, please let me know what steps you're following to install nodejs.

https://github.com/nodesource/distributions/blob/master/scripts/deb/setup_18.x#L79

**Comment by jogoossens** [comment]
Yes, we tried the pinning, and it works if you don't specify any version.

However it persist on installing the Debian one when we install nodejs like this:

apt-get install nodejs=18.*

We do this, since we also want to support downgrade if needed (we then replace major version in script)

**Comment by nudgegoonies** [comment]
I think i found it. We have not used a script but the documentation from deb.nodesource.org in the past.
The public key and the distribution changed. We must have missed an announcement regarding that.
We still use:
```
deb.nodesource.com/node_18.x bookworm main
```
But this changed to:
```
deb.nodesource.com/node_18.x nodistro main
```
Can someone please point me to the announcement about this change? Then i subscribe to the corresponding channel.

A suggestion. Remove bookworm, bullseye, etc. Then the apt-get fails and every one knows that something has changed. I assume that many others miss the announcement too and i also assume that many don't recognize, that they are running an outdated version.

**Comment by nudgegoonies** [comment]
Another hint! Bigger companies always use mirrors or caches. Especially when using a cache like 'cache.company.com/deb.nodesource.com' you should not pin origin but release like 'Pin: release n=nodistro'.

**Comment by nudgegoonies** [comment]
The metadata of the debian repo in general looks strange when comparing to the official repository for example:
deb.nodesource.com:
```
Origin: . nodistro
Label: . nodistro
Suite: nodistro
Codename: nodistro
```
Debian:
```
Origin: Debian
Label: Debian-Security
Suite: stable-security
Version: 12
Codename: bookworm-security
```

**Comment by JesusPaz** [comment]
We had a problem and these versions were missing, but now they are in the repo. Sorry for the confusion.
To install node.js v18:
```
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\
sudo apt-get install -y nodejs

```
