### ISSUE TITLE
[ERROR] Node.js 16 script throws with script/repo deprecated error

### ISSUE THREAD

**Issue by mxschmitt** [nodesource/distributions#1753]
**Describe your bug**

[`setup_16.x`](https://deb.nodesource.com/setup_16.x) will throw with `repo_deprecation_warning` while the [`setup_18.x`](https://deb.nodesource.com/setup_18.x) will not.

We are aware that Node.js 16 is EOL, but we need it, since thats the last supported Node.js version for Ubuntu 18.04.

There seems to be a left-over change which introduced the warning/60s delay which was forgotten to be removed.

**Distribution Information:**

- OS: Ubuntu
- Version: not relevant (but still Ubuntu 18)

**Node Version:** 16

- Node: 16.x

**To Reproduce**

1. Execute `https://deb.nodesource.com/setup_16.x` and it will run into `repo_deprecation_warning` while it should not anymore, since the scripts are not deprecated anymore.

**Expected behavior**

Just works and no 60s delay.

**Screenshots**

<img width="743" alt="image" src="https://github.com/nodesource/distributions/assets/17984549/d76df512-ef1e-4d6b-86e5-0432dbdaecd8">

**Additional information**

While the script got deprecated but then again un-deprecated, it looks like this warning is a leftover from making them deprecated.

**Comment by jameshallam93** [comment]
I am also seeing this issue.

**Comment by khanifikhsanudin** [comment]
I am also seeing this issue.

**Comment by srl295** [comment]
@gwhizofss it does indeed say "the scripts are back" but it's easy to miss.   Yes, I just moved away from the scripts in time for them to come back 😆 

Could we have an FAQ entry - "are the scripts deprecated?" 

Also it seems like the _manual_ instructions are no longer there. There's [migration guidance](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository) in the wiki. but is that old? new? obsolete?

**Comment by JesusPaz** [comment]
The scripts are back, but only for the Node.js versions currently supported. These scripts are solely designed to configure the repository. You have the flexibility to modify them, especially if you wish to remove the 60-second delay. Remember, all of this is open source – you are free to download the script and tailor it to your needs. That's the beauty of Linux; it empowers you to make technology work for you in the way you want it to.

A solution for your problem:
```
# Download the script
curl -sL https://deb.nodesource.com/setup_16.x -o setup_16.x

# Make the script executable
chmod +x setup_16.x

# Remove all instances of 'sleep'
sed -i '/sleep/d' setup_16.x

# Execute the script
sudo ./setup_16.x
```

**Comment by Carlo24Mzer** [comment]
@JesusPaz THank you. How about the missing Release file for 16x? WIthout it, the install also fails, and it messes up any use of apt update until I remove the 16x from the update list.
