### ISSUE TITLE
FAQ on scripts and manual install /

### ISSUE THREAD

**Issue by srl295** [nodesource/distributions#1759]
As noted in #1753 which I missed the first time, "the scripts are back"… just when I moved away from them!

- Could we have an FAQ entry - "Q: are the scripts deprecated?" 

- Also it seems like the _manual_ instructions are no longer there. There's [migration guidance](https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository) in the wiki. but is that old? new? obsolete? Are manual installations supported anymore?

Thanks and thanks for the distro.

**Comment by JesusPaz** [comment]
#1761

**Comment by JesusPaz** [comment]
Thank you for reporting the issue. I have already created a PR to address it, and the wiki has been updated accordingly. There are still some items pending updates, but we are addressing them one issue at a time.

**Comment by AlvesJorge** [comment]
Hey all,
Just so I understand, at some point using nodesource through
`curl -fsSL https://deb.nodesource.com/setup_18.x`
was intended.
Last year at some point it was announced that this method would no longer be supported, and we would need to use a different method.
But now its recommended again to use the `curl setup_xx.x` method? 

Is this correct?
