### ISSUE TITLE
[ERROR] Node.js 18 on Ubuntu22.04 cache update fail

### ISSUE THREAD

**Issue by muja** [nodesource/distributions#1769]
**Describe your bug**
Since recently, I cannot connect to deb.nodesource.com using APT or Firefox. Other clients work fine.
Note that I'm behind a proxy and have not had this issue until yesterday. This morning it also seemed to work fine (~10 hours before this post). Now it broke again. The error is only reproducible behind our proxy, direct connections work fine.

I believe this is a slight misconfiguration in either the deb.nodesource.com TLS that some clients are able to recover from. Or it's our corporate proxy, but this is limited to deb.nodesource.com. I've also noticed that this site works only in browsers with SNI support. In the past, and take this with a grain of salt, I've had a similar error happen (website worked fine in Chrome, but failed in Firefox), because I had used the wrong `.pem` file in my nginx config.

Maybe this is an easy change on the node maintainers' side, to get it back to working?
If not, and if nothing's changed on the TLS side the last 2 days, please do tell me so I can try and find out who is responsible for our corporate proxy.

Thank you!

**Distribution Information:**

- OS: Ubuntu
- Version jammy 22.04

**Node Version:**

- Node: Node.js v18.x

**To Reproduce**
Not reproducible unless you are behind the same proxy, but:

- add `deb https://deb.nodesource.com/node_18.x jammy main` to `/etc/apt/source.list.d/nodesource.list`
- run `sudo apt update`

**Expected behavior**
Success updating index/APT and Firefox can connect without problems

**Screenshots**
![image](https://github.com/nodesource/distributions/assets/3709726/a9044201-d09b-4db2-aa6b-fdc114294480)
![image](https://github.com/nodesource/distributions/assets/3709726/4b32edfb-7da3-4bff-966d-cd3d488bae10)

**Comment by JesusPaz** [comment]
try using:
```
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\
sudo apt-get install -y nodejs
```

**Comment by muja** [comment]
I'm not sure what that would change? All the script effectively does is put `deb https://deb.nodesource.com/node_18.x nodistro main` into the apt sources (with the `[arch=foo signed-by=bar]`) and calls `apt update`.
The problem here is clearly not the GPG key, but the TLS connection. Yesterday after your comment it was working again and now it works as well. As I said I have no idea who's responsible, `deb.nodesource.com` or our corporate proxy.

I just wanna know: have you been doing any changes to your server config these last few days?

**Comment by schmitch** [comment]
> try using:
> 
> ```
> curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\
> sudo apt-get install -y nodejs
> ```

I use the script and it did not work and I upgraded to 20, also did not work.

**Comment by riosje** [comment]
@muja it looks like you're behind some proxy and it has problems with the certificates.
there is not any other report about SSL issues.
We have millions of requests per day, no other person reported this issue.

**Comment by muja** [comment]
That was my assumption, which is why my question specifically was whether the configuration has somehow changed in the last few days. Still hasn't been answered BTW.
It doesn't necessarily mean it's gonna break normal users, but it might trigger a corner case in the proxy and `deb.nodesource.com` was _the only_ server that doesn't work out of about a few dozens tested.

**Comment by riosje** [comment]
@muja this error is clearly on the proxy side, we didn't changed in the past months nothing related to the TLS version or any other config related to the encryption.
Also while you tried to describe good enough the issue, I would appreciate you give us more detailed technical information, how are we supposed to reproduce this to fix it?

Do you have some logs from the proxy side?

What's the output when you use `curl -vvv` to download the key.
