### ISSUE TITLE
Openssl slowness with ARM Marvell Armada 370/XP processors

### ISSUE THREAD

**Issue by shouze** [nodesource/distributions#177]
@wmark has compiled more recent/adapted openssl lib with support for ChaCha20-Poly1305 from BoringSSL and so on: https://community.scaleway.com/t/blitznote-ubuntu-repository/1087

I doubt that the statically linked openssl lib bringed with node for arm have those patches included as I encounter the same slowness as described with my curl example in https://github.com/scaleway/kernel-tools/issues/148#issuecomment-158061180 with node requesting one of my https apis.

For the record, for the actual node 5.1.0 release:
```
node -pe process.versions
{ http_parser: '2.6.0',
  node: '5.1.0',
  v8: '4.6.85.31',
  uv: '1.7.5',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '47',
  openssl: '1.0.2d' }
```

**Comment by shouze** [comment]
@chrislea as I explained to @wmark in https://github.com/scaleway/kernel-tools/issues/148#issuecomment-158459681I will compile a nodejs binary of my own to check how to increase https performance on Scaleway C1 machines.

Can you point me out how you build your node arm debs please? Do you use the official nodejs repo? With some patches?

Can I start from this one?
https://deb.nodesource.com/node_5.x/pool/main/n/nodejs/nodejs_5.1.0-2nodesource1~vivid1.debian.tar.gz

**Comment by chrislea** [comment]
@shouze the build sources are right alongside the binary packages. So yes, everything you need is in the file you reference. The `rules` file in the debian directory specifically has what you're interested in, though it's currently super boring:

```make
config.status:
        dh_testdir
        dh_quilt_patch
        ./configure --prefix=/usr --with-intl=small-icu \
        --with-icu-source=$(CURDIR)/debian/icu
        touch $@
```

**Comment by shouze** [comment]
@chrislea ok I've built a release but anyway the best thing is to wait for openSSL upgrade. The good news is that [openssl 1.1.0](https://github.com/openssl/openssl/releases/tag/OpenSSL_1_1_0-pre1) is coming shortly with so great improvements (chacha20, faster curves and so on)

**Comment by retrohacker** [comment]
This looks to be something time will/has solve/solved when a new version of OpenSSL ships/shipped.

Closing this for now, please correct me if I'm wrong.
