### ISSUE TITLE
[ERROR] npm not available anymore after installing nodejs on Debian

### ISSUE THREAD

**Issue by gremo** [nodesource/distributions#1770]
**Describe your bug**
`npm` is not available anymore aflter installing `nodejs` package on Debian. I'm pretty sure it was installed with `nodejs` ultil December maybe, I'm maintaing some Docker images with Node and `npm` was always installed with it.

**Distribution Information:**

- OS: Debian 
- Version: 12 (bookworm)

**Node Version:**

- Node: 18

**To Reproduce**
Steps to reproduce the behavior (`NODE_VERSION` is 18 in this case):

```
mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_VERSION.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
apt-get install -y --no-install-recommends nodejs
```

**Expected behavior**
`npm` executable is installed along with `node`.

**Comment by riosje** [comment]
Hi @gremo if you run `node -v` what's the output?
I think you did not install node18, somehow you installed an older version of node.
Try our installation script is really easy

```
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\
sudo apt-get install -y nodejs
```

**Comment by riosje** [comment]
@gremo I'm glad it is working now for you.
Yes as you mentions it is needed to use the pin option, that's why I ask you to use our installation script which creates the repo properly.
