### ISSUE TITLE
[ERROR] Node.js 18 on CentOS 7 fails: Requires: libstdc++.so.6(GLIBCXX_3.4.20)(64bit)

### ISSUE THREAD

**Issue by zrhoffman** [nodesource/distributions#1774]
**Describe your bug**
NodeJS version `nodejs-18.16.0-1nodesource.x86_64` fails to install on CentOS 7 due to libraries being lower API versions than the RPM expects.

**Distribution Information:**

- OS: CentOS 7
- Version 7.9.2009

**Node Version:**

- Node: Node.js v18.x

**To Reproduce**

1. Execute CentOS Docker Image 7 (`centos:7`)
2. Execute Installation instructions for Node.js v18:
   ```shell
   rpm -Uvh https://rpm.nodesource.com/pub_18.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
   yum -y install nodejs
   ```

**Expected behavior**
NodeJS v18 is installed

**Actual behavior**
```shell
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 2:18.16.0-1nodesource will be installed
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.21)(64bit) for package: 2:nodejs-18.16.0-1nodesource.x86_64
--> Processing Dependency: libc.so.6(GLIBC_2.28)(64bit) for package: 2:nodejs-18.16.0-1nodesource.x86_64
--> Processing Dependency: libm.so.6(GLIBC_2.27)(64bit) for package: 2:nodejs-18.16.0-1nodesource.x86_64
--> Processing Dependency: libstdc++.so.6(CXXABI_1.3.9)(64bit) for package: 2:nodejs-18.16.0-1nodesource.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.20)(64bit) for package: 2:nodejs-18.16.0-1nodesource.x86_64
--> Finished Dependency Resolution
Error: Package: 2:nodejs-18.16.0-1nodesource.x86_64 (nodesour
           Requires: libstdc++.so.6(GLIBCXX_3.4.20)(64bit)
Error: Package: 2:nodejs-18.16.0-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(GLIBCXX_3.4.21)(64bit)
Error: Package: 2:nodejs-18.16.0-1nodesource.x86_64 (nodesource)
           Requires: libm.so.6(GLIBC_2.27)(64bit)
Error: Package: 2:nodejs-18.16.0-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(CXXABI_1.3.9)(64bit)
Error: Package: 2:nodejs-18.16.0-1nodesource.x86_64 (nodesource)
           Requires: libc.so.6(GLIBC_2.28)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Additional context**

Installing NodeJS v16 on CentOS 7 works:

```shell
rpm -Uvh https://rpm.nodesource.com/pub_16.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
yum -y install nodejs
```

**Comment by jonathanm28** [comment]
> Hi, Node18 and Node20 requires `GLIBC >=2.27` need to upgrade your SO.

hi, @riosje  what is SO? Do you mean the OS version needs to be updated, is there documentation which mentions this or provides this conclusion?

**Comment by riosje** [comment]
@jonathanm28 

>  hi, @riosje what is SO? 
sorry  it was a glitch in my mind at moment of writing the comment, I'm native spanish speaker.
**SO** is the abbreviation for `Sistema Operativo` = OS `Operating System`
https://es.wikipedia.org/wiki/Sistema_operativo

you can find the min reqs here to run `Node18`
https://github.com/nodejs/node/blob/v18.x/BUILDING.md#platform-list

We have also the supported distros documented
https://github.com/nodesource/distributions?tab=readme-ov-file#rpm-supported-versions

**Comment by n0099** [comment]
Workaround: https://github.com/nodejs/node/issues/42351#issuecomment-2561221715
