### ISSUE TITLE
[ERROR] Node.js 20 on Ubuntu 22.04 Installation fail

### ISSUE THREAD

**Issue by jorgegutierrez** [nodesource/distributions#1779]
**Describe your bug**

dpkg: error processing archive /var/cache/apt/archives/nodejs_20.11.1-1nodesource1_amd64.deb (--unpack):
 trying to overwrite '/usr/include/node/common.gypi', which is also in package libnode-dev 12.22.9~dfsg-1ubuntu3.3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_20.11.1-1nodesource1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Distribution Information:**

- OS: Ubuntu
- Version: 22.04.4 LTS 

**Node Version:**

- Node.js v20.x

**To Reproduce**

1- sudo apt-get update && sudo apt-get install -y ca-certificates curl gnupg
2- curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
NODE_MAJOR=20
3- echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
4- sudo apt-get update && sudo apt-get install nodejs -y

**Expected behavior**
Install Node.js 20 and npm
![Screenshot from 2024-02-28 14-06-07](https://github.com/nodesource/distributions/assets/4029851/2c1ed066-ff06-422a-a2cb-5a8d4217f9f5)

**Comment by riosje** [comment]
Hi @jorgegutierrez I'm so sorry current we do not support i386 arch.
You maye get an unofficial build in the following link.

https://unofficial-builds.nodejs.org/
https://unofficial-builds.nodejs.org/download/release/v20.11.1/
