### ISSUE TITLE
Linux Mint 17.3 rosa

### ISSUE THREAD

**Issue by yxtwang** [nodesource/distributions#178]

**Comment by rvagg** [comment]
Thanks @yxtwang, we don't normally support distributions that are not GA and Rosa is still in Beta. Given that it's based on Ubuntu Trusty we could probably add it, but in the meantime if you follow the [manual installation instructions](https://github.com/nodesource/distributions#manual-installation) and use "trusty" as the distribution then it should work for you.

**Comment by deathmood** [comment]
emm.. actually it has been released already.. no support as for today(( install with "trusty" worked

**Comment by rvagg** [comment]
Thanks @deathmood, I've updated the setup scripts with this, would you mind giving it a go and letting us know whether it works?
