### ISSUE TITLE
Missing RPM-Packages in Official nodesource-repository - nodejs 18.19.0 / 18.19.1

### ISSUE THREAD

**Issue by janfickler** [nodesource/distributions#1782]
Hi,

i found out that in the official nodesource-repository are not the latest nodejs-18 version available.

we using your official public repository -  [https://rpm.nodesource.com/pub_18.x/el/8/x86_64](https://rpm.nodesource.com/pub_18.x/el/8/x86_64)

on the nodejs.org webserver there is the newer binary for v18.19.1 available, but no RPM packages.

available are on your repository:
- nodejs-18.17.1-1nodesource.x86_64.rpm
- nodejs-docs-18.17.1-1nodesource.noarch.rpm
- nodejs-devel-18.17.1-1nodesource.x86_64.rpm

 the latest version is 18.19.0 / 18.19.1 which have some important bugfixes and security fixes included.

Could you please build and provide that RPM-Packages ?

**Comment by riosje** [comment]
Hi @janfickler it looks like you're using our old repository.
please try to configure again the repository using our installation script.

https://github.com/nodesource/distributions?tab=readme-ov-file#as-root-2
