### ISSUE TITLE
[ERROR] npm unavailable after installing on python:3.11-slim-bookworm docker image

### ISSUE THREAD

**Issue by SamStephens** [nodesource/distributions#1790]
**Describe your bug**

When I try and install using the setup script against the base Docker image `python:3.11-slim-bookworm`, `npm` is not available.

The failure looks similar to https://github.com/nodesource/distributions/issues/1770, however I'm using the setup script as that issue says I should. I've tried using the pinning workaround detailed in that issue, and it doesn't help.

The issue appears to be with using the slimmed down base image, using `python:3.11-bookworm` as the image does work. However if the failure is because the slimmed down base image doesn't include required dependencies, I'd expect the setup script to fail, not succeed without `npm` available,.

**Distribution Information:**

- OS: Debian
- Version: Bookworm
- Base docker image python:3.11-slim-bookworm

**Node Version:**

- Node: 20.x

**To Reproduce**

This Dockerfile will fail with the error `npm: not found`.

```
FROM python:3.11-slim-bookworm

RUN apt-get update --fix-missing && apt-get upgrade -y && apt-get dist-upgrade -y

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get install -y nodejs
RUN node -v
RUN npm -v
```

As will this one with [the pinning fix](https://github.com/nodesource/distributions/issues/1579#issuecomment-1594728038).

```
FROM python:3.11-slim-bookworm

RUN apt-get update --fix-missing && apt-get upgrade -y && apt-get dist-upgrade -y

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
RUN echo "Package: nodejs" >> /etc/apt/preferences.d/preferences
RUN echo "Pin: origin deb.nodesource.com" >> /etc/apt/preferences.d/preferences
RUN echo "Pin-Priority: 1001" >> /etc/apt/preferences.d/preferences
RUN apt-get install -y nodejs
RUN node -v
RUN npm -v
```

This Dockerfile will succeed - the only difference to the original failure Dockerfile is we're not using the slim version of the base image:

```
FROM python:3.11-bookworm

RUN apt-get update --fix-missing && apt-get upgrade -y && apt-get dist-upgrade -y

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get install -y nodejs
RUN node -v
RUN npm -v
```

**Expected behavior**

Either the setup script should have succeeded, and npm be available, or the setup script should have failed (probably complaining about missing build dependencies due to the usage of the slim base image).

**Screenshots**
N/A

**Additional context**
N/A

**Comment by riosje** [comment]
Hi @SamStephens.
I tried you Dockerfile but it fails because at first `curl` is not installed, for that reason 
Try installing `curl` at first :

```Dockerfile
FROM python:3.11-slim-bookworm

RUN apt-get update -y && apt-get install curl -y
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get install -y nodejs
RUN node -v
RUN npm -v
```

![installing](https://github.com/nodesource/distributions/assets/55195249/4c199eab-72b5-41eb-b234-349235237ca2)

**Comment by SamStephens** [comment]
Oh okay, that's embarrassing, apologies for the mistake. I was confused here because

```
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
```

Has an exit code of 0, hence Dockerfile execution continues, whereas

```
curl -fsSL https://deb.nodesource.com/setup_20.x
```

Has an exit code of 127.

I wonder if there's an alternative way to formulate a command to download and run https://deb.nodesource.com/setup_20.x that will fail if curl is not present?

**Comment by riosje** [comment]
Hi @SamStephens that's why we have the following in the README.

```
curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
apt-get install -y nodejs
```

The `apt-get install` will not be executed unless the curl returns an exit code 0.
That's what the `&&` operator does.

**Comment by SamStephens** [comment]
@riosje unfortunately the formulation with the `&&` is subject to the same issue.

As I said above, `curl -fsSL https://deb.nodesource.com/setup_20.x | bash -` has an exit code of 0 when curl is not available. I'm not that deep on shell internals, but it appears the exit code is the zero from the `bash` that is the pipe destination, not the `curl` command source with it's 127 exit code.

This is why I formulated things as I did, from a Dockerfile perspective,

```
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get install -y nodejs
```

Is functionally equivalent to

```
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs
```

with execution being halted before `apt-get` runs if `curl -fsSL https://deb.nodesource.com/setup_20.x | bash -` has a non-zero exit code.

You can see this empirically with the Dockerfile

```
FROM python:3.11-slim-bookworm

RUN apt-get update --fix-missing && apt-get upgrade -y && apt-get dist-upgrade -y

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs
RUN node -v
RUN npm -v
```

Which is subject to the same issue as my original reproduction.
