### ISSUE TITLE
[ERROR] Node.js 20.9.0 or any version lower than 20.12.0 on Ubuntu20.04 Installation fails

### ISSUE THREAD

**Issue by thisis-akash** [nodesource/distributions#1793]
**Describe your bug**
The installation process is not agile enough or configurable to install a specific version of Node. If we run the same installation script at different points in time, it might install a different minor version leading to inconsistency among systems running a particular software expecting things to work according to implementations in a specific minor version.

**Distribution Information:**

- OS: Ubuntu
- Version: focal (20.04)

**Node Version:**

- Node: Tried this with v20.x but I think it is applicable to versions before this too.

**To Reproduce**
One of 3 ways
1. Try specifying node version to the apt-get install command like so: sudo apt-get install -y nodejs=20.9.0
2. or try configuring the script to install a specific version like so, curl -fsSL https://deb.nodesource.com/setup_20.x | bash -s -- --version=20.9.0
3. or try mentioning the version directly in the url like so, curl -fsSL https://deb.nodesource.com/setup_20.9.0 | sudo -E bash - &&\
sudo apt-get install -y nodejs

**Expected behavior**
All 3 ways will result into failure or installing of 20.12.0 which is the latest LTS minor version at the time of writing

**Screenshots**
NA

**Additional context**
Some applications might want to install or rely on specific version of node, specific to the degree of a minor version. In our case I was informed that some bug was introduced in 20.12 or 20.10 maybe and we want to stick to a version lower than that. I was told to implement installation of a specific minor version so that whenever we install node on different environments at different times, all of them have the same version. 

There should not be an instance where just because we are installing node at a later point in time, a different minor version is installed while a different minor version was installed on systems that ran the script in the past. This behaviour should be made configurable. Be default, installing latest LTS minor version makes sense but not being able to configure it, is something that should be changed IMHO.

**Comment by riosje** [comment]
Hi @thisis-akash
It works, I think you're not following the instructions.

If you execute the command `apt-cache policy nodejs` you will see all the packages/version has the below format:
`<version>-1nodesource1` 

for this reason you should be executing the following command to install the specified version.

```shell
apt-get install -y nodejs=20.9.0-1nodesource1
```


Let me know if this works for you please.
