### ISSUE TITLE
[ERROR] Node.js 20 on Ubuntu20.04 Installation fail with non-default umask

### ISSUE THREAD

**Issue by lucasmo** [nodesource/distributions#1795]
**Describe your bug**
The official installer fails if a non-default umask is used.

**Distribution Information:**

- OS: Ubuntu
- Version: focal (20.04)

**Node Version:**

- Node: 20

**To Reproduce**

```
$ curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash - 
2024-04-10 00:15:47 - Installing pre-requisites
[ ... ]
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[ ... ]
Get:6 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
Err:6 https://deb.nodesource.com/node_20.x nodistro InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2F59B5F99B1BE0B4
Reading package lists...
W: GPG error: https://deb.nodesource.com/node_20.x nodistro InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2F59B5F99B1BE0B4
E: The repository 'https://deb.nodesource.com/node_20.x nodistro InRelease' is not signed.
2024-04-10 00:15:51 - Error: Failed to run 'apt-get update' (Exit Code: 0)
```

**Expected behavior**
nodesource apt repo is installed

**Additional context**
For security purposes, our company requires the default system umask to be 0007.
This means that /usr/share/keyrings/nodesource.gpg has a file mode of 640.

As a workaround not requiring modification of the script, this solves the issue:
```
(echo '#!/bin/bash'; echo 'umask 0002'; curl -fsSL https://deb.nodesource.com/setup_20.x) | sudo bash -
```
It would be nicer if the script set the mode of the file or ensured the umask was correct.

**Comment by JesusPaz** [comment]
#1819
