### ISSUE TITLE
npm ERR! Linux 3.10.0-229.7.2.el7.x86_64

### ISSUE THREAD

**Issue by hongluovz** [nodesource/distributions#180]
While doing  Hygieia build, I got this error in NPM:

[INFO] Found NPM version 2.7.1
[INFO]
[INFO] --- frontend-maven-plugin:0.0.25:npm (npm install) @ UI ---
[DEBUG] Configuring mojo com.github.eirslett:frontend-maven-plugin:0.0.25:npm from plugin realm ClassRealm[plugin>com.github.eirslett:frontend-maven-plugin:0.0.25, parent: sun.misc.Launcher$AppClassLoader@3ad6a0e0]
[DEBUG] Configuring mojo 'com.github.eirslett:frontend-maven-plugin:0.0.25:npm' with basic configurator -->
[DEBUG]   (f) arguments = install
[DEBUG]   (f) installDirectory = /apps/opt/tools/Hygieia-master/UI
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@49bbdad
[DEBUG]   (f) skip = false
[DEBUG]   (f) skipTests = false
[DEBUG]   (f) workingDirectory = /apps/opt/tools/Hygieia-master/UI
[DEBUG]   (f) execution = com.github.eirslett:frontend-maven-plugin:0.0.25:npm {execution: npm install}
[DEBUG] -- end configuration --
[INFO] Running 'npm install --color=false --proxy=http://user:pass@my_proxy:80' in /apps/opt/tools/Hygieia-master/UI
[ERROR] npm ERR! Linux 3.10.0-229.7.2.el7.x86_64
[ERROR] npm ERR! argv "/apps/opt/tools/Hygieia-master/UI/node/node" "/apps/opt/tools/Hygieia-master/UI/node/node_modules/npm/bin/npm-cli.js" "install" "--color=false" "--proxy=http://user:pass@my_proxy:80"
[ERROR] npm ERR! node v0.12.0
[ERROR] npm ERR! npm  v2.7.1
[ERROR] npm ERR! code ENOSPC
[ERROR] npm ERR! errno -28
[ERROR]
[ERROR] npm ERR! nospc ENOSPC, write
[ERROR] npm ERR! nospc This is most likely not a problem with npm itself
[ERROR] npm ERR! nospc and is related to insufficient space on your system.
[ERROR]
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /apps/opt/tools/Hygieia-master/UI/npm-debug.log

**Comment by retrohacker** [comment]
`ENOSPC` means Error No Space. It seems whatever directory you are building in has run the drive out of space. This doesn't appear to be an issue with the NodeSource repo.
