### ISSUE TITLE
Nodejs and git  

### ISSUE THREAD

**Issue by kaaya-27** [nodesource/distributions#1806]
Nodejs and Git 
I encountered error after installing nodejs v20.15.0 it encountered call error npm after updating the npm it got resolved but it shows error with git and nodeJs

Distribution Information:
npm error code ENOENT
npm error syscall spawn C:\Program Files\Git\cmd
npm error path C:\website\youtube-clone-react\node_modules\esbuild
npm error errno -4058
npm error enoent spawn C:\Program Files\Git\cmd ENOENT
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: C:\Users\kaviy\AppData\Local\npm-cache\_logs\2024-06-25T07_20_28_330Z-debug-0.log

npm attempts to use a Git command located at C:\Program Files\Git\cmd, but it cannot find this directory or file. when I use npm installation or npm start it throws this error. i could not create any other new react project 

OS: Windows 11

Node Version: v20.15.0
Npm version: 10.8.1

**Expected behavior**
it has to download the dependencies if I use npm install but it shows error in git path. the environment variable contains the git path even though it throws error

**Screenshots**
![Screenshot 2024-06-25 123538](https://github.com/nodesource/distributions/assets/89698472/7335123c-5492-4aac-a99f-6b1c563160f6)

**Additional context**
I have uninstalled and installed but the environment variable is not updating for npm I have to manually update the path

**Comment by JesusPaz** [comment]
Hi, we don't provide packages for windows. So, this is not the right repo to post the issue. But, this might help you https://github.com/nodejs/help/issues/3628
