### ISSUE TITLE
[ERROR] Node.js 20.x on Ubuntu 22.04 Installation fail due missing directory

### ISSUE THREAD

**Issue by UlisesGascon** [nodesource/distributions#1808]
**Describe your bug**
The installation scripts silently fail if the directory `/etc/apt/sources.list.d/` does not exist in a Debian-based environment.

**Distribution Information:**

- OS: Ubuntu
- Version: 22.04.4 LTS
- Other info if applicable: kernel 6.5.0-41-generic and using ARM

**Node Version:**

- Node: 20.x

**To Reproduce**

1. Follow the official guide: https://docs.nodesource.com/nsolid/5.0/docs#installing-nsolid-packages
2. Execute: `curl -fsSL https://deb.nodesource.com/setup_20.x | bash -`
3. The command seems to be executed correctly, but I got an installation error.

**Screenshots**

Error:

![Screenshot from 2024-07-02 09-40-29](https://github.com/nodesource/distributions/assets/5110813/1b391b66-d0e1-4612-9df7-ab63da72e6aa)

**Additional context**
I solved this problem by running `sudo mkdir -p /etc/apt/sources.list.d`.

![Screenshot from 2024-07-02 09-41-16](https://github.com/nodesource/distributions/assets/5110813/831fe349-f2aa-42cd-84a3-4702c965b6d9)

Let me know if you find this useful, so I can create a PR adding this patch. Maybe it is a local issue due to my personal configuration and not a common one.

**Comment by JesusPaz** [comment]
Hi @UlisesGascon, thank you for reporting this issue. I will look into it, I remember a similar issue and I think it was solved.

**Comment by riosje** [comment]
HI @UlisesGascon could you try it again, the issue should be gone with the last fix.

**Comment by UlisesGascon** [comment]
Thanks for the quick fix! It is working fine now :+1:
