### ISSUE TITLE
[ERROR] Node.js 18.x on Ubuntu22.04 Installation fail because of missing gpg key in https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key

### ISSUE THREAD

**Issue by jbwn** [nodesource/distributions#1818]
**Describe your bug**
The installation of Node.js 18.x fails because the gpg key used to sign the repo is 
**Distribution Information:**

- OS: Ubuntu
- Version: jammy 22.04

**Node Version:**

- Node: Node.js v18.x

**To Reproduce**

1. Use Ubuntu 22.04
2. Execute Installation instructions for Node.js v18.x
Script fails at this step: 
```
Get:5 https://deb.nodesource.com/node_18.x nodistro InRelease [12.1 kB]
Err:5 https://deb.nodesource.com/node_18.x nodistro InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2F59B5F99B1BE0B4
Reading package lists... Done
W: GPG error: https://deb.nodesource.com/node_18.x nodistro InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2F59B5F99B1BE0B4
E: The repository 'https://deb.nodesource.com/node_18.x nodistro InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
2024-08-08 10:06:52 - Error: Failed to run 'apt-get update' (Exit Code: 0)

```

**Expected behavior**
Product installs (repo is signed/added)

**Additional context**
The Repo of 18.x for Ubuntu 22.04 / jammy is signed with key 
```
curl -fsSL --compressed   "https://deb.nodesource.com/node_18.x/dists/jammy/InRelease" | gpg --verify
gpg: Signature made Wed 09 Aug 2023 07:27:40 PM UTC
gpg:                using RSA key 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280

```
but the gpg file at "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
does not contain this key anymore (it used to in the past)
```
curl -fsSL --compressed   "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key" | gpg --dry-run --show-keys --with-subkey-fingerprint --keyid-format LONG -
pub   rsa2048/2F59B5F99B1BE0B4 2016-05-23 [SC]
      6F71F525282841EEDAF851B42F59B5F99B1BE0B4
uid                            NSolid <nsolid-gpg@nodesource.com>
sub   rsa2048/7E9656125E955B26 2016-05-23 [E]
      0FA5ECC8C0CA58863C0AC5867E9656125E955B26

```

**Comment by montanoeuse** [comment]
This could be related to https://github.com/nodesource/distributions/issues/1688.
Fix: chmod a+r /usr/share/keyrings/nodesource.gpg

**Comment by jbwn** [comment]
> This could be related to permission on the gpg file`

Thanks for the suggestion, unfortunately we already checked that beforehand and excluded it as the source of the error.
Looking over it again I see why you suggested it though and my steps to reproduce might be misleading.
The script actually uses the nodistro repo at the point the error occured and we still have jammy specific repos in our scripts.

I just used the script on a test system and since it failed as well I thought it was the same reason why the manual install failed.

So our solution will be to switch from jammy repo to nodistro which is signed by the new key. (And also the suggested way in the repo readme)

Thanks for you help @montanoeuse 

So from our point the intial error we had is resolved.

I'll leave this open however because the error from the script is still valid, maybe it would be a good idea to include something in the script that checks the downloaded keyfile permissions and corrects them.
Additional Infomation to reproduce the error:
system has default umask 027

**Comment by riosje** [comment]
Hello guys, thanks for sharing your experience and collaboration debugging possible issues with our installation process.
Just let's break down this because it seems to be different scenarios.

@montanoeuse mentions there is an issue with the perms of the key and @jbwn confirms it happens when the system folder has umask 027, is that right?

the original issue was the gpg key mismatch the configured repo, but it seems you didn't used our installation scriot but configured the repo manually @jbwn, is that right?
Also you mention you had `jammy` as repo instead of `norepo` we switched from managing packages for each distro to having a single package for everyone using the `norepo` code, was that the root cause of this issue?

**Comment by jbwn** [comment]
> @montanoeuse mentions there is an issue with the perms of the key and @jbwn confirms it happens when the system folder has umask 027, is that right?
> 
Yes, this is correct.
> the original issue was the gpg key mismatch the configured repo, but it seems you didn't used our installation scriot but configured the repo manually @jbwn, is that right? Also you mention you had `jammy` as repo instead of `norepo` we switched from managing packages for each distro to having a single package for everyone using the `norepo` code, was that the root cause of this issue?
Correct as well.

**Comment by JesusPaz** [comment]
#1819
