### ISSUE TITLE
Package conflicts fail with fresh install on Debian Jessie

### ISSUE THREAD

**Issue by mafrosis** [nodesource/distributions#182]
With a fresh ISO install of Debian Jessie 8.2:

    > sudo -s
    > apt-get install apt-transport-https
    Building dependency tree... Done
    The following NEW packages will be installed:
      apt-transport-https
    .. snip ..
    > curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
    OK
    > echo 'deb https://deb.nodesource.com/node_5.x jessie main' > /etc/apt/sources.list.d/node5source.list
    > apt-get update
    .. snip ..
    > apt-get install npm
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
     npm : Depends: nodejs but it is not going to be installed
           Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
           Depends: node-ansi (>= 0.3.0-2) but it is not going to be installed
           Depends: node-ansi-color-table but it is not going to be installed
           Depends: node-archy but it is not going to be installed
           Depends: node-block-stream but it is not going to be installed
           Depends: node-fstream (>= 0.1.22) but it is not going to be installed
           Depends: node-fstream-ignore but it is not going to be installed
           Depends: node-github-url-from-git but it is not going to be installed
           Depends: node-glob (>= 3.1.21) but it is not going to be installed
           Depends: node-graceful-fs (>= 2.0.0) but it is not going to be installed
           Depends: node-inherits but it is not going to be installed
           Depends: node-ini (>= 1.1.0) but it is not going to be installed
           Depends: node-lockfile but it is not going to be installed
           Depends: node-lru-cache (>= 2.3.0) but it is not going to be installed
           Depends: node-minimatch (>= 0.2.11) but it is not going to be installed
           Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
           Depends: node-gyp (>= 0.10.9) but it is not going to be installed
           Depends: node-nopt (>= 3.0.1) but it is not going to be installed
           Depends: node-npmlog but it is not going to be installed
           Depends: node-once but it is not going to be installed
           Depends: node-osenv but it is not going to be installed
           Depends: node-read but it is not going to be installed
           Depends: node-read-package-json (>= 1.1.0) but it is not going to be installed
           Depends: node-request (>= 2.25.0) but it is not going to be installed
           Depends: node-retry but it is not going to be installed
           Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
           Depends: node-semver (>= 2.1.0) but it is not going to be installed
           Depends: node-sha but it is not going to be installed
           Depends: node-slide but it is not going to be installed
           Depends: node-tar (>= 0.1.18) but it is not going to be installed
           Depends: node-underscore but it is not going to be installed
           Depends: node-which but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.

Likewise with:

    > sudo -s
    > curl -sL https://deb.nodesource.com/setup_5.x | bash -

**Comment by chrislea** [comment]
This is because you're trying to just install `npm` which isn't what you want to do. Simply do

```bash
apt-get install nodejs
```

as the `nodejs` package we provide includes npm, all the headers, etc.

**Comment by mafrosis** [comment]
My bad @chrislea!

**Comment by ananth777** [comment]
HI,

I am getting the similar error on PI-3, any idea how the issue is resolved



pi@raspberrypi:~ $ sudo apt-get install npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: nodejs but it is not going to be installed
       Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
       Depends: node-ansi (>= 0.3.0-2) but it is not going to be installed
       Depends: node-ansi-color-table but it is not going to be installed
       Depends: node-archy but it is not going to be installed
       Depends: node-block-stream but it is not going to be installed
       Depends: node-fstream (>= 0.1.22) but it is not going to be installed
       Depends: node-fstream-ignore but it is not going to be installed
       Depends: node-github-url-from-git but it is not going to be installed
       Depends: node-glob (>= 3.1.21) but it is not going to be installed
       Depends: node-graceful-fs (>= 2.0.0) but it is not going to be installed
       Depends: node-inherits but it is not going to be installed
       Depends: node-ini (>= 1.1.0) but it is not going to be installed
       Depends: node-lockfile but it is not going to be installed
       Depends: node-lru-cache (>= 2.3.0) but it is not going to be installed
       Depends: node-minimatch (>= 0.2.11) but it is not going to be installed
       Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
       Depends: node-gyp (>= 0.10.9) but it is not going to be installed
       Depends: node-nopt (>= 3.0.1) but it is not going to be installed
       Depends: node-npmlog but it is not going to be installed
       Depends: node-once but it is not going to be installed
       Depends: node-osenv but it is not going to be installed
       Depends: node-read but it is not going to be installed
       Depends: node-read-package-json (>= 1.1.0) but it is not going to be installed
       Depends: node-request (>= 2.25.0) but it is not going to be installed
       Depends: node-retry but it is not going to be installed
       Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
       Depends: node-semver (>= 2.1.0) but it is not going to be installed
       Depends: node-sha but it is not going to be installed
       Depends: node-slide but it is not going to be installed
       Depends: node-tar (>= 0.1.18) but it is not going to be installed
       Depends: node-underscore but it is not going to be installed
       Depends: node-which but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by ananth777** [comment]
Since  not showing on pi 3. Hence problem still remains

**Comment by chrislea** [comment]
I'm not sure what you mean. Assuming you're running Raspbian as the OS, you should remove any previous installs:
```
sudo apt-get remove --purge nodejs* npm*
```
and then run the installer script and actually install our package
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by ananth777** [comment]
Apologies,

On execution of Curl > getting the following
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages

Ign http://d2buw04m05mirl.cloudfront.net jessie/main Translation-en_GB

Ign http://d2buw04m05mirl.cloudfront.net jessie/main Translation-en

Ign http://archive.raspberrypi.org jessie/main Translation-en_GB

Ign http://archive.raspberrypi.org jessie/main Translation-en

Ign http://archive.raspberrypi.org jessie/ui Translation-en_GB

Ign http://archive.raspberrypi.org jessie/ui Translation-en

Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_GB

Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en

Ign http://mirrordirector.raspbian.org jessie/main Translation-en_GB

Ign http://mirrordirector.raspbian.org jessie/main Translation-en

Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_GB

Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en

Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_GB

Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en

Err https://deb.nodesource.com jessie/main armhf Packages

  gnutls_handshake() failed: Error in the pull function.
Ign https://deb.nodesource.com jessie/main Translation-en_GB

Ign https://deb.nodesource.com jessie/main Translation-en

Fetched 1,728 B in 37s (46 B/s)

W: Failed to fetch
https://deb.nodesource.com/node_5.x/dists/jessie/main/binary-armhf/Packages
 gnutls_handshake() failed: Error in the pull function.

E: Some index files failed to download. They have been ignored, or old ones
used instead.
Error executing command, exiting

**Comment by chrislea** [comment]
This is an issue with either your TLS implementation or your network, it's not our repository.

Are you behind a proxy? If so please look at [this issue](https://github.com/nodesource/distributions/issues/9). Thanks.

**Comment by ananth777** [comment]
Sorry to be pain..
Actually i was trying thru VNC, THis time, i plugged the PI 3 to monitor
and on execution of curl >

gn https://deb.nodesource.com jessie/main Translation-en

Reading package lists... Done


## Run `apt-get install nodejs` (as root) to install Node.js v6.x and npm

root@raspberrypi:/home/pi# install Node.js v6.x and npm
install: target ‘npm’ is not a directory
root@raspberrypi:/home/pi# apt-get install nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

----------------------------------------------------------------
The following packages have unmet dependencies:
 npm : Depends: nodejs but it is not going to be installed
       Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
       Depends: node-ansi (>= 0.3.0-2) but it is not going to be installed
       Depends: node-ansi-color-table but it is not going to be installed
       Depends: node-archy but it is not going to be installed
       Depends: node-block-stream but it is not going to be installed
       Depends: node-fstream (>= 0.1.22) but it is not going to be installed
       Depends: node-fstream-ignore but it is not going to be installed
       Depends: node-github-url-from-git but it is not going to be installed
       Depends: node-glob (>= 3.1.21) but it is not going to be installed
       Depends: node-graceful-fs (>= 2.0.0) but it is not going to be
installed
       Depends: node-inherits but it is not going to be installed
       Depends: node-ini (>= 1.1.0) but it is not going to be installed
       Depends: node-lockfile but it is not going to be installed
       Depends: node-lru-cache (>= 2.3.0) but it is not going to be
installed
       Depends: node-minimatch (>= 0.2.11) but it is not going to be
installed
       Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
       Depends: node-gyp (>= 0.10.9) but it is not going to be installed
       Depends: node-nopt (>= 3.0.1) but it is not going to be installed
       Depends: node-npmlog but it is not going to be installed
       Depends: node-once but it is not going to be installed
       Depends: node-osenv but it is not going to be installed
       Depends: node-read but it is not going to be installed
       Depends: node-read-package-json (>= 1.1.0) but it is not going to be
installed
       Depends: node-request (>= 2.25.0) but it is not going to be installed
       Depends: node-retry but it is not going to be installed
       Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
       Depends: node-semver (>= 2.1.0) but it is not going to be installed
       Depends: node-sha but it is not going to be installed
       Depends: node-slide but it is not going to be installed
       Depends: node-tar (>= 0.1.18) but it is not going to be installed
       Depends: node-underscore but it is not going to be installed
       Depends: node-which but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by parlad** [comment]
cann't install npm

**Comment by mckaygerhard** [comment]
> cann't install npm

must unninstall only npm and nodejs prevoulsy installed on your system before install it from nodesource.. this of course have some depens incorrectly managed in comment https://github.com/nodesource/distributions/issues/182#issuecomment-289853520 so the right is first unninstall with --force as `apt-get remove --force nodejs npm` so cos npm are already included in nodejs .. later added the repository and install the nodejs package from nodesource cos due previously command some nodejs-xxx packages on debian are broken.. but will be resolved if you installed the new packaged from nodesource repository

**also i got working nodejs debs from same repository on wheezy.. for download go to : https://t.me/s/vegnuli/283 .. for 386 and amd64**
