### ISSUE TITLE
[ERROR] Not possible to install node 20.17 on Ubuntu Focal 20.04.6

### ISSUE THREAD

**Issue by mitar** [nodesource/distributions#1822]
**Describe your bug**

It seems there is no package for latest 20.x node for Ubuntu Focal 20.04.6. The latest I can find is v20.5.1.

**Distribution Information:**

- OS: Ubunut
- Version: Focal 20.04.6

**Node Version:**

- Node: 20.17.1

**To Reproduce**

Add apt sources:

```
deb https://deb.nodesource.com/node_20.x focal main
deb-src https://deb.nodesource.com/node_20.x focal main
```

`apt-get update`

```bash
$ apt-cache policy nodejs
nodejs:
  Installed: 20.5.1-deb-1nodesource1
  Candidate: 20.5.1-deb-1nodesource1
  Version table:
 *** 20.5.1-deb-1nodesource1 500
        500 https://deb.nodesource.com/node_20.x focal/main amd64 Packages
        100 /var/lib/dpkg/status
     10.19.0~dfsg-3ubuntu1.6 500
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages
     10.19.0~dfsg-3ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
```

**Expected behavior**

There should be a newer node 20.x package available.

**Comment by riosje** [comment]
Hi @mitar you have a misconfiguration in the repo, we're suing `nodistro` as default codename to support all debian based distros.

please refer to the README, and execute the installations scripts to overwrite your current config.
https://github.com/nodesource/distributions?tab=readme-ov-file#using-ubuntu-nodejs-20

**Comment by mitar** [comment]
Awesome. This worked. It seems I had some legacy config. I didn't notice that it has changed. Thanks.
