### ISSUE TITLE
npm: Permission denied

### ISSUE THREAD

**Issue by amazingfate** [nodesource/distributions#183]
verson: 0.12.8-1nodesource1~sid1

**Comment by chrislea** [comment]
This doesn't really give us anything to go on. Can you be more specific about what's going on?

**Comment by amazingfate** [comment]
install https://deb.nodesource.com/node_0.12/pool/main/n/nodejs/nodejs_0.12.8-1nodesource1~sid1_amd64.deb in debian sid
output of ```npm -v``` is "Permission denied"

**Comment by chrislea** [comment]
Ah, thanks for pointing that out. That's a bug we fixed on newer version builds but I forgot to backport the fix to 0.12. I've rebuilt things now. If you do

```bash
apt-get update && apt-get -y upgrade
```

as root it should fix things. Thanks!
