### ISSUE TITLE
Ubuntu 20.04 latest NodeJS 18.x version available is 18.17.1

### ISSUE THREAD

**Issue by mig5** [nodesource/distributions#1837]
**Describe your bug**

I am running Ubuntu 20.04 and using this in my apt sources:

```
deb https://deb.nodesource.com/node_18.x focal main
deb-src https://deb.nodesource.com/node_18.x focal main
```

The latest version of NodeJS 18.x I seem to be able to get on focal is 18.17.1 but it seems there are much newer versions of 18.x available - https://nodejs.org/en/about/previous-releases (e.g 18.20.5).

I'm wondering why Focal doesn't have the latest 18.x version? Thanks

**Distribution Information:**

- OS: Ubuntu
- Version 20.04

**Node Version:**

- Node: v18.17.1

**Comment by NewEraCracker** [comment]
Should use the new `nodistro` location.

My suggestion is that you remove the apt repository of node.js 18 and you reinstall it using the present script which sets it to the new `nodistro` location instead of `focal`.

My two cents.

**Comment by riosje** [comment]
As @NewEraCracker mentioned, you can also run the installation script to configure the new repo.
