### ISSUE TITLE
[Not available] Node.js 23.3 on Ubuntu 24.10 (nodistro) is not available

### ISSUE THREAD

**Issue by Congelli501** [nodesource/distributions#1839]
**Describe your bug**
NodeJS 23.3 is not yet available in the deb repo (nodistro).
The docker image was published a few days after release.

I don't know if the process is automated on your side, is there a bug in a build script ?

**Distribution Information:**

- OS: Ubuntu
- Version: 24.10

**Node Version:**

- Node: 23.3

**To Reproduce**

1. Execute Ubuntu Docker Image 24.10
2. Execute Installation instructions for Node.js 23.x (https://github.com/nodesource/distributions?tab=readme-ov-file#using-ubuntu-nodejs-23)
3. The installed version will be 23.2

**Expected behavior**
Node 23.3 should be available.

**Screenshots**
N/A

**Additional context**
Node 23.2 contains a regression that breaks a lot of web developpment workflow: https://github.com/nodejs/node/issues/55826

**Comment by JesusPaz** [comment]
@Congelli501 We had a problem in our pipelines, but it's fixed now. Let us know if you are able to use the package.

**Comment by Congelli501** [comment]
I successfully upgraded to v23.3.0 using the deb repository, thanks a lot
