### ISSUE TITLE
redhat-release-server-6Server-6.6.0.2.e16.x86_64 Doesn't support v0.12 or v4.x?

### ISSUE THREAD

**Issue by SteveGriffith** [nodesource/distributions#185]

**Comment by tjkierzkowski** [comment]
We've run into the same problem:
```bash
curl -sL https://rpm.nodesource.com/setup_0.12 | bash -

## Installing the NodeSource Node.js 0.12 repo...

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_0.12/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "redhat-release-server-6Server-6.7.0.3.el6.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

The [files in the repository](https://rpm.nodesource.com/pub_0.12/el/6/x86_64/) don't match the url that's constructed in the [setup_0.12 script](https://github.com/nodesource/distributions/blob/master/rpm/setup_0.12#L127-L133) 

Let me know what else I can do to help!

**Comment by harmic** [comment]
I saw the same issue. In fact the repo does contain the nodejs RPMS but the `nodesource-release` RPM is missing from all of the directories.

I was able to work around it by creating a file `/etc/yum.repos.d/nodesource.repo` with content:

    [nodesource]
    name=NodeSource Node.js repo
    baseurl=https://rpm.nodesource.com/pub_0.12/el/6/$basearch
    enabled=1

In fact as far as I can tell, at the moment none of the setup scripts could be working properly. There does not seem to be any nodesource-release RPMs anywhere to be seen.

**Comment by rrva** [comment]
Ditto for RHEL 6.5:

```
# Your distribution, identified as "redhat-release-server-6Server-6.5.0.2.el6_5.x86_64", is not currently supported
```

**Comment by Treysin** [comment]
as for CentOS 6.6 too:

```
Your distribution, identified as "centos-release-6-6.el6.centos.12.2.x86_64", is not currently supported...
```

**Comment by rsousauux** [comment]
I was able to workaround like @harmic sugested for v0.12 but not for v4.x as the corresponding files are not present in https://rpm.nodesource.com/pub_4.x/el/ for EL v6.

**Comment by plugin-kevin** [comment]
+1 for CentOS 6.6 
```Your distribution, identified as "centos-release-6-6.el6.centos.12.2.x86_64", is not currently supported…```

**Comment by chrislea** [comment]
@rsousauux the issue for Node 4.x on EL6 is being tracked in #128.

**Comment by par4dise** [comment]
Same problem for CentOS 6.6
> Your distribution, identified as "centos-release-6-6.el6.centos.12.2.x86_64", is not currently supported...
Any news?

**Comment by Yaowenjie** [comment]
+1
Same problem for CentOS 6.6
`## Your distribution, identified as "centos-release-6-6.el6.centos.12.2.i686", is not currently supported...`
