### ISSUE TITLE
Scientific Linux support?

### ISSUE THREAD

**Issue by petrmanek** [nodesource/distributions#186]
Hello,
I would love to add the NodeSource repo to my machine running Scientific Linux and guess what it is not supported. I hereby suggest support for this distro is added since it's not that different from the distributions NodeSource already supports.

The full name of my 'distribution package' is
```
sl-release-7.1-3.sl7.x86_64. 
```

Thanks in advance,
Petr (and some folks at CERN)

**Comment by rvagg** [comment]
thanks for picking this up @petrmanek, moving dicussion to #187
