### ISSUE TITLE
Documentation says CentOS 5 is supported using package manager but it is not true

### ISSUE THREAD

**Issue by logoff** [nodesource/distributions#190]
[This documentation page](https://nodejs.org/en/download/package-manager/) and [this page](https://github.com/nodesource/distributions) say that CentOS 5 64 bits is supported, but when I follow the script in my CentOS 5 VM this is the result:

    ## Confirming "el5-x86_64" is supported...
    
    + curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_0.10/el/5/x86_64/nodesource-release-el5-1.noarch.rpm'
    
    ## Your distribution, identified as "centos-release-5-6.el5.centos.1", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by helioricardo** [comment]
Same here with "centos-release-5-11.el5.centos"

## Your distribution, identified as "centos-release-5-11.el5.centos", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support.

**Comment by geoff-maddock** [comment]
Any explanation as to why it is not supported?

**Comment by chrislea** [comment]
EL5 is only currently supported for Node 0.10.x, so if you are trying to install a newer version that would explain why you are seeing the unsupported message. The reason is that the C++ compiler and the version of python that ship on EL5 are too old to build modern Node releases. I'm looking in to being able to build it using other toolchains, but it's not currently very high on the TODO list.

**Comment by logoff** [comment]
Thank you for the comment @chrislea. Maybe the proper solution is adding this limitation in the official documentation to avoid confusion.

**Comment by retrohacker** [comment]
@logoff, great suggestion. I've added this to the new FAQ and linked back to this issue.

It will land in https://github.com/nodesource/distributions/pull/308/

For now, as @chrislea said, adding support for EL5 for newer versions of Node.js is something we are considering. Closing this for now. We will revisit this after the migration to the new infrastructure.
