### ISSUE TITLE
Update the Node.js-maintained repositories for Ubuntu WilyWerewolf

### ISSUE THREAD

**Issue by Michael-Reidy** [nodesource/distributions#193]
When I tried adding the to add the Node.js-maintained repositories to my Ubuntu package source list with the command:

`curl -sL https://deb.nodesource.com/setup | sudo bash -`

I saw this message:

`Your distribution, identified as "wily", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support`

**Comment by Michael-Reidy** [comment]
These command do work though...

'curl -sL https://deb.nodesource.com/setup_5x | sudo -E bash -'
'curl -sL https://deb.nodesource.com/setup_4x | sudo -E bash -'

for the different versions...

**Comment by quinox** [comment]
It's stil a problem on Wily, Michael's command work when you modify the urls (at the moment his links give a 404):
* https://deb.nodesource.com/setup_5.x
* https://deb.nodesource.com/setup_4.x

**Comment by chrislea** [comment]
The original command doesn't work because that points to the 0.10 branch of Node. Wily was shipped after 4.x landed, and you *really* should be using that instead, so we didn't make 0.10 builds for these newer distros.

**Comment by quinox** [comment]
Thanks for the info, perhaps a notice about this can be added to `https://deb.nodesource.com/setup`; multiple sources tell you to run this command including https://nodesource.com/blog/chris-lea-joins-forces-with-nodesource/ which ranks quite high in Google when searching for Node PPA
