### ISSUE TITLE
fedora-release-23-1.noarch

### ISSUE THREAD

**Issue by LaKing** [nodesource/distributions#194]
I would like my distribution to be considered for support .-)

```
## Installing the NodeSource Node.js 0.10 repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "fc23-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_0.10/fc/23/x86_64/nodesource-release-fc23-1.noarch.rpm'

## Your distribution, identified as "fedora-release-23-1.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

```

**Comment by maaatts** [comment]
:+1:

**Comment by chrislea** [comment]
Fedora 23 is supported for Node 4.2.0 and higher. The 0.10 line is considered legacy now and is only being supported for really critical security issues.

**Comment by lukasbradley** [comment]
@chrislea Trying to run the following on Fedora 23 seems to default to 0.10.  Is there a way to change that?

`[lbradley@localhost ~]$ sudo curl --silent --location https://rpm.nodesource.com/setup | bash -`

`## Installing the NodeSource Node.js 0.10 repo...`

`## Inspecting system...`

`+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release`
`+ uname -m`

`## Confirming "fc23-x86_64" is supported...`

`+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_0.10/fc/23/x86_64/nodesource-release-fc23-1.noarch.rpm'`

`## Your distribution, identified as "fedora-release-23-1.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support`

Maybe I'm misunderstanding what you are trying to say.

**Comment by chrislea** [comment]
Yes please check out the installation instructions [here](https://github.com/nodesource/distributions/#rpminstall). You use different setup scripts depending on which version you want to install. Hope this helps!

**Comment by lukasbradley** [comment]
@chrislea Thank you so much for the response.  I read that page, and am embarrased to say I thought it was only for RHEL/CENTOS.  

When trying to run the script directly, I got the following error:

```
## Downloading release setup RPM...

+ mktemp
+ curl -sL -o '/tmp/tmp.3BlR6h6inY' 'https://rpm.nodesource.com/pub_5.x/fc/23/x86_64/nodesource-release-fc23-1.noarch.rpm'

## Installing release setup RPM...

+ rpm -i --nosignature --force '/tmp/tmp.3BlR6h6inY'
*error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Inappropriate ioctl for device)*
Error executing command, exiting
```
I was running as root, and didn't have a lock on rpm.  So I just downloaded and installed the rpm manually and it worked.  (Included in case anyone else has the same issue.)

```
wget https://rpm.nodesource.com/pub_5.x/fc/23/x86_64/nodesource-release-fc23-1.noarch.rpm
rpm -i nodesource-release-fc23-1.noarch.rpm
```

Thanks for your help.

**Comment by LaKing** [comment]
You can install the package with dnf. .)

```dnf -y install https://rpm.nodesource.com/pub_5.x/fc/23/x86_64/nodesource-release-fc23-1.noarch.rpm```

**Comment by LaKing** [comment]
Here is a little bash script to help out here. .)

```
## get the listing
curl -s https://rpm.nodesource.com/pub_5.x/fc/23/x86_64/ | grep 'href="nodejs-' > /tmp/nodeversion

## we will update this variable
nodejs_ver=''

## local variables we use
_checkcount=0
_checknum=0
_check=''

## process 
while read line
do
    if ! [[ "${line:16:1}" == "d" ]]
    then
	## substract the version from that listing
	_check=${line:16:7}
	_checknum=$(echo $_check | tr '.' '0' | tr '-' '0' )
	
	if [ "$_checknum" -gt "$_checkcount" ]
	then
	    ## update version number, as it seems to be the highest so far
	    _checkcount=$_checknum
	    nodejs_ver=$_check
	fi
    fi

done < /tmp/nodeversion

echo "latest node version is $nodejs_ver according to nodesource"

node_ver=0

if [ -f /bin/node ]
then
    node_ver=$(/bin/node --version)
fi

echo "$node_ver" == "v${nodejs_ver:0:-2}"
if [ "$node_ver" != "v${nodejs_ver:0:-2}" ]
then
    if [ -f /bin/node ]
    then
	dnf -y remove nodejs
    fi
    rpm_url="https://rpm.nodesource.com/pub_5.x/fc/23/x86_64/nodejs-"$nodejs_ver"nodesource.fc23.x86_64.rpm"
    echo "dnf -y install $rpm_url"
    dnf -y install $rpm_url
fi

```

**Comment by honza** [comment]
The `ioctl` issues go away for me when I insert `sudo` in from of the `bash` command from the installation instructions...

**Comment by damijanc** [comment]
Like @honza said, putting sudo in front of bash fixes the problem.

`curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo  bash -`
