### ISSUE TITLE
install scripts produce `nodejs` binary vs `node` binary on ubuntu 14.04

### ISSUE THREAD

**Issue by cdaringe** [nodesource/distributions#198]
is that intentional?  if not, what more information may I provided to be more assistive?

thanks all!

**Comment by chrislea** [comment]
Yes, that's intentional for some historical / political reasons. The Ubuntu packages make a symlink to `/usr/bin/node` so you can call it as you're used to.

**Comment by cdaringe** [comment]
@chrislea, thanks chris.  i'm betting the root of my issue is that we used `n` to install 2.5.0.  after running the steps in the readme to install 4.x, `node` still boots 2.5.0, not the `nodejs` binary as expects.  perhaps whatever generates that symlink only does so if it's not present already.  I'll experiment with trashing our old node installs _then_ reinstalling on Monday.

**Comment by chrislea** [comment]
Ah, yes. I would **definitely** get rid of any existing installs before using the NS repos for the first time.
