### ISSUE TITLE
Allow http access to repository

### ISSUE THREAD

**Issue by yurielation** [nodesource/distributions#202]
Hello

Https adds no security, since packages anyway authenticated using GPG.
But... it takes a lot of time to install apt-transport-https on ancient Debian systems.
(it updates libc which is not good news for many production sites)

Please remove obligatory redirection for http://deb.nodesource.com/ 
Make our lives easier, not harder. Please.

**Comment by ccope** [comment]
SSL also prevents caching proxies like apt-cacher-ng from working. +1 to allowing HTTP please.

**Comment by keyan** [comment]
+1, struggle with this right now. Anything I could do to help?

**Comment by keyan** [comment]
@rvagg @chrislea 🙏

**Comment by mk-pmb** [comment]
Looks like a duplicate of #71.

**Comment by mk-pmb** [comment]
The other thread also clears up some misconceptions mentioned here:

> Https adds no security,

In some scenarios, it does add security.

> SSL also prevents caching proxies like apt-cacher-ng from working.

For this argument, `apt-cacher-ng` is a bad example, as it can be configured to work with HTTPS.

**Comment by keyan** [comment]
@mk-pmb, while #71 is discussing the same issues there is too much noise on that ticket from initial troubleshooting. Whereas this ticket is very clearly asking for HTTP access. Perhaps if the title for #71 was updated we could close this ticket.

> For this argument, `apt-cacher-ng` is a bad example, as it can be configured to work with HTTPS.

Yes it can be configured to work with HTTPS, but it's just extra work for what seems to be little to no benefit.

> In some scenarios, it does add security.

This would be a more substantive comment if you could describe such a scenario.

**Comment by mk-pmb** [comment]
I've updated the title and added attack vectors to the overview in the first post.

**Comment by retrohacker** [comment]
Closing as a duplicate of #71

Thank you for all of your work opening and refining both of these issues @keyan and @mk-pmb
