### ISSUE TITLE
RPM GPG Key MIME-Type should be text/plain

### ISSUE THREAD

**Issue by jnovack** [nodesource/distributions#206]
Spacewalk will not properly download the GPG key for packages because the Content-Type on the webserver is `text/html` rather than the industry defacto standard (and GPG recommended) `text/plain`.

The rest of the world seems to use `text/plain` (if your friends jumped off a bridge too, would you?)

Even your debian brethren use `text/plain`.

    [root@spacewalk ~]# curl -I http://rpms.adiscon.com/RPM-GPG-KEY-Adiscon | grep Content-Type
    Content-Type: text/plain
    
    [root@spacewalk ~]# curl -I https://yum.mariadb.org/RPM-GPG-KEY-MariaDB | grep Content-Type
    Content-Type: text/plain
    
    [root@spacewalk ~]# curl -I http://fedora-epel.mirror.lstn.net/RPM-GPG-KEY-EPEL-7 | grep Content-Type
    Content-Type: text/plain
    
    [root@spacewalk ~]# curl -I https://deb.nodesource.com/gpgkey/nodesource.gpg.key | grep Content-Type
    Content-Type: text/plain

    [root@spacewalk ~]# curl -I https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL | grep Content-Type
    Content-Type: text/html

**Comment by chrislea** [comment]
Sorry about that. We actually had it set to `text/plain` but it looks like something got renamed and the config wasn't updated. Fixed now. Thanks for the catch!

```bash
>> curl -sI https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL | grep 'Content-Type'                                                                                 [13:26:33]
Content-Type: text/plain
```
