### ISSUE TITLE
Missing older patch releases

### ISSUE THREAD

**Issue by maspwr** [nodesource/distributions#207]
Do old patch releases get removed from the apt repositories when new releases are pushed out? It looks like only `4.2.4` is available through `https://deb.nodesource.com/setup_4.x`, whereas a few weeks ago `4.2.1` was available. I was hoping to pin installation scripts to install a specific version.

**Comment by johannmiller** [comment]
I am having this same problem. I had 4.2.4 specified in a deployment script, which is now breaking because only 4.2.6 exists.

**Comment by slurmulon** [comment]
Facing the issue as well due to a blind upgrade via `curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -`

Locked me into `4.2.6` when we were previously dependent on `4.2.4` (no longer found).

**Comment by leedm777** [comment]
I've hit the same problem. Interestingly, [the packages are still there](https://deb.nodesource.com/node_4.x/pool/main/n/nodejs/), but they are [missing from the Packages file](https://deb.nodesource.com/node_4.x/dists/trusty/main/binary-amd64/Packages).

And it's interesting that Docker had [exactly the same issue](https://github.com/docker/docker/issues/13191) last year.

**Comment by wblankenship** [comment]
Hey everyone. This issue is currently being tracked here: https://github.com/nodesource/distributions/issues/33

You can find an explanation as to why this is happening, along with some helpful work arounds, there.

**Comment by maspwr** [comment]
@wblankenship Thank you for the link. I hadn't seen that issue when searching earlier.
