### ISSUE TITLE
Your distribution, identified as "redhat-release-server-7.2-9.el7.x86_64", is not currently supported

### ISSUE THREAD

**Issue by deepres** [nodesource/distributions#209]
Hi, 

I tried to install ( `curl --silent --location https://rpm.nodesource.com/setup_5.x | bash -` )  up to date version of node and npm on my EL with the following result:

`## Your distribution, identified as "redhat-release-server-7.2-9.el7.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support`

is this something I can fix locally  ?
Thanks, Piotr

**Comment by retrohacker** [comment]
We now offer EL7 releases of 64 bit Node.js: https://rpm.nodesource.com/pub_5.x/el/7/x86_64/

Marking this as solved. If you are still experiencing problems with this, feel free to reopen and we can help debug!
