### ISSUE TITLE
centos-release-6-7.el6.centos.12.3.x86_64 not Supported

### ISSUE THREAD

**Issue by kavin-90** [nodesource/distributions#211]

**Comment by ZaValera** [comment]
I have same problem.

**Comment by m4grio** [comment]
Same problem here.

**Comment by jessi-f-lopes** [comment]
it seams i too have this issue...  im sure this is in error.?

**Comment by Alexander-OFM** [comment]
Same problem here. At https://rpm.nodesource.com/pub_4.x/el/ there is no 6 directory. Where can I download the rpms by hand?

**Comment by makkesk8** [comment]
same

**Comment by chrislea** [comment]
Hi all. This issue is being tracked in #128. We don't have 4.x or 5.x builds for EL6 because of toolchain issues but we're working on it. Please keep an eye out there for updates. Thanks!

**Comment by kavin-90** [comment]
Thanks for your Hard Work.

Please tell me which one to use.

https://rpm.nodesource.com/pub_4.x/el/6/x86_64/

**Comment by chrislea** [comment]
@kavin-90 I think you may have hit these when things were still in flux being pushed into the repos. If you just follow the [installation instructions](https://github.com/nodesource/distributions/#rpminstall) now I think things will work. You will need remove any existing Node installs and probably also do a

```bash
yum clean all
```
as the `root` user first to make sure there's not any residual bad info in your `rpm` database.

**Comment by kavin-90** [comment]
okay thanks.
