### ISSUE TITLE
Ubuntu 16.04 Xenial Xerus

### ISSUE THREAD

**Issue by presidento** [nodesource/distributions#213]
```
## Confirming "xenial" is supported...

+ wget -qO /dev/null -o /dev/null \
    'https://deb.nodesource.com/node_5.x/dists/xenial/Release'

## Your distribution, identified as "xenial", is not
currently supported, please contact NodeSource at 
https://github.com/nodesource/distributions/issues 
if you think this is incorrect or would like your
distribution to be considered for support
```

According to release schedule, [alpha 1 is out](https://wiki.ubuntu.com/XenialXerus/ReleaseSchedule), we would like to test the compatibility of our product in advance.

**Comment by rvagg** [comment]
Thanks for reporting @presidento. Unfortunately we're not going to begin shipping for 16.04 until it goes GA. In the meantime you can use the procedure outlined in https://github.com/nodesource/distributions#manual-installation and substitute `xenial` for `wiley` and it should work fine.

**Comment by panuhorsmalahti** [comment]
@rvagg By the way, it's `wily`,  not `wiley`
