### ISSUE TITLE
centos-release-7-1.1503.el7.centos.2.8.1.i686

### ISSUE THREAD

**Issue by Bob620** [nodesource/distributions#214]
curl --silent --location https://rpm.nodesource.com/setup_5.x | bash -
**Your distribution, identified as "centos-release-7-1.1503.el7.centos.2.8.1.i686", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support**

**Comment by retrohacker** [comment]
Per https://github.com/nodesource/distributions/issues/277 , unfortunately Node 4.x and greater only support 64-bit distributions of Enterprise Linux due to the compiler toolchain.

This has been added to the FAQ in the README that will land in #208.
