### ISSUE TITLE
Missing node 5.4.1 for vivid arm

### ISSUE THREAD

**Issue by Spy-Seth** [nodesource/distributions#215]
The package for the last version of node `5.4.1` is not available for vivid arm. Currently we have `5.4.0-1nodesource1~vivid1`: https://deb.nodesource.com/node_5.x/dists/vivid/main/binary-armhf/Packages

Does the other build are automated build ? The ARM jessie one seems to really quickly be available.

Thanks for your work by the way!

**Comment by chrislea** [comment]
Hrm, that is odd. The `deb` packages are all built in one automated pass from essentially identical sources, but it looks like for some reason the `vivid` build may have failed for this release. I'll check it out. Thanks for the catch!

**Comment by chrislea** [comment]
Okay, it's there now. Thanks again for the catch.

**Comment by Spy-Seth** [comment]
Thanks for the quick fix! :+1:
