### ISSUE TITLE
centos-release-6-3.el6.centos.9.i686 is not currently supported

### ISSUE THREAD

**Issue by sundagy** [nodesource/distributions#217]
## Confirming "el6-i386" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_5.x/el/6/i386/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "centos-release-6-3.el6.centos.9.i686", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by grahamlyons** [comment]
I believe this is duplicated by #218

**Comment by grahamlyons** [comment]
Being handled under #128
