### ISSUE TITLE
centos-release-6-7.el6.centos.12.3.x86_64 is not currently supported

### ISSUE THREAD

**Issue by ryangatchalian912** [nodesource/distributions#218]
Your distribution, identified as "centos-release-6-7.el6.centos.12.3.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by WooJaeWoo** [comment]
I have same issue!! with same version of OS

**Comment by grahamlyons** [comment]
Me too. What's the reason for not supporting EL6?

**Comment by grahamlyons** [comment]
Being handled under #128

**Comment by chasoft** [comment]
I have the same Issue!

**Comment by chrislea** [comment]
As noted, this is being tracked in #128, thanks.
