### ISSUE TITLE
redhat-release-server-6Server-6.5.0.1.el6.x86_64 not supported

### ISSUE THREAD

**Issue by rramacciani** [nodesource/distributions#221]

**Comment by chrislea** [comment]
Can you please let us know what specific steps you did that caused this message? Thanks!

**Comment by rramacciani** [comment]
Hi Chrislea, this is the command:
[root]# curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -

and this is the output:

## Installing the NodeSource Node.js 4.x LTS Argon repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_4.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "redhat-release-server-6Server-6.5.0.1.el6.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support


Thanks

**Comment by chrislea** [comment]
This issue is being tracked in #128. Thanks.
