### ISSUE TITLE
Debian GNU/Linux 6.0 not supported

### ISSUE THREAD

**Issue by johannesjo** [nodesource/distributions#222]

**Comment by chrislea** [comment]
Debian 6.0 is too old of a distro to reasonably support. In fact, we can only support Debian 7.0 [with some caveats](https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md). Also, 6.0 is [about to move beyond its support window](https://www.debian.org/releases/squeeze/) in a few weeks, so we'd advise you to upgrade to something still supported ASAP!
