### ISSUE TITLE
Node 5.x : Not supporting for Ubuntu 16.04 Xenial Xerus

### ISSUE THREAD

**Issue by udara-u3** [nodesource/distributions#228]
**I used the package manager for install Node 5.x**
`curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install -y nodejs`
Is there anyway I can install 5.X on Ubuntu 16.04 ?

![xenial](https://cloud.githubusercontent.com/assets/12265797/12909589/f17b32b6-cf1b-11e5-9bc6-0dbeffc93d60.jpg)

**Comment by chrislea** [comment]
We don't support distro releases until they are officially out, which is why Xenial is showing as unsupported. You can probably install the appropriate package [from Wily](https://deb.nodesource.com/node_5.x/pool/main/n/nodejs/) manually to give it a try though.

**Comment by simongareste** [comment]
Hi,

I believe Xenial has been out for a few months now, with the 04.1 update in July which is usually considered the "real" LTS version. Could you update this?

**Comment by chrislea** [comment]
Node v5.x is no longer supported, so we do not build new packages for it. Xenial is supported for Node v6.x.
