### ISSUE TITLE
A ubuntu distribution, identified as "wily", is not currently supported for nodejs

### ISSUE THREAD

**Issue by nkr-jgr** [nodesource/distributions#229]
Command: `curl -sL https://deb.nodesource.com/setup | sudo bash -`

Output at Terminal:

...
...
Reading package lists... Done

## Confirming "wily" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_0.10/dists/wily/Release'

**Comment by chrislea** [comment]
Wily was released after Node 4.x (LTS) came out, so we only support Node >= 4.x on it. If you use this setup script:

```
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
```

it should work.
