### ISSUE TITLE
Fedora 23 support please

### ISSUE THREAD

**Issue by calebadavis** [nodesource/distributions#231]
Your distribution, identified as "fedora-release-23-1.noarch", is not currently supported

**Comment by chrislea** [comment]
Can you please let us know what you did that resulted in seeing that message? Thanks.

**Comment by calebadavis** [comment]
I tried to follow the install directions for Fedora:
https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora

Since the software I'm trying to host was developed about a year ago using Node.js 0.10, I followed the steps for that branch:

> [root@mail ~]# curl --silent --location https://rpm.nodesource.com/setup | bash -
> ## Installing the NodeSource Node.js 0.10 repo...
> 
> ## Inspecting system...
>
> + rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release + uname -m
> 
> ## Confirming "fc23-x86_64" is supported...
> 
> + curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_0.10/fc/23/x86_64/nodesource-release-fc23-1.noarch.rpm'
> 
> ## Your distribution, identified as "fedora-release-23-1.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
The problem is that FC23 was release after Node 4.x shipped, so we don't build the old 0.10.x binaries for it since you should really be using 4.x. If you do the following it should work:

```bash
curl -sL https://rpm.nodesource.com/setup_4.x | bash -
```
