### ISSUE TITLE
Node v4.3.1 armhf packages missing

### ISSUE THREAD

**Issue by matiasdoyle** [nodesource/distributions#233]
Hi,

Trying to install v4.3.1, but looks like 4.3.0 is the latest available version for armhf. I'm on Jessie, but seems like it's missing from other distros as well. Will it be released at some point? :)

Thanks!

**Comment by chrislea** [comment]
Yup, we've actually just pushed them to the repository. The ARM builds take forever so they lag behind the Intel builds, but we do eventually get them in there. :)
