### ISSUE TITLE
Confirming "xenial" is supported

### ISSUE THREAD

**Issue by tigefa4u** [nodesource/distributions#235]
## Confirming "xenial" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_4.x/dists/xenial/Release'

Your distribution, identified as "xenial", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

add please :sparkling_heart:

**Comment by chrislea** [comment]
We don't support any pre-release distributions. When Xenial actually ships we will support it right away though.
