### ISSUE TITLE
support for centOS 6.x

### ISSUE THREAD

**Issue by MrAudioGuy** [nodesource/distributions#236]
Hi,

Though centOS 7.x has already released for more than a year, the 6.x is still trusted for enterprise systems. It will be great if new node binary releases were considered for 6.x.
The latest release available for centOS 6.x is still 0.10.x.

My release as identified by node bash script: "centos-release-6-4.el6.centos.10.x86_64"

Thanks

**Comment by chrislea** [comment]
EL6 is supported now, this is  being tracked in #128 .

**Comment by shunia** [comment]
Incase anyone searching this, quick way to work around is like:
```
wget https://rpm.nodesource.com/pub_4.x/el/6/x86_64/nodejs-4.3.1-1nodesource.el6.x86_64.rpm
yum localinstall nodejs-4.3.1-1nodesource.el6.x86_64.rpm
```

refered to [voodah's commont](https://github.com/nodesource/distributions/issues/128#issuecomment-178136430) in #128
