### ISSUE TITLE
Ubuntu 15 wily Not supported

### ISSUE THREAD

**Issue by Madeindreams** [nodesource/distributions#237]
Hello.

I am trying to install _Nodejs _with the following command line;

curl -sL https://deb.nodesource.com/setup | sudo -E bash -
But I get this message;

```
## Confirming "wily" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_0.10/dists/wily/Release'

## Your distribution, identified as "wily", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

If I install _Nodejs_ from the package manager or with `apt-get install`. It will install node but i am unable to install _npm_ cause it does'nt see Nodejs and telling me that some dependencys are missing.

If I try to install both at once like this;

`sudop apt-get install nodejs npm`

it is telling me that nodejs is conflicting with npm

My linux is in french so im translating the error I get.
`
E: impossible to repair, defective packages are in mode "keep in state"`

Seam like its trying to correct but cant change the files.

So I really dont know what to do.

**Comment by chrislea** [comment]
Ubuntu Wily is only supported for Node >= 4.2.x. If you do the following it should work:

```bash
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by Madeindreams** [comment]
Why does it keep installing v4.3.1?

**Comment by chrislea** [comment]
4.2.1 is the current release in the LTS line. It's what you should be using unless you need something bleeding edge from the 5.x development line.

**Comment by chrislea** [comment]
Sorry, typo, I meant that 4.3.1 is the current release in the LTS line.

**Comment by Madeindreams** [comment]
I get the exact same result as before. I cant install npm afterwards cuse all the node-stuff is required my ubuntu is not seeing any of nodejs extension
```
npm : Dépend: nodejs mais ne sera pas installé
       Dépend: node-abbrev (>= 1.0.4) mais ne sera pas installé
       Dépend: node-ansi (>= 0.3.0-2) mais ne sera pas installé
       Dépend: node-ansi-color-table mais ne sera pas installé
       Dépend: node-archy mais ne sera pas installé
       Dépend: node-block-stream mais ne sera pas installé
       Dépend: node-fstream (>= 0.1.22) mais ne sera pas installé
       Dépend: node-fstream-ignore mais ne sera pas installé
       Dépend: node-github-url-from-git mais ne sera pas installé
       Dépend: node-glob (>= 3.1.21) mais ne sera pas installé
       Dépend: node-graceful-fs (>= 2.0.0) mais ne sera pas installé
       Dépend: node-inherits mais ne sera pas installé
       Dépend: node-ini (>= 1.1.0) mais ne sera pas installé
       Dépend: node-lockfile mais ne sera pas installé
       Dépend: node-lru-cache (>= 2.3.0) mais ne sera pas installé
       Dépend: node-minimatch (>= 0.2.11) mais ne sera pas installé
       Dépend: node-mkdirp (>= 0.3.3) mais ne sera pas installé
       Dépend: node-gyp (>= 0.10.9) mais ne sera pas installé
       Dépend: node-nopt (>= 3.0.1) mais ne sera pas installé
       Dépend: node-npmlog mais ne sera pas installé
       Dépend: node-once mais ne sera pas installé
       Dépend: node-osenv mais ne sera pas installé
       Dépend: node-read mais ne sera pas installé
       Dépend: node-read-package-json (>= 1.1.0) mais ne sera pas installé
       Dépend: node-request (>= 2.25.0) mais ne sera pas installé
       Dépend: node-retry mais ne sera pas installé
       Dépend: node-rimraf (>= 2.2.2) mais ne sera pas installé
       Dépend: node-semver (>= 2.1.0) mais ne sera pas installé
       Dépend: node-sha mais ne sera pas installé
       Dépend: node-slide mais ne sera pas installé
       Dépend: node-tar (>= 0.1.18) mais ne sera pas installé
       Dépend: node-underscore mais ne sera pas installé
       Dépend: node-which mais ne sera pas installé
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».
```
How do i get all these dependencys if its not by installing nodejs?

**Comment by Madeindreams** [comment]
Sorry I have the french version of Ubuntu

**Comment by chrislea** [comment]
You don't want to install `npm` separately. NPM is included in our `nodejs` distribution and it not a separate package.

**Comment by Madeindreams** [comment]
But npm doesnt work I get this;
`/usr/local/bin/node: 1: /usr/local/bin/node: Syntax error: word unexpected (expecting ")")`

anytime I try to run npm

**Comment by Madeindreams** [comment]
npm -v return the same error

**Comment by Madeindreams** [comment]
if the 1: refer to line one this is what the line 1 is in npm:

`#!/bin/sh`

**Comment by chrislea** [comment]
It looks like you may have some other package stuff installed that you shouldn't. Or that you tried to compile node yourself. It shouldn't be using a binary in `/usr/local/bin`. I'd try something like this:
```bash
dpkg -l | egrep "nodejs|npm"
```
and then remove **any** packages related to `node` or `npm`. Then, make sure there's no `node` or `npm` stuff in `/usr/local/bin`. Then try running the installer script again.

**Comment by Madeindreams** [comment]
Ok that line you gave me return 

```
rc  nodejs                                        4.3.1-1nodesource1~wily1                   amd64        Node.js event-based server-side javascript engine
rc  npm                                           1.4.21+ds-2                                all          package manager for Node.js
```

If I remove nodejs using package manager or apt-get remove nodejs. It does get removed and its telling me that it is not installed. But i ran you command again and its still printing out the same thing.

So how should I remove it? I cant delete the files. Is there a sudo command line to delete them? from /usr/local ?
