### ISSUE TITLE
Apt repo at deb.nodesource.com hangs on apt-get update with ubuntu 14.04 64-bit... for node 4.x install

### ISSUE THREAD

**Issue by Shoeler** [nodesource/distributions#238]
Hi there - your deb.nodesource.com apt repo is currently hanging when I try to do an apt-get update on trusty/14.04 ubuntu. I mirror your repo locally and when I hit my local copy of your repo it hangs - changing this to point directly to https://deb.nodesource.com/node_4.x/ also hangs. Any idea what may be going on? 

I can wget the files fine by hand but it's causing issues with my ubuntu boxes.

**Comment by chrislea** [comment]
The fact that it hangs on your local copy is very suspect. What do the outputs of `traceroute` and `mtr` to deb.nodesource.com look like? Also, can you telnet to deb.nodesource.com on port 443 successfully?

**Comment by Shoeler** [comment]
root@mirror:/data/mirror/deb.nodesource.com/node_4.x# nc -v
deb.nodesource.com 443
Connection to deb.nodesource.com 443 port [tcp/https] succeeded!

So the one thing I didn't think to check before submitting this was adding
the deb.nodesource.com repo to my mirror and see if it (the mirror) is able
to get to packages fine.  It seems to be something going on with my apt
mirror.  Sigh.  Thanks for the quick response!

**Comment by chrislea** [comment]
No problem. Good luck!
