### ISSUE TITLE
Distribution not supported, xenial beta1

### ISSUE THREAD

**Issue by webeindustry** [nodesource/distributions#239]
I get that it's perhaps too early, but it would be nice to have support come April when 16.04 is officially released.

**Comment by chrislea** [comment]
Our policy is that we don't support pre-release versions, but when Xenial gets to an `rc` candidate I may make 4.x and 5.x packages assuming I don't see anything fishy with it. Regardless, we will support Xenial officially the day it's actually released if not before.
