### ISSUE TITLE
centos-release-6-7 unsupported

### ISSUE THREAD

**Issue by xsoft** [nodesource/distributions#240]
`curl -sL https://rpm.nodesource.com/setup_0.12 | bash -`

Your distribution, identified as "centos-release-6-7.el6.centos.12.3.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

```
#cat /etc/redhat-release
CentOS release 6.7 (Final)
```

**Comment by chrislea** [comment]
Hrm, you should be getting those. Can you see the packages directly here?
```
https://rpm.nodesource.com/pub_0.12/el/6/x86_64/
```
Also, is there a reason you're installing 0.12 instead of 4.x (you should really use 4.x if you can)?

**Comment by JorisVanEijden** [comment]
There is no nodesource-release-el6-1.noarch.rpm file at https://rpm.nodesource.com/pub_0.12/el/6/x86_64/

**Comment by flynets** [comment]
Execute this commands from root:

```
wget https://rpm.nodesource.com/pub_0.10/el/6/x86_64/nodesource-release-el6-1.noarch.rpm
yum install ./nodesource-release-el6-1.noarch.rpm
sed -i 's/pub/pub_0.12/' /etc/yum.repos.d/nodesource-el.repo
```
then proceed to install:
`yum install nodejs`

**Comment by geerlingguy** [comment]
@flynets - So basically, act like you're installing 0.10, then hack it to 0.12, then install to get 0.12?

Hopefully we can get the 0.12 repo working correctly though—should be available at https://rpm.nodesource.com/pub_0.12/el/6/x86_64/nodesource-release-el6-1.noarch.rpm

**Comment by chrislea** [comment]
Sorry guys, this is my fault. I need to make the release file for this repo, somehow missed that. Unfortunately I won't be able to look at this until tonight at the earliest, but I'll get to it as soon as I can. The hack @flynets suggests should totally work and will not cause any bad side effects until I shore this up.

**Comment by geerlingguy** [comment]
@chrislea - Awesome, thanks!

**Comment by scragg0x** [comment]
I'm trying to install v4.x on CentOS 6.8 and I get this:


> Your distribution, identified as "centos-release-6-8.el6.centos.12.3.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by scragg0x** [comment]
Figured it out.  It had to do with SSL and curl.  I did the following before running the nodesource script

`export CURL_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt`

**Comment by tikoney** [comment]
Can you give clear procedure to install nodejs 4.x if it's centos6/7 ?

**Comment by rvagg** [comment]
@retrohacker it's listed on the README: https://github.com/nodesource/distributions#rpminstall

**Comment by rvagg** [comment]
sorry that was for @tikoney: it's listed on the README: https://github.com/nodesource/distributions#rpminstall

**Comment by sajeerk123** [comment]
I am trying to install node 0.12.*
using this  "curl -sL https://rpm.nodesource.com/setup_0.12 | bash -
" bit i got this.
Your distribution, identified as "centos-release-7-2.1511.el7.centos.2.10.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
Please help me to solve this issue

**Comment by Romkond** [comment]
I cannot install 6.x or 7.x on CentOS 6.8 due to "is not currently supported"... What commands to install it manually? Thank you.

**Comment by Romkond** [comment]
Ah, okay... "CentOS 6 (32-bit and 64-bit) [For Node < 4.x]" actually((...
