### ISSUE TITLE
bunsen-hydrogen (BunsenLabs) unsupported.

### ISSUE THREAD

**Issue by Xulai** [nodesource/distributions#241]
Making an issue to hope it's considered to be supported.

`## Your distribution, identified as "bunsen-hydrogen", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support`

https://www.bunsenlabs.org/ Is the link for the distro, it's been pretty much appointed to be Crunchbang's successor, basically being Debian + Openbox, Tint2 and Conky.

**Comment by carvilsi** [comment]
Hi.

I have the same issue here with bunsen-hydrogen.

Linux hydrogen 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) i686 GNU/Linux

Thanks.

**Comment by chrislea** [comment]
Thanks for the interest. Nobody here has a bunsen install to test against, but if it's based on Debian Jessie it should be easy to support. Please just submit a PR against the setup scripts and if it looks good we'll merge it. To see what's been done for other distros that we have aliased support for (Linux Mint for example) look in the sections with the `check_alt` function being used. Thanks!

**Comment by carvilsi** [comment]
Hi @chrislea and @rvagg

PR to try add support for bunsenlabs Linux Hydrogen, based on Debian Jessie. This distro is the community continuation of great CrunchBang Linux !#

I Hope this PR is correct, and it's trying to solve this issue and #248 too. 

If any change is needed, please tell me.

Thanks.
