### ISSUE TITLE
Illegal instruction on ARM Linux (raspberry pi)

### ISSUE THREAD

**Issue by surdu** [nodesource/distributions#242]
I've posted this before here https://github.com/nodejs/node/issues/5495 and was instructed that maybe here would be a better place to post this.

After Installing nodejs on raspberry pi, when you run any node binary you get an `Illegal instruction`.

If I understood correctly from the issue mentioned above, this is because the `curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -` retrieves the wrong binary for raspberry pi.

**Comment by dsigurds** [comment]
It looks like the binary that's being installed is compiled for armv7.  RaspberryPi 1s are armv6.  As a work around you can grab the zip for armv6l here: http://nodejs.org/dist/latest-v4.x/ and install manually.

**Comment by chrislea** [comment]
What @dsigurds is correct, we only build these for armv7 (hard float IIRC). If you want armv6 you'll need to just use the tarballs linked.
