### ISSUE TITLE
Ubuntu Wily support

### ISSUE THREAD

**Issue by C-Bouthoorn** [nodesource/distributions#243]
I got the following message while installing NodeJS as described on the [site of MEAN.io ](http://learn.mean.io/#mean-stack-prerequisite-technologies)

```
+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_0.10/dists/wily/Release'

## Your distribution, identified as "wily", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

Is there any change you are able to support the latest version of Ubuntu: 15.10 Wily ?

`$ uname -a`
`Linux chiyuu 4.2.0-32-generic #37-Ubuntu SMP Fri Feb 26 02:21:44 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Thanks :smile:

**Comment by C-Bouthoorn** [comment]
Update: Using the `vivid` release works just fine

**Comment by chrislea** [comment]
This is because Wily is only supported for versions >= 4.x as noted [here](https://github.com/nodesource/distributions/#deb). If you install 4.x using
```bash
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
```
it should work.
