### ISSUE TITLE
Unable to build native addons on Centos 6 with Node 4.3

### ISSUE THREAD

**Issue by grimurd** [nodesource/distributions#244]
I have installed as instructed using the software collections to install.

```
[root] # uname -a
Linux hostname 2.6.32-504.16.2.el6.x86_64 #1 SMP Wed Apr 22 06:48:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root] # gcc --version
gcc (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)
[root] # python --version
Python 2.7.8
```

I have these entries in the bashrc file of the user who is doing the build(i have also tried enabing them using scl enable devtoolset-3 python27 without success)

```
source scl_source enable devtoolset-3
source scl_source enable python27
```

[My output from npm install](http://pastebin.com/8mL75dbN)

Any idea what is going on?

EDIT: [npm-debug.log](http://pastebin.com/MGHtBY3Y)

**Comment by retrohacker** [comment]
Hey @grimurd,

What version of Node.js do you have installed, and what process did you use to install it?
