### ISSUE TITLE
Debian wheezy sitck to v0.12.9? (armhf)

### ISSUE THREAD

**Issue by imZack** [nodesource/distributions#247]
Is deb package for debian 7 armhf will stick to v0.12.9 and not moving on?

Thanks.

**Comment by retrohacker** [comment]
Unfortunately, newer versions of V8 require a newer compiler toolchain than is available for wheezy and precise. This newer toolchain is not available on ARM, so we can no longer release updates.

More can be found here: https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md

I've added this to the FAQ which will land in #308
