### ISSUE TITLE
gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by OmarHallab** [nodesource/distributions#249]
Hi all, 

I am currently developing on a beaglebone black board with debian 7.9 Wheezy installed. I've been struggling for the past week trying to update my node version & its still going :/ 

I went for manual installation, unfortunately i wasn't able to add the NodeSource signing key:
root@beaglebone:~# wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
result : 'gpg: no valid OpenPGP data found.

------------------------------------------------------

Please get back to me on this & thank you. 

regards,
Omar

**Comment by chrislea** [comment]
Hrm, that file is certainly there. I'm wondering if you're behind some kind of proxy that's causing an issue. If you just go to that link in a web browser do you see the file?

**Comment by rvagg** [comment]
We did also have some server problems around the time of your issue filing, perhaps try again now?

**Comment by OmarHallab** [comment]
Hi guys, 

Still running through the same issue as of today, 
@chrislea  I'm able to open the webpage & see the nodesource pgp key so no fault with the proxy settings. 

Do you think there might be compatibility issues with beaglebone black running Debian wheezy 7.9 OS? 

regards,
Omar

**Comment by OmarHallab** [comment]
I decided to add parameter to wget method:

root@beaglebone:~# wget --no-check-certificate -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -

I recieved an "OK" return 

add the repo:
root@beaglebone:~# nano /etc/apt/sources.list
-------------------------------------------------------------------------------
deb https://deb.nodesource.com/node_0.12 wheezy main
#deb-src https://deb.nodesource.com/node_0.12 wheezy main
--------------------------------------------------------------------------------

After calling : 'apt-get update' this is my output: 
-----------------------------------------------------------------------------------------------------------------------------
Ign https://deb.nodesource.com wheezy Release.gpg
Ign https://deb.nodesource.com wheezy Release
Err https://deb.nodesource.com wheezy/main Sources
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

Err https://deb.nodesource.com wheezy/main armhf Packages
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Fetched 331 kB in 1min 42s (3214 B/s)

W: Failed to fetch https://deb.nodesource.com/node_0.12/dists/wheezy/main/source/Sources  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

W: Failed to fetch https://deb.nodesource.com/node_0.12/dists/wheezy/main/binary-armhf/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

E: Some index files failed to download. They have been ignored, or old ones used instead.
-----------------------------------------------------------------------------------------------------------------------------

Any ideas why I am getting these errors? 
Thank you 
:)

**Comment by OmarHallab** [comment]
Hi Guys,

I've followed this guide & I was able to successfully install node.js v0.12.0 on my Beaglebone black 
https://youtu.be/3HRceMZW7F4

Thanks,
Omar
