### ISSUE TITLE
Scientific Linux SL release 5.6 (Boron) Not Supported

### ISSUE THREAD

**Issue by crates** [nodesource/distributions#251]
sudo curl -k --location https://rpm.nodesource.com/setup | bash -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6977  100  6977    0     0   8344      0 --:--:-- --:--:-- --:--:-- 6813k

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el5-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_0.10/el/5/x86_64/nodesource-release-el5-1.noarch.rpm'

**Comment by retrohacker** [comment]
Hey @crates,

We, unfortunately, do not have the resources necessary to support and test the plethora of Linux releases in the wild, so we rely on community members such as yourself to get support on your favorite distributions.

I've added Scientific Linux to the list of requested distributions in our README.md, it will land in #308
