### ISSUE TITLE
Your distribution, identified as "cloudlinux-release-6-6.7.0.i686", is not currently supported

### ISSUE THREAD

**Issue by hendranata** [nodesource/distributions#252]
helo I have problem when install nodejs here

I follow the instruction from here 
https://www.otherdata.com/knowledge-base/linux-howtos/installing-nodejs-grunt-gulp-and-bower-cpanel-and-centos-or-cloudlinux

but when I enter "curl -sL https://rpm.nodesource.com/setup_4.x | bash -"

it shows me an error like this
```

root@iix-ssd [~]# curl -sL https://rpm.nodesource.com/setup_4.x | bash -

## Installing the NodeSource Node.js 4.x LTS Argon repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el6-i386" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_4.x/el/6/i386/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "cloudlinux-release-6-6.7.0.i686", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

```

now I dont know what is actually the problem..but I notice that is:
 Your distribution, identified as "cloudlinux-release-6-6.7.0.i686", is not currently supported

so how do we solve this issue?
currently my OS is centos 6.5 + cloudlinux 6.7

**Comment by retrohacker** [comment]
Hi @hendranata,

The 4.x releases of Node.js and newer require a 64 bit operating system per https://github.com/nodesource/distributions/issues/268

Adding this to the FAQ
