### ISSUE TITLE
 Identified as "xenial", is not currently supported

### ISSUE THREAD

**Issue by Ahmed0406** [nodesource/distributions#255]
W: gpgv:/var/lib/apt/lists/ppa.launchpad.net_rvm_smplayer_ubuntu_dists_xenial_InRelease: The repository is insufficiently signed by key E23A3C5344AE497C2FEE7B0BA7E13D78E4A4F4F4 (weak digest)
W: gpgv:/var/lib/apt/lists/ppa.launchpad.net_webupd8team_java_ubuntu_dists_xenial_InRelease: The repository is insufficiently signed by key 7B2C3B0889BF5709A105D03AC2518248EEA14886 (weak digest)

## Confirming "xenial" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_5.x/dists/xenial/Release'

**Comment by chrislea** [comment]
You're seeing this because we do not support pre-release distros, so Xenial is currently not in our support window. When it hits RC status we may start pushing builds out depending on what we see in the community relative to stability etc. Coming soon!

**Comment by Ahmed0406** [comment]
What about the Debian unstable ???
It did not supported ...

**Comment by chrislea** [comment]
We provide builds for Debian unstable because it is in a constant state of flux that perpetually, by definition, unstable. If somebody is running that distro, then they've already accepted the reality that things could break at any time. But in the case of Ubuntu / Fedora where there are regular releases, people want to be able to trust that things will work as expected.

**Comment by mgcrea** [comment]
@chrislea, I think supporting beta releases of Ubuntu LTS version makes sense, it's only one release every two year and having support during beta makes sure that everything is ready for GA as Ubuntu LTS releases are the go-to option for many cloud / dedicated-hosting providers,.

**Comment by david-gregory-inmar** [comment]
It makes sense that you wouldn't "support" pre-release distros, i.e. responding immediately to reported problems.  How about at least "acknowledging" them with an unsupported build?  At this point node.js is becoming an indispensable part of the open source infrastructure; not having a package available for an important beta distro means that the user community can't reliably test any packages that depend on node.js on that distro without jumping through hoops. IMO, anybody running a beta of any OS, even Ubuntu / Fedora, has already "accepted the reality that things could break at any time".
