### ISSUE TITLE
Add schmooze to supported distros

### ISSUE THREAD

**Issue by deweydb** [nodesource/distributions#257]
I'm running a copy of FreePBX which is essentially CentOS, but reports its distro package as:
schmooze-release-6-6.el6.shmz66.3.4.x86_64.

To install node4+ with nodesource i had to edit the script and change the line:
```` if [[ $DISTRO_PKG =~ ^(redhat|centos|cloudlinux|sl)- ]]; then ````

to:
```` if [[ $DISTRO_PKG =~ ^(redhat|centos|cloudlinux|sl|schmooze)- ]]; then ````

**Comment by retrohacker** [comment]
Hey @deweydb,

We, unfortunately, do not have the resources necessary to support and test the plethora of Linux releases in the wild, so we rely on community members such as yourself to get support on your favorite distributions. We welcome a PR adding support for this that you have tested and confirmed works!

I've added FreePBX to the list of requested releases in our README.md, it will land in https://github.com/nodesource/distributions/pull/308
