### ISSUE TITLE
Your distribution, identified as "wily", is not currently supported

### ISSUE THREAD

**Issue by DonaldSmil** [nodesource/distributions#260]
I'm trying to install node.js on my raspberry Pi 3 using ubuntu mate 15.10 and received the message:
"Your distribution, identified as "wily", is not currently supported".  Will "wily" be supported?

**Comment by mkg20001** [comment]
I have the same problem but https://deb.nodesource.com/node_5.x/dists/wily/Release seems to exist

**Comment by chrislea** [comment]
Hrm... the package is definitely in there:

https://deb.nodesource.com/node_5.x/pool/main/n/nodejs/nodejs_5.10.1-1nodesource1~wily1_armhf.deb

If you install it directly does it work properly?

**Comment by elichai** [comment]
same problem. the problem is with the script here `https://deb.nodesource.com/setup_5.x`

**Comment by elichai** [comment]
update, 
doesn't work with `https://deb.nodesource.com/setup_6.x` either.

**Comment by chrislea** [comment]
Wily should work on a Pi 3. Can you let us know exactly what command you're running and give us the full terminal output? Thanks.

**Comment by meiryasuda** [comment]
I had the same problem with ubuntu 15.10.

The command I ran:
``` 
 curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
```

The warning terminal output:
```
W: Failed to fetch http://br.archive.ubuntu.com/ubuntu/dists/wily/InRelease  

W: Failed to fetch http://br.archive.ubuntu.com/ubuntu/dists/wily-updates/InRelease  

W: Failed to fetch http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/wily/InRelease  

W: Failed to fetch http://ppa.launchpad.net/numix/ppa/ubuntu/dists/wily/InRelease  

W: Failed to fetch http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/wily/main/binary-i386/Packages  404  Not Found

W: Some index files failed to download. They have been ignored, or old ones used instead.

## Confirming "wily" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/wily/Release'

## Your distribution, identified as "wily", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by chrislea** [comment]
Ubuntu Wily is no longer supported by Canonical, so we no longer support it either. If you update to a supported distribution like Xenial, you'll find supported packages.
