### ISSUE TITLE
Your distribution, identified as "fedora-release-24-0.16.noarch", is not currently supported

### ISSUE THREAD

**Issue by Bledson** [nodesource/distributions#261]
I'm trying to install node.js on fedora xfce 24 alpha and received the message:
Your distribution, identified as "fedora-release-24-0.16.noarch", is not currently supported. Will be fedora 24 alpha/beta supported (soon)?

**Comment by chrislea** [comment]
We don't support pre-release distros in general. When FC24 hits the RC stage we may start doing builds for it then depending on what we see in the community relative to stability and etc. In the meantime you can probably install the builds for FC23 without any issues.
