### ISSUE TITLE
ARM64 Linux packages? 

### ISSUE THREAD

**Issue by aneesh-neelam** [nodesource/distributions#262]
Are there any plans to add ARM64 packages for the deb and rpm repositories? 

The Node.js website does provide ARM64 binaries [here](https://nodejs.org/dist/latest/). So, that shouldn't be too hard, right?

**Comment by nitot** [comment]
I'd be very interested too, and I'm sure I'm not the only one. FYI, Pine64 is shipping 37 000 of their Arm64 computer - https://www.kickstarter.com/projects/pine64/pine-a64-first-15-64-bit-single-board-super-comput

Best,

--Tristan

**Comment by chrislea** [comment]
Unfortunately this isn't as easy as you might imagine. We (NodeSource) don't use the same build infrastructure that the Node Foundation uses to build the official releases. They have a variety of different physical machines they use to build the releases on, whereas we rely on cross compilers to generate `arm` binaries. Also, they build a single release for each target architecture, whereas we build each binary package on the target distribution (so a package for Ubuntu Trusty is actually built using Ubuntu Trusty for example).

So, being able to do this would require having cross compilers available for all of the target distributions and also being able to get those compilers into our build workflow currently based on `pbuilder`. It's possible we'll look into it in the future but it's not on the near term roadmap I'm afraid. It may make more sense once there are fewer release lines to track as we're currently supporting 5 release lines.

**Comment by mhingston** [comment]
FWIW for others looking for ARM64 packages (deb), [termux](http://termux.net) have a repository.
