### ISSUE TITLE
Failed to install on Amazon Cloud desktop system-release-2012.03-3.16.metal.noarch

### ISSUE THREAD

**Issue by Jordan786** [nodesource/distributions#263]
curl -sL https://rpm.nodesource.com/setup | bash -

Inspecting system...
- rpm -q --whatprovides redhat-release
- uname -m

Could not determine your distribution version, you may not be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect. Include your 'distribution package'

Response of commands:
rpm -q --whatprovides redhat-release
system-release-2012.03-3.16.metal.noarch

uname -m
x86_64

Please let me know if you need any more info. Thank you!

**Comment by computermaster0101** [comment]
Hello All!

I ran into the same issue. To resolve, I used the script located at https://rpm.nodesource.com/setup then ran command "sudo yum install nodejs". Hope this helps!

**Comment by cccCody** [comment]
I have the same issue. The error message "Could not determine your distribution version..." is the output of that script
