### ISSUE TITLE
Your distribution, identified as "xenial", is not currently supported

### ISSUE THREAD

**Issue by Bizware** [nodesource/distributions#264]
**_UPDATE**:  I found an answer in this thread: https://github.com/nodesource/distributions/issues/235

"We don't support any pre-release distributions. When Xenial actually ships we will support it right away though."_

----------oOo---------------
I have tried to install Node.js on Ubuntu 16.04 with this script:

curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -

And I had this message as result:

"Your distribution, identified as "xenial", is not currently supported"

How can I solve this?  Thank you for your help   :+1:

**Comment by chrislea** [comment]
Duplicated of #258, closing.
