### ISSUE TITLE
Add support for elementary OS Loki

### ISSUE THREAD

**Issue by cassidyjames** [nodesource/distributions#265]
elementary OS Loki is an upcoming derivative of Ubuntu 16.04 Xenial that uses the Ubuntu 16.04 Xenial repositories. However, because `lsb_release -c -s` reports `loki` instead of `xenial`, nodesource says the distribution is not supported.

I see that elementary OS Freya is supported and mapped to trusty, so this should be relatively simple. :)

**Comment by Bizware** [comment]
I suggest you read this article: "**[Install Node.js 4.3 LTS on Ubuntu 16.04 Xenial Xerus LTS](https://by-example.org/install-node-js-4-3-lts-on-ubuntu-16-04-xenial-xerus-lts/)**"

That information will give you the way to install node.js in your distro. You can install node 4 or 5  with that guide.

**Comment by cassidyjames** [comment]
@Bizware I did not need help installing Node. I am reporting that the upcoming Loki version of elementary OS is currently not supported, and filed a one-line PR to fix it in the same way elementary OS Luna and Freya are supported.

**Comment by retrohacker** [comment]
Updated README.md here: https://github.com/nodesource/distributions/pull/308/commits/296dac38e9b82cbeea84917c32eaa659bbe3a5a2
