### ISSUE TITLE
Packaging policies?

### ISSUE THREAD

**Issue by djcp** [nodesource/distributions#267]
If I want a relatively recent node / npm where I'm guaranteed it'll only get bug fixes and no externally changing APIs (so a similar packaging policy to debian stable or ubuntu LTS), would I choose 4.x? 

Basically, I want to ensure all our machines get the same major/minor version of node always - now or a year from now until the version is deprecated.

Where can I read about node packaging policies?

Thanks!

**Comment by retrohacker** [comment]
Hi @djcp!

The Node.js project follows [semantic versioning](http://semver.org/)

The exact policies for the Node.js LTS release can be found on the LTS Working groups page here: https://github.com/nodejs/LTS

Tracking 4.X will bring in both minor and patch changes. Though minor bumps in LTS do happen, to quote Jeremiah Senkpiel:

> While these semver-minor increments are possible under the LTS plan, the project is attempting to keep them to a minimum, batching multiple changes where possible, such as in [the 4.4.0] release.

For an overview of the last semver-minor increment, refer to the blogpost here: https://nodesource.com/blog/node-js-v4-4-0-release-brief/

**Comment by djcp** [comment]
Thanks! 

It looks like my desire to install only  (for instance) 4.2.x until I say to install a greater minor version is not really how 4.x LTS works, as you get minor and patch updates. I wish it worked more like how Ubuntu / Debian thinks about LTS package versioning  - but maybe apt pinning can get us there.

Thanks again! We'll figure something out.
