### ISSUE TITLE
Your distribution, identified as "centos-release-6-7.el6.centos.12.3.i686", is not currently supported

### ISSUE THREAD

**Issue by honza777** [nodesource/distributions#268]
[root@centos66a node-v5.3.0]# curl --silent --location https://rpm.nodesource.com/setup_5.x | bash -

 Installing the NodeSource Node.js 5.x repo...

 Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

 Confirming "el6-i386" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_5.x/el/6/i386/nodesource-release-el6-1.noarch.rpm'

 Your distribution, identified as "centos-release-6-7.el6.centos.12.3.i686", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

### So CentOS 6.7 32-bit is not supported for Node 5.x ?

**Comment by chrislea** [comment]
Unfortunately, no, it's not. This is because to build 4.x or 5.x, we have to install a newer compiler toolchain than what CentOS 6 ships with. We do this via the enterprise linux [software collections](https://www.softwarecollections.org/en/). But, the software collections packages are 64bit only.
