### ISSUE TITLE
LinuxMint 14(Nadia) not supported

### ISSUE THREAD

**Issue by pperu** [nodesource/distributions#269]
Reading package lists... Done

## Confirming "nadia" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_5.x/dists/nadia/Release'

**Comment by retrohacker** [comment]
Hey @pperu,

We, unfortunately, do not have the resources necessary to support and test the plethora of Linux releases in the wild, so we rely on community members such as yourself to get support on your favorite distributions.

I've added LinuxMint Nadia to the list of requested releases in our README.md, it will land in https://github.com/nodesource/distributions/pull/308
