### ISSUE TITLE
Include all versions in Packages

### ISSUE THREAD

**Issue by luqasz** [nodesource/distributions#271]
Hi

I've noticed that whenever a new version is released, `https://deb.nodesource.com/node_5.x/dists/wheezy/main/binary-amd64/Packages` is updated with only given version. While `https://deb.nodesource.com/node_5.x/pool/main/n/nodejs/` has all possible versions. 

Can you generate `Packages` files with all possible versions ? This will enable easy usage of APT pining without first downloading specific version, inspecting dependencies, downloading them and then `dpkg -i package`.

**Comment by chrislea** [comment]
Duplicate of #33, closing.
