### ISSUE TITLE
centos-release-5-5.el5.centos

### ISSUE THREAD

**Issue by jkramerjj** [nodesource/distributions#272]
Linux C300152 2.6.18-308.11.1.el5.3adp #1 SMP Sun May 18 23:53:20 PDT 2014 x86_64 x86_64 x86_64 GNU/Linux

Please consider this distribution.

**Comment by chrislea** [comment]
We don't support EL5 on anything newer than 0.10.x because the compiler toolchain is too old to build a modern V8, sorry.
