### ISSUE TITLE
Problem with repository nginx configuration 

### ISSUE THREAD

**Issue by elig** [nodesource/distributions#273]
Looking at this request:
 curl -I https://deb.nodesource.com/node_4.x/dists/wheezy/main/binary-amd64/Packages.gz -H"Accept-Encoding: gzip"
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 11 Apr 2016 17:00:35 GMT
Content-Type: text/html
Last-Modified: Fri, 01 Apr 2016 06:55:36 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=15552000
Content-Encoding: gzip

1. You can see the returned Content-Type is wrong.
2.  The ETag is missing when I am requesting a compress resource, if I remove the -H"Accept-Encoding: gzip" the ETag is there, might be released to this issue [enable-etag-nginx-resources-sent-gzip](https://thinkingandcomputing.com/2014/09/27/enable-etag-nginx-resources-sent-gzip/)

Regards,
Eli

**Comment by chrislea** [comment]
It's returning `text/html` because there is still no true agreement on what the content type for a `.gz` file should be, so this is the Nginx default. Yes, there's an RFC that pushes for `application/gzip`, but it's not what's commonly in use (there's no true standard now that I'm aware of).

I'm less sure about the accept encoding thing other than it doesn't need to be sent here. The file is already gzipped before it gets served, so Nginx doesn't have to do it.

**Comment by elig** [comment]
Ok just for reference what other are sending back:
eli-mpb:Downloads eli$ curl -I http://us-west-1.ec2.archive.ubuntu.com/ubuntu/dists/vivid/main/binary-amd64/Packages.gz  -H"Accept-Encoding: gzip"
HTTP/1.1 200 OK
Date: Wed, 13 Apr 2016 12:11:23 GMT
Server: Apache/2.4.7 (Ubuntu)
Last-Modified: Fri, 24 Apr 2015 18:32:23 GMT
ETag: "1af3cd-5147c9e023bc0"
Accept-Ranges: bytes
Content-Length: 1766349
Cache-Control: max-age=0, proxy-revalidate
Expires: Wed, 13 Apr 2016 12:11:23 GMT
Content-Type: application/x-gzip

eli-mpb:Downloads eli$ curl -I http://security.ubuntu.com/ubuntu/dists/vivid/main/binary-amd64/Packages.gz  -H"Accept-Encoding: gzip"
HTTP/1.1 200 OK
Date: Wed, 13 Apr 2016 12:11:36 GMT
Server: Apache
Last-Modified: Fri, 24 Apr 2015 18:32:23 GMT
ETag: "1af3cd-5147c9e023bc0"
Accept-Ranges: bytes
Content-Length: 1766349
Cache-Control: max-age=0, s-maxage=3300, proxy-revalidate
Expires: Wed, 13 Apr 2016 12:11:36 GMT
Content-Type: application/x-gzip

When the Content-Type don't match the file type it causes problem to many tools.
