### ISSUE TITLE
Don't use curl and pipe into sh to install.

### ISSUE THREAD

**Issue by agustik** [nodesource/distributions#274]
Hey, 

I don't really like how you tell us how to install nodesource repo.

## Using the rpm nodesource-release##
```
rpm -ivh https://rpm.nodesource.com/pub_4.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm
```

## or just create the repo ##

create /etc/yum.repos.d/nodesource.repo
```
[nodesource]
name=Nodesoruce RPM repo
baseurl=https://rpm.nodesource.com/pub_4.x/el/$releasever/$basearch/
enabled=1
gpgcheck=0
```

**Comment by chrislea** [comment]
If you don't like pulling in the install script, as you note, you certainly don't have to use it. But many people find the installer scripts helpful so we'll keep providing them.
