### ISSUE TITLE
Your distribution, identified as "saucy", is not currently supported

### ISSUE THREAD

**Issue by namenyi** [nodesource/distributions#276]
I have Node v0.10.15 at the moment and would like to update to the latest one. I managed to do it on my own computer (Ubuntu 14.04) using these commands:

`curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -`
`sudo apt-get install -y nodejs`

All good, `node -v` now returns v4.4.3.

However, on the VPS we use for staging environment (Ubuntu 13.10), it just doesn't work. I've tried it with both `https://deb.nodesource.com/setup_4.x` and `https://deb.nodesource.com/setup_dev`, they both return the same error message:

> Your distribution, identified as "saucy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Any advice or suggestion on resolving this issue?

**Comment by chrislea** [comment]
Sorry, but saucy has reached end of life. We don't make new builds for distributions that are outside of their vendor support window.

**Comment by namenyi** [comment]
@chrislea alright, thanks for letting me know! I'm gonna upgrade the Ubuntu install then :)
