### ISSUE TITLE
Installing multiple nodejs packages at the same time?

### ISSUE THREAD

**Issue by alanfranz** [nodesource/distributions#278]
Hello,
i've seen and I have been using your nodejs distributions from some time; they're great,
and I think there's just one shortcoming: it's impossible to install multiple nodejs versions side-by-side, since the package name is always "nodejs"  and the files are installed in "/usr/lib/node_modules" and such similar paths.

While there's nothing inherently wrong in that, it would be failry easy to support multiple node versions at the same time on the same system: we could have packages named like

node-0.10
node-0.12
node-4.2

such packages could, each, install its files in a separate directory (e.g. /usr/lib/node-4.2/...), provide a versioned executable in path (e.g. /usr/bin/nodejs-4.2) and then the alternatives system could be used to set the "current" nodejs and node executables with the preferred version in the current environment; at the same time whoever needs a specific version could just invoke the proper executable.

the "nodejs" dependency could then be provided by each of those packages, and there could be metapackages for things like "nodejs-stable" if needed.

I'd be willing to contribute patches but it seems you're not publishing the specs or the debian packaging files.

**Comment by alanfranz** [comment]
For instance: this VERY similar to what happens with Java/JDK packages on Ubuntu and Centos/Redhat, and I think it works properly.

**Comment by chrislea** [comment]
We talked about doing this but decided against it for two reasons. 1) The general consensus amongst most people we asked was that this would be more confusing than just keeping everything separate. 2) the path to the `node_modules` directory is hardcoded into tons and tons of things, and the contents of that directory is not identical across different versions (we actually nuke any pre-existing instance of that directory on installation just to be safe), so figuring out a sane way to version that would be a lot of trouble.

**Comment by chrislea** [comment]
Oh, but also, if you do want to try something like this for yourself, the source packages are available in the same place as the binaries.

**Comment by retrohacker** [comment]
A popular solution, for people who need multiple versions of Node, is to use a manager such as `n` or `nvm`

**Comment by alanfranz** [comment]
Thanks for your reply.

@chrislea when you say "the path to the node_modules directory is hardcoded into tons and tons of things", you mean in your distribution or in nodejs source code itself? I mean: I was under the impression that if I download a binary nodejs distribution from

https://nodejs.org/en/download/

I could install it anywhere and launch node and/or npm from there, and the relative node_modules path would be correctly respected - I did something like that multiple times and I haven't got any error so far. Was I just lucky?

@retrohacker n or nvm are ok for personal, interactive use on a workstation. They're not suitable for use on servers, where I just want my packages to pull a dependency when installed.
