### ISSUE TITLE
Centos 5.11 install error

### ISSUE THREAD

**Issue by b60413** [nodesource/distributions#279]
curl --silent --location https://rpm.nodesource.com/setup_5.x | bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el5-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_5.x/el/5/x86_64/nodesource-release-el5-1.noarch.rpm'

## Your distribution, identified as "centos-release-5-11.el5.centos", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
Sorry, but CentOS 5 / RHEL 5 aren't supported for newer versions of Node due to the compiler toolchain being tool ancient to build a modern V8.
