### ISSUE TITLE
ARMHF missin on Xenial

### ISSUE THREAD

**Issue by meyskens** [nodesource/distributions#280]
The ARMHF package is missing in the Xenial 4.x realease.

**Comment by chrislea** [comment]
Yup, I know. It's because there's some bug with the QEMU emulator on Xenial that makes the builds segfault. Same thing is happening trying to build for Debian Sid. I'm looking into it but don't have anything to report other than that at this time.

**Comment by chrislea** [comment]
After a little more investigation, it appears to be this bug (which is not with the emulator, it's in the `ubuntu-dev-tools` package).

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816097

Unfortunately there's not much else we can do immediately about the situation, but I'll be monitoring the bug as closely as I can.

**Comment by chrislea** [comment]
Okay, I managed a workaround to build `armhf` 4.4.3 for Xenial and Sid. The process is a little different than what happens for all the other packages, so if you could try it out @meyskens that would be great. I have high confidence that the packages themselves are fine, what I'm mostly interested in is whether or not all the "repo" stuff works as expected. Meaning the installer script, using `apt-get upgrade` and that sort of thing.

**Comment by meyskens** [comment]
Works fine 👍
