### ISSUE TITLE
Unable to install on Ubuntu 14

### ISSUE THREAD

**Issue by gotenxds** [nodesource/distributions#282]
Hello I'm trying to install node (tried 5.x, 4.x and 0.12) on my ubuntu 14 and when running the 
```
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
```

command I get the following error:

```
W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting
```

Any idea whats the problem might be?

**Comment by chrislea** [comment]
Well, I'm not sure what's going on with your system, but you're trying to get a `Release` file for Google Chrome from `dl.google.com` there and that's where it's failing. Doesn't look like it has anything to do with our repo.

I'd recommend downloading the `.deb` from https://www.google.com/chrome and installing it manually to see if that fixes the `sources.list.d` entry that's causing problems.
