### ISSUE TITLE
deb setup_6.x error

### ISSUE THREAD

**Issue by Nolapete** [nodesource/distributions#284]
~/Downloads $ curl -sL https://deb.nodesource.com/setup_6.x | bash -
bash: line 1: html: No such file or directory
bash: line 2: syntax error near unexpected token `<'
'ash: line 2: `<head><title>404 Not Found</title></head>

**Comment by tleb** [comment]
It is a 404, normal it doesn't work.

I think you can use the direct link, at least for the moment: https://raw.githubusercontent.com/nodesource/distributions/master/deb/setup_6.x

**Comment by iperevozchikov** [comment]
the raw link above can not be working, because dists folder under the https://deb.nodesource.com/node_6.x/ is absent.

**Comment by tleb** [comment]
My bad, sorry for the wrong lead.

**Comment by isergey** [comment]
https://deb.nodesource.com/node_6.x/dists/rosa/main/binary-amd64/Packages  HttpError404

**Comment by chrislea** [comment]
The packages aren't built yet for 6.x. Once they are built, we'll push them as well as these setup scripts live.

**Comment by chrislea** [comment]
The packages are live now, enjoy!

**Comment by oncletom** [comment]
Thanks @chrislea :-)
