### ISSUE TITLE
rpm's missing or not present 

### ISSUE THREAD

**Issue by chacliff** [nodesource/distributions#287]
hello i am getting the following erorrs when trying to use the install command yum install -nodejs. 

machine: centos 7 

The .rpm's seem to be missing or no longer accessible. I've previously used your instructions and had no problems. 

this occurs while attempting to install 4.x, 5.x or 6.x
nodejs-0.10.44-1nodesource.el7 FAILED
https://rpm.nodesource.com/pub_4.x/el/7/x86_64/nodejs-0.10.44-1nodesource.el7.centos.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.

**Comment by chrislea** [comment]
That package is certainly available [here](https://rpm.nodesource.com/pub_0.10/el/7/x86_64/nodejs-0.10.44-1nodesource.el7.centos.x86_64.rpm). Can you let us know exactly what command you are running where you see this?

**Comment by chacliff** [comment]
yum install nodejs -y

**Comment by chrislea** [comment]
Looking at the output, there's a mismatch somehow on your system for where it's looking for packages. Specifically, it's looking for the `0.10.44` release under the `pub_4.x` directory where it's not going to find it. I'd check your repo setup and make sure everything lines up.

**Comment by chacliff** [comment]
i'll see if i can just remove the repo in general and start from scratch. i'm not too experienced in this enviroment, but thanks!

**Comment by chacliff** [comment]
not really sure where it gets the $basearch variable from but it looks to me that its what choosing to go to that path and not resolving to a file in the directory to download the .rpm from 
[nodesource]
name=Node.js Packages for Enterprise Linux 7 - $basearch
baseurl=https://rpm.nodesource.com/pub_4.x/el/7/$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL

[nodesource-source]
name=Node.js for Enterprise Linux 7 - $basearch - Source
baseurl=https://rpm.nodesource.com/pub_4.x/el/7/SRPMS
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
gpgcheck=1
