### ISSUE TITLE
 "kali-rolling", is not currently supported

### ISSUE THREAD

**Issue by honeyfairy** [nodesource/distributions#289]
`root@green:~# curl -sL https://deb.nodesource.com/setup | sudo -E bash -

## Populating apt-get cache...

+ apt-get update
Hit:1 http://ftp.halifax.rwth-aachen.de/kali kali-rolling InRelease
Reading package lists... Done

## Confirming "kali-rolling" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_0.10/dists/kali-rolling/Release'

## Your distribution, identified as "kali-rolling", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support`

**Comment by rvagg** [comment]
Thanks for reporting this @honeyfairy, unfortunately we are not in a position to test or even understand all of the various deb-based systems out there so we have to rely on users to provide that information for us. If you look at https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L81-L95 you'll see where we do mapping from Debian or Ubuntu based distributions back to their parents, or at least back to Debian or Ubuntu versions that are compatible enough. If you can figure out which distro and version `kali-rolling` is based off then send us a pull request to add a new line to that section and we can get it in.
