### ISSUE TITLE
Error msg while trying to install

### ISSUE THREAD

**Issue by booms-edv** [nodesource/distributions#29]
Hello,

I got today the following error message:
"## Your distribution, identified as "squeeze", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support".

Can you fix that or tell me how I can fix that?

Thanks in advance,

Thomas

**Comment by rvagg** [comment]
As I said in #23: We're having a hard enough time supporting wheezy, I'm sad to say that we're unlikely to support squeeze
