### ISSUE TITLE
Manual installation instructions for EL / Fedora

### ISSUE THREAD

**Issue by pwnall** [nodesource/distributions#290]
It would be nice to have a section that is similar to Ubuntu's section.

I think this would come down to documenting `https://rpm.nodesource.com/pub_6.x/` as a Yum repository (I use `https://rpm.nodesource.com/pub_6.x/fc/$releasever/$basearch`) and documenting `https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL` as the location that holds the GPG signing key.

Thank you for packaging node 6 early! I'm really grateful for all your work!

**Comment by andyfitz** [comment]
Any chance to support Fedora 26 ?

**Comment by chrislea** [comment]
As [previously noted](https://github.com/nodesource/distributions/issues/461), we'll support FC26 when the final release is available.
