### ISSUE TITLE
Consider creating distrobution without npm

### ISSUE THREAD

**Issue by jgrund** [nodesource/distributions#291]
Hi, 

Is there any reason why npm needs to be bundled in with a distribution?

It would be great to have a build that just included Node.js without packaging npm.

**Comment by chrislea** [comment]
It's our view that practically speaking, you're not really using Node if you don't have the availability of npm. In fact, one of the reasons we started making community distribution packages years ago was to ensure that npm was always bundled in the main nodejs package, as the official distribution packages tend to separate them which was causing confusion / trouble for a lot of people.
