### ISSUE TITLE
yakkety (Ubuntu gnome 16.04) not supported

### ISSUE THREAD

**Issue by mvondoyannick** [nodesource/distributions#292]
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -

## Populating apt-get cache...

+ apt-get update
Atteint:1 http://cm.archive.ubuntu.com/ubuntu yakkety InRelease
Atteint:2 http://security.ubuntu.com/ubuntu yakkety-security InRelease                          
Atteint:3 http://cm.archive.ubuntu.com/ubuntu yakkety-updates InRelease
Atteint:4 http://cm.archive.ubuntu.com/ubuntu yakkety-backports InRelease
Atteint:5 https://deb.opera.com/opera-developer stable InRelease
Lecture des listes de paquets... Fait

## Confirming "yakkety" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_5.x/dists/yakkety/Release'

## Your distribution, identified as "yakkety", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Need your help to install nodejs v6 into my linux distribution. thanks

**Comment by rvagg** [comment]
The releases we support are listed on the README and it notes that we only support the active releases Canonical support, which won't include yakkety until October. Have a look at the README at the [manual instructions](https://github.com/nodesource/distributions#manual-installation) and substitute xenial and you'll probably be OK.

**Comment by mmilkin** [comment]
Whats the time table for yakkety being supported?

**Comment by chrislea** [comment]
Yakkety has been supported since it was released.

__
