### ISSUE TITLE
Official documentation: piping curl to shell for installation 

### ISSUE THREAD

**Issue by CalvinHartwell** [nodesource/distributions#294]
I opened up an issue with the docs but they told me to open the issue up here instead and closed my original one ([https://github.com/nodejs/docs/issues/106](https://github.com/nodejs/docs/issues/106)). 

This has probably been mentioned before, but I believe this is pretty bad practice (https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora):

`curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -`

I believe the scenario described in this link is actually present in the script: https://www.seancassidy.me/dont-pipe-to-your-shell.html

RPM_TMP=$(mktemp || bail)
exec_cmd "rm -f '${RPM_TMP}'

So, if the connection is closed mid stream, you could remove some things accidentally from the temp dir and the user would not be aware of it.

My suggested fix is: 

curl --silent --location https://rpm.nodesource.com/setup_4.x > install-node.sh && chmod 500 install-node.sh && ./install-node.sh

My version of the command would not attempt to execute the script if curl had failed (non zero error code from timeouts, etc). It may also be a good idea to remove the --silent incase there has been an issue with curl (for example, if a proxy blocks nodejs.org, it will fail silently).

**Comment by rvagg** [comment]
Thanks for the thoughtful report @CalvinHartwell. We provide an easy curl|bash solution for convenience but also provide manual instructions on the README for people who dislike the practice for whatever reason. At this stage we're going to continue to offer the simple version and extended version rather than opt for something in between. Cheers.
