### ISSUE TITLE
Support rsync protocol

### ISSUE THREAD

**Issue by narqo** [nodesource/distributions#295]
Hello, everyone!

I've just talked to the guys who stand behind [mirror.yandex.ru](http://mirror.yandex.ru/) about mirroring repos of nodesource.

> mirror.yandex.ru mirrors Linux, BSD and other open sources projects. 
> As it is hosted by [Yandex](https://yandex.com/company/), it is distributed across several DCs in Russia, so it is highly available in Russia and Eastern Europe.
> It supports http(s), ftp and rsync protocols. And it has IPv6 support as well.

Before the mirror can be made, they asked if it is possible to support rsync protocol on rpm/deb.nodesource.com as it's much more suitable for mirroring.

**Comment by chrislea** [comment]
Hey @narqo. Normally I'd be all for this as we'd like to make those repositories maximally available to everybody. However, we're planning on moving them to Amazon S3 / CloudFront soon where I don't think we have the option to use `rsync`. So I'd prefer not to enable `rsync` on the existing repos and then have to take that functionality away once we're hosting on AWS.

Hope this makes sense.
