### ISSUE TITLE
Your distribution, identified as "saucy", is not currently supported

### ISSUE THREAD

**Issue by suneel2you** [nodesource/distributions#297]
Ubuntu 13.10 my Operating system, When I was trying to install node js 
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs

I GOT these issue.

Reading package lists... Done

## Confirming "saucy" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_4.x/dists/saucy/Release'

**Comment by rvagg** [comment]
Saucy hasn't been supported by canonical for quite some time now and we don't support versions of Ubuntu that aren't supported upstream. Your best bet is to upgrade one version to Trustry, 14.04, which is the closest LTS release which is still supported and will be for some time yet.

**Comment by suneel2you** [comment]
@rvagg Thank You
