### ISSUE TITLE
¿How to install Node binary distributions on Docker Alpine?

### ISSUE THREAD

**Issue by diegoug** [nodesource/distributions#298]
Hello everyone,

like the topic says, I want to install binary nodejs on apine docker image, but I dont know how to do that, i saw the instructions of apine image at [https://hub.docker.com/_/alpine/](url) and it have their own packages [http://pkgs.alpinelinux.org/packages](url), and in your main site says it only suport debian, red hat and derivatives images, do you know what can i do to install nodejs on apine?

Thanks.

**Comment by retrohacker** [comment]
Hey @diegoug,

When you say `binary`, I assume you mean dynamically linked. If you mean statically linked, this is not currently possible with Node.js.

mhart currently provides a set of these images here: https://github.com/mhart/alpine-node
