### ISSUE TITLE
Vivid is not currently supported 

### ISSUE THREAD

**Issue by eloyucu** [nodesource/distributions#301]
Hello everyone.
I am getting a problem whe I try to make:

curl -sL https://deb.nodesource.com/setup_6.x | bash -

The problem is that my distro is not supported, but I am using Ubuntu 15.04 and in this page: 
https://nodejs.org/en/download/package-manager/#arch-linux
on the Supported Ubuntu Versions, it shows Ubuntu 15.04 (Vivid Vervet)... 
Why not for me?? What can I do to install nodejs>=5?

Thanks

**Comment by chrislea** [comment]
Our apologies, that page on the nodejs.org website needs to be updated. The correct and up-to-date information is always here:

https://github.com/nodesource/distributions/

We only support Ubuntu distributions that are still receiving security updates from Canonical, and Vivid has reached EOL so it is no longer supported. We recommend that you update to a supported release ASAP so you can keep getting security updates as well as new builds of Node.js.

**Comment by eloyucu** [comment]
Ok Thanks!!
