### ISSUE TITLE
Good afternoon. Why did you stop support?

### ISSUE THREAD

**Issue by linuxoid69** [nodesource/distributions#302]
+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_5.x/dists/jessie/Release'

`## Your distribution, identified as "jessie", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support`

**Comment by chrislea** [comment]
I'm sorry but I'm not sure what you mean? Debian Jessie is still fully supported:

https://deb.nodesource.com/node_5.x/pool/main/n/nodejs/

I'm not sure what you hope to see by curling the `Release` file into `/dev/null`?
