### ISSUE TITLE
when using the setup script for node 6 I get  "fedora-release-21-2.noarch", is not currently supported, please contact NodeSource

### ISSUE THREAD

**Issue by atlantageek** [nodesource/distributions#311]
Your distribution, identified as "fedora-release-21-2.noarch", is not currently supported, please contact NodeSource

**Comment by retrohacker** [comment]
@atlantageek could you please post the command you are running along with its full output?

**Comment by atlantageek** [comment]
I just figured it out.  Apparently node v6.0 does not support fedora 21.

**Comment by chrislea** [comment]
Thanks for the catch @atlantageek .... just removed FC21 from our docs as it's been EOL for a few months now.
