### ISSUE TITLE
distribution sarah not supported

### ISSUE THREAD

**Issue by tejinderss** [nodesource/distributions#313]
linux mint 18 beta

**Comment by BandonRandon** [comment]
This is something I'd like to see as well. Linux Mint 18 "Sarah" is [now in beta](https://www.linuxmint.com/rel_sarah_cinnamon.php) Linux Mint 18 is based on Ubuntu 16.04 so may just need to clone that repo with a new name. For now I'll compile from source. 

Thanks for the attention.

**Comment by rvagg** [comment]
See https://github.com/nodesource/distributions#debmanual for how to set this up manually, just pin to xenial for now. We don't normally add support for distributions until they are stable and as a beta Sara doesn't qualify.

**Comment by rvagg** [comment]
As per discussion in https://github.com/nodesource/distributions/pull/312 we've gone ahead and pushed support live to the scripts, the justification being that Xenial isn't in Beta so it doesn't impact us as much. Please give it a try and let us know how you go.

**Comment by deathmood** [comment]
works fine)) thanks
