### ISSUE TITLE
unicode segment fault

### ISSUE THREAD

**Issue by gestapolur** [nodesource/distributions#32]
When I run scripts in a unicode language environment, the script give me a segment fault error.
```
curl -sL https://deb.nodesource.com/setup | sudo bash -

## Populating apt-get cache...

+ apt-get update
命中 http://dl.google.com stable Release.gpg                                   
命中 http://dl.google.com stable Release.gpg                                   
...
bash: 行 28:  1877 段错误               (核心已转储) bash -c "$1"              
Error executing command, exiting
```
It said in line 28 a segment fault occured.

locale:
```
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:en
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC=zh_CN.UTF-8
LC_TIME=zh_CN.UTF-8
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY=zh_CN.UTF-8
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER=zh_CN.UTF-8
LC_NAME=zh_CN.UTF-8
LC_ADDRESS=zh_CN.UTF-8
LC_TELEPHONE=zh_CN.UTF-8
LC_MEASUREMENT=zh_CN.UTF-8
LC_IDENTIFICATION=zh_CN.UTF-8
LC_ALL=
```
```
bash --version
GNU bash, version 4.2.25(1)-release (i686-pc-linux-gnu)
```
While setting locale to `LANG=C`, everything work fine.
```
~$ LANG=C curl -sL https://deb.nodesource.com/setup | sudo bash -
```
I am wondering if it occured in other unicode character language. Although it could run by setting `LANG=C`, it's more convience for others if you cloud solve this.

**Comment by retrohacker** [comment]
@gestapolur we have been unable to reproduce this and the issue hasn't had any activity since 2014.

If you continue to have problems with the setup scripts using unicode, please reopen this issue and we can help debug!
