### ISSUE TITLE
Your distribution, identified as "redhat-release-5Server-5.11.0.2", is not currently supported

### ISSUE THREAD

**Issue by cnestor1** [nodesource/distributions#320]
I have the previous message when trying to Install the NodeSource Node.js 6.x repo...
(sudo curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -)

I thought that RHEL 5 (32-bit and 64-bit) was supported. Which version is supported?
Thanks.

**Comment by gabrielenosso** [comment]
I have the same problem with "redhat-release-server-6Server-6.4.0.4.0.1.el6.x86_64"

**Comment by chrislea** [comment]
We can't support EL5 on modern versions of Node (>= 4.x), nor can we support 32bit versions of EL6, because [we don't have compilers that will work on those targets](https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md). Sorry!
