### ISSUE TITLE
can not install on Ubuntu due 404 error

### ISSUE THREAD

**Issue by mohsenkashi** [nodesource/distributions#324]
```
mohsen@mohsen-ThinkPad-Edge-E440:~$ curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

## Installing the NodeSource Node.js v6.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://ir.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://ir.archive.ubuntu.com/ubuntu xenial-updates InRelease                                                                                                                                                         
Hit:3 http://ir.archive.ubuntu.com/ubuntu xenial-backports InRelease                                                                                                                                                       
Hit:4 http://archive.canonical.com/ubuntu xenial InRelease                                                                                                                                           
Hit:5 http://deb.opera.com/opera-stable stable InRelease                                                                                                                     
Hit:6 http://ppa.launchpad.net/atareao/atareao/ubuntu xenial InRelease                                                      
Hit:7 http://ppa.launchpad.net/bablu-boy/nutty.0.1/ubuntu xenial InRelease
Get:8 http://security.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]
Ign:9 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial InRelease             
Hit:10 http://ppa.launchpad.net/maarten-baert/simplescreenrecorder/ubuntu xenial InRelease
Hit:11 http://ppa.launchpad.net/noobslab/apps/ubuntu wily InRelease                   
Hit:12 http://ppa.launchpad.net/webupd8team/java/ubuntu wily InRelease                
Hit:13 http://ppa.launchpad.net/webupd8team/java/ubuntu vivid InRelease
Ign:14 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial Release
Ign:15 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main amd64 Packages
Ign:16 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main i386 Packages
Ign:17 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main all Packages
Ign:18 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main Translation-en_US
Ign:19 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main Translation-en
Ign:20 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:21 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main DEP-11 64x64 Icons
Ign:15 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main amd64 Packages
Ign:16 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main i386 Packages
Ign:17 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main all Packages
Ign:18 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main Translation-en_US
Ign:19 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main Translation-en
Ign:20 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:21 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main DEP-11 64x64 Icons
Ign:15 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main amd64 Packages
Ign:16 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main i386 Packages
Ign:17 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main all Packages
Ign:18 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main Translation-en_US
Ign:19 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main Translation-en
Ign:20 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:21 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main DEP-11 64x64 Icons
Ign:15 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main amd64 Packages
Ign:16 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main i386 Packages
Ign:17 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main all Packages
Ign:18 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main Translation-en_US
Ign:19 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main Translation-en
Ign:20 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:21 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main DEP-11 64x64 Icons
Ign:15 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main amd64 Packages
Ign:16 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main i386 Packages
Ign:17 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main all Packages
Ign:18 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main Translation-en_US
Ign:19 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main Translation-en
Ign:20 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:21 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main DEP-11 64x64 Icons
Err:15 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main amd64 Packages
  404  Not Found
Ign:16 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main i386 Packages
Ign:17 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main all Packages
Ign:18 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main Translation-en_US
Ign:19 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main Translation-en
Ign:20 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:21 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main DEP-11 64x64 Icons
Fetched 94.5 kB in 5s (16.9 kB/s)
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting
mohsen@mohsen-ThinkPad-Edge-E440:~$ 

```

**Comment by rvagg** [comment]
Hey @mohsenkashi, it looks like it's getting hung up on the now very redundant launchpad repo that these distributions replace. It doesn't exist so it's failing on a simple `apt-get update` right at the begining of the script.

Try running these two commands to fully remove the old repo:

```
sudo add-apt-repository -y -r ppa:chris-lea/node.js
sudo rm -f /etc/apt/sources.list.d/chris-lea-node_js-*.list
```

Then run the setup script again and cross your fingers. Let us know how you get on.

**Comment by mohsenkashi** [comment]
Thanks @rvagg that works

**Comment by rvagg** [comment]
phew! glad it wasn't anything more complex.

**Comment by jhnferraris** [comment]
Hello I tried this solution but I'm still expecting the same error.

**Comment by jhnferraris** [comment]
Fixed mine.

I removed everything that is related to `chris_lea` and then rerun the script

sudo rm -f /etc/apt/sources.list.d/ppa_chris_lea_node_js_*

**Comment by blemn** [comment]
help me 
root@kali:~# apt-get update
Ign:1 http://ppa.launchpad.net/webupd8team/... trusty InRelease
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease
Ign:3 http://ppa.launchpad.net/webupd8team/... trusty Release
Atteint:4 http://dl.google.com/linux/chrome/deb stable Release
Ign:5 http://ppa.launchpad.net/webupd8team/... trusty/main Sources
Ign:6 http://ppa.launchpad.net/webupd8team/... trusty/main i386 Packages
Ign:7 http://ppa.launchpad.net/webupd8team/... trusty/main all Packages
Ign:9 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-fr_FR
Ign:10 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-fr
Ign:11 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-en
Ign:5 http://ppa.launchpad.net/webupd8team/... trusty/main Sources
Ign:6 http://ppa.launchpad.net/webupd8team/... trusty/main i386 Packages
Ign:7 http://ppa.launchpad.net/webupd8team/... trusty/main all Packages
Ign:9 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-fr_FR
Ign:10 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-fr
Ign:11 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-en
Ign:5 http://ppa.launchpad.net/webupd8team/... trusty/main Sources
Ign:6 http://ppa.launchpad.net/webupd8team/... trusty/main i386 Packages
Ign:7 http://ppa.launchpad.net/webupd8team/... trusty/main all Packages
Ign:9 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-fr_FR
Ign:10 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-fr
Ign:11 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-en
Ign:5 http://ppa.launchpad.net/webupd8team/... trusty/main Sources
Ign:6 http://ppa.launchpad.net/webupd8team/... trusty/main i386 Packages
Ign:7 http://ppa.launchpad.net/webupd8team/... trusty/main all Packages
Ign:9 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-fr_FR
Ign:10 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-fr
Ign:11 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-en
Ign:5 http://ppa.launchpad.net/webupd8team/... trusty/main Sources
Ign:6 http://ppa.launchpad.net/webupd8team/... trusty/main i386 Packages
Ign:7 http://ppa.launchpad.net/webupd8team/... trusty/main all Packages
Ign:9 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-fr_FR
Ign:10 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-fr
Ign:11 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-en
Err:5 http://ppa.launchpad.net/webupd8team/... trusty/main Sources
  404  Not Found
Ign:6 http://ppa.launchpad.net/webupd8team/... trusty/main i386 Packages
Ign:7 http://ppa.launchpad.net/webupd8team/... trusty/main all Packages
Ign:9 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-fr_FR
Ign:10 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-fr
Ign:11 http://ppa.launchpad.net/webupd8team/... trusty/main Translation-en
Lecture des listes de paquets... Fait
W: The repository 'http://ppa.launchpad.net/webupd8team/... trusty Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://dl.google.com/linux/chrome/deb stable InRelease' doesn't support architecture 'i386'
E: Impossible de récupérer http://ppa.launchpad.net/webupd8team/.../dists/trusty/main/source/Sources  404  Not Found
E: Le téléchargement de quelques fichiers d'index a échoué, ils ont été ignorés, ou les anciens ont été utilisés à la place.

**Comment by chrislea** [comment]
This is failing because of a problem with another repository on Launchpad from `webupd8team`:
```shell
W: The repository 'http://ppa.launchpad.net/webupd8team/... trusty Release' does not have a Release file.
```
We can't do anything to help that I'm afraid.

**Comment by bholagabbar** [comment]
@chrislea So basically, we can't run Node 6+ on Ubuntu/Linux right? I mean I've been facing this problem since today morning and no fix. Ended up settling for the old node 4.x which is already deprecated

**Comment by chrislea** [comment]
@bholagabbar I don't know what error you are seeing, but Node 6.x is supported on all currently supported versions of Ubuntu. So you should be able to use it just fine.

**Comment by BR0kEN-** [comment]
@chrislea I'm getting the same error as @mohsenkashi:

```
Err:9 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main amd64 Packages
  404  Not Found
```

This happens due to PPA doesn't contain a dist for Xenial (http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/xenial - not found).

Could this be resolved?

**Comment by BR0kEN-** [comment]
Ah, my previous comment is totally wrong. This happens only if you previously tried `apt install nodejs`. This actions adds wrong entries to `sources.list.d` and then APT starts looking up into the wrong place.

**Comment by zave** [comment]
I don't understand why BR0kEN's comment is totally wrong. The nodejs PPA mentioned above does not, in fact, exist.

**Comment by BR0kEN-** [comment]
@zave, using one of the installers (like `https://deb.nodesource.com/setup_6.x`) you must not have PPA repository added (`ppa:chris-lea/node.js`).

**Comment by mbze430** [comment]
still have 'apt remove nodejs' still can't install v6.x+

`Fetched 306 kB in 6s (43.9 kB/s)
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/upubuntu-com/web/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/upubuntu-com/web/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting`

**Comment by chrislea** [comment]
@mbze430 That error is saying there's some problem with the repository `http://ppa.launchpad.net/upubuntu-com/web/ubuntu`, which we don't control. Sorry, but there's nothing we can do to help you with that.

**Comment by jimmydave03** [comment]
@rvagg Thanks for the solution. It works.

**Comment by teosbpl** [comment]
@rvagg thx pal. works like a charm.

**Comment by Skrach34** [comment]
Hi **@rvagg**, did what you said and it didn't work for me :(, maybe because I didn't understand 

> Then run the setup script again

What setup script? Sorry for my ignorance.

**Comment by rvagg** [comment]
@Skrach34 `curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -`

**Comment by ZheyangSong** [comment]
Just in case that this will help anyone in the future, I ran into this issue when installing nodeJS in WSL (Windows Subsystem for Linux). It turned out that `sudo wget -qO- https://deb.nodesource.com/setup_8.x | sudo -E bash -` worked rather than `curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -`

**Comment by modestguy** [comment]
thank you, bro!

**Comment by elirehema** [comment]
@rvagg Thanks Much Bro!

**Comment by AhmedAliIbrahim** [comment]
I'm facing the same issue, tried the above solution but still getting The repository 'http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial Release' does not have a Release file.

**Comment by cncqw** [comment]
edit file：`/etc/apt/sources.list.d/chris-lea-ubuntu-node_js-xenial.list`

```
deb http://ppa.launchpad.net/chris-lea/node.js/ubuntu trusty main

deb-src http://ppa.launchpad.net/chris-lea/node.js/ubuntu trusty main
```

**Comment by stvenyin** [comment]
see.

**Comment by stvenyin** [comment]
Ign:105 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main Translation-en_US
Ign:106 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main Translation-en
Ign:107 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:108 http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial/main DEP-11 64x64 Icons
Fetched 54.4 MB in 38s (1,398 kB/s)
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/chris-lea/node.js/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
root@stvenyin-virtual-machine:/etc/apt# sudo su
root@stvenyin-virtual-machine:/etc/apt# sudo add-apt-repository -y -r ppa:chris-lea/node.js
root@stvenyin-virtual-machine:/etc/apt# sudo rm -f /etc/apt/sources.list.d/chris-lea-node_js-*.list
root@stvenyin-virtual-machine:/etc/apt# apt-get update
Hit:1 http://mirrors.aliyun.com/ubuntu xenial InRelease
Hit:2 http://mirrors.aliyun.com/ubuntu xenial-updates InRelease                                                                                                                                                                              
Hit:3 http://mirrors.aliyun.com/ubuntu xenial-backports InRelease                                                                                                                                                                            
Hit:4 http://mirrors.aliyun.com/ubuntu xenial-security InRelease                                                                                                                        
Hit:5 http://cn.archive.ubuntu.com/ubuntu xenial InRelease                                                                                                                              
Hit:6 http://cn.archive.ubuntu.com/ubuntu xenial-updates InRelease                                                                                                              
Hit:7 http://security.ubuntu.com/ubuntu xenial-security InRelease                                                                                     
Hit:8 http://archive.canonical.com/ubuntu xenial InRelease                                                                                       
Hit:9 https://dl.yarnpkg.com/debian stable InRelease                                                                       
Hit:10 http://cn.archive.ubuntu.com/ubuntu xenial-backports InRelease                                 
Hit:11 http://archive.ubuntu.com/ubuntu xenial InRelease                                              
Reading package lists... Done

**Comment by stvenyin** [comment]
see.

**Comment by stvenyin** [comment]
root@stvenyin-virtual-machine:/etc/apt# sudo su
root@stvenyin-virtual-machine:/etc/apt# sudo add-apt-repository -y -r ppa:chris-lea/node.js
root@stvenyin-virtual-machine:/etc/apt# sudo rm -f /etc/apt/sources.list.d/chris-lea-node_js-*.list
root@stvenyin-virtual-machine:/etc/apt# apt-get update
Hit:1 http://mirrors.aliyun.com/ubuntu xenial InRelease
Hit:2 http://mirrors.aliyun.com/ubuntu xenial-updates InRelease                                                                                                                                                                              
Hit:3 http://mirrors.aliyun.com/ubuntu xenial-backports InRelease                                                                                                                                                                            
Hit:4 http://mirrors.aliyun.com/ubuntu xenial-security InRelease                                                                                                                        
Hit:5 http://cn.archive.ubuntu.com/ubuntu xenial InRelease                                                                                                                              
Hit:6 http://cn.archive.ubuntu.com/ubuntu xenial-updates InRelease                                                                                                              
Hit:7 http://security.ubuntu.com/ubuntu xenial-security InRelease                                                                                     
Hit:8 http://archive.canonical.com/ubuntu xenial InRelease                                                                                       
Hit:9 https://dl.yarnpkg.com/debian stable InRelease                                                                       
Hit:10 http://cn.archive.ubuntu.com/ubuntu xenial-backports InRelease                                 
Hit:11 http://archive.ubuntu.com/ubuntu xenial InRelease                                              
Reading package lists... Done

**Comment by officialAmanchauhan** [comment]
Err:1 http://your.repo.domain/repository n/a InRelease
  Something wicked happened resolving 'your.repo.domain:http' (-5 - No address associated with hostname)
Hit:2 http://dl.google.com/linux/chrome/deb stable InRelease
Ign:3 https://deb.nodesource.com n/a InRelease                                 
Hit:4 https://mirrors.dotsrc.org/parrot rolling InRelease                   
Err:5 https://deb.nodesource.com n/a Release  
  404  Not Found [IP: 23.32.28.57 443]
Reading package lists... Done
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Translations (main/i18n/Translation-en_IN) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Packages (contrib/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Packages (contrib/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Translations (contrib/i18n/Translation-en_IN) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Translations (contrib/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Packages (non-free/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Packages (non-free/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Translations (non-free/i18n/Translation-en_IN) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Translations (non-free/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
E: The repository 'https://deb.nodesource.com n/a Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Translations (main/i18n/Translation-en_IN) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Packages (contrib/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Packages (contrib/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Translations (contrib/i18n/Translation-en_IN) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Translations (contrib/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Packages (non-free/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Packages (non-free/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Translations (non-free/i18n/Translation-en_IN) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
W: Target Translations (non-free/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/parrot.list:3 and /etc/apt/sources.list.d/parrot.list:5
 
On running sudo apt-get update , i always get this error what should i do???
