### ISSUE TITLE
unable to install nodejs on rhel

### ISSUE THREAD

**Issue by ChhotaDon** [nodesource/distributions#329]
I am trying to install nodejs on rhel but facing following problem:

Could not determine your distribution version, you may not be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect. Include your 'distribution package' name: system-release-2012.03-3.16.metal.noarch.

**Comment by rvagg** [comment]
I'm pretty sure system-release means you're running Amazon Linux rather than RHEL. We only support recent versions of Amazon Linux unfortunately, you'll have to upgrade your system (which is probably a good idea anyway, 2012 is a long time ago for Amazon Linux).
