### ISSUE TITLE
Installing node v0.12 on RHEL5

### ISSUE THREAD

**Issue by polhedel** [nodesource/distributions#331]
I'm running a RHEL5 and I'm trying to install the node.js v0.10 which is suposed to be supported...

Supported Red Hat® Enterprise Linux® versions:

RHEL 5 (32-bit and 64-bit) [For Node < 0.12.x]

But I get the message "You don't appear to be running a supported version of Enterprise Linux... dustribution package name: enterprise-release-5-0.0.22"

How can I install then nodejs v0.10?

Thank you!

**Comment by rvagg** [comment]
"enterprise-release" suggests you're using Oracle Linux. I've proposed adding support here: https://github.com/nodesource/distributions/pull/333

**Comment by rvagg** [comment]
_should_ work now, please let us know @polhedel
