### ISSUE TITLE
Error installing on ARM64

### ISSUE THREAD

**Issue by Homoran** [nodesource/distributions#339]
Trying to install nodejs on Pine64 with the command:
`curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -`
I get the error:
`Fehlschlag beim Holen von https://deb.nodesource.com/node_4.x/dists/jessie/InRelease  Erwarteter Eintrag »main/binary-arm64/Packages« konnte in Release-Datei nicht gefunden werden (falscher Eintrag in sources.list oder missgebildete Datei)`
(means something like: Error by getting https://deb.nodesource.com/node_4.x/dists/jessie/InRelease 
Expected entry »main/binary-arm64/Packages« couldn't be found in release-file
wrong entry in sources.list or broken file.)
I tried it many times

The ARM64 is identified correctly

**Comment by chrislea** [comment]
Duplicated of #262 .
