### ISSUE TITLE
REQUEST for support of Node.js v6

### ISSUE THREAD

**Issue by cnartey** [nodesource/distributions#343]
Your distribution, identified as "redhat-release-server-6Server-6.7.0.3.0.1.el6.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by picasik** [comment]
## You don't appear to be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support. Include your 'distribution package' name: rfremix-release-23-3.R.noarch.

**Comment by igsu** [comment]
Node.js v6 went EOL, closing this now.
