### ISSUE TITLE
Support for Node 6 on Vivid 15.04

### ISSUE THREAD

**Issue by MauJFernandezUVR** [nodesource/distributions#347]
Running `curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -` returns

```
## Confirming "vivid" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/vivid/Release'

## Your distribution, identified as "vivid", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

The URL returns a 404, but [https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) states

```
Supported Ubuntu versions:

Ubuntu 12.04 LTS (Precise Pangolin)
Ubuntu 14.04 LTS (Trusty Tahr)
Ubuntu 15.04 (Vivid Vervet)
```

**Comment by mweagle** [comment]
Thanks for filing @MauJFernandezUVR. We're currently heads down working to get the new 4.5/6.5LTS builds out the door and will investigate this as soon as possible.

**Comment by mweagle** [comment]
Hi @MauJFernandezUVR - this was a documentation error that was addressed by https://github.com/nodejs/nodejs.org/pull/883 - apologies for the outdated information. We now support `Ubuntu 16.04 (Xenial Xerus)` rather than `Ubuntu 15.04 (Vivid Vervet)`.

**Comment by MauJFernandezUVR** [comment]
Hi @mweagle, sorry for the delay, I forgot about this one.

Thanks for the update.
