### ISSUE TITLE
Raspberry Pi 3 + Centos 7.2 not supported

### ISSUE THREAD

**Issue by Alvaroctal** [nodesource/distributions#350]
Hi, got the following error trying to install node on my raspberry pi 3 running CentOS 7.2 (armv7).

> \#\# You don't appear to be running a supported machine architecture: armv7l. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support. 

So tutorials says that there is no big difference between `armv7` and `armv6` (however, everyone seems to be forgetting `aarch64/armv8`) performance, anyway, I guess it can be done easily.

thanks in advance.

**Comment by chrislea** [comment]
We only support `armhf` on newer Debian and Ubuntu distributions I'm afraid. For CentOS 7 / RHEL 7 we only support the `x86_64` architecture. You should be able to use the official release tarballs for `armhf` however.
