### ISSUE TITLE
Install instructions Error on Debian (Node.js v6.x:)

### ISSUE THREAD

**Issue by BenRoe** [nodesource/distributions#351]
Hi,
if i use the install command for on Debian for Node.js v6.x i get an error (unfortunately german).
`curl -sL https://deb.nodesource.com/setup_6.x | bash -`

```
sudo curl -sL https://deb.nodesource.com/setup_6.x | bash -

## Installing the NodeSource Node.js v6.x repo...


## Populating apt-get cache...

+ apt-get update
E: Sperrdatei /var/lib/apt/lists/lock konnte nicht geöffnet werden. - open (13: Keine Berechtigung)
E: Das Verzeichnis /var/lib/apt/lists/ kann nicht gesperrt werden.
E: Sperrdatei /var/lib/dpkg/lock konnte nicht geöffnet werden. - open (13: Keine Berechtigung)
E: Sperren des Administrationsverzeichnisses (/var/lib/dpkg/) nicht möglich, sind Sie root?
Error executing command, exiting
```
If i use the Ubuntu command everything is working.
`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -`

**Comment by retrohacker** [comment]
Hey @BenRoe,

apt didn't have write access to `/var/lib/apt/lists/lock`

You are running `sudo` for curl but not bash

`curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -` s should fix this
