### ISSUE TITLE
ipv6 problem

### ISSUE THREAD

**Issue by ditsikts** [nodesource/distributions#352]
ubuntu try to update using ipv6, this has result the command "curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -" to stack. Into the script replace 'apt-get update' with 'apt-get update -o Acquire::ForceIPv4=true' to force using ipv4 and update run smoothly

**Comment by jhonmike** [comment]
a good tip is to leave the ipv6 less preferably using the following command:
`sudo sh -c 'echo' precedence :: ffff: 0: 0/96 100 '>> /etc/gai.conf "`

**Comment by igsu** [comment]
Closing this now
