### ISSUE TITLE
Failed to validate the SSL certificate for deb.nodesource.com:443

### ISSUE THREAD

**Issue by mfergus1** [nodesource/distributions#355]
Hi there! Seeing an issue with certificate validation pop up in the last few days. 
"Failed to validate the SSL certificate for deb.nodesource.com:443"

**Comment by chrislea** [comment]
Hi. We recently started serving our repositories from Amazon CloudFront which requires SNI. Please reference https://github.com/nodesource/ansible-nodejs-role/issues/33 as it may be related.

**Comment by mfergus1** [comment]
Thanks!
