### ISSUE TITLE
Trying to install older (0.10.x) version results in 4.2.6 being installed

### ISSUE THREAD

**Issue by ccuilla** [nodesource/distributions#360]
Running (on Ubuntu 16.04.1):

```
curl -sL https://deb.nodesource.com/setup_0.10 | sudo -E bash -
sudo apt-get install -y nodejs
```

Actually results in 4.2.6 being installed.

apt-cache policy nodejs shows:

```
nodejs:
  Installed: 4.2.6~dfsg-1ubuntu4.1
  Candidate: 4.2.6~dfsg-1ubuntu4.1
  Version table:
 *** 4.2.6~dfsg-1ubuntu4.1 500
        500 http://mirrors.digitalocean.com/ubuntu xenial-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     4.2.6~dfsg-1ubuntu4 500
        500 http://mirrors.digitalocean.com/ubuntu xenial/universe amd64 Packages
     0.10.46-1nodesource1~xenial1 500
        500 https://deb.nodesource.com/node_0.10 xenial/main amd64 Packages
```

**Comment by chrislea** [comment]
That's because 16.04 ships with 4.2.6 in the primary Ubuntu repos so your system sees that as being "newest" and installs it. The only way around this would be to a) uninstall 4.2.6 and the associated `npm` installation and then install the `deb` package from our repository manually.

**Comment by ccuilla** [comment]
Thanks for quick reply Chris.

**Comment by chrislea** [comment]
I should probably point out also that 0.10.x is EOL on Oct 1st of this year, meaning less than two weeks from today. So you should *really* not be trying to install it anymore.

**Comment by ccuilla** [comment]
Yeah. I know. I'm kind of stuck on a Meteor 1.3.x application at the moment.
