### ISSUE TITLE
Nodejs support for Fedora25-alpha release

### ISSUE THREAD

**Issue by Thirumalesh-HS** [nodesource/distributions#362]
Hi folks,

I am trying to install nodejs on my laptop[ fedora25-alpa release 64bit] via package tools by running following command as root

`curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -`

And i am getting the following report,

Your distribution, identified as "fedora-release-25-0.11.noarch", is not currently supported.

Can someone please tell me how to install on the latest release-"fedora-release-25-0.11.noarch"

**Comment by chrislea** [comment]
We don't support Fedora releases in the alpha or beta stages. You may be able to install the FC24 package which you can download here:
```
https://rpm.nodesource.com/pub_4.x/fc/24/x86_64/
```
or just install from the official tarballs available from https://nodejs.org.
