### ISSUE TITLE
Your distribution, identified as "jessie", is not currently supported

### ISSUE THREAD

**Issue by espenronnevik** [nodesource/distributions#363]
Attempted to use setup_6.x script to install nodejs but script failed with message saying the distribution is not supported. Upgraded all packages to the latest versions, but error message remained.

Script runs `wget -qO /dev/null -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/jessie/Release'` to check for support and just attempting to run the wget command by itself gave the following output:

--2016-09-25 16:54:34--  https://deb.nodesource.com/node_6.x/dists/jessie/Release
Resolving deb.nodesource.com (deb.nodesource.com)... 54.192.98.26, 54.192.98.102, 54.192.98.19, ...
Connecting to deb.nodesource.com (deb.nodesource.com)|54.192.98.26|:443... connected.
ERROR: The certificate of 'deb.nodesource.com' is not trusted.
ERROR: The certificate of 'deb.nodesource.com' hasn't got a known issuer.

Adding the repository manually, using `deb https://deb.nodesource.com/node_6.x jessie main`  makes apt-get throw an error and failing to download index, replacing https with http works fine. 

This could be related to issue #260

**Comment by chrislea** [comment]
If your system isn't recognizing the SSL certificate then I wouldn't expect things to work. I would make sure that all the packages in your system, particularly `ca-certificates`, are up to date. Can you make sure that's the case and let us know what the results are?

**Comment by espenronnevik** [comment]
Yes, just did some additional checking and discovered that ca-certificates was not installed on the system, which obviously explains the error messages. Installing curl also pulled it in manually, which the script skipped as wget was already available. Maybe `ca-certificates` should be included in the PRE_INSTALL_PKGS variable? Something like:

>if [ ! -x /usr/sbin/update-ca-certificates ]; then
>    PRE_INSTALL_PKGS="${PRE_INSTALL_PKGS} ca-certificates"
>fi

Or ignore the check for wget and install curl, since that seems to pull in the package as well.

**Comment by chrislea** [comment]
Good idea, we'll look into adding that. Thanks!
