### ISSUE TITLE
GPG key for RPM packages

### ISSUE THREAD

**Issue by jtyr** [nodesource/distributions#366]
I can see that the RPM packages are signed with GPG key ID 5ddbe8d434fa74dd but I can not find the key anywhere. Please could you provide the GPG key on the web as you did for [DEB packages](https://deb.nodesource.com/gpgkey/nodesource.gpg.key)?

**Comment by chrislea** [comment]
It _should_ be available from the standard keyservers. If it's not for some reason, you can grab a [release rpm](https://rpm.nodesource.com/pub_6.x/fc/24/x86_64/nodesource-release-fc24-1.noarch.rpm) and unpack it to get the key with something like:
```
rpm2cpio nodesource-release-fc24-1.noarch.rpm | cpio -ivd
```
and it will be one of the files that gets unpacked.

**Comment by jtyr** [comment]
Users shouldn't need to get the GPG key from a key server or extract it from RPM. The key should be available for download from your page in the same way [as it's](https://deb.nodesource.com/gpgkey/nodesource.gpg.key) for the Debian packages.

Please expose the GPG key on your web in order users can freely download it without any additional complications.

**Comment by n3ph** [comment]
BUMP

**Comment by n3ph** [comment]
Request to reopen..

I really do not understand why the GPG signing key is not published in the same way as the GPG signing key for Debian packages already is..

Please define "standard keyservers" - I didn't find it anywhere - Even not on the [Ubuntu kerservers
](http://keyserver.ubuntu.com:11371/pks/lookup?search=5ddbe8d434fa74dd&fingerprint=on&hash=on&op=vindex)

And please explain your decision to close this request without any further actions..

--------

**Current Situation:**
The installation method for nodejs under RHEL is horrible. [Curling a bash script and pipe it to a root shell](https://github.com/nodesource/distributions/blob/master/README.md#rpminstall)... Seriously? Disgusting! 

**Requirement:**
We use Configuration Management to provision repository configurations. As we need to provide a GPG Key for the yum repository configuration we need to grab it from at least somewhere.

**Definition of Done:**
Host the GPG signing key for RPM packages the same way you are doing it for DEB packages.

Debian: [https://deb.nodesource.com/gpgkey/nodesource.gpg.key](https://deb.nodesource.com/gpgkey/nodesource.gpg.key)
RHEL (proposed): [https://rpm.nodesource.com/gpgkey/nodesource.gpg.key](https://rpm.nodesource.com/gpgkey/nodesource.gpg.key)

**Comment by mettacrawler** [comment]
> Please define "standard keyservers" - I didn't find it anywhere - Even not on the [Ubuntu keyservers ](http://keyserver.ubuntu.com:11371/pks/lookup?search=5ddbe8d434fa74dd&fingerprint=on&hash=on&op=vindex)

```
gpg --keyserver ha.pool.sks-keyservers.net --recv-key 5ddbe8d434fa74dd
gpg: key 5DDBE8D434FA74DD: public key "NodeSource <gpg-rpm@nodesource.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```
