### ISSUE TITLE
Node Installation on ubuntu 16.04

### ISSUE THREAD

**Issue by pptyasar** [nodesource/distributions#377]
When installing nodejs i got this error

Get:1 https://deb.nodesource.com/node_6.x xenial/main i386 nodejs i386 6.9.1-1nodesource1~xenial1 [9,771 kB]
Err:1 https://deb.nodesource.com/node_6.x xenial/main i386 nodejs i386 6.9.1-1nodesource1~xenial1

GnuTLS recv error (-54): Error in the pull function.
E: Failed to fetch https://deb.nodesource.com/node_6.x/pool/main/n/nodejs/nodejs_6.9.1-1nodesource1~xenial1_i386.deb GnuTLS recv error (-54): Error in the pull function.

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by chrislea** [comment]
It looks like a network connectivity error. Are you behind any kind of proxy? Also, can you pull down any of the `.deb` files directly using something like `curl`?

**Comment by develth** [comment]
Seems like there is an issue today, again:

When i try to Download 
`https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/nodejs_12.19.1-1nodesource1_amd64.deb`

There is an Error `Decryption has failed.`
Download in FF Results in `Can´t read the source file`
