### ISSUE TITLE
Node Installation failed on ubuntu 17.04

### ISSUE THREAD

**Issue by earlymeme** [nodesource/distributions#378]
I run `curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -`.It returnes as follow:
```
Your distribution, identified as "Ubuntu Zesty Zapus (development branch)", 
is a pre-release version of Ubuntu. 
NodeSource does not maintain official support for 
Ubuntu versions until they are formally released. 
You can try using the manual installation instructions available at https://github.com/nodesource/distributions 
and use the latest supported Ubuntu version name as the distribution identifier,
although this is not guaranteed to work.
```

**Comment by chrislea** [comment]
We don't support pre-release versions of Ubuntu, so Zesty is not supported currently. When 17.04 is released, we will support it at that time.

**Comment by peter-umb** [comment]
I am also getting this error. Am I reading this wrong?

From https://github.com/nodesource/distributions

NodeSource will maintain Ubuntu distributions in active support by Canonical, including LTS and the intermediate releases.

Ubuntu 14.04 LTS (Trusty Tahr)
Ubuntu 16.04 LTS (Xenial Xerus)
Ubuntu 16.10 (Yakkety Yak)
**Ubuntu 17.04 (Zesty Zappus)
Ubuntu 17.10 (Artful Aardvark)**
