### ISSUE TITLE
Setup installs End-Of-Life version of Node.js

### ISSUE THREAD

**Issue by OneLogicalMyth** [nodesource/distributions#379]
If you do the standard setup option which is to use;

`curl -sL https://deb.nodesource.com/setup | bash -`

This installs the the release version of Node.js v0.10.
Which as per https://github.com/nodejs/LTS is now EOL.

You might find less technical people are getting confused or even installing an EOL version of Node.js as a result.

**Comment by Daniel15** [comment]
Where do you see this mentioned? The only time we mention the NodeSource repo in the documentation, we mention the 6.x repo.

**Comment by Daniel15** [comment]
Doesn't it give a giant deprecation warning if you try to install Node.js 0.10?

I do agree that the default should be changed to Node.js 6 though!

**Comment by mgol** [comment]
@igsu any reason why this was closed?

**Comment by igsu** [comment]
@mgol `https://deb.nodesource.com/setup` script is deprecated and showing proper EOL warnings. Additionally, the documentation is up-to-date and there are scripts to install the `current` and `lts` versions. This issue is obsolete.

**Comment by mgol** [comment]
OK, thanks for the explanation!
