### ISSUE TITLE
Hash sum mismatch

### ISSUE THREAD

**Issue by olegsa** [nodesource/distributions#381]
Steps to reproduce the issue:
**Running apt-get update**
Describe the results you received:
Running 

> apt-get update

 on Debian Stretch just now results in

W: Failed to fetch https://deb.nodesource.com/node_6.x/dists/precise/main/source/Sources  Hash Sum mismatch

W: Failed to fetch https://deb.nodesource.com/node_6.x/dists/precise/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch https://deb.nodesource.com/node_6.x/dists/precise/main/binary-i386/Packages  Hash Sum mismatch

**Comment by chrislea** [comment]
I can't see that there's actually any mismatch. Are you behind any sort of network proxy? If not, can you try again and see if this is still happening?
