### ISSUE TITLE
npm fails during 6.9.1 installation

### ISSUE THREAD

**Issue by ckehoe** [nodesource/distributions#383]
Version: 6.9.1
Platform: Centos 7.2

When installing the latest LTS version of node on a fresh Centos 7.2 installation the bundled version of npm 3.10.8 fails to install. Manually installing npm 3.10.9 fixes the issue. Also as a secondary issue node isn't honoring the 4.x url and installing the latest version of the LTS.

**Error:**
Running transaction
  Installing : 1:npm-3.10.8-1.6.9.1.1.el7.x86_64                                                                                                                               1/2 
Error unpacking rpm package 1:npm-3.10.8-1.6.9.1.1.el7.x86_64
error: unpacking of archive failed on file /usr/lib/node_modules/npm/doc: cpio: rename
  Installing : 1:nodejs-6.9.1-1.el7.x86_64                                                                                                                                     2/2 
error: npm-1:3.10.8-1.6.9.1.1.el7.x86_64: install failed
  Verifying  : 1:nodejs-6.9.1-1.el7.x86_64                                                                                                                                     1/2 
  Verifying  : 1:npm-3.10.8-1.6.9.1.1.el7.x86_64

**Steps to Reproduce:**
curl --silent --location https://rpm.nodesource.com/setup_4.x | bash - && yum -y install nodejs

**Workaround**
``
yum remove -y npm
``
``
curl -L https://www.npmjs.com/install.sh | sh
``

**Comment by chrislea** [comment]
It looks like there was some attempt to install an `npm` package along with our `nodejs` package. You should not do this. Our `nodejs` package bundles `npm` with it, so there is no need for a separate package, which looks like it was causing trouble.

**Comment by ckehoe** [comment]
So i'm simply trying to install node and during the installation the version of npm that is bundled with the 6.9.1 package - which appears to be 3.10.8 - fails to install with the output I listed above in the error section. Running npm commands throw the following error after the failed installation:

[root@dev-machine]# npm --version
module.js:471
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:19:13
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:75:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

The workaround that allowed me to use npm again was to remove the npm version installed with the nodejs package and install npm separately since the version in the 6.9.1 node.js bundle is failing to install correctly and needs to be fixed.

**Comment by chrislea** [comment]
Ah, wait, I see the problem. You're installing the package `nodejs-6.9.1-1.el7.x86` which is not the one we produce. It's coming from some other repository you're subscribed to. Ours would be called `nodejs-6.9.1-1nodesource.el7`, ref [here](https://rpm.nodesource.com/pub_6.x/el/7/x86_64/).

**Comment by ckehoe** [comment]
okay thanks! I was pointed here by the node.js team. Any suggestions where I should file the issue?

**Comment by chrislea** [comment]
I'm not sure there's an issue to file. Whatever other repository you're using may have a bad `npm-3.10.8` package but as there's a newer one that works, you should be able to just install that. Or, get rid of the other repository and just use ours (which just has the single `nodejs` package for everything). The crux of the problem you're seeing is that you are on two different repos that both have a nodejs 6.9.1 package, which is not what you want.

**Comment by nugai** [comment]
Thanks, guys! I had the same problem and was able to fix it thanks to the information in this thread.

I would have never figured out by myself that there could be different rpms for nodejs (and that they could be inconsistent, if not conflicting).
