### ISSUE TITLE
installing node on older OS versions

### ISSUE THREAD

**Issue by EvaLok** [nodesource/distributions#385]
i wanted to install node on an older OS (centOS 6) and found this page:
https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md

..which is a whole lot of work, and in my case, installing the recommended packages was proving tedious because they themselves had dependency issues. something that is a whole lot easier is to simply use `n` - i tried that and got node v6 up really fast without any hassle of searching around for dependencies. if this knowledge tidbit is deemed worthy, i'd be happy to update the docs.. 

```bash  
# centos 6 / WHM
wget http://nodejs.org/dist/v0.10.4/node-v0.10.4.tar.gz
cd node-v0.10.4.tar.gz 
tar zxf node-v0.10.4.tar.gz 
cd node-v0.10.4
./configure
make
make install
npm install -g n
n lts
node #outputs: v6.9.1
```

**Comment by zhangzlili** [comment]
This works very well.
