### ISSUE TITLE
Unable install Nodejs v6 on Centos 6.4 

### ISSUE THREAD

**Issue by kienbui1995** [nodesource/distributions#387]
"Your distribution, identified as "centos-release-6-4.el6.centos.10.i686", is not currently supported"

**Comment by dasime** [comment]
`i686` is a 32 bit architecture.

 According to the [`README`](https://github.com/nodesource/distributions/blob/master/README.md#rpm) 32 bit CentOS 6 is only supported for versions of Node before Node 4.

>CentOS 6 (32-bit and 64-bit) [For Node < 4.x]
>CentOS 6 (64-bit) [For Node >= 4.x]

So this is working as intended.

**Comment by chrislea** [comment]
@dasime is correct. Unfortunately we can't support 32bit CentOS6 on newer versions of Node.js.
