### ISSUE TITLE
Unable to install 6.x on Ubuntu.

### ISSUE THREAD

**Issue by fdearle** [nodesource/distributions#389]
Hi,

As of this morning. 16th Nov 2016 we are getting a failure when we try to install 6.x on ubuntu.

Our installation scripts use the following:

curl --silent --location https://deb.nodesource.com/setup_6.x | sudo bash -

I've also tried the recommended curl

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

Both give the same error.

The handshake failure is on https://deb.nodesource.com/node_6.x/dists/trusty/main/source/Sources

Which is actually a 404, whereas there is a https://deb.nodesource.com/node_6.x/dists/trusty/main/source/Sources.gz

Note. That this exact script worked fine in all previous attempts. Up to and including 24 hours ago. The script is run as part of our spin up each morning for AWS staging and development environments but it is also part of our production spinup script that would execute if we get an auto scaling event.

Naturally I'm a bit worried right now that our production environment is vulnerable.

This is what is logged out by the curl command:

Get:5 http://security.ubuntu.com trusty-security/universe amd64 Packages [142 kB]
Hit http://security.ubuntu.com trusty-security/main Translation-en            
Ign https://deb.nodesource.com trusty Release.gpg
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Ign https://deb.nodesource.com trusty Release                       
Err https://deb.nodesource.com trusty/main Sources   
  gnutls_handshake() failed: Handshake failed
Err https://deb.nodesource.com trusty/main amd64 Packages
  gnutls_handshake() failed: Handshake failed
Ign https://deb.nodesource.com trusty/main Translation-en_US
Ign https://deb.nodesource.com trusty/main Translation-en
Fetched 920 kB in 3s (267 kB/s)
W: Failed to fetch https://deb.nodesource.com/node_6.x/dists/trusty/main/source/Sources  gnutls_handshake() failed: Handshake failed

W: Failed to fetch https://deb.nodesource.com/node_6.x/dists/trusty/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by mcfedr** [comment]
Same issue as https://github.com/nodesource/distributions/issues/388
