### ISSUE TITLE
Linux Mint 17.3 Unsupported?

### ISSUE THREAD

**Issue by xElendiLx** [nodesource/distributions#390]
Hi, first of all I'm new to nodejs and when I install it from official repo, It installs an outdated version of nodejs(v0.10.25) so I decided to install it manually or at least by .deb file... My research lead me here and when I try to install nodejs v6.x, it gives me this error:

```
## You seem to be using Linux Mint version rosa.
## This maps to Ubuntu "trusty"... Adjusting for you...

## Confirming "trusty" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/trusty/Release'

## Your distribution, identified as "trusty", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

```

I don't understand what is wrong, because when I check the list of supported Ubuntu versions there is Ubuntu 14.04 LTS(Trusty Tahr) which is Linux Mint 17.3 Rosa based on. But when I check the list of supported Linux Mint versions, 17.3 isn't there, why?

**Comment by chrislea** [comment]
Trusty should be supported. Are you behind any kind of network proxy? Also, can you get to this URL:
```
https://deb.nodesource.com/node_6.x/dists/trusty/Release
```
from the machine you are trying to install Node onto?

**Comment by xElendiLx** [comment]
No, I'm not behind any proxy network. Thanks, but i solved the problem by inserting manually trusty repos to source list... Thank you again...
