### ISSUE TITLE
xenial is not currently supported

### ISSUE THREAD

**Issue by yupengfei** [nodesource/distributions#392]
## Your distribution, identified as "xenial", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

my command is 

curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -

**Comment by rvagg** [comment]
@yupengfei xenial is supported for v7, perhaps this is getting caught up behind a proxy server that's not being propagated via environment variables (the `-E` is intended to pass down `http_proxy` and other environment variables that are required to call out). Do you know if you're behind a proxy server that may prevent it from connecting and verifying?

**Comment by yupengfei** [comment]
@rvagg sorry, I did not notice that, after turn off the proxy, it works now.
