### ISSUE TITLE
Fedora 25 install Node.js not support

### ISSUE THREAD

**Issue by rookiefly** [nodesource/distributions#393]
+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_6.x/fc/25/x86_64/nodesource-release-fc25-1.noarch.rpm'

## Your distribution, identified as "fedora-release-25-1.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
Node 6.9.1, which is currently the newest in the 6.x line, is already included in the standard FC25 distribution. As soon as there is a newer version of 6.x released, we'll build that for FC25 and it will be available via our installer at that time.
