### ISSUE TITLE
## Your distribution, identified as "Metamorphosis"

### ISSUE THREAD

**Issue by xricson** [nodesource/distributions#394]
## Your distribution, identified as "Metamorphosis", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by xricson** [comment]
trump@mx1:~
$ cat /etc/issue
Добро пожаловать в MX 16-RC1 (Metamorphosis) 64-bit! Работает на Debian.
But>2Headers in My Distros=> 1) linux-headers-4.7.0-0.bpo.1-ar 4.7.8-1mx16+1 and 2) linux-image-4.8.0-10.1-liquori: 4.8-14mx150+1 (191MB) for 64-bit PCs
And I will be installed texteditor Atom, after - electron (this packet in HOME status building), and others packets compiling on mac-img fs (!)

**Comment by pjockey** [comment]
Get the same, but the previous release, known as "Fusion".  Both are Debian based Jessie.

**Comment by chrislea** [comment]
If it's based on Debian Jessie it should be easy enough to support. Please just create a PR against the setup scripts with the correct aliases and if it looks good we'll merge it. Thanks!
