### ISSUE TITLE
Segmentation fault on npm

### ISSUE THREAD

**Issue by rafalpetryka** [nodesource/distributions#395]
I've trying install nodejs via
```
curl -sL https://deb.nodesource.com/setup_6.x | bash -
apt-get install -y nodejs
```
but unfortunately I've got segmentation fault on npm
```
➜  ~ node -v
v4.6.2
➜  ~ npm .v
[1]    5972 segmentation fault  npm .v
➜  ~ node
[1]    18644 segmentation fault  node

```

I've tried to install multiple versions, but without any effect.
I'm using debian 8 jessie

**Comment by Alf21** [comment]
Same issue

**Comment by chrislea** [comment]
Sorry for the late reply here @rafalpetryka .

You ran the setup scripts for Node.js v6.x, but the node you have installed is Node.js v4.x based on the output of `node -v` you include. So something didn't work with the installation. I'd try removing *any* nodejs or npm related packages with `apt`, remove any `nodesource.list` files in `/etc/apt/sources.list.d`, and then try re-running the setup script.

If there's some sort of mismatch between the version of Node you have and the version you think you have, I could easily imagine that could be a problem. @Alf21 , if you're seeing the same issue, I'd look also at the version mismatch. Hope this helps.

**Comment by Alf21** [comment]
had have a broken 4.x version that was not removed with `sudo apt-get remove --purge -fy node.* npm.*`. So i needed to search for each npm file and associated node file and delete it (completely). After cleaning and manually deleting the .deb in apt's cache folder, running `apt-get install -fy nodejs` and everything works fine

**Comment by VishalDas95** [comment]
I am having the same problem except that `npm -v` show ther version but `sudo npm -v` gives a `Segmentation Fault(core dumped)` error. 
![image](https://user-images.githubusercontent.com/35860774/41910167-80ac8402-7966-11e8-9c72-3e7ca81a27df.png)
Stuck here! can't forward with the installation of Angular CLI.
