### ISSUE TITLE
Segment Violation | npm | centOS 6 

### ISSUE THREAD

**Issue by andreamald** [nodesource/distributions#397]
Hello
I have this problem with npm in Centos 6 when doing any operation with the npm I throw the error of segment violation
npm -v

Paquetes instalados
Nombre        : nodejs
Arquitectura        : i686
Versión     : 0.10.46
Lanzamiento     : 1nodesource.el6
Tamaño        : 19 M
Repositorio        : installed
Desde el repositorio   : nodesource
Resumen     : JavaScript runtime
URL         : http://nodejs.org
Licencia     : MIT and ASL 2.0 and ISC and BSD
Descripción :Node.js is a platform built on Chrome\'s JavaScript runtime
           : for easily building fast, scalable network applications.
           : Node.js uses an event-driven, non-blocking I/O model that
           : makes it lightweight and efficient, perfect for data-intensive
           : real-time applications that run across distributed devices.

Paquetes disponibles
Nombre        : npm
Arquitectura        : noarch
Versión     : 1.3.6
Lanzamiento     : 5.el6
Tamaño        : 329 k
Repositorio        : epel
Resumen     : Node.js Package Manager
URL         : http://npmjs.org/
Licencia     : Artistic 2.0
Descripción :npm is a package manager for node.js. You can use it to install and publish your
           : node programs. It manages dependencies and does other cool stuff.

**Comment by chrislea** [comment]
I'm sorry but Node.js 0.10.x went EOL on Oct 31, 2016. It is no longer supported in any way.

You should **immediately** upgrade to 4.x or 6.x, as the 0.10.x line is no longer receiving security updates.

**Comment by andreamald** [comment]
Hello
When trying to install the new version of nodejs with the following steps
Curl -sL https://rpm.nodesource.com/setup_4.x | Bash-
I get this error
## Installing the NodeSource Node.js v4.x LTS Argon repo ...


## Inspecting system ...

+ Rpm -q --whatprovides redhat-release || Rpm -q --whatprovides centos-release || Rpm -q --whatprovides cloudlinux-release || Rpm -q --whatprovides sl-release
+ Uname -m

## Confirming "el6-i386" is supported ...

+ Curl -slf -o / dev / null 'https://rpm.nodesource.com/pub_4.x/el/6/i386/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "centos-release-6-8.el6.centos.12.3.i686", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think This is incorrect or would like your distribution to be considered for suppor


I could help with this please !!!!!

**Comment by andreamald** [comment]
Is there any way to compile 4.X nodejs on 32-bit operating systems. ? Or should I give up compiling this new version of nodejs for centos 6.8

**Comment by chrislea** [comment]
It's not an issue of 32bit exactly, the issue is what compilers are available for different distributions. We don't easily have access to a 32bit compiler for CentOS 6 that can compile Node 4.x which is why we don't make those packages. If you were using a supported version of Fedora or a new-ish version of Debian or Ubuntu you could compile a 32bit Node 4.x with no trouble, and we do provide pre-built packages for those distributions.

**Comment by andreamald** [comment]
As a solution to the problem is it better to migrate from cents 6.8 to 7.?

**Comment by chrislea** [comment]
Well, there is no official 32bit CentOS 7 release. I believe there is a community supported one, but it's not supported by the official channels so we don't provide official builds for it.

That said, if you install the community supported 32bit CentOS 7 and everything is working, you should be able to compile Node 4.x on it without any issues.

**Comment by andreamald** [comment]
No, it would be a centos 7 of 64 bits with this version, should not have problems with the new versioens of nodejs like 4.X. Thank you for your support in this problem.
