### ISSUE TITLE
Support Fedora 25

### ISSUE THREAD

**Issue by sherl0cks** [nodesource/distributions#398]
Per the setup script, I'm opening this issue:

```
## Your distribution, identified as "fedora-release-25-1.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by chrislea** [comment]
We currently have the newest 7.x builds available for FC25. What command were you using that generated this message?

**Comment by sherl0cks** [comment]
I'm looking for LTS. Both of the below failed:
- curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
- curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -

**Comment by ktriponis** [comment]
@sherl0cks You could just use node from official F25 repo, just tried `dnf install nodejs` and  without any hassle got node v6.9.1 and npm v3.10.8 installed and working.

**Comment by ktriponis** [comment]
@sherl0cks Why not just install it from official repository? I've just tried to install node using `dnf install nodejs` and got myself a working **v6.9.1** node and **v3.10.8** npm. Seems like a good hassle free deal to me.

**Comment by chrislea** [comment]
Yes we don't have 4.x or 6.x built for FC25 yet because no new releases on those lines have come out since FC25 itself was release. Also, 6.9.1 is already in the official repositories for FC25. As soon as a new version of 4.x or 6.x is released, we'll build it for FC25. Hope this helps.
