### ISSUE TITLE
Unable to install Node v5 on ubuntu 16.10 amd64

### ISSUE THREAD

**Issue by walidbaccari** [nodesource/distributions#400]
'Your distribution, identified as "yakkety", is not currently supported' when trying to install Node v5.x on Ubuntu 16.10 amd64 using curl. Manual install didn't work too.

**Comment by chrislea** [comment]
Node 5.x is EOL and no longer supported in any way. You should move to 6.x **immediately**. Yakkety is currently fully supported for 6.x (and 4.x, and 7.x).

**Comment by walidbaccari** [comment]
Got it! Thanks a lot for the quick reply!
