### ISSUE TITLE
Please Provide Manual Installation Instructions

### ISSUE THREAD

**Issue by xloem** [nodesource/distributions#401]
It's very convenient to pipe a url to bash as root, but this is an indescribably insecure thing to get a user in the habit of doing.

To encourage good user practices, and for the less trusting of us, it would be great to have instructions for manually installing the repositories.  This could be as little as a url and a pgp key !

**Comment by chrislea** [comment]
We do have manual instructions.

https://github.com/nodesource/distributions/#debmanual

Though piping our script into `bash` isn't a security issue in our case.
