### ISSUE TITLE
Where does /etc/profile.d/nodejs.sh come from?

### ISSUE THREAD

**Issue by godmar** [nodesource/distributions#403]
Please forgive the question if it's off topic.

In [create-react-app issue #1023](https://github.com/facebookincubator/create-react-app/issues/1023) we spent ~~hours~~ days tracking down a bug that ultimately turned out to be caused by the deb.nodesource.com package providing an `/etc/profile.d/nodejs.sh` file that sets `NODE_PATH`

The package in question was installed via instructions contained in [here](https://deb.nodesource.com/setup_6.x), which are widely repeated on the web

```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

dpkg -S shows:
```
Maintainer: Chris Lea <chl@nodesource.com>
...
Conffiles:
 /etc/profile.d/nodejs.sh 1079bfe1307fdeead400526e9152e51f
```

Where is the correct place to file an issue regarding this potentially dangerous system-wide setting?

Issue #50 in this repository claims that support for `NODE_PATH` is discontinued and won't be brought back, but it's not clear if this refers to the conffiles.  A search for `NODE_PATH` in this repository comes up empty, so how does it make its way into the nodesource Debian package?

**Comment by chrislea** [comment]
Ah, yes, that should be removed. It used to be needed but isn't anymore. I'll make sure it gets taken out no later than whenever the next releases come out. Thanks for pointing this out.

**Comment by ageis** [comment]
Aw, I liked that file. :rofl:
