### ISSUE TITLE
Table of supported and unsupported versions of nodejs

### ISSUE THREAD

**Issue by andreamald** [nodesource/distributions#405]
Hello
A page where you can see the versions of nodejs that are not supported and those that are supported and even when they are. Anyone knows if there is any official site nodejs and some alternate site where you can access this information. 
thanks

**Comment by chrislea** [comment]
I believe you want the LTS Schedule:

https://github.com/nodejs/LTS#lts-schedule

**Comment by andreamald** [comment]
I thank you very much
