### ISSUE TITLE
Incomplete repositories throw errors that derail install script setup_4.x

### ISSUE THREAD

**Issue by iankevinmcdonald** [nodesource/distributions#406]
PROBLEM:

I'm trying to install NodeJS >= 0.11 on my Asus netbook running Linux Mint Maya (#36-Ubuntu SMP).

The default repos only provide v 0.6, but nodesource provides scripts to install new sources into your apg-get sourcelists. (See https://nodejs.org/en/download/package-manager/)

Scripts like, for example, https://deb.nodesource.com/setup_4.x (or https://github.com/nodesource/distributions/blob/master/deb/setup_4.x)

I'm installing it as a dependency for "audiogram" (an audio visualisation generator made by New Yorks public radio station); and as the first step in that process I added this to my filespace in order to get an ffmpeg package (which it didn't have for my version, but I digress).
- http://ppa.launchpad.net/mc3man/trust-media/ubuntu

Fetches to that repository 404, and this derails the script. My fix was to remove that repository (it wasn't helping anyway).

UNAME
uname -a
Linux orwell 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:41:14 UTC 2012 i686 i686 i386 GNU/Linux

OUTPUT LOG FROM SETUP_4.x
[nodesource4_B.log.txt](https://github.com/nodesource/distributions/files/654791/nodesource4_B.log.txt)

**Comment by chrislea** [comment]
Sorry but I don't think whatever you're seeing has to do with us. The error that you're seeing is:
```
Failed to fetch http://ppa.launchpad.net/mc3man/trust-media/ubuntu/dists/precise/main/source/Sources
```
which isn't our repository.

**Comment by iankevinmcdonald** [comment]
Chris, I know it's not your repository.

The "issue" is that I think the missing file in the repository should be a "warning", not a fatal error.

(Unless there's a reason that it needs to be a fatal error that I've missed.)

**Comment by chrislea** [comment]
I still don't understand. We don't have any control over how `apt` works, so I don't think there is anything related to your situation that we can fix. If I'm wrong please let us know.

**Comment by iankevinmcdonald** [comment]
I don't know enough to know whether that behaviour by `apt ` was entirely intrinsic to `apt `, or something that related to how setup_4.x called it.  I'm inferring from your reply that it's entirely intrinsic and out of scope.

I file bugs in the hope of supplying helpful information, but I realise with complex systems I don't understand they sometimes go to the wrong place. The fault probably lies in me using an earlier Ubuntu than the installation guide was meant for.
