### ISSUE TITLE
No Trisquel 8 support.

### ISSUE THREAD

**Issue by ryanpcmcquen** [nodesource/distributions#409]
Trisquel 8 (`flidas`) is not supported by any of the setup scripts.

**Comment by ryanpcmcquen** [comment]
https://github.com/nodesource/distributions/pull/408 closes this.

**Comment by ryanpcmcquen** [comment]
Hello, is anyone maintaining this repo?

**Comment by chrislea** [comment]
Really sorry about that, I somehow missed your PR from before. It's all been updated and should be working now.
