### ISSUE TITLE
RHEL 7.3 installation fails (using official nodesource repo)

### ISSUE THREAD

**Issue by typekpb** [nodesource/distributions#410]
trying to install nodejs on RHEL 7.3 based on instructions present in: https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora

(I tried `curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -` as well as `curl --silent --location https://rpm.nodesource.com/setup_7.x | sudo bash -`), however none of these worked for me.

Once running:

    yum clean all && yum check-update 

I get:
 
    nodesource     | 2.5 kB  00:00:00     
	Not using downloaded repomd.xml because it is older than what we have:
	  Current   : Wed Dec  7 01:18:11 2016
	  Downloaded: Tue Dec  6 23:16:52 2016

	...

	https://rpm.nodesource.com/pub_6.x/el/7/x86_64/repodata/5955d51e8a46510dedc6d9e1331ddcb2d5498c31-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
	Trying other mirror.

	 One of the configured repositories failed (Node.js Packages for Enterprise Linux 7 - x86_64),
	 and yum doesn't have enough cached data to continue. At this point the only
	 safe thing yum can do is fail. There are a few ways to work "fix" this:

	     1. Contact the upstream for the repository and get them to fix the problem.

	     2. Reconfigure the baseurl/etc. for the repository, to point to a working
		upstream. This is most often useful if you are using a newer
		distribution release than is supported by the repository (and the
		packages for the previous distribution release still work).

	     3. Run the command with the repository temporarily disabled
		    yum --disablerepo=nodesource ...

	     4. Disable the repository permanently, so yum won't use it by default. Yum
		will then just ignore the repository until you permanently enable it
		again or use --enablerepo for temporary usage:

		    yum-config-manager --disable nodesource
		or
		    subscription-manager repos --disable=nodesource

	     5. Configure the failing repository to be skipped, if it is unavailable.
		Note that yum will try to contact the repo. when it runs most commands,
		so will have to try and fail each time (and thus. yum will be be much
		slower). If it is a very temporary problem though, this is often a nice
		compromise:

		    yum-config-manager --save --setopt=nodesource.skip_if_unavailable=true

	failure: repodata/5955d51e8a46510dedc6d9e1331ddcb2d5498c31-primary.sqlite.bz2 from nodesource: [Errno 256] No more mirrors to try.
	https://rpm.nodesource.com/pub_6.x/el/7/x86_64/repodata/5955d51e8a46510dedc6d9e1331ddcb2d5498c31-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found

**Comment by typekpb** [comment]
well, after some struggling it seems to be working fine for me.

I've noticed I had nodesource repo in the `/etc/yum.repos.d/` twice, once as: `/etc/yum.repos.d/nodesource-el7.repo`, and once as: `/etc/yum.repos.d/nodesource-el.repo`, so kept one of them only.

Afterwards I ran:

    sudo yum remove nodesource
    sudo yum remove nodesource-source
    sudo yum clean all && sudo yum check-update
 
once finished I just followed the official instructions and was able to install 7.3.0 version.

**Comment by denizdogan** [comment]
I had a completely different problem, but in case someone else finds this comment hopefully it will help.

I use Vagrant and I was passing my entire environment (`ENV`) to the provisioning script which runs the `curl` command to add NodeSource. Some of these environment variables confused the script into thinking it was being executed on a non-EL system, causing it to silently fail and not add NodeSource at all.
