### ISSUE TITLE
Need support for Ubuntu 12.04

### ISSUE THREAD

**Issue by harry-achsan** [nodesource/distributions#412]
I have installed Node.js in my Ubuntu 12.04. Unfortunately the default version of node.js was 0.6.x. After reinstall for many times, I realized that my OS is not supported any longer, the message was:
_## Your distribution, identified as "precise", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support_ 

**I have no option to upgrade my OS to a newer one.** So, could you please help me to solve my problem?

**Comment by chrislea** [comment]
Ubuntu Precise is currently supported for Node versions 4.x and 6.x. Precise will not be supported for Node 7.x and higher. You can see how to install the supported versions from our [distributions page](https://github.com/nodesource/distributions/). Hope this helps.
