### ISSUE TITLE
Power Drain

### ISSUE THREAD

**Issue by sag007** [nodesource/distributions#414]
Hey Sam,

One issue I noticed this morning is that an additional 4 signs had dropped offline. I think the issue will be because of the constant polling of the signs and therefore the batteries in the remote signs have been drained to far for the Edison to remain powered and therefore drop their connection to the network.

This issue was noticed during the development of my wireless, solar powered accident alarm. The solution in the accident alarm was to reduce the polling from every second to every 5-10 seconds as the polling's primary purpose was to ensure the sign was still active and online. Then have the remote device send a command to let the server know its state has changed, ie the sign has been put up, then the server responds with an ACK so the device knows the message was received.

Nathan

**Comment by chrislea** [comment]
I think this is an issue for some other project. Nobody named Sam works on this one.
