### ISSUE TITLE
Install without script?

### ISSUE THREAD

**Issue by WillemMali** [nodesource/distributions#417]
Do you just have a signature and a repo I can add? I'm on Debian Testing x64 and I don't want to have to read through 300 line Bash script, I don't even have Bash installed. Otherwise it's easier for me to build and install NodeJS from source.

**Comment by Centuriondan** [comment]
It's bad practise to encourage users to just blindly run random scripts as root!  

Why not just publish the instructions to set up the 3rd part repository??

**Comment by rvagg** [comment]
See https://github.com/nodesource/distributions#debmanual if you don't want to run the automated script. The README has all the answers.
