### ISSUE TITLE
Deepin

### ISSUE THREAD

**Issue by ggondim** [nodesource/distributions#418]
I was thinking to start this issue with asking for a Deepin distro support, but, I hacked the `VERSION` variable (when trying to manually install nodejs, following the README steps) and I have discovered the `trusty` release of Ubuntu is fully compatible with Deepin.

I think this is enough for a nodejs support for Deepin distro. How can I add this distro to nodejs list and/or even conttribute with this release?

**Comment by sergioMG25** [comment]
Please support to Deepin

**Comment by rontav** [comment]
Thanks for the hack. You saved me a lot of time

**Comment by ShazXVII** [comment]
How would I go about doing this? I need nodejs 7.x for a project, but seeing that I'm running Deepin I can't get install the latest version :/

**Comment by rontav** [comment]
@ShazXVII I can't remember very well, but I think you should edit /etc/lsb-release (try changing DISTRIB_CODENAME from unstable to trusty). If that doesn't work, download the [node install](https://deb.nodesource.com/setup_7.x) script and modify it to skip the distro validation.

**Comment by ShazXVII** [comment]
@rontav The first solution didn't seem to work, but it's all good because I figured I might as well just run it off my Ubuntu server :)

**Comment by diegolameira** [comment]
Just to know.

Download the bash file, ex.: deb.nodesource.com/setup_8.x 

Look for check_alt list and include these line:
check_alt "deepin"        "unstable" "Ubuntu" "xenial"

then do:
$ bash file.sh

**Comment by chrislea** [comment]
@diegolameira if you can make a PR against the setup script(s) with that alias added, we can merge it in for support.

**Comment by diegolameira** [comment]
did it, #515

**Comment by igsu** [comment]
We've added support for Deepin, closing this now.
