### ISSUE TITLE
Allow rsync protocol to made local mirror

### ISSUE THREAD

**Issue by kapouik** [nodesource/distributions#419]
Hi,

I use the RPM from nodesource but today it's very difficult for me to deploy them correctly. As my servers don't have any internet access (and will never have it), I use to made a local mirror of all repo I use. 

Is it possible to have an rsync connector for rpm.nodesource.com (and why not deb.nodesource.com too) ?

**Comment by chrislea** [comment]
The repositories are served from the AWS CloudFront. Unfortunately CloudFront only speaks HTTP(S), so we can't implement `rsync`. If that changes in the future we'll look into implementing it.
