### ISSUE TITLE
install fails due to missing Release file

### ISSUE THREAD

**Issue by cdaringe** [nodesource/distributions#420]
# problem statement

- install fails :(

# discussion

on a fresh ubuntu 16.04 box from Digitial Ocean,
```
# curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -

## Installing the NodeSource Node.js v7.x repo...


## Populating apt-get cache...

+ apt-get update
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 https://apt.dockerproject.org/repo ubuntu-xenial InRelease
Hit:3 https://deb.nodesource.com/node_6.x xenial InRelease
Ign:5 https://deb.nodesource.com/node_7.4.0 xenial InRelease
Hit:6 https://deb.nodesource.com/node_7.x xenial InRelease
Hit:4 http://sfo1.mirrors.digitalocean.com/ubuntu xenial InRelease
Ign:8 https://deb.nodesource.com/node_7.4.0 xenial Release
Hit:7 http://sfo1.mirrors.digitalocean.com/ubuntu xenial-updates InRelease
Ign:9 https://deb.nodesource.com/node_7.4.0 xenial/main Sources
Ign:10 https://deb.nodesource.com/node_7.4.0 xenial/main amd64 Packages
Ign:11 https://deb.nodesource.com/node_7.4.0 xenial/main all Packages
Hit:12 http://sfo1.mirrors.digitalocean.com/ubuntu xenial-backports InRelease
Ign:13 https://deb.nodesource.com/node_7.4.0 xenial/main Translation-en_US
Ign:14 https://deb.nodesource.com/node_7.4.0 xenial/main Translation-en
Ign:9 https://deb.nodesource.com/node_7.4.0 xenial/main Sources
Ign:10 https://deb.nodesource.com/node_7.4.0 xenial/main amd64 Packages
Ign:11 https://deb.nodesource.com/node_7.4.0 xenial/main all Packages
Ign:13 https://deb.nodesource.com/node_7.4.0 xenial/main Translation-en_US
Ign:14 https://deb.nodesource.com/node_7.4.0 xenial/main Translation-en
Ign:9 https://deb.nodesource.com/node_7.4.0 xenial/main Sources
Ign:10 https://deb.nodesource.com/node_7.4.0 xenial/main amd64 Packages
Ign:11 https://deb.nodesource.com/node_7.4.0 xenial/main all Packages
Ign:13 https://deb.nodesource.com/node_7.4.0 xenial/main Translation-en_US
Ign:14 https://deb.nodesource.com/node_7.4.0 xenial/main Translation-en
Ign:9 https://deb.nodesource.com/node_7.4.0 xenial/main Sources
Ign:10 https://deb.nodesource.com/node_7.4.0 xenial/main amd64 Packages
Ign:11 https://deb.nodesource.com/node_7.4.0 xenial/main all Packages
Ign:13 https://deb.nodesource.com/node_7.4.0 xenial/main Translation-en_US
Ign:14 https://deb.nodesource.com/node_7.4.0 xenial/main Translation-en
Ign:9 https://deb.nodesource.com/node_7.4.0 xenial/main Sources
Ign:10 https://deb.nodesource.com/node_7.4.0 xenial/main amd64 Packages
Ign:11 https://deb.nodesource.com/node_7.4.0 xenial/main all Packages
Ign:13 https://deb.nodesource.com/node_7.4.0 xenial/main Translation-en_US
Ign:14 https://deb.nodesource.com/node_7.4.0 xenial/main Translation-en
Err:9 https://deb.nodesource.com/node_7.4.0 xenial/main Sources
  404  Not Found
Ign:10 https://deb.nodesource.com/node_7.4.0 xenial/main amd64 Packages
Ign:11 https://deb.nodesource.com/node_7.4.0 xenial/main all Packages
Ign:13 https://deb.nodesource.com/node_7.4.0 xenial/main Translation-en_US
Ign:14 https://deb.nodesource.com/node_7.4.0 xenial/main Translation-en
Fetched 102 kB in 2s (48.4 kB/s)
Reading package lists... Done
W: The repository 'https://deb.nodesource.com/node_7.4.0 xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://deb.nodesource.com/node_7.4.0/dists/xenial/main/source/Sources  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting
```

**Comment by Leon-001** [comment]
hi,
same problem for me here.
When I do:
`curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -E -`

I get this:
`## Installing the NodeSource Node.js v8.x repo...

## Populating apt-get cache...

+ apt-get update
OK:1 http://ppa.launchpad.net/adilson/experimental/ubuntu xenial InRelease
OK:2 http://de.archive.ubuntu.com/ubuntu xenial InRelease                                                                                                                                      
OK:3 http://de.archive.ubuntu.com/ubuntu xenial-updates InRelease                                                                                                                              
OK:4 http://ppa.launchpad.net/ubuntu-mozilla-security/ppa/ubuntu xenial InRelease                                                                                                        
OK:5 http://de.archive.ubuntu.com/ubuntu xenial-backports InRelease                                                                                            
OK:6 http://archive.canonical.com/ubuntu xenial InRelease                                                                        
OK:7 http://security.ubuntu.com/ubuntu xenial-security InRelease            
Paketlisten werden gelesen... Fertig                

## Confirming "xenial" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/xenial/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js v8.x repo...

+ echo 'deb https://deb.nodesource.com/node_8.x xenial main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_8.x xenial main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Ign:1 https://deb.nodesource.com/node_8.x xenial InRelease
Ign:2 https://deb.nodesource.com/node_8.x xenial Release                                                                                                                                       
Ign:3 https://deb.nodesource.com/node_8.x xenial/main Sources                                                                                                                                  
Ign:4 https://deb.nodesource.com/node_8.x xenial/main i386 Packages                                                                                                                            
OK:5 http://de.archive.ubuntu.com/ubuntu xenial InRelease                                                                                                   
OK:6 http://ppa.launchpad.net/adilson/experimental/ubuntu xenial InRelease                                                                                  
Ign:7 https://deb.nodesource.com/node_8.x xenial/main all Packages                                                                                                                             
OK:8 http://de.archive.ubuntu.com/ubuntu xenial-updates InRelease                                                                                                                              
Ign:9 https://deb.nodesource.com/node_8.x xenial/main Translation-de_DE                                                                                                                        
Ign:10 https://deb.nodesource.com/node_8.x xenial/main Translation-de                                                                                                                          
OK:11 http://de.archive.ubuntu.com/ubuntu xenial-backports InRelease                                                                                                                           
Ign:12 https://deb.nodesource.com/node_8.x xenial/main Translation-en                                                       
OK:13 http://ppa.launchpad.net/ubuntu-mozilla-security/ppa/ubuntu xenial InRelease                  
Ign:14 https://deb.nodesource.com/node_8.x xenial/main i386 DEP-11 Metadata                         
Ign:15 https://deb.nodesource.com/node_8.x xenial/main DEP-11 64x64 Icons   
Ign:3 https://deb.nodesource.com/node_8.x xenial/main Sources               
OK:16 http://security.ubuntu.com/ubuntu xenial-security InRelease           
Ign:4 https://deb.nodesource.com/node_8.x xenial/main i386 Packages         
OK:17 http://archive.canonical.com/ubuntu xenial InRelease
Ign:7 https://deb.nodesource.com/node_8.x xenial/main all Packages
Ign:9 https://deb.nodesource.com/node_8.x xenial/main Translation-de_DE
Ign:10 https://deb.nodesource.com/node_8.x xenial/main Translation-de
Ign:12 https://deb.nodesource.com/node_8.x xenial/main Translation-en
Ign:14 https://deb.nodesource.com/node_8.x xenial/main i386 DEP-11 Metadata
Ign:15 https://deb.nodesource.com/node_8.x xenial/main DEP-11 64x64 Icons
Ign:3 https://deb.nodesource.com/node_8.x xenial/main Sources
Ign:4 https://deb.nodesource.com/node_8.x xenial/main i386 Packages
Ign:7 https://deb.nodesource.com/node_8.x xenial/main all Packages
Ign:9 https://deb.nodesource.com/node_8.x xenial/main Translation-de_DE
Ign:10 https://deb.nodesource.com/node_8.x xenial/main Translation-de
Ign:12 https://deb.nodesource.com/node_8.x xenial/main Translation-en
Ign:14 https://deb.nodesource.com/node_8.x xenial/main i386 DEP-11 Metadata
Ign:15 https://deb.nodesource.com/node_8.x xenial/main DEP-11 64x64 Icons
Ign:3 https://deb.nodesource.com/node_8.x xenial/main Sources
Ign:4 https://deb.nodesource.com/node_8.x xenial/main i386 Packages
Ign:7 https://deb.nodesource.com/node_8.x xenial/main all Packages
Ign:9 https://deb.nodesource.com/node_8.x xenial/main Translation-de_DE
Ign:10 https://deb.nodesource.com/node_8.x xenial/main Translation-de
Ign:12 https://deb.nodesource.com/node_8.x xenial/main Translation-en
Ign:14 https://deb.nodesource.com/node_8.x xenial/main i386 DEP-11 Metadata
Ign:15 https://deb.nodesource.com/node_8.x xenial/main DEP-11 64x64 Icons
Ign:3 https://deb.nodesource.com/node_8.x xenial/main Sources
Ign:4 https://deb.nodesource.com/node_8.x xenial/main i386 Packages
Ign:7 https://deb.nodesource.com/node_8.x xenial/main all Packages
Ign:9 https://deb.nodesource.com/node_8.x xenial/main Translation-de_DE
Ign:10 https://deb.nodesource.com/node_8.x xenial/main Translation-de
Ign:12 https://deb.nodesource.com/node_8.x xenial/main Translation-en
Ign:14 https://deb.nodesource.com/node_8.x xenial/main i386 DEP-11 Metadata
Ign:15 https://deb.nodesource.com/node_8.x xenial/main DEP-11 64x64 Icons
Fehl:3 https://deb.nodesource.com/node_8.x xenial/main Sources
  
Ign:4 https://deb.nodesource.com/node_8.x xenial/main i386 Packages
Ign:7 https://deb.nodesource.com/node_8.x xenial/main all Packages
Ign:9 https://deb.nodesource.com/node_8.x xenial/main Translation-de_DE
Ign:10 https://deb.nodesource.com/node_8.x xenial/main Translation-de
Ign:12 https://deb.nodesource.com/node_8.x xenial/main Translation-en
Ign:14 https://deb.nodesource.com/node_8.x xenial/main i386 DEP-11 Metadata
Ign:15 https://deb.nodesource.com/node_8.x xenial/main DEP-11 64x64 Icons
Paketlisten werden gelesen... Fertig
W: The repository 'https://deb.nodesource.com/node_8.x xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Fehlschlag beim Holen von https://deb.nodesource.com/node_8.x/dists/xenial/main/source/Sources  
E: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.
Error executing command, exiting`

It seems that `https://deb.nodesource.com/node_8.x xenial/main Sources` can not be reached.
Same problem with node_7.x and node_6.x

**Comment by chrislea** [comment]
The [release file](https://deb.nodesource.com/node_8.x/dists/xenial/Release) is certainly there. Can you get to:
```
https://deb.nodesource.com/node_8.x/dists/xenial/Release
```
from the target machine?

**Comment by Leon-001** [comment]
Strange: yes, I can reach the file!
But what am I doing wrong?

**Comment by migueldanto** [comment]
me sale esto:  :cry: 
```
## Installing the NodeSource Node.js 8.x LTS Carbon repo...


## Populating apt-get cache...

+ apt-get update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Obj:2 http://packages.microsoft.com/repos/vscode stable InRelease                                    
Obj:3 https://deb.opera.com/opera-stable stable InRelease                                            
Obj:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                                    
Obj:5 http://dl.google.com/linux/chrome/deb stable Release                                           
Ign:6 http://ppa.launchpad.net/kirillshkrogalev/ffmpeg-next/ubuntu bionic InRelease                  
Obj:7 http://mx.archive.ubuntu.com/ubuntu bionic InRelease                         
Des:9 http://mx.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                         
Obj:10 http://ppa.launchpad.net/obsproject/obs-studio/ubuntu bionic InRelease        
Err:11 http://ppa.launchpad.net/kirillshkrogalev/ffmpeg-next/ubuntu bionic Release  
  404  Not Found [IP: 91.189.95.83 80]
Des:12 http://mx.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Leyendo lista de paquetes... Hecho
E: El repositorio «http://ppa.launchpad.net/kirillshkrogalev/ffmpeg-next/ubuntu bionic Release» no tiene un fichero de Publicación.
N: No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.
N: Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios.
Error executing command, exiting

```

**Comment by chrislea** [comment]
@migueldanto Your issue seems to be with the `ffmpeg-next` repository, not ours. We don't have any control over that. Sorry!
