### ISSUE TITLE
arm7 nodejs 

### ISSUE THREAD

**Issue by mihongkun** [nodesource/distributions#422]
###### centos7 arm7(raspberry 3 b)  install nodejs ：
```shell
[root@centos-rpi3 ~]# curl --silent --location https://rpm.nodesource.com/setup_                                                                                                                                                             7.x | bash -

## Installing the NodeSource Node.js 7.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release |                                                                                                                                                             | rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## You don't appear to be running a supported machine architecture: armv7l. Plea                                                                                                                                                             se contact NodeSource at https://github.com/nodesource/distributions/issues if y                                                                                                                                                             ou think this is incorrect or would like your architecture to be considered for                                                                                                                                                              support.

```

what can i do? how to do?

**Comment by chrislea** [comment]
We do not provide ARM builds for CentOS or Fedora. We only provide ARM builds for Debian Jessie and newer, as well as Ubuntu Trusty and newer. If we get sufficient demand we will look into making `rpm` packages, but the demand to date has overwhelmingly been for `deb` packages. If you install Raspbian on your Rpi3, then our `deb` repositories should work fine. Hope this helps!

**Comment by rvagg** [comment]
first time I've seen someone using centos on rpi so this is a helpful datapoint at least! thanks for letting us know @mihongkun

**Comment by devilwacause** [comment]
Requesting that node.js be build for Centos & arm7.

**Comment by chrislea** [comment]
@devilwacause Unfortunately we can't build for that target because we don't have a compiler toolchain available that will build modern versions of V8 on CentOS.

**Comment by devilwacause** [comment]
@chrislea not sure this would help but found this link

https://web1.foxhollow.ca/?menu=centos7arm

Deals with something else but might be of use.

**Comment by chrislea** [comment]
@devilwacause Unfortunately not. That's a cross compiler which isn't what's needed.
