### ISSUE TITLE
problem installing Node JS on Kali. installation went in loop whilemake install

### ISSUE THREAD

**Issue by sultan-pathan** [nodesource/distributions#423]
while i am installing Node JS on Kali, after getting clone from GitHub (git clone git://github.com/nodejs/node.git)
then cd node
./configure --prefix=~/local
make install

When i tried to install through make command after installing few files my installation went in loop (screen shot is below) plz guide me how to overcome the error.
![nodejs install prob](https://cloud.githubusercontent.com/assets/25948837/23202154/c0760940-f902-11e6-8228-932ef97dda86.png)

**Comment by chrislea** [comment]
Sorry, but this repository is only for questions related to the `rpm` or `deb` packages we make for Node. If you're having trouble compiling it yourself I'd recommend asking for help on the appropriate IRC channel.
