### ISSUE TITLE
How about UPDATE instructions? Not installations only

### ISSUE THREAD

**Issue by wzup** [nodesource/distributions#424]
How to update? There is only for installations

![nodesource_distributions_ nodesource node js binary distributions - google chrome 2017-02-24 13 59 24](https://cloud.githubusercontent.com/assets/3880497/23292285/99a8721a-fa99-11e6-86f0-630ad5a5424d.png)

**Comment by chrislea** [comment]
When you install per the instructions, it sets up the NodeSource repostiories on your machine. After this happens you will automatically get any updates that come out for the release line you installed. So for example if you run the setup script for Node v6.x, after that if there's a new version of 6.x that comes out, your machine will automatically get it when you do
```
apt-get update && apt-get upgrade
```
or
```
yum -y update
```
depending on what kind of system you are using.

**Comment by wzup** [comment]
I'm on my AWS Ubuntu. And it doesn't get any updates.

**Comment by chrislea** [comment]
Can you be more specific about what you did to install our packges, what you're expecting to happen, and what behavior you're actually seeing?

**Comment by ItangSanjana** [comment]
I wonder about this too. Node v4 on Ubuntu 16.04. Should I purge this v4 and it's PPA first before installing v6?

Current repo:
```
https://deb.nodesource.com/node_4.x xenial/main i386 Packages
release o=Node Source,n=xenial,l=Node Source,c=main,b=i386
origin deb.nodesource.com
```

The key:
```
pub   4096R/68576280 2014-06-13
uid   NodeSource <gpg at nodesource dot com>
sub   4096R/AA01DA2C 2014-06-13
```

TIA

**Comment by igsu** [comment]
> When you install per the instructions, it sets up the NodeSource repostiories on your machine. After this happens you will automatically get any updates that come out for the release line you installed. So for example if you run the setup script for Node v6.x, after that if there's a new version of 6.x that comes out, your machine will automatically get it when you do
> 
> ```
> apt-get update && apt-get upgrade
> ```
> 
> or
> 
> ```
> yum -y update
> ```
> 
> depending on what kind of system you are using.

Updates are working as expected. 

Closing this now.
