### ISSUE TITLE
New error message when installing Node 6.9.5 Debian Package

### ISSUE THREAD

**Issue by lynnaloo** [nodesource/distributions#425]
This is the command I'm using to install Node 6.9.5 on my Ubuntu 14.04 VM:

```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y node=6.9.5-1nodesource1~trusty1
```

This is the error message that I started seeing two days ago (previously no errors):

```
E: Version '6.9.5-1nodesource1~trusty1' for 'node' was not found
```

**Comment by chrislea** [comment]
Our repository doesn't support pinning, so you can't use `apt` to install anything but the newest version which is currently 6.10.0. The earlier packages are there and you can grab them with something like `curl` if you need to.
