### ISSUE TITLE
[Debian 8] setup_7.x fails on apt-get update partial fail

### ISSUE THREAD

**Issue by ziglef** [nodesource/distributions#426]
Don't quite know if this can be solved but basically if you have a source that is failing to fetch `apt-get update` finishes and does everything normal but throws:
`E: Some index files failed to download. They have been ignored, or old ones used instead.`

To which setup_7.x says:
`Error executing command, exiting`.

While it is indeed an error it is one (in this case) that has nothing to do with nodejs and the setup could continue. In my case i had to manually remove said source run setup_7.x install node and then re-added the source.

**Comment by chrislea** [comment]
Yeah there's not really anything we can do about that as there's no way to know whether or not that kind of error would break the Node stuff or not, so we do the standard *NIX thing and bail out if something doesn't return cleanly during the install process.
