### ISSUE TITLE
Unable to install Node v6.10.0 LTS on Ubuntu OS 15.04

### ISSUE THREAD

**Issue by nabeeljavaid** [nodesource/distributions#427]
I am using following commands for installation

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

**Terminal Error Message:**
Reading package lists... Done                                                                                                                                            

## Confirming "vivid" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/vivid/Release'

## Your distribution, identified as "vivid", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

_**Please guide me why I am getting this message again and again**_

Thanks

**Comment by chrislea** [comment]
Ubuntu Vivid has reached EOL and is no longer being supported by Canonical. Therefore, we do not provide support for it either. If you update to something that is currently supported such as Ubuntu Xenial, the setup script will work.
