### ISSUE TITLE
RPM repository with wrong packages

### ISSUE THREAD

**Issue by bertalanimre** [nodesource/distributions#430]
Dear Dev. Team,

I've encountered an issue installing NodeJS 6.10 LTS on CentOS 7.

Formerly I've used your repository that you've provided on your website with the following command:
`curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -`

This creates the repo file with the follwoing content:
```
[nodesource]
name=Node.js Packages for Enterprise Linux 7 - $basearch
baseurl=https://rpm.nodesource.com/pub_6.x/el/7/$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL

[nodesource-source]
name=Node.js for Enterprise Linux 7 - $basearch - Source
baseurl=https://rpm.nodesource.com/pub_6.x/el/7/SRPMS
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
gpgcheck=1
```

However, I can't seem to install version 6.10, only 7 and above. If I list the available versions by yum, I get the following list:

```
[root@workstation ]# yum --showduplicates list nodejs | expand
Betöltött bővítmények: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.freepark.org
 * epel: mirror.inode.at
 * extras: ftp.freepark.org
 * remi-php71: ftp.arnes.si
 * remi-safe: ftp.arnes.si
 * updates: ftp.freepark.org
Elérhető csomagok
nodejs.x86_64             1:6.9.4-2.el7                               epel      
nodejs.x86_64             2:7.0.0-0.1.beta1.el7.centos                nodesource
nodejs.x86_64             2:7.0.0-1nodesource.el7.centos              nodesource
nodejs.x86_64             2:7.1.0-1nodesource.el7.centos              nodesource
nodejs.x86_64             2:7.2.0-1nodesource.el7.centos              nodesource
nodejs.x86_64             2:7.2.1-1nodesource.el7.centos              nodesource
nodejs.x86_64             2:7.3.0-1nodesource.el7.centos              nodesource
nodejs.x86_64             2:7.4.0-1nodesource.el7.centos              nodesource
nodejs.x86_64             2:7.5.0-1nodesource.el7.centos              nodesource
nodejs.x86_64             2:7.6.0-1nodesource.el7.centos              nodesource
nodejs.x86_64             2:7.7.1-1nodesource.el7.centos              nodesource
nodejs.x86_64             2:7.7.2-1nodesource.el7.centos              nodesource
nodejs.x86_64             2:7.7.2-2nodesource.el7.centos              nodesource
```

Can you confirm me if this is a bug or a feature? If it is a feature, how can I install LTS version from repository?

Thank you in advance!

Bert

**Comment by chrislea** [comment]
I suspect you may have previously set up things to install Node v7.x, and as a consequence it's still seeing those. Can you try removing the repo files:
```
rm -fv /etc/yum.repos.d/nodesource*
```
and also get rid of any release files:
```
yum remove nodesource-release* --purge
```
and then try re-running the setup script?

**Comment by bertalanimre** [comment]
I have not set up anything. Only installed epel and remi repositories. After that, I've started to install NodeJS 6.10 according to the install guide from the website. 

The methods you've encouraged me to do are already have been made. The above results are coming after each other in their plain order.

**Comment by chrislea** [comment]
Okay, so then I'm wondering if there's something in the `yum` cache that is still seeing the v7 packages. Have you tried running
```
yum clean all
```
as root?

**Comment by bertalanimre** [comment]
Also did that earlier, but it didn't fix the issue.

**Comment by pamamolf** [comment]
cd /etc/yum.repos.d/
rm -rf /etc/yum.repos.d/nodesource-el.repo
yum clean all
yum update

And then try again :) yum update needed after the clean :)

**Comment by bertalanimre** [comment]
That wasn't the answer neither. Somehow it got fixed after a few days on it's own. I suspect backent issues with the repository host server. ;)

Closing the ticket and thank you all for the help.
