### ISSUE TITLE
Failed to install Nodejs 6.10 on Debian Wheezy Armhf

### ISSUE THREAD

**Issue by vkotovv** [nodesource/distributions#431]
* **Version**: 6.10.0-1nodesource1~wheezy1
* **Platform**: Linux beaglebone 3.8.13-bone79 #1 SMP Tue Oct 13 20:44:55 UTC 2015 armv7l GNU/Linux

I was not able to install Nodejs 6.10 package via [installation script](https://deb.nodesource.com/setup_6.x) on my Beaglebone Black on Debian Wheezy (ARM-based). After spending some time struggling to install, I've found out that `Packages` file is empty in the [remote repo](https://deb.nodesource.com/node_6.x/dists/wheezy/main/binary-armhf/). `Packages.gz` is empty too, its just a gzipped 0-byte file. But for other architectures (like i386) files are present. Is it ok? Did anyone successfully install Nodejs on Debian 7 ARM?

Here is the output from apt-cache command:
```
root@beaglebone:~# apt-get clean
root@beaglebone:~# apt-get update
Hit:1 http://security.debian.org wheezy/updates InRelease
Ign:2 http://ftp.us.debian.org/debian wheezy InRelease                                           
Hit:3 http://ftp.us.debian.org/debian wheezy-updates InRelease                                   
Hit:4 http://repos.rcn-ee.com/debian wheezy InRelease                      
Hit:5 http://ftp.us.debian.org/debian unstable InRelease                 
Hit:6 http://ftp.us.debian.org/debian wheezy Release
Hit:7 https://deb.nodesource.com/node_6.x wheezy InRelease
Reading package lists... Done

root@beaglebone:~# apt-get install nodejs=6.10.0-1nodesource1~wheezy1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '6.10.0-1nodesource1~wheezy1' for 'nodejs' was not found

root@beaglebone:~# apt-cache madison nodejs
    nodejs | 4.7.2~dfsg-2+b1 | http://ftp.us.debian.org/debian unstable/main armhf Packages
    nodejs | 0.10.42~dfsg-0rcnee2~bpo70+20160217+1 | http://repos.rcn-ee.com/debian wheezy/main armhf Packages

root@beaglebone:~# apt-cache policy nodejs
nodejs:
  Installed: 4.7.2~dfsg-2+b1
  Candidate: 4.7.2~dfsg-2+b1
  Version table:
 *** 4.7.2~dfsg-2+b1 500
        500 http://ftp.us.debian.org/debian unstable/main armhf Packages
        100 /var/lib/dpkg/status
     0.10.42~dfsg-0rcnee2~bpo70+20160217+1 500
        500 http://repos.rcn-ee.com/debian wheezy/main armhf Packages

root@beaglebone:~# cat /etc/apt/sources.list.d/nodesource.list 
deb https://deb.nodesource.com/node_6.x wheezy main
# deb-src https://deb.nodesource.com/node_6.x wheezy main
```
I have unstable repository turned on for some other packages that I need.

**Comment by chrislea** [comment]
This is indeed an error on our side, for some reason the wheezy package for `armhf` didn't build properly and isn't in the repo. We are looking into it.

**Comment by chrislea** [comment]
Ah, I'm sorry again, I did not read the title fully.

Debian Wheezy is not supported for this version of Node on `armhf` due to the lack of available compilers that will actually build modern versions of V8. If you update to Jessie, the installation should work.

**Comment by vkotovv** [comment]
Ok, now I understood. Sorry, did not see corresponding section in the Readme. I've looked into [this guide](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions), and it says `armhf` is supported, Wheezy is supported. Maybe it can be stated there? Also, it would be great if install script could warn if there is no distribution available for Wheezy and Ubuntu precise.
