### ISSUE TITLE
How do I rollback to a previous Node 7.x.x version?

### ISSUE THREAD

**Issue by dandv** [nodesource/distributions#432]
After installing 7.7.4, a complex application exits with "RangeError: Invalid array length". How can I revert to a known version of node that worked?

**Comment by chrislea** [comment]
If you're using an `rpm` based distro, you can specify the version directly with `yum` or `dnf`. If it's a `deb` based distro, you'll need to download the appropriate package from
```
https://deb.nodesource.com/node_7.x/pool/main/n/nodejs/
```
and install it directly with `dpkg`.

**Comment by dandv** [comment]
I'm on Ubuntu and tried `sudo apt-get install nodejs=7.7.2` but the version was allegedly not found.

**Comment by chrislea** [comment]
As I said, if you're using a Debian based distribution, you'll need to download the package directly and install it with `dpkg`. Our `deb` repo doesn't support version pinning unfortunately.

**Comment by chrislea** [comment]
For more info on this, please reference https://github.com/nodesource/distributions/issues/307, but what it comes down to is that:

1. The `reprepro` command we use to manage the repo doesn't support pinning and
2. Switching away from `reprepro` will be a fair amount of work to do, so it hasn't happened yet (though I'd certainly like to get to it eventually)

Sorry I don't have a better answer for you. :-/
