### ISSUE TITLE
Alphine Linux Support !

### ISSUE THREAD

**Issue by shivarajnaidu** [nodesource/distributions#433]
Alphine Linux is a small minimal security focused linux distro and very feasible to use in containers such as docker.. There we can use it to construct docker images... so if we can able to add support to alphine linux it would be helpful to many developers... who use containers..

Any Support is appreciable....

**Comment by chrislea** [comment]
We are certainly aware of Alpine and we will look into providing direct support for it if there is sufficient demand. In the meantime we make Docker images based on Ubuntu available. Hope this helps.

**Comment by shivarajnaidu** [comment]
Thanks for kind response

**Comment by divishav** [comment]
Is there any update on this ticket? Do you have support for Alpine now?
