### ISSUE TITLE
Fedora 26 is not supported

### ISSUE THREAD

**Issue by bash** [nodesource/distributions#437]
When trying to set up the nodejs repository on Fedora 26 with `curl --silent --location https://rpm.nodesource.com/setup_7.x | bash -` the following message is shown:

> \#\# Your distribution, identified as "fedora-release-26-0.5.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
Our policy is that we don't generally support Linux distros that are in alpha / beta / some other pre-release state. According to [this](https://fedoraproject.org/wiki/Releases/26/Schedule), FC26 is supposed to ship on June 27th of this year, and assuming that's what they do, we will support it at that time. Until then I expect that the packages for FC25 will likely install just fine if you want to try that.
