### ISSUE TITLE
CyberGalleon (ParrotSec 3.5)

### ISSUE THREAD

**Issue by NoOutlet** [nodesource/distributions#438]
> Your distribution, identified as "CyberGalleon", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

ParrotSec is based on Debian.

**Comment by chrislea** [comment]
We can't support every Debian variant internally. However, the setup scripts which alias various Debian derivatives are freely available in this repo. Please feel free to submit a PR against them for support for this distro and if it looks good we'll merge it. Thanks.
