### ISSUE TITLE
v0.10.33 segfaults on Raspberry Pi with Raspbian Wheezy (2014-09-09)

### ISSUE THREAD

**Issue by sandeepmistry** [nodesource/distributions#44]
I followed the [Debian and Ubuntu based Linux distributions](https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions) instructions.

When I run ```node``` or ```npm``` a segmentation fault occurs.

```shell
pi@raspberrypi ~ $ node -v
Segmentation fault
pi@raspberrypi ~ $ npm -v
Segmentation fault
```

GDB output:
```shell
pi@raspberrypi ~ $ gdb /usr/bin/node
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/node...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/node 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x001e8fd2 in DES_xcbc_encrypt ()
(gdb) bt
#0  0x001e8fd2 in DES_xcbc_encrypt ()
(gdb) 
```

Install output:
```shell
pi@raspberrypi ~ $ sudo apt-get install nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  rlwrap
The following NEW packages will be installed:
  nodejs rlwrap
0 upgraded, 2 newly installed, 0 to remove and 2 not upgraded.
Need to get 0 B/5,671 kB of archives.
After this operation, 17.6 MB of additional disk space will be used.
Do you want to continue [Y/n]? y
Selecting previously unselected package rlwrap.
(Reading database ... 78080 files and directories currently installed.)
Unpacking rlwrap (from .../rlwrap_0.37-3_armhf.deb) ...
Selecting previously unselected package nodejs.
Unpacking nodejs (from .../nodejs_0.10.33-2nodesource1~wheezy1_armhf.deb) ...
Processing triggers for man-db ...
Setting up rlwrap (0.37-3) ...
update-alternatives: using /usr/bin/rlwrap to provide /usr/bin/readline-editor (readline-editor) in auto mode
Setting up nodejs (0.10.33-2nodesource1~wheezy1) ...
```

Ran a ```sudo apt-get update && sudo apt-get upgrade``` before node setup/install.

**Comment by andig** [comment]
Same problem here, crashing at least up to 0.11.14-1nodesource1~wheezy1

Could we get a more current build of 0.11 that contains the fix mentioned in https://github.com/nodesource/distributions/issues/44?

**Comment by babraham123** [comment]
@andig 
For now I've fixed the problem by compiling node from source. Just change the numbers to the version you want.
http://shapeshed.com/compiling-nodejs-from-source-on-ubuntu-10-04/

**Comment by rvagg** [comment]
I don't believe we can build armv6 binaries through our standard deb builder setup but it might be practical to maintain a completely separate channel for raspbian.

To try out a test setup I've made, remove the nodesource entries from `/etc/apt/sources.list` and do the following:

```
sudo apt-get remove nodejs
sudo su -c 'echo "deb https://deb.nodesource.com/armv6l-node/ weezy main" >> /etc/apt/sources.list'
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install nodejs
```

Don't count on this working forever, I'll need to discuss this with @chrislea and make sure we can keep things consistent.

If it stops working, come back here and chat.

**Comment by DarkPark** [comment]
thanks

**Comment by sandeepmistry** [comment]
@rvagg thanks! Works on my RPi!

Will the instructions be added to the [nodesource/distributons read me](https://github.com/nodesource/distributions/blob/master/README.md) or [Installing Node.js via package manager wiki page](https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager)?

**Comment by rvagg** [comment]
@sandeepmistry it'll be bundled into the setup script for all .deb-based distributions so you'll run the standard command used by ubuntu and debian (listed on that page and in the README of this repo). I just need to make some changes and test. It'll have to do a `uname -a` to find `armv6l` to differentiate it from vanilla `weezy` which is the problem now (i.e. no differentiation).

**Comment by nisargjhaveri** [comment]
Doesn't work for me. @rvagg, Any other solution now?

**Comment by enzanki-ars** [comment]
By the way, Adafruit has their own builds for Node.js.  See: https://learn.adafruit.com/node-embedded-development/installing-node-dot-js

**Comment by ayancey** [comment]
@enzanki-ars Node works fine on Adafruit's repo, but do you know if they have anything for npm?

**Comment by enzanki-ars** [comment]
When you install node from adafruit, it also installs npm.

**Comment by LouiseLi1889** [comment]
I got the same problem due to follow the instruction
by DougieLawson » Wed Mar 04, 2015 6:50 pm
On a Raspberry Pi 2B use
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install -y build-essential python-dev python-rpi.gpio nodejs

**Comment by rvagg** [comment]
Just a note here, if you're looking for good binaries for armv6 platforms, io.js comes with binaries that are now built on wheezy: https://iojs.org/dist/latest/

**Comment by LouiseLi1889** [comment]
Thanks.

**Comment by dmiddlecamp** [comment]
just hit this again... from instructions here - https://nodejs.org/en/download/package-manager/

**Comment by chrislea** [comment]
Please look [here](https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md) at the bottom. We don't currently support ARM builds on old Debian / Ubuntu distros due to compiler toolchain issues.

**Comment by dmiddlecamp** [comment]
I was using the latest Jessie raspbian on a Pi B+ v1.2 when I hit the segfault issue: 

![screen shot 2015-12-16 at 11 01 09 am](https://cloud.githubusercontent.com/assets/833793/11847700/5552543a-a3e4-11e5-9bb7-3bf5af5a8892.png)

Fixed by grabbing https://nodejs.org/dist/v4.2.3/node-v4.2.3-linux-armv6l.tar.gz

**Comment by aburgd** [comment]
Using the source that @rvagg posted worked for me on DietPi Jessie, FWIW

**Comment by mathiasrw** [comment]
@dmiddlecamp thanks :+1:

**Comment by samfearn** [comment]
The instructions supplied by @rvagg don't seem to work on a full Jessie build as opposed to the light version working as reported by @aburgd.
