### ISSUE TITLE
Deepin is not currently supported

### ISSUE THREAD

**Issue by rtalexk** [nodesource/distributions#442]
\#\# Installing the NodeSource Node.js v7.x repo...

\#\# Populating apt-get cache...

\+ apt-get update
Hit:1 http://repository.spotify.com stable InRelease                                             
Hit:2 http://packages.microsoft.com/repos/vscode stable InRelease                                
Hit:3 http://mirror.jmu.edu/pub/deepin unstable InRelease                                        
Get:4 http://packages.deepin.com/deepin unstable InRelease [13.8 kB]                             
Fetched 13.8 kB in 5s (2,466 B/s)                              
Reading package lists... Done

\#\# Confirming "unstable" is supported...

\+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_7.x/dists/unstable/Release'

\#\# Your distribution, identified as "unstable", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by SmartcoderC** [comment]
I solved this problem by this way   : 
1) Copy script from [https://deb.nodesource.com/setup_7.x](url) .
2) Find line DISTRO=$(lsb_release -c -s) and change to DISTRO="jessie".
3) Save all script to file /Downloads/script.sh .
4) then run comand in terminal : 
`cat ./Downloads/script.sh | sudo -E bash -
`
5) `sudo apt update && sudo apt install nodejs`

**Comment by marcoshmendes** [comment]
@SkynetAtack Really helpful, it works!

**Comment by KraevRoot** [comment]
@SkynetAtack works great even with setup_8.x, 10Q

**Comment by jiage8866** [comment]
@SkynetAtack Thank u,I slove the problem too ~

**Comment by froghramar** [comment]
thanks @SkynetAtack , even works for 8.x

**Comment by SkynetAtack** [comment]
Don't mention it. I am happy that I was able to help you somehow

**Comment by SkynetAtack** [comment]
Now  You can change DISTRO variable to DISTRO="stretch"

**Comment by SkynetAtack** [comment]
I rewrote the script a little. It includes support for Deepin
https://github.com/SkynetAtack/deepin-node6-script

**Comment by RaufR** [comment]
@SkynetAtack  thanks a lot

**Comment by diegolameira** [comment]
#515  I just added a pull request, I hope that it helps you to close this dupe issue =)

**Comment by dyangua** [comment]
Really good, thank !!

**Comment by jhc1982** [comment]
Old thread but still open so just wanted to see if there are any plans to support deepin 15.5 anytime soon? Failing that is anyone running v8 successfully? I am looking to move my main work dev machine to deepin

**Comment by chrislea** [comment]
Sorry for the radio silence. It looks as if at least one variant of Deepin [is supported](https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L286). Does this not cover your use case @jhc1982 ?

**Comment by jhc1982** [comment]
Hey @chrislea I am not sure but I am thinking the problem may be because deepin is actually based on Debian unstable..which came as news to me. I did follow @skynet-ltd 's advice above and I am now running V8.11.1...So he is now top of my Christmas card list :)

Thanks for the help all

**Comment by chrislea** [comment]
Okay, closing then.

**Comment by alazypig** [comment]
Helps me a lot.Thx

**Comment by decarvalholucas** [comment]
Thanks @skynet-ltd it's worked for me!

**Comment by donaldjohn** [comment]
Deepin 15.11 change $(lsb_release -c -s)  to 'stretch'

**Comment by psipher** [comment]
@donaldjohn Im getting the error
## Your distribution, identified as "stretch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support.
I have made this changes DISTRO='stretch'
