### ISSUE TITLE
Canaima "Chimanta" is not currently supported

### ISSUE THREAD

**Issue by jedial23** [nodesource/distributions#444]
Currently Debian-based Canaima "Chimantá" is not supported. 
Using method below:
`$    cd ~`
`$    curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh`
`$ sudo bash nodesource_setup.sh`

## Populating apt-get cache...

+ apt-get update
Leyendo lista de paquetes... Hecho

## Confirming "Chimanta" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/Chimanta/Release'

**Comment by chrislea** [comment]
We can't support all the Debian based distros ourselves, but if you'd like to add support for this by aliasing it to the correct builds that we make via our setup scripts, please just submit a PR with the changes. If it looks good we'll merge it in. Thanks.
