### ISSUE TITLE
Confirming "zesty" is supported...

### ISSUE THREAD

**Issue by KannarFr** [nodesource/distributions#445]
Heyo,

"Your distribution, identified as "zesty", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support."

(zesty is the new ubuntu).

Friendly,

Alex.

**Comment by InvaderDolan** [comment]
I've installed 17.04 and tried to install Node.js and after that message I typed 'sudo apt-get install -y nodejs' like a crazy man, lol.

**Comment by mattpalermo** [comment]
Yay Zesty has arrived. The following commands can be used to get the yakkity nodesource repo for now until there is an official zesty repo. So far it hasn't blown up (I ran `node --version` and it didn't explode).

```
sudo bash -c 'echo "deb https://deb.nodesource.com/node_6.x yakkety main" >> /etc/apt/sources.list.d/nodesource.list'
sudo bash -c 'echo "deb-src https://deb.nodesource.com/node_6.x yakkety main" >> /etc/apt/sources.list.d/nodesource.list'
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
sudo apt update
sudo apt install nodejs
```

**Comment by chrislea** [comment]
Hey folks. I know Zesty just landed and will try to get builds out just as soon as I can. Hopefully tomorrow (Friday), but my parents are in town visiting so it might be over the weekend, or Monday at the latest. The Yakkety packages will work fine I expect if you install them directly in the meantime. Please stay tuned.

**Comment by chrislea** [comment]
Okay, packages for Node.js versions 4, 6 and 7 have been added for all architectures for Zesty. Have fun all.

**Comment by aercanunal** [comment]
@chrislea what about node.js version 5?

**Comment by chrislea** [comment]
@aercanunal Node v5.x is ELO and no longer supported. We don't build new packages for it.

**Comment by aercanunal** [comment]
@chrislea thanks for your quick answer
