### ISSUE TITLE
why centos 7 not supported?

### ISSUE THREAD

**Issue by CharlotteLock** [nodesource/distributions#446]
my system is centos-release-7-3.1611.el7.centos.x86_64, setup_7.x notify me can't supported.

**Comment by chrislea** [comment]
CentOS 7 should be supported. Can you let us know what the output of the installer script says. Ideally, please download it to your machine and run it manually with the `-x` flag IE:
```
% curl -RLO https://rpm.nodesource.com/setup_7.x
% chmod 755 setup_7.x
% sudo ./setup_7.x -x
```
Thanks.

**Comment by CharlotteLock** [comment]
thanks  for your answer,the flowing is my machine output:
## Your distribution, identified as "centos-release-7-3.1611.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
Yes, but that doesn't tell us what anything about where the error is. Can you please run the commands from my previous post and paste the full output of the script, run with the `-x` flag, here so we can try and see what's going on?

**Comment by CharlotteLock** [comment]
[root@localhost ~]#rpm -qa nodejs
nodejs-7.9.0-1nodesource.el7.centos.x86_64
ok, it works fine, thanks for your answer, so i maybe think so, that lack package's install on the centos

**Comment by CharlotteLock** [comment]
at last, thanks

**Comment by christalk** [comment]
Hello chrislea,

I would like to thank you.

I had the error too:
## Your distribution, identified as "centos-release-7-3.1611.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

I have now : 
node v7.9.0
and npm 4.2.0

**Comment by christalk** [comment]
HI,
And now,  from 8.x, to update to the  the new node.js version 10.x ,, is it the same procedure ?

% curl -RLO https://rpm.nodesource.com/setup_10.x
% chmod 755 setup_10.x
% sudo ./setup_10.x -x
 
?
