### ISSUE TITLE
Change script in order to allow install of node.js 7 in oracle linux

### ISSUE THREAD

**Issue by ricardomfmartins** [nodesource/distributions#448]
Hi,

The page https://nodejs.org/en/download/package-manager/ informs that we can install the latest node,js version 7 using the command:
curl --silent --location https://rpm.nodesource.com/setup_7.x | bash -

After analyzing the script, I found out that you could easily change it to work with Oracle Linux version by adding the following code to the DISTRO_PKG variable:
rpm -qf /etc/oracle-release

Could you consider this change to be added to your scripts, it would help a lot user like me that have to work with this OS version.

Regards,

Ricardo Martins

**Comment by chrislea** [comment]
We'd be happy to consider it @ricardomfmartins . Please just submit a PR to the repo and if it looks good we'll merge it. Thanks!
