### ISSUE TITLE
Looks like v8-profiler installation is failing on Ubuntu 16.04 LTS server

### ISSUE THREAD

**Issue by stoczko** [nodesource/distributions#451]
OK, first time poster here, so I hope I'm putting this in the correct place. Any advice on how to continue would be most appreciated. Essentially, I am trying to enable pdf downloads using ElectronPdfService and RESTBase for MediaWiki on Unbuntu.

I just installed node.js (v7.9.0) and npm (4.2.0) and went to cxserver directory to run npm install, when this happened:

npm ERR! Failed at the v8-profiler@5.6.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-profiler
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-04-21T16_53_46_777Z-debug.log

**Comment by gihrig** [comment]
The meaningful error info often exists above the npm distractions. 

What's on your screen before `npm ERR!`?

**Comment by stoczko** [comment]
Sorry for the delay -- this is right before the npm ERR!:

Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/sean/cxserver/node_modules/v8-profiler/build/profiler/v5.6.5/node-v51-linux-x64/profiler.node --module_name=profiler --module_path=/home/sean/cxserver/node_modules/v8-profiler/build/profiler/v5.6.5/node-v51-linux-x64' (1)
cxserver@1.1.0 /home/sean/cxserver
└── (empty)

I've put cxserver inside my home directory (sean)... could this be the source of the error?

Right after entering the npm install cmd, there is this response:

npm WARN lifecycle v8-profiler@5.6.5~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.6.5 node -e 'process.exit(0)' /home/sean/cxserver/node_modules/.staging/v8-profiler-885fa46d

> v8-profiler@5.6.5 install /home/sean/cxserver/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.6.5/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.6.5 and node@7.9.0 (node-v51 ABI) (falling back to source compile with node-gyp)

**Comment by igsu** [comment]
This is not an issue related to the provided distributions, closing now.
