### ISSUE TITLE
fresh install got error: localStorage behaved unexpectedly

### ISSUE THREAD

**Issue by giangnm** [nodesource/distributions#452]
![image](https://cloud.githubusercontent.com/assets/3450836/25312143/de86ffc6-283b-11e7-8951-f8a030c65607.png)

anyone faced this issue and how to fix it?
Thanks.

**Comment by chrislea** [comment]
This doesn't look like an issue with the distribution of the Node.js package(es), which is what this repository is for. We can only help with issues relating to the packaging of Node.js, but generally not any specific behavior that your application might show. I'd suggest asking about this in the Node.js IRC channel to see if anybody can help you diagnose this.
