### ISSUE TITLE
Unable to install v7 onto RHEL 7 System

### ISSUE THREAD

**Issue by dkgreco** [nodesource/distributions#453]
Hello,

I'm currently trying to install Nodejs v7 onto a RHEL 7 System.  

I'm using the command found from the Nodejs.org site:
curl --silent --location https://rpm.nodesource.com/setup_7.x | bash -

On execution of the statement I receive the following error:
## Could not determine your distribution version, you may not be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect. Include your 'distribution package' name: redhat-release-client-7.3-4.el7.x86_64

On running the uname -m command I receive the following value: x86_64
On running the rpm query [rpm -q --whatprovides redhat-release] for redhat release I receive:
redhat-release-client-7.3-4.el7.x86_64

and if I view the redhat-release file in the etc dir, I'm currently running:
Red Hat Enterprise Linux Client release 7.3 (Maipo)

Any help I might be able to receive would be greatly appreciated.  Just an FYI that I am new to RHEL systems...so I could be doing something wrong.
Thank you,
Dustin

**Comment by vijax** [comment]
same issue for me

**Comment by vijax** [comment]
## Your distribution, identified as "redhat-release-server-7.3-7.el7.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by rohankambli** [comment]
Hi ,

I am also facing same issue for redhat enterprise linux. Below is the message we are getting while executing command. Can anyone help fixing this issue ?

"curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -"

## Installing the NodeSource Node.js 8.x repo...
 
 
## Inspecting system...
 
+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m
 
## Confirming "el7-x86_64" is supported...
 
+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'
 
## Your distribution, identified as "redhat-release-server-7.3-7.el7.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
