### ISSUE TITLE
nodejs: installer should not regress npm

### ISSUE THREAD

**Issue by refack** [nodesource/distributions#454]
Ref: nodejs/node#12641

The installer script shouldn't instal an older version of `npm` then the one the user currently has installed.
Bonus point: The Installer could suggest and, if the user chooses to, update `npm` to latest.

**Comment by Avol-V** [comment]
Yes it’s terrible!
It says:
```
Detected old npm client, removing...
```
And replace my `5.2.0` version with `5.0.3` version!
Maybe it should **really** check current version before do this?

**Comment by refack** [comment]
Cross-ref https://github.com/nodejs/version-management/issues/16

**Comment by chrislea** [comment]
Doing this was a tough call. It boils down to this. If you globally install a newer version of `npm`, or anything for that matter, then there is no way to know 100% if everything will be in a working state when a new Node.js comes out if we just upgrade over the user upgrade. It's entirely possible (as in, we have seen this happen) that you could update `npm` or some other package to a newer version, and then if we upgrade over it, `npm` itself is just left in an non-working state entirely.

Now, some people will say "well if a user globally updates something then that's on them, you still shouldn't regress anything ever". However others will turn right around and say "you should never allow an install or update to leave things in a non-functional state". So there is no way to make everybody happy here.

We have decided to go with the "make sure things are always functional after an upgrade" route. It's not ideal, but we feel it has the least potential to do bad things. Sorry for the inconvenience, but we hope you understand why.

**Comment by refack** [comment]
> We have decided to go with the "make sure things are always functional after an upgrade" route. It's not ideal, but we feel it has the least potential to do bad things. Sorry for the inconvenience, but we hope you understand why.

I'm Ok with this if it's intentional, and the tradeoffs have been given thought.
I'm not a `.deb` expert but I have a faint recollection of installers asking me if I wanted some stuff to happen or not, so maybe give the user the choice (with the default being `npm` as packaged)?

**Comment by chrislea** [comment]
@refack Yes I considered the option of having a user prompt also. The problem there is that there are absolutely **tons** of people who rely on the installs happening automatically without any user intervention for their systems automation. So anything that requires user input to complete an install is not an option.

**Comment by refack** [comment]
> @refack Yes I considered the option of having a user prompt also. The problem there is that there are absolutely tons of people who rely on the installs happening automatically without any user intervention for their systems automation. So anything that requires user input to complete an install is not an option.

Like I wrote I don't know enough, but if there's an option to have a default for "silent" installs, and "GUI" for interactive installs, that would be nice.
If not possible to distinguish, then IMHO the current approach is best.

**Comment by chrislea** [comment]
Nope, there's no way to distinguish between "interactive" and "non-interactive".
