### ISSUE TITLE
Node repository and install script fails on Centos:latest docker container

### ISSUE THREAD

**Issue by robert-marriott** [nodesource/distributions#456]
The script runs and decides that centos 7:latest image is incompatible. Both Node 6.x and 7.x scripts have the same result:

```Your distribution, identified as "centos-release-7-3.1611.el7.centos.x86_64", is not currently supported```

**Comment by chrislea** [comment]
Can you please provide the full output of the setup script? Ideally, please download it and run it locally with the `-x` flag ie:
```
curl -sL https://rpm.nodesource.com/setup_7.x
chmod 755 setup_7.x
sudo ./setup_7.x -x
```
Those setup scripts were written assuming they'd be run on "normal" servers, so I'm not sure if being inside a Docker container will cause issues.

**Comment by robert-marriott** [comment]
Hi, I believe I have identified the issue. I was attempting to install node into the CentOS container behind a corporate network. When using a nonproxied network the script completed without any issues for both Node 6 and 7. 

I am unsure why it decided that the "unsupported distribution" shell message was the one to arrive on. Perhaps the environment variables from behind the proxy didn't resolve in the appropriate way.

**Comment by chrislea** [comment]
Ah, yes, the proxy thing is a [known issue](https://github.com/nodesource/distributions/issues/9). The TLDR is to do:
```
curl -sL https://rpm.nodesource.com/setup_7.x | sudo -E bash -
```
The `-E` makes `sudo` preserve the environment which gets around the proxy issues.

Glad you got it sorted out either way.
