### ISSUE TITLE
How to update node v7.9.0 to the latest node v7.10.0 version, on Centos-release-7-3.1611.el7.centos.x86_64 ?

### ISSUE THREAD

**Issue by christalk** [nodesource/distributions#459]
Hello, 

The install works fine with node V7.9.0 on Centos 7-3.1611 with
https://github.com/nodesource/distributions/issues/446

But how update now node version to **node v7.10**.0 ?

Thanks.

**Comment by chrislea** [comment]
The packages for 7.10.0 were added earlier today. So you should be able to just run:
```
sudo yum update
```
to install 7.10.0. Is this not working for you?

**Comment by christalk** [comment]
Hi chrislea,

Thank you so much. It works fine.

Ps: I don't know if the error message about applydeltarpm is important.
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
-------------------------------------------------------------------------------------------------------------
node -v7.9.0
sudo yum update
[Errno 14] HTTP Error 504 - Gateway Timeout
…
Loading mirror speeds from cached hostfile
…
Update
nodejs     x86_64     2:7.10.0-1nodesource.el7.centos     nodesource      10 M
…
Is this ok [y/d/N]: y
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
nodejs-7.10.0-1nodesource.el7.centos.x86_64.rpm   |  10 MB  00:00:02     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Detected old npm client, removing...
…
node -v
v7.10.0
-------------------------------------------------------------------------------------------------------------

**Comment by chrislea** [comment]
Nope, that's all normal output. Closing.
