### ISSUE TITLE
Your distribution, identified as "wheezy", is not currently supported

### ISSUE THREAD

**Issue by brilvio** [nodesource/distributions#46]
Hi there I using a Beaglebone Black with Debian wheezy.

PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian

And this is the error:

 Confirming "wheezy" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node/dists/wheezy/Release'

 Your distribution, identified as "wheezy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

But in https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager says this:

Supported Debian versions:

Debian 7 / stable (wheezy)

**Comment by rvagg** [comment]
`sudo -E` is now listed on the README

**Comment by BartManX** [comment]
i am having this issue and i am root ... any ideas?

**Comment by chrislea** [comment]
What command specifically are you trying to run @BartManX ?

**Comment by geoidesic** [comment]
Same problem here: I ran the command
`curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -`
as shown here:
`https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions`

**Comment by chrislea** [comment]
We are not supporting Node 7.x on Debian Wheezy due to not having suitable compilers (we are not supporting Node 7.x on Ubuntu Precise for the same reason). The minimum supported releases for Node 7.x are Debian Jessie and Ubuntu Trusty. Hope this helps.

**Comment by ch3ll0v3k** [comment]
You can download bins from https://nodejs.org/en/download/

And then just tar -xf downloadet.files.arch.extention

ln -s /downloadet.files.arch.extention/usr/bin/node /usr/bin/node
ln -s /downloadet.files.arch.extention/usr/bin/npm /usr/bin/npm


```
node -v 
v8.9.1
```

**Comment by ch3ll0v3k** [comment]
Daammm. See it just now :D this post was in 2014 hahahahah sorry

**Comment by mckaygerhard** [comment]
hi i got working nodejs debs from same repository on wheezy.. for download go to : https://t.me/s/vegnuli/283 .. for 386 and amd64
