### ISSUE TITLE
Repo support for node7 on fedora 26 please

### ISSUE THREAD

**Issue by andyfitz** [nodesource/distributions#461]
$subject;

**Comment by chrislea** [comment]
We don't generally support distros in alpha or beta release stages. So, we'll be supporting FC26 once it is [fully released](https://fedoraproject.org/wiki/Releases/26/Schedule). Thanks.

**Comment by chrislea** [comment]
In the meantime, I'm pretty sure the [FC25 packages](https://rpm.nodesource.com/pub_7.x/fc/25/x86_64/) will install and work just fine on the FC26 beta (or whatever state FC26 is in now).

**Comment by andyfitz** [comment]
Agreed.  They work for me, I just stripped the releasever from the repo config. 

Some repos create anticipatory directories which is friendly to beta and alpha testers but I totally understand why you're only targeting stable.
