### ISSUE TITLE
Why different ubuntu / debian instructions in readme?

### ISSUE THREAD

**Issue by scottlinux** [nodesource/distributions#462]
Why does the readme indicate for debian to 'run as root' vs ubuntu to not run as root?

The 'ubuntu' commands work ok on debian. 

Ex:

# Using Ubuntu
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs

# Using Debian, as root
curl -sL https://deb.nodesource.com/setup_7.x | bash -
apt-get install -y nodejs

**Comment by chrislea** [comment]
This is because Ubuntu defaults to giving the user you create during the setup process full `sudo` privileges, but this is not always true on Debian systems depending on how they are initially set up. So better safe than sorry.

**Comment by scottlinux** [comment]
This makes things more confusing rather than 'safe'.  

Also, even if one runs as root, the sudo command would still work. So there is no real argument in having separate instructions for debian and ubuntu.

All of the various cloud debian versions today default to a limited user with sudo (default user: admin with most cloud debian images). For GCE, AWS, openstack, KVM, etc.

https://wiki.debian.org/Cloud

**Comment by chrislea** [comment]
We aren't aiming to address relative confusing-ness, and there's nothing more or less safe to either approach. We're aiming for consistency, and these instructions have proved to be the most consistently effective. Our `deb` packages get downloaded and installed several million times per day with generally very few issues from end users, so we're pretty happy with the setup instructions.

Also, we can't assume that people are using cloud versions of anything. We have to assume the target could be in the cloud, bare metal, virtualized bare metal, a user's desktop or laptop, or something like a Raspberry Pi.

**Comment by geofft** [comment]
> Also, even if one runs as root, the sudo command would still work.

@scottlinux The default non-cloud Debian installation does not have the sudo command installed, so instructions using sudo would fail. These instructions look correct to me as written: they say "as root", which means you should become root with `su` or by logging in with the password created during the install.

**Comment by scottlinux** [comment]
I would suggest for simplicity sake having single instructions for debian and ubuntu, using sudo.

Having users escalate to root to do anything should be avoided, especially with a curl | bash thing going on.

Debian users do not need hand holding if they do not have sudo installed. And like I said, this is not the case in for cloud, vagrant, or where various other official debian images which feature a limited user and sudo.

**Comment by chrislea** [comment]
We are certainly not going to change the instructions to tell Debian users to run a command that may not even exist on their systems. If your argument is that they don't need handholding about `sudo` issues, I don't think they're going to be confused by the setup instructions either. Also, nobody has to our setup script(s) at all if they don't want to. People can, and do, create the needed list files by hand and import our signing key, and things work just fine.

Finally, practically speaking, this has never caused any real world issues that we're aware of. If that changes in the future we'll revise our documentation accordingly.
