### ISSUE TITLE
Node JS 8 for Centos 7?

### ISSUE THREAD

**Issue by Jayflux** [nodesource/distributions#464]
https://nodejs.org/en/blog/release/v8.0.0/

When will this be available?

**Comment by chrislea** [comment]
Everything is building currently, I'll make sure everything gets published before I go to bed today. We'll tweet about it when everything is ready.

**Comment by Jayflux** [comment]
thank you @chrislea

**Comment by chrislea** [comment]
My Twitter handle is also @chrislea.

**Comment by Jayflux** [comment]
@chrislea should i be seeing an 8 here? https://rpm.nodesource.com/pub_0.12/el/
Usually ive downloaded the rpms directly instead of doing the setup (as we have our own repo). sorry if this  isn't done yet, i saw your tweet

**Comment by chrislea** [comment]
I think you're probably wanting to look in here:

https://rpm.nodesource.com/pub_8.x/el/

**Comment by Jayflux** [comment]
@chrislea ahh thank you, yes this is what i was looking for
