### ISSUE TITLE
How to update (or upgrade) node v7.10.0 to the latest node v8.0.0 version, on Centos-release-7-3.1611.el7.centos.x86_64 ?

### ISSUE THREAD

**Issue by christalk** [nodesource/distributions#465]
Hello, 

How to update (ou upgrade) node v7.10.0 to the **latest node v8.0.0** version, on Centos-release-7-3.1611.el7.centos.x86_64 ?

sum yum update -> no package marked for update
sum yum upgrade -> no package marked for update

**Comment by christalk** [comment]
****

**Comment by gibfahn** [comment]
Have you tried the instructions in the README: https://github.com/nodesource/distributions#installation-instructions ?

**Comment by crzidea** [comment]
@gibfahn The node v8.x was just released and I can't find any place to update the package.

**Comment by gibfahn** [comment]
![image](https://cloud.githubusercontent.com/assets/15943089/26625001/ad7f13c4-45ea-11e7-895e-b2bac2acb3be.png)

**Comment by christalk** [comment]
That's very kind of you, but I'm not sure it's the same issue :  Ubuntu vs Centos ?
The link you are giving is working on Debian or Ubuntu. 
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

There is another link with  Centos
https://github.com/nodesource/distributions/issues/446
% curl -RLO https://rpm.nodesource.com/setup_8.x
% chmod 755 setup_8.x
% sudo ./setup_8.x -x


Thanks. 

Regards.

**Comment by gibfahn** [comment]
Sorry for conflating the two issues.

So for Ubuntu you're now sorted right?

Did you have an issue with the CentOS link? Everything should work fine.

**Comment by christalk** [comment]
**So for Ubuntu you're now sorted right?**
Yes, thank you.
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
## Confirming "yakkety" is supported...etc
I saw the line in my apt-repository has been changed in new lines with 8.0.0  
and It seems, the nodejs and /usr/lib/node_modules exist now only in version 8.0.0.
There is no old version . Great. That's what I wanted.
node  ->  v8.0.0
npm    ->  v5.0.0

**Did you have an issue with the CentOS link? Everything should work fine.**
I just learned that I have a demo next Friday.
I fully trust you, but as you can guess, I do not want to change 48h before, a project that works in v7.10.0 on Centos,
I would keep you informed by next week at the latest.

Regards, 

Chris

**Comment by chrislea** [comment]
The easiest thing to do if you already have the 7.x repository working is to update the repository list file directly to point to the 8.x repository.
```
sudo sed -i "s/7\.x/8\.x/g" /etc/yum.repos.d/nodesource-el7.repo
```
Then you should be able to just do a `yum update` to get the 8.x package.

**Comment by christalk** [comment]
Thank you, I will try soon, this substitution in the nodesource-el7.repo file.
I think the 7 of el7 in the name of this file, is for Centos?
And has nothing to do with the previous version of Node JS?
Is that right ?


_PS :  I'm wondering how to do the upgrade 
node.js v7.9.0   ->    node.js v8.0.0
- Windows 10  64 bts
- Windows 7 / 32 bts_    
           :

**Comment by chrislea** [comment]
Yes, the 7 in that filename refers to RHEL7 or CentOS7, not the Node.js version.

I don't know how you'd go about the upgrade on Windows, though I expect you'd just download the installer for the newest version and run it. I just maintain the Linux repositories.

**Comment by gibfahn** [comment]
@christalk for Windows you just download the installer (msi) from https://nodejs.org/en/download/current/ and install it.

**Comment by christalk** [comment]
@chrislea
Thank for the information about RHEL7 on CentOS7


@gibfahn : Thank you so much. All well passed with msi files.
Node.js v8.0.0 is now installed both on my Win7-32 bts and Win10-64

**Comment by christalk** [comment]
As I explained above, I had to wait a little to realize this new update (upgrade) from 7.x to 8.x on Centos.
I did it this morning, with instruction as indicated by chrislea, and it worked.
Directly from 7.10 to 8.1.0
Thanks to you, chrislea.

**Comment by christalk** [comment]
Hello, 

Could you tell me , please, if it's the same , now,  to update from 8.x to 10.x ?


% curl -RLO https://rpm.nodesource.com/**setup_10.x**
% chmod 755 setup_**10.x**
% sudo ./setup_**10.x -x**

?

**Comment by christalk** [comment]
Hello, 

Could you tell me, please, If it's the same, now ?
to update from 8.x to 10.x ?

https://rpm.nodesource.com/setup_10.x

**Comment by chrislea** [comment]
Yes, the same sort of procedure should work. I'd do something like:
```
sudo sed -i "s/8\.x/10\.x/g" /etc/yum.repos.d/nodesource-el7.repo
```
followed by
```
sudo yum update && sudo yum upgrade
```
Hope this helps.

**Comment by christalk** [comment]
Following your advice, I just update and upgrade from Node 8. x   to  Node 10.x.  on Centos 7.
Thanks again.

CentOS Linux release 7.6.1810 
Node.js 10.15.1
