### ISSUE TITLE
Request support for centos-release-6-9.el6.12.3.x86_64

### ISSUE THREAD

**Issue by vansteki** [nodesource/distributions#466]
when i use `yum install nodejs` on CentOS 6.9 by

`curl --silent --location https://rpm.nodesource.com/setup_7.x | bash -`

i got following message:

```
## Installing the NodeSource Node.js 7.x repo...

## Inspecting system...
+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_7.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "centos-release-6-9.el6.12.3.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support**
```

**"centos-release-6-9.el6.12.3.x86_64", is not currently supported**

**Comment by buschtoens** [comment]
CentOS 6.9 should be supported.

Are you using a proxy? Then you might be experiencing the same problem I had. 

https://github.com/nodesource/distributions/issues/470#issuecomment-306568956

**Comment by shadowym** [comment]
I have the same problem.  Not behind a proxy.

**Comment by chrislea** [comment]
Node 0.12.x is EOL and should not be installed anymore, ever. You need to update to _at least_ the 4.x release line, which should work fine installing onto CentOS 6.
