### ISSUE TITLE
403 forbidden when accessing SRPM repodata

### ISSUE THREAD

**Issue by bigeagle** [nodesource/distributions#47]
Hi,
I got 403 forbidden when trying to access this file:
https://rpm.nodesource.com/pub/el/6/SRPMS/repodata/db0852512678d58b7a87bf48658c6162e8210694-filelists.sqlite.bz2

Is the server miss configured?

cheers,
Justin

**Comment by rvagg** [comment]
please reopen if you're still having problems with this, sorry for not responding earlier

**Comment by bigeagle** [comment]
Hi, 
This file got 403,
https://rpm.nodesource.com/pub/fc/20/x86_64/repodata/db07a4d635a4a1d930354f7d0420c4ced18e640d-other.xml.gz

Cheers,
Justin

**Comment by wblankenship** [comment]
Confirmed. All other files in that directory are fine, but that is returning a 403.

**Comment by chrislea** [comment]
Sorry about this. It should **actually** be fixed now.
