### ISSUE TITLE
Request support for Linux Mint 18.2 [codename 'Sonya']

### ISSUE THREAD

**Issue by dzift** [nodesource/distributions#473]
Followed the official [nodejs.org links](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)

`## Your distribution, identified as "sonya", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support'`

**Comment by wongselent** [comment]
:+1:

**Comment by dmark** [comment]
LM 18.2 is just xenial under the hood. We just need a line added to the setup script(s) mapping Sonya to Xenial.

**Comment by dmark** [comment]
Interim solution: Grab the version specific install script you want, e.g.,

`https://deb.nodesource.com/setup_8.x`

Edit the script to add an additional `check_alt` line down around line 265, mapping "sonya" to "xenial". Run the script and install node:

    $ sudo -E bash deb/setup_8.x    
    $ sudo apt-get install -y nodejs

**Comment by dzift** [comment]
One could also use [nvm](https://github.com/creationix/nvm) or what I did was change my distro nickname just for the install.

**Comment by chrislea** [comment]
Hey folks. I'm running really busy today, but I'll get things set up (no pun intended) for Sonya ASAP. In the interim @dmark 's interim solution should work fine. Please stay tuned.

**Comment by chrislea** [comment]
Okay, I've made the needed changes so Sonya should now be supported directly from the `setup_X.x` scripts you can `curl` down from the repository. If anybody here could give me a sanity check that things are working, I'd appreciate it.

**Comment by dzift** [comment]
Sorry, I recently switched to Arch+XFCE. Maybe @dmark can verify.

**Comment by karlhaas** [comment]
@chrislea tested `curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -` with Mint 18.2 and it works. thx!

**Comment by chrislea** [comment]
Okay, good enough for me. Closing.

**Comment by stephanfriedrich** [comment]
hi actually,
i got an error with my clean linux mint 18.2 


repository 'https://deb.nodesource.com/node_6.x sonya Release' does not have a Release file.\nE: Fehlschlag beim Holen von https://deb.nodesource.com/node_6.x/dists/sonya/main/source/Sources  404  Not Found\nE: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.
