### ISSUE TITLE
My parrot linux distribution is not supported

### ISSUE THREAD

**Issue by brayands** [nodesource/distributions#475]

**Comment by MrRobotVPN** [comment]
I am having the same issue. Please support Parrot!

Setting up libav-tools (7:3.2.5-1) ...
Processing triggers for libc-bin (2.24-9) ...
┌─[mrrobotvpn@parrot]─[~/Python-2.7.13]
└──╼ $curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

## Installing the NodeSource Node.js v8.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://mirrordirector.archive.parrotsec.org/parrot stable InRelease
Reading package lists... Done

## Confirming "CyberGalleon" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/CyberGalleon/Release'

## Your distribution, identified as "CyberGalleon", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
@MrRobotVPN The setup scripts are included in this repository. If your Parrot Linux distro is based on a Debian or Ubuntu release, it should be very easy to add it as an alternate install. Just update the setup scripts as needed, test your changes, and issue a PR against the repository. If it looks good we'll merge it in for Parrot support. Thanks.
