### ISSUE TITLE
Request support for Sparky Linux

### ISSUE THREAD

**Issue by Ubulindy** [nodesource/distributions#476]
## Your distribution, identified as "Tyche", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support.

Thank you   :)

**Comment by n-makarin** [comment]
I have the same problem..

**Comment by igsu** [comment]
Hey @Ubulindy,

We, unfortunately, do not have the resources necessary to support and test the plethora of Linux releases in the wild, so we rely on community members such as yourself to get support on your favorite distributions.

I've added Sparky Linux to the list of requested releases in our README.md.

**Comment by igsu** [comment]
SparkyLinux 5.9 “Nibiru” is supported.
In case anyone is still interested in "Tyche" please let me know.
