### ISSUE TITLE
8.x setup script for Debian based systems

### ISSUE THREAD

**Issue by dmark** [nodesource/distributions#478]
The installation instructions refer to an install script for 8.x on Debian based systems, but that script does not appear to be in the source on github:

```curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -```

I don't see a `setup_8.x` in `deb/`.

**Comment by chrislea** [comment]
That's added as of https://github.com/nodesource/distributions/commit/a78ba038254363dee1baf4b5ca9ac553ecb451ee
