### ISSUE TITLE
Installation fail (404 release link)

### ISSUE THREAD

**Issue by gpeddler** [nodesource/distributions#483]
Installation failed during `curl -sL https://deb.nodesource.com/setup_7.x | bash -`

```
## Installing packages required for setup: apt-transport-https lsb-release...

+ apt-get install -y apt-transport-https lsb-release > /dev/null 2>&1

## Confirming "stretch" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_7.x/dists/stretch/Release'

## Your distribution, identified as "stretch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

The command '/bin/sh -c curl -sL https://deb.nodesource.com/setup_7.x | bash -' returned a non-zero code: 1
```

So, I found the release script site is closed. Please fix it quickly. I cannot release my services.
(404 Not found - https://deb.nodesource.com/node_7.x/dists/stretch/Release)

**Comment by SystemZ** [comment]
8.x seems to work with stretch

**Comment by chrislea** [comment]
We haven't built Node.js 7.x for stretch because it's only going to be supported for about another week, and may not even see another release in that time. You should move to 8.x ASAP.
