### ISSUE TITLE
node_7.x Stretch version in repository

### ISSUE THREAD

**Issue by gil13** [nodesource/distributions#485]
Im trying to install node_7.x in Debian 9 (nginx docker image) and here https://deb.nodesource.com/node_7.x/dists/ I can not find the stretch folder.

There are any issue with that or is the expected behaviour ?

Thanks

**Comment by gil13** [comment]
Any update ?

**Comment by chrislea** [comment]
Node.js 7.x is EOL as of today. You should use Node.js 8.x. Stretch is supported as usual for 8.x.
