### ISSUE TITLE
RHEL/CentOS packages don't update from node 6 to 8 properly (easy fix)

### ISSUE THREAD

**Issue by mikemaccana** [nodesource/distributions#486]
A RHEL/CentOS system with node 6 installed won't upgrade properly to node 8.

1. Install node 6 per https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora
2. Later, install node 8 per https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora

### What happens:

`yum -y install nodejs` still fetches the 6.x version

### What should happen

`yum -y install nodejs` should install node 8

### Fix

The scripts should add a `yum clean all` as the final step. After this,  `yum -y install nodejs` will install node 8

This has happened on each of our main app nodes so we're pretty confident it can be replicated easily.

**Comment by lkappeler** [comment]
Had to remove the `/etc/yum.repos.d/nodesource-el.repo` since the script is creating `/etc/yum.repos.d/nodesource-el6.repo`

**Comment by chrislea** [comment]
Thanks for bringing this up and pointing out the fix @lkappeler . I'll need to look into a better fix for this going forward as you shouldn't have to remove that `.repo` file as an end user. I'm at re:Invent all week, but I'll try look at it as soon as I can (which will probably be early next week).

**Comment by IdanAdar** [comment]
Was this closed because it's fixed? Happened to me in CentOS...

**Comment by tedeh** [comment]
It did not work for me either. The last command I tried was `rm -rf /var/cache/yum` as root and that seemed to have done the trick. This was after doing this: (I can't remember the exact order or which commands were significant):

```sh
/bin/rm -rf /var/cache/yum
/usr/bin/yum remove -y nodejs
/bin/rm /etc/yum.repos.d/nodesource*
/usr/bin/yum clean all
/usr/bin/curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
```

**Comment by vkotovv** [comment]
@chrislea @IdanAdar I think this issue should be reopened (don't know why it was closed). Happened to me when upgrading from Nodejs 7 to 8 on Centos 7.

**Comment by vkotovv** [comment]
@tedeh You you only need `sudo yum clean all` as a workaround, as was stated by @mikemaccana in his original message.

**Comment by tedeh** [comment]
@vkotovv Running `sudo yum clean all` was not sufficient unfortunately.

**Comment by bbnplace** [comment]
simply running `yum remove -y nodejs` was sufficient in my case.

**Comment by kyyung** [comment]
For me, it works after using "/bin/rm /etc/yum.repos.d/nodesource*"

**Comment by JONDJ** [comment]
The way of @tedeh works for me

**Comment by jordanj-daycos** [comment]
Even a year and a half after this ticket was opened, I was having this issue as well. Just running `rm -rf /var/cache/yum` as @tedeh suggested worked for me.

**Comment by shreya2394** [comment]
I am also facing same issue for latest version of node in CentOS, The latest version for particular user (In my case, osboxes) is v0.10.30
Whereas for root user, it is working fine, v10.15.0
I am not able to install latest version of node in osboxes user

**Comment by pradipshenolkar** [comment]
> It did not work for me either. The last command I tried was `rm -rf /var/cache/yum` as root and that seemed to have done the trick. This was after doing this: (I can't remember the exact order or which commands were significant):
> 
> ```shell
> /bin/rm -rf /var/cache/yum
> /usr/bin/yum remove -y nodejs
> /bin/rm /etc/yum.repos.d/nodesource*
> /usr/bin/yum clean all
> /usr/bin/curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
> ```

This solved my issue.

**Comment by shreya2394** [comment]
This helped with my issue. Thank you, Pradip.

**Comment by blakewenloe** [comment]
tedeh's fix worked for me as well

**Comment by LewisJohnson** [comment]
@tedeh My hero!

**Comment by vkotovv** [comment]
@chrislea Looks like this issue is not resolved.. I think this issue should be reopened (don't know why it was closed)

**Comment by sviguier** [comment]
@tedeh thanks for the tip, got stung trying to install node 8.x and still ending-up getting old 4.x, your instructions saved the day.

**Comment by sham132** [comment]
Thanks for the information,

Regards
Ehtasham ul haq

**Comment by hasan-abbas86** [comment]
Unfortunately, none of the above worked for me to upgrade nodejs from 6.x to 12.x... I tried following and it worked for me on Centos 7:
`curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
sudo yum install yarn`

**Comment by EndiHariadi43** [comment]
yum remove -y nodejs not work for me
but this is work :
/usr/bin/curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -

then use : 

rm -rf /var/cache/yum/x86_64/7/nodesource
