### ISSUE TITLE
Distro not supported?

### ISSUE THREAD

**Issue by pmralbuquerque** [nodesource/distributions#487]
Using MX-16, after running setup, got this message:

## Confirming "Metamorphosis" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/Metamorphosis/Release'

**Comment by matteotanca** [comment]
For me that worked in Ubuntu 17.10 :
curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -x -

**Comment by chrislea** [comment]
I'm assuming MX-16 is a Debian derivative. Please issue a PR against our [setup scripts](https://github.com/nodesource/distributions/tree/master/deb/src) to alias your distro correctly and if it looks good we'll merge it. Thanks.
