### ISSUE TITLE
Ubuntu 17.04

### ISSUE THREAD

**Issue by josherquiaga** [nodesource/distributions#488]
Curious if support for 17.04 is in the works or not.

**Comment by josherquiaga** [comment]
As an update, I see the zesty packages and can download them with wget and install with dpkg - is it just the setup script that needs to be updated?

**Comment by chrislea** [comment]
Zesty is supported for versions 4.x, 6.x and 8.x of Node. The setup script should work just fine. If it's not, please re-open this and show the full output of the relevant setup script.
