### ISSUE TITLE
support for cloudlinux-release-6-6.6.0.x86_64

### ISSUE THREAD

**Issue by u007** [nodesource/distributions#49]
hi,

can you help to add in 
cloudlinux-release-6-6.6.0.x86_64 ?
its part of centos 6.6 / redhat linux equivalent.

thanks

**Comment by rvagg** [comment]
hi @u007, what we need is a contribution on the translation of the OS identifier to the EL/FC release path. If you look in https://github.com/nodesource/distributions/blob/master/rpm/setup between the two lines that have `#-check-distro-#`, this needs to work to produce `DIST_TYPE`, `DIST_VERSION`, and `DIST_ARCH` for a given server. In the same place there is a test script that extracts this section and tests against various known version strings: https://github.com/nodesource/distributions/blob/master/rpm/test.sh

What you should do is fork this repo, edit `rpm/setup` to make it work, put in at least one version string in `rpm/test.sh` to ensure it works as expected (preferably more if you can get them from real running servers). Submit a pull request when you're done and we can merge it in.

Unfortunately we don't have the people resources to support all of these variants ourselves so it's helpful to have contributions from people actually using them.

**Comment by wrender** [comment]
I've added a pull request to add support for CloudLinux 6.6 x86_64  (Latest version from CloudLinux).  Hope it is good enough to merge in.

Thanks,

**Comment by wblankenship** [comment]
<:heart:>
Thanks @wrender, you rock!
</:heart:>

**Comment by u007** [comment]
thanks @wrender :)
