### ISSUE TITLE
Debain Stretch is missing 8.1.3

### ISSUE THREAD

**Issue by phristov** [nodesource/distributions#491]
Debian Stretch is missing 8.1.3 release. Jessie, Sid and all Ubuntu releases were updated on June 29th.

https://deb.nodesource.com/node_8.x/dists/

**Comment by chrislea** [comment]
Thanks for pointing this out. I'm getting on an airplane shortly but I'll try and get this fixed up ASAP once I'm home.

**Comment by ccoenen** [comment]
stretch can install 8.1.4 - does this obsolete this issue or do you need specifically 8.1.3 @phristov?

**Comment by chrislea** [comment]
Sorry, yes, this should be closed. **Nobody** should be running 8.1.3 as 8.1.4 fixes a non-trivial security issue. That's why I didn't rebuild 8.1.3 for Stretch. So basically, install 8.1.4 instead please.
