### ISSUE TITLE
Ubuntu Precise missing 6.11.1 (and 4.8.4)

### ISSUE THREAD

**Issue by sudowork** [nodesource/distributions#494]
I realize that Ubuntu 12.04 Precise is already out of LTS, but I noticed that the recent [security release](https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/) is not present.

Are there plans to add 6.11.1 to the repo?

If there aren't plans to continue support for 12.04, should the support section in the [nodejs.org documentation](https://github.com/nodejs/nodejs.org/blame/4916a9ee2dfd1acbbcfa199f6c337dae92da6460/locale/en/download/package-manager.md#L72) be updated?

**Comment by chrislea** [comment]
We are no longer making builds for Precise as it's reached EOL. You are correct that we need to update the docs, I'll try and get to that ASAP. Thanks for pointing it out.
