### ISSUE TITLE
Node 8.2?

### ISSUE THREAD

**Issue by kachkaev** [nodesource/distributions#498]
Hi guys,

Just wondering what's the plan for updating node to 8.2 in the deb packages. The PR was merged and the release went out yesterday: https://github.com/nodejs/node/pull/13744.

I'm still seeing `nodejs is already the newest version (8.1.4-2nodesource1~xenial1)` on Ubuntu 16.04 no matter how hard I'm trying to `apt update` :–)

**Comment by rvagg** [comment]
It's coming, the minimum compiler requirements were bumped so @chrislea has been adapting to the new build requirements. The .rpm's are done and the .deb's should be ready within a matter of hours I believe. Keep an eye on the repo and they'll show up!

**Comment by kachkaev** [comment]
Cool! It'd be great if you dropped a line here once all's done – I'll check.

**Comment by rvagg** [comment]
I'm pretty sure it's been submitted through the automatic build process and now the relevant people are :zzz: so you'll probably see it before they wake up if you keep checking for yourself.
