### ISSUE TITLE
debian sid, NODE_PATH and npm

### ISSUE THREAD

**Issue by Ivan-SB** [nodesource/distributions#50]
It seems that your package doesn't add /usr/local/... to NODE_PATH but npm install package there.
It could be a problem of debian official packages as well. I'll check shortly.

thanks

**Comment by rvagg** [comment]
I think it was at Node 0.8 that a global NODE_PATH was deprecated and no longer recommended. I don't think we'll be adding it back again. If you _really_ want globals to be picked up by packages then you're best to manage NODE_PATH yourself.

**Comment by Ivan-SB** [comment]
But this way npm -g simply doesn't work.

Where npm -g installs stuff and where nodejs search them should be the same or having -g is misleading. No matter if NODE_PATH is deprecated upstream: -g doesn't work with the configuration npm comes with.

thanks

**Comment by rvagg** [comment]
Generally `-g` is simply for installing runnable applications, like npm itself, a shared search path across all applications is pretty dangerous given the way Node works. If you really need shared things, make use of `npm link` which can be useful during development.

**Comment by Ivan-SB** [comment]
Thanks for the suggestion, still having an option for installing stuff globally that install them in a place where nodejs don't look is *at least* misleading.
I grep through nodejs/npm code and it did't seem obvious where those path are set, but at least they should agree.

thanks

**Comment by rvagg** [comment]
if this is a documentation problem, perhaps file an issue @ http://github.com/npm/npm
