### ISSUE TITLE
Apt update error (Writing more data than expected)

### ISSUE THREAD

**Issue by alexwhitman** [nodesource/distributions#500]
Running `sudo apt update` on Ubuntu 16.04 LTS is giving the following error:

```
E: Failed to fetch https://deb.nodesource.com/node_8.x/dists/xenial/main/source/Sources  Writing more data than expected (761 > 759)
```

**Comment by alexwhitman** [comment]
Worked around by running `sudo apt -o Acquire::https::No-Cache=True -o Acquire::http::No-Cache=True update` instead.  Looks like some caching somewhere went wrong.

**Comment by chrislea** [comment]
I **just** pushed out 8.2.1 updates so yeah, almost certainly a cache catch-up thing.
