### ISSUE TITLE
kali linux jessie not supported for nodejs

### ISSUE THREAD

**Issue by snjai** [nodesource/distributions#502]
when i went to install nodejs by entering the commands writtern on  "https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions" it says that "Your distribution, identified as "jessie", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support"  so i want my operating  system  to be supported fot nodejs
thankyou

**Comment by chrislea** [comment]
Jessie should be supported. Can you please run the setup script with the `-x` flag such as:
```
curl -sL https://deb.nodesource.com/setup_6.x | bash -x -
```
and show us the complete output?

**Comment by zdzdz** [comment]
I have a problem too. I'm with Kali rolling (Debian Jessie).
Until recently I used `deb https://deb.nodesource.com/node_7.x jessie main
deb-src https://deb.nodesource.com/node_7.x jessie main` 
in nodesource.list to update. 
But this suddenly stopped working. I tried "https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions" instructions for Debian.
`curl -sL https://deb.nodesource.com/setup_8.x | bash -`
does nothing. I mean there is no output when run the command.
After that I run
`sudo apt-get install -y nodejs`
and what it is being installed is "https://pkg.kali.org/pkg/nodejs"  **nodejs 4.8.4~dfsg** which I don't know what is. After I install node command doesn't work.
Any suggestions how to install nodejs v8 on Kali rolling?

**Comment by chrislea** [comment]
According to here:

https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L258-L259

Kali rolling should be supported. We really need to see the output of that script with the `-x` flag as I mentioned above. Something like this should work:
```
% wget -q -O setup_8.x https://deb.nodesource.com/setup_8.x
% sudo /bin/bash -x ./setup_8.x
```

**Comment by spooknick** [comment]
Facing the same problem, here's my output:

```
prompt:~$ sudo /bin/bash -x ./setup_6.x
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ SCRSUFFIX=_6.x
+ NODENAME='Node.js v6.x'
+ NODEREPO=node_6.x
+ NODEPKG=nodejs
+ test -t 1
++ which tput
++ tput colors
+ ncolors=256
+ test -n 256
+ test 256 -ge 8
++ tput cols
+ termcols=120
++ tput bold
+ bold=''
++ tput smul
+ underline=''
++ tput smso
+ standout=''
++ tput sgr0
+ normal=''
++ tput setaf 0
+ black=''
++ tput setaf 1
+ red=''
++ tput setaf 2
+ green=''
++ tput setaf 3
+ yellow=''
++ tput setaf 4
+ blue=''
++ tput setaf 5
+ magenta=''
++ tput setaf 6
+ cyan=''
++ tput setaf 7
+ white=''
+ setup
+ script_deprecation_warning
+ '[' X_6.x == X ']'
+ print_status 'Installing the NodeSource Node.js v6.x repo...'
+ echo

+ echo '## Installing the NodeSource Node.js v6.x repo...'
## Installing the NodeSource Node.js v6.x repo...
+ echo

++ uname -m
++ grep -Eq '^armv6'
+ PRE_INSTALL_PKGS=
+ '[' '!' -e /usr/lib/apt/methods/https ']'
+ '[' '!' -x /usr/bin/lsb_release ']'
+ '[' '!' -x /usr/bin/curl ']'
+ print_status 'Populating apt-get cache...'
+ echo

+ echo '## Populating apt-get cache...'
## Populating apt-get cache...
+ echo

+ exec_cmd 'apt-get update'
+ exec_cmd_nobail 'apt-get update'
+ echo '+ apt-get update'
+ apt-get update
+ bash -c 'apt-get update'
Ign http://repo.mongodb.org wheezy/mongodb-org/3.0 InRelease
Get:2 http://repo.mongodb.org wheezy/mongodb-org/3.0 Release.gpg [455 B]
Hit http://repo.mongodb.org wheezy/mongodb-org/3.0 Release
Get:3 http://repo.saltstack.com jessie InRelease [2,837 B]
Hit http://repo.mongodb.org wheezy/mongodb-org/3.0/main amd64 Packages
Ign http://repo.mongodb.org wheezy/mongodb-org/3.0/main Translation-en_US
Ign http://repo.mongodb.org wheezy/mongodb-org/3.0/main Translation-en
Hit http://repo.saltstack.com jessie/main amd64 Packages
Ign http://repo.saltstack.com jessie/main Translation-en_US
Ign http://repo.saltstack.com jessie/main Translation-en
Fetched 9,384 B in 8s (1,054 B/s)
Reading package lists... Done
+ '[' X '!=' X ']'
++ lsb_release -d
++ grep 'Ubuntu .*development'
++ echo 1
+ IS_PRERELEASE=1
+ [[ 1 -eq 0 ]]
++ lsb_release -c -s
+ DISTRO=jessie
+ check_alt Kali sana Debian jessie
+ '[' Xjessie == Xsana ']'
+ check_alt Kali kali-rolling Debian jessie
+ '[' Xjessie == Xkali-rolling ']'
+ check_alt 'Linux Mint' maya Ubuntu precise
+ '[' Xjessie == Xmaya ']'
+ check_alt 'Linux Mint' qiana Ubuntu trusty
+ '[' Xjessie == Xqiana ']'
+ check_alt 'Linux Mint' rafaela Ubuntu trusty
+ '[' Xjessie == Xrafaela ']'
+ check_alt 'Linux Mint' rebecca Ubuntu trusty
+ '[' Xjessie == Xrebecca ']'
+ check_alt 'Linux Mint' rosa Ubuntu trusty
+ '[' Xjessie == Xrosa ']'
+ check_alt 'Linux Mint' sarah Ubuntu xenial
+ '[' Xjessie == Xsarah ']'
+ check_alt 'Linux Mint' serena Ubuntu xenial
+ '[' Xjessie == Xserena ']'
+ check_alt 'Linux Mint' sonya Ubuntu xenial
+ '[' Xjessie == Xsonya ']'
+ check_alt LMDE betsy Debian jessie
+ '[' Xjessie == Xbetsy ']'
+ check_alt elementaryOS luna Ubuntu precise
+ '[' Xjessie == Xluna ']'
+ check_alt elementaryOS freya Ubuntu trusty
+ '[' Xjessie == Xfreya ']'
+ check_alt elementaryOS loki Ubuntu xenial
+ '[' Xjessie == Xloki ']'
+ check_alt Trisquel toutatis Ubuntu precise
+ '[' Xjessie == Xtoutatis ']'
+ check_alt Trisquel belenos Ubuntu trusty
+ '[' Xjessie == Xbelenos ']'
+ check_alt BOSS anokha Debian wheezy
+ '[' Xjessie == Xanokha ']'
+ check_alt bunsenlabs bunsen-hydrogen Debian jessie
+ '[' Xjessie == Xbunsen-hydrogen ']'
+ check_alt Tanglu chromodoris Debian jessie
+ '[' Xjessie == Xchromodoris ']'
+ '[' Xjessie == Xdebian ']'
+ print_status 'Confirming "jessie" is supported...'
+ echo

+ echo '## Confirming "jessie" is supported...'
## Confirming "jessie" is supported...
+ echo

+ '[' -x /usr/bin/curl ']'
+ exec_cmd_nobail 'curl -sLf -o /dev/null '\''https://deb.nodesource.com/node_6.x/dists/jessie/Release'\'''
+ echo '+ curl -sLf -o /dev/null '\''https://deb.nodesource.com/node_6.x/dists/jessie/Release'\'''
+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/jessie/Release'
+ bash -c 'curl -sLf -o /dev/null '\''https://deb.nodesource.com/node_6.x/dists/jessie/Release'\'''
+ RC=7
+ [[ 7 != 0 ]]
+ print_status 'Your distribution, identified as "jessie", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support'
+ echo

+ echo '## Your distribution, identified as "jessie", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support'
## Your distribution, identified as "jessie", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
+ echo

+ exit 1
```

**Comment by zdzdz** [comment]
`+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ SCRSUFFIX=_8.x
+ NODENAME='Node.js v8.x'
+ NODEREPO=node_8.x
+ NODEPKG=nodejs
+ test -t 1
++ which tput
++ tput colors
+ ncolors=256
+ test -n 256
+ test 256 -ge 8
++ tput cols
+ termcols=90
++ tput bold
+ bold=''
++ tput smul
+ underline=''
++ tput smso
+ standout=''
++ tput sgr0
+ normal=''
++ tput setaf 0
+ black=''
++ tput setaf 1
+ red=''
++ tput setaf 2
+ green=''
++ tput setaf 3
+ yellow=''
++ tput setaf 4
+ blue=''
++ tput setaf 5
+ magenta=''
++ tput setaf 6
+ cyan=''
++ tput setaf 7
+ white=''
+ setup
+ script_deprecation_warning
+ '[' X_8.x == X ']'
+ print_status 'Installing the NodeSource Node.js v8.x repo...'
+ echo

+ echo '## Installing the NodeSource Node.js v8.x repo...'
## Installing the NodeSource Node.js v8.x repo...
+ echo

++ uname -m
++ grep -Eq '^armv6'
+ PRE_INSTALL_PKGS=
+ '[' '!' -e /usr/lib/apt/methods/https ']'
+ '[' '!' -x /usr/bin/lsb_release ']'
+ '[' '!' -x /usr/bin/curl ']'
+ print_status 'Populating apt-get cache...'
+ echo

+ echo '## Populating apt-get cache...'
## Populating apt-get cache...
+ echo

+ exec_cmd 'apt-get update'
+ exec_cmd_nobail 'apt-get update'
+ echo '+ apt-get update'
+ apt-get update
+ bash -c 'apt-get update'
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://ftp.debian.org/debian wheezy-backports InRelease                            
Hit:3 http://download.virtualbox.org/virtualbox/debian jessie InRelease                  
Hit:4 https://packages.microsoft.com/repos/vscode stable InRelease                       
Hit:5 https://repo.skype.com/deb stable InRelease                                        
Hit:6 http://dl.google.com/linux/chrome/deb stable Release                               
Hit:7 http://mirrors.netix.net/kali kali-rolling InRelease              
Reading package lists... Done                     
+ '[' X '!=' X ']'
++ lsb_release -d
++ grep 'Ubuntu .*development'
++ echo 1
+ IS_PRERELEASE=1
+ [[ 1 -eq 0 ]]
++ lsb_release -c -s
+ DISTRO=kali-rolling
+ check_alt Kali sana Debian jessie
+ '[' Xkali-rolling == Xsana ']'
+ check_alt Kali kali-rolling Debian jessie
+ '[' Xkali-rolling == Xkali-rolling ']'
+ echo

+ echo '## You seem to be using Kali version kali-rolling.'
## You seem to be using Kali version kali-rolling.
+ echo '## This maps to Debian "jessie"... Adjusting for you...'
## This maps to Debian "jessie"... Adjusting for you...
+ DISTRO=jessie
+ check_alt 'Linux Mint' maya Ubuntu precise
+ '[' Xjessie == Xmaya ']'
+ check_alt 'Linux Mint' qiana Ubuntu trusty
+ '[' Xjessie == Xqiana ']'
+ check_alt 'Linux Mint' rafaela Ubuntu trusty
+ '[' Xjessie == Xrafaela ']'
+ check_alt 'Linux Mint' rebecca Ubuntu trusty
+ '[' Xjessie == Xrebecca ']'
+ check_alt 'Linux Mint' rosa Ubuntu trusty
+ '[' Xjessie == Xrosa ']'
+ check_alt 'Linux Mint' sarah Ubuntu xenial
+ '[' Xjessie == Xsarah ']'
+ check_alt 'Linux Mint' serena Ubuntu xenial
+ '[' Xjessie == Xserena ']'
+ check_alt 'Linux Mint' sonya Ubuntu xenial
+ '[' Xjessie == Xsonya ']'
+ check_alt LMDE betsy Debian jessie
+ '[' Xjessie == Xbetsy ']'
+ check_alt elementaryOS luna Ubuntu precise
+ '[' Xjessie == Xluna ']'
+ check_alt elementaryOS freya Ubuntu trusty
+ '[' Xjessie == Xfreya ']'
+ check_alt elementaryOS loki Ubuntu xenial
+ '[' Xjessie == Xloki ']'
+ check_alt Trisquel toutatis Ubuntu precise
+ '[' Xjessie == Xtoutatis ']'
+ check_alt Trisquel belenos Ubuntu trusty
+ '[' Xjessie == Xbelenos ']'
+ check_alt BOSS anokha Debian wheezy
+ '[' Xjessie == Xanokha ']'
+ check_alt bunsenlabs bunsen-hydrogen Debian jessie
+ '[' Xjessie == Xbunsen-hydrogen ']'
+ check_alt Tanglu chromodoris Debian jessie
+ '[' Xjessie == Xchromodoris ']'
+ '[' Xjessie == Xdebian ']'
+ print_status 'Confirming "jessie" is supported...'
+ echo

+ echo '## Confirming "jessie" is supported...'
## Confirming "jessie" is supported...
+ echo

+ '[' -x /usr/bin/curl ']'
+ exec_cmd_nobail 'curl -sLf -o /dev/null '\''https://deb.nodesource.com/node_8.x/dists/jessie/Release'\'''
+ echo '+ curl -sLf -o /dev/null '\''https://deb.nodesource.com/node_8.x/dists/jessie/Release'\'''
+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/jessie/Release'
+ bash -c 'curl -sLf -o /dev/null '\''https://deb.nodesource.com/node_8.x/dists/jessie/Release'\'''
+ RC=6
+ [[ 6 != 0 ]]
+ print_status 'Your distribution, identified as "jessie", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support'
+ echo

+ echo '## Your distribution, identified as "jessie", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support'
## Your distribution, identified as "jessie", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
+ echo

+ exit 1
`

**Comment by ishanvaid** [comment]
In Order to resolve this Grab the version specific install script you want, e.g.,

https://deb.nodesource.com/setup_8.x

Edit the script to add an additional check_alt line down around line 265, mapping "sonya" to "xenial". Run the script and install node:

$ sudo -E bash deb/setup_8.x    
$ sudo apt-get install -y nodejs

**Comment by mayankmetha** [comment]
version 8 onwards work well with kali linux

**Comment by chrislea** [comment]
This has been fixed for a while, closing.
