### ISSUE TITLE
centos-release-7-2.1511.el7.centos.2.10.x86_64", is not currently supported

### ISSUE THREAD

**Issue by fuckohyes** [nodesource/distributions#503]
centos-release-7-2.1511.el7.centos.2.10.x86_64", is not currently supported

**Comment by chrislea** [comment]
Please post the full output of the relevant setup script with the `-x` flag enabled to help us see what's going on. For example, assuming you are trying to install the newest 6.x release:
```
curl -sL https://rpm.nodesource.com/setup_6.x | bash -
```

**Comment by johanneswegele** [comment]
Hi, i got the same problem, an the commandline looks like this: 

$ curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -

## Installing the NodeSource Node.js 8.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Your distribution, identified as "centos-release-7-2.1511.el7.centos.2.10.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by johanneswegele** [comment]
When trying to install, I get: 

`$ sudo yum -y install nodejs                                
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.iweb.ca
 * epel: epel.besthosting.ua
 * extras: centos.mirror.iweb.ca
 * updates: centos.mirror.iweb.ca
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 1:6.11.1-1.el7 will be installed
--> Processing Dependency: npm = 1:3.10.10-1.6.11.1.1.el7 for package: 1:nodejs-6.11.1-1.el7.x86_64
--> Processing Dependency: libuv >= 1:1.9.1 for package: 1:nodejs-6.11.1-1.el7.x86_64
--> Processing Dependency: http-parser >= 2.7.0 for package: 1:nodejs-6.11.1-1.el7.x86_64
--> Processing Dependency: libuv.so.1()(64bit) for package: 1:nodejs-6.11.1-1.el7.x86_64
--> Processing Dependency: libicuuc.so.50()(64bit) for package: 1:nodejs-6.11.1-1.el7.x86_64
--> Processing Dependency: libicui18n.so.50()(64bit) for package: 1:nodejs-6.11.1-1.el7.x86_64
--> Processing Dependency: libicudata.so.50()(64bit) for package: 1:nodejs-6.11.1-1.el7.x86_64
--> Processing Dependency: libhttp_parser.so.2()(64bit) for package: 1:nodejs-6.11.1-1.el7.x86_64
--> Running transaction check
---> Package libicu.x86_64 0:50.1.2-15.el7 will be installed
---> Package libuv.x86_64 1:1.10.2-1.el7 will be installed
---> Package nodejs.x86_64 1:6.11.1-1.el7 will be installed
--> Processing Dependency: http-parser >= 2.7.0 for package: 1:nodejs-6.11.1-1.el7.x86_64
--> Processing Dependency: libhttp_parser.so.2()(64bit) for package: 1:nodejs-6.11.1-1.el7.x86_64
---> Package npm.x86_64 1:3.10.10-1.6.11.1.1.el7 will be installed
--> Finished Dependency Resolution
Error: Package: 1:nodejs-6.11.1-1.el7.x86_64 (epel)
           Requires: libhttp_parser.so.2()(64bit)
Error: Package: 1:nodejs-6.11.1-1.el7.x86_64 (epel)
           Requires: http-parser >= 2.7.0
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
`

**Comment by johanneswegele** [comment]
With --skip-broken I get: 


```
Packages skipped because of dependency problems:
    libicu-50.1.2-15.el7.x86_64 from base
    1:libuv-1.10.2-1.el7.x86_64 from epel
    1:nodejs-6.11.1-1.el7.x86_64 from epel
    1:npm-3.10.10-1.6.11.1.1.el7.x86_64 from epel

```

However the installation is not done, see here: 

```
$ node
-bash: node: command not found
```
and
```
$ nodejs
-bash: nodejs: command not found
```

**Comment by xhb3909** [comment]
you should use https://rpm.nodesource.com/setup_7.x replace https://rpm.nodesource.com/setup_6.x，I try do that  and success .

**Comment by chrislea** [comment]
Nobody should be installing Node v7.x anymore, it's EOL. @johanneswegele the node package that your system is trying to install is from EPEL, not our repository. We need to see the full output of our installer script run with the `-x` flag as noted above to try and tell what's going on.

**Comment by johanneswegele** [comment]
Thanks a lot for your help!
Today I just ran 

```
$ curl --location https://rpm.nodesource.com/setup_8.x
$ sudo bash-
$ sudo yum -y install nodejs
```

and it worked: 

```
$ node
> a=0
0
> b=4
4
> c=3
3
> d=a*b+a
0
> d=c*b+a
12
> .exit

```

The output with the dependencies is: 

```
Dependencies Resolved
=====================================================================================
 Package           Arch         Version                          Repository     Size
=====================================================================================
Installing:
 nodejs            x86_64       1:6.11.1-1.el7                   epel          4.5 M
Installing for dependencies:
 http-parser       x86_64       2.7.1-5.el7_4                    updates        28 k
 libicu            x86_64       50.1.2-15.el7                    base          6.9 M
 libuv             x86_64       1:1.10.2-1.el7                   epel          109 k
 npm               x86_64       1:3.10.10-1.6.11.1.1.el7         epel          2.5 M

Transaction Summary
=====================================================================================
Install  1 Package (+4 Dependent packages)

Total download size: 14 M
Installed size: 50 M
Downloading packages:
(1/5): http-parser-2.7.1-5.el7_4.x86_64.rpm                   |  28 kB  00:00:03
(2/5): libuv-1.10.2-1.el7.x86_64.rpm                          | 109 kB  00:00:05
(3/5): npm-3.10.10-1.6.11.1.1.el7.x86_64.rpm                  | 2.5 MB  00:00:10
(4/5): libicu-50.1.2-15.el7.x86_64.rpm                        | 6.9 MB  00:00:14
(5/5): nodejs-6.11.1-1.el7.x86_64.rpm                         | 4.5 MB  00:00:18
-------------------------------------------------------------------------------------
Total                                                   729 kB/s |  14 MB  00:19
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : http-parser-2.7.1-5.el7_4.x86_64                                  1/5
  Installing : libicu-50.1.2-15.el7.x86_64                                       2/5
  Installing : 1:libuv-1.10.2-1.el7.x86_64                                       3/5
  Installing : 1:npm-3.10.10-1.6.11.1.1.el7.x86_64                               4/5
  Installing : 1:nodejs-6.11.1-1.el7.x86_64                                      5/5
  Verifying  : 1:libuv-1.10.2-1.el7.x86_64                                       1/5
  Verifying  : libicu-50.1.2-15.el7.x86_64                                       2/5
  Verifying  : 1:nodejs-6.11.1-1.el7.x86_64                                      3/5
  Verifying  : http-parser-2.7.1-5.el7_4.x86_64                                  4/5
  Verifying  : 1:npm-3.10.10-1.6.11.1.1.el7.x86_64                               5/5

Installed:
  nodejs.x86_64 1:6.11.1-1.el7

Dependency Installed:
  http-parser.x86_64 0:2.7.1-5.el7_4       libicu.x86_64 0:50.1.2-15.el7
  libuv.x86_64 1:1.10.2-1.el7              npm.x86_64 1:3.10.10-1.6.11.1.1.el7

Complete!

```

**Comment by juwito** [comment]
I stuck with the same message 

"## Your distribution, identified as "centos-release-7-2.1511.el7.centos.2.10.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support"

After googling I found this thread
https://serverfault.com/questions/611791/centos-7-cant-yum-install-npm

I use EPEL repo and succeed, but the nodejs version was v6.11.3 and NPM was v3.10.10. Is there any way to upgrade it to v8

**Comment by johanneswegele** [comment]
Thank you juwito,

Mit freundlichen Grüßen / Best regards

Johannes Wegele
BOSCH Group
TT/PJ-EIS-T-Lol

Tel. +49 6441 418-2472

Von: juwito [mailto:notifications@github.com]
Gesendet: Montag, 20. November 2017 07:16
An: nodesource/distributions <distributions@noreply.github.com>
Cc: Wegele Johannes (TT/PJ-EIS-T-Lol) <Johannes.Wegele@de.bosch.com>; Mention <mention@noreply.github.com>
Betreff: Re: [nodesource/distributions] centos-release-7-2.1511.el7.centos.2.10.x86_64", is not currently supported (#503)


I stuck with the same message

"## Your distribution, identified as "centos-release-7-2.1511.el7.centos.2.10.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support"

After googling I found this thread
https://serverfault.com/questions/611791/centos-7-cant-yum-install-npm

I use EPEL repo and succeed, but the nodejs version was v6.11.3 and NPM was v3.10.10. Is there any way to upgrade it to v8
