### ISSUE TITLE
Update failed from Node.js 8.1.0 to Node.js 8.2.1  on Centos 7 (repodata/repomd.xml or multiple errors)

### ISSUE THREAD

**Issue by christalk** [nodesource/distributions#506]
Hello, 

I don't know what to do. 
Here is the issue 

Update failed from Node.js 8.1.0 to Node.js 8.2.1  on Centos 7 
"http://..../CentOS/7/updates/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 504 - Gateway Timeout"

My environment: 
CentOS Linux release 7.3.1611 (Core)
node -> v8.1.2
npm -> 5.0.3

previously
upgrade 7.10 to 8.1.0 -> OK  #465
update 7.9 to 7.10 -> OK  #459
install 7.9 on Centos -> OK  #446

Now, the same command failed
$sudo yum update
nodejs-8.2.1-1nodesource.el7.c FAILED                                          
https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodejs-8.2.1-1nodesource.el7.centos.x86_64.rpm: [Errno -1] 
-> package does not match intended download
I already tried  : 
sudo yum --enablerepo=nodesource clean metadata
sudo yum clean all
yum repolist

$ sudo yum repolist

 fastestmirror
http://..../CentOS/7/base/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 504 - Gateway Timeout
try another 
http://..../CentOS/7/base/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 504 - Gateway Timeout
try another 
http://..../CentOS/7/updates/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 504 - Gateway Timeout
id                                                                                                 name                                                                                                 statut
base/7/x86_64                                                                  CentOS-7 - Base                                                                                                 0
nodesource/x86_64                                                              Node.js Packages for Enterprise Linux 7 - x86_64                                                               33
updates/7/x86_64                                                               CentOS-7 - Updates                                                                                              0
repolist: 33
$

list all
ll /etc/yum.repos.d
total 40
-rw-------  1 root root 1817  7 juil. 12:09 CentOS-Base.repo
-rw-r--r--. 1 root root 1309 29 nov.   2016 CentOS-CR.repo
-rw-r--r--. 1 root root  649 29 nov.   2016 CentOS-Debuginfo.repo
-rw-r--r--. 1 root root  314 29 nov.   2016 CentOS-fasttrack.repo
-rw-r--r--. 1 root root  630 29 nov.   2016 CentOS-Media.repo
-rw-r--r--. 1 root root 1331 29 nov.   2016 CentOS-Sources.repo
-rw-r--r--. 1 root root 2893 29 nov.   2016 CentOS-Vault.repo
-rw-r--r--  1 root root  472 30 mai   20:34 nodesource-el7.repo
-rw-------  1 root root  472 12 juin  11:07 nodesource-el7.repo.SAVE
drwxr-xr-x. 2 root root 4096  6 fÃ©vr. 15:40 sav
$

See what nodesource* contain :
$ cat nodesource-el7.repo
[nodesource]
name=Node.js Packages for Enterprise Linux 7 - $basearch
baseurl=https://rpm.nodesource.com/pub_8.x/el/7/$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL

[nodesource-source]
name=Node.js for Enterprise Linux 7 - $basearch - Source
baseurl=https://rpm.nodesource.com/pub_8.x/el/7/SRPMS
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
gpgcheck=1

$ sudo cat nodesource-el7.repo.SAVE
[nodesource]
name=Node.js Packages for Enterprise Linux 7 - $basearch
baseurl=https://rpm.nodesource.com/pub_7.x/el/7/$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL

[nodesource-source]
name=Node.js for Enterprise Linux 7 - $basearch - Source
baseurl=https://rpm.nodesource.com/pub_7.x/el/7/SRPMS
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
gpgcheck=1
$

I tried another way, but I have to run ..."yum install -y nodejs"

$ sudo curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -
## Inspecting system...
+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m
## Confirming "el7-x86_64" is supported...
+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'
## Downloading release setup RPM...
+ mktemp
+ curl -sL -o '/tmp/tmp.MZiUNYcYq3' 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'
## Installing release setup RPM...
+ rpm -i --nosignature --force '/tmp/tmp.MZiUNYcYq3'
## Cleaning up...
+ rm -f '/tmp/tmp.MZiUNYcYq3'
## Checking for existing installations...
+ rpm -qa 'node|npm' | grep -v nodesource
##   `yum install -y gcc-c++ make`
=============================================================================================

$ sudo yum install -y gcc-c++ make
Modules complÃ©mentaires chargÃ©sÂ : fastestmirror
http://..../CentOS/7/base/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 504 - Gateway Timeout
try another..

 One of the configured repositories failed (CentOS-7 - Base),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=base ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable base
        or
            subscription-manager repos --disable=base

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=base.skip_if_unavailable=true

failure: repodata/repomd.xml from base: [Errno 256] No more mirrors to try.
http://..../CentOS/7/base/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 504 - Gateway Timeout
$
yum-config-manager not installed
==================================================================================
I tried another way 
% curl -RLO https://rpm.nodesource.com/setup_8.x
% chmod 755 setup_8.x
% sudo ./setup_8.x -x

[cavril-adc@VVD-CHAT DEPOSIT]$ sudo ./setup_8.x -x

## Inspecting system...
+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m
## Confirming "el7-x86_64" is supported...
+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'
## Downloading release setup RPM...
+ mktemp
+ curl -sL -o '/tmp/tmp.0wk5tWVgrE' 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'
## Installing release setup RPM...
+ rpm -i --nosignature --force '/tmp/tmp.0wk5tWVgrE'
## Cleaning up...
+ rm -f '/tmp/tmp.0wk5tWVgrE'
## Checking for existing installations...
+ rpm -qa 'node|npm' | grep -v nodesource
##   `yum install -y gcc-c++ make`
$
and again..;
$ sudo yum update
Modules complÃ©mentaires chargÃ©sÂ : fastestmirror
http://..../CentOS/7/base/x86_64/repodata/repomd.xml: [Errno 14] H                                                                          TTP Error 504 - Gateway Timeout
Essai d'un autre miroir.

 One of the configured repositories failed (CentOS-7 - Base),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=base ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable base
        or
            subscription-manager repos --disable=base

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=base.skip_if_unavailable=true

failure: repodata/repomd.xml from base: [Errno 256] No more mirrors to try.
http://..../CentOS/7/base/x86_64/repodata/repomd.xml: [Errno 14] H                                                                          TTP Error 504 - Gateway Timeout

###

**Comment by chrislea** [comment]
The 504 error you are seeing is a [Gateway Timeout](https://www.lifewire.com/504-gateway-timeout-error-explained-2622941). That's something to do with the network on your target machine, not our repository, so unfortunately there's nothing we can do to "fix" the situation since we don't have any control over your machine.

I'd recommend running any networking diagnostics that you can to see what's going on with your network. Hope this helps.
