### ISSUE TITLE
Your distribution, identified as "centos-release-6-6.el6.centos.12.2.i686", is not currently supported"

### ISSUE THREAD

**Issue by lopezdp** [nodesource/distributions#507]
I am having an issue installing nodejs. Ultimately I need to use npm to install the pg module so I can connect my db. I have tried every one of the solutions being tracked at #128 and none are working. I am on a CentOS machine, Release 6.6, Kernal Linux 2.6.32-504.12.2.el6.i686, GNOME 2.28.2. Because of my workplace I cannot update this configuration due to other systems that are dependent on this machine.

I am trying to install based on instructions at: https://nodejs.org/en/download/package-manager/

I am getting an error that says:
"Your distribution, identified as "centos-release-6-6.el6.centos.12.2.i686", is not currently supported"

Anyone have a work around for this issue???

**Comment by lopezdp** [comment]
Ive tried these procedures among many:I tried:
# Add NodeSource Repo:
curl -sL https://rpm.nodesource.com/setup_4.x | bash -

I get this error:
## Your distribution, identified as "centos-release-6-6.el6.centos.12.2.i686", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

I tried your solution from Feb 2016 that begins with:

[dplopez2@alhat-hsi CCDD_Viewer_2.0]$ wget https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/epel-6-x86_64/download/rhscl-devtoolset-3-epel-6-x86_64.noarch.rpm

and I get this error:

--2017-08-01 08:13:43--  https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/epel-6-x86_64/download/rhscl-devtoolset-3-epel-6-x86_64.noarch.rpm
Resolving www.softwarecollections.org... 52.55.174.129
Connecting to www.softwarecollections.org|52.55.174.129|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-08-01 08:13:44 ERROR 404: Not Found.


Got any hints as to which direction I should take???
# Add NodeSource Repo:
curl -sL https://rpm.nodesource.com/setup_4.x | bash -

I get this error:
## Your distribution, identified as "centos-release-6-6.el6.centos.12.2.i686", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

I tried a solution from Feb 2016 that begins with:

[dplopez2@alhat-hsi CCDD_Viewer_2.0]$ wget https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/epel-6-x86_64/download/rhscl-devtoolset-3-epel-6-x86_64.noarch.rpm

and I get this error:

--2017-08-01 08:13:43--  https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/epel-6-x86_64/download/rhscl-devtoolset-3-epel-6-x86_64.noarch.rpm
Resolving www.softwarecollections.org... 52.55.174.129
Connecting to www.softwarecollections.org|52.55.174.129|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-08-01 08:13:44 ERROR 404: Not Found.


Got any hints as to which direction I should take???

**Comment by blacksunset** [comment]
+1

**Comment by karthiiivgn** [comment]
same error for me
wget https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/epel-6-x86_64/download/rhscl-devtoolset-3-epel-6-x86_64.noarch.rpm -e use_proxy=yes -e https_proxy=10.100.1.110:3128
--2018-07-30 19:10:01--  https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/epel-6-x86_64/download/rhscl-devtoolset-3-epel-6-x86_64.noarch.rpm
Connecting to 10.100.1.110:3128... connected.
Proxy request sent, awaiting response... 404 Not Found
2018-07-30 19:10:04 ERROR 404: Not Found.

**Comment by chrislea** [comment]
That's an error with the repository from https://www.softwarecollections.org, not ours. We don't have any control over that so I'm afraid we can't do anything to fix it. Sorry!
