### ISSUE TITLE
One of the configured repositories failed (CentOS-7 - Base),  and yum doesn't have enough cached data to continue

### ISSUE THREAD

**Issue by christalk** [nodesource/distributions#509]
CentOS Linux release 7.3.1611 (Core)
node v8.1.2 -> Error to update in node 8.2.x  

"sudo yum update nodejs"

ERROR : One of the configured repositories failed (CentOS-7 - Base),
 and yum doesn't have enough cached data to continue

failure: repodata/repomd.xml from base

Hello, 

I have this error. 

You told me (#506) it was a network error, but I would like to say that those other commands work : (no network prob whis thoses)

$ curl -RLO https://rpm.nodesource.com/setup_8.x  -> OK 
 or
$ wget https://rpm.nodesource.com/setup_8.x -> OK 
or 
$npm install -g vue.js -> OK 

But the command "sudo yum update -y nodejs"  doesn't work anymore. 
$sudo yum install -y nodejs
Modules complÃ©mentaires chargÃ©sÂ : fastestmirror
http://.../CentOS/7/base/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 504 - Gateway Timeout
Essai d'un autre miroir.

 One of the configured repositories failed (CentOS-7 - Base),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=base ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable base
        or
            subscription-manager repos --disable=base

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=base.skip_if_unavailable=true

failure: repodata/repomd.xml from base: [Errno 256] No more mirrors to try.
http://.../CentOS/7/base/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 504 - Gateway Timeout

Regards,

Chris

**Comment by chrislea** [comment]
It's giving a 504 error which is a gateway timeout. That's a networking issue between your machine and CloudFront (which is the CDN that serves the repositories). Unfortunately we don't have any control over that. The [file it's trying to reach](https://rpm.nodesource.com/pub_8.x/el/7/x86_64/repodata/repomd.xml) is definitely there, so I'd look into whatever may be causing the networking glitch. Hope this helps.

**Comment by davidcavalcante** [comment]
yum install yum-utils
yum-config-manager --save --setopt=C7.3.1611-base.skip_if_unavailable=true
yum-config-manager --save --setopt=C7.3.1611-updates.skip_if_unavailable=true

**Comment by sure403** [comment]
How to solve problem tell me

**Comment by davidcavalcante** [comment]
yum install yum-utils
yum-config-manager --save --setopt=C7.3.1611-base.skip_if_unavailable=true
yum-config-manager --save
--setopt=C7.3.1611-updates.skip_if_unavailable=true

Att,

*David Cavalcante* | Consultor de InBound Marketing, Diretor de Arte | +55
65 2136 4436 | +55 65 99922 4060 | Skype: hellodav | LinkedIn
<http://br.linkedin.com/in/davidcavalcante/>

2018-07-10 3:04 GMT-04:00 sure403 <notifications@github.com>:

**Comment by stevenbill** [comment]
when i run yum install yum-utils 
show to me same error
