### ISSUE TITLE
Updated node.js from 8.1.0 to 8.2.0 on Ubuntu 16.10 ( but no current node.js 8.2.1)

### ISSUE THREAD

**Issue by christalk** [nodesource/distributions#510]
Hello, 
I tried to update node.js on Ubuntu 16.10,
from 8.1.0 to the new 8.2.1 (2017-07-20)
But the update gives only 8.2.0  (2017-07-19)
Do you know why ?

apt : 
https://deb.nodesource.com/node_8.x yakkety  main
https://deb.nodesource.com/node_8.x yakkety  main (Code source)

env : 
Ubuntu 16.10 on Windows10's VM
node.js 8.2.0
npm 5.3.0

**Comment by chrislea** [comment]
Ubuntu Yakkety has reached EOL. Canonical is no longer supporting it, and therefore we are no longer building any packages for it. You should update to a supported release like Zesty. Hope this helps.
