### ISSUE TITLE
deepin 15.x is not supported for installed

### ISSUE THREAD

**Issue by fabpin** [nodesource/distributions#511]
i tried to install via the script node.js version 6, but didnt support my deepin 15.4.1 of 64bits, this is the url: [deepin OS](https://www.deepin.org/en/)

**Comment by dragonwarriormaster** [comment]
me too.
nodejs 8
deepin 15.4.1

**Comment by dragonwarriormaster** [comment]
I also encountered the same problem, and this may be useful to you
https://github.com/nodesource/distributions/issues/442

**Comment by Cipfahim** [comment]
i also have the same problem any solution for this issue???

**Comment by diegolameira** [comment]
#515 I just added a pull request, I hope that it helps you to close this dupe issue =)

**Comment by ahmadaidil** [comment]
+ 1

**Comment by igsu** [comment]
We've added support for Deepin 15.10 stable, closing this now.
