### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by twhitbeck** [nodesource/distributions#512]
I was looking for _uninstall_ instructions, but I couldn't find any. Am I missing something?

I realize I can just `sudo apt remove nodejs`, but I want to remove all traces, backtrack the steps that the install script performed. Is there an uninstall script?

**Comment by chrislea** [comment]
The following (as root) should do it:
```
apt remove nodejs
rm -fv /etc/apt/sources.list.d/nodesource*
apt-key del 1655A0AB68576280
```
