### ISSUE TITLE
Node.js 8.3.0 for CentOS 6 has glibc dependency errors

### ISSUE THREAD

**Issue by danlange** [nodesource/distributions#513]
* **Version**: 8.3.0
* **Platform**:Linux automation-reporting 2.6.32-696.6.3.el6.x86_64 #1 SMP Wed Jul 12 14:17:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**:

I installed node on my system:
```
% curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -
% sudo yum -y install nodejs
```
When I attempted to use it, it reported shared library errors:
```
% npm --version
node: error while loading shared libraries: cannot allocate memory in static TLS block
% node --version
node: error while loading shared libraries: cannot allocate memory in static TLS block
```
I am running CentOS 6, on which the only glibc option is 2.12:

```
% ldd --version
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
I was able to work around the problem by removing version 8.3.0 and installing version 8.2.1 instead:
```
% yum remove nodejs
...
% yum -y install nodejs-8.2.1
% npm --version
5.3.0
```

I was able to download and untar: https://nodejs.org/dist/v8.3.0/node-v8.3.0-linux-x64.tar.xz
When I ran it, it appeared to work correctly:
```
% ./node --version
v8.3.0
% ./npm --version
5.3.0
```

**Comment by chrislea** [comment]
I've reproduced the issue, it's because of a [glibc bug](https://sourceware.org/bugzilla/show_bug.cgi?id=14898) that exists on ancient distros.

I'm too tired right now to dig into it, but will look into what's going on tomorrow. Thanks for bringing this to our attention. Stay tuned.

**Comment by chrislea** [comment]
Okay @danlange, this was a tricky one. Fortunately one of the core Node committers was able to work abound the `glibc` bug with a patch to V8 that should propagate out into future versions of Node.

I've made a new one-off build of 8.3.0 just for EL6 with the fix that should work. Please just try:
```
yum -y update
```
and it should pick up the new file (it's [here](https://rpm.nodesource.com/pub_8.x/el/6/x86_64/nodejs-8.3.0-2nodesource.el6.x86_64.rpm) if for some reason it doesn't... you may need to clean your `yum` cache or something).

If it's working (or if it's not) please let us know here on the issue. Thanks.

**Comment by danlange** [comment]
I updated and it is working now.
