### ISSUE TITLE
Why do you provide bash script for installing on centos/rhel?

### ISSUE THREAD

**Issue by agustik** [nodesource/distributions#516]
Hey there, just a small question, why do you provide a whole bash script for installing nodejs/nodesource repo?

Simple steps would be:
- yum install https://rpm.nodesource.com/pub_7.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
- yum install nodejs

**Comment by chrislea** [comment]
There are a couple of reasons including (but not limited to):

1. We do it for the DEB packages so this is for consistency
2. We may want to do more complex things in the future, and having a script means we have that option without requiring the end user to do anything different
  2a. For example, with the script, we can print a warning message if the end user is trying to install an EOL version of Node as you would be doing above
3. If we didn't have the script, we'd have to have a whole thing explaining which release rpm to install based on the end user's distro and the version of Node they want
4. Other projects (Docker, etc) do a similar thing with a setup script, so people are used to them

Hope this helps.
