### ISSUE TITLE
Node not working properly with ARM71 ubuntu

### ISSUE THREAD

**Issue by koushag** [nodesource/distributions#52]
I installed node with apt-get install nodejs and it worked, except it was outdated and the npm was also outdated. I installed the newest version and after installment after I type 'node' or executing a basic script it just hangs and nothing happens except when I check the version (v0.10.34) (npm also hangs). Sorry if this is a bad issue it's my first time doing it.

**Comment by rvagg** [comment]
@koushag are you using the deb.nodesource.com repo to get your Node installs or whatever is coming with the Ubuntu distro you have? What does `node -v` say?

**Comment by koushag** [comment]
I used this to get it: curl -sL https://deb.nodesource.com/setup | sudo bash -

and node -v says: 'v0.10.34'

**Comment by rvagg** [comment]
@koushag can you paste the output of `lsb_release -a` in here for us?

**Comment by koushag** [comment]
Here you go:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise

**Comment by rvagg** [comment]
What sort of board is this? The closest I can come with what I have available to test is an Odroid running 14.04 and I can't replicate a problem with this.

Also, you may want to `npm config set loglevel http` to get a bit more output on `npm install`, sometimes it does things that take a long time and without good feedback it can seem like it's stalled.

**Comment by koushag** [comment]
What do you mean by board? I'm on a Chromebook HP 11 with crouton.

**Comment by rvagg** [comment]
Ah, that's what I mean then! A Chromebook.

Unfortunately I don't know what the way forward is here because I can't replicate a 12.04 setup to try this out.

**Comment by koushag** [comment]
Will upgrading my ubuntu version help in anyway?

**Comment by rvagg** [comment]
perhaps but I can't guarantee that. 14.04 should be pretty safe as it's an LTS release. There's potentially something different about your CPU but my guess is that it's mostly likely about the OS.

**Comment by koushag** [comment]
Just as an update - it worked! I upgraded from 12.04 to 14.04 (trusty), I uninstalled then re-installed nodejs after upgrading and everything went smoothly. Thanks for the help rvagg.
