### ISSUE TITLE
Setup Angular dev with ng failed with error

### ISSUE THREAD

**Issue by rajz** [nodesource/distributions#522]
**Step 1:**
Installed Nodejs following instructions -> https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
**Step 2:**
Installed angular cli -> https://github.com/angular/angular-cli#installation

~/dev/angular$  nodejs --version
v6.11.2
~/dev/angular$ npm --version
3.10.10

**Step 3:**
ng new my-app

**Following error received.**
/usr/lib/node_modules/@angular/cli/node_modules/universalify/index.js:16
  }, 'name', { value: fn.name })
                        ^
TypeError: Cannot read property 'name' of undefined
    at exports.fromCallback (/usr/lib/node_modules/@angular/cli/node_modules/universalify/index.js:16:25)
    at api.forEach.method (/usr/lib/node_modules/@angular/cli/node_modules/fs-extra/lib/fs/index.js:47:21)
    at Array.forEach (native)
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/node_modules/fs-extra/lib/fs/index.js:46:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/node_modules/fs-extra/lib/index.js:8:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by rajz** [comment]
Tried installing older angular-cli
>sudo npm install -g angular-cli
```
npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN gentlyRm not removing /usr/bin/ng as it wasn't installed by /usr/lib/node_modules/angular-cli
/usr/bin/ng -> /usr/lib/node_modules/angular-cli/bin/ng
/usr/lib
`-- angular-cli@1.0.0-beta.28.3 
  +-- @angular-cli/ast-tools@1.0.16
  | `-- @angular/tsc-wrapped@0.5.2
  |   `-- tsickle@0.2.6
  |     `-- source-map-support@0.4.17 
  +-- html-webpack-plugin@2.30.1
  | `-- html-minifier@3.5.3
  |   `-- clean-css@4.1.8 
  `-- UNMET PEER DEPENDENCY rxjs@^5.0.1

```
After that was able to create the angular project directory.
>ng new my-app

```
As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

installing ng2
  create .editorconfig
  create README.md
  create src/app/app.component.css
  create src/app/app.component.html
  create src/app/app.component.spec.ts
  create src/app/app.component.ts
  create src/app/app.module.ts
  create src/assets/.gitkeep
  create src/environments/environment.prod.ts
  create src/environments/environment.ts
  create src/favicon.ico
  create src/index.html
  create src/main.ts
  create src/polyfills.ts
  create src/styles.css
  create src/test.ts
  create src/tsconfig.json
  create angular-cli.json
  create e2e/app.e2e-spec.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tslint.json
Successfully initialized git.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Project 'my-app' successfully created.
araj@vfroot-ThinkPad-T440:~/dev/angular$ ~

```
Did i miss something in the install or there are some things which are still not ironed out in @ angular/cli

**Comment by Eashwarswamy** [comment]
Hi,

I am also facing the same issue. I am using the Ubuntu 14.04.

Is there any way we can resolve this issue?. 

I must use the latest angular/cli(Angular 4) for my project not the older version.

Thanks,
Eashwar

**Comment by chrislea** [comment]
Folks, sorry, but this is not the right place for these errors. We just package up Node (and npm). The issues you are seeing are with the `ng` command which is part of Angular, not part of what we do here. I'd advise reporting these issues to the Angular folks, there's not anything we can do to help.

**Comment by Eashwarswamy** [comment]
Got it Thanks :)
