### ISSUE TITLE
Install on Mx Linux  Metamorphosis

### ISSUE THREAD

**Issue by jast1234** [nodesource/distributions#523]
When i want to get the script i get this error message:
## Confirming "Metamorphosis" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/Metamorphosis/Release'

## Your distribution, identified as "Metamorphosis", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
Hi. Assuming this is based on some version of Debian or Ubuntu, please just send us a pull request against the setup script(s) that aliases this distro to the correct base Debian or Ubuntu version. If it looks good we'll merge it in and it will then be supported. Thanks!

**Comment by jast1234** [comment]
Hi, Mx Linux "Metamorphosis" is base on Debian version "Jessie"

Thank you for the quick answer.
