### ISSUE TITLE
6.11.3 package has introduced a dependency on python 2

### ISSUE THREAD

**Issue by candlerb** [nodesource/distributions#524]
This is on Ubuntu 16.04 amd64.  Previously I had installed `6.11.2-1nodesource1~xenial1` from the node_6.x repository:

~~~
deb https://deb.nodesource.com/node_6.x xenial main
deb-src https://deb.nodesource.com/node_6.x xenial main
~~~

Now when I do an update, it suddenly wants to pull in python2 as a dependency:

~~~
$ sudo apt-get dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  libpython-stdlib libpython2.7-minimal libpython2.7-stdlib python python-minimal python2.7 python2.7-minimal
The following packages will be upgraded:
  nodejs snapd ubuntu-core-launcher
3 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 24.5 MB of archives.
After this operation, 15.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
~~~

It seems that the 6.11.3 package has introduced a dependency on "python-minimal":

~~~
$ apt-cache show nodejs | egrep '^(Version:|Depends:|Recommends:|Suggests:)'
Version: 6.11.3-1nodesource1
Depends: libc6 (>= 2.4), libgcc1 (>= 1:3.4), libstdc++6 (>= 4.1.1), python-minimal, ca-certificates
Version: 6.11.2-1nodesource1~xenial1
Depends: libc6 (>= 2.15), libgcc1 (>= 1:3.4), libstdc++6 (>= 5.2)
Version: 4.2.6~dfsg-1ubuntu4.1
Depends: libc6 (>= 2.15), libgcc1 (>= 1:3.4), libicu55 (>= 55.1-1~), libssl1.0.0 (>= 1.0.2~beta3), libstdc++6 (>= 5.2), libuv1 (>= 1.6.1), zlib1g (>= 1:1.1.4)
Version: 4.2.6~dfsg-1ubuntu4
Depends: libc6 (>= 2.15), libgcc1 (>= 1:3.4), libicu55 (>= 55.1-1~), libssl1.0.0 (>= 1.0.2~beta3), libstdc++6 (>= 5.2), libuv1 (>= 1.6.1), zlib1g (>= 1:1.1.4)
~~~

However, Ubuntu 16.04 is by default python3 only, and I wish to keep my systems this way.  python2 is [obsolete](https://pythonclock.org/); having mixed python versions in a system can lead to confusion.

There is a package "python3-minimal" that could be used as a dependency for ubuntu 16.04.  Having said that, I'm not sure why nodejs needs to depend on python in the first place.

If there is some corner case which needs it, it could be made a `Suggests:` or `Recommends:` soft dependency.

**Comment by candlerb** [comment]
It's also odd that the dependency on `libc6` and `libstdc++6` has gone down.  Was the package rebuilt in a different environment?

**Comment by chrislea** [comment]
There has always been a dependency on python2 (or there should be). Node itself doesn't need it, but `node-gyp` does need it when building native add-ons. Nobody is particularly happy about this, but that's the way things are.

As of 6.11.3, we're not re-building the binaries from source for every platform. We decided to just take the binary distributions that the Node foundation makes and put those bits into DEB and RPM packages to ensure better consistency. They build the binaries on older systems which is why the `libc6` and `libstdc++` dependencies went to lower versions.

Hope this clears things up.
