### ISSUE TITLE
Node 8.x ubuntu zesty support?

### ISSUE THREAD

**Issue by vinothbabu** [nodesource/distributions#525]
Is there a support for node 8.x in ubuntu zesty?

`curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -`

When i try to execute the above command, i get the below errror: 

> 
> Fetched 178 kB in 12s (14.7 kB/s)                                                                                                             
> Reading package lists... Done
> W: The repository 'http://ppa.launchpad.net/mmozeiko/rclone-browser/ubuntu zesty Release' does not have a Release file.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: Failed to fetch http://ppa.launchpad.net/mmozeiko/rclone-browser/ubuntu/dists/zesty/main/binary-amd64/Packages  404  Not Found
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> Error executing command, exiting

**Comment by chrislea** [comment]
Zesty is supported.

The error message you are seeing is because of an improperly configured PPA on Launchpad, specifically:
```
http://ppa.launchpad.net/mmozeiko/rclone-browser/
```
It doesn't have anything to do with our setup script.
