### ISSUE TITLE
distro precise not supported?

### ISSUE THREAD

**Issue by NaNraptor** [nodesource/distributions#531]
Hello I tried to install node v8.x on my PcDuino3s but unfortunately got the following message:

Your distribution, identified as "precise", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Any feedback on the issue?

**Comment by chrislea** [comment]
Precise is no longer supported by Canonical, so we do not build packages for it. If you update to a supported version of Ubuntu, there will be packages available.
