### ISSUE TITLE
Missing NodeJS 8.6.0 RPM for centos 7

### ISSUE THREAD

**Issue by nicolas-moteau** [nodesource/distributions#537]
Hi, 
I'm trying to install NodeJS 8.**6**.0 from RPM on centos 7 but it seems the file is missing:
```
wget https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodejs-8.6.0-1nodesource.el7.centos.x86_64.rpm
...
2017-10-04 16:54:31 ERROR 404: Not Found.
```

_Note: it is OK with NodeJS 8.**4**.0 (https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodejs-8.4.0-1nodesource.el7.centos.x86_64.rpm)_

**Comment by chrislea** [comment]
It's there, but as of 8.5.0 the packages are [named differently](https://rpm.nodesource.com/pub_8.x/el/7/x86_64/). If you just set up the yum repo using the installer script (or manually) then just running:
```
sudo yum update
```
will correctly fetch the newest version for you.

**Comment by nicolas-moteau** [comment]
OK. Thanks.

**Comment by Akira669** [comment]
no funciona algo mas chingon
