### ISSUE TITLE
No Debian source files for 6.11.4 release

### ISSUE THREAD

**Issue by mika** [nodesource/distributions#538]
For the 6.11.4-1nodesource1 Debian package:

```
% dpkg --info nodejs_6.11.4-1nodesource1_amd64.deb | grep Version
 Version: 6.11.4-1nodesource1
```

.... there don't seem to be the corresponding source files available.
The latest ones I can find are for version 6.11.2-1nodesource1 only:

```
nodejs_6.11.2-1nodesource1~stretch1.debian.tar.xz
nodejs_6.11.2-1nodesource1~stretch1.dsc
nodejs_6.11.2.orig.tar.gz
```

Could you please provide the according dsc/orig.tar.gz/debian.tar.xz files for 6.11.4 release as well?

**Comment by chrislea** [comment]
We stopped building individual distribution releases directly from source starting with 6.11.3, so there aren't useful build sources. We are now simply taking the binary releases from https://nodejs.org and pushing those bits into `deb` and `rpm` formats. Hope this helps.
