### ISSUE TITLE
Debug package version mismatch

### ISSUE THREAD

**Issue by mitza-oci** [nodesource/distributions#539]
https://deb.nodesource.com/node_6.x/dists/xenial/main/binary-amd64/Packages
```
Package: nodejs
Version: 6.11.4-1nodesource1

Package: nodejs-dbg
Version: 6.11.2-1nodesource1~xenial1
Depends: nodejs (= 6.11.2-1nodesource1~xenial1)
```

apt:
```
The following packages have unmet dependencies:
 nodejs-dbg : Depends: nodejs (= 6.11.2-1nodesource1~xenial1) but 6.11.4-1nodesource1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by chrislea** [comment]
We stopped building directly from sources after 6.11.2, meaning the `nodejs-dbg` packages are no longer being created. You'll need to remove the one you have installed in order to run the update IE:
```
sudo apt-get remove nodejs-dbg
sudo apt-get update && sudo apt-get upgrade
```
should work successfully.

**Comment by mitza-oci** [comment]
I didn't start out having the -dbg installed.  I'd like to install one to assist with debugging a native addon.  Probably not necessary but gdb notes that the debugging symbols aren't available so I thought it would be easy enough to get them.

**Comment by chrislea** [comment]
Ah, okay. If that's what you want you'll need to build a binary from source yourself and enable a debug build.
