### ISSUE TITLE
Not available in OpenSuse

### ISSUE THREAD

**Issue by steve5287** [nodesource/distributions#540]
I was trying to install yarn in opensuse 42.3 but i get this message from terminal:
## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## You don't appear to be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support. Include your 'distribution package' name: ningún paquete proporciona redhat-release
ningún paquete proporciona centos-release
ningún paquete proporciona cloudlinux-release
ningún paquete proporciona sl-release. 

Or i'm wrong?

**Comment by chrislea** [comment]
We currently [only support](https://github.com/nodesource/distributions/#rpm) RPM distros in the RHEL / CentOS family via our installer. We may look into adding support for SuSE in the future if there's enough interest.

In the meantime you may be able to install the [binary packages](https://rpm.nodesource.com/pub_6.x/el/6/x86_64/) directly if you want to run our builds. Hope this helps.
