### ISSUE TITLE
The repository... does not have a Release file

### ISSUE THREAD

**Issue by ropedonkey** [nodesource/distributions#541]
Installation fails (at least on xenial) with:

`The repository 'https://deb.nodesource.com/node_6.x xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use`

Tested on multiple boxes from multiple locations/networks.

Tried installing manually and also with Ansible Galaxy roles geerlingguy/ansible-role-nodejs and nodesource/ansible-nodejs-role - they all fail. Apt-get update fails as as soon as the repositories are added:
[https://github.com/nodesource/distributions](https://github.com/nodesource/distributions)

Repro steps:
```
curl --silent https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
VERSION=node_6.x
DISTRO="$(lsb_release -s -c)"
echo "deb https://deb.nodesource.com/$VERSION $DISTRO main" | sudo tee /etc/apt/sources.list.d/nodesource.list
echo "deb-src https://deb.nodesource.com/$VERSION $DISTRO main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list
sudo apt-get update
```

Maybe it's just me though - I find it odd that I can't find others reporting the same problem...

**Comment by richardjharris** [comment]
`rjh@merlion:~/HackerBuzz-ReactNative$ curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -

## Installing the NodeSource Node.js v9.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu yakkety InRelease
Hit:2 http://archive.ubuntu.com/ubuntu yakkety-updates InRelease                                                 
Hit:3 http://archive.ubuntu.com/ubuntu yakkety-backports InRelease                                               
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease                                  
Hit:5 http://archive.ubuntu.com/ubuntu yakkety-security InRelease                             
Hit:6 http://archive.canonical.com/ubuntu yakkety InRelease                                   
Hit:7 http://dl.google.com/linux/chrome/deb stable Release                                    
Ign:8 http://ppa.launchpad.net/kaihengfeng/lp1292830/ubuntu xenial InRelease
Err:9 http://ppa.launchpad.net/kaihengfeng/lp1292830/ubuntu xenial Release
  403  Forbidden
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/kaihengfeng/lp1292830/ubuntu xenial Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by chrislea** [comment]
You're seeing this error because of a PPA on Launchpad, specifically:
```
http://ppa.launchpad.net/kaihengfeng/lp1292830/ubuntu
```
That's not something we can do anything about I'm afraid.

**Comment by richardjharris** [comment]
Thanks. Just in case anyone else comes across this, the error is caused by a PPA somewhere in `/etc/apt/sources.list.d` that is actually nothing to do with nodesource. The solution is to remove or update that PPA path.

**Comment by hillbilly-mark** [comment]
what if it is the node source ppa causing the error?  I have apt-cacher-ng.  I'm not sure if that is the reason or how to work around it?

W: The repository 'https://deb.nodesource.com/node_10.x stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://deb.nodesource.com/node_10.x/dists/stretch/main/source/Sources  Received HTTP code 403 from proxy after CONNECT
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting

**Comment by hillbilly-mark** [comment]
yet the install still fails?  Do I have to uninstall apt-cacher-ng?  Turn that machine off?  Set something else in the apt/sources.list.d/*?

**Comment by hillbilly-mark** [comment]
I'm not spending another 12 hours to figure out how to not use the cacher.    The debian repository works fine.  Those people are probably far more familiar with how to make apt-cacher work around it.  I'm not.  I'm just someone who lives where the phone company thinks we don't need any internet.  So with mobile internet being my only internet.   I'm not going to spend a day taking down the apt-cacher.  then putting it back...   just to install node.    Which should in my eyes install as easly as a million other packages, without having to take down the apt-cacher.  Hoo-rah for the millions per week that have no issues installing node.  I'm not sure how that is supposed to make it unbroken for me though.

I guess next you will say it is my fault for installing apt-cacher and expecting apt-cache install to work?

**Comment by chrislea** [comment]
I am not trying to assign blame, I just can't troubleshoot your machine. Though if memory serves, it shouldn't take more than a few minutes to configure things to stop using `apt-cacher-ng`. It doesn't need to be removed, you just have to configure `apt` to not use it. If you look [here](https://www.tecmint.com/apt-cache-server-in-ubuntu/) in the "Client Side Configuration" section, and just reverse what they are doing, I expect that would get you set up pretty quickly.

You can also just download the package directly and install it with `dpkg`. You can see the package listing here for Node 10.x:
```
https://deb.nodesource.com/node_10.x/pool/main/n/nodejs/
```

**Comment by hillbilly-mark** [comment]
After several hours and a few more hairs pulled out.  I have at last found the solution.  I am posting it here for those who find themselves in a similar situation, as there is very little help available.  The solution is simple enough, that if you have spend as much time as I have to get here.  You will hate it.

The solution:
1. open /etc/sources.list.d/nodesource.list with your favorite text editor.
2. remove the "s" from "https://" making it "http://" in both lines
3. save the file.
4. apt-get update && apt-get install ....

It should work as expected.

**Comment by juliangruber** [comment]
@hillbilly-mark can you check if your system time is off?

**Comment by tzvaita** [comment]
@chrislea can you help me with this i am getting the same error i have removed the ppas from software and updates when i run apt update it succeeds but when i try to run the command again,its getting stuck on the 404 error 

$ bash < <(curl -sL https://raw.githubusercontent.com/spbooks/rails3v5/master/scripts/install_linux.sh)
Adding PPA for up-to-date Node.js runtime. Give your password when asked.
 Evented I/O for V8 javascript. Node's goal is to provide an easy way to build scalable network programs
 More info: https://launchpad.net/~chris-lea/+archive/ubuntu/node.js
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
Hit:2 http://zw.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:3 http://archive.canonical.com/ubuntu bionic InRelease                     
Ign:4 http://ppa.launchpad.net/chris-lea/node.js/ubuntu bionic InRelease       
Hit:5 http://zw.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Get:6 http://zw.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB] 
Err:7 http://ppa.launchpad.net/chris-lea/node.js/ubuntu bionic Release         
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                                  
E: The repository 'http://ppa.launchpad.net/chris-lea/node.js/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
tenny@ProBook:~$ sudo apt-get update
Ign:1 http://ppa.launchpad.net/chris-lea/node.js/ubuntu bionic InRelease       
Hit:2 http://archive.canonical.com/ubuntu bionic InRelease                     
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]    
Err:4 http://ppa.launchpad.net/chris-lea/node.js/ubuntu bionic Release         
  404  Not Found [IP: 91.189.95.83 80]
Hit:5 http://zw.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:6 http://zw.archive.ubuntu.com/ubuntu bionic-updates InRelease
Get:7 http://zw.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Reading package lists... Done       
E: The repository 'http://ppa.launchpad.net/chris-lea/node.js/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
tenny@ProBook:~$

**Comment by chrislea** [comment]
@tzvaita It looks like you're using my old Launchpad PPA that's not maintained anymore. Please use our [NodeSource distributions](https://github.com/nodesource/distributions/) instead.

**Comment by tzvaita** [comment]
Ok thanks Chris
I will get back to you once i try to get from that site
thanks for the response

**Comment by tzvaita** [comment]
@chrislea thanks its done now

**Comment by cyphercodes96** [comment]
facing same issue on a cloud VPS
can't install anything it seems
sources.list.d file doesn't have neither http not https

**Comment by Elendiar** [comment]
apper same error through routing connection. Enable routes with netplan - refuse (

**Comment by k1nghat** [comment]
im getting the same thing on ubuntu server bionic. i cant copy/pasta because in vm:

![image](https://user-images.githubusercontent.com/16073360/50178212-7ff5ad80-02c9-11e9-8272-093822a17627.png)

@richardjharris - https://github.com/nodesource/distributions/issues/541#issuecomment-341202948
> Thanks. Just in case anyone else comes across this, the error is caused by a PPA somewhere in `/etc/apt/sources.list.d` that is actually nothing to do with nodesource. The solution is to remove or update that PPA path.

this is a fresh ubuntu server install. i have added docker PPA but everything checked out before i tried to add nodejs. only thing in `/etc/apt/sources.list.d` is `nodesource.list`.

![image](https://user-images.githubusercontent.com/16073360/50178334-d7941900-02c9-11e9-92e3-25d38ab8833e.png)

**Comment by cjohnweb** [comment]
@hillbilly-mark  This may not be an ideal solution, but you should consider using node in docker. For example, there are containers already built with node and npm installed, ready to go. You can use something like docker-compose to tell the node container where your source code is and how to start your node application. The container will run on top of your current OS with minimal overhead and just work. No installation needed (except that of docker and docker-compose of course), and it's super portable. You could even grab a node container, clone your repo in it, npm install, etc, and tell it how to start the server. Now you can literally run that container with docker or docker-compose. If you start using docker, you'll never even have to install node or npm ever again. And that makes me feel all warm and gooey inside :)

**Comment by AlirezaEbrahimkhani** [comment]
@richardjharris thanks its work !

**Comment by ZoR420** [comment]
@AlirezaEbrahimkhani how did you solve it exactly?

You had the same issue ?


zor@ansidemo:~/ansible-playbooks/apache_ubuntu1804$ ansible-playbook playbook.yml -l ubuntu1 -u zor
SSH password: 

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [192.168.131.135]

TASK [Install prerequisites] ***************************************************
failed: [192.168.131.135] (item=aptitude) => {"ansible_loop_var": "item", "changed": false, "item": "aptitude", "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu focal Release' does not have a Release file."}

PLAY RECAP *********************************************************************
192.168.131.135            : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

zor@ansidemo:~/ansible-playbooks/apache_ubuntu1804$

**Comment by Voppis** [comment]
I had the same problem. 
Solution:
1) Open file /etc/apt/sources.list.d/rpi-distro-ubuntu-ppa-focal.list
2) Comment first line (deb http://ppa.launchpad.net/rpi-distro/ppa/ubuntu focal main)
3) apt-get update works!

**Comment by vaneeswaran** [comment]
> After several hours and a few more hairs pulled out. I have at last found the solution. I am posting it here for those who find themselves in a similar situation, as there is very little help available. The solution is simple enough, that if you have spend as much time as I have to get here. You will hate it.
> 
> The solution:
> 
> 1. open /etc/sources.list.d/nodesource.list with your favorite text editor.
> 2. remove the "s" from "https://" making it "http://" in both lines
> 3. save the file.
> 4. apt-get update && apt-get install ....
> 
> It should work as expected.

Thanks it worked :)

**Comment by quincy** [comment]
I am seeing the same issue as of today.  Looks like the root cause for me is an expired certificate.

```
Err:4 https://deb.nodesource.com/node_14.x focal Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 23.220.206.29 443]
...
Reading package lists...
E: The repository 'https://deb.nodesource.com/node_14.x focal Release' no longer has a Release file.
```

**Comment by ryenus** [comment]
> After several hours and a few more hairs pulled out. I have at last found the solution. I am posting it here for those who find themselves in a similar situation, as there is very little help available. The solution is simple enough, that if you have spend as much time as I have to get here. You will hate it.
> 
> The solution:
> 
> 1. open /etc/sources.list.d/nodesource.list with your favorite text editor.
> 2. remove the "s" from "https://" making it "http://" in both lines
> 3. save the file.
> 4. apt-get update && apt-get install ....
> 
> It should work as expected.

^ [This][1] still does the trick as of today.

[1]: https://github.com/nodesource/distributions/issues/541#issuecomment-392932122

**Comment by ifediM** [comment]
not sure what the reason was behind this, but this worked, simply remove this repo and then apt-update or install 

sudo rm /etc/apt/sources.list.d/nodesource.list

**Comment by BestDownLoader365** [comment]
> not sure what the reason was behind this, but this worked, simply remove this repo and then apt-update or install
> 
> sudo rm /etc/apt/sources.list.d/nodesource.list

You save my life.

**Comment by rumilll** [comment]
> not sure what the reason was behind this, but this worked, simply remove this repo and then apt-update or install
> 
> sudo rm /etc/apt/sources.list.d/nodesource.list

I was trying for hours various things, did what you suggested and it worked, thank you
