### ISSUE TITLE
Support: Fedora 27

### ISSUE THREAD

**Issue by mmhyamin** [nodesource/distributions#542]
I tried to install 8.x. But got an error message:

`Your distribution, identified as "fedora-release-27-0.3.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support`

**Comment by mmhyamin** [comment]
It looks like I don't need to add the 8.x repo explicitly on Fedora 27. `sudo dnf install nodejs` works fine.

**Comment by chrislea** [comment]
We don't generally support linux distros before their full release. When FC27 is final, we will add support for it.
