### ISSUE TITLE
The npm version bundled with 6.x is too old

### ISSUE THREAD

**Issue by UnitedMarsupials** [nodesource/distributions#544]
The version of npm bundled with packages available from https://deb.nodesource.com/node_6.x/ , for example, is currently 3.10.10, which is way too buggy (see nodejs/node#16455 for example).

If npm has to be bundled with nodejs at all -- instead of being packaged on its own -- can it, please, be tracking the latest available?

**Comment by chrislea** [comment]
We just bundle whatever version comes included with any given release. If you want that handled differently you'd need to take it up with the official Node release team (again, we just make packages from whatever they put out). Hope this helps.

**Comment by UnitedMarsupials** [comment]
@chrislea, are you suggesting, I file a ticket with nodejs/node?

**Comment by chrislea** [comment]
They would be the ones to ask about it. Though I'm pretty sure they have well defined ways of determining which versions of npm they bundle, so I'm not sure how much luck you'll have.

**Comment by UnitedMarsupials** [comment]
@chrislea, what remains up to you is the decision to not bundle an npm with nodejs _at all_ and offer it as a separate package instead. [FreeBSD does it this way](http://www.freshports.org/www/npm). The [node port](http://www.freshports.org/www/node6) is built with the `--without-npm` flag passed to the `configure`-script.

**Comment by chrislea** [comment]
We decided a long time ago that our intent was to provide `deb` and `rpm` packages that would a) mirror as exactly as possible what the official node releases do and b) be easy to install via package managers. If you want something different than that, we're probably not the right vendor to get the bits from.

**Comment by UnitedMarsupials** [comment]
Official code-releases offer excluding npm as a valid option...

**Comment by chrislea** [comment]
You're welcome to use those to get an npm-free install if you wish. As I said, our goal has always been to make installable packages that mirror whatever the linux binary builds are.
