### ISSUE TITLE
Install script for Node.js 9.x fails on Fedora 26

### ISSUE THREAD

**Issue by lpinca** [nodesource/distributions#547]
The script fails as there is no `nodesource-release-fc26-1.noarch.rpm` in https://rpm.nodesource.com/pub_9.x/fc/26/x86_64/

**Comment by chrislea** [comment]
Very sorry about that, that's my fault.

Please try again, I've added the release packages as I should have.

I'm closing this as I think it's fixed, but if there are still issues please re-open it. Thanks.

**Comment by lpinca** [comment]
Thank you.
