### ISSUE TITLE
nodejs-9.0.0-1nodesource.x86_64.rpm is not signed

### ISSUE THREAD

**Issue by jeanroger** [nodesource/distributions#548]
Hello,
I'm trying to install nodejs 9 on RHEL7 and get this error :
`Package nodejs-9.0.0-1nodesource.x86_64.rpm is not signed`
rpm info give me
`Name        : nodejs
Epoch       : 2
Version     : 9.0.0
Release     : 1nodesource
Architecture: x86_64
Install Date: (not installed)
Group       : Development/Languages
Size        : 52745413
License     : MIT and ASL 2.0 and ISC and BSD
Signature   : (none)
Source RPM  : nodejs-9.0.0-1nodesource.src.rpm
Build Date  : Tue 31 Oct 2017 11:08:18 PM CET
Build Host  : b1b180da027a
Relocations : (not relocatable)
URL         : http://nodejs.org
Summary     : JavaScript runtime
`
Did I miss something ?

**Comment by chrislea** [comment]
Sorry about that, it should be fixed now. Can you please try again?

I'm going to close the issue as I believe it's working now, but please re-open it if not.

**Comment by jeanroger** [comment]
It's fine, thanks a lot.

**Comment by mgibeau** [comment]
Hi, I'm getting the same error for NodeJS 4.8.6 `nodejs-4.8.6-1nodesource.x86_64.rpm is not signed`

rpm -qip nodejs-4.8.6-1nodesource.x86_64.rpm:

```
warning: nodejs-4.8.6-1nodesource.x86_64.rpm: NOKEY, key ID 34fa74dd
Name        : nodejs                       Relocations: (not relocatable)
Version     : 4.8.6                             Vendor: (none)
Release     : 1nodesource                   Build Date: Tue Nov  7 14:38:53 2017
Install Date: (not installed)            Build Host: c997d764effc
Group       : Development/Languages         Source RPM: nodejs-4.8.6-1nodesource.src.rpm
Size        : 33394721                         License: MIT and ASL 2.0 and ISC and BSD
Signature   : RSA/SHA256, Tue Nov  7 17:58:38 2017, Key ID 5ddbe8d434fa74dd
URL         : http://nodejs.org
Summary     : JavaScript runtime
Architecture: x86_64
```

**Comment by chrislea** [comment]
Can you clear your cache and try again? I screwed this up yesterday but then fixed it. Thanks.
