### ISSUE TITLE
Downloads are very slow right now

### ISSUE THREAD

**Issue by jaguilar** [nodesource/distributions#549]
Downloads from deb.nodesource.com are *very* slow right now. Ten minutes and counting for a 10MB node_6.x download. This is what apt printed:

Get:1 https://deb.nodesource.com/node_6.x zesty/main amd64 nodejs amd64 6.11.5-1nodesource1 [9,903 kB]

**Comment by jaguilar** [comment]
Canceling and reissuing fixed the problem.

**Comment by chrislea** [comment]
We don't actually have any control over the download speed, as the files are all part of an AWS CloudFront distribution (which is Amazon's CDN). If you saw slow downloads and trying again fixed the problem, the issue most likely was just a temporary poor connection between your ISP and AWS. Regardless, glad things are snappy again.
