### ISSUE TITLE
io.js support

### ISSUE THREAD

**Issue by rvagg** [nodesource/distributions#55]
@chrislea this is for you but I'm more than happy to do some of the work if you can provide pointers.

The main trick for io.js support is the minimum requirement of gcc 4.8, which is a pain on everything but the latest distros. These are yaks I've already shaved for the CI machines [here](https://github.com/iojs/build) and the CI containers [here](https://github.com/iojs/build-containers) but I'm not sure how transferrable that info is to the pbuilder process.

* EL 7: just need stock gcc & gcc-c++
* EL 6: devtoolset-2 from SLC:

```
curl -sL http://linuxsoft.cern.ch/cern/devtoolset/slc6-devtoolset.repo -o /etc/yum.repos.d/slc6-devtoolset.repo
rpm --import http://ftp.scientificlinux.org/linux/scientific/5x/x86_64/RPM-GPG-KEYs/RPM-GPG-KEY-cern
curl http://linuxsoft.cern.ch/cern/scl/slc6-scl.repo -o /etc/yum.repos.d/slc6-scl.repo
# then run the build within a devtoolset-2 bash or directly with:
scl enable devtoolset-2 [bash or make or whatever command needs newer gcc]
```

* EL 5: EPEL _and_ devtoolset-2:

```
cul -sL http://dl.fedoraproject.org/pub/epel/5/{{ server_arch }}/epel-release-5-4.noarch.rpm -o /tmp/epel-release-5-4.noarch.rpm
bash -c 'rpm -Uvh /tmp/epel-release-5-4.noarch.rpm || true'
yum install python-hashlib # needed for the newer format of slc5-rpm
curl -sL http://linuxsoft.cern.ch/cern/devtoolset/slc5-devtoolset.repo -o /etc/yum.repos.d/slc5-rpm --import http://ftp.scientificlinux.org/linux/scientific/5x/{{ server_arch }}/RPM-GPG-KEYs/RPM-GPG-KEY-cern
# then run the build within a devtoolset-2 bash or directly with:
scl enable devtoolset-2 [bash or make or whatever command needs newer gcc]
```

* Ubuntu 14.04 and 14.10 have required tools by default
* Ubuntu 12.04: Using ppa:ubuntu-toolchain-r/test and then setting alternatives for gcc and g++ for 4.8 so they are default
* Ubuntu 10.04: Using ppa:ubuntu-toolchain-r/test and then setting alternatives for gcc and g++ for 4.8 so they are default

* Debian Stable: such a big pain that I made our own distro of gcc 4.9:

```
echo 'deb https://deb.nodesource.com/weezy-gcc49 weezy-gcc49 main' >> /etc/apt/sources.list && \
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
apt-get install g++-4.9 gcc-4.9 cpp-4.9
# set alternatives for cc, gcc and g++ to 4.9
```

* Debian Testing: Has all the required tools by default

**Comment by rvagg** [comment]
Regarding releases, there are two files, an [index.tab](https://iojs.org/dist/index.tab) and an [index.json](https://iojs.org/dist/index.json) that are updated when each release happens so it would be super-easy to automate this for new releases. Releases are going to come out much more frequently than Node.js releases.

There are also nightlies, they belong in https://iojs.org/download/nightly/ and have the same index.tab and index.json and it would be great to have repos for them too at some point.

**Comment by rvagg** [comment]
@bnoordhuis what is the minimum version of clang needed for io.js? @chrislea is considering using it as an alternative to all of this crazy gcc 4.8 mess.

**Comment by bnoordhuis** [comment]
@rvagg @chrislea That would be clang 3.4.

**Comment by MichalStaruch** [comment]
+1 for this one. Maybe split it to two phases: first modern distributions (EL7, Jessie, Trusty Tahr), then those with old gcc/clang.

**Comment by tracker1** [comment]
+1

**Comment by feross** [comment]
Any update on this? io.js is really hard to use in production without an ubuntu PPA. Eager to start using it in production!

**Comment by devTristan** [comment]
:+1:
![grabbyhands](https://cloud.githubusercontent.com/assets/216009/6314938/5c73a2d8-b9bf-11e4-91e6-c2927adb9f62.gif)

**Comment by Dexus** [comment]
is there any update? i mean, i have my build vm and build my own deb... but a official deb will be a very nice to have!

**Comment by chrislea** [comment]
See here all: https://github.com/iojs/io.js/issues/640#issuecomment-76453181

**Comment by ChALkeR** [comment]
I think this link belongs here: https://deb.nodesource.com/iojs_1.x/

**Comment by rvagg** [comment]
https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories

I'll update the README soon

**Comment by polpo** [comment]
There's no mention of the RPM repositories in that blog post. Will those be updated as well?

**Comment by chrislea** [comment]
Yes, we're actively working on RPM packages for iojs.

**Comment by ChALkeR** [comment]
Ok, looks like you don't have to care about Debian 7 Wheezy anymore, it's oldstable now.

**Comment by aneesh-neelam** [comment]
Why only io.js 1.x? Why not 2.x as well?

**Comment by ChALkeR** [comment]
@aneesh-neelam https://github.com/nodesource/distributions — read ***carefully***.

>***or*** *io.js v2.x*:

>```curl -sL https://deb.nodesource.com/setup_iojs_2.x | sudo bash -```

**Comment by aneesh-neelam** [comment]
@ChALkeR: Oh, I'm sorry. My mistake. Thank you.

**Comment by rvagg** [comment]
Cross-posted from #63:



The README @ https://github.com/nodesource/distributions has updated instructions for io.js and 0.12 on Debian / Ubuntu, although support is still limited on older systems so don't expect full coverage (build chain dramas make this really hard).

RPMs are being built for Node 0.12 for Fedora and EL6 and EL7 but you'll have to download them manually from http://rpm.nodesource.com/pub_0.12/ as the setup procedure is still being worked on and we need some people to test the RPMs. io.js v2.x RPMs are also available for Fedora and EL7 at https://rpm.nodesource.com/pub_iojs_2.x/ - we'd love feedback on these RPMs if you're using them.

**Comment by cthayer** [comment]
Any plans or eta to build io.js v2.x RPMs for EL6?

**Comment by chrislea** [comment]
We're working on it, but iojs 2.x, or more specifically the version of V8 that it uses, requires at least gcc 4.8 which is newer than what ships on any EL release lower than 7. So it's pretty complicated.

**Comment by cthayer** [comment]
Ok.  Thanks.
