### ISSUE TITLE
https://rpm.nodesource.com/pub_7.x/el/7/x86_64/nodejs-8.9.1-1nodesource.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found

### ISSUE THREAD

**Issue by VitorSavedra** [nodesource/distributions#553]
**Command:**
```sh
curl -sL https://rpm.nodesource.com/setup_7.x | bash -
```

**Output:**
```sh
[stdout]Downloading packages:
[stderr]https://rpm.nodesource.com/pub_7.x/el/7/x86_64/nodejs-8.9.1-1nodesource.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found
[stderr]Trying other mirror.
[stderr]To address this issue please refer to the below knowledge base article 
[stderr]
[stderr]https://access.redhat.com/articles/1320623
[stderr]
[stderr]If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.
[stderr]
[stderr]Error downloading packages:
[stderr]  2:nodejs-8.9.1-1nodesource.x86_64: [Errno 256] No more mirrors to try.
```

----

**OS:**
```
NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"
PRETTY_NAME="Amazon Linux AMI 2017.09"
Amazon Linux AMI release 2017.09
```

----

The file `nodejs-8.9.1-1nodesource.x86_64.rpm` is locate in `https://rpm.nodesource.com/pub_8.x/el/7/x86_64/`. But, my node version is 7.5.0, so I need to use the URL `pub_7.x`. Correct? 

Why is he pointing out a package for a future release?

**Comment by chrislea** [comment]
Node 7.x is EOL and not being further developed. You should update to 8.x. Something like this should work:
```
sudo yum remove nodejs nodesource-release
curl -sL https://rpm.nodesource.com/setup_8.x | sudo bash -E -
sudo yum install nodejs
```

**Comment by VitorSavedra** [comment]
Changed, but no success:

Output:
```sh
https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodejs-7.10.1-1nodesource.el7.centos.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found
```

Continues to make the wrong URL.

**Comment by chrislea** [comment]
You are still somehow trying to get a 7.x package. That's not what you want. You want 8.x, specifically this file:
```
https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodejs-8.9.1-1nodesource.x86_64.rpm
```

**Comment by VitorSavedra** [comment]
Yeah, but anyway return 7.x. 

**Solved with:**
```sh
sudo yum remove nodejs nodesource-release
sudo yum clean all
curl -sL https://rpm.nodesource.com/setup_8.x | sudo bash -E -
sudo yum install nodejs
```

Thanks a lot.

**Comment by rhino007US** [comment]
I have run into the same problem, only now it's 2021 now the setup package is on V 14.  Could someone outline the steps to install the current version please.  I downloaded package 14

wget https://rpm.nodesource.com/setup_14.x | sudo bash -E -

this creates a file setup_14.x in the directory /etc/node but yum installs has no ida what to do with it
