### ISSUE TITLE
"Parrot 3.9 (Intruder) 4.13.0-parrot4-amd64 x86_64" is not currently supported

### ISSUE THREAD

**Issue by LulzRose** [nodesource/distributions#554]
I am requesting support for this distribution of Parrot OS. 
Here is the output and the command I ran:
--
`curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -

## Populating apt-get cache...

+ apt-get update
Hit:1 http://deb.parrotsec.org/parrot parrot InRelease
Reading package lists... Done

## Confirming "intruder" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_4.x/dists/intruder/Release'

## Your distribution, identified as "intruder", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
`

**Comment by chrislea** [comment]
If there's a distro you'd like to see supported, please add support for it to our [setup scripts](https://github.com/nodesource/distributions/tree/master/deb/src) and issue a PR. If it looks good we'll merge it. Thanks!
