### ISSUE TITLE
yum install return 403

### ISSUE THREAD

**Issue by tomdevroomen** [nodesource/distributions#555]
I'm trying to install version 4.x.

The first part (`curl --location https://rpm.nodesource.com/setup_4.x | sudo -E bash - `)
 is successful,  but when running `yum install nodejs` the installation fails with
`failure: repodata/repomd.xml from nodesource: [Errno 256] No more mirrors to try.
https://rpm.nodesource.com/pub_4.x/el/7/x86_64/repodata/repomd.xml: [Errno 14] curl#22 - "The requested URL returned error: 403"`

I'm running this behind a proxy, could this be part of the issue or is there something wrong with the repo?

Thnx in advance!

**Comment by chrislea** [comment]
It's almost certainly something to do with the proxy. The url:
```
https://rpm.nodesource.com/pub_4.x/el/7/x86_64/repodata/repomd.xml
```
is definitely there. Here's going to it using `httpie` from my machine (no proxies).
```
(chl-3.6) chl@luthien:~/VirtualENV/chl-3.6$ http --headers https://rpm.nodesource.com/pub_4.x/el/7/x86_64/repodata/repomd.xml
HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 106
Connection: keep-alive
Content-Length: 2525
Content-Type: text/xml
Date: Wed, 08 Nov 2017 09:11:16 GMT
ETag: "5a023bac-9dd"
Last-Modified: Tue, 07 Nov 2017 23:03:08 GMT
Server: nginx/1.12.1
Via: 1.1 2789801ae3a48d82c133f9b7d9690609.cloudfront.net (CloudFront)
X-Amz-Cf-Id: FSqQKUY4-fBCwLK3OxjMiUzCzS9pb-0PRDGDwpAnBfjxP2yr8xuPpA==
X-Cache: Hit from cloudfront
```
Closing this as I don't think it's an issue with our repo, but please reopen if you think I'm wrong.

**Comment by LaurianoElmiroDuarte** [comment]
the same thing happened to me.

[lauriano@lauriano yum.repos.d]$ sudo yum install -y mongodb-org
SUDO Automation is in progress. Please wait...
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: ftp.unicamp.br
 * extras: ftp.unicamp.br
 * updates: ftp.unicamp.br
base                                                                                                                                                                   | 3.6 kB  00:00:00     
extras                                                                                                                                                                 | 2.9 kB  00:00:00     
https://repo.mongodb.org/yum/redhat/7/mongodb-org/4.4/x86_64/repodata/repomd.xml: [Errno 14] curl#22 - "The requested URL returned error: 403"
Trying other mirror.


 One of the configured repositories failed (MongoDB Repository),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=mongodb-org-4.4 ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable mongodb-org-4.4
        or
            subscription-manager repos --disable=mongodb-org-4.4

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=mongodb-org-4.4.skip_if_unavailable=true

failure: repodata/repomd.xml from mongodb-org-4.4: [Errno 256] No more mirrors to try.
https://repo.mongodb.org/yum/redhat/7/mongodb-org/4.4/x86_64/repodata/repomd.xml: [Errno 14] curl#22 - "The requested URL returned error: 403"
