### ISSUE TITLE
Fedora 27 upgrade broken

### ISSUE THREAD

**Issue by gtirloni** [nodesource/distributions#556]
While upgrading to Fedora 27, I get this error:

```
Error: Transaction check error:
  file /usr/lib/node_modules/npm/doc from install of npm-1:5.4.2-1.8.7.0.1.fc27.2.x86_64 conflicts with file from package nodejs-2:8.1.2-1nodesource.fc26.x86_64
  file /usr/lib/node_modules/npm/html from install of npm-1:5.4.2-1.8.7.0.1.fc27.2.x86_64 conflicts with file from package nodejs-2:8.1.2-1nodesource.fc26.x86_64
  file /usr/lib/node_modules/npm/man from install of npm-1:5.4.2-1.8.7.0.1.fc27.2.x86_64 conflicts with file from package nodejs-2:8.1.2-1nodesource.fc26.x86_64
...
```

This seems to be happening because dnf wants to downgrade de nodejs package to version `1:8.7.0-1.fc27` from the `updates` repository.

I'm not sure what the solution is but just wanted to give a heads up.

The workaround for me was to remove NodeSource's package (version `1:8.7.0-1.fc27`), perform the upgrade and reinstall it later.

**Comment by chrislea** [comment]
That should work fine yes. This happened because since FC27 was released today, no new versions of Node have been released, so we haven't made any FC27 packages. When the next releases of Node happens they'll get packaged for FC27 at that time.
