### ISSUE TITLE
Offline install

### ISSUE THREAD

**Issue by kjetilhp** [nodesource/distributions#557]
Anyway to get offline support for these builds? (systems that have no internet connection whatsoever) Would be great if we could download the deb/rpm files from somewhere.

**Comment by chrislea** [comment]
The deb and rpm files are publicly available. Just look at where the repositories point to and they are easy to find. For starters, assuming you want Node 8.x, look under:
```
https://deb.nodesource.com/node_8.x
https://rpm.nodesource.com/pub_8.x
```
Hope this helps.
