### ISSUE TITLE
install destination/permissions config [debian stretch]

### ISSUE THREAD

**Issue by mainettis** [nodesource/distributions#560]
## Questions:
 - ~~Is nodesource distribution choosing the install destination?~~
 - ~~If so,~~ In the package, could install destination be changed to /usr/local or get optional distribution for this?
 - Is this the right place to request repackaging or new package?
 - If not, where can I request this?

## More Details/Reasoning:

Having issues running installing packages from npm after installing through nodesource apt-get. And, I always have to sudo to run npm installs. Mainly, ended up on an infinite loop trying to run `sudo npm install -g @angular/cli
`
After I run the apt-get install, node modules seems to end up under /usr/lib/ path. Shouldn't this be /usr/local/lib/ ? That's where python installs (usr/local). Where the root is not the only one that can read/write/execute. This would allow the developer to install and run all the packages he needs to work I believe.

It seems that most people put the installation in home dir https://github.com/nodejs/node-gyp/issues/454#issuecomment-315691803 . Not sure how/if apt actually supports that. And, I'd rather not have to install multiple package managers to try and work around this. ~~Would changing install path be done here by the package management?~~ Is this the right place to request a repackaging?

~~I tried looking through the source, but couldn't really find exactly where that happens.~~
This involves repackaging with the  dh_auto_install pointing to /usr/local/

Without package management this seems to be the best option: https://github.com/nodejs/help/issues/632#issuecomment-303023922

I'm using Debian stretch. I'm trying to setup my nodejs dev environment on my laptop.

**Comment by chrislea** [comment]
These packages aren't relocatable and we're not going to try and make relocatable packages in order to maintain a basic level of compatibility between the packages we publish, and the ones from the official Debian / Ubuntu repositories (those are not relocatable either).

If you need to install a copy of node locally, meaning not as `root`, for development purposes, you might find [nvm](https://github.com/creationix/nvm) to be an installation method more suited to your needs. Hope this helps.

**Comment by mainettis** [comment]
Well.. in that case permissions might need to be changed when packaging for Debian. Right now, the install makes node_modules with permissions rwxr-xr-x root root. That makes it so you have to su in order to install packages, when being part of root group should be sufficient. 

I'd just be happy if `sudo npm install -g @angular/cli` would work. And not throw warning 

> user "root" does not have permission to access dir

Than cause an endless loop. Though I still think it would be a bit inconvenient. to sudo all the time when working on a project. And, I just don't think I should ever really have to use the root account unless is some major change to my system.

For some reason, I hate the idea of having an extra package manager to install a package manager that will install a service and its own separate package manager. Something about that just doesn't make sense to me. So my stubbornness does not allow me to use nvm. Sorry.

My current workaround was to download the tar.xz file from node site and create a bash script to install/uninstall.

**Comment by chrislea** [comment]
You're installing `npm` packages with the `-g` option, which is [generally considered a bad practice](https://www.smashingmagazine.com/2016/01/issue-with-global-node-npm-packages/) if you can avoid it. If you just install packages locally without the `-g` flag then our packages should work with no problems.

**Comment by mainettis** [comment]
It is bad practice to install "dependencies" that way. And, don't force the user to do extra steps. That's what that article states, and it lists good examples of packages to install globally. 

**Please note:** I'm trying to install angular CLI and maybe even typescript. Not a direct dependency to a specific app.

Despite all that. It is generally accepted [bad practice to have to su to run applications](https://askubuntu.com/questions/16178/why-is-it-bad-to-log-in-as-root
). And, given that installing global is an option of npm. Bad or good, I believe is made even more problematic by logging in as root to run.

Another alternative is to simply tell [npm to use a different default directory](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory). But, if that is what I have to do upon installation then why even make the folder node_modules during package installation?

Either way using the package right now forces us to take extra administrative steps to get things going. Deleting unused folders, making new folders and/or changing permissions manually. I would think it beneficial remove/reduce those steps.

***
### Going back to the having to sudo part:
npm doc mentions that [running sudo to install packages can cause issues](
https://docs.npmjs.com/getting-started/installing-npm-packages-globally) with other applications which are set up to run as user.
