### ISSUE TITLE
node_8.x xenial repo missing nodejs-dbg package

### ISSUE THREAD

**Issue by Sean-Der** [nodesource/distributions#561]
Hey!

I am trying to debug an issue, but don't have the symbols I need. 
```
                Stack trace of thread 45228:
                #0  0x00007f93a291dedc _xend (libpthread.so.0)
                #1  0x00000000009e0bae X509_STORE_add_cert (node)
                #2  0x00000000012d6379 n/a (node)
                #3  0x00000000012d682d _ZN4node6crypto13SecureContext12AddRootCertsERKN2v820FunctionCallbackInfoINS2_5ValueEEE (node)
                #4  0x0000000000b1a073 _ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE (node)
                #5  0x0000000000b8fe3c n/a (node)
                #6  0x0000000000b90a8f _ZN2v88internal21Builtin_HandleApiCallEiPPNS0_6ObjectEPNS0_7IsolateE (node)
                #7  0x000021782820463d n/a (n/a)
```

I am pretty sure [this](https://sourceware.org/bugzilla/show_bug.cgi?id=17561) is the issue. Basically  undefined behavior (unlocking an already unlocked lock) on non-TRM CPUs may cause a SIGILL (I don't have XEND) but I can't confirm anything because I don't have the symbols.

It looks like it stopped getting updated
```
***@***:~$ apt-cache show nodejs-dbg
Package: nodejs-dbg
Source: nodejs
Version: 8.4.0-1nodesource1~xenial1
Architecture: amd64
Maintainer: Chris Lea <chl@nodesource.com>
Installed-Size: 6470
Depends: nodejs (= 8.4.0-1nodesource1~xenial1)
Suggests: libv8-dbg (>= 2.2.7)
Homepage: http://nodejs.org/
Priority: extra
Section: debug
Filename: pool/main/n/nodejs/nodejs-dbg_8.4.0-1nodesource1~xenial1_amd64.deb
Size: 1111960
SHA256: c91b125942523b6565b26e056adc937780b1442b81d1a04aa69c8e817565e909
SHA1: 34d66bb6fa092f0c122b54ae1cb6af5af1180a63
MD5sum: 149b23ed71cebecda3737c8b8093923b
Description: Node.js event-based server-side javascript engine (debug)
 Node.js is similar in design to and influenced by systems like
 Ruby's Event Machine or Python's Twisted.
 .
 It takes the event model a bit further - it presents the event
 loop as a language construct instead of as a library.
 .
 Node.js is bundled with several useful libraries to handle server tasks :
 System, Events, Standard I/O, Modules, Timers, Child Processes, POSIX,
 HTTP, Multipart Parsing, TCP, DNS, Assert, Path, URL, Query Strings.
 .
 This package contains the debugging symbols.
Description-md5: 6166fbe583e7e4ebb70d7a0c6316971c
```

**Comment by Sean-Der** [comment]
@chrislea I think you are the right person to bug for this, sorry if you get an email twice

**Comment by chrislea** [comment]
@Sean-Der no worries.

A few releases ago, we stopped building every release / distro / architecture combo from source when we make packages, and we are currently just pushing the bits made available at nodejs.org into `deb` and `rpm` package formats. Unfortunately this means no more debug builds as the Node foundation doesn't make those. Your best bet will just be to build node yourself from source I expect, unless `nvm` or some other tool can get you the binaries you need (I honestly don't know).

Sorry for the trouble, but hope this helps.

**Comment by alejagapatrick** [comment]
> Hey!
> 
> I am trying to debug an issue, but don't have the symbols I need.
> 
> ```
>                 Stack trace of thread 45228:
>                 #0  0x00007f93a291dedc _xend (libpthread.so.0)
>                 #1  0x00000000009e0bae X509_STORE_add_cert (node)
>                 #2  0x00000000012d6379 n/a (node)
>                 #3  0x00000000012d682d _ZN4node6crypto13SecureContext12AddRootCertsERKN2v820FunctionCallbackInfoINS2_5ValueEEE (node)
>                 #4  0x0000000000b1a073 _ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE (node)
>                 #5  0x0000000000b8fe3c n/a (node)
>                 #6  0x0000000000b90a8f _ZN2v88internal21Builtin_HandleApiCallEiPPNS0_6ObjectEPNS0_7IsolateE (node)
>                 #7  0x000021782820463d n/a (n/a)
> ```
> I am pretty sure [this](https://sourceware.org/bugzilla/show_bug.cgi?id=17561) is the issue. Basically undefined behavior (unlocking an already unlocked lock) on non-TRM CPUs may cause a SIGILL (I don't have XEND) but I can't confirm anything because I don't have the symbols.
> 
> It looks like it stopped getting updated
> 
> ```
> ***@***:~$ apt-cache show nodejs-dbg
> Package: nodejs-dbg
> Source: nodejs
> Version: 8.4.0-1nodesource1~xenial1
> Architecture: amd64
> Maintainer: Chris Lea <chl@nodesource.com>
> Installed-Size: 6470
> Depends: nodejs (= 8.4.0-1nodesource1~xenial1)
> Suggests: libv8-dbg (>= 2.2.7)
> Homepage: http://nodejs.org/
> Priority: extra
> Section: debug
> Filename: pool/main/n/nodejs/nodejs-dbg_8.4.0-1nodesource1~xenial1_amd64.deb
> Size: 1111960
> SHA256: c91b125942523b6565b26e056adc937780b1442b81d1a04aa69c8e817565e909
> SHA1: 34d66bb6fa092f0c122b54ae1cb6af5af1180a63
> MD5sum: 149b23ed71cebecda3737c8b8093923b
> Description: Node.js event-based server-side javascript engine (debug)
>  Node.js is similar in design to and influenced by systems like
>  Ruby's Event Machine or Python's Twisted.
>  .
>  It takes the event model a bit further - it presents the event
>  loop as a language construct instead of as a library.
>  .
>  Node.js is bundled with several useful libraries to handle server tasks :
>  System, Events, Standard I/O, Modules, Timers, Child Processes, POSIX,
>  HTTP, Multipart Parsing, TCP, DNS, Assert, Path, URL, Query Strings.
>  .
>  This package contains the debugging symbols.
> Description-md5: 6166fbe583e7e4ebb70d7a0c6316971c
> ```
