### ISSUE TITLE
please support 

### ISSUE THREAD

**Issue by aludeno** [nodesource/distributions#562]
## Confirming "Horizon" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/Horizon/Release'

## Your distribution, identified as "Horizon", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

not install nodejs in distro linux is
 MX 17.b1 (Horizon) 64-bit! Powered by Debian.
Linux 4.9.0-4-amd64 x86_64
NAME="MX"
VERSION="17.b1 (Horizon)"
ID="mx"
VERSION_ID="17."
PRETTY_NAME="MX 17.b1 (Horizon)"
ANSI_COLOR="0;34"
HOME_URL="https://mxlinux.org"
BUG_REPORT_URL="https://mxlinux.org"
PRETTY_NAME="MX 17 Horizon"
DISTRIB_ID=MX
DISTRIB_RELEASE=17
DISTRIB_CODENAME=Horizon
DISTRIB_DESCRIPTION="MX 17 Horizon"
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

#cat /etc/debian_version
9.2

**Comment by igsu** [comment]
@aludeno current support:

```
Supported MX Linux versions:

MX-17 Horizon (via Debian 9)
MX-18 Continuum (via Debian 9)
```

Closing this issue now
