### ISSUE TITLE
Your distribution, identified as "sylvia", is not currently supported

### ISSUE THREAD

**Issue by manendrabhel** [nodesource/distributions#563]
Your distribution, identified as "sylvia", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chiol** [comment]
me too

**Comment by dkebler** [comment]
sylvia uses 16.04 which is supported.  There is no reason for your script to bail.  Now I have to do a manual install

**Comment by dkebler** [comment]
If you want to use the script just do this.
put `https://deb.nodesource.com/setup_9.x`
into your browser, copy and paste the script into a file `nodeins`, make it executable then copy and paste and modify this line
check_alt "Linux Mint"    "sonya"    "Ubuntu" "xenial"
to
check_alt "Linux Mint"    "sylvia"    "Ubuntu" "xenial"
run that script ast `./nodeins`

@chrislea, maintainers please add @
`check_alt "Linux Mint"    "sylvia"    "Ubuntu" "xenial"`  to your script.   Not really worth the effort for a PR

**Comment by eliiik** [comment]
me too.

**Comment by Ardogar** [comment]
me too.

**Comment by chrislea** [comment]
Sorry for the delay, I've been traveling around the Thanksgiving holiday. Sylvia should now be supported.

**Comment by RyanNerd** [comment]
Please reopen:

## Installing the NodeSource Node.js v7.x repo...
## Populating apt-get cache...

## Your distribution, identified as "sylvia", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
Node 7.x is EOL and we will not be making any updates around that distribution line. If you update to 8.x you'll find supported packages. Hope this helps!
