### ISSUE TITLE
Your distribution, identified as "onyedi", is not currently supported

### ISSUE THREAD

**Issue by electrocoder** [nodesource/distributions#565]
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -

## Populating apt-get cache...

+ apt-get update
Hit:1 http://depo.pardus.org.tr/pardus onyedi InRelease
Hit:2 http://depo.pardus.org.tr/guvenlik onyedi InRelease
Hit:3 https://download.sublimetext.com apt/stable/ InRelease
Reading package lists... Done

## Confirming "onyedi" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_9.x/dists/onyedi/Release'

**Comment by igsu** [comment]
Linux Pardus Onyedi distribution is currently supported via `Debian stretch`.
Closing this now.
