### ISSUE TITLE
 Your distribution, identified as "centos-release-7-3.1611.el7.centos.x86_64", is not currently supported,

### ISSUE THREAD

**Issue by tamim74** [nodesource/distributions#567]
I am trying to install nodejs in a Centos machine but I am getting an error:  
Your distribution, identified as "centos-release-7-3.1611.el7.centos.x86_64", is not currently supported,

Can anyone help please?

**Comment by chrislea** [comment]
Can you please run the setup script with the `-x` flag to help us see what's going on? IE:
```
curl -sL https://rpm.nodesource.com/setup_8.x | sudo bash -x -E -
```
Please cut and paste the full output here. Thanks.

**Comment by guillaume-acard** [comment]
@chrislea I am having the exact same issue, here the output of the command:
`+ print_status 'Installing the NodeSource Node.js 8.x repo...'
++ echo 'Installing the NodeSource Node.js 8.x repo...'
++ sed -r 's/\\n/\\n## /mg'
+ local 'outp=Installing the NodeSource Node.js 8.x repo...'
+ echo

+ echo -e '## Installing the NodeSource Node.js 8.x repo...'
## Installing the NodeSource Node.js 8.x repo...
+ echo

+ print_status 'Inspecting system...'
++ echo 'Inspecting system...'
++ sed -r 's/\\n/\\n## /mg'
+ local 'outp=Inspecting system...'
+ echo

+ echo -e '## Inspecting system...'
## Inspecting system...
+ echo

+ '[' '!' -x /bin/rpm ']'
+ echo '+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release'
+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
++ rpm -q --whatprovides redhat-release
+ DISTRO_PKG=centos-release-7-3.1611.el7.centos.x86_64
+ echo '+ uname -m'
+ uname -m
++ uname -m
+ UNAME_ARCH=x86_64
+ '[' Xx86_64 == Xi686 ']'
+ '[' Xx86_64 == Xx86_64 ']'
+ DIST_ARCH=x86_64
+ [[ centos-release-7-3.1611.el7.centos.x86_64 =~ ^(redhat|centos|cloudlinux|sl)- ]]
+ DIST_TYPE=el
+ [[ centos-release-7-3.1611.el7.centos.x86_64 =~ ^system-release-201[4-9]\. ]]
++ echo centos-release-7-3.1611.el7.centos.x86_64
++ sed -r 's/^[[:alpha:]]+-release(-server|-workstation)?-([0-9]+).*$/\2/'
+ DIST_VERSION=7
+ [[ 7 =~ ^[0-9][0-9]?$ ]]
+ RELEASE_URL_VERSION_STRING=el7
+ RELEASE_URL=https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
+ print_status 'Confirming "el7-x86_64" is supported...'
++ echo 'Confirming "el7-x86_64" is supported...'
++ sed -r 's/\\n/\\n## /mg'
+ local 'outp=Confirming "el7-x86_64" is supported...'
+ echo

+ echo -e '## Confirming "el7-x86_64" is supported...'
## Confirming "el7-x86_64" is supported...
+ echo

+ exec_cmd_nobail 'curl -sLf -o /dev/null '\''https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'\'''
+ echo '+ curl -sLf -o /dev/null '\''https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'\'''
+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'
+ bash -c 'curl -sLf -o /dev/null '\''https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'\'''
+ RC=7
+ [[ 7 != 0 ]]
+ print_status 'Your distribution, identified as "centos-release-7-3.1611.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support'
++ echo 'Your distribution, identified as "centos-release-7-3.1611.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support'
++ sed -r 's/\\n/\\n## /mg'
+ local 'outp=Your distribution, identified as "centos-release-7-3.1611.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support'
+ echo

+ echo -e '## Your distribution, identified as "centos-release-7-3.1611.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support'
## Your distribution, identified as "centos-release-7-3.1611.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
+ echo

+ exit 1
`

**Comment by b01** [comment]
**Bad temp work-a-round for CentOS 7.4**

In my docker container on my developer machine I had this issue and I had to do some shady business. This is temporary though:

```
# Turn off SSL verification for yum on the whole system (very bad).
echo "sslverify=false" >> /etc/yum.conf

# Download the RPM though cURL with SSL verify disabled.
curl -sSk https://rpm.nodesource.com/pub_9.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm >> ./nodesource-release-el7-1.noarch.rpm

# Install the RPM without gpg check.
yum -y install --nogpgcheck ./nodesource-release-el7-1.noarch.rpm

# Now install
yum -y update && yum -y install nodejs

# Now remove the line "sslverify=false" from /etc/yum.conf.
```
