### ISSUE TITLE
Fedora 21 isn't supported

### ISSUE THREAD

**Issue by mahtuag** [nodesource/distributions#57]
I used the install script hosted at https://rpm.nodesource.com/setup - it seems fedora 21 isn't currently supported. There was an issue raised about this when fedora 21 was still Alpha https://github.com/nodesource/distributions/issues/31 but it is now closed.

## Your distribution, identified as "fedora-release-21-2.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by rvagg** [comment]
Whoops! We let that one slip, sorry @mahtuag 

@chrislea can you spin up an fc21 release please? I'll update the setup script when it's ready.

**Comment by chrislea** [comment]
Yup, I'll see if I can't whip that out this evening.

**Comment by chrislea** [comment]
Okay I **think** that fc21 should be ready to go. @rvagg if you could update the setup script that would be great. Testing of course is very much appreciated. Leaving this open until somebody verifies everything is working as expected.

**Comment by rvagg** [comment]
Thanks @chrislea, I just needed to add a test case for fc21 in the script, it works as is:

```
# node -pe process.versions
{ http_parser: '1.0',
  node: '0.10.35',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.30',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1j' }
```

Let us know if you have problems with it @mahtuag

**Comment by mahtuag** [comment]
All ok! Thanks for the quick fix @rvagg @chrislea
