### ISSUE TITLE
Your distribution, identified as "Nibiru", is not currently supported

### ISSUE THREAD

**Issue by diahron** [nodesource/distributions#570]
It appears that there is no support in Nodejs 8^ for any Debian based release.

**Comment by chrislea** [comment]
We support all currently maintained Debian releases with Node 8.x packages. If you'd like support for a Debian based distro, which I'm guessing is what "nibiru" is, please open up a pull request against our [setup script sources](https://github.com/nodesource/distributions/tree/master/deb/src) and if it looks good we'll merge it in. Thanks.
