### ISSUE TITLE
Red Hat installation issues

### ISSUE THREAD

**Issue by nbarr007** [nodesource/distributions#571]
Hi Support,

Could you please review the log below and advise? From your page can see that RHEL 7 64bit is supported 

Many thanks in advance

Rgd's

Norman
-------------------------------------------------------------------------------------------------------------------
## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

**Comment by oniid666** [comment]
Having the same issue, which is odd because I installed this on an identical server literally 9 days ago with no issue
