### ISSUE TITLE
nodejs npm support on deepin os 

### ISSUE THREAD

**Issue by suman-kr** [nodesource/distributions#572]
When i tried installing nodejs npm then it ended with following message:
Your distribution, identified as "unstable", is not currently supported, please contact NodeSource

operating system:deepin os(linux)

**Comment by HeraKumi** [comment]
Here I was going through the same troubles as you are and found a workaround with it by just installing the nodejs with the deepin server by doing 
sudo apt-get install node npm
thus you will begin the fun part,

```
➜  Downloads  sudo npm cache clean -f 
npm WARN using --force I sure hope you know what you are doing.
➜  Downloads  sudo npm install -g n 
/usr/bin/n -> /usr/lib/node_modules/n/bin/n
/usr/lib
└── n@2.1.8 

➜  sudo n latest 

     install : node-v9.2.1
       mkdir : /usr/local/n/versions/node/9.2.1
       fetch : https://nodejs.org/dist/v9.2.1/node-v9.2.1-linux-x64.tar.gz
######################################################################## 100.0%
   installed : v9.2.1


```

then it installed the latest version

```
➜  node -v
v9.2.1


```

**Comment by RickOrchard** [comment]
Indeed, the 'supported distro list' is far from complete. It searches a predefined shortlist using the output of the command

`lsb_release -c -s`

I assume you get 'unstable' as output, which is not telling much. In that case creating a pull request on [this list](https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L258-L277) with the addition of:

`check_alt "Deepin OS"  "unstable"   "Debian" "jessie"`

might solve the issue (still think 'unstable' is a weird name). More explanation on Debian repositories [here](https://www.debian.org/releases/). But keep in mind that apparently 'jessie' is still the repo of choice.

**Comment by hasibweb** [comment]
I am also facing this problem right now. How can I fix this problem?

**Comment by chrislea** [comment]
@RickOrchard was / is correct. If you'd like this distribution supported, please make a pull request against our [setup script](https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L258-L281) to add the correct alias. If it looks good we'll merge it in. Thanks!

**Comment by zhoyifan** [comment]
sudo apt-get install nodejs
sudo apt-get install node
Then type 'npm' in your terminal. You will find that npm is installed.
