### ISSUE TITLE
Where is source rpm of 8.9.3 located?

### ISSUE THREAD

**Issue by axot** [nodesource/distributions#576]
I can not find srpm after `8.4.0`.
https://rpm.nodesource.com/pub_8.x/el/7/SRPMS/

What is the process to build a rpm from source code.

`https://github.com/nodejs/node/blob/master/tools/rpm/rpmbuild.sh` seems not be used now.

**Comment by chrislea** [comment]
After 8.4.0, we stopped building the packages from sources. We are now just pulling the binary tarballs from https://nodejs.org/dist/ and re-packaging those into `rpm` and `deb` formats, so there aren't any more source packages. Hope this helps!

**Comment by axot** [comment]
Is it possible to re-packaging rpm in my local machine?

**Comment by chrislea** [comment]
You can if you want to, there are a variety of utilities such as [checkinstall](https://www.ostechnix.com/build-packages-source-using-checkinstall/) that make it fairly easy to do. Though I don't know what benefit this would give you that you wouldn't get from just using our binary packages.

**Comment by axot** [comment]
@chrislea Thank you for the information. Basically we always build rpm from source rpm to void requirement conflict.

**Comment by chrislea** [comment]
I assume you mean the requirement on `python`. Just be aware that `node-gyp` will **not** work correctly without `python` installed.
