### ISSUE TITLE
Failed to fetch...

### ISSUE THREAD

**Issue by solick** [nodesource/distributions#58]
Hi, performing the curl command, the script exits after the following error line:

    Failed to fetch https://deb.nodesource.com/node/dists/wheezy/Release  Unable to find expected entry 'main/binary-armel/Packages' in Release file (Wrong sources.list entry or malformed file)

As far as i can see, the full node subdir node is no longer existing.

**Comment by rvagg** [comment]
please try again and reopen if you're having trouble

**Comment by kvanisterdael** [comment]
I have the same issue on my Debian Wheezy installation:

W: Failed to fetch https://deb.nodesource.com/node_0.12/dists/wheezy/Release  Unable to find expected entry 'main/binary-armel/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting

**Comment by dkebler** [comment]
Having same error but different  entry   ```binary-mips.```  Indeed that entry is not in the release file.

I double check nodesouce.list in my sources.list.d directory and the entries are fine.  Just the same as the manual install notes.

            W: Failed to fetch https://deb.nodesource.com/node_0.12/dists/wheezy/Release  Unable to find expected entry 'main/binary-mips/Packages' in Release file (Wrong sources.list entry or malformed file)

**Comment by doug65536** [comment]
Note to future viewers of this page: you might need to look at files in `/etc/apt/sources.list.d/` and comment out any lines that match your error. I had to comment out stuff in `nodesources.list`.

**Comment by retrohacker** [comment]
Hey @doug65536,

Would you mind sharing the lines you commented out?

**Comment by retrohacker** [comment]
along with the output of `lsb_release -a`

**Comment by doug65536** [comment]
I tried to get those lines but those filed appear to have been modified by something (presumably apt) since then. Sorry, I should have quoted the lines I commented out when I posted that comment.

Here is my `lsb_release -a` output anyway:

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily

```

**Comment by doug65536** [comment]
I have these lines there now, and they work:

```
deb https://deb.nodesource.com/node_0.10 wily main
deb-src https://deb.nodesource.com/node_0.10 wily main
```
