### ISSUE TITLE
NodeJS Support on Parrot OS

### ISSUE THREAD

**Issue by crash0verrid3** [nodesource/distributions#580]
I'm using Parrot OS (Release "Intruder") and can't install NodeJS. It's basically pure Debian so it wouldn't need any porting or recompiling.

The message I get is:
#### Your distribution, identified as "intruder", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
We have a facility for aliasing Debian and Ubuntu based distributions. If you could add the needed entry to our [setup script](https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L258-L276) in a pull request, we'll have a look. If it looks good we'll merge it and your distro will be supported. Thanks!

**Comment by gsairam08** [comment]
Nodejs pre-installed in Parrot OS, we cannot updated it.

Getting Error like:

Your distribution, identified as "ara", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
