### ISSUE TITLE
NodeJs 4 on Centos 4.4  Is it possible ?

### ISSUE THREAD

**Issue by perry9186** [nodesource/distributions#583]
i want to install nodejs on centos 4.4 is it possible ?
i can't upgrade to advanced version.

thanks in advanced .
Perry

**Comment by chrislea** [comment]
Unfortunately this is not possible. CentOS 4.x has been EOL for some time now and is no longer supported upstream, so we've never tried to make packages for it. Additionally, the C++ compiler and the version of `libstdc++` available on CentOS 4.x are too ancient to build or run a modern version of Node. I hope this helps.
