### ISSUE TITLE
https://rpm.nodesource.com/pub_8.x/el/6/x86_64/nodejs-6.12.2-1nodesource.x86_64.rpm: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"

### ISSUE THREAD

**Issue by arun-awnics** [nodesource/distributions#584]
### I am submitting a bug report.
I get this following error while I am trying to install nodejs on my GCP. I use CentOS 6.9.

```
Downloading Packages:
https://rpm.nodesource.com/pub_8.x/el/6/x86_64/nodejs-6.12.2-1nodesource.x86_64.rpm: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.



Error Downloading Packages:
  2:nodejs-6.12.2-1nodesource.x86_64: failure: nodejs-6.12.2-1nodesource.x86_64.rpm from nodesource: [Errno 256] No more mirrors to try.
```

#### Steps to generate the error:
* curl -sL https://rpm.nodesource.com/setup_8.x | bash -
* yum install -y nodejs

Here is the screenshot of the error:

![image](https://user-images.githubusercontent.com/25379505/34408231-992ddd84-ebe8-11e7-8993-0014408ec191.png)

**Comment by chrislea** [comment]
Are you behind a proxy? If so, can you try:
```
curl -sL https://rpm.nodesource.com/setup_8.x | bash -E -
```
Otherwise, please refer to [this article](https://www.centos.org/forums/viewtopic.php?t=6138) to see if updating your `yum` config helps.

**Comment by arun-awnics** [comment]
So its the proxy that is blocking. I am not sure about the configuration. I will check that once. I installed it using the binary file since this link [https://rpm.nodesource.com/pub_8.x/el/6/x86_64/nodejs-6.12.2-1nodesource.x86_64.rpm](url) gives me not found error. I thought there might have been a missing file or something. Thank you for your help though.
