### ISSUE TITLE
AMD Athlon 32 bit processors

### ISSUE THREAD

**Issue by philipbcook** [nodesource/distributions#585]
I am running Debian v8 - Jessie linux distribution on an AMD Athlon 2600+ processor.
The nodejs V9 installation runs fine..... but running node or npm after installation both produce the error 'Illegal Instruction'
Is AMD Athlon 32 bit hardware not supported?
Perhaps the code has been compiled using Intel specific accelerator cpu functions.
Thanks.

**Comment by chrislea** [comment]
Thanks for the information. You should file an issue with the actual [Node project](https://github.com/nodejs/) for information on the builds. We are just packaging up the binaries that they produce, so this isn't really the place to ask. Hope this helps.

**Comment by philipbcook** [comment]
Thanks Chris.
I wasn’t sure if you were simply packaging the binaries or compiling them as well.
I have reposted my question to the Node project as you suggest.
Regards
Philip
