### ISSUE TITLE
Bad RPM Builds?

### ISSUE THREAD

**Issue by blongstreth** [nodesource/distributions#586]
I am wondering why the change in RPM format and missing source RPM for various setups.  I am seeing this for various builds.  Example:

Found:
https://rpm.nodesource.com/pub_4.x/el/6/x86_64/nodejs-4.8.7-1nodesource.x86_64.rpm

Expected:
https://rpm.nodesource.com/pub_4.x/el/6/x86_64/nodejs-4.8.7-1nodesource.el6.x86_64.rpm

Seems like the .el6. prefix is missing.  This might be part of the reason the following sources are missing?

Latest Setup 4.x Source RPM:

Latest found was:
https://rpm.nodesource.com/pub_4.x/el/6/SRPMS/nodejs-4.8.4-1nodesource.el6.src.rpm

Missing 4.8.7:
https://rpm.nodesource.com/pub_4.x/el/6/SRPMS/nodejs-4.8.7-1nodesource.el6.src.rpm

These cases also hold true for other setups like pub_8.x.

I use the source RPMS to make FIPS builds.  Unless you fix the builds, I will have to figure out how to make builds for latest versions of 4 and 8.

**Comment by chrislea** [comment]
A few months ago we switched from building from source for every distro / architecture we support to simply re-packaging the binaries produced by the Node.js foundation, because discrepancies kept popping up. As a result, there aren't `.src.rpm` files produced anymore because we don't ever touch the sources.

As far as I know, the existing source rpm files should still be useful as templates if you want to keep making your own builds. You'll just need to extract them, update the version numbers, and pull down the newer sources to build with.

Hope this helps!

**Comment by blongstreth** [comment]
Okay.  I will take a peek at the changes.  Specifically, I will review the spec file and see what needs to be done.  I am curious about the following:
```
# For NodeSource, we use the sources direct from nodejs.org/dist
Source0: node-v%{version}.tar.xz
Source1: icu4c-56_1-src.tgz
```
I want to make sure it is as simple as you say.  It appears the ICU stuff is not variable versioned and the latest version of [`ICU`](http://site.icu-project.org/download) ICU is 60.2.  If NodeSource were to update the spec file, I assume a new .src.rpm (and/or spec file) would need to be released.  

Also, I am going to review the following file and hope it contains the spec file.  Maybe this file is what would be updated if your team were to properly version the ICU files:

https://rpm.nodesource.com/pub_4.x/el/6/SRPMS/nodesource-release-el6-1.noarch.rpm

Thanks for the quick reply!

**Comment by chrislea** [comment]
Newer versions of Node bundle ICU with their source distribution. Even when we were building from sources, we always used the bundled version of ICU if it was there, regardless of what version is newest or shipped with the target distro. Hope this helps.

**Comment by blongstreth** [comment]
Okay.  I will take a look. I worry that the ICU tar in the RPM is really what is being used due to the following snippets:

```
# For NodeSource, we use the sources direct from nodejs.org/dist
Source0: node-v%{version}.tar.xz
Source1: icu4c-56_1-src.tgz
```

```
%if 0%{?rhel} == 6
. /opt/rh/devtoolset-3/enable && . /opt/rh/python27/enable
./configure --prefix=%{_prefix} \
           --without-dtrace \
           --with-intl=small-icu \
           --with-icu-source=%{SOURCE1}
%else
./configure --prefix=%{_prefix} \
           --without-dtrace \
           --with-intl=small-icu \
           --with-icu-source=%{SOURCE1}
%endif
```

Based on that, it seems like it would need to be fixed to use the NodeJS source maybe (unless the --with-icu-source switch not applicable)?

Thanks once again for prompt reply!

**Comment by chrislea** [comment]
If memory serves, we did that for older versions of Node (4.x) but not newer ones when they started bundling it. If we weren't using the bundled version, we should have been.

**Comment by blongstreth** [comment]
So, would you say if I were to build 4.8.7 should I update spec file to use the NodeJS provided ICU rather than the one you ship or just leave it as 56_1?

**Comment by chrislea** [comment]
I _think_ that for 4.x you should use the version included in the source rpm. Sorry, it's been a long time since I looked at that.

**Comment by blongstreth** [comment]
Do you have a guide or anything which outlines which CFLAGS and CXXFLAGS to set and why?  I need some insight in order to support long term since Nodesource won't be supporting spec files.  Example flags from spec file:
```
export CFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -mtune=generic -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
export CXXFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -mtune=generic -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
```
For now, I will be building on CentOS 6 with FIPS and assume that some of the settings above will already be there by default.

**Comment by chrislea** [comment]
We ended up running into some weird behavior with the flags you mentioned where in edge cases, the binaries built with those flags would behave differently than the binaries from the official builds. The correct thing to do is to not set `CFLAGS` or `CXXFLAGS` at all (which is what happens for the official builds).

**Comment by blongstreth** [comment]
That is such great news, especially since I don't have a good resource off hand for a description of all the flags :-) . Thanks so much for the super speedy quick replies!

**Comment by blongstreth** [comment]
Do you publish your latest spec files anywhere so I can see how the look please?

Also, I was comparing the Nodesource spec files vs the Node.js bundled spec files and there are some differences, especially how the files are installed (https://github.com/nodejs/node/blob/v4.8.7/tools/rpm/node.spec).  For example, Node.js seems to be cleaning out files at installation time.  Anyway, I am trying to see what I can get away with long term with minimal maintenance (similar problem Nodesource faced I guess).  Can I trust the Node.js bundled spec file and only worry about including the proper build requirements for CentOS 6 and FIPS (devtoolset-3, python27, etc.).

**Comment by chrislea** [comment]
The current spec files are basically identical to the ones already available from the older source RPM files, they just don't actually compile anything since we're no longer building from source. If you're building from source, I'd just grab the last source RPM we published for the major version / Linux distribution you care about, install it, and use that spec file as a starting point.

That will likely work for whatever major version you're building. There's no way to tell if future major versions (like when Node 10 ships) will require modifications.

**Comment by blongstreth** [comment]
Okay.  I gotcha.  The only bummer here the source RPM won't be there initially when a newer version of Node is published (like 10) so comparing spec files (minus build part) will not be possible.  As a result, any chance the spec files (or source RPMS) can be published down the road please?

FYI:  Believe it or not, it seems like the following code from the Node.js spec file to prune from node_modules is valid:
```
# Remove junk files from node_modules/ - we should probably take care of
# this in the installer.
for FILE in .gitmodules .gitignore .npmignore .travis.yml \*.py[co]; do
  find %{buildroot}/usr/lib/node_modules/ -name "$FILE" -delete
done
```
I happened to notice the various flavors of files in the RPM output of my FIPS builds.  Also, the Node.js spec uses `make install` instead of `install.py` directly which is why I was inquired about the differences.  

Regardless, of how Nodesource spec bundles, installs, etc. vs Node spec, if you are maintaining them and they are somehow accessible should do the trick.

Thanks again for the help!

**Comment by chrislea** [comment]
We aren't going to be publishing spec files anymore as we're not publishing source RPM packages. But as I said, if you just get the most recent source RPMs that we did make, you should be pretty much fine.

We remove `node_modules` manually because it's possible for a user to globally install something in there with a hard dependency that the upgrade would overwrite, thus potentially breaking `npm`. It's not an ideal solution but it's the best one we've come up with.

**Comment by blongstreth** [comment]
If a newer Node.js version comes out and the spec file has some important differences, is this something I can inquire about since they won't be published?

When you say "...remove `node_modules`...manually", I am not sure I fully understand because I don't see anything in there explicitly related to pruning `node_modules` (outside the directory and file listings in the %files section) in the v4 spec files.  Sorry for the confusion.

As always, thanks for the time and help!
