### ISSUE TITLE
nodesource-release-el7-1.noarch.rpm is not signed for 7.x and 8.x

### ISSUE THREAD

**Issue by mscifo** [nodesource/distributions#587]
```
$ rpm -qip https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm | grep Signature
Signature   : (none)
$ rpm -qip https://rpm.nodesource.com/pub_7.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm | grep Signature
Signature   : (none)
```

**Comment by chrislea** [comment]
Thanks for bringing that up, our mistake. Should be fixed now.

**Comment by mscifo** [comment]
Did you sign it with the key associated with https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL?

Getting `Header V4 RSA/SHA256 Signature, key ID 9b1be0b4: NOKEY\n\n\nPublic key for nodesource-release-el7-1.noarchqBC89D.rpm is not installed` even though I have `NODESOURCE-GPG-SIGNING-KEY-EL` installed.

**Comment by chrislea** [comment]
Let's please pretend I didn't just screw this up twice. :)

I think it should _actually_ be fixed now.
