### ISSUE TITLE
Your distribution, identified as "fedora-release-21-2.noarch", is not currently supported

### ISSUE THREAD

**Issue by deanksalinux** [nodesource/distributions#588]
While running curl --silent --locurl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -cation https://rpm.nodesource.com/setup_8.x | sudo bash - I get the error. Is this issue going to be fixed?

**Comment by chrislea** [comment]
Fedora 21 went EOL on Dec 1, 2015. We don't support distros that aren't supported upstream, which is why the installer script is failing. If you upgrade to a supported version of Fedora, the installer script should work.
