### ISSUE TITLE
ubilinux/dolcetto

### ISSUE THREAD

**Issue by huckIeberry** [nodesource/distributions#590]
Good morning everyone,

I'm using the combination ubilinux on Up Squared. Ubilinux dolcetto is based on Debian Stretch. I want to install nodejs >= 8.9.x on the system and tried that with 
`curl -sL https://deb.nodesource.com/setup_8.x | bash -`
with little success:
```
+ apt-get update
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease         
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian stretch Release
Hit:5 https://ubilinux.org/ubilinux dolcetto InRelease
Reading package lists... Done

## Confirming "dolcetto" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/dolcetto/Release'

## Your distribution, identified as "dolcetto", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

Looks to me as if the connection to stretch is done by the setup script anyway, but since the distribution name states 'dolcetto', it still exits with an error. The source list of apt is stretch only by the way. So I reckon installing the stretch version of nodejs would work. Is there a way to trick the script into using the stretch version? Or does anyone have another helpful tip for me here?

Thanks in advance

**Comment by chrislea** [comment]
If you'd like this to be supported, please issue a pull request against our [setup script](https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L258-L276) with the appropriate alias in place. If it looks good we'll merge it in for support. Thanks.

**Comment by gutobrz** [comment]
@chrislea, I fixed it inserting the bellow line in the setup script and the install worked like a charm.
`check_alt "Ubilinux"      "dolcetto"  "Debian" "stretch"`
Shoud I open a new issue to go ahead with the pull request or you can re-open this one?
