### ISSUE TITLE
Fedora 18 is not allowing to install node JS

### ISSUE THREAD

**Issue by njgandhi** [nodesource/distributions#592]
Hi Team,

I am new to node js and I am trying to install node js on my system which is fedora as per below configuration:

[root@localhost modules]# cat /etc/fedora-release 
Fedora release 18 (Spherical Cow)

[root@localhost modules]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 58
Stepping:              9
CPU MHz:               2900.000
BogoMIPS:              5786.78
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              3072K
NUMA node0 CPU(s):     0,1

Command : curl -sL  https://rpm.nodesource.com/setup_4.x | sudo -E bash -

Output: 
## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "fc18-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_4.x/fc/18/x86_64/nodesource-release-fc18-1.noarch.rpm'

## Your distribution, identified as "fedora-release-18-6.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Requesting you to please help how Can I install.

**Comment by chrislea** [comment]
Fedora 18 is EOL so we don't support it. Please reference #588 .
