### ISSUE TITLE
"centos-release-6-9.el6.12.3.i686", is not currently supported,

### ISSUE THREAD

**Issue by wuwu20048** [nodesource/distributions#595]
[root@host www]# curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el6-i386" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_6.x/el/6/i386/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "centos-release-6-9.el6.12.3.i686", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
32bit CentOS 6 is not supported for Node 6.x. If you instead use a 64bit OS, you will find that packages are available. Hope this helps.
