### ISSUE TITLE
Include SparkyLinux ('Nibiru') in the supported releases file

### ISSUE THREAD

**Issue by RickOrchard** [nodesource/distributions#597]
SparkyLinux is a Debian Testing distribution. It is not recognized though:

```
## Confirming "Nibiru" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_9.x/dists/Nibiru/Release'

## Your distribution, identified as "Nibiru", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

```

**Comment by chrislea** [comment]
If you'd like this distribution to be supported by the setup scripts, please issue a pull request with the correct alias against the [setup script source](https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L258-L277). If it looks good we'll merge it in. Thanks!
