### ISSUE TITLE
Ubuntu 17.04 No longer being supported

### ISSUE THREAD

**Issue by D3m0nKingx** [nodesource/distributions#599]
When logging into the my system:
--
Welcome to Ubuntu 17.04 (GNU/Linux 4.13.0-31-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Spectre Mitigation Updates Available for Testing in Ubuntu Proposed
   - https://ubu.one/uSpectre

**Your Ubuntu release is not supported anymore.**
For upgrade information, please visit:
http://www.ubuntu.com/releaseendoflife

New release '17.10' available.
Run 'do-release-upgrade' to upgrade to it.

**Informing you that the zesty repositories previously used for updating 17.04 are no longer active.**

**Comment by chrislea** [comment]
That is just the Ubuntu supplied [MOTD](https://en.wikipedia.org/wiki/Motd_(Unix)) telling you that the version of Ubuntu you're running is no longer supported. It doesn't have anything to do with our repositories one way or the other. I'd suggest you upgrade immediately to a supported release. Hope this helps.
