### ISSUE TITLE
nodejs automatically updated to 0.11.15 in Ubuntu utopic-amd64 as of 2015-01-29

### ISSUE THREAD

**Issue by ronjouch** [nodesource/distributions#60]
Hello. Is [this](https://deb.nodesource.com/node/dists/utopic/main/binary-amd64/Packages) expected? Is there a way to revert to 0.10.x?

    Package: nodejs
    Version: 0.11.15-1nodesource1~utopic1
    Architecture: amd64
    Maintainer: Jérémy Lal <kapouer@melix.org>
    Installed-Size: 24599
    Depends: libc6 (>= 2.15), libgcc1 (>= 1:4.1.1), libstdc++6 (>= 4.9), rlwrap
    Conflicts: nodejs-dev, nodejs-legacy, npm
    Replaces: nodejs-dev (<= 0.8.22), nodejs-legacy, npm (<= 1.2.14)
    Provides: nodejs-dev, nodejs-legacy, npm
    Homepage: http://nodejs.org/
    Priority: extra
    Section: web
    Filename: pool/main/n/nodejs/nodejs_0.11.15-1nodesource1~utopic1_amd64.deb
    Size: 5698932
    SHA256: 99731ceeaebcf1aba9e5d4148b803392db24e05c85551e8aad5549db4b831986
    SHA1: 889acee2a935a56fdeb5b001eeeba4235fca4c7c
    MD5sum: 40244d6d0629bd11b9bc1a22d22f51e2

**Comment by bpmarinho** [comment]
Hi.

It seems for utopic it was built the unstable version and had the same problem.
I manually download the previous version and install from https://deb.nodesource.com/node/pool/main/n/nodejs/

**Comment by ronjouch** [comment]
Okay, thanks!

**Comment by guidouil** [comment]
Just for the record
```
wget https://deb.nodesource.com/node/pool/main/n/nodejs/nodejs_0.10.35-1nodesource1~utopic1_amd64.deb
sudo dpkg -i nodejs_0.10.35-1nodesource1~utopic1_amd64.deb
```

**Comment by yoyurec** [comment]
+1
will it be fixed or every Unicorn user should downgrade everytime? ((

**Comment by joemaller** [comment]
This broke our deploys. It's especially frustrating since version-stability was kind of the whole reason for installing with NodeSource. 

The unstable nodejs version will fail for anyone trying to install node-sass (250k+ downloads last month) and likely other modules with bundled binaries. 

sass/node-sass#563
sass/node-sass#627

**Comment by chrislea** [comment]
So no, that should not be happening. The 0.10.x builds and the 0.11.x builds are in different repositories. Can somebody show me the output of:

```apt-cache policy nodejs```

from an affected machine?

**Comment by bpmarinho** [comment]
I don't have it here but if you browse the repo files you will see that for Ubuntu 14.10 unicorn, it was built only the unstable version. Because it's the highest it's the one we get upgraded to.

**Comment by bpmarinho** [comment]
Sorry, utopic, not unicorn and see check the directory, https://deb.nodesource.com/node/pool/main/n/nodejs/

**Comment by joemaller** [comment]
@chrislea This is what I got from a freshly deployed Ubuntu 14.10 x64 VPS just now:

```
nodejs:
  Installed: 0.11.15-1nodesource1~utopic1
  Candidate: 0.11.15-1nodesource1~utopic1
  Version table:
 *** 0.11.15-1nodesource1~utopic1 0
        500 https://deb.nodesource.com/node/ utopic/main amd64 Packages
        100 /var/lib/dpkg/status
     0.10.25~dfsg2-2ubuntu1 0
        500 http://mirrors.digitalocean.com/ubuntu/ utopic/universe amd64 Packages
```

**Comment by chrislea** [comment]
Thanks @joemaller.

So first thing's first, which is my apologies that this happened to being with. It was our (my) error, not anything anyone on this thread did wrong. I'm still not exactly sure how this got messed up as it's a fairly automated process, but I'll review things and see if I can clean things up better.

So second thing, thanks to everybody for reporting this so I could get it fixed.

The 0.11.x build for utopic has been removed from the repo and 0.10.36 has been installed properly. You should be able to trust that the NodeSource repos are going to work as expected. Unfortunately, if you got hit by this, you will have to get rid of the 0.11.x build first before you can get back to "situation normal". I believe the following commands, as root, should do the trick for you:

```
apt-get remove --purge nodejs
apt-get update
apt-get -y install nodejs
```

If there are still issues please report them here. I will leave this open until I get some verification that things are okay again.

**Comment by yoyurec** [comment]
:+1:

**Comment by joemaller** [comment]
@chrislea  Looks like we're all good again, thank you!

Here's the `apt-cache policy nodejs ` output I got from another clean Ubuntu 14.10 VPS:

```
nodejs:
  Installed: 0.10.36-1nodesource1~utopic1
  Candidate: 0.10.36-1nodesource1~utopic1
  Version table:
 *** 0.10.36-1nodesource1~utopic1 0
        500 https://deb.nodesource.com/node/ utopic/main i386 Packages
        100 /var/lib/dpkg/status
     0.10.25~dfsg2-2ubuntu1 0
        500 http://mirrors.digitalocean.com/ubuntu/ utopic/universe i386 Packages

**Comment by chrislea** [comment]
Thanks for the report. Closing this down.
