### ISSUE TITLE
install on rhel 5.5 not working

### ISSUE THREAD

**Issue by trevor-pierce** [nodesource/distributions#61]
I receive the following message when trying to install via "curl -kL https://rpm.nodesource.com/setup | bash -": "Your distribution, identified as "redhat-release-5Server-5.5.0.2", is not currently supported". What can be done to fix this? Is a newer version of rhel5 supported?
Thanks

**Comment by trevor-pierce** [comment]
Can anyone help? I am told this is needed for our builds to run right. Is there another way to install this?

**Comment by chrislea** [comment]
It looks like the DIST_PKG string that the setup script makes and uses is a weird format on your machine. Can you let us know what the output of

```
rpm -q --whatprovides redhat-release
```

on your system is?

**Comment by trevor-pierce** [comment]
# rpm -q --whatprovides redhat-release
redhat-release-5Server-5.5.0.2

**Comment by rvagg** [comment]
@trevor-pierce do you have an outgoing proxy that you have to force requests through? It's failing on the step where it tries to confirm it can get access to the release rpm.

Try this on the same server: `curl -sLf -O https://rpm.nodesource.com/pub/el/5/x86_64/nodesource-release-el5-1.noarch.rpm` and see if you end up with a nodesource-release-el5-1.noarch.rpm file (you should).

**Comment by trevor-pierce** [comment]
We are not using a proxy for outgoing requests. That command fails with a certificate error: "curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed"

If I run it with the -k also to ignore the error then I am able to get the rpm. Thanks

**Comment by rvagg** [comment]
very odd, have you done a `yum upgrade` on the server to make sure you have the latest certificates?

**Comment by trevor-pierce** [comment]
I have not run a yum upgrade in awhile since this is a heavily used server and I do not want to mess with changing versions if I don't have to. Is it possible to install this manually with the rpm? Thanks

**Comment by trevor-pierce** [comment]
Any other suggestions?

**Comment by chrislea** [comment]
Well you should be able to tell what RPMs would get installed if you look through the setup script. But if you haven't run a `yum update` on the machine in long enough that you have an out of date cert for DigiCert, then I'd *really* recommend updating that box, as it's probably very insecure and a lot of things need to be updated.

**Comment by trevor-pierce** [comment]
I have manually installed it from the rpm. Seems to be ok. Thanks for the help.
