### ISSUE TITLE
MLOS: McAfee Linux

### ISSUE THREAD

**Issue by urmilparikh** [nodesource/distributions#610]
Please add support for MLOS distribution. It is based on CentOS.
distribution package name: `mlos-release-3.0-3.mlos3.noarch`

```bash
$ sudo cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
```

**Comment by chrislea** [comment]
If you'd like this distribution to be included, please issue a pull request against our setup scripts with the needed changes and if it looks good we'll merge it in. I don't have a version of this distribution around to test with, but I think that you'll want to make modifications [here](https://github.com/nodesource/distributions/blob/master/rpm/src/_setup.sh#L225-L229) to check for the `mlos-release` package. Thanks.
