### ISSUE TITLE
Missing install scripts?

### ISSUE THREAD

**Issue by whmountains** [nodesource/distributions#612]
Where is the source for `curl --silent --location https://rpm.nodesource.com/setup_9.x | sudo bash -`?

**Comment by chrislea** [comment]
I'm not sure what you mean? That script is at the URL you are referencing there.

**Comment by whmountains** [comment]
Sorry, I didn't make myself clear.  Where is it in the nodesource/distributions repository?

I would expect it to be [here](https://github.com/nodesource/distributions/tree/master/rpm), but I only see versions up to 7.x.

**Comment by chrislea** [comment]
Ah, sorry. It's where you think it is, but the version in the repository is out of sync with what's on the actual server. We'll get that fixed up shortly, but that just means adding the needed entries to [this file](https://github.com/nodesource/distributions/blob/master/rpm/src/build.sh) and running it.
