### ISSUE TITLE
Devuan not supported

### ISSUE THREAD

**Issue by Schoumi** [nodesource/distributions#613]
Devuan (Debian fork) is not supported by your script for node 8

> Your distribution, identified as "ceres", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

ceres is equivalent to sid

**Comment by Schoumi** [comment]
add this to the script make it work
check_alt "Devuan"        "ceres" "Debian" "sid"

**Comment by chrislea** [comment]
Closed by 3070143
