### ISSUE TITLE
Please add blackPanther OS support

### ISSUE THREAD

**Issue by blackPantherOS** [nodesource/distributions#614]
"You don't appear to be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support. Include your 'distribution package' name: blackPanther-release-Default-16.1-1bP"

The next release name is blackPanther-release-Default-17.1-1bP"

blackPanther OS is a 16. years old Hungarian RPM based distro, please add to your script if possible.
Thank You

**Comment by chrislea** [comment]
We're not familiar with this distribution, but if you'd like it to be supported, please open up a pull request against our [setup script](https://github.com/nodesource/distributions/blob/master/rpm/src/_setup.sh) with the needed modifications. If it looks good and doesn't break anything that we currently support, we'll merge it in. Thanks!
