### ISSUE TITLE
Fail to install nodejs 6.x/8.x on CentOS 7 i686 (32bit)

### ISSUE THREAD

**Issue by chris001** [nodesource/distributions#615]
**Your distribution, identified as "centos-release-7-4.1708.el7.centos.i686", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support**

**Comment by chrislea** [comment]
This is failing because we don't support 32bit CentOS 7. If you use a 64bit OS, you'll find it's supported. Hope this helps.

**Comment by chris001** [comment]
Is there a workaround, is there a script to build it from source easily, because this centos 7 32bit is a live running system and cannot be replaced by 64bit without significant downtime.

**Comment by chrislea** [comment]
I suspect if you just download and use the 32bit [binary tarballs](https://nodejs.org/dist/) directly from the Node foundation, those will work.
