### ISSUE TITLE
Hardened node.js for alpine

### ISSUE THREAD

**Issue by rajiff** [nodesource/distributions#616]
Did the hardened version of Node.JS distro got out ever

I read this article and was actually looking for it
https://www.infoworld.com/article/3190606/javascript/hardened-nodejs-distro-comes-to-docker-friendly-alpine-linux.html

Or any suggestion on what needs to be done to harden the node.js distro, may be I can do and share it here

**Comment by chrislea** [comment]
You're looking for our commercial product NSolid. You can find download instructions [here](https://downloads.nodesource.com/).
