### ISSUE TITLE
"sylvia", is not currently supported

### ISSUE THREAD

**Issue by NawazShorif** [nodesource/distributions#618]
I want to install node js  and npm  that's why use command :+1: 
1:  $ sudo apt-get install python-software-properties
2: $ curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
3: $ sudo apt-get install nodejs
hp@hp ~ $ sudo apt-get install python-software-properties
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-software-properties is already the newest version (1.7.2).
The following packages were automatically installed and are no longer required:
  gyp libjs-inherits libjs-node-uuid libssl-dev libuv1 libuv1-dev zlib1g-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 265 not upgraded.
hp@hp ~ $ curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

## Populating apt-get cache...

+ apt-get update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://dl.google.com/linux/chrome/deb stable Release                                                                                                             
Hit:3 http://ppa.launchpad.net/damien-moore/codeblocks-stable/ubuntu xenial InRelease                                                                                  
Hit:4 http://archive.ubuntu.com/ubuntu xenial InRelease                                                                                                               
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]                                                                                            
Hit:7 http://archive.canonical.com/ubuntu xenial InRelease                                                                                                             
Hit:8 http://archive.ubuntu.com/ubuntu xenial-updates InRelease                                                                                                        
Ign:9 http://packages.linuxmint.com sylvia InRelease                                                                                                      
Hit:10 http://ppa.launchpad.net/webupd8team/sublime-text-3/ubuntu xenial InRelease                                              
Get:11 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]                                                    
Hit:12 http://packages.linuxmint.com sylvia Release                                                                   
Fetched 204 kB in 1s (125 kB/s)                                                                 
Reading package lists... Done

## Confirming "sylvia" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/sylvia/Release'

**Comment by rvagg** [comment]
@NawazShorif would you mind opening a pull request for this? Edit the file `deb/src/_setup.sh` and at about line 268 you'll see a place to insert a new line under the existing Linux Mint entries. Add "sylvia" as an alias for Ubuntu "xenial", it should be clear how to do that since it's the same as the last 3 Mint releases.

**Comment by chrislea** [comment]
I got it. Closed by 6aa319eecf2c8a4c8de2ce410b7fc8692f34ade1.

**Comment by NawazShorif** [comment]
deb/src/_setup.sh    I can't find   it

**Comment by chrislea** [comment]
@NawazShorif Don't worry, I already added support. You should be able to use the installation instructions that you tried before and things will work.
