### ISSUE TITLE
V5, Stretch not supported anymore

### ISSUE THREAD

**Issue by NebzHB** [nodesource/distributions#619]
Dears,

I receive that message when installing v5 on stretch : 

## Your distribution, identified as "stretch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

But it works on jessie... normal ?

**Comment by chrislea** [comment]
Stretch is supported for Node versions that are currently supported. 5.x has been EOL since the middle of 2016. You need to switch to a supported version **immediately** as 5.x has numerous security vulnerabilities.
