### ISSUE TITLE
Failed to install last node version on debian 9

### ISSUE THREAD

**Issue by Gatreek92** [nodesource/distributions#620]
Hi , 
i tried to install NodeJS on my Debian 9 by following the steps in [NodeJs website](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) 

When i do : 
`sudo curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -`
i get an error that i think it has no relation with node : 
`E: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/InRelease` 
(I don't know if this could impact node's installation or not)

After that i did : 
`sudo apt-get install -y nodejs`
the program  finish the installation , but it installed v4.8.2 and not the last version.
And when i do : 
`nodejs  -v ` 
i get : 
`v4.8.2`

I tried to add those two lines to my nodesource.list file 
`deb https://deb.nodesource.com/node_9.x stretch main
deb-src https://deb.nodesource.com/node_9.x stretch main`
And then `apt-get update` but this did not resolve the issue :( 

Anyone know what should i do ?
Thanks guys for your help !

**Comment by angelHarizanov** [comment]
I get `W: Failed to fetch https://deb.nodesource.com/node_8.7.0/dists/trusty/main/binary-i386/Packages  HttpError404` with 8.7.0.

**Comment by mok-liee** [comment]
Hi, 
similar problem.

i am using latest debian 9.4 and after running:
`curl -x {proxy-address} -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -`

i got:
```
## Confirming "stretch" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/stretch/Release'

## Your distribution, identified as "stretch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

i think the curl line in the script is not using my proxy. is it possible to grab the proxy information in the script?

**Comment by chrislea** [comment]
If you're behind a proxy, please take a look at the first question in [the FAQ](https://github.com/nodesource/distributions/#questions). Thanks.
