### ISSUE TITLE
centos-release-7-4.1708.el7.centos.x86_64 not supported. 

### ISSUE THREAD

**Issue by dwjohnston** [nodesource/distributions#621]
There is already an issue here: https://github.com/nodesource/distributions/issues/545 which says that it should now work, but it doesn't. 

```
## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Your distribution, identified as "centos-release-7-4.1708.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by chrislea** [comment]
CentOS 7 is certainly supported. Can you get to that referenced `rpm` file from the target machine? Meaning, if from the target machine you do something like:
```
curl -RLO https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
```
does it download the release `rpm`?

**Comment by dwjohnston** [comment]
Hmmm, yeah, it does look like there's something wrong on my end. 

[administrator@jos-k8s-server2 ~]$ curl -v -RLO https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm > /tmp/rpm2.rpm
* About to connect() to proxy 172.17.68.251 port 3128 (#0)
*   Trying 172.17.68.251...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 172.17.68.251 (172.17.68.251) port 3128 (#0)
* Establish HTTP proxy tunnel to rpm.nodesource.com:443
> CONNECT rpm.nodesource.com:443 HTTP/1.1
> Host: rpm.nodesource.com:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
< Via: 1.1 DNZWGPX3
< Connection: Keep-Alive
< Proxy-Connection: Keep-Alive
<
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=*.nodesource.com
*       start date: Sep 12 00:00:00 2017 GMT
*       expire date: Oct 12 12:00:00 2018 GMT
*       common name: *.nodesource.com
*       issuer: CN=Amazon,OU=Server CA 1B,O=Amazon,C=US
> GET /pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm HTTP/1.1
> User-Agent: curl/7.29.0
> Host: rpm.nodesource.com
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/x-rpm
< Content-Length: 8736
< Connection: keep-alive
< Accept-Ranges: bytes
< Date: Wed, 17 Jan 2018 11:43:52 GMT
< ETag: "5a4e91ab-2220"
< Last-Modified: Thu, 04 Jan 2018 20:42:19 GMT
< Server: nginx/1.12.1
< Age: 595
< X-Cache: Hit from cloudfront
< Via: 1.1 1fe5a3dd696b067d230fbe4cb4093583.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: uW7U24FxFTvQziXrXMOdwK8vrQN1opDZo9kKYxDGfjC3zvJVvCTzdQ==

The curl response shows the right size, but it's empty in the /tmp folder.

**Comment by chrislea** [comment]
Are you behind a proxy? If so, please look at the first entry in the [FAQ](https://github.com/nodesource/distributions/#faq).

**Comment by dwjohnston** [comment]
@chrislea  great thanks.

**Comment by chrislea** [comment]
Okay, thanks. Closing.
