### ISSUE TITLE
Ubuntu distribution, identified as "artful", is not currently supported

### ISSUE THREAD

**Issue by fcurti** [nodesource/distributions#622]
Please consider "artful" ubuntu distribution to be supported

**Comment by chrislea** [comment]
Artful is supported for all currently maintained release lines. Could you show us the exact command you're running and its output please so we can see what's going on?

**Comment by hd74** [comment]
$ curl -sL https://deb.nodesource.com/setup | sudo -E bash -

## Confirming "artful" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_0.10/dists/artful/Release'

## Your distribution, identified as "artful", is not currently supported

**Comment by chrislea** [comment]
The 0.10.x line has been EOL for years, so we don't build it anymore. Artful was released after it was EOL, so it's never been built for Artful.

It hasn't been getting security updates for years, so you **really** need to update to a supported version of Node **immediately**.
