### ISSUE TITLE
Deepin OS

### ISSUE THREAD

**Issue by alpinus4** [nodesource/distributions#624]
I got this when I was installing node 8.
"## Your distribution, identified as "unstable", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support"

**Comment by chrislea** [comment]
If you'd like this distribution to be supported, please make a PR with the appropriate alias against our [setup script](https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L258-L281). If it looks good we'll merge it in. Thanks!
