### ISSUE TITLE
solydxk-9 is not currently supported

### ISSUE THREAD

**Issue by jdall** [nodesource/distributions#625]
While Debian Stretch is supported in node 8.x, it appears that SolydXK-9, based on Debian 9, is not. 
Please consider adding it.
Thanks.

**Comment by chrislea** [comment]
If you'd like this distribution to be included, please create a pull request against our [setup script](https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L258-L281) with the appropriate alias. If it looks good we'll merge it in. Thanks!
