### ISSUE TITLE
RHEL6 repo files are corrupt

### ISSUE THREAD

**Issue by oss-chapman** [nodesource/distributions#626]
Hello, 
When trying to mirror https://rpm.nodesource.com/pub_6.x/el/6/x86_64/repodata/ for our company's internal use, We run into an issue. The repomd.xml (Date 6-Mar-2018) file is corrupt, or doesn't match the packages provided. 
Can you put up a new repo file?

Thanks!

**Comment by chrislea** [comment]
Hrm. It looks fine to me, but I went ahead and regenerated it just in case. Hope this helps.
