### ISSUE TITLE
Centos not supported - centos-release-7-3.1611.el7.centos.x86_64

### ISSUE THREAD

**Issue by roccokp** [nodesource/distributions#627]
Hello Team,
I'm trying to install node LST on my server but I received the following message

## Your distribution, identified as "centos-release-7-3.1611.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Is it possible to update the source to support 7-3.1611.el7.centos.x86_64 ?
Is there any possibility to install node even this error?

thx
rocco
-

**Comment by roccokp** [comment]
I verified my current version and I see the following

[root@myhost-22IT etc]# rpm --query centos-release
centos-release-7-4.1708.el7.centos.x86_64

**Comment by roccokp** [comment]
solved. in my case the proxy is the problem.
solved using

curl -kL https://rpm.nodesource.com/setup_8.x --proxy http://host:80 | bash -x -

**Comment by mokeyjay** [comment]
not work in my case :(

**Comment by igsu** [comment]
CentOS 7 is currently supported. 

Closing this now.
