### ISSUE TITLE
Node.js v0.12 distribution

### ISSUE THREAD

**Issue by dshaw** [nodesource/distributions#63]
Per @chrislea's previous experience with the v0.8 transition to v0.10 breaking a large number of builds, we're working on a strategy to make sure the same thing does not happen with the v0.12 release.

Given the number of issues the io.js team has encountered with native modules, there's a high likelihood that this will occur in v0.12.

@chris-prince has some useful suggestions in #33.

**Comment by thomaschaaf** [comment]
Postgres used to do it like this for debian:

    deb https://deb.nodesource.com/node ${DISTRO} latest #alias for 0.12 or whatever comes after that
    deb https://deb.nodesource.com/node ${DISTRO} 0.12
    deb https://deb.nodesource.com/node ${DISTRO} 0.10

**Comment by vincentwoo** [comment]
Any chance we can at least get 0.12 on node-devel?

**Comment by chrislea** [comment]
Hi all. We have 0.12.0 packages built!

They are "public" in the sense that you can reach them via the open interwebz, but we haven't made any official announcements yet because we'd love it if we could get a little sanity checking from the community first. Assuming you are set up with the mainline NodeSource repository (last published version was 0.10.36) then the following command should  switch you over to the 0.12.x repository.

```
sudo sed -i 's/node /node012 /g;' /etc/apt/sources.list.d/nodesource.list
```

After that a familiar

```
sudo apt-get update && sudo apt-get -y upgrade
```

should install 0.12.0 for you. If people could please take it out and kick the tires a bit I'd really appreciate it. Please let us know here if you find anything. Assuming it all looks good, we'll make an official announcement.

Thanks very much in advance!

**Comment by mlaccetti** [comment]
Got 0.12 running under utopic without any hiccups; taking it for a spin to ensure all is well.

**Comment by paambaati** [comment]
@chrislea Just curious, are 0.12.0 built packages available also for EL?

**Comment by chrislea** [comment]
@paambaati We're working on EL builds. Getting things to work for EL 5 is just an exercise in awfulness, but I'm giving it as much time / attention as I can.

**Comment by ripper2hl** [comment]
why no add update for version 0.12 in the 'normal'  ubuntu repositoriy ? , the release is 'stable' https://github.com/joyent/node/releases/tag/v0.12.0.
and installing nodejs 0.12 no problems under ubuntu 14.04 
Great job :+1:

**Comment by antwan1986** [comment]
Just wondering whenever this'll land for me via:
`deb https://deb.nodesource.com/node utopic main`

Certain vendors are seemingly bypassing `0.11` all of a sudden (only supporting `0.10` and `0.12`), such as here:
https://github.com/sass/node-sass-binaries

**Comment by mlaccetti** [comment]
@antwan1986 That's because 0.11 was the development version for 0.12.  Even numbers are the production ones.

**Comment by rvagg** [comment]
```
curl -sL https://deb.nodesource.com/setup_0.10 | bash -
```

```
curl -sL https://deb.nodesource.com/setup_0.12 | bash -
```

```
curl -sL https://deb.nodesource.com/setup_iojs_1.x | bash -
```

Pick one. We're about to announce this "officially" including more details about what's there and the rationale for the way we've done it, but you should be able to start using it now.

**Comment by EgoAleSum** [comment]
What about RPM packages?

**Comment by rvagg** [comment]
Coming, see https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories

The .debs for newer distros were the lowest-hanging fruit so we picked them off first, keep an eye on this repo for more news.

**Comment by samkrew** [comment]
May you add armhf binaries to https://deb.nodesource.com/node_0.12 ?

**Comment by rvagg** [comment]
@samkrew yes, it'll be coming, just like older Linux distros it's a bit of trickiness we're pushing down the road a little way. Please keep an eye on this repo for more news about it.

**Comment by chrislea** [comment]
Sorry about that @samkrew, the ARM builds for 0.12.0 should be in the repo now.

**Comment by jrnewell** [comment]
Will the node_0.12 build be updated regularly?  It looks like it is still on v0.12.0.

**Comment by chrislea** [comment]
Yes, 0.12.1 should be in the repo in a few hours.

**Comment by callerc1** [comment]
0.12.0 upgrade smooth for me. Great work :)

**Comment by EgoAleSum** [comment]
Any news about RPMs for EL?

**Comment by chrislea** [comment]
They should be up today.

**Comment by bizmurr** [comment]
Is 0.12.1 up for deb? My node version still reports 0.12.0.

```
nodejs --version
v0.12.0

sudo apt-cache policy nodejs

nodejs:
  Installed: 0.12.0-1nodesource1~trusty1
  Candidate: 0.12.0-1nodesource1~trusty1
  Version table:
 *** 0.12.0-1nodesource1~trusty1 0
        500 https://deb.nodesource.com/node_0.12/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     0.10.25~dfsg2-2ubuntu1 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
```

**Comment by tehsenaus** [comment]
How do I get RPMs for 0.12?

**Comment by EgoAleSum** [comment]
@chrislea still can't find Node 0.12.x on yum:

    $ sudo yum list nodejs
    Loaded plugins: priorities, update-motd, upgrade-helper
    Available Packages
    nodejs.x86_64                                 0.10.38-1nodesource.el7.centos                                  nodesource

**Comment by jamiemcconnell** [comment]
Just wondering if there is any update on the ETA for EL6 RPMs?

**Comment by it-can** [comment]
Any news on this?

**Comment by owenallenaz** [comment]
+1 to @jamiemcconnell question.

**Comment by sboulkour** [comment]
Hi there,

any news regarding RPMS for EL7 ?

**Comment by b-long** [comment]
Has anyone tried the packages that @owenallenaz pointed out?

**Comment by rvagg** [comment]
The README @ https://github.com/nodesource/distributions has updated instructions for io.js and 0.12 on Debian / Ubuntu, although support is still limited on older systems so don't expect full coverage (build chain dramas make this really hard).

RPMs are being built for Node 0.12 for Fedora and EL6 and EL7 but you'll have to download them manually from http://rpm.nodesource.com/pub_0.12/ as the setup procedure is still being worked on and we need some people to test the RPMs. io.js v2.x RPMs are also available for Fedora and EL7 at https://rpm.nodesource.com/pub_iojs_2.x/ - we'd love feedback on these RPMs if you're using them.

**Comment by owenallenaz** [comment]
I just installed the 12 on Centos 6 running the following steps:

```bash
# remove old version, replace with your specific needs
sudo yum remove nodejs
# download the file
sudo curl -O https://rpm.nodesource.com/pub_0.12/el/6/x86_64/nodejs-0.12.7-1nodesource.el6.x86_64.rpm
sudo rpm -Uvh nodejs-0.12.7-1nodesource.el6.x86_64.rpm
node -v
# v0.12.7
npm -v
# 2.11.3
```

So far everything appears to be running fine, will report back if I have an issue.

**Comment by empierre** [comment]
Node.js v0.12 v0.10 segfault on raspberry B/B+ running Raspbian 7 Wheezy:
Linux 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux
What shall I report back more ?

**Comment by empierre** [comment]
@rvagg looks like it works from the nodejs site. I guess that for many people armv6 should not be present on nodesource wich is so well referenced on google... that would save people lot of time ! thanks for the link !

**Comment by rvagg** [comment]
@empierre good point, I don't see a reference to ARMv6 or Pi on our documentation, I'll try and get around to fixing that (although a PR would be welcome if you have the time!)

**Comment by retrohacker** [comment]
0.12 has been released for quite some time. Closing this issue as stale.
