### ISSUE TITLE
Your distribution, identified as "centos-release-7-4.1708.el7.centos.x86_64", is not currently supported

### ISSUE THREAD

**Issue by aswans** [nodesource/distributions#630]
“curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -” ，I got an error when installing node.js，Your distribution, identified as "centos-release-7-4.1708.el7.centos.x86_64", is not currently supported。

**Comment by franta** [comment]
Message is confusing, please change:
http_proxy=... https_proxy=... curl -sL https://rpm.nodesource.com/setup_8.x | bash -

to:
http_proxy=... https_proxy=... curl -sL https://rpm.nodesource.com/setup_8.x | http_proxy=... https_proxy=... bash -

**Comment by igsu** [comment]
Support for CentOS 7 was added a long time ago. Closing this now.
