### ISSUE TITLE
Installation fails on Deepin OS (LTS Version from official download site)

### ISSUE THREAD

**Issue by davidherzlos** [nodesource/distributions#638]
My OS is Deepin 15.5, is Debian based: https://www.deepin.org/en/

When i run on terminal:
```
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
```
I get:

>Your distribution, identified as "unstable", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Thanks & Regards,
David OC

![deepinscreenshot_deepin-terminal_20180410093326](https://user-images.githubusercontent.com/4148480/38563352-418ff0ac-3ca2-11e8-9d7a-461ad4972367.png)

**Comment by chrislea** [comment]
If you'd like to see this included, please issue a PR against our [setup script](https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L258-L287) to make the appropriate alias. If it looks good we'll merge it in. Thanks!

**Comment by davidherzlos** [comment]
I've made a pull request. Thanks!

**Comment by XTechnologyTR** [comment]
ERSION=node_14.x

DISTRO="$(dpkg --status tzdata|grep Provides|cut -f2 -d'-')"

echo "deb https://deb.nodesource.com/$VERSION $DISTRO main" | sudo tee /etc/apt/sources.list.d/nodesource.list

echo "deb-src https://deb.nodesource.com/$VERSION $DISTRO main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list

curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -

sudo apt-get update

sudo apt-get install nodejs
