### ISSUE TITLE
Not able to install npm - No more mirrors to try

### ISSUE THREAD

**Issue by abhijitvikash123** [nodesource/distributions#647]
Hi Support, 

I am trying to install npm in /usr/local/bin using document https://www.rosehosting.com/blog/how-to-install-node-js-and-npm-on-centos-7/ but getting below Error. 

I also tried clearing the cache https://access.redhat.com/articles/1320623 , but to no help. This issue is reoccurring. 

[root@ip-10-237-167-169 bin]# yum install -y gcc-c++ make
Loaded plugins: fastestmirror
MariaDB | 2.9 kB 00:00:00
base | 3.6 kB 00:00:00
docker | 2.9 kB 00:00:00
epel | 4.7 kB 00:00:00
extras | 3.4 kB 00:00:00
https://rpm.nodesource.com/setup_7.x/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/

 One of the configured repositories failed (nodesource yum repository),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=nodejs ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable nodejs
        or
            subscription-manager repos --disable=nodejs

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=nodejs.skip_if_unavailable=true

failure: repodata/repomd.xml from nodejs: [Errno 256] No more mirrors to try.
https://rpm.nodesource.com/setup_7.x/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

**Comment by m-anish** [comment]
Okay, more comments

`apt install nodejs fails` and is super slow
`aptitude install nodejs` works like a charm!

**Comment by chrislea** [comment]
There are a few issues I see here. First is that you're trying to install Node 7.x, which is EOL and should **definitely** not be used anymore. I'd recommend installing Node 8.x.

It's failing looking for https://rpm.nodesource.com/setup_7.x/repodata/repomd.xml which makes sense because there's nothing there. What's the output from running the following command as root?
```
% curl -sL https://rpm.nodesource.com/setup_8.x | bash -
```
