### ISSUE TITLE
Your distribution, identified as "redhat-release-server-6Server-6.7.0.3.0.1.el6.x86_64", is not currently supported,

### ISSUE THREAD

**Issue by acayci** [nodesource/distributions#650]
Hello,

I am getting the above referenced error message while I try to enable node

bash-4.1$ curl -L https://rpm.nodesource.com/setup_6.x | bash -x.

At least one person posted a same issue.  However I wasn't sure if there was a solution.  

Any help is much appreciated.  

Mustafa

======================

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0+ print_status 'Installing the NodeSource Node.js 6.x repo...'
101  6981  101  6981    0     0  13259      0 --:--:-- -++ echo 'Installing the NodeSource Node.js 6.x repo...'
-:--:-- --:++ sed -r 's/\\n/\\n## /mg'
--:-- 14574
+ local 'outp=Installing the NodeSource Node.js 6.x repo...'
+ echo

+ echo -e '## Installing the NodeSource Node.js 6.x repo...'
## Installing the NodeSource Node.js 6.x repo...
+ echo

+ print_status 'Inspecting system...'
++ echo 'Inspecting system...'
++ sed -r 's/\\n/\\n## /mg'
+ local 'outp=Inspecting system...'
+ echo

+ echo -e '## Inspecting system...'
## Inspecting system...
+ echo

+ '[' '!' -x /bin/rpm ']'
+ echo '+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release'
+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
++ rpm -q --whatprovides redhat-release
+ DISTRO_PKG=redhat-release-server-6Server-6.7.0.3.0.1.el6.x86_64
+ echo '+ uname -m'
+ uname -m
++ uname -m
+ UNAME_ARCH=x86_64
+ '[' Xx86_64 == Xi686 ']'
+ '[' Xx86_64 == Xx86_64 ']'
+ DIST_ARCH=x86_64
+ [[ redhat-release-server-6Server-6.7.0.3.0.1.el6.x86_64 =~ ^(redhat|centos|cloudlinux|sl)- ]]
+ DIST_TYPE=el
+ [[ redhat-release-server-6Server-6.7.0.3.0.1.el6.x86_64 =~ ^system-release-201[4-9]\. ]]
++ echo redhat-release-server-6Server-6.7.0.3.0.1.el6.x86_64
++ sed -r 's/^[[:alpha:]]+-release(-server|-workstation)?-([0-9]+).*$/\2/'
+ DIST_VERSION=6
+ [[ 6 =~ ^[0-9][0-9]?$ ]]
+ RELEASE_URL_VERSION_STRING=el6
+ RELEASE_URL=https://rpm.nodesource.com/pub_6.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm
+ print_status 'Confirming "el6-x86_64" is supported...'
++ echo 'Confirming "el6-x86_64" is supported...'
++ sed -r 's/\\n/\\n## /mg'
+ local 'outp=Confirming "el6-x86_64" is supported...'
+ echo

+ echo -e '## Confirming "el6-x86_64" is supported...'
## Confirming "el6-x86_64" is supported...
+ echo

+ exec_cmd_nobail 'curl -sLf -o /dev/null '\''https://rpm.nodesource.com/pub_6.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'\'''
+ echo '+ curl -sLf -o /dev/null '\''https://rpm.nodesource.com/pub_6.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'\'''
+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_6.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'
+ bash -c 'curl -sLf -o /dev/null '\''https://rpm.nodesource.com/pub_6.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'\'''

+ RC=7
+ [[ 7 != 0 ]]
+ print_status 'Your distribution, identified as "redhat-release-server-6Server-6.7.0.3.0.1.el6.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support'
++ echo 'Your distribution, identified as "redhat-release-server-6Server-6.7.0.3.0.1.el6.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support'
++ sed -r 's/\\n/\\n## /mg'
+ local 'outp=Your distribution, identified as "redhat-release-server-6Server-6.7.0.3.0.1.el6.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support'
+ echo

+ echo -e '## Your distribution, identified as "redhat-release-server-6Server-6.7.0.3.0.1.el6.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support'
## Your distribution, identified as "redhat-release-server-6Server-6.7.0.3.0.1.el6.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
+ echo

+ exit 1

**Comment by acayci** [comment]
hi  Chris,

Yes I am.

Mustafa

**Comment by chrislea** [comment]
Please reference the first item in the [distributions FAQ](https://github.com/nodesource/distributions/#questions).

**Comment by acayci** [comment]
Hi Chris,  I closed the putty session and open again.  I went into bash prompt.  I issued the same command.

bash-4.1$ curl -sL https://rpm.nodesource.com/setup_6.x | sudo -E bash -
sudo: Illegal option -E
usage: sudo -V | -h | -L | -l | -v | -k | -K | [-H] [-P] [-S] [-b] [-p prompt]
            [-u username/#uid] -s | <command>

This time I am getting sudo illegal option -E.

Mustafa
