### ISSUE TITLE
Fedora 28 not supported

### ISSUE THREAD

**Issue by Jesus-Gonzalez** [nodesource/distributions#655]
Hello,

When running:

```bash
curl` --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -
```

I get:

`Your distribution, identified as "fedora-release-28-1.noarch", is not currently supported`

Awaiting for the Fedora 28 package to be distributed.

Thank you :slightly_smiling_face: 

EDIT: nodejs 8.11.x is already in the Fedora 28 repository :sweat_smile: 

It would still be interesting to have the package distributed by Node directly, so we get the latest updates/security fixes from the Node's team desk directly.

Also, this issue also applies to installing Node 10.x

**Comment by chrislea** [comment]
FC28 doesn't have any packages because there have been no new applicable Node releases since FC28 went live on Monday. As soon as there's a new version of 8.x or 10.x released, it will be available in the repository for FC28.

**Comment by ai** [comment]
@chrislea Do we also need to fix installer script? Not it says that your distributive is not supported even for Fedor 27.

**Comment by chrislea** [comment]
There should be no changes required for the installer script. It doesn't have any versions hardwired in.
