### ISSUE TITLE
Support for Ubuntu 15.04 "vivid"

### ISSUE THREAD

**Issue by funnylookinhat** [nodesource/distributions#66]
A lot of devs ( myself included ) have begun moving to ubuntu+1 ( 15.04 codenamed "vivid" ) - could you add support for that release to your deb scripts?

**Comment by rvagg** [comment]
@funnylookinhat no, we won't be adding this till it goes stable in April, it's too much of a moving target. _But_, you should be able to manually add it in by aliasing utopic.

```
apt-get update && apt-get install curl apt-transport-https -y
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
echo 'deb https://deb.nodesource.com/node utopic main' > /etc/apt/sources.list.d/nodesource.list
echo 'deb-src https://deb.nodesource.com/node utopic main' >> /etc/apt/sources.list.d/nodesource.list
apt-get update && apt-get install nodejs -y
node -v && npm -v
```

Additionally, to support building native add-ons:

```
apt-get install build-essential python -y
```

To confirm a full, working installation:

```
curl -sL https://deb.nodesource.com/test | bash -
```

**Comment by funnylookinhat** [comment]
@rvagg That works!  Thanks for the suggestion.
