### ISSUE TITLE
Your distribution, identified as "redhat-release-server-6Server-6.7.0.3.el6.x86_64", is not currently supported

### ISSUE THREAD

**Issue by riz100** [nodesource/distributions#662]
## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

**Comment by chrislea** [comment]
That distro is definitely supported. Can you show the full output of the setup script with the `-x` option passed to `bash` IE:
```
curl -sL https://rpm.nodesource.com/setup_8.x | bash -x -
```
Also, are you behind a proxy?

**Comment by chrislea** [comment]
If you're behind a proxy, please look at the first issue in [the FAQ](https://github.com/nodesource/distributions/#faq).
