### ISSUE TITLE
Make python-minimal an optional dependency

### ISSUE THREAD

**Issue by mal** [nodesource/distributions#664]
_Feature Request_

These distributions are massively helpful, but it would be really nice to be able to use them while also being able to opt out of the `python-minimal` dependency (deb). By moving it to an optional dependency users that don't utilise native modules (and thus have no need of `node-gyp`) can avoid the python v2 install by using the `--no-install-recommends` flag during installation.

Thanks 🙂

**Comment by chrislea** [comment]
This has come up before. Unfortunately, there's no solution that meets everybody's needs, and the standard case is that we need to support people who might want or need native modules. So the `python` dependency is there to stay.
