### ISSUE TITLE
Your distribution, identified as "lemur-3", is not currently supported

### ISSUE THREAD

**Issue by liquidlemur** [nodesource/distributions#667]
Hi, trying to install on my Liquid Lemur Linux 3 distro and nogo. Lemur-3 is a Debian 9 based distro. Debian is supposed to be supported. I'll assume you're pulling info from the lsb-release file?

**Comment by chrislea** [comment]
If you'd like this distribution to be supported, please issue a PR against [the setup script](https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L201-L231). If it looks good we'll merge it in. Thanks!
