### ISSUE TITLE
Ubuntu "bionic" is not currently supported

### ISSUE THREAD

**Issue by jarrodek** [nodesource/distributions#671]
It would be nice to have support for "bionic" release of Ubuntu.
Is this planned?

**Comment by chrislea** [comment]
Bionic is definitely supported, I'm actually typing this from a machine running Bionic right now.

Can you please post the full output of the setup script where you saw this error?

**Comment by jarrodek** [comment]
Sorry, I just noticed this message. I will do this later when at home.

**Comment by jarrodek** [comment]
I just tried to install node again and it worked.
I really don't know why yesterday was different.

Anyway, closing.

**Comment by sdspieg** [comment]
So is this supposed to work? Because when I try to install, I get
```
Err:17 http://ppa.launchpad.net/gnome-terminator/ppa/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/gnome-terminator/ppa/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting
```
