### ISSUE TITLE
fedora-release-27-1.noarch not currently supported

### ISSUE THREAD

**Issue by fernandohg97** [nodesource/distributions#672]
Tried to install nodejs via package manager and it shows me a message that my distro is not supported.
What should I do?

**Comment by chrislea** [comment]
Fedora 27 is definitely supported. Can you put the full output from the setup script here so we can see what's going on? Ideally please run it with the `-x` switch IE:
```
curl -sL https://rpm.nodesource.com/setup_8.x | bash -x -
```

**Comment by fernandohg97** [comment]
No

**Comment by chrislea** [comment]
What does the output of the command:
```
rpm -q --whatprovides redhat-release
```
give you?

**Comment by fernandohg97** [comment]
This:

![screenshot from 2018-05-23 23-09-02](https://user-images.githubusercontent.com/17859146/40467400-a3d8fa02-5ede-11e8-8952-b338700547fb.png)
