### ISSUE TITLE
Incorrest version of node getting installed for setup_6.x

### ISSUE THREAD

**Issue by sumitsj** [nodesource/distributions#673]
I was trying to install node version 6.x inside docker using below commands - 

RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs

I had also added below line to verify node version and showed me **v8.10.0**
RUN echo "Node Version $(node --version)"

Where exactly I am getting wrong? or is this an issue?

**Comment by chrislea** [comment]
What distribution is being used for the Docker image here?

**Comment by sumitsj** [comment]
Distribution : Ubuntu
Docker Version: 17.12.0-ce-mac49 (21995)
OS: Mac High Sierra

[Dockerfile.txt](https://github.com/nodesource/distributions/files/2043654/Dockerfile.txt)

**Comment by sonicdoe** [comment]
You’re probably installing Node.js v8 from the official Ubuntu repositories, see https://github.com/nodesource/distributions/issues/657. You can run `apt policy nodejs` to verify which one is installed.

**Comment by Apollon77** [comment]
we had several issues from "ioBroker" (nodejs based smart home software) on mainy raspberry and such since last friday/saturday.

Users uses the nodesource 8.x command and ended up in having node 8 and no npm!!

Is there anything more known to this?

**Comment by chrislea** [comment]
Again, as @sonicdoe notes above, please run
```
apt policy nodejs
```
and see if our repository is the one you're getting the package from. If there is still confusion about what's happening, please re-open this issue and post the full output of running the installer script as well as `apt policy nodejs` so we can try and see what's going on.

**Comment by Apollon77** [comment]
Ok, the following happens:

When node 6 is installed or should be installed but the os updated the node version in their repo (Ubuntu 18.04 and it seems also raspbian after a apt-get Update/Upgrade) then the Version in the repo is 8.x and then this is used over nodesource repo. 

Should an install from your repo not pin the major Version to prevent that? Seems that this was never needed because original repos were always veeeery old ... but now it changed

**Comment by chrislea** [comment]
The default for `apt` is just to install the newest version it sees in any repository. If you want to pin an older version than what the default is for your distribution that's up to you, but we're not going to try and admin an end user's machine in that way.

**Comment by Apollon77** [comment]
completely understandable :-) thank you for clarification

**Comment by sonicdoe** [comment]
I can understand not wanting to pin NodeSource’s repository on the user’s machine, however, the current approach might only become more confusing as time goes on and distributions ship newer Node.js versions.

This is complicated by the fact that Ubuntu’s `nodejs` package does not include `npm` whereas NodeSource’s does. I can imagine a situation where APT upgrades to a newer version (while also switching repositories) and suddenly the `npm` command is gone.
