### ISSUE TITLE
Ubuntu Xenial (16.04) is unsupported

### ISSUE THREAD

**Issue by murphyj** [nodesource/distributions#674]
Hi

I'm getting the following error message when trying to install Node 6.x or 8.x

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11098  100 11098    0     0  16119      0 --:--:-- --:--:-- --:--:-- 16130

## Installing the NodeSource Node.js 8.x LTS Carbon repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease
Fetched 109 kB in 3s (35.9 kB/s)
Reading package lists... Done

## Confirming "xenial" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/xenial/Release'

## Your distribution, identified as "xenial", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to
be considered for support
```

I believe Xenial should be a priority to support and here's my reason why...

Windows 10 currently ships with Ubuntu Xenial (16.04) as part of it's supported Linux Subsystem. This should surely mean that it should be more widely supported as I suspect this is a popular setup for Windows 10 users who are forced to use Windows (due to corporate security policy).

**Comment by chrislea** [comment]
Xenial is _definitely_ supported. Can you get to the release file from the target machine? It's here:
```
https://deb.nodesource.com/node_8.x/dists/xenial/Release
```
Also, are you behind a proxy?

**Comment by phackwer** [comment]
We had similar issues starting yesterday in 2 different projects. 

Seems like node-js is only installing now after a dist-upgrade in 16.04. This happened (and can be reproduced) in a dockerised.


Command that was raising error:

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - \
  && apt-get update -y \
  && apt-get install -y --allow-unauthenticated --fix-missing nodejs \
  && npm install -g gulp -y \
  && npm install -g bower --allow-root \
  && rm -rf /var/lib/apt/lists/*

"Solution" for the dockerised environment was to run this before node install:

# UBUNTU BASIC SETUP
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d
RUN apt-get update -y --allow-unauthenticated --fix-missing \
    && apt-get dist-upgrade -y --allow-unauthenticated --fix-missing \
    && apt-get upgrade -y --allow-unauthenticated --fix-missing \
    && apt-get install -y --allow-unauthenticated --fix-missing software-properties-common git

**Comment by lazzarello** [comment]
The `Release` file is missing for `node_10.x`

Here's my output

```
root@6199ce532986:/# apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Ign:2 https://deb.nodesource.com/node_10.x stable InRelease
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
Ign:4 https://deb.nodesource.com/node_10.x stable Release                          
Ign:5 https://deb.nodesource.com/node_10.x stable/main amd64 Packages              
Get:6 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Ign:7 https://deb.nodesource.com/node_10.x stable/main all Packages
Ign:5 https://deb.nodesource.com/node_10.x stable/main amd64 Packages
Ign:7 https://deb.nodesource.com/node_10.x stable/main all Packages 
Ign:5 https://deb.nodesource.com/node_10.x stable/main amd64 Packages
Ign:7 https://deb.nodesource.com/node_10.x stable/main all Packages 
Ign:5 https://deb.nodesource.com/node_10.x stable/main amd64 Packages
Ign:7 https://deb.nodesource.com/node_10.x stable/main all Packages
Ign:5 https://deb.nodesource.com/node_10.x stable/main amd64 Packages
Ign:7 https://deb.nodesource.com/node_10.x stable/main all Packages
Err:5 https://deb.nodesource.com/node_10.x stable/main amd64 Packages
  404  Not Found
Get:8 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Ign:7 https://deb.nodesource.com/node_10.x stable/main all Packages
Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [1042 kB]
Fetched 1365 kB in 2s (630 kB/s)   
Reading package lists... Done
W: The repository 'https://deb.nodesource.com/node_10.x stable Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://deb.nodesource.com/node_10.x/dists/stable/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by chrislea** [comment]
The release file for Xenial is definitely there at this URI:
```
https://deb.nodesource.com/node_10.x/dists/xenial/Release
```
Can you get to it from a web browser?

**Comment by lazzarello** [comment]
Ah, I got confused since I typed "stable" but the instructions used `DISTRO="$(lsb_release -s -c)"`

Everything is fine now. Thanks.
