### ISSUE TITLE
node and nodejs version and warning message

### ISSUE THREAD

**Issue by UNiXMIT** [nodesource/distributions#676]
I have installed NodeJS on my Pi using these commands as root:
`curl -sL https://deb.nodesource.com/setup_10.x | bash -`
`apt-get install -y nodejs`

Now I get:
`node –v`
`v7.10.0`
`nodejs –v`
`v10.3.0`

Is this correct? The reason I ask is because is because I see this warning message sometimes:
`npm WARN npm npm does not support Node.js v7.10.0`
`npm WARN npm You should probably upgrade to a newer version of node as we`
`npm WARN npm can't make any promises that npm will work with this version.`
`npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.`
`npm WARN npm You can find the latest version at https://nodejs.org/`

Forgive my ignorance with this but as I see it my NodeJS version is 10.3 so is this warning referring to my node version 7.10 and should this match my NodeJS version?

Thanks for any help.

**Comment by chrislea** [comment]
I suspect you already had a version of node installed, and you installed ours alongside it. What is the output of:
```
dpkg -S /usr/bin/node
```
?

Also, what Linux distribution are you running on the board?

**Comment by UNiXMIT** [comment]
That might explain it. Output is:
nodejs: /usr/bin/node

Does that mean I had a previous version? I don’t get a version number. If so I’ll have to remove it. I’m running Debian 9. 

Thanks

**Comment by chrislea** [comment]
Hrm. Well, I expect there's something you need to remove, I'm just not sure what. What's the output of:
```
dpkg -l | grep nodejs
```
?

**Comment by UNiXMIT** [comment]
Well that seems to pick up the right version:

ii  nodejs                             10.3.0-1nodesource1              arm64        Node.js event-based server-side javascript engine

**Comment by chrislea** [comment]
I'd try just removing anything node related and then running the installer again.
```
apt-get remove 'nodejs*'
apt-get remove 'npm*'
curl -sL https://deb.nodesource.com/setup_10.x | bash -
```

**Comment by UNiXMIT** [comment]
Thanks I’ll give it a go and report back. Thanks for the help.

**Comment by UNiXMIT** [comment]
Well I tried it and it's still the same:
`node –v`
`v7.10.0`
`nodejs –v`
`v10.3.0`

I might try removing them again and try those commands to see if anything is found that may have been leftover.

**Comment by UNiXMIT** [comment]
Bingo. I removed nodejs* and npm and tried node -v and it still showed me v7.10.0
So I did `which node` which showed me the location of it. I removed that and reinstalled and now all is good. Thanks for the help in tracking this down. Much appreciated.
