### ISSUE TITLE
problem with nodejs update

### ISSUE THREAD

**Issue by Devhercule** [nodesource/distributions#678]
I would like to update nodejs on centos 7, but not supported !!!

I have this error :

`## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Your distribution, identified as "centos-release-7-2.1511.el7.centos.2.10.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
`

**Comment by chrislea** [comment]
Node 7.x is EOL and should never be installed at this point. Please use Node 8.x.

**Comment by Devhercule** [comment]
I'm already using Node 8.x.

`curl  -sL https://rpm.nodesource.com/setup_8.x | sudo -E bash -`

**Comment by igsu** [comment]
Closing this now as CentOS 7 is currently supported.
