### ISSUE TITLE
Security updates for all active release lines, June 2018

### ISSUE THREAD

**Issue by jagregory** [nodesource/distributions#681]
New versions of Node have been published with security updates, see: [Security updates for all active release lines, June 2018](https://groups.google.com/d/msg/nodejs-sec/lsXouy5LPFo/PmN3ky7CAwAJ)

What is the process/timeline for these releases being incorporated into the nodesource packages?

Cheers :)

**Comment by chrislea** [comment]
All of the security releases should be in our repos now. Ref from my laptop:
```
chl@mirel:~$ apt-cache policy nodejs
nodejs:
  Installed: 10.4.1-1nodesource1
  Candidate: 10.4.1-1nodesource1
  Version table:
 *** 10.4.1-1nodesource1 500
        500 https://deb.nodesource.com/node_10.x bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     8.10.0~dfsg-2 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```
Closing.

**Comment by jagregory** [comment]
👏 Thanks Chris for the super fast response.
