### ISSUE TITLE
Distribution, identified as "Tyche", is not currently supported

### ISSUE THREAD

**Issue by progguru** [nodesource/distributions#682]
While trying to install nodejs by typing in terminal `curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
` I get the following message:

> ##

 Installing the NodeSource Node.js 8.x LTS Carbon repo...

Populating apt-get cache...

 apt-get update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Stary:2 http://www.deb-multimedia.org stretch InRelease                        
Ign:3 http://ftp.debian.org/debian stretch InRelease                           
Stary:4 http://security.debian.org stretch/updates InRelease                   
Stary:5 http://dl.google.com/linux/chrome/deb stable Release                   
Stary:6 http://ftp.debian.org/debian stretch Release                           
Stary:7 https://sparkylinux.org/repo stable InRelease    
Stary:8 https://sparkylinux.org/repo testing InRelease
Czytanie list pakietów... Gotowe

 Confirming "Tyche" is supported...

 curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/Tyche/Release'

 Your distribution, identified as "Tyche", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
>##
My distribution details are:
>##
Distributor ID:	Sparky
Description:	SparkyLinux
Release:	4
Codename:	Tyche
>##
Kernel release in my machine is:
>##
4.9.0-6-amd64
>##
Please add support to forementioned distribution.

**Comment by chrislea** [comment]
If you'd like this distribution to be supported, please issue a pull request against our [setup script build sources](https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L201-L233). If it looks good we'll merge it in. Thanks.
