### ISSUE TITLE
Failed to install node.js repository

### ISSUE THREAD

**Issue by shahrukhbari99** [nodesource/distributions#685]
I am trying to install node.js repository using command **sudo add-apt-repository ppa:chris-lea/node.js** but I am getting error message **E: The repository 'http://ppa.launchpad.net/chris-lea/node.js/ubuntu bionic Release' does not have a Release file** . Can you help ?

**Comment by chrislea** [comment]
You're trying to use my old Launchpad PPA which is no longer maintained. Please read the installation instructions [here](https://github.com/nodesource/distributions/).

**Comment by shahrukhbari99** [comment]
Thanks Chris
