### ISSUE TITLE
Add Archive property to Release file

### ISSUE THREAD

**Issue by r4ny** [nodesource/distributions#686]
`unattended-upgrades` needs two properties, `Origin` and `Archive`.

The current [`Release`](https://deb.nodesource.com/node_8.x/dists/xenial/Release) file does not contain `Archive` property.

**Comment by chrislea** [comment]
Unfortunately this isn't supported by the `reprepro` tool that we use to manage the repositories. We are looking into other options that support more features, but our automation setup is currently tied to `reprepro` fairly tightly so this is not a trivial operation. We'll keep this request in mind though moving forward.
