### ISSUE TITLE
Error message when I try to install on elive (What can be done now?)

### ISSUE THREAD

**Issue by knittingdiamonds** [nodesource/distributions#69]
>>> curl -sL https://deb.nodesource.com/setup | bash -

## Populating apt-get cache...

+ apt-get update
Hit http://dl.google.com stable Release.gpg
Hit http://repository.spotify.com stable Release.gpg                           
Get:1 http://linux.dropbox.com wheezy Release.gpg [489 B]                      
Hit http://dl.google.com stable Release                                        
Hit http://repository.spotify.com stable Release                               
Hit http://ftp.debian.org wheezy Release.gpg                                   
Get:2 http://linux.dropbox.com wheezy Release [2,601 B]                        
Hit http://ftp.debian.org wheezy Release                                       
Hit http://repository.spotify.com stable/non-free i386 Packages                
Hit http://dl.google.com stable/main i386 Packages                             
Get:3 http://linux.dropbox.com wheezy/main i386 Packages [1,150 B]             
Get:4 http://repository.elivecd.org wheezy Release.gpg [836 B]                 
Hit http://ftp.debian.org wheezy/main i386 Packages                            
Get:5 http://repository.elivecd.org wheezy Release [30.2 kB]                   
Hit http://ftp.debian.org wheezy/contrib i386 Packages                         
Hit http://ftp.debian.org wheezy/non-free i386 Packages                        
Hit http://repository.elivecd.org wheezy/main i386 Packages                    
Hit http://ftp.debian.org wheezy/contrib Translation-en                        
Hit http://ftp.debian.org wheezy/main Translation-en                           
Get:6 http://www.deb-multimedia.org wheezy Release.gpg [819 B]                 
Ign http://dl.google.com stable/main Translation-en_US                         
Hit http://ftp.debian.org wheezy/non-free Translation-en                       
Hit http://www.deb-multimedia.org wheezy Release                               
Ign http://www.deb-multimedia.org wheezy Release                               
Ign http://dl.google.com stable/main Translation-en                            
Ign http://repository.spotify.com stable/non-free Translation-en_US            
Hit http://repository.elivecd.org wheezy/elive i386 Packages                   
Ign http://www.deb-multimedia.org wheezy/main i386 Packages/DiffIndex          
Ign http://repository.spotify.com stable/non-free Translation-en               
Get:7 http://repository.elivecd.org wheezy/efl i386 Packages [40.8 kB]         
Ign http://linux.dropbox.com wheezy/main Translation-en_US                     
Ign http://www.deb-multimedia.org wheezy/non-free i386 Packages/DiffIndex      
Ign http://linux.dropbox.com wheezy/main Translation-en                     
Hit http://www.deb-multimedia.org wheezy/main i386 Packages                    
Hit http://www.deb-multimedia.org wheezy/non-free i386 Packages                
Hit http://repository.elivecd.org wheezy/games i386 Packages             
Hit http://repository.elivecd.org wheezy/ports i386 Packages             
Hit http://repository.elivecd.org wheezy/fixes i386 Packages             
Hit http://repository.elivecd.org wheezy/drivers i386 Packages           
Hit http://repository.elivecd.org wheezy/tests i386 Packages             
Hit http://repository.elivecd.org wheezy/multimedia i386 Packages       
Hit http://repository.elivecd.org wheezy/non-free i386 Packages    
Ign http://www.deb-multimedia.org wheezy/main Translation-en_US                
Ign http://www.deb-multimedia.org wheezy/main Translation-en                   
Ign http://www.deb-multimedia.org wheezy/non-free Translation-en_US            
Ign http://www.deb-multimedia.org wheezy/non-free Translation-en               
Ign http://repository.elivecd.org wheezy/drivers Translation-en_US             
Ign http://repository.elivecd.org wheezy/drivers Translation-en
Ign http://repository.elivecd.org wheezy/efl Translation-en_US
Ign http://repository.elivecd.org wheezy/efl Translation-en
Ign http://repository.elivecd.org wheezy/elive Translation-en_US
Ign http://repository.elivecd.org wheezy/elive Translation-en
Ign http://repository.elivecd.org wheezy/fixes Translation-en_US
Ign http://repository.elivecd.org wheezy/fixes Translation-en
Ign http://repository.elivecd.org wheezy/games Translation-en_US
Ign http://repository.elivecd.org wheezy/games Translation-en
Ign http://repository.elivecd.org wheezy/main Translation-en_US
Ign http://repository.elivecd.org wheezy/main Translation-en
Ign http://repository.elivecd.org wheezy/multimedia Translation-en_US
Ign http://repository.elivecd.org wheezy/multimedia Translation-en
Ign http://repository.elivecd.org wheezy/non-free Translation-en_US
Ign http://repository.elivecd.org wheezy/non-free Translation-en
Ign http://repository.elivecd.org wheezy/ports Translation-en_US
Ign http://repository.elivecd.org wheezy/ports Translation-en
Ign http://repository.elivecd.org wheezy/tests Translation-en_US
Ign http://repository.elivecd.org wheezy/tests Translation-en
Fetched 77.0 kB in 29s (2,622 B/s)
Reading package lists... Done
W: GPG error: http://www.deb-multimedia.org wheezy Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5C808C2B65558117

## Installing packages required for setup: apt-transport-https...

+ apt-get install -y apt-transport-https 2>&1 > /dev/null

## Confirming "Topaz+" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node/dists/Topaz+/Release'

**Comment by rvagg** [comment]
What we need to know is:

1. Does Elive actually track Ubuntu or Debian or is it something different?
2. What do the version names in Elive map to in Debian or Ubuntu version names? This doesn't have to be perfect or complete but at start would be helpful. e.g. You have "Topaz+", what does it map to as an Ubuntu or Debian version? What is the base system they have started from?

Can you find some docs for us that describe any of this?

What we do is put mappings into our setup file, like this: https://github.com/nodesource/distributions/blob/aace33385577107b704444d3c60729a7c9eb57a4/deb/setup#L76-L82
