### ISSUE TITLE
Installing Node JS on Amazon AMI

### ISSUE THREAD

**Issue by maane018** [nodesource/distributions#690]
When I am trying to install Node js on Amazon EC2, I am getting this error:
Your distribution, identified as "system-release-2-3.amzn2.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support.

Installation Steps: https://nodejs.org/en/download/package-manager/
Can you please include this in the support list?

**Comment by JakubMatejka** [comment]
+1 see https://travis-ci.org/keboola/developer-portal/jobs/397211205

**Comment by nihammer** [comment]
I think that there is something wrong with the latest version of amazonlinux image of hub.docker.com.
Before:
```
bash-4.2# cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2018.03"
```

Now:
```
bash-4.2# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
```

My temporary solution is:
Fix Dockerfile:
```
FROM amazonlinux:2018.03
```

**Comment by flyapplefly** [comment]
So what should I do to make it work?

**Comment by chrislea** [comment]
I've updated the installer scripts to handle the change that @nihammer noted in the newest Amazon Linux AMI. Can you try running it again please and let me know if it works @flyapplefly ?
