### ISSUE TITLE
Raspberry Pi 3 CentOS 7 issue 

### ISSUE THREAD

**Issue by vgoffman** [nodesource/distributions#692]
You don't appear to be running a supported machine architecture: armv7l

BUT I HAVE:

Linux version 4.14.52-v7.1.el7 (mockbuild@armhfp-01.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)) #1 SMP Thu Jun 28 08:25:49 UTC 2018

processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2835
Revision        : a02082
Serial          : 0000000018255327

**Comment by chrislea** [comment]
Sorry, but we only support `deb` based distributions for the Raspberry Pi. If you use Raspbian or a supported Debian or Ubuntu distro, you'll find supported packages. Hope this helps.

**Comment by vgoffman** [comment]
Can you build CentOS distributions ?

**Comment by chrislea** [comment]
If you use the binary tarballs for ARM that are made by the Node foundation they should work fine on your setup. Making `rpm` packages is harder. The issue is that the [sbuild](https://wiki.ubuntu.com/SimpleSbuild) tools for Debian / Ubuntu handle foreign architectures easily, but the [mock](https://github.com/rpm-software-management/mock/wiki) tools for Fedora / CentOS don't. So making `deb` packages is fairly easy for ARM, but making `rpm` packages isn't.

**Comment by vgoffman** [comment]
thank you anyway! But hope you will build for CentOS
