### ISSUE TITLE
elementaryOS Juno

### ISSUE THREAD

**Issue by pavlepiramida** [nodesource/distributions#693]
https://developer.elementary.io/#beta

elementaryOS Juno **beta 1** is out,based on bionic.
Would be nice to include it in setup_X scripts

![image](https://user-images.githubusercontent.com/18991480/42463152-a30e0338-83a5-11e8-83f9-934684395e75.png)

**Comment by chrislea** [comment]
Done. Closed by https://github.com/nodesource/distributions/commit/a5ce9b21b7821771e5005c07ca6e03c661c25a2c .
