### ISSUE TITLE
fedora-release-28-2.noarch is not currently supported

### ISSUE THREAD

**Issue by siccl** [nodesource/distributions#695]
fedora-release-28-2.noarch is not currently supported
Is possible add this support option ?

**Comment by chrislea** [comment]
FC28 is definitely supported. Can you please cut and paste the entire output of the setup script in here so we can try to see what's going on?

**Comment by rumjantsevv** [comment]
@chrislea 
 

> ## Installing the NodeSource Node.js 6.x LTS Boron repo...
> 
> 
> ## Inspecting system...
> 
> + rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
> + uname -m
> 
> ## Confirming "fc28-x86_64" is supported...
> 
> + curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_6.x/fc/28/x86_64/nodesource-release-fc28-1.noarch.rpm'
> 
> ## Your distribution, identified as "fedora-release-28-2.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by qubesosmacbook** [comment]
Hi

Same problem here

[fedora@localhost ~]$ curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -

## Installing the NodeSource Node.js 6.x LTS Boron repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "fc28-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_6.x/fc/28/x86_64/nodesource-release-fc28-1.noarch.rpm'

## Your distribution, identified as "fedora-release-28-2.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
Okay, sorry guys I wasn't paying attention. We don't package Node 6.x for FC28 because it ships Node 8.x from the main repos. So even if you install ours, `dnf` won't install it because the version in the main repos is newer. If you install 8.x or newer, you'll find supported packages. Hope this helps.

**Comment by qubesosmacbook** [comment]
Hi Chris

I have been trying but without success

I downloaded your package but how do i install it

**Comment by chrislea** [comment]
@qubesosmacbook I believe the command is
```
% dnf localinstall <packagename>
```
But you'll want to consult the `dnf` man page or other docs to make sure.
