### ISSUE TITLE
centos-release-6-10.el6.centos.12.3.i686

### ISSUE THREAD

**Issue by HHaarryy** [nodesource/distributions#696]
Could you please enable the support of "centos-release-6-10.el6.centos.12.3.i686".

I just upgraded centos to v6.10 and then trying to install nodejs 6 version on CentOS 6.10 and is getting following message:

`[root@root ~]# curl -sL https://rpm.nodesource.com/setup_6.x | sudo -E bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el6-i386" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_6.x/el/6/i386/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "centos-release-6-10.el6.centos.12.3.i686", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support`

Of if you could tell me any other alternative, from which i can install nodejs 6.14 on centos OR if you could tell me if this is possible or not?

Thank you in advance.

Have a great day !!

**Comment by chrislea** [comment]
Node 6.x is not supported for 32bit versions of CentOS 6 due to the lack of a compiler that can build V8 for that platform target. If you use a 64bit version of the distro you'll find supported packages. Hope this helps.
