### ISSUE TITLE
"centos-release-7-5.1804.el7.centos.2.x86_64", is not currently supported

### ISSUE THREAD

**Issue by iamnumlock** [nodesource/distributions#697]
## Your distribution, identified as "centos-release-7-5.1804.el7.centos.2.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
Please post the full output of the setup script you ran so that we can try to see what's going on. CentOS 7 should be fully supported.

**Comment by iamnumlock** [comment]
problem is work with proxy
solution:
# cat ~/.curlrc 
proxy=socks5h://10.35.215.218:443
