### ISSUE TITLE
redhat 7 PGP md5 NOT OK

### ISSUE THREAD

**Issue by GregoryNEUT** [nodesource/distributions#698]
Hello,

I'm trying to install **node.js v9.11.2** on my **RedHat 7**. The problem is I got the following error :

```
# rpm -K nodejs-9.11.2-1nodesource.x86_64.rpm
nodejs-9.11.2-1nodesource.x86_64.rpm: RSA sha1 ((MD5) PGP) md5 NOT OK (MISSING KEYS: (MD5) PGP#34fa74dd)
```

Thx

![image](https://user-images.githubusercontent.com/22965416/42943614-8d1a3374-8b63-11e8-992a-0c24c2a59510.png)

**Comment by chrislea** [comment]
Node 9.x is [EOL](https://github.com/nodejs/Release#end-of-life-releases) so we'd *really* recommend updating to use a supported line  like 10.x. Something like this should help you do that:
```
% sudo yum remove nodejs* npm*
% sudo rm -fv /etc/yum.repos.d/nodesource*
% curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -E -
```
Hope this helps.

**Comment by GregoryNEUT** [comment]
Hello,

your answer is very helpful. Many thanks so now I know there is some deprecated node.js version!

Have a good day
