### ISSUE TITLE
Debian installation script fails with 404

### ISSUE THREAD

**Issue by jniggemann** [nodesource/distributions#70]
`http://debian.tagancha.org/debian/dists/stable/main/binary-i386/Packages  404  Not Found`

**Comment by rvagg** [comment]
`debian.tagancha.org`? what even is this and how is it related to deb.nodesource.com? did you run our script and if so can you give us the full output of it?

**Comment by jniggemann** [comment]
Argh, this was completely unrelated (it's the Scribus repo), sorry.
