### ISSUE TITLE
"fedora-release-28-2.noarch" is not currently supported

### ISSUE THREAD

**Issue by rumjantsevv** [nodesource/distributions#700]
`curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -`

> ## Installing the NodeSource Node.js 6.x LTS Boron repo...
> 
> 
> ## Inspecting system...
> 
> + rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
> + uname -m
> 
> ## Confirming "fc28-x86_64" is supported...
> 
> + curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_6.x/fc/28/x86_64/nodesource-release-fc28-1.noarch.rpm'
> 
> ## Your distribution, identified as "fedora-release-28-2.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
FC28 ships with Node 8.x, so we don't make 6.x packages for it since those are older than what's in the base distro. If you install 8.x or newer, you'll find supported packages. Hope this helps.

**Comment by rumjantsevv** [comment]
@chrislea i have a legacy project with node 6 :(

**Comment by chrislea** [comment]
You can still install 6.x from the binary tarballs the Node foundation makes, but yum (by default) wouldn't install 6.x anyway since 8.x is available in the main repository and yum will install the newest version it sees.
