### ISSUE TITLE
centos 6.9/6.10 is not supported

### ISSUE THREAD

**Issue by harsszegi** [nodesource/distributions#701]
Hello,
Trying to install it on CentOS 6.9 / 6.10:

curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release

+ uname -m

## Confirming "el6-i386" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_10.x/el/6/i386/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "centos-release-6-9.el6.12.3.i686", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

cat /etc/redhat-release 
CentOS release 6.9 (Final)

uname -a
Linux terminal.btl-terminals 2.6.32-696.23.1.el6.i686 #1 SMP Tue Mar 13 23:09:35 UTC 2018 i686 i686 i386 GNU/Linux

curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el6-i386" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_10.x/el/6/i386/nodesource-release-el6-1.noarch.rpm'

## Your distribution, identified as "centos-release-6-10.el6.centos.12.3.i686", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

cat /etc/redhat-release 
CentOS release 6.10 (Final)

uname -a
Linux terminal.btl-terminals 2.6.32-754.2.1.el6.i686 #1 SMP Fri Jul 13 13:16:25 UTC 2018 i686 i686 i386 GNU/Linux

Please advise,
thanks

**Comment by chrislea** [comment]
The Node foundation [isn't making 32bit Intel builds for 10.x. or newer](https://github.com/nodejs/build/issues/885), so we're not making packages for that version / target. If you install 8.x you'll find supported packages. Hope this helps.
