### ISSUE TITLE
Not able to install the node js for the Red Hat enterprise Linux Version 7.5

### ISSUE THREAD

**Issue by Rajesh701035** [nodesource/distributions#702]
curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Your distribution, identified as "redhat-release-server-7.5-8.el7.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Can you please check and update us for this issue.

Regards,
Rajesh M

**Comment by chrislea** [comment]
That distribution is definitely supported for Node 8.x. Can you run the installer script with the `-x` flag and paste the complete output here? Meaning
```
% curl -sL https://rpm.nodesource.com/setup_8.x | sudo bash -x -E -
```
Also, are you behind a proxy?

**Comment by Rajesh701035** [comment]
Hey Hi Chrislea,

Thanks a lot , Yes it was behing the Firewall . Post adding the rpm.sourcenode.com in the access list 

we can able to down theload the rpm's to the server . Thanks a lot for your prompt response.

Rajesh M
