### ISSUE TITLE
Debian Strech Not currently supported, why?

### ISSUE THREAD

**Issue by osmaryasm** [nodesource/distributions#703]
Confirming "stretch" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/stretch/Release'

**## Your distribution, identified as "stretch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support**

**Comment by chrislea** [comment]
Stretch is definitely supported for Node 8.x. Can you run the setup script with the `-x` flag and paste the complete output here for example:
```
curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -x -E -
```
Also, are you behind a proxy?

**Comment by osmaryasm** [comment]
Yes, im behind a proxy

**Comment by chrislea** [comment]
Please look at the first question addressed in [the FAQ](https://github.com/nodesource/distributions/#faq).

**Comment by worc** [comment]
aka issue #9: https://github.com/nodesource/distributions/issues/9, which mentions a firewall rule blocking a curl request to https://deb.nodesource.com
