### ISSUE TITLE
Support Uruk GNU/Linux-libre

### ISSUE THREAD

**Issue by jorgesumle** [nodesource/distributions#707]
After executing `curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash` I get the following message.

> \#\# Your distribution, identified as "lugalbanda", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Uruk GNU/Linux-libre should be supported, as it is uses free Debian packages and shouldn't be problematic.

**Comment by chrislea** [comment]
If you'd like this distro to be supported, please issue a pull request against the [build sources](https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L201-L235) that adds the appropriate alias. If it looks good we'll merge it in. Thanks!
