### ISSUE TITLE
dist with full embedded icu

### ISSUE THREAD

**Issue by mhf-ir** [nodesource/distributions#713]
Is there any change to we have full icu build version:

ICU:
https://nodejs.org/api/intl.html

We cant rebuild deb repo from source anymore:
https://github.com/nodesource/distributions/issues/608

**Comment by chrislea** [comment]
We don't compile anything anymore, we just use the binary tarballs that the Node foundation distributes. So if you want to have builds with full ICU, you'd need to ask the main Node.js project, not us. Hope this helps.
