### ISSUE TITLE
centos 7.5 is not currently supported

### ISSUE THREAD

**Issue by mPyth** [nodesource/distributions#716]
Attempt to run following command on "**centos-release-7-5.1804.4.el7.centos.x86_64**" machine:
```
curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
```
gives following output:
```
## Installing the NodeSource Node.js 10.x repo...

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Your distribution, identified as "centos-release-7-5.1804.4.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by chrislea** [comment]
That distro is definitely supported. Can you run the installer script with the `-x` flag and paste the full input here? Also, are you behind a proxy? Example:
```
curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -x -E -
```

**Comment by tvdijen** [comment]
I'm on RHEL7.5 and experiencing the same... Also behind a proxy.
A trace as requested: [debug.txt](https://github.com/nodesource/distributions/files/2378630/debug.txt)

**Comment by chrislea** [comment]
If you're behind a proxy, please read the first issue in [the FAQ](https://github.com/nodesource/distributions/#faq). That should get you sorted out.

**Comment by tvdijen** [comment]
I don't see how the FAQ, or endless redirections to other issues solves this in any way...
Node should honor env-variables for proxy-settings
