### ISSUE TITLE
[Feature] Add setup_current

### ISSUE THREAD

**Issue by dubrowgn** [nodesource/distributions#718]
For those of us that want to automate installing the lastest stable version of node.js, having a script that effectively just points to the latest install script would be most handy. Something like sym-linking setup_current to setup_10.x. When the next major version is released, update the sym-link to point to the new setup script.

Thanks!

**Comment by chrislea** [comment]
We decided early on that we weren't going to ever do something via these packages that could potentially update Node across a major version. The possibility of this messing something up for people is just too high. However, assuming you're running a quasi-modern distro, you can [install Node via a snap package](https://nodesource.com/blog/announcing-node-js-snap-linux-users/) which will do what you want. Hope this helps!

**Comment by chrislea** [comment]
You can do all of that with the snap package. Just install it via `snap install` on the initial OS installation, and after that, the `snapd` daemon will automatically update it for you. No user intervention required, you'll just always have the newest version, which is I think what you want.

**Comment by untidy-hair** [comment]
I almost opened the same request. It would be great if the Readme install section mentions this decision :)
