### ISSUE TITLE
sources and debug packages not up to date in xenial package repo

### ISSUE THREAD

**Issue by phil-marble** [nodesource/distributions#719]
sources and debug packages not up to date in xenial package repo:

```
$ reprepro -b packages/node list xenial-upstream 
xenial-upstream|main|amd64: nodejs 8.12.0-1nodesource1
xenial-upstream|main|amd64: nodejs-dbg 8.4.0-1nodesource1~xenial1
xenial-upstream|main|i386: nodejs 8.12.0-1nodesource1
xenial-upstream|main|i386: nodejs-dbg 8.4.0-1nodesource1~xenial1
xenial-upstream|main|source: nodejs 8.4.0-1nodesource1~xenial1
```

(ref: https://github.com/nodejs/node/issues/22964)

**Comment by chrislea** [comment]
This is because we no longer build the packages from source, we just take the binary tarballs distributed by the Node foundation and put those bits into `deb` and `rpm` format. So, there aren't any source or debug packages being made.

**Comment by phil-marble** [comment]
On Thu, Sep 20, 2018 at 11:21:43AM -0700, Chris Lea wrote:
> Not sure what you're referring to?
>

for example, from https://deb.nodesource.com/node_8.x/dists/xenial/main/binary-amd64/Packages:


> Package: nodejs-dbg
> Source: nodejs
> Version: 8.4.0-1nodesource1~xenial1
> Architecture: amd64
> Maintainer: Chris Lea <chl@nodesource.com>
> Installed-Size: 6470

**Comment by chrislea** [comment]
That's the correct behavior as that's the newest version of that package. It's a _very_ bad idea to retroactively remove packages from a repository without a deeply compelling reason.

**Comment by phil-marble** [comment]
uh... sure, except a debug package without a matching binary is useless
and providing a source package in your repo of an earlier version than
what the binary install package is confusing.

```
$ sudo apt-get install nodejs
nodejs is already the newest version (8.12.0-1nodesource1).

$ apt-get source nodejs
Get:1 https://deb.nodesource.com/node_8.x xenial/main nodejs 8.4.0-1nodesource1~xenial1 (dsc) [1,153 B]
Get:2 https://deb.nodesource.com/node_8.x xenial/main nodejs 8.4.0-1nodesource1~xenial1 (tar) [31.0 MB]
Get:3 https://deb.nodesource.com/node_8.x xenial/main nodejs 8.4.0-1nodesource1~xenial1 (diff) [11.3 kB]                      
Fetched 31.0 MB in 6s (4,784 kB/s)                                                                                            
dpkg-source: warning: extracting unsigned source package
(nodejs_8.4.0-1nodesource1~xenial1.dsc)
dpkg-source: info: extracting nodejs in nodejs-8.4.0
dpkg-source: info: unpacking nodejs_8.4.0.orig.tar.gz
dpkg-source: info: unpacking nodejs_8.4.0-1nodesource1~xenial1.debian.tar.xz
```

/me shrugs

just looks like a mistake to me :-/

**Comment by phil-marble** [comment]
also this, bro:

```
$ sudo apt-get install nodejs-dbg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nodejs-dbg : Depends: nodejs (= 8.4.0-1nodesource1~xenial1) but 8.12.0-1nodesource1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by refack** [comment]
@chrislea should we (Node.js) be building anything special for `nodejs-dbg`?

**Comment by chrislea** [comment]
@refack the Node.js foundation hasn't ever made debug builds, and this kind of question only comes up rarely. Unless there's some new need for them I wouldn't worry about it.

**Comment by refack** [comment]
Someone on IRC was looking for at least the debug symbols (and we do distribute them for Windows Release builds)

**Comment by chrislea** [comment]
I mean, it's up to you guys. If you start making debug builds, we should be able to package them up. IIRC, what we were doing when we built all of this from source was to make a `Debug` build, which resulted in both `Release` and `Debug` binaries getting made. We then put the debug binary in the `-dbg` package at `/usr/lib/debug/usr/bin/nodejs` so it was available if people wanted to get to it.
