### ISSUE TITLE
a way to check available versions visually

### ISSUE THREAD

**Issue by PavelPolyakov** [nodesource/distributions#72]
Before, when the nodejs binaries were located here:
https://launchpad.net/~chris-lea/+archive/ubuntu/node.js-devel

It was possible to check (visually) which versions are available.
Could someone tell me how we can do the same for the nodesource repository ?

Because I still don't know if the 0.12 version is already there :)

Regards,

**Comment by rvagg** [comment]
https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories

**Comment by PavelPolyakov** [comment]
@rvagg 

great, so the 0.12 is there. But anyhow - is there a way to check the available versions visually? Or with the help of some terminal command.

Regards,

**Comment by rvagg** [comment]
the problem is that there are so many variations and this is only going to increase

```
curl -sL https://deb.nodesource.com/node_0.10/dists/utopic/main/binary-amd64/Packages | grep '^\(Version\|Package\):'
```

that's the closest I can think of right now to meeting your needs but you'll have to adjust the URL for your disto, arch and Node.js/io.js version.

**Comment by PavelPolyakov** [comment]
Thanks, I got your point!
