### ISSUE TITLE
NodeJS 8.x issue

### ISSUE THREAD

**Issue by squirelnnut** [nodesource/distributions#722]
I  was trying to run this command : NodeJS 8.x by issueing: curl -sL https://rpm.nodesource.com/setup_8.x | bash -
I got this message: Your distribution, identified as "fedora-release-29-0.16.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues....
Please help.

**Comment by chrislea** [comment]
We don't generally publish packages until the full (non-beta) release for any given distro. When FC29 is released at the end of Oct, we'll support it at that time. Hope this helps.
