### ISSUE TITLE
Raspberry: no way to get an older version of Node.js

### ISSUE THREAD

**Issue by mc0re** [nodesource/distributions#723]
I need version 8.11.4, but can only see 8.12.0 and 0.10.29. Is there a possibility to add some historical versions here (at least 8.11.4 :-) )?

**Comment by chrislea** [comment]
I assume you mean you're using a Raspberry Pi, which likely means you need `deb` packages. You can see all the `deb` packages we've ever made for the 8.x release line [here](https://deb.nodesource.com/node_8.x/pool/main/n/nodejs/).
