### ISSUE TITLE
Debian stretch not supported?

### ISSUE THREAD

**Issue by hstoellinger** [nodesource/distributions#725]
Hello Folks,
I am trying to install Node.js on my Debian9 (stretch) system. However bash script "setup_10.x" comes back with the message...
## Your distribution, identified as "stretch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
According to "https://tecadmin.net/install-latest-nodejs-npm-on-debian/" it should however be supported. 
Am I missing something?
Regards
H. Stoellinger

**Comment by chrislea** [comment]
Stretch should definitely be supported. Can you run the installer with the `-x` flag and paste the output here so we can see what's going on?
```
curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -x -E -
```
Also, can you see this file from the target machine?
```
https://deb.nodesource.com/node_10.x/dists/stretch/main/binary-amd64/Packages
```
and are you behind a proxy?

**Comment by hstoellinger** [comment]
Thanks for the quick reply...
No, I am NOT behind a proxy.

When I run "curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -x -E -" NOTHING at all happens at my console!

Yes, I can see file "https://deb.nodesource.com/node_10.x/dists/stretch/main/binary-amd64/Packages".
The display is...
Package: nodejs
Version: 10.11.0-1nodesource1
Architecture: amd64
Maintainer: Chris Lea <chl@nodesource.com>
Installed-Size: 69569
Depends: libc6 (>= 2.7), libgcc1 (>= 1:3.4), libstdc++6 (>= 4.4.0), python-minimal, ca-certificates
Conflicts: nodejs-dev, nodejs-legacy, npm
Replaces: nodejs-dev (<= 0.8.22), nodejs-legacy, npm (<= 1.2.14)
Provides: nodejs-dev, nodejs-legacy, npm
Homepage: https://nodejs.org
Priority: optional
Section: web
Filename: pool/main/n/nodejs/nodejs_10.11.0-1nodesource1_amd64.deb
Size: 14955854
SHA256: 6b3efd9180be13c4c66bef4060d9130f151876694af123ad95dbe1a151971771
SHA1: 63d8002657899d58276d6e685f2b67ab3b6d3f92
MD5sum: 7cf5d46a739cd7b0b79db5ddbb88b761
Description: Node.js event-based server-side javascript engine
 Node.js is similar in design to and influenced by systems like
 Ruby's Event Machine or Python's Twisted.
 .
 It takes the event model a bit further - it presents the event
 loop as a language construct instead of as a library.
 .
 Node.js is bundled with several useful libraries to handle server tasks :
 System, Events, Standard I/O, Modules, Timers, Child Processes, POSIX,
 HTTP, Multipart Parsing, TCP, DNS, Assert, Path, URL, Query Strings.

Thanks for your valuable help!
H. Stoellinger

**Comment by hstoellinger** [comment]
Sorry, it's the first time I interact... Did NOT want to close the issue...

**Comment by chrislea** [comment]
Is `curl` installed on your machine? For example, does this command produce any output?
```
curl https://deb.nodesource.com/setup_10.x
```

**Comment by hstoellinger** [comment]
Yes, command
curl https://deb.nodesource.com/setup_10.x
produces the following output on the KDE-konsole:
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs

**Comment by chrislea** [comment]
Okay, something is wrong with the SSL certificates on your machine which is making `curl` fail against a `https` site. Can you check if the `ca-certificates` package is installed? If it's not, can you install it and try again.

**Comment by hstoellinger** [comment]
Hello again, 
I was away yesterday! 
Yes, the ca-certificates package is installed at version (20161130+nmu1+deb9u1).
 In directory /etc/ssl/certs there are a couple of crt-files and loads of symbolic links (.pem) to crt-files in other locations. Also, there IS a file "ca-certificates.crt" in that directory. Maybe it is somehow corrupt? Somewhere I read that they have to be in .pem-format. 
Regards
H. S.

**Comment by chrislea** [comment]
Hm, not sure then. But the issue is with `curl`, not our repository. Maybe check out [this](https://stackoverflow.com/questions/3160909/how-do-i-deal-with-certificates-using-curl-while-trying-to-access-an-https-url) posting on SO for some tips. Hope this helps!
