### ISSUE TITLE
Where is node/npm installed on Ubuntu 16.04?

### ISSUE THREAD

**Issue by MPLLC** [nodesource/distributions#726]
Like the subject heading asks, where is node actually installed?  I'm trying to install some packages via npm, but npm isn't in `/usr/local/bin`:

    ~$ node -v
    bash: /usr/local/bin/node: No such file or directory
    ~$ nodejs -v
    v10.11.0
    ~$ npm install n -g
    bash: /usr/local/bin/npm: No such file or directory

What am I missing?

**Comment by chrislea** [comment]
It's in `/usr/bin`

You can see the install locations of all files with:
```
dpkg -L nodejs
```
