### ISSUE TITLE
Couldn't install nodejs repo on Fedora 29 beta.

### ISSUE THREAD

**Issue by ukulanne** [nodesource/distributions#727]
[panda@pandaville ~]$ curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "fc29-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_10.x/fc/29/x86_64/nodesource-release-fc29-1.noarch.rpm'

**Comment by chrislea** [comment]
Duplicate of https://github.com/nodesource/distributions/issues/722, closing.
