### ISSUE TITLE
xenial is not supported

### ISSUE THREAD

**Issue by ujjvala-odoo** [nodesource/distributions#728]
I run this command:
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -

Output:
## Confirming "xenial" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_9.x/dists/xenial/Release'

## Your distribution, identified as "xenial", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by chrislea** [comment]
The 9.x release line is EOL and should *never* be used anymore as it's not getting security updates. If you set up the 8.x or 10.x versions you should be fine as both are supported by Xenial.

**Comment by ujjvala-odoo** [comment]
Yeah, it worked with 10.x.
Thanks
