### ISSUE TITLE
 Your distribution, identified as "redhat-release-server-7.2-9.el7.x86_64", is not currently supported

### ISSUE THREAD

**Issue by Poly1199** [nodesource/distributions#729]
Hi, 
i do:
rnd-vm-13-127# curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Your distribution, identified as "redhat-release-server-7.2-9.el7.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

why node8 is not supported for my version ?
Thanks for answer,
Tomas

**Comment by chrislea** [comment]
EL7 is definitely supported. Can you run the script with the `-x` flag and paste the complete output here so we can try to see what's going on? IE:
```
curl -sL https://rpm.nodesource.com/setup_8.x | sudo bash -x -
```
Also, are you behind a proxy?

**Comment by thiagoc** [comment]
I've been getting this same error and I'm behind a transparent proxy, so I had to add the `-k` parameter to the all the `curl` calls on the script.

**Comment by chrislea** [comment]
Thanks. Closing.
