### ISSUE TITLE
CentOS 7, NodeJS 0.12

### ISSUE THREAD

**Issue by haf** [nodesource/distributions#73]
Hi,

I'm trying to use your service to install the latest nodejs, v0.12 -- but I can't find instructions for it (https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories)

Could you give a hand?

**Comment by rvagg** [comment]
@haf they are coming _very soon_, we have started with the .debs because they are more popular and easier but .rpms for at least EL6 and EL7 will be landing soon and we'll work on EL5 after that

keep an eye on this repo for news.

**Comment by AndrewFarley** [comment]
+1 for Centos7 RPMs.  :)

**Comment by prabhu** [comment]
Any news?

**Comment by AaronJan** [comment]
..OK, I'm downloading `Ubuntu` now.

+1 for `CentOS 7`
Thank you guys!

**Comment by clayreimann** [comment]
`CentOS 7` :+1:

**Comment by haf** [comment]
This was 1 1/2 months ago now; any updates?

**Comment by EgoAleSum** [comment]
I remember in the other thread we were promised 0.12 on EL in february...

**Comment by clayreimann** [comment]
@rvagg updates? a better place to get updates?

**Comment by haf** [comment]
No better place to get updates to an issue than in the issue itself.

**Comment by chrislea** [comment]
Hi guys, this one's in my court, not @rvagg's. I have 0.12 RPMs built for things newer than EL5, but we're getting some last things in place so the setup scripts do what they should intelligently. I'm getting it all done as quickly as I can. Thanks very much for being patient!

**Comment by efx** [comment]
@chrislea let me know if it would be useful for me to help with any tasks related to this.

**Comment by tonylukasavage** [comment]
+1 for Centos7 RPMs

**Comment by sup3rman** [comment]
+1 for Centos7 RPMs

**Comment by prabhu** [comment]
For those really impatient for rpm and want to upgrade right away
```bash
cd /tmp
wget http://nodejs.org/dist/v0.12.3/node-v0.12.3-linux-x64.tar.gz
cd /usr && tar --strip-components 1 -xzf /tmp/node-v0.12.3-linux-x64.tar.gz
```

**Comment by EgoAleSum** [comment]
@prabhu I'd recommend creating a symlink. Like in here http://stackoverflow.com/questions/23082242/how-to-install-nodejs-0-10-26-from-binaries-in-ubuntu/23084499#23084499

**Comment by carloscarcamo** [comment]
+1 for Centos 7 RPMs :)

**Comment by Jakobud** [comment]
Any word on this yet? Was surprised to see nodesource yum repo still spitting out 0.10.x....

**Comment by thynson** [comment]
+1

**Comment by Jakobud** [comment]
For anyone curious, I installed Node Version Manager and it was able to seamlessly and easily install 0.12.x on CentOS 7 for me. It's a great tool for managing multiple versions on Node on a single server.

**Comment by mrichard** [comment]
+1

**Comment by rvagg** [comment]
You can try out the new EL7 rpms by grabbing them manually from here: https://rpm.nodesource.com/pub_0.12/el/7/x86_64/ - we just need some testing and we're working on getting the setup script completed

**Comment by eskaaren** [comment]
+1

**Comment by den-is** [comment]
+1

**Comment by mroedel** [comment]
+1

**Comment by Jakobud** [comment]
`https://rpm.nodesource.com/pub_0.12/el/7/x86_64/nodejs-0.12.7-1nodesource.el7.centos.x86_64.rpm`

Installed perfectly for me on CentOS 7.

**Comment by object88** [comment]
+1 Anything...?

**Comment by jorgevillamizarco** [comment]
@object88 , @Jakobud solution worked perfect for me!
wget https://rpm.nodesource.com/pub_0.12/el/7/x86_64/nodejs-0.12.7-1nodesource.el7.centos.x86_64.rpm

rpm -Uvh nodejs-0.12.7-1nodesource.el7.centos.x86_64.rpm

**Comment by object88** [comment]
@jorgevillamizarco, your suggestion does work, but I had to code a number of ansible tasks around it.  My previous ansible playbook simple retrieved the script and executed; much simpler.  I was hoping to continue to use that.

**Comment by xudaiqing** [comment]
I current modify /etc/yum.repos.d and replace all /pub/ whith /pub_0.12/ . 
then 'yum install nodejs' will install 0.12.
I do this on fresh installed centos, update from old one should work, but may have problems.

**Comment by geerlingguy** [comment]
:+1: for CentOS 7. Same use case as @object88 — my [Ansible role for Node.js](https://github.com/geerlingguy/ansible-role-nodejs) currently works great for both 0.10 and 0.12 for Debian/Ubuntu, but the poor RHEL/CentOS users only get 0.10 so far.

**Comment by chrislea** [comment]
Hey all. We have builds of everything for EL7, but we're still kicking the tires on them before we publicize their existence. You can get the files directly from:

https://rpm.nodesource.com/pub_0.12/el/7/x86_64/
https://rpm.nodesource.com/pub_4.x/el/7/x86_64/

If you install the `nodesource-release-el7-1.noarch.rpm` files, you should actually get on the yum update channels. But, as we are still testing them out, please don't be too verbose about their existence. We (read: I) would **love** to hear about anything you see good or bad.

**Comment by chrislea** [comment]
BTW: These builds also exist for FC19+. Just sub out "el" with "fc" and also "7" with the FC release in the above URLs. Example:

https://rpm.nodesource.com/pub_4.x/fc/20/x86_64/

**Comment by chrislea** [comment]
BTW BTW: When I said 19+ above, I meant inclusive of FC19. Also, for FC there are still 32bit builds. So for Example:

https://rpm.nodesource.com/pub_0.12/fc/19/i386/

**Comment by mattiasgeniar** [comment]
Just to confirm here: using the 0.12 repos on CentOS 6 and CentOS 7 and they're both working exactly as they should. As far as I'm concerned, you can blow of the tires and make it public. ;-)

**Comment by samy100** [comment]
Any news on this for Centos 6 support?

**Comment by djeps** [comment]
I can confirm that installation with `yum install https://rpm.nodesource.com/pub_0.12/el/7/x86_64/nodejs-0.12.9-1nodesource.el7.centos.x86_64.rpm` with provided rpm packages installed and work correctly in rhel7.2.

**Comment by reynot** [comment]
curl -sL https://rpm.nodesource.com/setup_0.12 | bash -

Still fails on Centos 7 as not currently supported?  Any news on this?

**Comment by retrohacker** [comment]
The centos7 repos are available here: https://rpm.nodesource.com/pub_0.12/el/7/x86_64/

And the setup script now supports centos7

**Comment by marcelmfs** [comment]
Just for the sake of completion I can also confirm that the provided package for 0.12.18 also works in Centos 7.3.
