### ISSUE TITLE
Expose node.npx as a command in snapcraft package

### ISSUE THREAD

**Issue by thrnio** [nodesource/distributions#730]
The snapcraft packages have the `npx` binary available, but they don't expose it as an available command, either as `node.npx` or with an `npx` alias.

**Comment by rvagg** [comment]
<img width="640" alt="screenshot 2018-10-31 12 01 10" src="https://user-images.githubusercontent.com/495647/47759651-b02ac200-dd04-11e8-9c7b-4b5d5a0079e9.png">

done, across all lines, some are still building.

I've also requested the `npx` alias https://forum.snapcraft.io/t/new-alias-request-node-npx-npx/8235 and if that happens you'll have to remove the snap and reinstall it again to get it set up. Or you can just do it manually: 

<img width="451" alt="screenshot 2018-10-31 12 02 48" src="https://user-images.githubusercontent.com/495647/47759693-e5cfab00-dd04-11e8-9045-382397d55482.png">

Also FYI I'm getting Node 11 set up too, I just need them to authorize an `11` track. I'm a bit slow on this one but it'll get there.

**Comment by rvagg** [comment]
for the record, the snapcraft.yml template is in this repo under /snap/, the change I introduced is here https://github.com/nodesource/distributions/blob/master/snap/snapcraft.yaml.sh#L63-L64
