### ISSUE TITLE
"centos-release-7-5.1804.4.el7.centos.x86_64", is not currently supported

### ISSUE THREAD

**Issue by steverhubarb** [nodesource/distributions#731]
What's my quickest workaround please?

**Comment by chrislea** [comment]
CentOS 7 is supported. Can you run the installer with the `-x` flag and paste the entire output here so we can try to see what's going on?
```
% curl -sL https://rpm.nodesource.com/setup_8.x | sudo bash -x -E -
```
Also, are you behind a proxy?

**Comment by steverhubarb** [comment]
Hi Chris

I’ve tried again and succeeded, so not sure what happened before.
Thanks

Steve
