### ISSUE TITLE
Can't upgrade from 6.14.4 to 8.12.0 on Amazon Linux

### ISSUE THREAD

**Issue by jwerre** [nodesource/distributions#734]
Whenever I try to install the latest version of Node 8 I end up with the latest version of 6. Here is what I've tried:

	$ sudo yum remove nodejs nodesource-release
		Loaded plugins: priorities, update-motd, upgrade-helper
		No Match for argument: nodejs
		No Match for argument: nodesource-release
		No Packages marked for removal

	$ sudo yum clean all
		Loaded plugins: priorities, update-motd, upgrade-helper
		Cleaning repos: amzn-main amzn-updates
		Cleaning up everything

	$ sudo yum makecache
		Loaded plugins: priorities, update-motd, upgrade-helper
		amzn-main                                                                                                                                                     | 2.1 kB  00:00:00     
		amzn-updates                                                                                                                                                  | 2.5 kB  00:00:00     
		(1/9): amzn-main/latest/group_gz                                                                                                                              | 4.4 kB  00:00:00     
		(2/9): amzn-main/latest/filelists_db                                                                                                                          | 5.7 MB  00:00:00     
		(3/9): amzn-main/latest/other_db                                                                                                                              |  475 B  00:00:00     
		(4/9): amzn-main/latest/primary_db                                                                                                                            | 4.0 MB  00:00:00     
		(5/9): amzn-updates/latest/group_gz                                                                                                                           | 4.4 kB  00:00:00     
		(6/9): amzn-updates/latest/updateinfo                                                                                                                         | 520 kB  00:00:00     
		(7/9): amzn-updates/latest/filelists_db                                                                                                                       | 3.5 MB  00:00:00     
		(8/9): amzn-updates/latest/other_db                                                                                                                           |  473 B  00:00:00     
		(9/9): amzn-updates/latest/primary_db                                                                                                                         | 734 kB  00:00:00     
		Metadata Cache Created

	$ curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -

		## Installing the NodeSource Node.js 8.x LTS Carbon repo...

		## Inspecting system...

		+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
		+ uname -m

		## Confirming "el7-x86_64" is supported...

		+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

		## Downloading release setup RPM...

		+ mktemp
		+ curl -sL -o '/tmp/tmp.vA9teajQnb' 'https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

		## Installing release setup RPM...

		+ rpm -i --nosignature --force '/tmp/tmp.vA9teajQnb'

		## Cleaning up...

		+ rm -f '/tmp/tmp.vA9teajQnb'

		## Checking for existing installations...

		+ rpm -qa 'node|npm' | grep -v nodesource

		## Run `sudo yum install -y nodejs` to install Node.js 8.x LTS Carbon and npm.
		## You may also need development tools to build native addons:
		     sudo yum install gcc-c++ make
		## To install the Yarn package manager, run:
		     curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
		     sudo yum install yarn

	$ sudo yum install nodejs
		Loaded plugins: priorities, update-motd, upgrade-helper
		Resolving Dependencies
		--> Running transaction check
		---> Package nodejs.x86_64 2:6.14.4-1nodesource will be installed
		--> Processing Dependency: python >= 2.6 for package: 2:nodejs-6.14.4-1nodesource.x86_64
		--> Running transaction check
		---> Package python26.x86_64 0:2.6.9-2.89.amzn1 will be installed
		--> Processing Dependency: libpython2.6.so.1.0()(64bit) for package: python26-2.6.9-2.89.amzn1.x86_64
		--> Running transaction check
		---> Package python26-libs.x86_64 0:2.6.9-2.89.amzn1 will be installed
		--> Finished Dependency Resolution

		Dependencies Resolved

		=====================================================================================================================================================================================
		 Package                                     Arch                                 Version                                             Repository                                Size
		=====================================================================================================================================================================================
		Installing:
		 nodejs                                      x86_64                               2:6.14.4-1nodesource                                nodesource                                13 M
		Installing for dependencies:
		 python26                                    x86_64                               2.6.9-2.89.amzn1                                    amzn-main                                5.8 M
		 python26-libs                               x86_64                               2.6.9-2.89.amzn1                                    amzn-main                                697 k

		Transaction Summary
		=====================================================================================================================================================================================
		Install  1 Package (+2 Dependent packages)

		Total download size: 20 M
		Installed size: 59 M
		Is this ok [y/d/N]: n
		Exiting on user command
		Your transaction was saved, rerun it with:
		 yum load-transaction /tmp/yum_save_tx.2018-10-16.02-35.k_ERNz.yumtx

Any idea how I can resolve this?

**Comment by chrislea** [comment]
Welp, that is indeed odd, as that's pretty much exactly what'd I'd have recommended that you do. What's the output of:
```
% cat /etc/yum.repos.d/nodesource-el7.repo
```
?

**Comment by jwerre** [comment]
#### /etc/yum.repos.d/nodesource-el7.repo

```
[nodesource]
name=Node.js Packages for Enterprise Linux 7 - $basearch
baseurl=https://rpm.nodesource.com/pub_8.x/el/7/$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL

[nodesource-source]
name=Node.js for Enterprise Linux 7 - $basearch - Source
baseurl=https://rpm.nodesource.com/pub_8.x/el/7/SRPMS
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
gpgcheck=1
```

**Comment by chrislea** [comment]
Well, that's also correct. It's been a while since I've really used RedHat style machines for much personally so my `yum` skills aren't what they used to be. Is it possible you need to do a `yum update` first to pick up the new version? I have to assume there's just something cached on your machine somewhere.

**Comment by jwerre** [comment]
So I gave up last night and came in this morning, sat down at my console and voilà!

	$ sudo yum install -y  nodejs

		Loaded plugins: priorities, update-motd, upgrade-helper
		amzn-main                                                                                                                                                     | 2.1 kB  00:00:00     
		amzn-updates                                                                                                                                                  | 2.5 kB  00:00:00     
		nodesource                                                                                                                                                    | 2.5 kB  00:00:00     
		nodesource/x86_64/primary_db                                                                                                                                  |  39 kB  00:00:00     
		Resolving Dependencies
		--> Running transaction check
		---> Package nodejs.x86_64 2:8.12.0-1nodesource will be installed
		--> Processing Dependency: python >= 2.6 for package: 2:nodejs-8.12.0-1nodesource.x86_64
		--> Running transaction check
		---> Package python26.x86_64 0:2.6.9-2.89.amzn1 will be installed
		--> Processing Dependency: libpython2.6.so.1.0()(64bit) for package: python26-2.6.9-2.89.amzn1.x86_64
		--> Running transaction check
		---> Package python26-libs.x86_64 0:2.6.9-2.89.amzn1 will be installed
		--> Finished Dependency Resolution

		Dependencies Resolved

		=====================================================================================================================================================================================
		 Package                                     Arch                                 Version                                             Repository                                Size
		=====================================================================================================================================================================================
		Installing:
		 nodejs                                      x86_64                               2:8.12.0-1nodesource                                nodesource                                16 M
		Installing for dependencies:
		 python26                                    x86_64                               2.6.9-2.89.amzn1                                    amzn-main                                5.8 M
		 python26-libs                               x86_64                               2.6.9-2.89.amzn1                                    amzn-main                                697 k

		Transaction Summary
		=====================================================================================================================================================================================
		Install  1 Package (+2 Dependent packages)

		Total size: 23 M
		Total download size: 16 M
		Installed size: 69 M
		Downloading packages:
		nodejs-8.12.0-1nodesource.x86_64.rpm                                                                                                                          |  16 MB  00:00:00     
		Running transaction check
		Running transaction test
		Transaction test succeeded
		Running transaction
		Warning: RPMDB altered outside of yum.
		  Installing : python26-libs-2.6.9-2.89.amzn1.x86_64                                                                                                                             1/3 
		  Installing : python26-2.6.9-2.89.amzn1.x86_64                                                                                                                                  2/3 
		  Installing : 2:nodejs-8.12.0-1nodesource.x86_64                                                                                                                                3/3 
		  Verifying  : python26-2.6.9-2.89.amzn1.x86_64                                                                                                                                  1/3 
		  Verifying  : python26-libs-2.6.9-2.89.amzn1.x86_64                                                                                                                             2/3 
		  Verifying  : 2:nodejs-8.12.0-1nodesource.x86_64                                                                                                                                3/3 

		Installed:
		  nodejs.x86_64 2:8.12.0-1nodesource                                                                                                                                                 

		Dependency Installed:
		  python26.x86_64 0:2.6.9-2.89.amzn1                                                     python26-libs.x86_64 0:2.6.9-2.89.amzn1                                                    

		Complete!
		
	$ node --version

		v8.12.0

**Comment by chrislea** [comment]
Welp, I'm glad it's working! I can't see that you did anything wrong. Sorry I can't be more help diagnosing why it didn't immediately do the expected thing.
