### ISSUE TITLE
The repository 'https://deb.nodesource.com/node_10.x cosmic Release' does not have a Release file.

### ISSUE THREAD

**Issue by mayankmetha** [nodesource/distributions#736]
Kindly fix this so that i can quickly finish with my projects. Thank you in advance.

**Comment by BAbdullatif** [comment]
You can install Node from snap temporarily, it's packaged Node team.

**Comment by chrislea** [comment]
Ubuntu Cosmic should be supported now.

https://deb.nodesource.com/node_10.x/dists/cosmic/Release
