### ISSUE TITLE
Ubuntu cosmic not supported for node v8 (ok for v10)

### ISSUE THREAD

**Issue by colinl** [nodesource/distributions#740]
Running https://deb.nodesource.com/setup_8.x on Ubuntu 8.10 (cosmic) yields the 'not supported' message, though it works for setup_10.x.  Will there be an 8.x release for cosmic?

**Comment by chrislea** [comment]
The version of Node that ships in the standard Ubuntu repositories for 8.x is the current version. As soon as a new version of 8.x comes out, it will go into our repo for Cosmic. Hope this helps.

**Comment by colinl** [comment]
OK, thanks for that.
For the record the issue is that the node-red install/upgrade script (originally written for the Raspbian but works on Debian and Ubuntu) [1] attempts to install from the NodeSource repository, so that is currently failing.  The workaround is to install version 10.x from NodeSource and then the script is content.

[1] https://nodered.org/docs/hardware/raspberrypi
