### ISSUE TITLE
Error installing setup_8.x -- Your distribution, identified as "cosmic", is not currently supported

### ISSUE THREAD

**Issue by bobhy** [nodesource/distributions#745]
Indeed, I am running Ubuntu Server 18.10.

Why is 8.x not supported on 18.10? [Elsewhere](https://discourse.nodered.org/t/pi-install-script-doesnt-install-npm-on-ubuntu-18-10/4054/2), I have read that this issue has been asked and answered that 8.x is packaged in Canonical's archives, so nodesource doesn't have to change their install script.

However, that doesn't work for me, as the Canonical archive does not include NPM, which I must use to install Ghost. OTOH, [Ghost team supports NodeJS  8.9, but nothing later](https://docs.ghost.org/faq/node-versions/).  

So I'm caught between a rock and a hard place and am about to hack the install nodesource script to proceed with the install anyway.  Since 8.9 passed Canonical's testing (or whatever acceptance criteria they have for their archive), I'm not actually expecting to run into serious issues, but will certainly raise another issue here if I do...

**Comment by bobhy** [comment]
This issue turns out to not be a show-stopper for me, since Canonical supports NPM, just as a separately installed package.  I was able to complete the Ghost install between the 2 packages.

But, if nodesource's particular packaging for nodejs and npm is important to them, I think that incurs an obligation to support it at initial release of new versions of the distros that they're committed to supporting eventually anyway.

**Comment by chrislea** [comment]
8.11.4, which is the newest 8.x release, is in the default Ubuntu repositories, which is why we don't include it in our repos for Cosmic. Whenever the next 8.x release comes out, it will be available in our repos. Hope this helps.

**Comment by waghanza** [comment]
@chrislea The **latest** is not `8.13`

**Comment by chrislea** [comment]
@waghanza 8.13.0 is in the repositories now, and there are packages for Ubuntu Cosmic.
