### ISSUE TITLE
unable to locate nodejs when used within bash.

### ISSUE THREAD

**Issue by joshrathke** [nodesource/distributions#750]
`curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -`
`sudo apt-get install -y nodejs`

Oddly get an error about an invalid option. So when I write:
`curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash - && sudo apt-get install -y nodejs`

The curl goes through but I then get an error about it being "unable to locate package nodejs". Has anyone run into this before? Outside a shell script and in command prompt both commands go through just fine.

**Comment by chrislea** [comment]
I think you're running into an issue with bash spawning itself. If you're trying to do this from within a bash script, I'd just curl the setup script down and then run it. Something like:
```
% curl -sL https://deb.nodesource.com/setup_11.x
% chmod 755 setup_11.x
% ./setup_11.x
```
Hope this helps.
