### ISSUE TITLE
'Google, Inc.' to 'Google LLC'

### ISSUE THREAD

**Issue by uncleGena** [nodesource/distributions#755]
copy and paste your code for Ubuntu installation after first row which is 
`curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -`
I've got this:
```
Get:8 http://dl.google.com/linux/chrome/deb stable Release.gpg [819 B]
Reading package lists... Done
E: Repository 'http://dl.google.com/linux/chrome/deb stable Release' changed its 'Origin' value from 'Google, Inc.' to 'Google LLC'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Error executing command, exiting
```
and after this the version which was installed is v8.11.4

**Comment by chrislea** [comment]
That error doesn't have anything to do with our repository. Google changed their name in their repo, and you have to accept that change before `apt` will work the way you expect it to.
