### ISSUE TITLE
Your distribution, identified as "jessie", is not currently supported

### ISSUE THREAD

**Issue by janpio** [nodesource/distributions#756]
Strange test failure because suddenly "jssie" is not supported any more:
https://circleci.com/gh/fastlane/fastlane/25790

The test suite is executing `curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -` which normally works just fine on that environment: https://circleci.com/gh/fastlane/fastlane/25638

Just rerunning the test "fixed" the problem: https://circleci.com/gh/fastlane/fastlane/25794

Seems the servers were "broken" for a short time?

**Comment by chrislea** [comment]
Honestly, I can't say. There haven't been any new releases of anything today, so we haven't touched that server, and the monitoring doesn't show anything. If I had to guess, you probably just hit some kind of temporary issue with the CDN. If it's working now, I wouldn't spend any more time worrying about it. Hope this helps!
