### ISSUE TITLE
Error while using npm

### ISSUE THREAD

**Issue by g7890** [nodesource/distributions#757]
can you please help out with below issue
installed nodejs and npm via apt-get

version
node -v v0.6.12
npm -v 1.1.4

if i try to install any package using npm getting below error

 npm i multer
npm http GET https://registry.npmjs.org/multer

npm ERR! Error: failed to fetch from registry: multer
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /root/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.0.31
npm ERR! command "node" "/usr/bin/npm" "i" "multer"
npm ERR! cwd /root
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: multer
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm not ok

**Comment by chrislea** [comment]
You'd need to contact the NPM folks for help with this. We just package NPM, we don't provide any support for it. I do note that you're using an *ancient* version of Node and NPM, we haven't made packages of those for years as they've been EOL for a long, long time. I'd strongly recommend installing a package of a supported version of Node.
