### ISSUE TITLE
RHEL 6: You don't appear to be running an Enterprise Linux based system

### ISSUE THREAD

**Issue by bennyn** [nodesource/distributions#76]
Today I wanted to install node on my WildFly cartridge which is running on Red Hat OpenShift. My OpenShift application runs on `Red Hat Enterprise Linux Server release 6.6 (Santiago)` so I tried to install node with `curl -sL https://rpm.nodesource.com/setup | bash -`. 

Unfortunately this does not work. The Terminal tells me: `You don't appear to be running an Enterprise Linux based system`:

![](http://ge.tt/api/1/files/9IP270D2/0/blob/x675)

**Comment by wblankenship** [comment]
Hey @bennyn, could you provide the output of `rpm --version` and `whereis rpm`

**Comment by bennyn** [comment]
@wblankenship: Sure!

```bash
$ rpm version
bash: /bin/rpm: Permission denied
```

```bash
$ whereis rpm
rpm: /bin/rpm /etc/rpm /usr/lib/rpm
```

**Comment by wblankenship** [comment]
Err, it doesn't look like you have execute permission on `/bin/rpm`. Try `ls -al rpm` to double check.

We use `rpm` in our script to install node, so the script checks to make sure `/bin/rpm` both exists and is executable.

**Comment by bennyn** [comment]
It looks like OpenShift shields this area. Flags for `/bin/rpm` are `-rwxr-x--- root`. Is there another recommended way to install node?

**Comment by bakmanhans** [comment]
Same here with ClearOS 6.6 (clearos-release-community-6-6.6.0.3.v6.noarch)
# rpm --version
RPM version 4.8.0
# whereis rpm
rpm: /bin/rpm /etc/rpm /usr/lib/rpm /usr/share/man/man8/rpm.8.gz

**Comment by wblankenship** [comment]
Hey @bakmanhans, could you provide the output of `rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release` please?

**Comment by wblankenship** [comment]
@bennyn were you able to find a best practice for getting Node.js installed on OpenShift?

**Comment by bakmanhans** [comment]
@wblankenship 
<code># rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release</code>
<code>clearos-release-community-6-6.6.0.3.v6.noarch</code>

**Comment by wblankenship** [comment]
@bakmanhans ClearOS is not officially supported by the install script. Unfortunately, we don't have the resources to support all of the distributions that exist in the wild, so we rely on community members to add support for their favorite linux systems. The lines that would need to be modified to get the script to work can be found here: https://github.com/nodesource/distributions/blob/master/rpm/setup#L55-83

If you manage to get the script to run and install on ClearOS, we would love a PR so that the work can help others in the community!

:smile:

**Comment by bennyn** [comment]
@wblankenship — Unfortunately not. I gave up.

**Comment by bakmanhans** [comment]
@wblankenship To modify the script to enable ClearOS support, should I fork the master branch? I'm not really familiar with it all.

**Comment by wblankenship** [comment]
@bakmanhans yup! I would recommend playing around with the script on a system you don't mind messing up, i.e. a virtual machine. Fork master, clone onto your machine then:
```
cd distributions/rpm
cat setup | sh -
```

That will run the script. You will probably need to setup some sort of aliasing like in https://github.com/nodesource/distributions/blob/master/deb/setup#L81-88

**Comment by rvagg** [comment]
a pull request against rpm/src/_setup.sh is needed to support new variants, it's difficult for us to test them all so any help would be appreciated
