### ISSUE TITLE
You don't appear to be running a supported machine architecture: ppc64le.

### ISSUE THREAD

**Issue by freeztime** [nodesource/distributions#762]
Hi..
I tried to install nodejs on my machine using this command:
` curl -sL https://rpm.nodesource.com/setup_8.x | sudo bash -`
and it gave me this error: 

![image](https://user-images.githubusercontent.com/4597012/49297727-18301c00-f4ee-11e8-993c-a6b44f1f4da0.png)

I run this command:
`rpm -q --whatprovides redhat-release`
this is the result:

![image](https://user-images.githubusercontent.com/4597012/49297809-53324f80-f4ee-11e8-949a-3d0ed40aec67.png)

Is there a way to install node.js on this system? Thank you for your help.

**Comment by freeztime** [comment]
** Update
So I run this command : 
`curl -sL https://rpm.nodesource.com/setup_8.x | bash -x -` 
and got this:

![image](https://user-images.githubusercontent.com/4597012/49299156-a4900e00-f4f1-11e8-9ec6-6d58b68c3608.png)

seems this system is not supported right?

**Comment by chrislea** [comment]
We don't make `rpm` packages for power pc architectures. You can install Node directly from the foundation's [binary distributions](https://nodejs.org/dist/latest-v8.x/) however. Hope this helps!

**Comment by freeztime** [comment]
@chrislea thank you sir.

**Comment by lag-linaro** [comment]
> We don't make `rpm` packages for power pc architectures. You can install Node directly from the foundation's [binary distributions](https://nodejs.org/dist/latest-v8.x/) however. Hope this helps!

What's the reason for not producing packages for `ppc` and/or `aarch64`?

**Comment by chrislea** [comment]
@lag-linaro our build system is in AWS and we don't have access to the hardware needed to do it there.

**Comment by lag-linaro** [comment]
How about:

https://aws.amazon.com/blogs/aws/new-ec2-instances-a1-powered-by-arm-based-aws-graviton-processors/

**Comment by chrislea** [comment]
Yes, we may look into those. It will also depend somewhat on distribution support, though I doubt that will be an impasse. Unfortunately we still won't have any way to deal with `ppc` support even if those do work for ARM.

**Comment by lag-linaro** [comment]
Should I start another Issue specifying `aarch64` support?
