### ISSUE TITLE
nodesource-release rpm still install nodesource-source repository

### ISSUE THREAD

**Issue by ganoze** [nodesource/distributions#767]
According to #586 source rpm are no longer provided. However starting from NodeJS 9.x, the _nodesource-release_ rpm (installed by _setup_9.x_) still installs the non-existing _nodesource-source_ repository with the following definition.

```
[nodesource-source]
name=Node.js for Enterprise Linux 7 - $basearch - Source
baseurl=https://rpm.nodesource.com/pub_9.x/el/7/SRPMS
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
gpgcheck=1
```

Even though it is disable, in my use case (using _yum-builddep_) this causes issues because the repository URL is not accessible.

I would have liked to make a PR to remove it myself but I could not find sources of _nodesource-release_. Feel free to share any pointer with me. If inaccessible could it be possible to get _nodesource-source_ removed from _nodesource-release_ ?

**Comment by chrislea** [comment]
Thanks for bringing this up, we'll look into taking that out.

Please be aware that Node 9.x is EOL and **nobody** should be using it at this point.

**Comment by alejagapatrick** [comment]
@ganoze [](url)
