### ISSUE TITLE
missing nodejs-dev package

### ISSUE THREAD

**Issue by nkovacs** [nodesource/distributions#77]
I'm trying to install execSync, but the gyp build fails, because it can't find /usr/include/nodejs/common.gypi
[This file is in the nodejs-dev package in the ubuntu repos](http://packages.ubuntu.com/search?searchon=contents&keywords=common.gypi&mode=exactfilename&suite=trusty&arch=any), but isn't available in this repo.

**Comment by EgoAleSum** [comment]
execSync is builtin into Node 0.12 and iojs.

**Comment by nkovacs** [comment]
I know, but that's irrelevant.

**Comment by EgoAleSum** [comment]
It's not irrelevant. If you installed Node 0.12 from the packages, you don't need to install execSync.
What does `node -v` say?

**Comment by nkovacs** [comment]
My package depends on the execSync package, and it won't install because execSync won't build.

**Comment by EgoAleSum** [comment]
Are you on 0.12 then? If so, it's a bug with the package, not the distribution.
I've been able to install Node-gyp modules with Nodesource's packages before without problems.

**Comment by nkovacs** [comment]
It's a bug with the package because common.gypi is missing.

**Comment by nkovacs** [comment]
The linux binary from nodejs.org (http://nodejs.org/dist/v0.12.1/node-v0.12.1-linux-x64.tar.gz) contains the include directory. The debian package only contains bin, lib and share.

**Comment by LinusU** [comment]
@EgoAleSum even if he maybe didn't need that specific package this is still a bug since **no native addons** will build without that file and the appropriate headers.

**Comment by nkovacs** [comment]
Where is the source code for these packages? Apt-get source tells me it's git://git.debian.org/git/collab-maint/nodejs.git, but that's the debian packages, which btw [**does have nodejs-dev**](https://packages.debian.org/sid/nodejs-dev)

**Comment by chrislea** [comment]
We don't split `npm` and the development files into a different package the way that the mainline Ubuntu and Debian distros do. This is because we feel that if you're not using `npm`, you're not really using `node` correctly. And you have to have the development headers available if you want to use `npm`. So everything is just bundled into the main nodejs packages that we ship.

**Comment by chrislea** [comment]
Also, the build sources are in the same place that the binary packages are. For example:

https://deb.nodesource.com/node_4.x/pool/main/n/nodejs/

**Comment by nkovacs** [comment]
Ok, that's great. But the main nodejs package is **still missing the include directory**

**Comment by chrislea** [comment]
Okay this does appear to be an issue with how the package is built. I'm looking into it now. Re-opening the issue. Thanks for catching this @nkovacs!

**Comment by chrislea** [comment]
Okay, new builds (intel only, arm coming) are in the repo now for 4.2.1. Running:

```bash
sudo apt-get update
sudo apt-get -y upgrade
```

will install them.

Header files and `common.gypi` are now in `/usr/include/node`. Can somebody verify one way or the other if this makes things work as expected please @nkovacs @LinusU ?

**Comment by LinusU** [comment]
Currently don't have access to a Ubuntu machine but I might get the opportunity to check it out in the near time.

It should be able to be tested by installing any native module. e.g. `npm install fs-xattr`.

Come to think of it thought, I think that node-gyp actually downloads the headers itself. I guess it's more convenient to have them pre-installed thought, provided that it finds them.

**Comment by chrislea** [comment]
I get the following when I try to build that module:

```
chl@luthien:~$ npm install fs-xattr
-
> fs-xattr@0.1.11 install /home/chl/node_modules/fs-xattr
> node-gyp rebuild

make: Entering directory `/home/chl/node_modules/fs-xattr/build'
  CXX(target) Release/obj.target/xattr/src/error.o
  CXX(target) Release/obj.target/xattr/src/xattr.o
  SOLINK_MODULE(target) Release/obj.target/xattr.node
  COPY Release/xattr.node
make: Leaving directory `/home/chl/node_modules/fs-xattr/build'
fs-xattr@0.1.11 node_modules/fs-xattr
└── nan@2.1.0
chl@luthien:~$ cd node_modules/
chl@luthien:~/node_modules$ file ./fs-xattr/build/Release/xattr.node 
./fs-xattr/build/Release/xattr.node: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=cb86ffd20b92f322265a6be8c4aa0f4296f1b033, not stripped
```

so it appears to me it's working. But I'd still love some outside verification. :)

**Comment by nkovacs** [comment]
Thanks. I'm still running utopic at home, so I can't test this right now. I'll check it out tomorrow or on Wednesday at work.

**Comment by LinusU** [comment]
@chrislea Is that with your new build? It looks all right, you could try running `npm install && npm test` in the fs-xattr directory.

It would be interesting to see how it looks with the old build? It doesn't look like it downloaded any headers on itself thought so that's good \o/

**Comment by chrislea** [comment]
@LinusU yup, that's with the new builds from this morning. Running `npm install` seems to work fine. Running `npm test` fails all the tests with errors like this:

```
  2) xattr#sync should get an attribute:
     Error: The file system does not support extended attributes or has the feature disabled.
      at Error (native)
      at Object.getSync (index.js:78:16)
      at Context.<anonymous> (test/xattr.js:29:21)
```

which looks to me like the module doesn't like my file system (btrfs), but that it is "working". I can put the full output from the install and the test here but it's kinda verbose.

**Comment by LinusU** [comment]
Ahh, yeah that's probably the module. I have only tested it on HFS+ fs:es myself...

**Comment by LinusU** [comment]
This one should have tests that works on Linux if you feel like you have the time: `generate-rsa-keypair`

**Comment by chrislea** [comment]
Nope, that one fails to build with a bunch of compiler errors that look something like this:

```
make: Entering directory `/home/chl/node_modules/generate-rsa-keypair/build'
  CXX(target) Release/obj.target/generate-rsa-keypair/binding.o
In file included from ../binding.cc:2:0:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
```

**Comment by LinusU** [comment]
Yeah, it doesn't work with the newer node. Should be easy to find something that does thought, two seconds...

**Comment by LinusU** [comment]
You could use this one https://github.com/nodejs/node-addon-examples

**Comment by nkovacs** [comment]
I tried a couple of the addons, and they work, so I think this is fixed.
Thanks
