### ISSUE TITLE
v8.14.1 source code on upstream, but not in rpm repo

### ISSUE THREAD

**Issue by doctornkz** [nodesource/distributions#773]
Hi. 
I've received notification about newer version on upstream nodejs8.14.1 from docker-library (hub.docker.com). But my automated deployment process was broken with failure. I've checked official nodejs rpm repo and faced with only 8.14.0 version as latest. So I am forced to change my process to build docker from sources, not from rpm. Is rpm repo still supported? 
Thank you!

**Comment by chrislea** [comment]
Sorry about that, 8.14.1 `rpm` packages should be available now. Thanks for pointing this out!
