### ISSUE TITLE
MX Linux Continuum 18 (Based on Debian 9)

### ISSUE THREAD

**Issue by Vitrixzyn** [nodesource/distributions#775]
## Confirming "Continuum" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/Continuum/Release'

**Comment by chrislea** [comment]
If you'd like this distribution to be supported, please issue a pull request against the relevant section of the [build sources](https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L201-L239). If it looks good we'll merge it in. Thanks!
