### ISSUE TITLE
Certificate verification failed: The certificate is NOT trusted.

### ISSUE THREAD

**Issue by SebastienElet** [nodesource/distributions#776]
Hello,

Like in #355, since today, i'm stuck with this error on ubuntu 18.04.
I disabled the source from my servers.

**Comment by chrislea** [comment]
The comments from #355 are still valid. CloudFront, which is the CDN we use to serve these repos, requires SNI. That shouldn't be a problem using Ubuntu 18.04, but if there's an issue with the certificate trust chain, that's not something we have control over. Hope this helps.
