### ISSUE TITLE
Update Snap package

### ISSUE THREAD

**Issue by KristijanZic** [nodesource/distributions#779]
Snap package track 11/stable is still on 11.5.0 even tho 11.6.0 was out for some time already. 
Please update to the latest nodejs version.

**Comment by toverux** [comment]
I'm wondering, Node 12 is out, but not available on Snapcraft, while there is already an apt repository for it. Is that normal? However, the edge channel already proposes version `13.0.0-nightly2019042608a9c4a9`.
Should I be confident in using snap or should I better go with apt? I've made the transition yesterday, thinking it would be easier to switch versions.

**Comment by rvagg** [comment]
Yeah, whoops! Thanks @toverux, I would have realised eventually but I completely forgot about getting a snap up.
I've got the code ready to go but need to get a [`12` channel manually approved in the Snapcraft store](https://forum.snapcraft.io/t/track-request-for-node-12/11120). That should be pretty quick. I'll update here when it's all done.

**Comment by toverux** [comment]
Thanks a lot @rvagg, I hope for you that they'll implement a more liberal system here, didn't knew that each track needed a manual confirmation.

**Comment by rvagg** [comment]
this went live, `sudo snap refresh node --channel=12`
