### ISSUE TITLE
Add support for Node 0.12.2

### ISSUE THREAD

**Issue by dwest-ee** [nodesource/distributions#78]
Hi,

I'm sure this is in the pipeline however I would be grateful for an ETA?

**Comment by chrislea** [comment]
It's already there for newer distros (basically, everything but RHEL5 and Ubuntu Precise). We're still sorting out toolchain issues on these older distros, as they don't ship with a compiler sufficiently modern to build 0.12.x. We are working on it though.

**Comment by dwest-ee** [comment]
Thanks Chris
