### ISSUE TITLE
Install fails due to GPG key not found

### ISSUE THREAD

**Issue by eddy-geek** [nodesource/distributions#785]
On running sudo apt-get update, the following occurs:

Reading package lists... Done
> W: GPG error: https://deb.nodesource.com/node_10.x cosmic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1655A0AB68576280

This can be fixed with:

    curl --silent https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -

This could be integrated in the manual instructions & the one-line setup script.

**Comment by suntong** [comment]
I'm still getting the above problem:

```
$ curl --silent https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
OK

$ sudo apt update
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://deb.debian.org/debian buster-updates InRelease                      
Hit:3 http://security.debian.org/debian-security buster/updates InRelease        
Hit:4 http://ftp.debian.org/debian buster-backports InRelease                                     
Hit:5 http://deb.debian.org/debian bullseye InRelease                                             
Hit:6 http://deb.debian.org/debian bullseye-updates InRelease               
Hit:7 http://ftp.debian.org/debian bullseye-backports InRelease             
Get:8 https://deb.nodesource.com/node_14.x buster InRelease [4584 B]        
Err:8 https://deb.nodesource.com/node_14.x buster InRelease                                                                                                  
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1655A0AB68576280
Reading package lists... Done                                                                                                                                
W: GPG error: https://deb.nodesource.com/node_14.x buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1655A0AB68576280
E: The repository 'https://deb.nodesource.com/node_14.x buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

How to fix the problem? thx

PS. The machine is WSL within Win10 accessing Internet behind corp man-in-the-middle (MitM) firewall.

**Comment by dieulot** [comment]
The correct (not insecure) solution has been posted in another issue: https://github.com/nodesource/distributions/issues/1181#issuecomment-809163621

 ```Shell
chmod +r "/usr/share/keyrings/nodesource.gpg"
```

(I had the same problem on Debian 11. This issue (#785) is the first result on Google for that error.)

**Comment by jmanteigueiro** [comment]
> chmod +r "/usr/share/keyrings/nodesource.gpg"

This was the solution for me as well, but +r did not work. 

I had to use `chmod 644`

**Comment by geonanorch** [comment]
something is missing in that command, probably `chmod a+r /usr/share/keyrings/nodesource.gpg` was meant.

**Comment by suntong** [comment]
> This was the solution for me as well, but +r did not work.

Confirmed. Should be `chmod a+r`.

**Comment by M0hammedImran** [comment]
I was facing this issue when I cancelled the installation process in progress.
Deleting `/etc/apt/sources.list.d/nodesource.list` and running the install script again worked.

**Comment by nrdvana** [comment]
Please add the ``chmod a+r`` to the official instructions.  I just wasted an hour on this.

**Comment by netik** [comment]
You can also add the key from ubuntu...

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 23E7166788B63E1E

**Comment by baozitao** [comment]
@



> I was facing this issue when I cancelled the installation process in progress. Deleting `/etc/apt/sources.list.d/nodesource.list` and running the install script again worked.

good job, it worked!!

**Comment by jotakar** [comment]
Hi, I have a similar issue. I can add the repository but I cannot use it. I got installed nodejs always.
I do:
curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
I get : 
## Installing the NodeSource Node.js 16.x repo...


## Populating apt-get cache...

+ apt-get update
Obj:1 http://security.debian.org/debian-security bullseye-security InRelease
Obj:2 http://deb.debian.org/debian bullseye InRelease                                                                      
Obj:3 http://deb.debian.org/debian bullseye-updates InRelease                                                              
Obj:4 https://deb.nodesource.com/node_14.x bullseye InRelease                                                              
Obj:5 https://dl.yarnpkg.com/debian stable InRelease  
Leyendo lista de paquetes... Hecho

## Confirming "bullseye" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/bullseye/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg >/dev/null

## Creating apt sources list file for the NodeSource Node.js 16.x repo...

+ echo 'deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x bullseye main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x bullseye main' >> /etc/apt/sources.list.d/nodesource.list
## Running `apt-get update` for you...
+ apt-get update
Obj:1 http://deb.debian.org/debian bullseye InRelease
Obj:2 http://deb.debian.org/debian bullseye-updates InRelease                                                                                       
Obj:3 http://security.debian.org/debian-security bullseye-security InRelease                                                                        
Des:4 https://deb.nodesource.com/node_16.x bullseye InRelease [4.586 B]                                                                             
Obj:5 https://dl.yarnpkg.com/debian stable InRelease                                            
Descargados 4.586 B en 0s (12,8 kB/s)
Leyendo lista de paquetes... Hecho
## Run `sudo apt-get install -y nodejs` to install Node.js 16.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
     echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn

No error. And the file nodesource.list is in the sources.list.d folder. 

But when I write
 apt-cache policy nodejs
I get following result
nodejs:
  Instalados: (ninguno)
  Candidato:  12.22.12~dfsg-1~deb11u1
  Tabla de versión:
     12.22.12~dfsg-1~deb11u1 500
        500 http://security.debian.org/debian-security bullseye-security/main i386 Packages
     12.22.5~dfsg-2~11u1 500
        500 http://deb.debian.org/debian bullseye/main i386 Packages
So it looks like it doesn't read the nodesource.list repository!!, is the source disabled? how to enable?
Where is the error?
Thanks

**Comment by JesusPaz** [comment]
the necessary line has already been added to the documentation #1494
