### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by icebluey** [nodesource/distributions#790]
#node -v
v11.8.0
Aborted (core dumped)

#uname -a
Linux ubuntu1604 4.19.18-041918-generic #041918.201901261840 SMP Sat Jan 26 18:42:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

All versions of node 11.x and node 10.x give this "Aborted (core dumped)" error.

**Comment by chrislea** [comment]
Hey, sorry to hear that. We don't actually support Node itself, we just package it up to make it easy for people to install. If you're having issues with Node itself, it's a better idea to report it directly to the [Node developers](https://github.com/nodejs/node). Hope this helps.
