### ISSUE TITLE
Unable to install nodejs10 Ubuntu 18.04

### ISSUE THREAD

**Issue by KursLabIgor** [nodesource/distributions#791]
Hi
I have ubuntu 18.04
Performed steps as described on your repository
As result on step `sudo apt-get update`
 Failed to fetch http://ppa.launchpad.net/nm-l2tp/network-manager-l2tp/ubuntu/dists/bionic/main/binary-amd64/Packages  404  Not Found [IP: 91.189.95.83 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
Any ideas ?

**Comment by chrislea** [comment]
`apt` is failing because of a PPA controlled by the `nm-l2tp` group. We don't have any influence over that, so we can't fix it. If you resolve that issue, possibly by removing the bad PPA, I expect things will work. Hope this helps!
