### ISSUE TITLE
Cant Install Node on Centos 7

### ISSUE THREAD

**Issue by ramrasi** [nodesource/distributions#794]
I am trying to install nodejs 10 but i got error as

"Your distribution, identified as "centos-release-7-5.1804.5.el7.centos.x86_64", is not currently supported,"

**Comment by Jackpoto** [comment]
Hello,

I suppose tha you use the wrong command to install nodejs.
Take a look at the doc, the good one for redhat and centos server is : curl -sL https://rpm.nodesource.com/setup_10.x | bash -

**Comment by meyerdg** [comment]
I hit this problem but it was mitigated by instructions at the top of the script that gets pulled down. Unfortunately you don't see that unless you come here and look or download, read and then run the script.

You may need your regular user environment (proxy settings?) if running through sudo you would run it like so:

curl -sL https://rpm.nodesource.com/setup_10x | sudo -E bash -

**Comment by karezza** [comment]
I'm seeing similiar:

# curl -ksL https://rpm.nodesource.com/setup_10.x | bash -

## Installing the NodeSource Node.js 10.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Your distribution, identified as "centos-release-7-6.1810.2.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by igsu** [comment]
@ramrasi @karezza this is not an issue anymore as CentOS 7 and CentOS 8 are currently supported.
Could you please confirm the issue is solved?

**Comment by karezza** [comment]
I've left the job where I was working on this.  However, I've contacted my old coworker and will see if we can get a confirmation on this.  Will update if I can get one.
