### ISSUE TITLE
Kali still not supported

### ISSUE THREAD

**Issue by JOduMonT** [nodesource/distributions#795]
Hi;

### I just install Kali from the [2018.04](https://www.kali.org/downloads/7/) version

`lsb_release -c -s` return me : n/a
`uname -r` return me : 4.19.0-kali1-amd64

I saw multiple time issues open than close from people running Kali : #792, #611, #502, #423, #317, #289, #153, #135, #119, #28

and Parrot : #788, #580, #575, #568, #554, #530, #499, #475

Now I didn't read all of them but considering both Distro are based on Debian Testing which is Sid and nodesource support Sid

#### why not simply

if $(uname -r)
return kali OR parrot
then should be something like this :

check_alt "Kali" "kali-rolling" "Debian" "Buster"

what do you think ?

**Comment by jodumont** [comment]
@xeptore it is true
[Kali](http://distrowatch.org/table.php?distribution=kali) and [Parrot](http://distrowatch.org/table.php?distribution=parrot) are based on Testing not unstable

and in my case I'm able to go over the issue
it is more for the community and the project. :)

**Comment by XaviTorello** [comment]
As a workaround, just provide the needed `VERSION_CODENAME` (used for `lsb_relase`):
```
# echo 'VERSION_CODENAME=kali-rolling' >> /etc/os-release
```

**Comment by igsu** [comment]
I just tried the setup script and it's working.
In my case I installed Node v12.14.1:

xxxxxxxxx@kali:~$ node -v
v12.14.1
xxxxxxxxx@kali:~$ lsb_release -c -s
kali-rolling
xxxxxxxxx@kali:~$ uname -r
5.3.0-kali2-amd64
Is this still an issue for you?
