### ISSUE TITLE
fedora-release-common-30-0.19.noarch NOT SUPPORTED

### ISSUE THREAD

**Issue by grgoffe** [nodesource/distributions#796]
Hi,

Apparently my distribution is not yet supported. Can you guys fix this please?

Regards,

George...

fedora-release-common-30-0.19.noarch

**Comment by joshas** [comment]
Fedora 30 was released yesterday. Distribution package name: fedora-release-common-30-1.noarch
Please add support for it.

**Comment by JunioSouz** [comment]
Same problem here fedora-release-common-30-1.noarch

**Comment by mcritchlow** [comment]
Still a thing with `fedora-release-common-30-4.noarch`

**Comment by igsu** [comment]
@grgoffe @joshas @JunioSouz support for Fedora 30 has been added: https://github.com/nodesource/distributions#enterprise-linux-based-distributions
