### ISSUE TITLE
node binary path creating issues when installing packages

### ISSUE THREAD

**Issue by KristijanZic** [nodesource/distributions#800]
$ sudo npm install -g nativescript
/usr/local/bin/tns -> /usr/local/lib/node_modules/nativescript/bin/tns
/usr/local/bin/nativescript -> /usr/local/lib/node_modules/nativescript/bin/tns
**npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/1684/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.**

> nativescript@5.2.0 postinstall /usr/local/lib/node_modules/nativescript
> node postinstall.js

2019/02/15 18:10:50.080036 cmd_run.go:871: WARNING: cannot create user data directory: cannot create "/nonexistent/snap/node/1684": mkdir /nonexistent: permission denied
cannot create user data directory: /nonexistent/snap/node/1684: Permission denied
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.6 (node_modules/nativescript/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript@5.2.0 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nativescript@5.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aresminos/.npm/_logs/2019-02-15T17_10_50_806Z-debug.log

**Comment by NatoBoram** [comment]
I'm having a similar issue with `nonexistent`. https://github.com/nwjs/npm-installer/issues/73

**Comment by igsu** [comment]
This issue is not related to the packages distributed in this repository.
