### ISSUE TITLE
fedora-release-29-7.noarch not supported 

### ISSUE THREAD

**Issue by RedFoxyC** [nodesource/distributions#803]
curl -sL https://rpm.nodesource.com/setup_8.x | sudo -E bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "fc29-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/fc/29/x86_64/nodesource-release-fc29-1.noarch.rpm'

**Comment by igsu** [comment]
@RedFoxyC support for Fedora 29 has been added: https://github.com/nodesource/distributions#enterprise-linux-based-distributions
