### ISSUE TITLE
Node installed through snap containers has linking dependency issues

### ISSUE THREAD

**Issue by mwamp** [nodesource/distributions#804]
OS : debian with snap containers

Take the following situation :
Your node package depends on a particular binary and is built at install by node-gyp
The binary compiles properly and is linked to some specific libs (In my case libstdcpp : GLIBCXX: 3.4.22)
At run time node will execute insides it's own container which may or may not have access to the same lib (in my case unfortunately the snap distro had installed  GLIBCXX 3.4.21)
So at run time you'll get a crash.
And then you have the joy of learning more about how your software stack is actually executing.

AFAIK  and AFAICT there is no documented way to upgrade the snap environment.
The issue comes from the fact that you build env is in fact different from you run env ( slightly but still )

I was very dubious about using the snapped version of node at first and rightly so as it appears. It would be nice point to possible issue in the installation doc in that regard. I think this is the kind of potential problems useful to have in mind when you make the decision to use such or such install platform so I bring it up.

I get this is a specific issue and few people will ever encounter it. But if anyone has ideas on how to work around this I'd be glad to hear them.

For now my workaround is to mount --bind the needed libs (which strangely is allowed whereas updating them is difficult).

Feel free to close the issue if no one  actually has any interest in this.

**Comment by modernlearner** [comment]
I'm also experiencing this issue when using node installed via snap. There are version mismatches when using node-gyp with the `core` package and GLIBC versions.
