### ISSUE TITLE
Unable to install nodejs v10 on Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by virtualvishwam** [nodesource/distributions#809]
Hi, I am unable t install Nodejs on Ubuntu 18.04.2 LTS (which is running on Windows).
Here are my version details -
  
  _No LSB modules are available.
  Distributor ID: Ubuntu
  Description:    Ubuntu 18.04.2 LTS
  Release:        18.04
  Codename:       bionic_

The error comes when I run this command -
  _curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -_

The terminal output is as follows - 

  `## Installing the NodeSource Node.js 10.x repo...

## Populating apt-get cache...

+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [273 kB]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [102 kB]
Get:7 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [126 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [71.4 kB]
Fetched 463 kB in 6s (77.2 kB/s)
Reading package lists... Done

## Confirming "bionic" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_10.x/dists/bionic/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js 10.x repo...

+ echo 'deb https://deb.nodesource.com/node_10.x bionic main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_10.x bionic main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Get:1 https://deb.nodesource.com/node_10.x bionic InRelease [4584 B]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Get:5 https://deb.nodesource.com/node_10.x bionic/main amd64 Packages [769 B]
Get:6 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:7 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
Ign:8 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en
Get:7 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [277 kB]
Err:7 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
  File has unexpected size (272624 != 276600). Mirror sync in progress? [IP: 91.189.88.152 80]
  Hashes of expected file:
   - Filesize:276600 [weak]
   - SHA256:700c3c81fe2136e5af413cf2dd678370c1e14265d4efb591b9e9610f8a5f1e3c
   - SHA1:87416c789d7bb387090a3ee232856cf3765d5282 [weak]
   - MD5Sum:daec3d81cb8677e0e50b2fc34a7d9250 [weak]
  Release file created at: Tue, 05 Mar 2019 16:12:19 +0000
Get:8 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [102 kB]
Err:8 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en

Fetched 94.1 kB in 7s (13.7 kB/s)
Reading package lists... Done
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/main/binary-amd64/Packages.xz  File has unexpected size (272624 != 276600). Mirror sync in progress? [IP: 91.189.88.152 80]
   Hashes of expected file:
    - Filesize:276600 [weak]
    - SHA256:700c3c81fe2136e5af413cf2dd678370c1e14265d4efb591b9e9610f8a5f1e3c
    - SHA1:87416c789d7bb387090a3ee232856cf3765d5282 [weak]
    - MD5Sum:daec3d81cb8677e0e50b2fc34a7d9250 [weak]
   Release file created at: Tue, 05 Mar 2019 16:12:19 +0000
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/main/i18n/Translation-en.xz
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting`

**Comment by BoGnY** [comment]
I've the same problem..
The script don't install node 10.x repo...
