### ISSUE TITLE
Debian bartholomea / TANGLU is not supported

### ISSUE THREAD

**Issue by arohrmann** [nodesource/distributions#81]
I got on an Debian Distro TANGLU this error:

**Comment by wblankenship** [comment]
@arohrmann could you please take a look at https://github.com/nodesource/distributions/blob/master/deb/setup#L76-L82 ? Modifying this with the appropriate mapping of Tanglu Bartholomea to Debian should solve your problem. If you can confirm and submit a PR against this file with the fix it would be appreciated! We, unfortunately, do not have the resources necessary to do all of these mappings, so we rely on community members such as yourself to get support on your favorite distributions!

**Comment by retrohacker** [comment]
Converting this to a PR against the README.md containing a list of requested distributions.

https://github.com/nodesource/distributions/pull/308
