### ISSUE TITLE
not supported on MX-Linux 18

### ISSUE THREAD

**Issue by muhammadSaferagic** [nodesource/distributions#811]
## Confirming "Continuum" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_11.x/dists/Continuum/Release'

**Comment by dominikk** [comment]
Hi there (@muhammadSaferagic),

the mapping to the underlying debian version seems to be broken. You have to add the following line:

```
check_alt "Continuum"     "Continuum" "Debian" "stretch"
```

![image](https://user-images.githubusercontent.com/1086332/54885197-f16d6b00-4e79-11e9-9a0e-880a97eb159f.png)

**Comment by jodumont** [comment]
I understand Continuum is declared and [I see it in the code](https://github.com/nodesource/distributions/blob/master/deb/setup_10.x#L246)

but I tried to install nodejs 10 on Linux MX Continuum and this error still there

```
Reading package lists... Done

## Confirming "Continuum" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_10.x/dists/Continuum/Release'

## Your distribution, identified as "Continuum", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by dominikk** [comment]
@jodumont,
have you tried the fix proposed here [1]? v.10 installed just fine for me.

[1] https://github.com/nodesource/distributions/issues/811#issuecomment-475995571
[2] 
![image](https://user-images.githubusercontent.com/1086332/60491216-959c5480-9ca8-11e9-8180-47bb7a4ea2fe.png)

**Comment by jodumont** [comment]
@dominikk I didn't understood before you point it out;
when I look at it it make sense and will work :)

**Comment by anselal** [comment]
I confirm that adding the line mentioned at https://github.com/nodesource/distributions/issues/811#issuecomment-475995571 works

**Comment by igsu** [comment]
@muhammadSaferagic Linux MX 18 Continuum is now supported!

Thanks for your patient, closing this issue now.
