### ISSUE TITLE
Fedora 28.3 not supported

### ISSUE THREAD

**Issue by Stan1sl0s** [nodesource/distributions#812]
# It seems that even in 64bit that's not supported - Update setup script granted versions ?

\# curl -sL https://rpm.nodesource.com/setup_11 | bash -

feedback : 
\## Your distribution, identified as "fedora-release-28-3.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

uname -a
Linux XXXXXX 4.19.5-200.fc28.x86_64 #1 SMP Tue Nov 27 20:19:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by JungMinu** [comment]
@gkrizek please take a look

**Comment by igsu** [comment]
Obsolete issue. Closing now.
