### ISSUE TITLE
cannot install nodejs 8.x on Kali linux 

### ISSUE THREAD

**Issue by pritItaliyaDev** [nodesource/distributions#814]
Tried many possibilities still cannot install nodejs 8.15.1 version.

**Comment by JungMinu** [comment]
Could you please post the errors if you see any?

**Comment by dexter313100** [comment]
can anyone please fix this issue fast.......  i have to hack my girlfriends phone

**Comment by XaviTorello** [comment]
As a workaround, just provide the needed `VERSION_CODENAME` (used by `lsb_relase`):
```
# echo 'VERSION_CODENAME=kali-rolling' >> /etc/os-release
```

**Comment by XaviTorello** [comment]
@Prit1104 probably [this workaround](https://github.com/nodesource/distributions/issues/795#issuecomment-476019261) may help you

**Comment by igsu** [comment]
@Prit1104 I just tried the setup script and it's working.
In my case I installed Node v12.14.1:

```
xxxxxxxxx@kali:~$ node -v
v12.14.1
xxxxxxxxx@kali:~$ lsb_release -c -s
kali-rolling
xxxxxxxxx@kali:~$ uname -r
5.3.0-kali2-amd64
```

Is this still an issue for you?
