### ISSUE TITLE
Failed to fetch Debian jessie-updates packages

### ISSUE THREAD

**Issue by alexbobes** [nodesource/distributions#817]
Hello,

Keep getting since yesterday 404 errors when trying to install packages from http://deb.debian.org jessie-updates/main amd64 Packages repository.

Using Dockerfile:

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - \ && apt-get install -y nodejs

Probably they've moved some repositories / packages. Until yesterday all was working fine. Log below.

Thank you.

```
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://deb.debian.org jessie InRelease
Ign http://deb.debian.org jessie-updates InRelease
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [822 kB]
Get:3 http://deb.debian.org jessie Release.gpg [2420 B]
Ign http://deb.debian.org jessie-updates Release.gpg
Get:4 http://deb.debian.org jessie Release [148 kB]
Ign http://deb.debian.org jessie-updates Release
Get:5 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Err http://deb.debian.org jessie-updates/main amd64 Packages
  
Err http://deb.debian.org jessie-updates/main amd64 Packages
  
Err http://deb.debian.org jessie-updates/main amd64 Packages
  
Err http://deb.debian.org jessie-updates/main amd64 Packages
  
Err http://deb.debian.org jessie-updates/main amd64 Packages
  404  Not Found
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found
```

**Comment by matthewbennink** [comment]
I ran into the same. However, it seems related to `apt` and not this project in particular. The line that fails is `apt-get update`. See https://deb.debian.org/, a couple lines down:

> The server deb.debian.org does not have packages itself, but the name has SRV records in DNS that let apt _in stretch and later_ find places.

Note the _in stretch and later_ phrase. It seems to me that `jessie` may no longer be available, or perhaps the files have been removed temporarily?

Either way, this suggests changes are needed at the OS/image/container-level, which would then allow this tool to work as expected.

**Comment by sansculotte** [comment]
same here. appearently "jessie-updates" is gone from the url
http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages
while
http://deb.debian.org/debian/dists/jessie/main/binary-amd64/Packages
would work.

**Comment by manuel-sanchez** [comment]
Any possible workaround for this? We are also seeing the same issues

**Comment by chrislea** [comment]
Folks, I'm not sure what to say here. NodeSource doesn't have any control over deb.debian.org. If there are problems with it, there's not anything NodeSource can do.

**Comment by gkrizek** [comment]
Yep, what @chrislea said is correct. This is an issue with `deb.debian.org` and outside of our control.

**Comment by sleibman** [comment]
Maybe the setup scripts (e.g. `https://deb.nodesource.com/setup_10.x` need to be updated to look at archive.debian.org, per https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository ?

**Comment by chrislea** [comment]
Those setup scripts don't reference any repositories other than the NodeSource ones. Anything other than deb.nodesource.com that you see is from your own `apt` setup.

**Comment by sleibman** [comment]
Got it. I see now. My comment above is wrong.
Agreed -- not a Nodesource problem.

But even updating our own `apt` setup (by modifying `/etc/apt/sources.list`) doesn't look like it helps because `jessie/updates` isn't (as of this moment) available at either http://archive.debian.org/debian/dists or http://deb.debian.org/debian/dists

Note that I ran into this problem on a docker image provided by CircleCI, so I imagine there are lots of other running into it on similarly provisioned machines.

**Comment by sansculotte** [comment]
> Got it. I see now. My comment above is wrong.
> Agreed -- not a Nodesource problem.
> 
> But even updating our own `apt` setup (by modifying `/etc/apt/sources.list`) doesn't look like it helps because `jessie/updates` isn't (as of this moment, 2019-03-26) available at either http://archive.debian.org/debian/dists or http://deb.debian.org/debian/dists

jessie has been officially deprecated. hence the retirement of package repositories.

> Note that I ran into this problem on a docker image provided by CircleCI, so I imagine there are lots of others running into it on similarly provisioned machines.

you can specify the os version in your circleci config, in the docker section, this should do the trick
   image: circleci/python:2.7.14-stretch

**Comment by sleibman** [comment]
> you can specify the os version in your circleci config, in the docker section, this should do the trick
image: circleci/python:2.7.14-stretch

Oh, yes, of course! Thank you! That works great.
