### ISSUE TITLE
Confirming "Continuum" is supported

### ISSUE THREAD

**Issue by muhagad** [nodesource/distributions#819]
+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/Continuum/Release'

**Comment by JungMinu** [comment]
What os are you using?

**Comment by jhalmu** [comment]
Same for me. MX linux. Current release: MX-18.1

**Comment by ironor** [comment]
Hello,
Just to signal that there is an error in the installation script. In the line 145, parameters 1 and 2 are in the wrong position. It should be : 
check_alt "mx-linux"      "Continuum" "Debian" "stretch"

and not 

check_alt "Continuum"    "mx-linux" "Debian" "stretch"

Regards, Ironor

**Comment by igsu** [comment]
@muhagad Linux MX 18 Continuum is now supported!

Thanks for your patient, closing this issue now.
