### ISSUE TITLE
Enterprise Linux Instructions Missing Install Step In README

### ISSUE THREAD

**Issue by byrdware** [nodesource/distributions#826]
The README.md for this project includes installation instructions for various package managers, however, it is lacking the final and most important step for the enterprise / Fedora / yum / dnf crowd, and that is the installation of node itself. There needs to be a <code>yum install nodejs</code> step added to the end of these instructions, with an alert to the new 'dnf' package manager, for those who have moved beyond yum.

**Comment by igsu** [comment]
Hi @byrdware 

During the execution of the scripts for these distributions, the instructions that you mention is provided only after successfully checking that there is support for the distro/version. Additional instructions that may be required in certain cases are also provided:

```
## Run `sudo yum install -y nodejs` to install Node.js 13.x and npm.
## You may also need development tools to build native addons:
     sudo yum install gcc-c++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
     sudo yum install yarn
```
