### ISSUE TITLE
Support Ubuntu 19.04

### ISSUE THREAD

**Issue by Maia-Everett** [nodesource/distributions#827]
Ubuntu 19.04 Disco Dingo is out, so `disco` should be supported as a distribution name.

**Comment by DiegoAlexanderManjarres** [comment]
Yes, Just installed Ubuntu Disco Dingo only to find out its not supported.

**Comment by MAFiA303** [comment]
bump!

**Comment by nxv109** [comment]
please, support nodejs on 19.04

**Comment by camdenorrb** [comment]
Yes please <3

**Comment by anurgsrivastava** [comment]
yes, please add the support as soon as possible

**Comment by faradoxuz** [comment]
Please

**Comment by faradoxuz** [comment]
You temporary solution worked for me:
` curl -L https://www.npmjs.com/install.sh | sh`
run this as root

**Comment by confusedwdeveloper** [comment]
Waiting for support. Sucks to see node not supported after installing 19.04

**Comment by likwidoxigen** [comment]
> Waiting for support. Sucks to see node not supported after installing 19.04

While there's no APT repository the SNAP packages are still available and working for me on 19.04. Just choose your version in the drop down next to the "install" button: https://snapcraft.io/node

19.04 has been out for barely a day officially I'd rather they release a quality product than rush it just to be there on day 0, especially when the SNAP's working fine.

**Comment by camdenorrb** [comment]
It wouldn't impact the quality to release on day 0 though, there have been beta releases since forever

**Comment by gkrizek** [comment]
Our Node.js repositories now support Ubuntu 19.04 (Disco Dingo)

**Comment by gbrohammer** [comment]
Also update your landing page.
