### ISSUE TITLE
iojs on elementaryOS luna / precise

### ISSUE THREAD

**Issue by carneeki** [nodesource/distributions#83]
Running elementaryOS luna.

Running ```curl -sL https://deb.nodesource.com/setup_iojs_1.x | sudo bash -``` yields the following output after apt-get runs and collects a few things:

```
## You seem to be using elementaryOS version luna.
## This maps to Ubuntu "precise"... Adjusting for you...

## Confirming "precise" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/iojs_1.x/dists/precise/Release'

## Your distribution, identified as "precise", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

I was able to install and run IO.js using 'trusty' if this helps. Perhaps the .debs can be shared between both distributions?

**Comment by wblankenship** [comment]
elementaryOS support landed here for reference: https://github.com/nodesource/distributions/pull/11/files

We do not, currently, have support for any distribution based on Ubuntu Precise in the iojs repository. To find the supported architecture/platform/version combinations, see here: https://deb.nodesource.com/iojs_1.x/pool/main/i/iojs/ 

And you can see the current mappings of Ubuntu and Debian to derivative distributions here: https://github.com/nodesource/distributions/blob/master/deb/setup#L76-82

If you are confident that the trusty binary is suitable for your system you can follow these steps:
(Please note, this is not a supported setup. While it might work, it may also be unstable.)

### Download setup file

 `curl -sL https://deb.nodesource.com/setup_iojs_1.x > setup.sh`

### Update distribution mapping

and then change line 84 in the newly created _setup.sh_ from 

`check_alt "elementaryOS" "luna" "Ubuntu" "precise"` 

to 

`check_alt "elementaryOS" "luna" "Ubuntu" "trusty"` 

### Run the modified script

`cat script.sh | bash -`

If that doesn't work, feel free to post back here for more help :smile:

**Comment by carneeki** [comment]
Hi William,

Setting up as trusty is working for me, but as you indicated, it may not be stable.

elementaryOS is releasing a trusty base in 3 or 4 days. If anyone is searching around - all I can say is "it worked for me".

Thanks for your help!
