### ISSUE TITLE
Confirming "Continuum" is supported

### ISSUE THREAD

**Issue by wolfitis** [nodesource/distributions#835]
After I run the command:
`sudo curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash`

after:
>  Reading package lists... Done

this appears: 

> ##Confirming "Continuum" is supported...
> + curl -sLf -o /dev/null 'https://deb.nodesource.com/node_12.x/dists/Continuum/Release'
> 
> Your distribution, identified as "Continuum", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

my OS details after running:
`lsb_release -a`

are:
> No LSB modules are available.
> Distributor ID:	MX
> Description:	MX 18.2 Continuum
> Release:            18.2
> Codename:	Continuum

**Comment by Bortechino** [comment]
There is an error in https://github.com/nodesource/distributions/blob/master/deb/setup_12.x
in string 246
check_alt "Continuum" "mx-linux" "Debian" "stretch"

should be
check_alt "MX" "Continuum" "Debian" "stretch"

**Comment by raghav135** [comment]
+1

**Comment by Tecardo1** [comment]
in 11 its on line 248 :)

**Comment by igsu** [comment]
@wolfitis Linux MX 18 Continuum is now supported!

Thanks for your patient, closing this issue now.
