### ISSUE TITLE
How to install on raspbian stretch? No guide... node 12

### ISSUE THREAD

**Issue by microfx** [nodesource/distributions#836]
Hey! 

Node is and was always horror for me - always wrong versions being installed and no guide for raspberry nowhere up to date - not even in this guide here. You don't make this easy for non superadmins. And why is node 8 installed over apt-get if we are at 12? Linux will stay too complicated for the rest of us if you are continue like this.

**Comment by endrin** [comment]
`curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -` works for Raspbian just fine.

**Comment by igsu** [comment]
Hey @microfx, so sorry to hear that.
`curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -` should work just fine for you.
Let me know if the issue persists.
