### ISSUE TITLE
Deepin Linux 15.10 not detected

### ISSUE THREAD

**Issue by Tecardo1** [nodesource/distributions#838]
The new base of deepin 15.10 is Debian Stretch, so i added this line:

check_alt "Deepin"        "stable"   "Debian" "stretch"
(Line 244 on Setup_11.x)
It's for the new branch of deepin and should work on all setups that support stretch.

**Comment by deepinaccount** [comment]
OS: Deepin 15.10 stable

`sudo apt install node`

`node -v
v10.15.3`

`npm -v
6.4.1`

**Comment by NewtonGrav** [comment]
The solution of @deepinaccount  helped me. 
Apparently deepin accepts at most the version v10.15.3

**Comment by igsu** [comment]
We've added support for Deepin 15.10 stable, closing this now.
