### ISSUE TITLE
"redhat-release-server-6Server-6.6.0.2.el6.x86_64", is not currently supported

### ISSUE THREAD

**Issue by emadandrews** [nodesource/distributions#84]
Is there any plan to support "redhat-release-server-6Server-6.6.0.2.el6.x86_64", i

**Comment by manid** [comment]
+1

**Comment by rvagg** [comment]
Are you getting an error from the setup script? It should be supported but currently only 0.10 is available but the RPMs are coming for 0.12 for rhel6

**Comment by EdwardCoyle** [comment]
+1

**Comment by retrohacker** [comment]
Enterprise Linux version 6 is now supported through the setup scripts

https://rpm.nodesource.com/pub_0.12/el/6/
