### ISSUE TITLE
Setup_12.x with fixes for Deepin, MX 18 "Continuum" and rewritten to use apt

### ISSUE THREAD

**Issue by Tecardo1** [nodesource/distributions#841]
changed to apt for setup_12.x
also added Deepin 15.10 and MX Linux 18 fixes. 
Hash tagged the source rep. It's optional.

You can use that file by saving it and run it like this: 
Rename it before ;)
sudo -E bash - '/home/XXX/setup_12.x' 
Tested on ubuntu 19.04, 18.04, deepin 15.10 and linux mint 19.1

[setup_12.txt](https://github.com/nodesource/distributions/files/3136829/setup_12.txt)

**Comment by Vitrixzyn** [comment]
Not working for me on MX Linux Continum.

**Comment by igsu** [comment]
@Tecardo1 Linux MX 18 Continuum is now supported!

Thanks for your patient, closing this issue now.
