### ISSUE TITLE
Please add support for Fedora 30

### ISSUE THREAD

**Issue by cyfrost** [nodesource/distributions#842]
Hi, I'm reporting that Fedora 30 (which was officially out 3~ days ago) isn't supported by the installer script.

On a fresh Fedora 30 Workstation installation, I've run the following command (found [here](https://github.com/nodesource/distributions/#rpminstall)):

`curl -sL https://rpm.nodesource.com/setup_12.x | bash -` 

I ran into the following error and the installation failed.

![Screenshot from 2019-05-02 22-47-22](https://user-images.githubusercontent.com/12471103/57093831-85114180-6d2c-11e9-8f0a-5bbceabe6206.png)

This happened while trying to install NodeJS 12.x

Thanks!

**Comment by Tecardo1** [comment]
can you post the output of lsb_release -a

**Comment by cyfrost** [comment]
@Tecardo1 Sure, here it is:

![image](https://user-images.githubusercontent.com/12471103/57097845-631cbc80-6d36-11e9-8b9b-66c7166239d0.png)

**Comment by Tecardo1** [comment]
can you try running this:
uname -m

and this: 
rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release

want to see the output, right now i don't have a fedora 30 system here, but to note, i'm not dev or maintaining this scripts. It will make thinks more clear for the devs.

**Comment by cyfrost** [comment]
output for `uname -m` is `x86_64`

output for `rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release`      is      `fedora-release-common-30-1.noarch`

**Comment by Tecardo1** [comment]
try replacing this: 
Line 216: DIST_VERSION=$(echo $DISTRO_PKG | sed -r 's/^[[:alpha:]]+-release(-server|-workstation|-client)?-([0-9]+).*$/\2/')

With

DIST_VERSION=$(echo $DISTRO_PKG | sed -r 's/^[[:alpha:]]+-release(-server|-workstation|-client|-common)?-([0-9]+).*$/\2/')

in the file, save it for that. Or use this file. 
run it with bash - 'Script location'

[setup_12rpm.zip](https://github.com/nodesource/distributions/files/3139596/setup_12rpm.zip)

**Comment by cyfrost** [comment]
@Tecardo1 Thanks for pitching in, I will try that when I get back to my comp.

Once I verify your changes as working, maybe someone from us can send a quick PR.

And yes, I'm using the normal workstation image downloaded from https://getfedora.org

**Comment by Tecardo1** [comment]
Please report back if it works :)

**Comment by paulomanrique** [comment]
@Tecardo1 I tried your change and got this:

```
## Installing the NodeSource Node.js 12.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "fc30-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_12.x/fc/30/x86_64/nodesource-release-fc30-1.noarch.rpm'

## Your distribution, identified as "fedora-release-common-30-1.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by Tecardo1** [comment]
Indeed they don't provide the rpm packages for fedora 30 right now. 28 and 29 are included only. Didnt check that, sorry :)

**Comment by cyfrost** [comment]
Just found out: For Fedora 29, the release URL of the RPM repo was:
`https://rpm.nodesource.com/pub_12.x/fc/29/x86_64/nodesource-release-fc29-1.noarch.rpm`

So, for Fedora 30, it should be:
`https://rpm.nodesource.com/pub_12.x/fc/30/x86_64/nodesource-release-fc30-1.noarch.rpm`

But if you look [here](https://rpm.nodesource.com/pub_12.x/fc/), you won't see "30" as a available directory indicating that releases aren't prepped for Fedora 30 yet.

All this might have been a moot discovery but I found this out while hacking the official [installation script](https://rpm.nodesource.com/setup_12.x) to see what it was doing.

Fingers crossed for faster Node 12 release on Fedora 30 (also Docker-CE for F30 isn't available yet :( ).

**Comment by Tecardo1** [comment]
As mentioned there is no Node 12 release for Fedora 30. But there isn't any release for fedora 30.

**Comment by mlouage** [comment]
Any update on this? From what I see above modifying the installer does not help because the rpm is not available on the server. Is there a way we can help building those rpm's so they are updated faster on the server?

**Comment by joaodforce** [comment]
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/9410916/58215594-f95a5780-7cd0-11e9-8d7b-eb964fd4334d.png">

I wonder why its printing .noarch when I'm running on x86_64 platform. I was trying with the 8.x script

**Comment by obsirdian** [comment]
Installing the Fedora 29 repo worked for me on 30... so far. If anyone else can't wait for the 30 package to be released:

`sudo dnf install https://rpm.nodesource.com/pub_12.x/fc/29/x86_64/nodesource-release-fc29-1.noarch.rpm`

`sudo dnf install nodejs`

**Comment by Tecardo1** [comment]
Right now there isn't much activity in here. Don't know what's happening, but your way could break things.

**Comment by cyfrost** [comment]
Also, if you're tired of all this (like I am). Simply start using NVM

**Comment by dwaynebradley** [comment]
Considering that Fedora 28 is now officially end-of-life, hopefully they will get the official package for 30 ready soon.

https://fedoramagazine.org/fedora-28-end-of-life/

**Comment by josenobile** [comment]
Now in Docker 
FROM fedora:latest is 30, build not working.

**Comment by salortiz** [comment]
From Jun 14 the rpm repositories exists, see [here for 10.x](https://rpm.nodesource.com/pub_10.x/fc/30/) or [here for 12.x](https://rpm.nodesource.com/pub_12.x/fc/30/)

```
sudo dnf install https://rpm.nodesource.com/pub_12.x/fc/30/x86_64/nodesource-release-fc30-1.noarch.rpm
sudo dnf intall nodejs
```
works.
Seem that only the fix for the script is missing.

**Comment by cyfrost** [comment]
The instructions at https://github.com/nodesource/distributions/#rpminstall now work as expected, so closing this issue, thanks for the fix.

**Comment by williamzachary209** [comment]
Please add support for Fedora 30

**Comment by vorburger** [comment]
> The instructions at https://github.com/nodesource/distributions/#rpminstall now work as expected --I was able to install Node 12 on Fedora 30 Workstation, so closing this issue, thanks for the fix.

just FYI, NOK for Node 8 for me, in a Fedora 30 container:

    FROM fedora:30
    RUN curl -sL https://rpm.nodesource.com/setup_8.x | bash -

causes:

```
STEP 4: RUN curl -sL https://rpm.nodesource.com/setup_8.x | bash -
tput: No value for $TERM and no -T specified

## Installing the NodeSource Node.js 8.x LTS Carbon repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || r
pm -q --whatprovides sl-release
+ uname -m

## Could not determine your distribution version, you may not be running a supported version of Enterprise Linux. Please contac
t NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect. Include your 'distribution p
ackage' name: fedora-release-common-30-5.noarch. 

Error: error building at STEP "RUN curl -sL https://rpm.nodesource.com/setup_8.x | bash -": error while running runtime: exit status 1
```

> using NVM (https://github.com/nvm-sh/nvm) instead,

Yeah that one works for me, so no action needed on this, just wanted to let you know.

BTW: Fedora 30 is also not mentioned on the README.
