### ISSUE TITLE
child_process.spawn produces empty string for various commands (node, npm, ncu)

### ISSUE THREAD

**Issue by kleinfreund** [nodesource/distributions#843]
* **Version**: v12.1.0, v13.1.0, v13.12.0, v14.10.1, v15.6.0
* **Platform**: Linux RAUMSTATION 5.0.0-13-generic 14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: child process (?)

I switched from the PPA binary (https://github.com/nodesource/distributions/blob/master/README.md#debinstall) to the snap binary (https://snapcraft.io/node). This started to break the `ncu -g` command. Originally, I opened an issue with npm-check-updates, but it doesn’t seem to be an issue on their end (for reference: https://github.com/tjunnone/npm-check-updates/issues/536).

Only with the snap binary do I get the following error:

```
/home/phil/.npm-global/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:387
        throw err;
        ^

Error: Expected JSON from "npm ls". This could be due to npm instability.


    at parseJson (/home/phil/.npm-global/lib/node_modules/npm-check-updates/lib/package-managers/npm.js:38:15)
    at /home/phil/.npm-global/lib/node_modules/npm-check-updates/lib/package-managers/npm.js:144:30
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

The command that is executed with `child_process.spawn` is `npm ls --global --depth=0 --json` which produces the correct JSON with both the PPA and the snap binary when executed directly from the terminal.

**Steps to reproduce**:

Create a reproduction.js file containing the following code and run `node reproduction.js` with `node` being a Node.js binary from a Snap source (reproduces with all versions from `v12` to `v14` at least).

```node
const { spawnSync } = require('child_process')

// Both these spawn commands will yield nothing in their stdout.
// The latter should just contain a Node version tring such as `v14.10.1`.

// npm ls --global --depth=0 --json
const npmListOutput = String(spawnSync('npm', ['ls', '--global', '--depth=0', '--json']).stdout)
console.log({ npmListOutput });

// node --version
const nodeVersionOutput = String(spawnSync('node', ['--version']).stdout)
console.log({ nodeVersionOutput });
```

To switch around the Node binary on Ubuntu:

1. Uninstall Node.

   ```
   sudo apt remove nodejs
   ```

2. Install Node via Snap.

   ```
   sudo snap install node --channel=14/stable --classic
   ```

3. Verify that Snap’s Node is used (i.e. on my system, the binary is reported to be in `/snap/bin/node` when running `which node`).
4. Run npm-check-updates with the global flag.

   ```
   ncu -g
   ```

5. Remove Node via Snap.

   ```
   sudo snap remove node
   ```

6. Install Node via apt.

   ```
   sudo apt install nodejs
   ```

**Comment by pachulo** [comment]
We were bitten by this same problem, and we think that is related to this: https://forum.snapcraft.io/t/snapd-2-32-breaks-live-server-installer/4597

**Comment by kleinfreund** [comment]
I’m closing this because there hasn’t been a response or interest in this issue (which is still happening).

**Comment by kleinfreund** [comment]
For posterity, both the following scripts produce the empty string when their commands executed in a shell return a completely different (and expected) results:

```node
const npm = require('child_process').spawnSync('npm', ['ls', '--global', '--depth=0', '--json', '--prefix=/home/phil/.npm-global'])
console.log(String(npm.stdout) === '');
```

The asynchronous variant never runs into either callbacks for `stdout` or `stderr` and completes with `child process exited with code 0`.

```node
const npm = require('child_process').spawn('npm', ['ls', '--global', '--depth=0', '--json', '--prefix=/home/phil/.npm-global'])

npm.stdout.on('data', (data) => {
    console.log(`stdout: ${data}`);
});

npm.stderr.on('data', (data) => {
    console.error(`stderr: ${data}`);
});

npm.on('close', (code) => {
    console.log(`child process exited with code ${code}`);
});
```

**Comment by kleinfreund** [comment]
This is still broken in the Snap distribution of Node.js.

The following short program logs `true` even though the expression `String(npm.stdout)` should evaluate to a dependency graph of globally installed npm packages.

```node
const npm = require('child_process').spawnSync('npm', ['ls', '--global', '--depth=0', '--json', '--prefix=/home/phil/.npm-global'])
console.log(String(npm.stdout) === '');
```

This issue makes the Snap distribution of Node.js unuseable for me.

**Comment by desmap** [comment]
I just had the same issue with coc.vim which relies on node. When it`s installed via snap coc.vim cannot check node's version number: https://github.com/neoclide/coc.nvim/issues/2870

**Comment by igsu** [comment]
We are not responsible for maintaining the Snap packages, to solve any issue or more information:

https://github.com/nodejs/snap
