### ISSUE TITLE
wrong dependencies for Debian jessie

### ISSUE THREAD

**Issue by TerranUlm** [nodesource/distributions#846]
The debian packages (node.js 12) for jessie (Raspian) require libstdc++6 with version >5 - but jessie has only 4.9 available:

https://packages.debian.org/en/jessie/libstdc++6
https://deb.nodesource.com/node_12.x/dists/jessie/main/binary-armhf/Packages

**Comment by ignatiusmy** [comment]
Yep, getting a problem with it. Been trying to install node 12 on my CHIP SBC which is using Debian Jessie. Should I resort to an older version of node or find a way to update my libstdc++6/gcc?

![2019-11-24 00_29_39-chip@blbsr_ ~](https://user-images.githubusercontent.com/811623/69482935-758a4f00-0e5c-11ea-83da-d1e573caa4fe.png)
