### ISSUE TITLE
curl is failing to install the node.js binary distribution

### ISSUE THREAD

**Issue by prasunjit** [nodesource/distributions#850]
While trying to install node.js in our Docker, it is failing to find the packages.
We are running the below command in our Docker file

```
curl -sL https://deb.nodesource.com/setup_10.x | bash -
apt-get install -y nodejs
```

It fails with the below errors 

> The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file
> The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file
> The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file
> Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  Connection failed
> Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  Connection failed
> Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  Connection failed

Could anybody help us understand if this distribution is having problem and should use below command
```
curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by oliverw** [comment]
Can confirm. Same result in WSL Ubuntu 18.03 Bionic on Windows 10 (1903). After running it, the entire WSL becomes unusable until you reboot.

**Comment by prasunjit** [comment]
@oliverw Do you know if we are supposed to call a different script ? In case if you have resolved this

**Comment by uqcgreen** [comment]
I'm getting the same issue, script works find until it hits apt-get update, then:

> Err:5 https://deb.nodesource.com/node_12.x stretch/main Sources
>    The HTTP server sent an invalid reply header

> Reading package lists...
> W: The repository 'https://deb.nodesource.com/node_12.x stretch Release' does not have a Release file.
> E: Failed to fetch https://deb.nodesource.com/node_12.x/dists/stretch/main/source/Sources  The HTTP server sent an invalid reply header
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get update' returned a non-zero code: 100

**Comment by ArPharazon** [comment]
any update on this issue? :/
