### ISSUE TITLE
Basic Installation Problems

### ISSUE THREAD

**Issue by relknip** [nodesource/distributions#852]
Hi,

I'm trying to get the Zenko-Cloudserver up and running on a Ubuntu 18.04.2 Server.

root@mrh-zenko:/home/zenko/S3# npm -v
6.9.0
root@mrh-zenko:/home/zenko/S3#
root@mrh-zenko:/home/zenko/S3#
root@mrh-zenko:/home/zenko/S3# node -v
v12.3.1

I'm not even get over the install steps. I tried ubuntu 14.04 16.04 / debian / and now ubuntu 18.04 and just don't know how to get this zenko server up and running.

root@mrh-zenko:/home/zenko/S3# npm start

> @zenko/cloudserver@8.1.0-beta start /home/zenko/S3
> npm-run-all --parallel start_dmd start_s3server

sh: 1: npm-run-all: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @zenko/cloudserver@8.1.0-beta start: `npm-run-all --parallel start_dmd start_s3server`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @zenko/cloudserver@8.1.0-beta start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-31T15_25_26_763Z-debug.log

Can somebody help what i'm doing wrong?

Thanks
Raphael

**Comment by relknip** [comment]
root@mrh-zenko:/home/zenko/S3# npm install
The authenticity of host 'github.com (140.82.118.4)' can't be established.arsenal@github:scality/arsenal#787f664 Command failed: git clone --mirr
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? [  ................] | fetchMetadata: sill fetchPackageMetaData error for arsenal@github:sc[  ................] | fetchMetadata: sill fetchPackageMetaData error for arsenal@github:scality/arsenal#787f664 Command failed: git clone --mirr

**Comment by igsu** [comment]
Hi @relknip:

Unfortunately, this issue is not related to the distributions of this repository. Probably [here](https://github.com/scality/cloudserver) you will find more help.

Closing this now.
