### ISSUE TITLE
Installation on RHEL

### ISSUE THREAD

**Issue by g1ps** [nodesource/distributions#853]
The instructions (`sudo curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -`) fail on RHEL, and probably others, for those of us who have to use sudo and don't have root access. After a miserable time I finally found that **_sudo_** `curl -sL https://rpm.nodesource.com/setup_12.x |` **_sudo_** `bash -` does work. It would be nice to have this documented and save us wasting time to find that out.

Thanks.

**Comment by igsu** [comment]
This will be solved as of #993, thank you for noticing, closing this now.
