### ISSUE TITLE
Centos 6 packages are broken for Node 12

### ISSUE THREAD

**Issue by twk3** [nodesource/distributions#859]
Installing on centos 6 results in the following errors

```
---> Package nodejs.x86_64 2:12.0.0-1nodesource will be installed
--> Processing Dependency: libstdc++.so.6(CXXABI_1.3.5)(64bit) for package: 2:nodejs-12.0.0-1nodesource.x86_64
--> Processing Dependency: libc.so.6(GLIBC_2.17)(64bit) for package: 2:nodejs-12.0.0-1nodesource.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.15)(64bit) for package: 2:nodejs-12.0.0-1nodesource.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.18)(64bit) for package: 2:nodejs-12.0.0-1nodesource.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.14)(64bit) for package: 2:nodejs-12.0.0-1nodesource.x86_64
--> Finished Dependency Resolution
Error: Package: 2:nodejs-12.0.0-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
Error: Package: 2:nodejs-12.0.0-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(GLIBCXX_3.4.18)(64bit)
Error: Package: 2:nodejs-12.0.0-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(CXXABI_1.3.5)(64bit)
Error: Package: 2:nodejs-12.0.0-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(GLIBCXX_3.4.14)(64bit)
Error: Package: 2:nodejs-12.0.0-1nodesource.x86_64 (nodesource)
           Requires: libc.so.6(GLIBC_2.17)(64bit)
```

**Comment by danieleCode** [comment]
Same error installing on centos 6, please check it.

**Comment by Roguelazer** [comment]
This is still broken; it looks like these were compiled on an EL7 machine by accident.

**Comment by magnets-is-magic** [comment]
A server I manage is having this issue now when trying to update nodejs.

**Comment by nlfiedler** [comment]
Seems like binaries for Node.js v12.14 itself have this problem; I tried running the binary from the "Linux Binaries" tarball on nodejs.org and it reported identical linking errors.

**Comment by Roguelazer** [comment]
Yeah upstream no longer builds releases that support glibc 2.12 or libstdc++ 4.x.

I "solved" this problem by backporting gcc 9, building a node binary with `-static-libstdc++` and hoping none of my users ever expect to be able to install a C/C++ extension with the system C compiler.

Practically, unless you're interested in maintaining your own distribution with a backported glibc, gcc, and libstdc++, you're unlikely to get a working Node 12 on EL6.

**Comment by IgorUsoltsev** [comment]
I don't know if that might help anyone but I got rid of this bug
https://stackoverflow.com/a/42704095/6726769

~~~
yum clean all
rm -rf /var/cache/yum/*
yum update
~~~

Be sure to update Node download version with or so
`curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -`

**Comment by igsu** [comment]
As mentioned above, Node.js 12.x is not supported on EL6.
