### ISSUE TITLE
io.js not supported on Ubuntu 12.04 LTS Precise

### ISSUE THREAD

**Issue by pmontrasio** [nodesource/distributions#86]
There are no files for precise at https://deb.nodesource.com/iojs_1.x/dists/
12.04 is a LTS distribution supported for two more years and installed on many servers.

**Comment by rvagg** [comment]
older distros are a work in progress given the complexities of the toolchain required to compile on them, we'll get there soon!

**Comment by garthk** [comment]
Could you define 'soon', @rvagg? @chrislea had mastered the complexities of the toolchain, but he handed it to you a year ago. If it'll actually be 'never' for Node 4 on `precise`, could you break it to us earlier rather than later?

**Comment by chrislea** [comment]
Actually that's not on @rvagg's plate, that's still me, and I've been working on it a bunch recently. Still have some non-trivial yak to shave, but I am honestly hoping to get this done next week. No promises of course but that is honestly what I'm aiming for.

**Comment by demian85** [comment]
Any news on this? I need it!!

**Comment by chrislea** [comment]
Please ref: https://github.com/nodesource/distributions/issues/125#issuecomment-143911468

**Comment by chrislea** [comment]
Node 4.1.1 is available for precise now.

**Comment by garthk** [comment]
Thanks yet again, @chrislea.
