### ISSUE TITLE
Please add s390x as a supported platform

### ISSUE THREAD

**Issue by fosslou** [nodesource/distributions#860]
s390X as a supported platform. 

Developers can get a  LinuxOne RHEL distribution VM @ https://developer.ibm.com/linuxone/

**Comment by JesusPaz** [comment]
Hi @fosslou. At this time we only support the following architectures:
- **x86_64** (64-bit)
- **arm64** (ARM 64-bit, ARMv8 and up: aarch64-linux-gnu)

At the moment we do not plan to support s390X.
