### ISSUE TITLE
install node without npm on ubuntu 19.04

### ISSUE THREAD

**Issue by marslord** [nodesource/distributions#861]
follow the guide:

> # Using Ubuntu
> curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
> sudo apt-get install -y nodejs

get the node :  v10.15.2

but need to install npm by `sudo apt install npm`, get npm 5.8.0

when use `npm i ...`, get the warning 
> npm does not support Node.js v10.15.2

**Comment by marslord** [comment]
Sorry for my bad!
I closed my proxy then reinstalled, then node and npm both installed.

**Comment by shrmrf** [comment]
@marslord you can set proxy with:
```bash
sudo snap set system proxy.http="<PROX:Y>"
sudo snap set system proxy.https="<PROX:Y>"
```
