### ISSUE TITLE
Deepin 15.10.1 - ERRO: NO_PUBKEY  (RESOLVIDO)

### ISSUE THREAD

**Issue by luizgustavo77** [nodesource/distributions#863]
I just got this message when i tried to install node 10 in Deepin 15.10.1
## Populating apt-get cache...

+ apt-get update
Hit:1 https://repo.skype.com/deb unstable InRelease
Hit:2 https://download.docker.com/linux/debian stretch InRelease                                                                                                                
Hit:3 https://repos.influxdata.com/debian stretch InRelease                                                                                                                     
Hit:4 http://packages.microsoft.com/repos/vscode stable InRelease                                                                                                               
Hit:6 http://ppa.launchpad.net/ansible/ansible/ubuntu disco InRelease                                                                                                           
Hit:7 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease                                                                                               
Hit:8 http://packages.deepin.com/deepin panda InRelease                                                                                                               
Hit:5 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Hit:9 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease
Reading package lists... Done

## Confirming "stable" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_10.x/dists/stable/Release'

**Comment by EudesSA** [comment]
Estou com o mesmo problema no meu Deepin 15.10.1

**Comment by luizgustavo77** [comment]
ERRO- As assinaturas a seguir não puderam ser verificadas devido à chave pública não estar disponível: NO_PUBKEY NÚMERO_DA_CHAVE
SOLUCAO- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys NÚMERO_DA_CHAVE

**Comment by PHPINHEIRO** [comment]
estou com esse mesmo problema, como eu consigo essa chave?

**Comment by FelipeLarsen** [comment]
também estou com esse problema. tentei esse comando: ¨sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys¨ mas nao adiantou nada, como n sei que chave é essa nao coloquei nada depois tbm.

**Comment by igsu** [comment]
We've added support for Deepin 15.10 stable, closing this now.
