### ISSUE TITLE
can't install nodejs 8 on ubuntu 19.04

### ISSUE THREAD

**Issue by thameemk612** [nodesource/distributions#866]
can't install nodejs 8 on ubuntu 19.04. 
Even after using "curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -" , system install 
nodejs 10.15.2

**Comment by johnny4young** [comment]
hi @thameemk612, thank you for reach out to us, as you mentioned, the normal workflow is trying to get the latest version of Node.js by default. but if you want any specific version, there is a solution in the FAQ section:
https://github.com/nodesource/distributions/issues/657

let me post a recap:

- Remove the current nodejs installed:  
```
sudo apt-get purge nodejs 
```
- Open preference 
``` 
sudo vim /etc/apt/preferences.d/nodesource 
```
- Paste this configuration:
```
Package: *
Pin: origin deb.nodesource.com
Pin-Priority: 600
```
- Verify the change:
```
apt-cache policy nodejs
```
- trying again to install Node.js
```
sudo apt-get install nodejs
```

Please let me know if this solution works for you.

Regards,

**Comment by thameemk612** [comment]
Thanks @johnny4young , Its working

**Comment by jasdheer** [comment]
This works https://hostadvice.com/how-to/how-to-install-and-configure-node-js-on-debian-9/
