### ISSUE TITLE
Can’t install node.js repo because I can’t find and download the gpg key

### ISSUE THREAD

**Issue by sudoranger** [nodesource/distributions#867]
Link:

https://deb.nodesource.com/gpgkey/nodesource.gpg.key

Result:

The operation couldn’t be completed. (QuickLookErrorDomain error 16.)

(null)

**Comment by JungMinu** [comment]
Which version of OS are you using?

**Comment by sudoranger** [comment]
Ubuntu 18.04.2

**Comment by sudoranger** [comment]
I tried again a few hours later and it was fixed. Not sure what went wrong. I’m able to install it now.
