### ISSUE TITLE
Fedora 22 (beta) isn't supported by NodeSource

### ISSUE THREAD

**Issue by Lern-X** [nodesource/distributions#87]
Hello to everyone,

I wrote this command : "sudo wget -qO- https://rpm.nodesource.com/setup | bash -" and it returned an error.

"Your distribution, identified as "fedora-release-22-0.15.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support"

Fedora 22 is still a beta version, but it will be released at the end of this month (May).

Is it possible, please, to make NodeSource compatible with Fedora 22 ?
Thank you.

Best regards,

**Comment by om4rezz** [comment]
BTW, Fedora 21 is NOT supported too and gives the same error!

**Comment by rvagg** [comment]
oh? I thought Fedora 21 was supported .. I see that 22 has just been released too so I'll put that on our list of supported platforms.

**Comment by rvagg** [comment]
i.e. will let you know here

**Comment by harrytruong** [comment]
@om4rezz FWIW, I just checked and Fedora 21 is currently working. Have you tried again recently? 

I've added Fedora 21 support to the README in my PR: https://github.com/nodesource/distributions/pull/100

However, Fedora 22 is still unsupported. (Missing `https://rpm.nodesource.com/pub/fc/22/` for it?)

**Comment by den-is** [comment]
support for Fedora 22 will be very appreciated
+1

**Comment by Ava7** [comment]
++

**Comment by NickNaso** [comment]
Fedora 22 is not in beta at this time please support this OS version!

**Comment by aidylewis** [comment]
+1

**Comment by RobertBaron** [comment]
+1

**Comment by chrislea** [comment]
Hi all - we have builds for FC22 up, but we're still testing them to make sure things work as expected. If you'd like to give them a test run, you can install the RPMs directly:

https://rpm.nodesource.com/pub_0.10/fc/22/x86_64/
https://rpm.nodesource.com/pub_0.12/fc/22/x86_64/
https://rpm.nodesource.com/pub_iojs_2.x/fc/22/x86_64/
https://rpm.nodesource.com/pub_iojs_3.x/fc/22/x86_64/

Again, for now these are "use at your own risk", but if you'd like to take them for a spin please do and let us know what you find. Thanks!

**Comment by Ava7** [comment]
@chrislea Thank you, appreciated! :+1:

**Comment by felipesousa** [comment]
Worked for me! Thanks :+1:

**Comment by gbraad** [comment]
please move to general usage

**Comment by wiese** [comment]
Fedora 22 is not beta anymore, installer still wont work
```
$ curl --silent --location https://rpm.nodesource.com/setup | bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release
+ uname -m

## Confirming "fc22-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub/fc/22/x86_64/nodesource-release-fc22-1.noarch.rpm'

## Your distribution, identified as "fedora-release-22-1.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

Thanks for a timely resolution

**Comment by Draccoz** [comment]
Fedora 23 is coming soon, and this has not been yet fixed for F22. I am very disappointed. Please do fix it ASAP.

**Comment by chrislea** [comment]
@wiese sorry about that, we'll have a look at the installer script(s).

FC22 does have builds available, you can grab them directly from here:

<https://rpm.nodesource.com/pub_4.x/fc/22/x86_64/>

They don't get as much testing as the Ubuntu / Debian packages, so we're not as vocal about them, but plenty of people are using them and we haven't gotten any scary reports of problems, so please feel free to jump in. And, of course, let us know if anything doesn't work the way it should.

**Comment by cfchase** [comment]
+1

**Comment by trammel** [comment]
Fedora 23 is out, meaning 21 is now an unsupported release. But your repo doesn't have a nodesource-release-fc22-1.noarch.rpm at https://rpm.nodesource.com/pub/fc/22/x86_64/ so the install instructions fail.

**Comment by felipesousa** [comment]
because you  no try with source code? With me worked! https://nodejs.org/en/

**Comment by chrislea** [comment]
Please see the install instructions [here](https://github.com/nodesource/distributions/#rpminstall).

For 4.x, the release rpm you want is here.

https://rpm.nodesource.com/pub_4.x/fc/22/x86_64/nodesource-release-fc22-1.noarch.rpm
