### ISSUE TITLE
Debian testing - new distro name -> "bullseye"

### ISSUE THREAD

**Issue by patrick-ausderau** [nodesource/distributions#873]
Hi,

## Your distribution, identified as "bullseye", is not currently supported
Debian released new stable last week. So debian testing is now bullseye. 

Can you please add? 

Thanks!

**Comment by Daniel15** [comment]
For what it's worth, the buster repo still works fine on bullseye:
```
deb https://deb.nodesource.com/node_12.x buster main
deb-src https://deb.nodesource.com/node_12.x buster main
```

**Comment by patrick-ausderau** [comment]
Thanks for temporary fix. But, the idea of a script is to avoid to have to manually edit the config files...

As already asked two years ago #489, why not using "testing" instead of code names? Otherwise, (even if the next release date has not have been announced yet) debian usually follow a 2 year cycle before publishing a new version (and maintain (old) stable for 5 years). So the same distro name problem will arise in summer 2021.

**Comment by ZeroAurora** [comment]
I use Debian testing as a rolling release, so it would be better to use "testing" rather than each version's own codename.

**Comment by im-n1** [comment]
Just ran into this. Seems like it's one line fix but no response from the maintainers at all. Node is being node.

**Comment by ZeroAurora** [comment]
@im-n1 Well, one of the solutions is to use a user-wide node version manager (`nvm` for example). However, I'd rather choose a system-wide installation (since `nvm` slows down my shell). But it seems as if no one cares about Debian bullseye... I regret that I didn't stick to Debian stable.

**Comment by Matheesan2113** [comment]
> Just ran into this. Seems like it's one line fix but no response from the maintainers at all. Node is being node.

Newbie here, what may the one line fix be? A brief explanation could help too if you can. Thanks

**Comment by im-n1** [comment]
@Matheesan2113 use `buster` instead.

**Comment by danger89** [comment]
Could you try? https://node.melroy.org/ instead.

**Comment by au5ton** [comment]
Someone might need this:

`curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -`

**Comment by asperduti** [comment]
In the README you have the instruction to make a [manual instaltion](https://github.com/nodesource/distributions#manual-installation) when the distro is not supported.

But yes, I agree that it will be to use "testing" instead of the distro codename.

**Comment by vasanthdeveloper** [comment]
> Someone might need this:
> 
> `curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -`

If you are using `buster` repositories on `bullseye` this :point_up:  is required to be run before doing an `apt update`.
