### ISSUE TITLE
NPM update frequency

### ISSUE THREAD

**Issue by arothian** [nodesource/distributions#874]
What is the frequency that the npm versions in the deb package are updated?

In particular, I'm looking to see npm version 6.10.0 or greater be packaged by default due to fixed included around vulnerable dependencies in npm. 

It looks like the the node 8x deb package, it currently provides npm 6.4.1

**Comment by igsu** [comment]
Hi @arothian, with each new version of Node, the latest version of `npm` available at that time is packed by default. For example, at this moment the latest version for Node 12 is `v12.14.0` and it comes by default with npm `v6.13.4`

You can get the npm version for each release [here](https://nodejs.org/en/download/releases/).
