### ISSUE TITLE
node/npm version mis-match

### ISSUE THREAD

**Issue by SilkAndSlug** [nodesource/distributions#875]
I've installed `nodejs` and `npm` packages on Debian Buster. Running `npm` gives this error:

    npm WARN npm npm does not support Node.js v10.15.2
    npm WARN npm You should probably upgrade to a newer version of node as we
    npm WARN npm can't make any promises that npm will work with this version.
    npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
    npm WARN npm You can find the latest version at https://nodejs.org/

Packages from this repo should be compatible.

`node -v` gives `v10.15.2` ; `npm -v` gives `5.8.0`

**Comment by razsh** [comment]
`curl -sL https://deb.nodesource.com/setup_6.x | bash -`
actually install `v10.15.2`

**Comment by razsh** [comment]
`curl -sL https://deb.nodesource.com/setup_6.x | bash -` will install node version 10 and with no `npm`.
I believe the same is true for `setup_8.x`.

**Comment by rhpereda** [comment]
Hi, i'm facing the same issues with `curl -sL https://deb.nodesource.com/setup_8.x | bash -`, any updates or workarounds?

**Comment by ashhadsheikh** [comment]
+1, while curling `setup_6.x` we get version 10.

**Comment by StevenPyle** [comment]
Confirmed, both setup_6.x and 8.x install 10.15.  We do a CI build pinned on node 8.  It installed 8 on Friday and started installing 10 on Monday so something changed in the last few days.  A workaround is possible by adding a /etc/apt/preferences.d/nodesource file which gives priority to the nodesource version.  Details can be found here:  #866

**Comment by pixelbrackets** [comment]
> Confirmed, both setup_6.x and 8.x install 10.15. We do a CI build pinned on node 8. It installed 8 on Friday and started installing 10 on Monday so something changed in the last few days. A workaround is possible by adding a /etc/apt/preferences.d/nodesource file which gives priority to the nodesource version. Details can be found here: #866

Same here, we use Debian 10 and node 8 in one of our CI builds and get node 10 instead, without npm. It was working before however.

A workaround is to pin the version to 8 using the method suggested in #866. In our case I added the following line right before the nodejs install command to make the builds green again.

```bash
(echo "Package: *" && echo "Pin: origin deb.nodesource.com" && echo "Pin-Priority: 600") > /etc/apt/preferences.d/nodesource
```
