### ISSUE TITLE
Workaround for unsupported HeliOS (Unix-like) operating system

### ISSUE THREAD

**Issue by altgov3en** [nodesource/distributions#877]
Hello, I'm new to the world of Unix-like operating system and that's why I've got confused after I tried to install NodeJS on my current Virtual Machine (VM) running Unix-like operating system - HeliOS.

Following the [installation tutorial](https://tecadmin.net/install-latest-nodejs-and-npm-on-centos/) I've executed the following commands in the terminal:

> yum install -y gcc-c++ make
> curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -

and received the following error message:

> You don't appear to be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support. Include your 'distribution package' name: **helios-release-7.5-1.helios7.x86_64**.

Is there any workaround to succeed with the NodeJS installation?

Thanks.

**Comment by igsu** [comment]
@altgov3en unfortunately, and as specified in the script response, HeliOS is not a supported version of Enterprise Linux, so these scripts cannot be used and there's no workaround available in this channel to succeed on that specific regard. 

Closing this now.
