### ISSUE TITLE
Problems Installing on Linux Mint 19.2b

### ISSUE THREAD

**Issue by Hygens** [nodesource/distributions#878]
## Confirming "tina" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_12.x/dists/tina/Release'

## Your distribution, identified as "tina", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

That above is the error when I attempt install nodejs 12 on Linux Mint 19.2 Beta Release.
Linux Mint Tina is Based on Ubuntu 19.04 and Ubuntu 18.04 and this is supported.

Thank you,

**Comment by kanyi** [comment]
It's looks like the same problem:
https://github.com/nodesource/distributions/issues/872#issuecomment-516409929

**Comment by DEVfancybear** [comment]
I also suffer from such a situation

**Comment by TickleMaPickle** [comment]
Having the same problem.

**Comment by mathiaspueschel** [comment]
Same problem here.

**Comment by Hygens** [comment]
Hi guys!

here the unique alternative is install via snapd while not solved that issue:
https://nodesource.com/blog/installing-nodejs-tutorial-using-snaps-on-linux/

All teh best,

**Comment by manikk** [comment]
Confirming the same problem with Fresh Install of Linux Mint 19.2 while trying to install Node 10.x

`## Installing the NodeSource Node.js 10.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://ppa.launchpad.net/geary-team/releases/ubuntu bionic InRelease                                                                                              
Hit:2 http://archive.canonical.com/ubuntu bionic InRelease                                                                                                              
Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease                                                              
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                              
Ign:5 http://packages.linuxmint.com tina InRelease                       
Hit:6 http://packages.linuxmint.com tina Release                         
Hit:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:9 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done

## Confirming "tina" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_10.x/dists/tina/Release'

## Your distribution, identified as "tina", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
`

**Comment by bkilinc** [comment]
Same problem here. Cannot install Node 12 on Linux Mint 19.2 .

**Comment by bkilinc** [comment]
I just installed it by downloading the script with wget
`wget https://deb.nodesource.com/setup_12.x` 
open it with
`nano setup_12.x`
add the line after all Linux Mint definitions
`check_alt "Linux Mint"    "tina"     "Ubuntu" "bionic"`
make the setup script executable and run. finally;
`sudo apt-get install -y nodejs`

**Comment by TickleMaPickle** [comment]
@bkilinc Thanks Man, You saved my hide. :+1:

**Comment by Vlad-Shevliakov** [comment]
@bkilinc  What means _make the setup script executable and run_? How do that?

**Comment by srldl** [comment]
@mathiaspueschel Vlad-Shevliakov
chmod 755 setup_12.x
sudo ./setup_12.x

> 
> 
> @bkilinc What means _make the setup script executable and run_? How do that?

chmod 755 setup_12.x
sudo ./setup_12.x

**Comment by srldl** [comment]
> @bkilinc What means _make the setup script executable and run_? How do that?

chmod 755 setup_12.x
sudo ./setup_12.x

**Comment by Vlad-Shevliakov** [comment]
@bkilinc 😚😚😚 👍👍👍
@srldl 😚😚😚 👍👍👍
Thanks guys!

**Comment by mnezmah** [comment]
> > @bkilinc What means _make the setup script executable and run_? How do that?
> 
> chmod 755 setup_12.x
> sudo ./setup_12.x

Thanks for 'translation' :)

**Comment by Vlad-Shevliakov** [comment]
@mnezmah Something is wrong?

**Comment by bkilinc** [comment]
In nemo, right click the setup file, select 'properties' and then select Permissions Tab. Click on "Allow executing file as program". This will make the file executable. After that, double click the setup file, this will execute the file. Finally you can run "sudo apt-get install -y nodejs" to install nodejs. Happy coding :) this was just a start.

**Comment by mnezmah** [comment]
@Vlad-Shevliakov 
nothing is wrong, I am just saying thank you that you have translated 
"make the setup script executable and run? "
to those two commands
```chmod 755 setup_12.x
sudo ./setup_12.x```
so I can so it right. 
great job :)

**Comment by CaoSagan** [comment]
Thanks @bkilinc , I used this example for the 10.x and works very well!!!

**Comment by Kanhasonu21** [comment]
E: The repository 'https://deb.nodesource.com/node_10.x tina Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting 

this is happening

**Comment by danruiyot** [comment]
Thanks. Worked fine

> I just installed it by downloading the script with wget
> `wget https://deb.nodesource.com/setup_12.x`
> open it with
> `nano setup_12.x`
> add the line after all Linux Mint definitions
> `check_alt "Linux Mint" "tina" "Ubuntu" "bionic"`
> make the setup script executable and run. finally;
> `sudo apt-get install -y nodejs`

**Comment by alannaidon** [comment]
Unfortunatelly that didn't work for me neither =(

**Comment by kewi69** [comment]
Had the same problem but followed "Manual installation" and then changed tina to bionic in  nodesource.list
But I find it a little strange that this is not resolved yet

**Comment by debanjancred** [comment]
> > @bkilinc What means _make the setup script executable and run_? How do that?
> 
> chmod 755 setup_12.x
> sudo ./setup_12.x

Thanks, Man. You saved my life.

**Comment by maegi90** [comment]
Thanks!

**Comment by khube007** [comment]
Thanks!

**Comment by monistar** [comment]
Guys thank you, you "saved" my life

**Comment by LeandroSoares89** [comment]
> Acabei de instalar baixando o script com o wget
> `wget https://deb.nodesource.com/setup_12.x`
> aberto e
> `nano setup_12.x`
> adicionando a linha depois que todas as definições do Linux Mint
> `check_alt "Linux Mint" "tina" "Ubuntu" "bionic"`
> tornam o script de instalação executável e executado. finalmente;
> `sudo apt-get install -y nodejs`

salvou mais uma vida

**Comment by Vlad-Shevliakov** [comment]
OMG is this problem still relevant?

**Comment by Hygens** [comment]
@Vlad-Shevliakov
If the issue is solved on mainstream it's not more relevant if not continue each more relevant. 
Observe the number of persons with same problem.

**Comment by Hygens** [comment]
Since not work almost up now:
jose@master-node:~/nifi-release$ curl -sL https://rpm.nodesource.com/setup_12.x | bash -

## Installing the NodeSource Node.js 12.x repo...


## Inspecting system...


## You don't appear to be running an Enterprise Linux based system,
please contact NodeSource at https://github.com/nodesource/distributions/issues
if you think this is incorrect or would like your distribution to be considered
for support.

**Comment by igsu** [comment]
@Hygens Linux Mint 19.2 (Tina) is now supported.
Thanks for pointing this out!

**Comment by squarerobin** [comment]
E: The repository 'https://deb.nodesource.com/node_13.x tina Release' does not have a Release file.
