### ISSUE TITLE
Installing version 10 on Linux Mint 19.2 (tina) final release

### ISSUE THREAD

**Issue by rvleustaquio** [nodesource/distributions#881]
Hi!

On using: `url -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -`

Results in: `## Confirming "tina" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_10.x/dists/tina/Release'

## Your distribution, identified as "tina", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
`

Thanks

**Comment by segadora** [comment]
I am also having this issue

**Comment by abhishek-nigam** [comment]
Until Linux Mint 19.2 (tina) is added to the list of supported distros, I think the only way to install updated version of NodeJS is to do a manual installation as mentioned [here](https://github.com/nodesource/distributions/blob/master/README.md). In step 3, you need to export two environment variables 1. VERSION (to specify which version of NodeJS you want installed) 2. DISTRO (the codename of a supported distro, here you can use bionic (which is codename for Ubuntu 18.04, on which Linux Mint 19.2 is based).

**Comment by wilson-gardner** [comment]
I suggest using Linuxbrew: [https://docs.brew.sh/Homebrew-on-Linux]
I was stuck on this as well and I'm actually surprised I haven't seen more people using this approach as it is easier than manually installing and gives you Node v12.8.x and npm v6.10.x.

**Comment by segadora** [comment]
Just download `https://deb.nodesource.com/setup_10.x` and add tina under tara

```
check_alt "Linux Mint"    "tara"     "Ubuntu" "bionic"
```

Replace with

```
check_alt "Linux Mint"    "tara"     "Ubuntu" "bionic"
check_alt "Linux Mint"    "tina"     "Ubuntu" "bionic"
```

then run `./setup_10.x`

And you are good to go


https://github.com/nodesource/distributions/blob/master/deb/setup_10.x#L221

**Comment by rvleustaquio** [comment]
Thanks for everyone help!

I used the @segadora comments and works like a charm.

Tnks.

**Comment by segadora** [comment]
@rvleustaquio This should be left open untill the issue has been fixed

**Comment by rvleustaquio** [comment]
Ops!

**Comment by nileshjain166** [comment]
I used the @segadora comments and installed node 12.

**Comment by segadora** [comment]
Pull request for this can be found here https://github.com/nodesource/distributions/pull/876

**Comment by sirwilld** [comment]
I tried a segadora solution, but it gives me the following error: The repository 'https://deb.nodesource.com/node_10.x tina Release' does not have a Release file.

**Comment by segadora** [comment]
@sirwilld You might be doing something wrong then. It should type bionic in the url that you have provided.

**Comment by sirwilld** [comment]
After trying and failing, I installed the binary version

**Comment by ViniciosSilva811** [comment]
I also used @segadora comments and installed node 10.16.3

**Comment by derrickmehaffy** [comment]
Confirmed tina issue with node 10 and node 12

**Comment by AbdifatahZamiir** [comment]
how can i download please  @segadora give me more detail i have confused.

**Comment by rvleustaquio** [comment]
> how can i download please @segadora give me more detail i have confused.

Go to the link https://deb.nodesource.com/setup_10.x, save a file in any folder with name setup_10.x. Give permission to execute e run.

After that, runs sudo apt-get install -y nodejs if you are in deb distribuitions.

**Comment by AbdifatahZamiir** [comment]
> > how can i download please @segadora give me more detail i have confused.
> 
> Go to the link https://deb.nodesource.com/setup_10.x, save a file in any folder with name setup_10.x. Give permission to execute e run.
> 
> After that, runs sudo apt-get install -y nodejs if you are in deb distribuitions.

first thanks to your quick reply i saved the file with setup_10.x name so what is the next step what do you mean  Give permission to execute e run.

**Comment by rvleustaquio** [comment]
chmod +x setup_10.x

**Comment by rvleustaquio** [comment]
after

**Comment by AbdifatahZamiir** [comment]
> chmod +x setup_10.x
> sudo ./setup_10.x


Thanks for being there for me when I really needed you. it works like a charm.

**Comment by DurandA** [comment]
> I tried a segadora solution, but it gives me the following error: The repository 'https://deb.nodesource.com/node_10.x tina Release' does not have a Release file.

Same error for me.

**Comment by senorcitizen** [comment]
I also tried segadora's fix, but I'm still getting the error messages:

_E: The repository 'https://deb.nodesource.com/node_10.x tina Release' does not have a Release file._
_N: Updating from such a repository can't be done securely, and is therefore disabled by default._

**Comment by anselm94** [comment]
@sirwilld @DurandA @senorcitizen 

> E: The repository 'https://deb.nodesource.com/node_10.x tina Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.

To fix this issue

- Go to ***Software Sources*** -> ***Additional Repositories***

- Select '**Nodesource /bionic**' -> Click on '**Edit**' -> Paste `deb https://deb.nodesource.com/node_10.x bionic main` -> Click '**OK**'

- Select '**Nodesource (Sources) /bionic**' -> Click on '**Edit**' -> Paste `deb https://deb.nodesource.com/node_10.x bionic main` -> Click '**OK**'

**Comment by d3vil-91** [comment]
what is Software Sources?

**Comment by anselm94** [comment]
@d3vil-91 It's one of the available apps in Linux Mint

**Comment by message** [comment]
`sudo sed -i 's/tina/bionic/g' /etc/apt/sources.list.d/nodesource.list` until support is released

**Comment by frederic-bonjour** [comment]
Thank you very much, @segadora ! :)

**Comment by artavasdes** [comment]
I need some help, I installed the link provided by Segadora for the Node JS 10. I named that file as setup_10.x
I go to the terminal and type ./setup_10.x and I get an error saying "cannot access 'setup_10.x': No such file or directory" even though the file for Node Js installation is right in front of me on the desktop.

**Comment by message** [comment]
@artavasdes 
```
echo -e "deb https://deb.nodesource.com/node_10.x bionic main" | sudo tee /etc/apt/sources.list.d/nodesource.list
echo -e "deb-src https://deb.nodesource.com/node_10.x bionic main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list

sudo apt update
sudo apt install nodejs
```

**Comment by artavasdes** [comment]
@message  I did the four commands you gave me in order and it says that nodejs is already the newest version (8.10.0~dfsg-2ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 264 not upgraded.
I go and try finding NodeJS, but I can't, I guess it didn't install. By the way, the linux mint I have is brand new, I installed it two weeks ago.

**Comment by message** [comment]
@artavasdes what `sudo apt-cache policy nodejs` does say?

**Comment by artavasdes** [comment]
@message When I put that in alone, it says: 
Installed: 8.10.0~dfsg-2ubuntu0.4
  Candidate: 8.10.0~dfsg-2ubuntu0.4
  Version table:
 *** 8.10.0~dfsg-2ubuntu0.4 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     8.10.0~dfsg-2ubuntu0.2 500
        500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
     8.10.0~dfsg-2 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

**Comment by message** [comment]
@artavasdes well, not sure why apt doesn't see new source. Usually you need to add new source file into `/etc/apt/sources.list.d`, `sudo apt update` to rebuild the indexes and `sudo apt install nodejs` to install a new version. You can try maybe [this](https://github.com/nodesource/distributions/issues/881#issuecomment-534654494) option

**Comment by artavasdes** [comment]
@message I really don't know why none of these are working, is there another way to do this?

**Comment by message** [comment]
@artavasdes what does `sudo apt update` say? did you import the key like `curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -`?

**Comment by artavasdes** [comment]
@message sudo apt update just updates it and installs a couple things. For the last command you gave, the terminal just shows a bunch of commands. I also wanted to say that I am a noob with linux and so I don't know if there is something that I am missing that I should download.

**Comment by artavasdes** [comment]
@message I tried a couple things to get it to work and I found how I was an idiot, I did not open up terminal in the location of the setup. My new problem is that it gives me this error when I run the ./setup_10.x in the terminal.
This is the error:
## Installing the NodeSource Node.js 12.x repo...


## Populating apt-get cache...

+ apt-get update
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
Error executing command, exiting
Also, thanks for the help, I really appreciate it.

**Comment by rvleustaquio** [comment]
@artavasdes!

Have you tried with sudo?

sudo ./setup_10.x

**Comment by artavasdes** [comment]
@message I get an error. It loads the package and then gives this:


W: GPG error: https://deb.nodesource.com/node_10.x bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1655A0AB68576280
E: The repository 'https://deb.nodesource.com/node_10.x bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/nodesource.list:1 and /etc/apt/sources.list.d/nodesource.list:2
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/nodesource.list:1 and /etc/apt/sources.list.d/nodesource.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/nodesource.list:1 and /etc/apt/sources.list.d/nodesource.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/nodesource.list:1 and /etc/apt/sources.list.d/nodesource.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/nodesource.list:1 and /etc/apt/sources.list.d/nodesource.list:2
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/nodesource.list:1 and /etc/apt/sources.list.d/nodesource.list:2
W: Target DEP-11 (main/dep11/Components-all.yml) is configured multiple times in /etc/apt/sources.list.d/nodesource.list:1 and /etc/apt/sources.list.d/nodesource.list:2
W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list.d/nodesource.list:1 and /etc/apt/sources.list.d/nodesource.list:2
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list.d/nodesource.list:1 and /etc/apt/sources.list.d/nodesource.list:2
Error executing command, exiting

**Comment by message** [comment]
@artavasdes you see NO_PUBKEY? You need to import a missing signature. So basically:

```
# Add missing signature
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 1655A0AB68576280

# Replace misconfigured  sources file
echo -e "deb https://deb.nodesource.com/node_10.x bionic main" | sudo tee /etc/apt/sources.list.d/nodesource.list
echo -e "deb-src https://deb.nodesource.com/node_10.x bionic main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list

# Update packages and install
sudo apt update
sudo apt install nodejs
```

**Comment by artavasdes** [comment]
@message I ran the commands you gave me in order and then I ran sudo ./setup_10.x. The terminal told me to run this: sudo apt-get install -y nodejs
I ran that also and I got no errors, none of the commands had errors, but I am kind of a noob and I don't know how you would launch node js when it is installed (if it is installed). 
Thanks for the help!

**Comment by message** [comment]
@artavasdes you don't need to run ./setup file. Check if node is installed by typing `nodejs -v` in terminal

**Comment by artavasdes** [comment]
@message I think it is installed: this is what I get v12.13.0
I am noob to linux so how do you open up Node JS?

**Comment by danger89** [comment]
Try: https://node.melroy.org/

**Comment by igsu** [comment]
Duplicated #878 
Linux Mint 19.2 Tina has support now.
