### ISSUE TITLE
Add support for Devuan beowulf release

### ISSUE THREAD

**Issue by MrCsabaToth** [nodesource/distributions#884]
It's compatible with Debian Buster

**Comment by MrCsabaToth** [comment]
Do you need a PR? Basically it's in between `ascii` and `ceres`, I added the following line to the PPA installer shell script:
`check_alt "Devuan"        "beowulf"  "Debian" "buster"`

**Comment by igsu** [comment]
hi @MrCsabaToth 

Devuan Beowulf is now supported, thank you for your patience.

**Comment by MrCsabaToth** [comment]
Kinda off topic, but the community should establish a database where these tuples can be fetched from. An open source project which would build the tuples into various consumable source files - multiple languages. (in this particular case it's kind of a custom script tho, but it could fetch the data from a json? It maybe too complicated).
