### ISSUE TITLE
rhel6 broken

### ISSUE THREAD

**Issue by Ignition** [nodesource/distributions#887]
```
$ curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -

## Installing the NodeSource Node.js 12.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_12.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Downloading release setup RPM...

+ mktemp
+ curl -sL -o '/tmp/tmp.dU4glE0BdZ' 'https://rpm.nodesource.com/pub_12.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Installing release setup RPM...

+ rpm -i --nosignature --force '/tmp/tmp.dU4glE0BdZ'

## Cleaning up...

+ rm -f '/tmp/tmp.dU4glE0BdZ'

## Checking for existing installations...

+ rpm -qa 'node|npm' | grep -v nodesource

## Run `sudo yum install -y nodejs` to install Node.js 12.x and npm.
## You may also need development tools to build native addons:
     sudo yum install gcc-c++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
     sudo yum install yarn
```
```
$ sudo yum install -y nodejs
Loaded plugins: product-id, search-disabled-repos, security
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 2:12.8.1-1nodesource will be installed
--> Processing Dependency: libstdc++.so.6(CXXABI_1.3.5)(64bit) for package: 2:nodejs-12.8.1-1nodesource.x86_64
--> Processing Dependency: libc.so.6(GLIBC_2.17)(64bit) for package: 2:nodejs-12.8.1-1nodesource.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.15)(64bit) for package: 2:nodejs-12.8.1-1nodesource.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.18)(64bit) for package: 2:nodejs-12.8.1-1nodesource.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.14)(64bit) for package: 2:nodejs-12.8.1-1nodesource.x86_64
--> Finished Dependency Resolution
Error: Package: 2:nodejs-12.8.1-1nodesource.x86_64 (nodesource)
           Requires: libc.so.6(GLIBC_2.17)(64bit)
Error: Package: 2:nodejs-12.8.1-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(GLIBCXX_3.4.14)(64bit)
Error: Package: 2:nodejs-12.8.1-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(CXXABI_1.3.5)(64bit)
Error: Package: 2:nodejs-12.8.1-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(GLIBCXX_3.4.18)(64bit)
Error: Package: 2:nodejs-12.8.1-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.10 (Santiago)

$ strings /lib64/libc.so.6 | grep GLIBC
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_PRIVATE

$ strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_FORCE_NEW
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
GLIBC is 2.12 on RHEL6
GLIBCXX is 3.4.13 on RHEL6

**Comment by Ignition** [comment]
`libstdc++` can be statically linked. To my knowledge you can't make a binary on rhel6 use a newer glibc.

**Comment by andreyunugro** [comment]
On Centos 6.10.
<pre>
$ curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -

## Installing the NodeSource Node.js 12.x repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el6-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_12.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Downloading release setup RPM...

+ mktemp
+ curl -sL -o '/tmp/tmp.ZT4upj5CPI' 'https://rpm.nodesource.com/pub_12.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'

## Installing release setup RPM...

+ rpm -i --nosignature --force '/tmp/tmp.ZT4upj5CPI'

## Cleaning up...

+ rm -f '/tmp/tmp.ZT4upj5CPI'

## Checking for existing installations...

+ rpm -qa 'node|npm' | grep -v nodesource

## Run `sudo yum install -y nodejs` to install Node.js 12.x and npm.
## You may also need development tools to build native addons:
     sudo yum install gcc-c++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
     sudo yum install yarn
</pre>

<pre>
$ sudo yum install nodejs
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.unej.ac.id
 * extras: mirror.unej.ac.id
 * updates: mirror.0x.sg
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 2:12.11.1-1nodesource will be installed
--> Processing Dependency: libstdc++.so.6(CXXABI_1.3.5)(64bit) for package: 2:nodejs-12.11.1-1nodesource.x86_64
--> Processing Dependency: libc.so.6(GLIBC_2.17)(64bit) for package: 2:nodejs-12.11.1-1nodesource.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.15)(64bit) for package: 2:nodejs-12.11.1-1nodesource.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.18)(64bit) for package: 2:nodejs-12.11.1-1nodesource.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.14)(64bit) for package: 2:nodejs-12.11.1-1nodesource.x86_64
--> Finished Dependency Resolution
Error: Package: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
Error: Package: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(GLIBCXX_3.4.18)(64bit)
Error: Package: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
           Requires: libc.so.6(GLIBC_2.17)(64bit)
Error: Package: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(GLIBCXX_3.4.14)(64bit)
Error: Package: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
           Requires: libstdc++.so.6(CXXABI_1.3.5)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
</pre>

<pre>
$ cat /etc/redhat-release 
CentOS release 6.10 (Final)
</pre>

**Comment by akoripelly** [comment]
> On Centos 6.10.
> 
> $ curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
> 
> ## Installing the NodeSource Node.js 12.x repo...
> 
> 
> ## Inspecting system...
> 
> + rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
> + uname -m
> 
> ## Confirming "el6-x86_64" is supported...
> 
> + curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_12.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'
> 
> ## Downloading release setup RPM...
> 
> + mktemp
> + curl -sL -o '/tmp/tmp.ZT4upj5CPI' 'https://rpm.nodesource.com/pub_12.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'
> 
> ## Installing release setup RPM...
> 
> + rpm -i --nosignature --force '/tmp/tmp.ZT4upj5CPI'
> 
> ## Cleaning up...
> 
> + rm -f '/tmp/tmp.ZT4upj5CPI'
> 
> ## Checking for existing installations...
> 
> + rpm -qa 'node|npm' | grep -v nodesource
> 
> ## Run `sudo yum install -y nodejs` to install Node.js 12.x and npm.
> ## You may also need development tools to build native addons:
>      sudo yum install gcc-c++ make
> ## To install the Yarn package manager, run:
>      curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
>      sudo yum install yarn
> $ sudo yum install nodejs
> Loaded plugins: fastestmirror
> Setting up Install Process
> Loading mirror speeds from cached hostfile
>  * base: mirror.unej.ac.id
>  * extras: mirror.unej.ac.id
>  * updates: mirror.0x.sg
> Resolving Dependencies
> --> Running transaction check
> ---> Package nodejs.x86_64 2:12.11.1-1nodesource will be installed
> --> Processing Dependency: libstdc++.so.6(CXXABI_1.3.5)(64bit) for package: 2:nodejs-12.11.1-1nodesource.x86_64
> --> Processing Dependency: libc.so.6(GLIBC_2.17)(64bit) for package: 2:nodejs-12.11.1-1nodesource.x86_64
> --> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.15)(64bit) for package: 2:nodejs-12.11.1-1nodesource.x86_64
> --> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.18)(64bit) for package: 2:nodejs-12.11.1-1nodesource.x86_64
> --> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.14)(64bit) for package: 2:nodejs-12.11.1-1nodesource.x86_64
> --> Finished Dependency Resolution
> Error: Package: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
>            Requires: libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
> Error: Package: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
>            Requires: libstdc++.so.6(GLIBCXX_3.4.18)(64bit)
> Error: Package: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
>            Requires: libc.so.6(GLIBC_2.17)(64bit)
> Error: Package: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
>            Requires: libstdc++.so.6(GLIBCXX_3.4.14)(64bit)
> Error: Package: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
>            Requires: libstdc++.so.6(CXXABI_1.3.5)(64bit)
>  You could try using --skip-broken to work around the problem
>  You could try running: rpm -Va --nofiles --nodigest
> $ cat /etc/redhat-release 
> CentOS release 6.10 (Final)
> $ uname -a
> Linux centos6 2.6.32-754.23.1.el6.x86_64 #1 SMP Thu Sep 26 12:05:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux





Facing same issue for same CentOS release 6.10 (Final). Someone please help to install Node in centOS 6. 
Thanks

**Comment by BatchuSanthi** [comment]
> On Centos 6.10.
> 
> $ curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
> 
> ## Installing the NodeSource Node.js 12.x repo...
> 
> 
> ## Inspecting system...
> 
> + rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
> + uname -m
> 
> ## Confirming "el6-x86_64" is supported...
> 
> + curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_12.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'
> 
> ## Downloading release setup RPM...
> 
> + mktemp
> + curl -sL -o '/tmp/tmp.ZT4upj5CPI' 'https://rpm.nodesource.com/pub_12.x/el/6/x86_64/nodesource-release-el6-1.noarch.rpm'
> 
> ## Installing release setup RPM...
> 
> + rpm -i --nosignature --force '/tmp/tmp.ZT4upj5CPI'
> 
> ## Cleaning up...
> 
> + rm -f '/tmp/tmp.ZT4upj5CPI'
> 
> ## Checking for existing installations...
> 
> + rpm -qa 'node|npm' | grep -v nodesource
> 
> ## Run `sudo yum install -y nodejs` to install Node.js 12.x and npm.
> ## You may also need development tools to build native addons:
>      sudo yum install gcc-c++ make
> ## To install the Yarn package manager, run:
>      curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
>      sudo yum install yarn
> $ sudo yum install nodejs
> Loaded plugins: fastestmirror
> Setting up Install Process
> Loading mirror speeds from cached hostfile
>  * base: mirror.unej.ac.id
>  * extras: mirror.unej.ac.id
>  * updates: mirror.0x.sg
> Resolving Dependencies
> --> Running transaction check
> ---> Package nodejs.x86_64 2:12.11.1-1nodesource will be installed
> --> Processing Dependency: libstdc++.so.6(CXXABI_1.3.5)(64bit) for package: 2:nodejs-12.11.1-1nodesource.x86_64
> --> Processing Dependency: libc.so.6(GLIBC_2.17)(64bit) for package: 2:nodejs-12.11.1-1nodesource.x86_64
> --> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.15)(64bit) for package: 2:nodejs-12.11.1-1nodesource.x86_64
> --> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.18)(64bit) for package: 2:nodejs-12.11.1-1nodesource.x86_64
> --> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.14)(64bit) for package: 2:nodejs-12.11.1-1nodesource.x86_64
> --> Finished Dependency Resolution
> Error: Package: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
>            Requires: libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
> Error: Package: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
>            Requires: libstdc++.so.6(GLIBCXX_3.4.18)(64bit)
> Error: Package: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
>            Requires: libc.so.6(GLIBC_2.17)(64bit)
> Error: Package: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
>            Requires: libstdc++.so.6(GLIBCXX_3.4.14)(64bit)
> Error: Package: 2:nodejs-12.11.1-1nodesource.x86_64 (nodesource)
>            Requires: libstdc++.so.6(CXXABI_1.3.5)(64bit)
>  You could try using --skip-broken to work around the problem
>  You could try running: rpm -Va --nofiles --nodigest
> $ cat /etc/redhat-release 
> CentOS release 6.10 (Final)
> $ uname -a
> Linux centos6 2.6.32-754.23.1.el6.x86_64 #1 SMP Thu Sep 26 12:05:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux



Facing same issue, for the same CentOS version. Can someone please help to install Node in CentOS.
Thank you very much.

**Comment by igsu** [comment]
[Node.js 12 support](https://github.com/nodesource/distributions#enterprise-linux-based-distributions) for RHEL starts from version 7, we stopped creating Node.js 12 packages for RHEL because it requires dependencies that are not possible to install or resolve in RHEL 6 to support Node.js 12. There are a few issues created in Node.js repositories:

https://github.com/nodejs/build/issues/1995
https://github.com/nodejs/node/blob/v12.x/BUILDING.md#supported-platforms
