### ISSUE TITLE
You don't appear to be running an Enterprise Linux based system

### ISSUE THREAD

**Issue by ogulcandegdas** [nodesource/distributions#888]
edit: I installed with nvm -> https://linuxize.com/post/how-to-install-node-js-on-ubuntu-18.04/

hi, I get an error npm while installing :

curl -sL https://rpm.nodesource.com/setup_8.x | sudo -E bash -

$ 887 Installing the NodeSource Node.js 8.x LTS Carbon repo...
$ Inspecting system...
$ You don't appear to be running an Enterprise Linux based system,
please contact NodeSource at https://github.com/nodesource/distributions/issues
if you think this is incorrect or would like your distribution to be considered
for support.

what is  issue?
my os system: deepin/debian

**Comment by Ignition** [comment]
https://github.com/nodesource/distributions#installation-instructions

**Comment by yeninesil** [comment]
yes, problem it is should be. My bad, thank you very much.

**Comment by mattlundberg1980** [comment]
> 
> 
> You are trying to use rpm based installations, you should be using deb based installation
> https://github.com/nodesource/distributions#installation-instructions

Hi 

I am following the installation-instructions however when i run the:

# Using Debian, as root
curl -sL https://deb.nodesource.com/setup_13.x | bash -
apt-get install -y nodejs

i get the following back:

"/usr/bin/apt-get: cannot execute binary file"

do you know what i have missed or what i am doing wrong?

Kind regards
Matt

**Comment by Ignition** [comment]
Something is up with your Linux enviroment. `apt-get` should have the execute bit set like so:
```
$ ls -la `which apt-get`
-rwxr-xr-x 1 root root 43168 Sep  3 12:05 /usr/bin/apt-get
```

**Comment by mattlundberg1980** [comment]
> 
> 
> Something is up with your Linux enviroment. `apt-get` should have the execute bit set like so:
> 
> ```
> $ ls -la `which apt-get`
> -rwxr-xr-x 1 root root 43168 Sep  3 12:05 /usr/bin/apt-get
> ```

This is my output:
![image](https://user-images.githubusercontent.com/55487604/71662688-4237bb80-2d4a-11ea-92e1-133dd4e94171.png)

looks the same.

**Comment by sircollins** [comment]
Had the same issue. i did the following first then install node

curl --silent  --location https://deb.nodesource.com/setup_10.x \|sudo bash -

Then

sudo apt-get install -y nodejs
--
