### ISSUE TITLE
How do I install node.js on Ubuntu 18.04 32 bit?

### ISSUE THREAD

**Issue by JonDevOps** [nodesource/distributions#890]
Instructions or knowledge as to weather or not it's possible would be great. Thanks in advance.

**Comment by Vlad-Shevliakov** [comment]
@JonDevOps   Mint 19.2 tina, has same problem!

**Comment by igsu** [comment]
Hi @JonDevOps, as mentioned in the documentation [here](https://github.com/nodesource/distributions#debian-and-ubuntu-based-distributions), there's no support available for **Node.js 10 and later** in the case of i386 (32-bit)

However, you should be able to install [Node 8 packages](https://deb.nodesource.com/node_8.x/dists/bionic/main/binary-i386/Packages), please take a look here at the steps in the docs!

------------------------------------------------------------

@Vlad-Shevliakov Mint 19.2 Tina is now supported!

**Comment by sebma** [comment]
> However, you should be able to install [Node 8 packages](https://deb.nodesource.com/node_8.x/dists/bionic/main/binary-i386/Packages), please take a look at the steps in the docs!
> 
> @Vlad-Shevliakov Mint 19.2 Tina is now supported!

@Vlad-Shevliakov Hi, that doc would be here, right : https://github.com/nodesource/distributions#manual-installation ?
