### ISSUE TITLE
xenial is not currently supported

### ISSUE THREAD

**Issue by ghostofdeath** [nodesource/distributions#892]
Hellow.

## Confirming "xenial" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_10.x/dists/xenial/Release'

**Comment by mathieujobin** [comment]
you are kidding right?

what are all of these unsupported linux system?

this is a joke.

**Comment by wolfy1339** [comment]
No longer an issue. It's been fixed

**Comment by igsu** [comment]
Fixed a while ago, closing this now.
