### ISSUE TITLE
Your distribution, identified as "tina", is not currently supported

### ISSUE THREAD

**Issue by nareshmahato** [nodesource/distributions#895]
Linux Mint 19.2 Tina

Confirming "tina" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_12.x/dists/tina/Release'

## Your distribution, identified as "tina", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by danger89** [comment]
;( Indeed!

**Comment by danger89** [comment]
https://github.com/nodesource/distributions/issues/881#issuecomment-520308043

**Comment by danger89** [comment]
Try: https://node.melroy.org/

**Comment by igsu** [comment]
Duplicated #878 
Linux Mint 19.2 Tina has support now.
