### ISSUE TITLE
Your distribution, identified as "tina", is not currently supported

### ISSUE THREAD

**Issue by ananda394** [nodesource/distributions#899]
Your distribution, identified as "tina", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by message** [comment]
`sudo sed -i 's/tina/bionic/g' /etc/apt/sources.list.d/nodesource.list` until support is released

**Comment by jedial23** [comment]
Hi, I used manually: `deb https://deb.nodesource.com/node_12.x bionic main` `deb-src https://deb.nodesource.com/node_12.x bionic main` and work for me. `nodejs -v : v12.13.0`

**Comment by igsu** [comment]
Duplicated #878 
Linux Mint 19.2 Tina has support now.
