### ISSUE TITLE
issue- 'buster'

### ISSUE THREAD

**Issue by Retr0Hax894** [nodesource/distributions#901]
when installing node js from this command: curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash - 
its said ' your distribution, identified as 'buster' is currently not supported

**Comment by robbie-mac** [comment]
Are you intentionally trying to install the 5.x version series? It has been EOL, and is no longer supported

**Comment by igsu** [comment]
Hi @Retr0Hax894, as mentioned by @robbie-mac Node 5 went EOL and is no longer supported. On the other hand, you should not have problems installing the other versions in Debian buster since it is currently supported. Let me know if you have any other issue.

Closing this now.
