### ISSUE TITLE
Your distribution, identified as "tina", is not currently supported

### ISSUE THREAD

**Issue by favafelipe** [nodesource/distributions#902]
Please add tina to the list of supported distributions, to get easier to install it.
I opened this report just to ask you guys to add officially it to the list, it's working fine, just add it and turn the process less complicated to us.
The Mint community will really appreciate this action.

**Comment by jalmansa88** [comment]
Same issue here.

**Comment by juanodecc** [comment]
same issue
## Your distribution, identified as "tina", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by AndriyMeleshko** [comment]
## Your distribution, identified as "tina", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by eirikhanssen** [comment]
Same comment here. Tina is using the same ubuntu base as Tessa in Linux mint, so it's really just to add tina to this list.

**Comment by rvleustaquio** [comment]
Look at #881

**Comment by Avanish-git** [comment]
> Same comment here. Tina is using the same ubuntu base as Tessa in Linux mint, so it's really just to add tina to this list.

ye ab tina ko kya dikkat hai bhai

**Comment by message** [comment]
`sudo sed -i 's/tina/bionic/g' /etc/apt/sources.list.d/nodesource.list` until support is released

**Comment by favafelipe** [comment]
@message I'll try this later, but does it work fine??

**Comment by message** [comment]
Yes. Your `/etc/apt/sources.list.d/nodesource.list` should look like this after an edit. 
```
deb https://deb.nodesource.com/node_12.x bionic main
deb-src https://deb.nodesource.com/node_12.x bionic main
```
Then just `sudo apt update && sudo apt install nodejs`

**Comment by LouieB** [comment]
@message 

> sudo sed -i 's/tina/bionic/g' /etc/apt/sources.list.d/nodesource.list

gives me this:

sed: can't read /etc/apt/sources.list.d/nodesource.list: No such file or directory

**Comment by favafelipe** [comment]
@message as @LouieB reported, the nodesource.list is not present in the system because as 'tina' is not supported officially , the archive is not created when we try to install node because we can not install it.
There are some ways to install node on tina, but this ways are not official and require some knowledge to be correctly done.
As I said, I created this issue just to ask if please the node team could add tina to the list of supported distributions and make it much more easy to us to install it, because node is working fine, as long as I know, in this version of Mint.

**Comment by message** [comment]
@favafelipe it's already added in #876. Just waiting for a merge. 

@LouieB 
```
echo -e "deb https://deb.nodesource.com/node_12.x bionic main" | sudo tee /etc/apt/sources.list.d/nodesource.list
echo -e "deb-src https://deb.nodesource.com/node_12.x bionic main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list

sudo apt update
sudo apt install nodejs
```
