### ISSUE TITLE
CentOS 7.7 Support

### ISSUE THREAD

**Issue by Yrek** [nodesource/distributions#906]
Hi,

When I trie to add the nodesource repo with the file on https://rpm.nodesource.com/setup_12.x I get following error:

Your distribution, identified as "centos-release-7-7.1908.0.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Do you have an idea how I can install nodejs on CentOS 7.7?

Thanks alot in advance!

**Comment by j07hnZyH** [comment]
Hi,

I have the same issue, with the same CentOS version and node10 and node12

Thanks

**Comment by Yrek** [comment]
My workaround was to manually install it with the rpm:s on https://rpm.nodesource.com/pub_12.x/el/7/x86_64/

**Comment by igsu** [comment]
Duplicated #943
