### ISSUE TITLE
Your distribution, identified as "tina", is not currently supported

### ISSUE THREAD

**Issue by hriteek** [nodesource/distributions#907]
I am getting this issue when trying to install node in my new system

**Comment by rojeras** [comment]
I also just hit this issue. I would appreciate if you can add tina, representing Linux Mint 19.2.

**Comment by message** [comment]
`sudo sed -i 's/tina/bionic/g' /etc/apt/sources.list.d/nodesource.list` until support is released

**Comment by Koli14** [comment]
> `sudo sed -i 's/tina/bionic/g' /etc/apt/sources.list.d/nodesource.list` until support is released

I do not have  a `nodesource.list` file. Can you pls copy it's full content?

**Comment by Koli14** [comment]
Got the solution, the `/etc/apt/sources.list.d/nodesource.list` file should look like:
`deb https://deb.nodesource.com/node_10.x bionic main
deb-src https://deb.nodesource.com/node_10.x bionic main
`

**Comment by johndcarmichael** [comment]
I got the same issue just now.

manually added the nodesource.list but also had to manually inject the key:
```
curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
```

**Comment by landercosta** [comment]
> `sudo sed -i 's/tina/bionic/g' /etc/apt/sources.list.d/nodesource.list` until support is released

It worked for me. Thanks @Koli14

**Comment by danger89** [comment]
Try: https://node.melroy.org/

**Comment by igsu** [comment]
Duplicated #878 
Linux Mint 19.2 Tina has support now.
