### ISSUE TITLE
ubuntu installation installs python2 

### ISSUE THREAD

**Issue by jrwren** [nodesource/distributions#909]
python 2 is soon to be obsolete

It would be nice if the nodejs package did not depend on the python 2 package.

I'm somewhat familiar with deb packaging. If someone can point me to where the python is necessary I can investigate migrating it to python3.

**Comment by mtibben** [comment]
See https://github.com/nodejs/node/issues/25789

**Comment by jrwren** [comment]
Oh, thank you.
