### ISSUE TITLE
Nodejs 12.x debian repository

### ISSUE THREAD

**Issue by cyrusel** [nodesource/distributions#911]
The latest version of Nodejs 12.xx debian package on deb.nodesource.com is 12.10 while 12.11 was released last week. Is there any technical reason for this delay?
https://deb.nodesource.com/node_12.x/dists/buster/main/binary-amd64/

**Comment by robbie-mac** [comment]
Nodejs 12.11.1 has been released to fix a regression. They may have noticed the issue with 12.11 and been waiting for the patch before creating the package.

**Comment by jaromanda** [comment]
Since the issue with 12.11.0 was _a regression that prevented from building Node.js using the official source tarball_ you can understand why 12.11.0 was not "built" 😃

**Comment by cyrusel** [comment]
You're right, thanks.

**Comment by hasimo** [comment]
How about 12.11.1 ? I can find it in the repository. 
https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/
When it will be available ?

**Comment by ErisDS** [comment]
> Since the issue with 12.11.0 was a regression that prevented from building Node.js using the official source tarball you can understand why 12.11.0 was not "built" 😃

Is this still a bug? 12.12 and 12.13 don't seem to have been build either.

**Comment by jaromanda** [comment]
> Is this still a bug? 12.12 and 12.13 don't seem to have been built either.

12.13 is definitely built ... now that 12.x is the LTS line, wonder when 13.x will appear

**Comment by robbie-mac** [comment]
Its been less than 24 hours since its release.

Given the recent staff changes at Nodesource I would suggest a little patience. Updates may not come as fast as they used to.

**Comment by jaromanda** [comment]
13 is up now :D
