### ISSUE TITLE
10.x EL nodesource-release signed with wrong key?

### ISSUE THREAD

**Issue by andrew-niaid** [nodesource/distributions#914]
The EL6 and EL7 nodesource-release rpms appear are not signed with the key included in the package. The origin of the signature is not clear as I can't find the public key file for the key id, 2f59b5f99b1be0b4, anywhere. It appears that it has been accidentally used to erroneously sign packages in the past (https://github.com/nodesource/distributions/issues/587#issuecomment-355390999)
```
$ rpm -qpi https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm 2>/dev/null| grep Sig
Signature   : RSA/SHA256, Tue 24 Apr 2018 01:46:23 PM MDT, Key ID 2f59b5f99b1be0b4
$ gpg --with-fingerprint /etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
pub  4096R/34FA74DD 2014-08-30 NodeSource <gpg-rpm@nodesource.com>
      Key fingerprint = 2E55 207A 95D9 944B 0CC9  3261 5DDB E8D4 34FA 74DD
```

**Comment by igsu** [comment]
This should be fixed now @andrew-niaid, can you confirm?
