### ISSUE TITLE
Node v12 not up to date for bionic

### ISSUE THREAD

**Issue by ErisDS** [nodesource/distributions#916]
I tried to install Node v8, v10 and v12 to do some testing - the sources for node v8 and v10 are both giving me the most recent version, but it seems the latest version of Node.js v12 available is 12.10.0, meaning 12.11.0 and 12.11.1 are missing. 

Am I missing something?

`sudo apt-get update`

> Hit:3 https://deb.nodesource.com/node_12.x bionic InRelease

`sudo apt-cache policy nodejs`

```
nodejs:
  Installed: 12.10.0-1nodesource1
  Candidate: 12.10.0-1nodesource1
  Version table:
 *** 12.10.0-1nodesource1 500
        500 https://deb.nodesource.com/node_12.x bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     8.10.0~dfsg-2ubuntu0.4 500
        500 http://mirrors.digitalocean.com/ubuntu bionic-updates/universe amd64 Packages
     8.10.0~dfsg-2ubuntu0.2 500
        500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
     8.10.0~dfsg-2 500
        500 http://mirrors.digitalocean.com/ubuntu bionic/universe amd64 Packages
```

**Comment by cyrusel** [comment]
https://github.com/nodesource/distributions/issues/911

**Comment by cyrusel** [comment]
It's updated to 12.11.1 today:
https://deb.nodesource.com/node_12.x/dists/bionic/main/

**Comment by ErisDS** [comment]
It's behind again, 12.12 was released 10 days ago. 

12.13 was released today and is the official LTS. Please can we get this onto nodesource ASAP?

**Comment by cyrusel** [comment]
https://github.com/nodesource/distributions/issues/925#issuecomment-545122466

**Comment by igsu** [comment]
Node v12.13.1 and Node 13.3.0 available, they are up to date!

Closing this now.
