### ISSUE TITLE
Please also provide manual instructions for EL

### ISSUE THREAD

**Issue by mvz** [nodesource/distributions#917]
There's a manual section for Debian-based distros, but not for EL-based ones. Please consider adding one.

**Comment by igsu** [comment]
You are right @mvz, we will consider this in the future. Also if you are interested, I encourage you to collaborate with the required instructions, which will be reviewed and if they look good they can be published in the docs.

**Comment by mvz** [comment]
Well, even though I prefer to know what's going on, I ended up doing the `curl | sudo` thing, so I have no clue what the manual steps would be. Someone with more knowledge will have to write those.
