### ISSUE TITLE
Please add support for Linux Mint 19.2 (Tina)

### ISSUE THREAD

**Issue by lfcapucho** [nodesource/distributions#919]
Please add support for Linux Mint 19.2 distribution

**Comment by mathielo** [comment]
Apparently being worked on #876

**Comment by danger89** [comment]
yea plz

**Comment by muhagad** [comment]
yes plz me too need it

**Comment by danger89** [comment]
OK, I solved it myself, visit: https://node.melroy.org/

**Comment by muhagad** [comment]
Thanks so much ..it works 😊

**Comment by benemohamed** [comment]
@danger89 Thank you

**Comment by noobunity** [comment]
+1

**Comment by eskizolibereco** [comment]
> OK, I solved it myself, visit: https://node.melroy.org/

Thanks danger89 !! =)

**Comment by glindberg** [comment]
Thank you @danger89! Would you mind explaining what you did?

**Comment by danger89** [comment]
@glindberg I merged all important PRs on this repo into my fork, including the support of Linux Mint 19.2. And Host it at node.melroy.org 

https://github.com/danger89/distributions/blob/master/deb/src/_setup.sh#L223

**Comment by thetomcoffee** [comment]
@danger89 Thank you very much! So glad I can finally run the version of Node I need to. Thank you, thank you.

**Comment by igsu** [comment]
Duplicated #878 
Linux Mint 19.2 Tina has support now.
