### ISSUE TITLE
Ubuntu 15.04 armhf packages missing

### ISSUE THREAD

**Issue by bigcat** [nodesource/distributions#92]
I'm working with Ubuntu Mate 15.04 on a raspberry pi 2, and can't get the repository for node 0.12 or iojs 1.x to update via apt.

Upon investigation it looks like the package files for Vivid are 0 byte, and I'm thinking this might be the issue.

For example, see: https://deb.nodesource.com/iojs_1.x/dists/vivid/main/binary-armhf/Packages

**Comment by chrislea** [comment]
Yup, we're building the armhf ones (take forever because of emulation). I'll update here when they are done.

**Comment by chrislea** [comment]
Also, iojs 1.x builds on ARM for Vivid didn't happen because iojs 2.x was the stable release at the time Vivid came out. The ARM builds for 2.x for Vivid are in the repo.

**Comment by bigcat** [comment]
Thanks! You guys are awesome!

**Comment by chrislea** [comment]
No problem. The node 0.12.3 ARM builds for Vivid should be in there now.
