### ISSUE TITLE
Node 10 not updated in snap 10/stable channel

### ISSUE THREAD

**Issue by pachulo** [nodesource/distributions#921]
Hi! The version in snap channel 10/stable is stuck in 10.16.1, but there were two more releases: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.16.3

Thanks!

**Comment by cyrusel** [comment]
https://github.com/nodesource/distributions/issues/925#issuecomment-545122466

**Comment by pachulo** [comment]
https://github.com/nodesource/distributions/issues/925#issuecomment-545193790

**Comment by pachulo** [comment]
As today, the snap channel 10/stable is not updated:
`10/stable:    10.16.1                        2019-07-31 (2485) 19MB classic`

**Comment by pachulo** [comment]
`10.19.0` is the latest available version and it contains security fixes: could you at least close the `10/*` channels if they are not going be updated?

**Comment by pachulo** [comment]
@igsu do you have any information on this?

**Comment by pachulo** [comment]
Well, this is now updated. Thanks a lot!
```
$ snap info node
name:      node
summary:   Node.js
publisher: NodeSource, Inc. (nodesource✓)
store-url: https://snapcraft.io/node
contact:   https://github.com/nodesource/distributions
license:   MIT
description: |
  A JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven,
  non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm,
  is the largest ecosystem of open source libraries in the world. https://nodejs.org/
snap-id: MEd4V4HHFkCXBSz6UzVmKF2D2PmWcVwR
channels:

...

  10/stable:        10.20.1                        2020-04-23 (2638) 20MB classic
  10/candidate:     ↑                                                     
  10/beta:          ↑                                                     
  10/edge:          ↑                                                     

```
