### ISSUE TITLE
Node v12 not up to date for Centos7 ?

### ISSUE THREAD

**Issue by christalk** [nodesource/distributions#922]
Node v12 not up to date for Centos7 .

CentOS Linux release 7.7.1908 (Core)
Noje.js 10.16.3 is intalled,

But , Node.js 12.12.0  gives -> **Package nodejs-10.16.3-1 nodesource.x86_64 is already installed in its latest version.**                                                                          
Nothing to do.

What I did :
% curl -RLO https://rpm.nodesource.com/setup_12.x
% chmod 755 setup_12.x
% sudo ./setup_12.x -x
...
## Inspecting system...
+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release |                                                                                      | rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m
## Confirming "el7-x86_64" is supported...
+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_12.x/el/7/x86_64/nodeso                                                                                      urce-release-el7-1.noarch.rpm'
## Downloading release setup RPM...
+ mktemp
+ curl -sL -o '/tmp/tmp.kTsY4bzAkX' 'https://rpm.nodesource.com/pub_12.x/el/7/x8                                                                                      6_64/nodesource-release-el7-1.noarch.rpm'
## Installing release setup RPM...
+ rpm -i --nosignature --force '/tmp/tmp.kTsY4bzAkX'
## Cleaning up...
+ rm -f '/tmp/tmp.kTsY4bzAkX'

## Checking for existing installations...
+ rpm -qa 'node|npm' | grep -v nodesource
## You may also need development tools to build native addons:
     sudo yum install gcc-c++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/y                                                                                      arn.repo
     sudo yum install yarn
  = = = = =  = =
 = = =  =
%  sudo yum install -y nodejs
* base: centos.crazyfrogs.org
 * extras: centos.mirror.fr.planethoster.net
 * updates: centos.crazyfrogs.org
**Package nodejs-10.16.3-1 nodesource.x86_64 is already installed in its latest version.**                                                                          
Nothing to do.

Any idea ?

**Comment by JungMinu** [comment]
Could you please try the following commands?
```
curl -L https://git.io/n-install | bash
n 12.12.0
```
Please let us know if this works for you.

**Comment by christalk** [comment]
Thank you for answering.
Actually, it worked after a couple of days, with "sudo yum update" 
but I had not read your message yet. Thanks for that.
The version is now v12.13.0.

Regards,

**Comment by JungMinu** [comment]
Closing the issue since this has been resolved
