### ISSUE TITLE
PopOS not supported

### ISSUE THREAD

**Issue by xNarkon** [nodesource/distributions#924]
Hello,

PopOS 19.10 is not supported, but should be because it's Ubuntu 19.10 just with some additional stuff and drivers. 

Please consider adding it ;-)

**Comment by igsu** [comment]
Hey @xNarkon,

We, unfortunately, do not have the resources necessary to support and test the plethora of Linux releases in the wild, so we rely on community members such as yourself to get support on your favorite distributions.

I've added PopOS to the list of requested releases in our `README.md`.

**Comment by mjcurc** [comment]
Hey @igsu @xNarkon,

Running Pop OS 19.10 here, just follow the instructions to manual instructions for Ubuntu/Debian. Works like a dream.

**Comment by KMatuszak** [comment]
Ubuntu instructions work fine for me on 20.04

![Screenshot from 2020-05-15 17-09-29](https://user-images.githubusercontent.com/53585406/82065886-f705c000-96ce-11ea-958f-9be1f3552f6e.png)

**Comment by VladPutinEu** [comment]
Since PopOS is based on Ubuntu and seems to work fine with the Ubuntu version, I would suggest following the instructions for Ubuntu.
