### ISSUE TITLE
Support Node.js v13

### ISSUE THREAD

**Issue by nikeee** [nodesource/distributions#925]
Node.js v13.0.0 [released today](https://nodejs.org/en/blog/release/v13.0.0/).

**Comment by pedrofurtado** [comment]
https://deb.nodesource.com/setup_12.x is available, but https://deb.nodesource.com/setup_13.x not 👍

**Comment by cyrusel** [comment]
Is nodesource dead? It seems it's been abandoned. There are couple of issues posted recently about new node releases that are not available on nodesource and nobody cares.

**Comment by haggholm** [comment]
> Is nodesource dead? It seems it's been abandoned. There are couple of issues posted recently about new node releases that are not available on nodesource and nobody cares.

I lack any insider knowledge, but there have been some speculations. There were a number of tweets in September from NodeSource employees leaving/looking for new jobs, and not much activity since. Cf. replies/discussion: https://twitter.com/jasnell/status/1170579262690271232?lang=en

**Comment by edsadr** [comment]
We are still supporting our distributions channel, Newest versions were pushed are ready to be installed now for Dubnium and Erbium, we expect to regain the usual speed.

Stay tunned we will start supporting 13 soon

**Comment by pedrofurtado** [comment]
@edsadr Please, add nodejs 13.x support for CentOS 8 :+1: The nodejs 12.x also does not have support for centOS 8 :beers:

**Comment by edsadr** [comment]
ok, now nodejs 13.x is supported, closing this issue, and thanks to everybody for being patient.

closing this issue now

**Comment by pedrofurtado** [comment]
@edsadr In CentOS 8, the script https://rpm.nodesource.com/setup_13.x is installing the nodejs 10.16 :confused:
