### ISSUE TITLE
Node LTS/12 (12.13.0)

### ISSUE THREAD

**Issue by haggholm** [nodesource/distributions#926]
Currently, the latest releases available seem to be 12.11.x. However, the official LTS release starts with 12.13.0. Moreover, this has some important changes, e.g. the `--enable-source-maps` option was added in 12.12.0.

**Comment by cyrusel** [comment]
https://github.com/nodesource/distributions/issues/925#issuecomment-545122466

**Comment by edsadr** [comment]
Latest LTS is now available, sorry for the delay.

Closing this issue now
