### ISSUE TITLE
Symlink location on Debian compatible systems

### ISSUE THREAD

**Issue by szepeviktor** [nodesource/distributions#93]
After couple of years of usage I've realized that nodejs installed from deb.nodesource.com put global (`npm -g install lessc`) symlinks in `/usr/bin` however that is a Debian package directory.
Please consider putting those symlinks in `/usr/local/bin` - as python `pip` does. Thank you!
```bash
which lessc
/usr/bin/lessc
```

**Comment by rvagg** [comment]
you'll have to `npm config set prefix=/usr/local/` if you want to change the default, we install npm with default settings for being installed to `/` and this is its behaviour

**Comment by szepeviktor** [comment]
Thank you very much.
It could be added to the README.Debian.

**Comment by szepeviktor** [comment]
Could you help me find the Debian packages source? (e.g. README.Debian)

**Comment by szepeviktor** [comment]
@chrislea Please reconsider going the Debian way and using `/user/local/` to store npm packages thus non-deb files.
Thank you.
