### ISSUE TITLE
Suppor necesary for linuxMint Tina 19.2

### ISSUE THREAD

**Issue by iprodevstudio** [nodesource/distributions#931]
Please, need support to install nodejs 12

**Comment by SergioGlorias** [comment]
the script has not been updated yet
but you can do manual installation
since mint is ubuntu lts
https://github.com/nodesource/distributions#manual-installation

**Comment by ijash** [comment]
you can use the ubuntu repo since linux mint tina is based on ubuntu 18.04 
```bash
VERSION=node_12.x
DISTRO=bionic
echo "deb https://deb.nodesource.com/$VERSION $DISTRO main" | sudo tee /etc/apt/sources.list.d/nodesource.list
echo "deb-src https://deb.nodesource.com/$VERSION $DISTRO main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list
```

**Comment by comdotlinux** [comment]
This was tested for Node 12.x on Tina :) : https://github.com/nodesource/distributions/pull/939

**Comment by danger89** [comment]
Try: https://node.melroy.org/

**Comment by gsgonzalez88** [comment]
> you can use the ubuntu repo since linux mint tina is based on ubuntu 18.04
> 
> ```shell
> VERSION=node_12.x
> DISTRO=bionic
> echo "deb https://deb.nodesource.com/$VERSION $DISTRO main" | sudo tee /etc/apt/sources.list.d/nodesource.list
> echo "deb-src https://deb.nodesource.com/$VERSION $DISTRO main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list
> ```

it works!

**Comment by igsu** [comment]
Duplicated #878 
Linux Mint 19.2 Tina has support now.
