### ISSUE TITLE
Your distribution, identified as "drishti", is not currently supported,

### ISSUE THREAD

**Issue by sathish53787** [nodesource/distributions#935]
i am newly installed node package in my new system but not installed node in my system.this error occured in my system - Your distribution, identified as "drishti", is not currently supported,

**Comment by danger89** [comment]
I would like to try to help you. But which Debian version is BOSS Drishti based on?

What does `lsb_release -a` gives?

Or try `cat /etc/issue` otherwise.

**Comment by igsu** [comment]
Hi @sathish53787,

BOSS Drishti is now supported, closing this now.
