### ISSUE TITLE
Debian stretch is not supported

### ISSUE THREAD

**Issue by yurikoles** [nodesource/distributions#94]
I suggest to add stretch or simply testing

**Comment by matiux** [comment]
+1
I have the same problem

**Comment by matiux** [comment]
@yurikoles How did you solved it?

**Comment by rvagg** [comment]
We're probably not going to add stretch until it's officially released. In the mean time just add it as jessie and you may be OK:

```
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
echo 'deb https://deb.nodesource.com/node_0.10 jessie main' > /etc/apt/sources.list.d/nodesource.list
echo 'deb-src https://deb.nodesource.com/node_0.10 jessie main' >> /etc/apt/sources.list.d/nodesource.list
```

Change `node_0.10` to `node_0.10`, `iojs_1.x` or `iojs_2.x`

**Comment by matiux** [comment]
Perhaps you meant "Change node_0.10 to node_0.12" ?

**Comment by rvagg** [comment]
yeah, that too, will edit my comment

**Comment by matiux** [comment]
Ok, but after 

echo 'deb https://deb.nodesource.com/node_0.12 jessie main' > /etc/apt/sources.list.d/nodesource.list

I still have 0.10 version...

**Comment by rvagg** [comment]
check your /etc/apt/sources.list* files to make sure you only have one source of node, do an `apt-get update && apt-get upgrade -y` to make sure you have the latest too.

it's possible that the version coming from debian is overriding the one we're supplying, you may need to edit the apt policy magic (google / stackoverflow is your friend on this one)

**Comment by rvagg** [comment]
the readme has updated manual instructions if anyone comes here looking for stretch instructions, just substitute jessie

**Comment by rvagg** [comment]
as per discussion in #103 we've aliased stretch to jessie in the setup scripts so it should be good to go now

**Comment by arthurlogilab** [comment]
Stretch is almost out (next week), do you have any plans to have a stretch repo ? (should I file a new ticket?)

**Comment by chrislea** [comment]
We'll build releases specifically for stretch once it's officially out.

**Comment by yurikoles** [comment]
@chrislea now?
