### ISSUE TITLE
Fedora 31 not supported

### ISSUE THREAD

**Issue by ukulanne** [nodesource/distributions#942]
> 
> ## Installing the NodeSource Node.js 12.x repo...
> 
> 
> ## Inspecting system...
> 
> + rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
> + uname -m
> 
> ## Confirming "fc31-x86_64" is supported...
> 
> + curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_12.x/fc/31/x86_64/nodesource-release-fc31-1.noarch.rpm'
> 
> ## Your distribution, identified as "fedora-release-common-31-1.noarch", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
>

**Comment by o-alquimista** [comment]
I tried version 13. Same result.

**Comment by KBeDeveloper** [comment]
Did you tried the installation with DNF? (There should be a NodeJS 12 repo by default)

BTW, I tried with version 13 too on my Fedora 31, getting the same result.

**Comment by Sinihopea** [comment]
> Did you tried the installation with DNF? (There should be a NodeJS 12 repo by default):
> 
> `$ sudo dnf install nodejs`
> 
> BTW, I tried with version 13 too on my Fedora 31, getting the same result.

Please, don't do that. Instead do:
`$ sudo dnf module install nodejs:12`

We now have package streams as a feature in both RHEL and Fedora. This is especially important when dealing with programs such as Node.js and such. See:

https://docs.fedoraproject.org/en-US/modularity/using-modules/
https://developers.redhat.com/blog/2018/11/15/rhel8-introducing-appstreams/

**Comment by timofey-retailnext** [comment]
Same answer for nodejs 1.10.x for FC31 : "please install native package via dnf" ?

**Comment by gtirloni** [comment]
If people wanted the Fedora-provided Node.js package, they wouldn't be asking how to install the NodeSource-provided Node.js package.

NodeSource needs to build the packages for Fedora 31 and make them available.

**Comment by igsu** [comment]
@ukulanne support added for Fedora 31: https://github.com/nodesource/distributions#enterprise-linux-based-distributions

Thanks for your patient!

Closing this now
