### ISSUE TITLE
NodeSource shutdown: Will these repositories actively maintained?

### ISSUE THREAD

**Issue by phanect** [nodesource/distributions#944]
Please forgive me for posting a question as an issue.

I hear NodeSource has closed their business.
I concern if these repository will continue to be maintained.

I confirmed (former?) NodeSource employee @edsadr's commit on Oct 23, so it seems still maintained for now, but I wonder if it continues.

If it will no-longer be maintained, I think announcement is needed on Readme. Some users might continues to use old vulnerable version without noticing that this repository stop maintenance.

**Comment by Gioyik** [comment]
Hi @phanect,

We published an post to the public with more information about NodeSource and the latest news. You can find it here:

https://nodesource.com/blog/what-happened-to-NodeSource

TL;DR: Is NodeSource shutting down? No

Hope this makes everything clear

**Comment by phanect** [comment]
Thanks @Gioyik.
I missed that blog post.

It seems hard situation for NodeSource, but I'm glad to hear that NodeSource is still alive.
