### ISSUE TITLE
Can't install node in centos7.

### ISSUE THREAD

**Issue by saisuresh-sakthivel** [nodesource/distributions#945]
Getting the following error.

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_12.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

**Comment by igsu** [comment]
Duplicated #943
