### ISSUE TITLE
Raspberry Pi4 - Node support.

### ISSUE THREAD

**Issue by theno1soco** [nodesource/distributions#946]
Installing node-v8.16.0-x64.msi message on Ubuntu 19.10 Server LTS:
"Your distribution, identified as "eoan", is not currently supported"

May I request support?

**Comment by jwatt** [comment]
[Random fly-by comment.]

It looks like eoan support (issue #918) was only added going back as far as node 10:

https://deb.nodesource.com/node_10.x/dists/eoan/Release

You may be out of luck if you can't use a more recent version of node.

It's also confusing to me that you're trying to install a Windows .msi on Linux, and it actually runs - how does that work?

**Comment by igsu** [comment]
Ubuntu 19.10 Eoan is now supported @theno1soco, it's curious that you are using a .msi file to install a package in Eoan, instead you can try:

```
# Using Ubuntu
curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
sudo apt-get install -y nodejs
```
