### ISSUE TITLE
deb.nodesource.com not reachable

### ISSUE THREAD

**Issue by bacacosta** [nodesource/distributions#947]
since last week I can't reach deb.nodesource.com. rpm.nodesource.com redirects to the project's page in github, but the deb subdomain can't be even pinged.

**Comment by Gioyik** [comment]
Hi,

Do you have a log or something we can check? We checked and the services are running without issue. Are you behind a proxy or something?

Thanks,
Gio

**Comment by bacacosta** [comment]
Hi Gioyik, I solved the problem, I had a fixed (wrong) IP address for deb.nodesource.com in my hosts file (probably added it years ago when first installing Node). All fine now, thanks for your reply.
