### ISSUE TITLE
io.js Wheezy support

### ISSUE THREAD

**Issue by strebl** [nodesource/distributions#95]
Hi guys

Did you stop supporting wheezy or did you never support io.js for wheezy?

I got following message:
```
## Confirming "wheezy" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/iojs_2.x/dists/wheezy/Release'

## Your distribution, identified as "wheezy", is not currently supported, please contact
NodeSource at https://github.com/nodesource/distributions/issues if you think this is
incorrect or would like your distribution to be considered for support
```

Trying to install io.js/node.js on a Raspberry Pi.

**Comment by rvagg** [comment]
No wheezy yet, it's a tough problem because of the toolchain involved.

FWIW you can get armv6 (pi) binaries from https://iojs.org/dist/latest/ which will work for you.

**Comment by strebl** [comment]
Thanks for your information.

The binaries working. But I need node/io.js as dependency. Therefore a repo version would be better in my mind.
A user runs my installation script which should install node/io.js.
Sure, that's no problem. But I thinks it's easier for the user if he can apt-get upgrade these packages.
I can install node.js, however the installations went fine but node.js doesn't work.

As I know, wheezy is oldstable now. Do you think you're going to support it at all?

**Comment by MathRobin** [comment]
+1

**Comment by nicokaiser** [comment]
Any news on this? Not having to unzip the binary distribution but being able to just "apt-get" iojs would be very nice (even when the Wheezy package just packages the static binary distribution from iojs.org).

**Comment by julianduque** [comment]
Related #127

**Comment by chrislea** [comment]
Node 4.1.1 is available for Wheezy now.
