### ISSUE TITLE
missing/broken repo for nodesource 1.10.x for EL8

### ISSUE THREAD

**Issue by timofey-retailnext** [nodesource/distributions#952]
https://rpm.nodesource.com/pub_10.x/el/8/x86_64/
contains no package rpms and no repodata

**Comment by ifmorrison** [comment]
I see the same issue on 
https://rpm.nodesource.com/pub_11.x/el/8/x86_64/
https://rpm.nodesource.com/pub_12.x/el/8/x86_64/
https://rpm.nodesource.com/pub_13.x/el/8/x86_64/

I am using the installer scripts provided on this page: https://github.com/nodesource/distributions#rpminstall

Error given:

> Cannot download 'https://rpm.nodesource.com/pub_13.x/el/8/x86_64': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried.
> Error: Failed to synchronize cache for repo 'nodesource'

This leaves me unable to install node, or update yum or install any package until the nodesource repo is removed from /etc/yum.repos.d.


Contents of /etc/yum.repos.d/nodesource-el8.repo are:

```
name=Node.js Packages for Enterprise Linux 8 - $basearch
baseurl=https://rpm.nodesource.com/pub_13.x/el/8/$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL

[nodesource-source]
name=Node.js for Enterprise Linux 8 - $basearch - Source
baseurl=https://rpm.nodesource.com/pub_13.x/el/8/SRPMS
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
gpgcheck=1

```

OS version is:

```
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"

```

**Comment by igsu** [comment]
@timofey-retailnext support for EL8 was added!

```
curl -sL https://rpm.nodesource.com/setup_13.x | bash -
sudo yum install -y nodejs
```

The handling of `python` in EL8 may cause issues such as Node being installed from the main repository with a wrong version, the reason is that by default this distribution doesn't make `python` available:

```
Error:
 Problem: conflicting requests
  - nothing provides /usr/bin/python needed by nodejs-13.3.0-1nodesource.x86_64.rpm
  - nothing provides python >= 2.6 needed by nodejs-13.3.0-1nodesource.x86_64.rpm
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

In the case that happens, I recommend you to follow this work around:

$ sudo yum install python2
$ sudo yumdownloader nodejs
$ sudo rpm -ivh --nodeps nodejs-13.3.0-1nodesource.x86_64.rpm

**Comment by timofey-retailnext** [comment]
Thanks for fixing repo.
I've got exactly this error when tried to install nodejs 1.10.x.
EL8 doesn't have "python" package, only versioned "python2" and "python3"
nodejs installer is not able to find "/usr/bin/python" even if I set it via "alternatives" or manually create the link.
Should this python package dependency be fixed (in rpm script) ?

**Comment by rodehoed** [comment]
I think this bugreport should be closed as the original problem has been solved. There are EL8 rpms now.

The dependency on a python package should be a new bug report tbh. But for the rest +1 for a fix for this one!

**Comment by igsu** [comment]
Original issue was fixed.
More info about RHEL 8/CentOS 8 support: #845
