### ISSUE TITLE
Fedora 25 not supported 

### ISSUE THREAD

**Issue by timofey-retailnext** [nodesource/distributions#953]
nodesource 1.10.x support Fedora range in 26..30
25 as well as 31 is not supported.

**Comment by o-alquimista** [comment]
From the [Fedora Releases](https://fedoraproject.org/wiki/Releases) page, you can see that versions older than F29 went EOL. Anyway, this is a duplicate of issue #942.

**Comment by timofey-retailnext** [comment]
Thanks for fixing it for FC31

**Comment by igsu** [comment]
@timofey-retailnext as mentioned by @o-alquimista F29 went EOL and F31 us now supported (#941) 

Closing this now, thanks for your patience!
