### ISSUE TITLE
Latest version build for Ubuntu 19.10?

### ISSUE THREAD

**Issue by xeptore** [nodesource/distributions#954]
Hi!  
Why there is no latest (v13.1.0) build for [Ubuntu 19.10 Eoan](https://deb.nodesource.com/node_13.x/dists/eoan/main/binary-amd64/Packages)? Is there any build problem with this version of Ubuntu?

**Comment by tagplus5** [comment]
@xeptore 
Change the eoan NodeSource repository to disco
```
/etc/apt/sources.list.d/nodesource.list
``` 
```
deb https://deb.nodesource.com/node_13.x disco main
deb-src https://deb.nodesource.com/node_13.x disco main
```

**Comment by xeptore** [comment]
Yes. I noticed that, but I can't reason about it.
Thank you!
Closing.
