### ISSUE TITLE
0.12 bleeding edge ?

### ISSUE THREAD

**Issue by loxK** [nodesource/distributions#96]
Hello,

As the nodejs homepage states: "Current Version: v0.12.4"

So why do you present the 0.12 version as bleeding edge with the obsolete 0.10 being stable ?

**Comment by wblankenship** [comment]
Hi @loxK,

I need a bit more context to be helpful. What wording are you referring to? Could you post a quote and its source below?

Thanks!
Will

**Comment by rvagg** [comment]
was listed as setup_dev, it's been changed now for debian/ubuntu but the rpm instructions are a work in progress
