### ISSUE TITLE
Ubuntu 19.10 eoan

### ISSUE THREAD

**Issue by khteh** [nodesource/distributions#960]
When will this distribution be supported?
```
$ curl -sL --insecure https://deb.nodesource.com/setup_13.x | sudo bash -
## Installing the NodeSource Node.js 13.x repo...


## Populating apt-get cache...

+ apt-get update
Get:1 http://packages.microsoft.com/repos/vscode stable InRelease [3,959 B]
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                
Hit:3 http://dl.google.com/linux/chrome/deb stable Release                                                                                               
Get:4 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages [152 kB]                               
Hit:6 http://ppa.launchpad.net/linuxuprising/java/ubuntu eoan InRelease                                                                          
Hit:7 http://sg.archive.ubuntu.com/ubuntu eoan InRelease                                                          
Hit:8 http://archive.canonical.com/ubuntu eoan InRelease                                    
Hit:10 http://sg.archive.ubuntu.com/ubuntu eoan-updates InRelease     
Hit:11 http://sg.archive.ubuntu.com/ubuntu eoan-backports InRelease          
Hit:9 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease
Hit:12 http://security.ubuntu.com/ubuntu eoan-security InRelease
Fetched 156 kB in 6s (24.8 kB/s)                                                                                                                                                                                  
Reading package lists... Done

## Confirming "eoan" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_13.x/dists/eoan/Release'

## Your distribution, identified as "eoan", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by JungMinu** [comment]
What OS Version are you running?

**Comment by igsu** [comment]
hi @khteh 

Ubuntu 19.10 Eoan is now supported, [Node v13.3.0](https://nodejs.org/ja/blog/release/v13.3.0/) is available.

**Comment by usmanhaider869** [comment]
## Installing the NodeSource Node.js 8.x LTS Carbon repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 https://deb.nodesource.com/node_12.x eoan InRelease
Hit:2 http://ae.archive.ubuntu.com/ubuntu eoan InRelease                                                  
Get:3 http://security.ubuntu.com/ubuntu eoan-security InRelease [97.5 kB]                                 
Get:4 http://ae.archive.ubuntu.com/ubuntu eoan-updates InRelease [97.5 kB]
Get:5 http://ae.archive.ubuntu.com/ubuntu eoan-backports InRelease [88.8 kB]
Fetched 284 kB in 2s (169 kB/s)     
Reading package lists... Done

## Confirming "eoan" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/eoan/Release'

**## Your distribution, identified as "eoan", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support**

usman@usman-Vostro-5468:~/v2.2.1118$ ^C
usman@usman-Vostro-5468:~/v2.2.1118$ nodejs -v
v13.0.0
