### ISSUE TITLE
Wrong version numbers in Eoan PPA files

### ISSUE THREAD

**Issue by jwatt** [nodesource/distributions#961]
Support for using the PPA on Eoan was added in #918 - unfortunately the version number in the Description line in the Release files (and maybe elsewhere?) is wrong. For example, in:

https://deb.nodesource.com/node_13.x/dists/eoan/Release

Instead of saying "for the Node.JS 12.x Branch" it should say "for the Node.JS 13.x Branch".

@JungMinu can you maybe take a look?

**Comment by igsu** [comment]
It is fixed now @jwatt, thanks for pointing this out!
