### ISSUE TITLE
Installation instructions for debian causes permisssion denied error

### ISSUE THREAD

**Issue by surasshu0x0** [nodesource/distributions#964]
There is permission denied error because the instruction doesn't explicitly say to do `sudo bash -` .  I think this causes confusion for newcomers

**Comment by xCykrix** [comment]
The installation instructions state above the command that you copy and pasted to use root. Executing as a non-root user will require invoking the additional `sudo bash -`

There is a low amount of issues that I can see which involve permission issues of misunderstanding the command requirements.

**Comment by surasshu0x0** [comment]
Alright got you. Thanks. Just thought explicit commands would be best
