### ISSUE TITLE
Support for Linux Mint Tina

### ISSUE THREAD

**Issue by richardarowe** [nodesource/distributions#967]
Will you please add support for Linux Mint Tina? Thank you. Richard

**Comment by thetomcoffee** [comment]
I second that. Please add support for Linux Mint 19.2 Tina. Thank you.

**Comment by danielpk74** [comment]
Hi, please add support for Linux Mint Tina. Thanks in advance.

**Comment by ed36cuir** [comment]
Tina is worth supporting, come on guys!

**Comment by smwelisson** [comment]
up

**Comment by Farid212** [comment]
up

**Comment by igsu** [comment]
Duplicated #878 
Linux Mint 19.2 Tina has support now!
