### ISSUE TITLE
Node8 on Debian 10?

### ISSUE THREAD

**Issue by rover000** [nodesource/distributions#968]
Hey, I have a Debian 10.2 no DE machine and I need to install Node8 to get MineOS working. Problem is that I'm pretty sure it won't work. I already had Debian 10.1 installed two times and it didn't work. 

these are the commands I used:

`curl -sL https://deb.nodesource.com/setup_8.x | bash -
apt-get -y install nodejs`

node --version and I got 10.5. blah blah blah.

I got the commands from the official mineos wiki.

https://minecraft.codeemo.com/mineoswiki/index.php?title=MineOS-node_(apt-get)

If anyone knows a workaround to get node8 on Debian, please share your fix with me :(

I'm decently familiar with the Linux environment but I don't think I'm great at troubleshooting lol.

Have a great day!

**Comment by xCykrix** [comment]
If you have installed higher versions of NodeJS in the past, you may have to remove them from your APT Sources `/etc/apt/sources.list.d/nodesource.list` and completely uninstall NodeJS before using those commands to install Node 8, as higher versions available will take priority.

#### Logged in as *ROOT* Shell
`apt remove nodejs && apt autoremove`
`curl -sL https://deb.nodesource.com/setup_8.x | bash -`
`apt install -y nodejs`
