### ISSUE TITLE
Update io.js to v 2.3.0

### ISSUE THREAD

**Issue by buschtoens** [nodesource/distributions#97]
As far as I can see, io.js 2.3.0 was released, but not published to the ppa. At least I don't get an update on Ubuntu Vivid Vervet. Is this intentional?

Thanks!

**Comment by chrislea** [comment]
It's definitely in there:

https://deb.nodesource.com/iojs_2.x/dists/vivid/main/binary-amd64/Packages

What version do you currently have installed?

**Comment by buschtoens** [comment]
Sorry, seems like `apt-get` messed up a bit. Rerunning the setup script fixed everything.

Thanks!
