### ISSUE TITLE
Add support for elementary OS 5.1 "Hera"

### ISSUE THREAD

**Issue by drom98** [nodesource/distributions#975]
Add support for the new elementary OS update. It is still based on Ubuntu 18.04.

**Comment by fajaryoedha** [comment]
## Confirming "hera" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_10.x/dists/hera/Release'

## Your distribution, identified as "hera", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by fajaryoedha** [comment]
what should i do?

**Comment by justvamp** [comment]
@fajaryoedha 
The workaround is to add a new line
`check_alt "elementaryOS"  "hera"     "Ubuntu" "bionic"`
after this one:
`check_alt "elementaryOS"  "juno"     "Ubuntu" "bionic"`
in the downloaded file `https://deb.nodesource.com/setup_10.x` and then run it locally.

**Comment by muhjamie** [comment]
How do I run it locally?

**Comment by iyashpal** [comment]
I am getting this one.

```
## Installing the NodeSource Node.js 13.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://ppa.launchpad.net/elementary-os/stable/ubuntu bionic InRelease                                                           
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                                          
Hit:3 http://packages.elementary.io/appcenter bionic InRelease                                                                        
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                                                          
Hit:5 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease                                                                     
Hit:6 http://in.archive.ubuntu.com/ubuntu bionic InRelease                                                                            
Hit:7 http://in.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                    
Hit:8 http://dl.google.com/linux/chrome/deb stable Release                                                                            
Hit:9 http://in.archive.ubuntu.com/ubuntu bionic-backports InRelease                                     
Hit:11 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu bionic InRelease                         
Fetched 88.7 kB in 3s (34.3 kB/s)                               
Reading package lists... Done

## Confirming "hera" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_13.x/dists/hera/Release'

## Your distribution, identified as "hera", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by Lukaszz10** [comment]
> How do I run it locally?

Maybe just: `chmod +x setup_13.x && sudo ./setup_13.x`

**Comment by Adjilino** [comment]
> > How do I run it locally?
> 
> Just run like this: `chmod +x setup_13.x && sudo ./setup_13.x`
> 
> Worked like a charm, thanks @justvamp
> 
> ****EDIT****
> 
> So, I've made this little script to update it automagically, it's really simple, but it may help someone, so here it is (it's as txt because github doesn't accept .sh, but just rename and run as sudo): [nodeSourceElementaryHera.txt](https://github.com/nodesource/distributions/files/3960745/nodeSourceElementaryHera.txt)

Many thanks
After run all _.txt_ file just run command **sudo apt-get install -y nodejs**

**Comment by girishgv21iosys** [comment]
Download the latest file from Node website and follow these steps

#######INSTALLING NODE#######
`sudo tar -xJvf node-*.tar.xz -C /usr/local/lib/nodejs`
`export PATH=/usr/local/lib/nodejs/node-v12.13.1-linux-x64/bin:$PATH`

Refresh
`. ~/.profile`

`nano ~/.profile`
/******* Paste these in the opened file *******/

```
# NodeJS
export NODEJS_HOME=/usr/local/lib/nodejs/node-v12.13.1-linux-x64/bin
export PATH=$NODEJS_HOME:$PATH
```

Refresh
`. ~/.profile`

`nano ~/.bashrc`
==Paste those lines again==

**Comment by girishgv21iosys** [comment]
Download the latest file from Node website and follow these steps

#######INSTALLING NODE#######

Extracting the files into usr folder which will be automatically created on pasting these line
`sudo tar -xJvf node-*.tar.xz -C /usr/local/lib/nodejs`

Setting PATH
`export PATH=/usr/local/lib/nodejs/node-v12.13.1-linux-x64/bin:$PATH`

Opening ~/.profile file
`nano ~/.profile`

Paste these in the opened file 
```
# NodeJS
export NODEJS_HOME=/usr/local/lib/nodejs/node-v12.13.1-linux-x64/bin
export PATH=$NODEJS_HOME:$PATH
```

Refresh
`. ~/.profile`

`nano ~/.bashrc`
Paste those 3 lines again

**Comment by igsu** [comment]
hi @drom98 

Elementary OS 5.1 "Hera" is now supported, Node v13.3.0 is available.
