### ISSUE TITLE
the versions 10 and above are not getting installed on ubuntu 16.04

### ISSUE THREAD

**Issue by nishank-kesari** [nodesource/distributions#978]
I tried installing the version 12 on my ubuntu 16.04...after downloading all files and unpacking it showed that node is already in its latest version which was just 4.6 something ... i literally said what nonsense .. please help ..yeah one can say that I should update my OS...but still.

**Comment by edsadr** [comment]
hey @nishank-kesari, thanks for reaching out but as stated in the README, those versions are not compatible due dependencies  unfortunately if you need Node 10 and beyond you would need to update your distribution.

**Comment by nishank-kesari** [comment]
> hey @nishank-kesari, thanks for reaching out but as stated in the README, those versions are not compatible due dependencies unfortunately if you need Node 10 and beyond you would need to update your distribution.

![image](https://user-images.githubusercontent.com/52621025/70267580-bbcca000-17c4-11ea-8029-fc70d2cd5103.png)

but here it is not mentioned you should get it edited asap.
