### ISSUE TITLE
Linux Mint Tricia

### ISSUE THREAD

**Issue by donguty** [nodesource/distributions#979]
Your distribution, identified as "tricia", is not currently supported

**Comment by Mayccoll** [comment]
Temp fix.
Add this to the `22x` line where all the `check_alt` are.
`check_alt "Linux Mint"  "tricia" "Ubuntu" "bionic"`
It worked for me in the Linux version Mint 19.3 Beta

**Comment by analubarreto** [comment]
> Temp fix.
> Add this to the `22x` line where all the `check_alt` are.
> `check_alt "Linux Mint" "tricia" "Ubuntu" "bionic"`
> It worked for me in the Linux version Mint 19.3 Beta

What the heck is check_alt? Where do I find it? Is it a file? It's not a command, where? Please be specific, not everyone is a linux expert.

**Comment by igsu** [comment]
@donguty Linux Mint 19.3 (Tricia) is now supported, closing this now.
