### ISSUE TITLE
Update NPM to v6.13.4 

### ISSUE THREAD

**Issue by bermannoah** [nodesource/distributions#980]
Hi there -- NPM recently disclosed and patched an arbitrary path access vulnerability and recommends updating to v6.13.4 as soon as possible. Currently the latest NPM version available appears to be v6.13.1. An updated version would be much appreciated. :)

https://blog.npmjs.org/post/189618601100/binary-planting-with-the-npm-cli

**Comment by igsu** [comment]
It is now available with the latest versions. Thanks for pointing this out @bermannoah.

**Comment by bermannoah** [comment]
@igsu fantastic, thanks so much!
