### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by aberba** [nodesource/distributions#983]
[Flatpak](flatpak.org) is a next-generation technology for building and distributing desktop applications on Linux with support for all major Linux distributions. Create one app and distribute it to the entire Linux desktop market. Flatpak apps continue to be compatible with new versions of Linux distributions. 

Hundreds of Linux apps are now distributed on Flathub.org, the online flatpak store. Please, consider distributing your Node.js runtimes using flatpak too.

**Comment by igsu** [comment]
Thank you for your recommendation, however, this is not an issue. We may consider it in the future!

Closing now!
