### ISSUE TITLE
Support to Ubuntu 19.10 "eoan"

### ISSUE THREAD

**Issue by wilmargiraldo** [nodesource/distributions#986]
Please add support to latest Ubuntu release.
Thanks.

**Comment by igsu** [comment]
Hi @wilmargiraldo,

Ubuntu Eoan Ermine is currently supported:

```
igsu@xxxxxxxxxxx:~$ nodejs -v
v13.5.0
igsu@xxxxxxxxxxx:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```

**Comment by cirovargas** [comment]
## Confirming "eoan" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_13.x/dists/eoan/Release'

## Your distribution, identified as "eoan", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
