### ISSUE TITLE
Please add support for Linux Mint 17.2 "Rafaela"

### ISSUE THREAD

**Issue by harrytruong** [nodesource/distributions#99]
Similar to https://github.com/nodesource/distributions/issues/88 and the related fix (https://github.com/nodesource/distributions/commit/a7e0a9e6a1244fb3784562e3158d1f00e4de5ee2). Missing support for Linux Mint 17.2 "rafaela", based on Ubuntu "trusty".

---

See related PR for this.

**Comment by Cyrilovich** [comment]
Same for me !
