### ISSUE TITLE
Error on Ubuntu 19.04

### ISSUE THREAD

**Issue by ArpanKIIT2017** [nodesource/distributions#992]
sudo -E bash setup_12.x

## Populating apt-get cache...

+ apt-get update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://in.archive.ubuntu.com/ubuntu eoan InRelease                                                 
Get:3 http://security.ubuntu.com/ubuntu eoan-security InRelease [97.5 kB]                                
Ign:4 http://ppa.launchpad.net/daniel-marynicz/filemanager-actions/ubuntu eoan InRelease                 
Hit:5 http://in.archive.ubuntu.com/ubuntu eoan-updates InRelease                                         
Hit:6 http://in.archive.ubuntu.com/ubuntu eoan-backports InRelease                                       
Ign:7 https://deb.nodesource.com/node_13.0 eoan InRelease                                                
Hit:8 http://dl.google.com/linux/chrome/deb stable Release                                               
Hit:9 http://ppa.launchpad.net/ondrej/php/ubuntu eoan InRelease                                       
Hit:10 https://repo.windscribe.com/ubuntu bionic InRelease                                            
Err:12 https://deb.nodesource.com/node_13.0 eoan Release                                                 
  404  Not Found [IP: 2600:9000:21f0:2400:1f:6523:6040:93a1 443]
Err:13 http://ppa.launchpad.net/daniel-marynicz/filemanager-actions/ubuntu eoan Release
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
Reading package lists... Done
E: The repository 'https://deb.nodesource.com/node_13.0 eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/daniel-marynicz/filemanager-actions/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting

**Comment by SuperSandro2000** [comment]
The apt source is ``https://deb.nodesource.com/node_13.x``. Replace the 0 with an X.

**Comment by igsu** [comment]
@ArpanKIIT2017 Ubuntu Eoan Ermine is currently supported. As mentioned by @SuperSandro2000 you are using the wrong URL. Using `https://deb.nodesource.com/node_13.x` should solve the issue.
