### ISSUE TITLE
how to add nodejs and yarn to jailkit?

### ISSUE THREAD

**Issue by broros** [nodesource/distributions#994]
after install everything works fine except in the jailkit environment I get an error with npm

```
npm -v
node: ../deps/uv/src/unix/core.c:556: uv__close_nocheckstdio: Assertion `fd > -1' failed.
Aborted
```

this is my jailkit configuration file settings.. nano /etc/jailkit/jk_init.ini

```
[env]
comment = environment variables
executables = /usr/bin/env


[node]
comment = NodeJS
executables = /usr/bin/npm, /usr/bin/node, /usr/bin/nodejs
directories = /usr/lib/node_modules
```

**Comment by igsu** [comment]
Hi @broros, this issue is not associated with the support provided in this distributions repository.

**Comment by rudolfbyker** [comment]
Hi @broros, have you figured this out yet? It might be good to leave a link here for searchers.

**Comment by broros** [comment]
more information and setup instructions can be found here:
https://themerevel.com/essential-tips/ispconfig-add-more-applications-to-shell-user-jailkit-chroot/
