### ISSUE TITLE
Source RPM link in nodesource-el7.repo is broken

### ISSUE THREAD

**Issue by carbonin** [nodesource/distributions#998]
The nodesource-release-el7-1.noarch.rpm package provides a repo for source rpms, but the base url value (https://rpm.nodesource.com/pub_10.x/el/7/SRPMS) returns a 404.

**Comment by antaln** [comment]
Same for nodesource-release-el8-1.noarch.rpm: https://rpm.nodesource.com/pub_10.x/el/7/SRPMS does not exist.

**Comment by abregar** [comment]
Also observed same, there is no srpm for any el. 
Noticed that when looking for el6 v12.16.2 rpm build which is also not present, only 7 and 8.
Would be nice to have it built or access to srpm.

**Comment by dholth** [comment]
This is a problem because it breaks `yum-builddep <package>` where `<package>` is unrelated to Node.

```
Errors during downloading metadata for repository 'nodesource-source':
  - Status code: 404 for https://rpm.nodesource.com/pub_12.x/el/8/SRPMS/repodata/repomd.xml (IP: 104.104.244.89)
Error: Failed to download metadata for repo 'nodesource-source': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

If the SRPMS aren't going to be made available then this part of `/etc/yum.repos.d/nodesource-el8.repo` needs to be deleted.

```
[nodesource-source]
name=Node.js for Enterprise Linux 8 - $basearch - Source
baseurl=https://rpm.nodesource.com/pub_12.x/el/8/SRPMS
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
gpgcheck=1
```

**Comment by JesusPaz** [comment]
Node v10 is deprecated, we recommend using a more recent version.
